/** Movers U3 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-its-weather",
      title: "Lesson 1: It's + Weather",
      learningObjective:
        "Use It's + adjective to describe today's weather (It's sunny today).",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-its-learn",
          title: "Learn: It's Sunny / Rainy",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "It's sunny today — It is + tính từ.",
              correct: "It's sunny today.",
              wrong: ["It sunny today.", "It's a sunny today."],
              distractorNotes: ["Thiếu is", "Không dùng a trước tính từ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ it hot in summer?",
              skillTag: "grammar",
              topicTag,
              explanation: "Is it hot — câu hỏi với It.",
              correct: "Is",
              wrong: ["Are", "Does"],
              distractorNotes: ["It → Is", "Does it hot — sai"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Look outside! _____ rainy now.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's — It is rainy.",
              correct: "It's",
              wrong: ["Its", "It"],
              distractorNotes: ["Its = của nó", "Thiếu is"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh says: _____ sunny. I can play outside.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's sunny — câu trong bài đọc.",
              correct: "It's",
              wrong: ["Its", "Is"],
              distractorNotes: ["Sở hữu cách", "Thiếu It"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-its-practice",
          title: "Practice: Complete It's Sentences",
          instructions: "Fill in It's or Is it.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: [0] sunny today. | [1] it windy? | No, [2] not windy. | [3] hot in summer.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's; Is; it's; It's — khẳng định và câu hỏi.",
              template:
                "[0] sunny today. [1] it windy? No, [2] not windy. [3] hot in summer.",
              correctAnswers: ["It's", "Is", "it's", "It's"],
              acceptableAnswers: [
                ["It's", "It is"],
                ["Is", "is"],
                ["it's", "It is", "It's"],
                ["It's", "It is"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-its-check",
          title: "Check: It's Weather Challenge",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is NOT correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "It is a cloudy — không dùng a trước cloudy.",
              correct: "It is a cloudy today.",
              wrong: ["It's cloudy today.", "It isn't sunny now."],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum says: _____ very hot. Wear a hat.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's very hot — lời mẹ trong bài nghe.",
              correct: "It's",
              wrong: ["Its", "Is"],
              distractorNotes: ["Sở hữu", "Thiếu It"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best answer: Is it sunny today?",
              skillTag: "grammar",
              topicTag,
              explanation: "Yes, it is — trả lời câu hỏi Is it…?",
              correct: "Yes, it is. It's sunny and hot.",
              wrong: ["Yes, it's sunny is.", "Yes, are it sunny."],
              distractorNotes: ["Thừa is", "Sai are"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-its-apply",
          title: "Apply: Build Weather Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: It's / sunny / and / hot / today.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's sunny and hot today.",
              words: ["It's", "sunny", "and", "hot", "today."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Is / it / rainy / now?",
              skillTag: "grammar",
              topicTag,
              explanation: "Is it rainy now?",
              words: ["Is", "it", "rainy", "now?"],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-its-review",
          title: "Review: It's Weather Mix",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "It's windy so we stay inside — It's + windy.",
              correct: "It's windy so we stay inside.",
              wrong: ["It windy so we stay inside.", "It's a windy so we stay."],
              distractorNotes: ["Thiếu is", "Thừa a"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Autumn is cloudy. It _____ cool too.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's cool — mô tả thời tiết mùa thu.",
              correct: "is",
              wrong: ["are", "am"],
              distractorNotes: ["It → is", "I → am"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "_____ it cold in winter?",
              skillTag: "grammar",
              topicTag,
              explanation: "Is it cold — câu hỏi chuẩn.",
              correct: "Is",
              wrong: ["Are", "Do"],
              distractorNotes: ["It → Is", "Do it cold — sai"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-was-were",
      title: "Lesson 2: Was and Were",
      learningObjective:
        "Use was and were to talk about weather and places in the past.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-was-learn",
          title: "Learn: Was / Were",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Yesterday it _____ rainy and windy.",
              skillTag: "grammar",
              topicTag,
              explanation: "It → was — quá khứ của is.",
              correct: "was",
              wrong: ["were", "is"],
              distractorNotes: ["You/we/they", "Hiện tại"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh and Linh _____ at home yesterday.",
              skillTag: "grammar",
              topicTag,
              explanation: "They → were — quá khứ của are.",
              correct: "were",
              wrong: ["was", "is"],
              distractorNotes: ["I/he/she/it", "Hiện tại"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ it sunny yesterday?",
              skillTag: "grammar",
              topicTag,
              explanation: "Was it sunny — câu hỏi với it.",
              correct: "Was",
              wrong: ["Were", "Is"],
              distractorNotes: ["We/you/they", "Hiện tại"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "We _____ at the beach last summer.",
              skillTag: "grammar",
              topicTag,
              explanation: "We → were — trong bài nghe Linh.",
              correct: "were",
              wrong: ["was", "are"],
              distractorNotes: ["I/he/she", "Hiện tại"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-was-practice",
          title: "Practice: Complete Was / Were",
          instructions: "Fill in was or were.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Yesterday it [0] rainy. | Minh and Linh [1] at home. | It [2] cold in the morning. | We [3] happy inside.",
              skillTag: "grammar",
              topicTag,
              explanation: "was; were; was; were — it was, they were.",
              template:
                "Yesterday it [0] rainy. Minh and Linh [1] at home. It [2] cold in the morning. We [3] happy inside.",
              correctAnswers: ["was", "were", "was", "were"],
              acceptableAnswers: [
                ["was", "Was"],
                ["were", "Were"],
                ["was", "Was"],
                ["were", "Were"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-was-check",
          title: "Check: Was / Were Challenge",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "It was rainy yesterday — it + was.",
              correct: "It was rainy yesterday.",
              wrong: ["It were rainy yesterday.", "It was rain yesterday."],
              distractorNotes: ["It → was", "Rain là danh từ — cần rainy"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Summer _____ hot last year.",
              skillTag: "grammar",
              topicTag,
              explanation: "Summer (it) → was hot.",
              correct: "was",
              wrong: ["were", "is"],
              distractorNotes: ["We/they", "Hiện tại"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best answer: Were you at home yesterday?",
              skillTag: "grammar",
              topicTag,
              explanation: "Yes, we were — trả lời were.",
              correct: "Yes, we were. It was rainy.",
              wrong: ["Yes, we was.", "Yes, we were at home was."],
              distractorNotes: ["We → were", "Thừa was"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-was-apply",
          title: "Apply: Order Past Weather Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Yesterday / it / was / rainy / and / windy.",
              skillTag: "grammar",
              topicTag,
              explanation: "Yesterday it was rainy and windy.",
              words: ["Yesterday", "it", "was", "rainy", "and", "windy."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Minh / and / Linh / were / at / home.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh and Linh were at home.",
              words: ["Minh", "and", "Linh", "were", "at", "home."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-was-review",
          title: "Review: Was / Were Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "The weather _____ different yesterday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Weather (it) → was different.",
              correct: "was",
              wrong: ["were", "are"],
              distractorNotes: ["It → was", "Hiện tại"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is NOT correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "We was — sai, phải We were.",
              correct: "We was at home all day.",
              wrong: ["They were at home.", "It was windy."],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "_____ it cold in winter?",
              skillTag: "grammar",
              topicTag,
              explanation: "Was it cold — câu hỏi quá khứ (general).",
              correct: "Is",
              wrong: ["Are", "Were"],
              distractorNotes: ["It → Is (general fact)", "Were it — sai"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-weather-mixed",
      title: "Lesson 3: Mixed Weather Grammar",
      learningObjective:
        "Use It's / was / were together to compare today and yesterday.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-mixed-learn",
          title: "Learn: Today vs Yesterday",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Today it's sunny. Yesterday it _____ rainy.",
              skillTag: "grammar",
              topicTag,
              explanation: "Yesterday → was — quá khứ.",
              correct: "was",
              wrong: ["is", "were"],
              distractorNotes: ["Hiện tại", "It → was"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which pair is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "It's hot today / It was cold yesterday — hiện tại và quá khứ.",
              correct: "It's hot today. It was cold yesterday.",
              wrong: ["It hot today. It were cold.", "It's hot today. It is cold yesterday."],
              distractorNotes: ["Thiếu is/was", "Yesterday cần was"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh and Linh _____ at home yesterday. Today they are at school.",
              skillTag: "grammar",
              topicTag,
              explanation: "They → were — quá khứ.",
              correct: "were",
              wrong: ["was", "is"],
              distractorNotes: ["I/he/she", "Hiện tại"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "In spring the weather _____ warm.",
              skillTag: "grammar",
              topicTag,
              explanation: "Weather (it) → is warm — sự thật chung.",
              correct: "is",
              wrong: ["was", "were"],
              distractorNotes: ["Quá khứ cụ thể", "It → is"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-practice",
          title: "Practice: Today and Yesterday Gaps",
          instructions: "Fill in is, was, were or It's.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: [0] sunny today. | Yesterday it [1] rainy. | We [2] at home. | Today we [3] at school.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's; was; were; are — so sánh hôm nay và hôm qua.",
              template:
                "[0] sunny today. Yesterday it [1] rainy. We [2] at home. Today we [3] at school.",
              correctAnswers: ["It's", "was", "were", "are"],
              acceptableAnswers: [
                ["It's", "It is"],
                ["was", "Was"],
                ["were", "Were"],
                ["are", "Are"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-check",
          title: "Check: Mixed Grammar Challenge",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Mum says: Yes, it _____ rainy and windy. We _____ at home all day.",
              skillTag: "grammar",
              topicTag,
              explanation: "was; were — trong bài nghe với mẹ.",
              correct: "was ... were",
              wrong: ["were ... was", "is ... are"],
              distractorNotes: ["It → was", "Hiện tại"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "It's sunny today but yesterday it was cloudy.",
              correct: "It's sunny today but yesterday it was cloudy.",
              wrong: ["It's sunny today but yesterday it is cloudy.", "It sunny today but was cloudy."],
              distractorNotes: ["Yesterday cần was", "Thiếu It's"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Summer _____ hot. Last summer _____ very hot too.",
              skillTag: "grammar",
              topicTag,
              explanation: "is (general); was (last summer — past).",
              correct: "is ... was",
              wrong: ["was ... is", "were ... was"],
              distractorNotes: ["General fact → is", "Summer → is/was"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-apply",
          title: "Apply: Build Mixed Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: It's / hot / today / but / yesterday / it / was / cold.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's hot today but yesterday it was cold.",
              words: ["It's", "hot", "today", "but", "yesterday", "it", "was", "cold."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: In / winter / it / can / be / cold.",
              skillTag: "grammar",
              topicTag,
              explanation: "In winter it can be cold.",
              words: ["In", "winter", "it", "can", "be", "cold."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-review",
          title: "Review: Weather Grammar Mix",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best description of Minh's week:",
              skillTag: "grammar",
              topicTag,
              explanation: "It's sunny today. Yesterday it was rainy. We were at home.",
              correct: "It's sunny today. Yesterday it was rainy and we were at home.",
              wrong: ["It sunny today. Yesterday were rainy.", "It's sunny today. Yesterday it is rainy."],
              distractorNotes: ["Thiếu is/was", "Yesterday cần was"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh says: I love summer. It _____ hot and sunny.",
              skillTag: "grammar",
              topicTag,
              explanation: "It is hot — mô tả mùa hè nói chung.",
              correct: "is",
              wrong: ["was", "were"],
              distractorNotes: ["General present", "It → is"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "_____ Minh and Linh at the beach last summer?",
              skillTag: "grammar",
              topicTag,
              explanation: "Were they — Minh and Linh = they.",
              correct: "Were",
              wrong: ["Was", "Is"],
              distractorNotes: ["They → Were", "Hiện tại"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
