/** Movers U3 — listening lessons (3 × 5 exercises). */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptWeatherHome,
  listeningScriptLinhSeasons,
  listeningAnswerKeys,
  topicTag,
}) {
  const weatherHome = listeningScriptWeatherHome;
  const linhSeasons = listeningScriptLinhSeasons;
  const keysHome = listeningAnswerKeys.weatherHome;
  const keysLinh = listeningAnswerKeys.linhSeasons;

  return [
    {
      slug: "listening-weather-home",
      title: "Lesson 1: Weather at Home",
      learningObjective:
        "Listen to a dialogue at home and identify weather words.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-home-learn",
          title: "Learn: Weather at Home",
          instructions: "Listen to Minh and his mum. Answer the questions.",
          sortOrder: 0,
          script: weatherHome,
          answerKey: keysHome,
          questions: [
            buildMcq({
              questionText: "What's the weather like today?",
              skillTag: "listening",
              topicTag,
              explanation: "It's sunny and hot today — Minh nói.",
              correct: "Sunny and hot",
              wrong: ["Rainy and cold", "Snowy and windy"],
              distractorNotes: ["Hôm qua", "Không tuyết"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Was it sunny yesterday?",
              skillTag: "listening",
              topicTag,
              explanation: "No — it was rainy and windy.",
              correct: "No",
              wrong: ["Yes", "Not mentioned"],
              distractorNotes: ["Mưa gió", "Mẹ nói rõ"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-home-practice",
          title: "Practice: More Weather Details",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: weatherHome,
          answerKey: keysHome,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "What was the weather like yesterday?",
              skillTag: "listening",
              topicTag,
              explanation: "Rainy and windy — mẹ xác nhận.",
              correct: "Rainy and windy",
              wrong: ["Sunny and hot", "Snowy"],
              distractorNotes: ["Hôm nay", "Không tuyết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Where were they all day yesterday?",
              skillTag: "listening",
              topicTag,
              explanation: "We were at home all day.",
              correct: "At home",
              wrong: ["At the park", "At school"],
              distractorNotes: ["Trời mưa", "Sáng mới nói hôm nay"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-home-check",
          title: "Check: Weather at Home Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: weatherHome,
          answerKey: keysHome,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What should Minh wear?",
              skillTag: "listening",
              topicTag,
              explanation: "Wear a hat — trời rất nóng.",
              correct: "A hat",
              wrong: ["A coat", "Boots for snow"],
              distractorNotes: ["Trời nóng", "Không tuyết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Can Minh play outside with Linh today?",
              skillTag: "listening",
              topicTag,
              explanation: "Yes — mẹ đồng ý.",
              correct: "Yes",
              wrong: ["No", "Not mentioned"],
              distractorNotes: ["Mẹ nói yes", "Có nhắc Linh"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh loves _____ days.",
              skillTag: "listening",
              topicTag,
              explanation: "I love sunny days!",
              correct: "sunny",
              wrong: ["rainy", "snowy"],
              distractorNotes: ["Hôm qua mưa", "Không tuyết"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-home-apply",
          title: "Apply: Match Today and Yesterday",
          instructions: "Listen again. Match each day to the weather.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: weatherHome },
          questions: [
            buildMatching({
              questionText: "Match each day to the weather.",
              skillTag: "listening",
              topicTag,
              explanation: "Today sunny/hot; yesterday rainy/windy/at home.",
              pairs: [
                { left: "today", right: "sunny and hot" },
                { left: "yesterday", right: "rainy and windy" },
                { left: "yesterday", right: "at home all day" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-home-review",
          title: "Review: Weather at Home Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: weatherHome,
          answerKey: keysHome,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Mum says: It's very _____",
              skillTag: "listening",
              topicTag,
              explanation: "Very hot — wear a hat.",
              correct: "hot",
              wrong: ["cold", "snowy"],
              distractorNotes: ["Ngược", "Không tuyết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh asks: Was it _____ yesterday?",
              skillTag: "listening",
              topicTag,
              explanation: "Was it rainy yesterday?",
              correct: "rainy",
              wrong: ["sunny", "snow"],
              distractorNotes: ["Hôm nay nắng", "Không tuyết"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-linh-seasons",
      title: "Lesson 2: Linh's Favourite Season",
      learningObjective:
        "Listen for season words and favourite weather in a dialogue.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-linh-learn",
          title: "Learn: Favourite Season",
          instructions: "Listen to Minh and Linh. Answer the questions.",
          sortOrder: 0,
          script: linhSeasons,
          answerKey: keysLinh,
          questions: [
            buildMcq({
              questionText: "What is Linh's favourite season?",
              skillTag: "listening",
              topicTag,
              explanation: "I love summer — Linh nói.",
              correct: "Summer",
              wrong: ["Winter", "Autumn"],
              distractorNotes: ["Thích hè nhất", "Thích hè"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What is Minh's favourite season?",
              skillTag: "listening",
              topicTag,
              explanation: "My favourite season is spring.",
              correct: "Spring",
              wrong: ["Summer", "Winter"],
              distractorNotes: ["Linh thích hè", "Không thích đông"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-linh-practice",
          title: "Practice: Season Weather Words",
          instructions: "Listen again. Focus on weather in each season.",
          sortOrder: 1,
          script: linhSeasons,
          answerKey: keysLinh,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "Summer is _____ and sunny.",
              skillTag: "listening",
              topicTag,
              explanation: "It's hot and sunny — Linh nói về hè.",
              correct: "hot",
              wrong: ["cold", "snowy"],
              distractorNotes: ["Ngược", "Không tuyết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Autumn is cloudy and _____",
              skillTag: "listening",
              topicTag,
              explanation: "Cloudy and cool — mùa thu.",
              correct: "cool",
              wrong: ["hot", "snowy"],
              distractorNotes: ["Mùa hè", "Không tuyết"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-linh-check",
          title: "Check: Seasons Listening Details",
          instructions: "Listen to the full conversation again.",
          sortOrder: 2,
          script: linhSeasons,
          answerKey: keysLinh,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Where were they last summer?",
              skillTag: "listening",
              topicTag,
              explanation: "We were at the beach — Minh nhớ.",
              correct: "At the beach",
              wrong: ["At home", "In the snow"],
              distractorNotes: ["Hôm qua ở nhà — dialogue khác", "Không tuyết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Was it cold in winter?",
              skillTag: "listening",
              topicTag,
              explanation: "Yes, it was cold — nhưng không tuyết.",
              correct: "Yes",
              wrong: ["No", "Not mentioned"],
              distractorNotes: ["Minh nói yes", "Có nhắc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Does it snow in Hanoi?",
              skillTag: "listening",
              topicTag,
              explanation: "It doesn't snow in Hanoi.",
              correct: "No",
              wrong: ["Yes", "Sometimes"],
              distractorNotes: ["Minh nói không", "Không tuyết"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-linh-apply",
          title: "Apply: Match Season to Weather",
          instructions: "Listen again. Match seasons to weather.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: linhSeasons },
          questions: [
            buildMatching({
              questionText: "Match each season to weather from the dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Summer hot; spring warm; autumn cool/cloudy; winter cold.",
              pairs: [
                { left: "summer", right: "hot and sunny" },
                { left: "spring", right: "warm weather" },
                { left: "autumn", right: "cloudy and cool" },
                { left: "winter", right: "cold, no snow in Hanoi" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-linh-review",
          title: "Review: Linh Seasons Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: linhSeasons,
          answerKey: keysLinh,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Linh says: I love _____",
              skillTag: "listening",
              topicTag,
              explanation: "I love summer.",
              correct: "summer",
              wrong: ["winter", "snow"],
              distractorNotes: ["Thích hè", "Không tuyết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They will talk about the weather again _____",
              skillTag: "listening",
              topicTag,
              explanation: "Let's talk about the weather again tomorrow!",
              correct: "tomorrow",
              wrong: ["never", "last year"],
              distractorNotes: ["Ngược", "Quá khứ"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-weather-review",
      title: "Lesson 3: Mixed Weather Listening",
      learningObjective:
        "Identify weather and season words across two short dialogues.",
      estimatedMinutes: 22,
      exercises: [
        buildListeningExercise({
          slug: "listening-mixed-learn",
          title: "Learn: Home Dialogue Reminder",
          instructions: "Listen to the weather at home dialogue again.",
          sortOrder: 0,
          script: weatherHome,
          answerKey: keysHome,
          questions: [
            buildMcq({
              questionText: "Who talks about yesterday's weather?",
              skillTag: "listening",
              topicTag,
              explanation: "Mum — Yes, it was rainy and windy.",
              correct: "Mum",
              wrong: ["Linh", "The teacher"],
              distractorNotes: ["Dialogue khác", "Không có"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Today it's _____ and hot.",
              skillTag: "listening",
              topicTag,
              explanation: "Sunny and hot — Minh nói.",
              correct: "sunny",
              wrong: ["rainy", "snowy"],
              distractorNotes: ["Hôm qua", "Không tuyết"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-practice",
          title: "Practice: Seasons Dialogue Reminder",
          instructions: "Listen to Linh's favourite season dialogue again.",
          sortOrder: 1,
          script: linhSeasons,
          answerKey: keysLinh,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Which season word does Linh say first?",
              skillTag: "listening",
              topicTag,
              explanation: "I love summer — hè đầu tiên.",
              correct: "summer",
              wrong: ["winter", "autumn"],
              distractorNotes: ["Sau mới nhắc", "Sau mới nhắc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh's favourite season is _____",
              skillTag: "listening",
              topicTag,
              explanation: "Spring — weather is warm.",
              correct: "spring",
              wrong: ["summer", "winter"],
              distractorNotes: ["Linh thích hè", "Không thích đông nhất"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-check",
          title: "Check: Mixed Weather Listening",
          instructions: "Listen to the home dialogue. Harder questions.",
          sortOrder: 2,
          script: weatherHome,
          answerKey: keysHome,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which word is in BOTH dialogues?",
              skillTag: "listening",
              topicTag,
              explanation: "Hot — sunny and hot / summer is hot.",
              correct: "hot",
              wrong: ["snow", "doctor"],
              distractorNotes: ["Chỉ dialogue Linh phủ định", "Không có"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which place is ONLY in the seasons dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "The beach — last summer.",
              correct: "The beach",
              wrong: ["The kitchen", "The school office"],
              distractorNotes: ["Dialogue home", "Không có"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-mixed-apply",
          title: "Apply: Match Dialogue to Fact",
          instructions: "Match each fact to the correct dialogue.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: linhSeasons },
          questions: [
            buildMatching({
              questionText: "Match facts to Home or Seasons dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Home: yesterday rainy; Seasons: favourite summer/spring.",
              pairs: [
                { left: "Yesterday was rainy and windy", right: "Home dialogue" },
                { left: "Linh loves summer", right: "Seasons dialogue" },
                { left: "Wear a hat — it's hot", right: "Home dialogue" },
                { left: "It doesn't snow in Hanoi", right: "Seasons dialogue" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-review",
          title: "Review: Both Dialogues Mix",
          instructions: "Listen to the seasons dialogue. Final review.",
          sortOrder: 4,
          script: linhSeasons,
          answerKey: keysLinh,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which season is warm according to Minh?",
              skillTag: "listening",
              topicTag,
              explanation: "Spring — the weather is warm.",
              correct: "spring",
              wrong: ["winter", "summer only"],
              distractorNotes: ["Đông lạnh", "Hè nóng hơn ấm"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They talk about the _____ every day and tomorrow too.",
              skillTag: "listening",
              topicTag,
              explanation: "Weather — talk about weather again tomorrow.",
              correct: "weather",
              wrong: ["homework", "medicine"],
              distractorNotes: ["Không liên quan", "Unit khác"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
