/** Movers U3 — reading lessons (3 × 5 exercises). */

export function readingLessons({
  buildMcq,
  buildGapFill,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMinhWeatherSeasons,
  topicTag,
}) {
  const passage = passageMinhWeatherSeasons;

  return [
    {
      slug: "reading-complete-sentences",
      title: "Lesson 1: Complete Sentences",
      learningObjective:
        "Read a short text and complete sentences about weather today vs yesterday.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-complete-learn",
          title: "Learn: Read About the Weather",
          instructions: "Read the passage. Answer the questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What is the weather like today?",
              skillTag: "reading",
              topicTag,
              explanation: "It's sunny and hot today — đoạn đầu bài đọc.",
              correct: "Sunny and hot",
              wrong: ["Rainy and windy", "Cold and snowy"],
              distractorNotes: ["Hôm qua", "Không có tuyết"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What was the weather like yesterday?",
              skillTag: "reading",
              topicTag,
              explanation: "It was rainy and windy — hôm qua mưa và gió.",
              correct: "Rainy and windy",
              wrong: ["Sunny and hot", "Snowy and cold"],
              distractorNotes: ["Hôm nay", "Không tuyết"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-complete-practice",
          title: "Practice: Complete the Sentence",
          instructions: "Read again. Choose the best ending for each sentence.",
          sortOrder: 1,
          passage,
          difficulty: 0.25,
          questions: [
            buildMcq({
              questionText: "Minh says: It's sunny today. I can _____",
              skillTag: "reading",
              topicTag,
              explanation: "Play outside with Linh — trong bài đọc.",
              correct: "play outside with Linh",
              wrong: ["go swimming in the snow", "stay inside all day"],
              distractorNotes: ["Không tuyết", "Hôm nay nắng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Yesterday Minh and Linh were _____",
              skillTag: "reading",
              topicTag,
              explanation: "At home — không chơi công viên.",
              correct: "at home",
              wrong: ["at the beach", "at school playing outside"],
              distractorNotes: ["Mùa hè bãi biển", "Trời mưa"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-complete-check",
          title: "Check: Complete Sentences Challenge",
          instructions: "Read carefully. Complete the idea.",
          sortOrder: 2,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Complete: Today the weather is _____ and _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Sunny and hot — mô tả hôm nay.",
              correct: "sunny ... hot",
              wrong: ["rainy ... cold", "cloudy ... snowy"],
              distractorNotes: ["Hôm qua", "Không tuyết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Complete: They couldn't play in the _____",
              skillTag: "reading",
              topicTag,
              explanation: "Park — không chơi công viên vì mưa.",
              correct: "park",
              wrong: ["hospital", "kitchen"],
              distractorNotes: ["Không trong bài", "Không trong bài"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Complete: Yesterday the weather was _____",
              skillTag: "reading",
              topicTag,
              explanation: "Different — hôm qua khác hôm nay.",
              correct: "different",
              wrong: ["the same", "snowy"],
              distractorNotes: ["Ngược nghĩa", "Không tuyết"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-complete-apply",
          title: "Apply: Fill Gaps from the Text",
          instructions: "Use the passage. Fill in the missing words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: Today it's [0] and [1]. | Yesterday it was [2] and [3]. | They were at [4].",
              skillTag: "reading",
              topicTag,
              explanation: "sunny; hot; rainy; windy; home — chi tiết từ bài đọc.",
              template:
                "Today it's [0] and [1]. Yesterday it was [2] and [3]. They were at [4].",
              correctAnswers: ["sunny", "hot", "rainy", "windy", "home"],
              acceptableAnswers: [
                ["sunny", "Sunny"],
                ["hot", "Hot"],
                ["rainy", "Rainy"],
                ["windy", "Windy"],
                ["home", "Home"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-complete-review",
          title: "Review: Sentence Completion Mix",
          instructions: "Read the passage one more time. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Where does Minh live?",
              skillTag: "reading",
              topicTag,
              explanation: "Hanoi — with his mum.",
              correct: "Hanoi",
              wrong: ["London", "Ho Chi Minh City"],
              distractorNotes: ["Không trong bài", "Sai thành phố"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who can Minh play with outside today?",
              skillTag: "reading",
              topicTag,
              explanation: "Linh — his friend.",
              correct: "Linh",
              wrong: ["His mum only", "The doctor"],
              distractorNotes: ["Mẹ ở nhà", "Không trong bài"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-seasons-text",
      title: "Lesson 2: Seasons in the Text",
      learningObjective:
        "Find information about the four seasons in a short reading text.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-seasons-learn",
          title: "Learn: Four Seasons in Vietnam",
          instructions: "Read the passage. Find season information.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "Which season is hot and sometimes rainy?",
              skillTag: "reading",
              topicTag,
              explanation: "Summer — mùa hè nóng, đôi khi mưa.",
              correct: "Summer",
              wrong: ["Winter", "Spring"],
              distractorNotes: ["Đông lạnh", "Xuân ấm"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which season is cloudy and cool?",
              skillTag: "reading",
              topicTag,
              explanation: "Autumn — mùa thu nhiều mây, mát.",
              correct: "Autumn",
              wrong: ["Summer", "Spring"],
              distractorNotes: ["Hè nóng", "Xuân ấm"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-seasons-practice",
          title: "Practice: Season Details",
          instructions: "Read again. Choose the correct statement.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "In spring the weather is warm.",
              skillTag: "reading",
              topicTag,
              explanation: "Mum says this — đúng.",
              correct: "True",
              wrong: ["False", "Not in the text"],
              distractorNotes: ["Có trong bài", "Có trong bài"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "It snows in Hanoi in winter.",
              skillTag: "reading",
              topicTag,
              explanation: "It doesn't snow in Hanoi — sai.",
              correct: "False",
              wrong: ["True", "Not in the text"],
              distractorNotes: ["Bài nói không tuyết", "Có nhắc đến"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-seasons-check",
          title: "Check: Seasons Detail Search",
          instructions: "Find the answers in the text.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Who loves summer best?",
              skillTag: "reading",
              topicTag,
              explanation: "Linh loves summer — thích bơi.",
              correct: "Linh",
              wrong: ["Minh", "Mum"],
              distractorNotes: ["Minh thích spring", "Mẹ kể về mùa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh likes spring because the flowers _____",
              skillTag: "reading",
              topicTag,
              explanation: "Bloom — hoa nở mùa xuân.",
              correct: "bloom",
              wrong: ["fall", "freeze"],
              distractorNotes: ["Mùa thu", "Không trong bài"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Winter can be _____ in Vietnam.",
              skillTag: "reading",
              topicTag,
              explanation: "Cold — mùa đông có thể lạnh.",
              correct: "cold",
              wrong: ["hot", "snowy always"],
              distractorNotes: ["Mùa hè", "Không tuyết Hà Nội"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-seasons-apply",
          title: "Apply: Complete Season Facts",
          instructions: "Fill in the gaps using words from the passage.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: In [0] the weather is warm. | [1] is hot. | [2] is cloudy and cool. | [3] can be cold.",
              skillTag: "reading",
              topicTag,
              explanation: "spring; Summer; Autumn; Winter — mẹ kể bốn mùa.",
              template:
                "In [0] the weather is warm. [1] is hot. [2] is cloudy and cool. [3] can be cold.",
              correctAnswers: ["spring", "Summer", "Autumn", "Winter"],
              acceptableAnswers: [
                ["spring", "Spring"],
                ["Summer", "summer"],
                ["Autumn", "autumn"],
                ["Winter", "winter"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-seasons-review",
          title: "Review: Seasons Text Mix",
          instructions: "Find the answers in the text again.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Minh's favourite season is _____",
              skillTag: "reading",
              topicTag,
              explanation: "Spring — when flowers bloom.",
              correct: "spring",
              wrong: ["summer", "winter"],
              distractorNotes: ["Linh thích hè", "Đông lạnh"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Why does Linh love summer?",
              skillTag: "reading",
              topicTag,
              explanation: "She likes swimming — thích bơi.",
              correct: "She likes swimming",
              wrong: ["She likes snow", "Flowers bloom"],
              distractorNotes: ["Không tuyết", "Mùa xuân"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-gap-detail",
      title: "Lesson 3: Gap-Fill and Details",
      learningObjective:
        "Complete gaps and find detailed information in a weather text.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-gap-learn",
          title: "Learn: Find Key Details",
          instructions: "Read the passage. Answer detail questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "How old is Minh?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh is nine — đoạn đầu.",
              correct: "Nine",
              wrong: ["Seven", "Ten"],
              distractorNotes: ["Không đúng", "Không đúng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Who tells Minh about the four seasons?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh's mum — mẹ kể về bốn mùa.",
              correct: "His mum",
              wrong: ["Linh", "His teacher"],
              distractorNotes: ["Bạn gái", "Không trong bài"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-gap-practice",
          title: "Practice: Match Text Details",
          instructions: "Match each detail to the correct person or time.",
          exerciseType: "matching",
          sortOrder: 1,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each detail from the text.",
              skillTag: "reading",
              topicTag,
              explanation: "Today sunny; yesterday rainy; Linh summer; Minh spring.",
              pairs: [
                { left: "today", right: "sunny and hot" },
                { left: "yesterday", right: "rainy and windy" },
                { left: "Linh", right: "loves summer" },
                { left: "Minh", right: "likes spring" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-gap-check",
          title: "Check: Detail and Gap Challenge",
          instructions: "Read carefully. Choose the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Which sentence is NOT true?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh plays in park yesterday — sai, hôm qua ở nhà.",
              correct: "Yesterday Minh and Linh played in the park.",
              wrong: [
                "Today it's sunny.",
                "It doesn't snow in Hanoi.",
              ],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh and Linh talk about the weather _____",
              skillTag: "reading",
              topicTag,
              explanation: "Every day — cuối bài đọc.",
              correct: "every day",
              wrong: ["never", "only in winter"],
              distractorNotes: ["Ngược nghĩa", "Cả năm"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Complete: It doesn't _____ in Hanoi in winter.",
              skillTag: "reading",
              topicTag,
              explanation: "Snow — không có tuyết.",
              correct: "snow",
              wrong: ["rain", "shine"],
              distractorNotes: ["Vẫn có thể mưa", "Không phù hợp"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-gap-apply",
          title: "Apply: Full Gap-Fill from Text",
          instructions: "Fill in all gaps using the passage.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh lives in [0]. | Today it's [1] and hot. | Yesterday it was [2] and windy. | Linh loves [3] best.",
              skillTag: "reading",
              topicTag,
              explanation: "Hanoi; sunny; rainy; summer — chi tiết chính.",
              template:
                "Minh lives in [0]. Today it's [1] and hot. Yesterday it was [2] and windy. Linh loves [3] best.",
              correctAnswers: ["Hanoi", "sunny", "rainy", "summer"],
              acceptableAnswers: [
                ["Hanoi", "hanoi"],
                ["sunny", "Sunny"],
                ["rainy", "Rainy"],
                ["summer", "Summer"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-gap-review",
          title: "Review: Gap-Fill Mix",
          instructions: "Choose the best word to complete each sentence from the text.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          content: { passage },
          questions: [
            buildMcq({
              questionText: "The weather was _____ yesterday.",
              skillTag: "reading",
              topicTag,
              explanation: "Different — khác hôm nay.",
              correct: "different",
              wrong: ["the same", "snowy"],
              distractorNotes: ["Ngược", "Không tuyết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They couldn't play outside because it was _____",
              skillTag: "reading",
              topicTag,
              explanation: "Rainy and windy — hôm qua.",
              correct: "rainy and windy",
              wrong: ["sunny and hot", "snowy"],
              distractorNotes: ["Hôm nay", "Không tuyết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Every day they talk about the _____ together.",
              skillTag: "reading",
              topicTag,
              explanation: "Weather — thời tiết.",
              correct: "weather",
              wrong: ["homework", "football"],
              distractorNotes: ["Không trong bài", "Không trong bài"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
