/** Movers U3 — speaking lessons (3 × 5 exercises; only Check is AI). */

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [todayCheck, yesterdayCheck, seasonsCheck] = speakingChecks;

  return [
    {
      slug: "speaking-today-weather",
      title: "Lesson 1: Talk About Today's Weather",
      learningObjective:
        "Choose appropriate spoken phrases about today's weather.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-today-learn",
          title: "Learn: What to Say About Today",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Someone asks: What's the weather like today? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "It's sunny and hot — câu trả lời tự nhiên.",
              correct: "It's sunny and hot today.",
              wrong: ["Sunny hot it is today.", "It are sunny today."],
              distractorNotes: ["Sai trật tự", "It → is"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best answer: Is it windy today?",
              skillTag: "speaking",
              topicTag,
              explanation: "No, it isn't. It's sunny — trả lời đầy đủ.",
              correct: "No, it isn't. It's sunny and hot.",
              wrong: ["No, it not windy sunny.", "No, isn't it windy sunny."],
              distractorNotes: ["Thiếu is", "Sai trật tự"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-today-practice",
          title: "Practice: Today Weather Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Mum says: Look outside! Best reply:",
              skillTag: "speaking",
              topicTag,
              explanation: "Wow! It's sunny and hot — phản ứng tự nhiên.",
              correct: "Wow! It's sunny and hot today.",
              wrong: ["Wow sunny hot it.", "It sunny wow hot."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Can I play outside? Best answer from Mum:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, but wear a hat — lời mẹ trong bài nghe.",
              correct: "Yes, but wear a hat. It's very hot.",
              wrong: ["Yes wear hat hot very.", "Yes you can hat wear hot."],
              distractorNotes: ["Không thành câu", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        todayCheck,
        buildExercise({
          slug: "speaking-today-apply",
          title: "Apply: Quick Today Weather Replies",
          instructions: "Choose the best short spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Friend asks about today. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "It's sunny — có thể chơi ngoài.",
              correct: "It's sunny today. We can play in the park!",
              wrong: ["Sunny play park today.", "Today sunny we park play."],
              distractorNotes: ["Quá ngắn", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-today-review",
          title: "Review: Today Weather Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Describe today's weather. Best phrase:",
              skillTag: "speaking",
              topicTag,
              explanation: "It's sunny and hot — mô tả hôm nay.",
              correct: "It's sunny and hot. The weather is great!",
              wrong: ["Hot sunny weather great is.", "It are sunny hot great."],
              distractorNotes: ["Sai trật tự", "It → is"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say you love sunny days. Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "I love sunny days — như Minh nói.",
              correct: "I love sunny days! I can play outside.",
              wrong: ["Sunny days love I outside.", "Love sunny I days play."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-yesterday-weather",
      title: "Lesson 2: Talk About Yesterday",
      learningObjective:
        "Use was and were in short spoken answers about past weather.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-yesterday-learn",
          title: "Learn: Say Was / Were",
          instructions: "Choose the best spoken answer about yesterday.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "What was the weather like yesterday? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "It was rainy and windy — quá khứ.",
              correct: "It was rainy and windy yesterday.",
              wrong: ["It were rainy windy yesterday.", "Yesterday it is rainy windy."],
              distractorNotes: ["It → was", "Yesterday cần was"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Where were you yesterday? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "We were at home all day — trong bài nghe.",
              correct: "We were at home all day.",
              wrong: ["We was at home all day.", "At home we were all day was."],
              distractorNotes: ["We → were", "Thừa was"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-yesterday-practice",
          title: "Practice: Past Weather Replies",
          instructions: "Choose the correct spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Was it sunny yesterday? Best reply:",
              skillTag: "speaking",
              topicTag,
              explanation: "No, it was rainy and windy.",
              correct: "No, it was rainy and windy. We were at home.",
              wrong: ["No, it were rainy windy.", "No, was it rainy we home."],
              distractorNotes: ["It → was", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum explains yesterday. Best thing to repeat:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, it was rainy and windy — nhắc lại mẹ.",
              correct: "Yes, yesterday it was rainy and windy.",
              wrong: ["Yes yesterday were rainy it.", "Yes it rainy was windy yesterday were."],
              distractorNotes: ["Sai trật tự", "Sai was/were"],
              difficultyRating: 2,
            }),
          ],
        }),
        yesterdayCheck,
        buildExercise({
          slug: "speaking-yesterday-apply",
          title: "Apply: Compare Today and Yesterday",
          instructions: "Pick the most natural spoken comparison.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best comparison:",
              skillTag: "speaking",
              topicTag,
              explanation: "It's sunny today but yesterday it was rainy.",
              correct: "It's sunny today, but yesterday it was rainy and windy.",
              wrong: ["Sunny today rainy yesterday it was is.", "Today sunny yesterday was rainy it."],
              distractorNotes: ["Sai thì", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-yesterday-review",
          title: "Review: Yesterday Speaking Quiz",
          instructions: "Choose the best spoken answer using was/were.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Could you play outside yesterday? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "No — it was rainy. We were at home.",
              correct: "No. It was rainy and we were at home.",
              wrong: ["No rainy was we home.", "No it were rainy we was home."],
              distractorNotes: ["Sai trật tự", "Sai was/were"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Ask about yesterday's weather. Best question:",
              skillTag: "speaking",
              topicTag,
              explanation: "Was it rainy yesterday? — câu hỏi chuẩn.",
              correct: "Was it rainy yesterday?",
              wrong: ["It was rainy yesterday?", "Were it rainy yesterday?"],
              distractorNotes: ["Thiếu Was đầu", "It → Was"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-seasons",
      title: "Lesson 3: Talk About Seasons",
      learningObjective:
        "Describe favourite seasons and weather in short spoken answers.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-seasons-learn",
          title: "Learn: Season Phrases",
          instructions: "Choose the best thing to say about seasons.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "What's your favourite season? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "My favourite season is spring — câu hỏi phổ biến.",
              correct: "My favourite season is spring. The weather is warm.",
              wrong: ["Favourite spring season my warm.", "My favourite is spring warm weather."],
              distractorNotes: ["Sai trật tự", "Thiếu season"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What is summer like? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Summer is hot and sunny — Linh nói.",
              correct: "Summer is hot and sunny. I love swimming!",
              wrong: ["Summer hot sunny swimming love.", "Hot sunny is summer swimming."],
              distractorNotes: ["Không thành câu", "Sai trật tự"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-seasons-practice",
          title: "Practice: Four Seasons Replies",
          instructions: "Choose the best spoken answers about seasons.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Does it snow in Hanoi? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "No, it doesn't snow in Hanoi — Minh nói.",
              correct: "No, it doesn't snow in Hanoi in winter.",
              wrong: ["No snow doesn't it Hanoi.", "No it snows not Hanoi winter."],
              distractorNotes: ["Sai trật tự", "Sai phủ định"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What season is cloudy and cool? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Autumn is cloudy and cool — Linh nói.",
              correct: "Autumn is cloudy and cool.",
              wrong: ["Autumn cloudy cool is and.", "Cloudy cool autumn is."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        seasonsCheck,
        buildExercise({
          slug: "speaking-seasons-apply",
          title: "Apply: Tell About Favourite Season",
          instructions: "Choose the best short spoken description.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best short story about Linh and seasons:",
              skillTag: "speaking",
              topicTag,
              explanation: "Linh loves summer → hot → swimming — thứ tự rõ.",
              correct:
                "Linh loves summer best because it's hot and sunny. She likes swimming at the beach.",
              wrong: ["Linh summer hot swimming loves beach.", "Summer Linh loves hot beach swimming sunny."],
              distractorNotes: ["Không thành câu", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-seasons-review",
          title: "Review: Seasons Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Talk about all four seasons. Best opening:",
              skillTag: "speaking",
              topicTag,
              explanation: "There are four seasons — spring, summer, autumn, winter.",
              correct: "There are four seasons: spring, summer, autumn and winter.",
              wrong: ["Four seasons spring summer autumn winter there are.", "Seasons four is spring summer."],
              distractorNotes: ["Sai trật tự", "Không thành câu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What do Minh and Linh talk about every day?",
              skillTag: "speaking",
              topicTag,
              explanation: "The weather — cuối bài đọc.",
              correct: "They talk about the weather every day.",
              wrong: ["They talk weather every about day.", "Talk they weather day every."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
