/** Movers U3 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-weather-words",
      title: "Lesson 1: Weather Words",
      learningObjective:
        "Recognise and use sunny, rainy, windy and cloudy in short weather sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-weather-learn",
          title: "Learn: Weather Adjectives",
          instructions: "Read each clue. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "When the sun is shining, it is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Sunny (nắng) — có ánh nắng mặt trời.",
              correct: "sunny",
              wrong: ["rainy", "cloudy"],
              distractorNotes: ["Có mưa", "Nhiều mây nhưng không nhất thiết nắng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When water falls from the sky, it is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rainy (có mưa) — trời mưa.",
              correct: "rainy",
              wrong: ["windy", "sunny"],
              distractorNotes: ["Có gió", "Có nắng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When the air moves a lot, it is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Windy (có gió) — gió thổi mạnh.",
              correct: "windy",
              wrong: ["cloudy", "hot"],
              distractorNotes: ["Nhiều mây", "Nóng — khác nghĩa"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When there are many grey clouds, it is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cloudy (nhiều mây) — bầu trời đầy mây.",
              correct: "cloudy",
              wrong: ["sunny", "snow"],
              distractorNotes: ["Trời nắng", "Tuyết — danh từ"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-weather-practice",
          title: "Practice: Match Weather Words",
          instructions: "Match each word to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the weather words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mỗi từ mô tả một kiểu thời tiết khác nhau.",
              pairs: [
                { left: "sunny", right: "the sun is shining" },
                { left: "rainy", right: "rain is falling from the sky" },
                { left: "windy", right: "the air is moving strongly" },
                { left: "cloudy", right: "there are many clouds in the sky" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-weather-check",
          title: "Check: Weather Words Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "It's _____ today. Minh can play outside.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Sunny — trời nắng, chơi ngoài trời được.",
              correct: "sunny",
              wrong: ["rainy", "windy"],
              distractorNotes: ["Mưa thì khó chơi", "Gió mạnh"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Yesterday it was _____ and _____. We stayed inside.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rainy and windy — mưa và gió, ở trong nhà.",
              correct: "rainy ... windy",
              wrong: ["sunny ... hot", "cloudy ... snow"],
              distractorNotes: ["Nắng nóng — chơi ngoài được", "Tuyết không phù hợp Hà Nội"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Autumn days are often _____ in Hanoi.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cloudy — mùa thu thường nhiều mây.",
              correct: "cloudy",
              wrong: ["snow", "sunny only"],
              distractorNotes: ["Không có tuyết", "Thu không chỉ nắng"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-weather-apply",
          title: "Apply: Complete Weather Sentences",
          instructions: "Fill in each gap with the correct weather word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Today it's [0]. | Yesterday it was [1]. | It was [2] too, so we stayed home.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "sunny; rainy; windy — hôm nay nắng, hôm qua mưa và gió.",
              template:
                "Today it's [0]. Yesterday it was [1]. It was [2] too, so we stayed home.",
              correctAnswers: ["sunny", "rainy", "windy"],
              acceptableAnswers: [
                ["sunny", "Sunny"],
                ["rainy", "Rainy"],
                ["windy", "Windy"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-weather-review",
          title: "Review: Weather Words Mix",
          instructions: "Mixed review from this lesson. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Minh says: It's _____ today. I can play with Linh.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Sunny — trong bài đọc hôm nay trời nắng.",
              correct: "sunny",
              wrong: ["rainy", "cold"],
              distractorNotes: ["Hôm qua mới mưa", "Nóng hơn là lạnh hôm nay"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word means 'rain is falling'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rainy — có mưa.",
              correct: "rainy",
              wrong: ["windy", "cloudy"],
              distractorNotes: ["Có gió", "Có mây — chưa chắc mưa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We couldn't play in the park. It was _____ and windy.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rainy — mưa và gió, không chơi ngoài được.",
              correct: "rainy",
              wrong: ["sunny", "hot"],
              distractorNotes: ["Nắng thì chơi được", "Nóng không phải lý do chính"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-seasons",
      title: "Lesson 2: Seasons",
      learningObjective:
        "Use spring, summer, autumn and winter to talk about the four seasons.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-seasons-learn",
          title: "Learn: Four Seasons",
          instructions: "Read each sentence. Choose the best season.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Flowers bloom. The weather is warm. This is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Spring (mùa xuân) — hoa nở, thời tiết ấm.",
              correct: "spring",
              wrong: ["winter", "summer"],
              distractorNotes: ["Mùa đông lạnh", "Mùa hè rất nóng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "It is hot and sunny. Children like swimming. This is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Summer (mùa hè) — nóng, đi bơi.",
              correct: "summer",
              wrong: ["autumn", "spring"],
              distractorNotes: ["Mùa thu mát", "Mùa xuân ấm nhưng không nóng nhất"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The weather is cloudy and cool. Leaves fall. This is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Autumn (mùa thu) — nhiều mây, mát mẻ.",
              correct: "autumn",
              wrong: ["summer", "spring"],
              distractorNotes: ["Mùa hè nóng", "Mùa xuân ấm"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "It can be cold. In Hanoi it doesn't snow. This is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Winter (mùa đông) — lạnh, không tuyết ở Hà Nội.",
              correct: "winter",
              wrong: ["summer", "autumn"],
              distractorNotes: ["Mùa hè nóng", "Mùa thu mát hơn đông"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-seasons-practice",
          title: "Practice: Match Seasons",
          instructions: "Match each season to its description.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the four seasons.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Spring, summer, autumn, winter — bốn mùa trong năm.",
              pairs: [
                { left: "spring", right: "warm weather, flowers bloom" },
                { left: "summer", right: "hot and sometimes rainy" },
                { left: "autumn", right: "cloudy and cool" },
                { left: "winter", right: "cold, no snow in Hanoi" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-seasons-check",
          title: "Check: Seasons Quiz",
          instructions: "Choose the best answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Linh loves _____ best because she likes swimming.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Summer — Linh thích mùa hè vì bơi.",
              correct: "summer",
              wrong: ["winter", "autumn"],
              distractorNotes: ["Đông lạnh", "Thu mát"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh likes _____ when the flowers bloom.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Spring — Minh thích mùa xuân.",
              correct: "spring",
              wrong: ["summer", "winter"],
              distractorNotes: ["Hè nóng", "Đông lạnh"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which season is cloudy and cool in Vietnam?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Autumn — mùa thu nhiều mây và mát.",
              correct: "autumn",
              wrong: ["summer", "spring"],
              distractorNotes: ["Hè nóng", "Xuân ấm"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-seasons-apply",
          title: "Apply: Complete Season Sentences",
          instructions: "Complete the sentences about seasons.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: In [0] the weather is warm. | [1] is hot. | [2] is cloudy and cool. | [3] can be cold.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "spring; Summer; Autumn; Winter — bốn mùa theo mẹ kể.",
              template:
                "In [0] the weather is warm. [1] is hot. [2] is cloudy and cool. [3] can be cold.",
              correctAnswers: ["spring", "Summer", "Autumn", "Winter"],
              acceptableAnswers: [
                ["spring", "Spring"],
                ["Summer", "summer"],
                ["Autumn", "autumn"],
                ["Winter", "winter"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-seasons-review",
          title: "Review: Seasons Mix",
          instructions: "Mixed review. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "There are _____ seasons in a year.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Four — spring, summer, autumn, winter.",
              correct: "four",
              wrong: ["three", "five"],
              distractorNotes: ["Thiếu một mùa", "Thừa mùa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which season comes after summer?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Autumn — sau hè là thu.",
              correct: "autumn",
              wrong: ["spring", "winter"],
              distractorNotes: ["Xuân trước hè", "Đông sau thu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Summer is _____ and sometimes rainy.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hot — mùa hè nóng.",
              correct: "hot",
              wrong: ["cold", "snow"],
              distractorNotes: ["Lạnh — mùa đông", "Tuyết — danh từ"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-weather-mix",
      title: "Lesson 3: Snow, Hot, Cold and Weather",
      learningObjective:
        "Use snow, hot, cold and weather in mixed weather and season contexts.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-mix-learn",
          title: "Learn: Hot, Cold, Snow and Weather",
          instructions: "Choose the word that best completes each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "It's _____ today. Minh wears a T-shirt.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hot (nóng) — mặc áo phông khi trời nóng.",
              correct: "hot",
              wrong: ["cold", "snow"],
              distractorNotes: ["Lạnh — mặc áo ấm", "Tuyết — danh từ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "It was _____ yesterday morning.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cold (lạnh) — sáng hôm qua lạnh.",
              correct: "cold",
              wrong: ["hot", "sunny"],
              distractorNotes: ["Nóng", "Nắng — khác cold"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "It doesn't _____ in Hanoi in winter.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Snow (tuyết) — Hà Nội không có tuyết.",
              correct: "snow",
              wrong: ["rain", "wind"],
              distractorNotes: ["Mưa vẫn có", "Gió — động từ khác"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh and Linh talk about the _____ every day.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Weather (thời tiết) — nói về thời tiết hàng ngày.",
              correct: "weather",
              wrong: ["season", "cloudy"],
              distractorNotes: ["Mùa — rộng hơn", "Tính từ"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mix-practice",
          title: "Practice: Match Mixed Words",
          instructions: "Match each word to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the weather vocabulary.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hot, cold, snow, weather — từ bổ sung cho unit.",
              pairs: [
                { left: "hot", right: "very warm, like summer days" },
                { left: "cold", right: "not warm, like winter mornings" },
                { left: "snow", right: "white ice that falls in very cold places" },
                { left: "weather", right: "sun, rain, wind, hot or cold outside" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mix-check",
          title: "Check: Mixed Weather Challenge",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Today it's sunny and _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hot — nắng và nóng trong bài đọc.",
              correct: "hot",
              wrong: ["snow", "cold"],
              distractorNotes: ["Không có tuyết", "Ngược với nắng nóng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "It doesn't snow in Hanoi — phủ định với snow.",
              correct: "It doesn't snow in Hanoi in winter.",
              wrong: ["It doesn't snowy in Hanoi.", "It doesn't snows in Hanoi."],
              distractorNotes: ["Snowy là tính từ", "Sai -s sau doesn't"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What's the _____ like today?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Weather — câu hỏi về thời tiết.",
              correct: "weather",
              wrong: ["season", "spring"],
              distractorNotes: ["Mùa — câu hỏi khác", "Một mùa cụ thể"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mix-apply",
          title: "Apply: Complete Mixed Sentences",
          instructions: "Fill in with hot, cold, snow or weather.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: It's [0] and sunny. | Winter can be [1]. | It doesn't [2] in Hanoi. | We talk about the [3] every day.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "hot; cold; snow; weather — tổng hợp từ bài.",
              template:
                "It's [0] and sunny. Winter can be [1]. It doesn't [2] in Hanoi. We talk about the [3] every day.",
              correctAnswers: ["hot", "cold", "snow", "weather"],
              acceptableAnswers: [
                ["hot", "Hot"],
                ["cold", "Cold"],
                ["snow", "Snow"],
                ["weather", "Weather"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mix-review",
          title: "Review: All Weather Words Mix",
          instructions: "Choose the best word from the whole unit.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Yesterday it was rainy, windy and _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cold — sáng lạnh kết hợp mưa gió.",
              correct: "cold",
              wrong: ["hot", "snow"],
              distractorNotes: ["Ngược với mưa lạnh", "Không tuyết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The _____ is sunny today but was rainy yesterday.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Weather — so sánh thời tiết hôm nay và hôm qua.",
              correct: "weather",
              wrong: ["snow", "windy"],
              distractorNotes: ["Không liên quan", "Tính từ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "In summer the weather is _____ and sometimes rainy.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hot — mùa hè nóng.",
              correct: "hot",
              wrong: ["cold", "cloudy only"],
              distractorNotes: ["Mùa đông", "Hè chủ yếu nóng"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
