/** Flyers U2 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-passive-intro",
      title: "Lesson 1: Passive Voice — Introduction",
      learningObjective:
        "Recognise and use is made and are made in simple passive sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-passive-learn",
          title: "Learn: Is Made / Are Made",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "New paper _____ from old newspapers.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is made — paper (số ít) + is made.",
              correct: "is made",
              wrong: ["are made", "is make"],
              distractorNotes: ["Paper is singular", "Need past participle made"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "New bins _____ from recycled plastic.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are made — bins (số nhiều) + are made.",
              correct: "are made",
              wrong: ["is made", "are make"],
              distractorNotes: ["Bins is plural", "Need past participle"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The report _____ by our teacher.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is written — report (số ít) + is + past participle.",
              correct: "is written",
              wrong: ["are written", "is write"],
              distractorNotes: ["Report is singular", "Need past participle"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Trees _____ near the playground.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are planted — trees (số nhiều) + are planted.",
              correct: "are planted",
              wrong: ["is planted", "are plant"],
              distractorNotes: ["Trees is plural", "Need past participle"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-passive-practice",
          title: "Practice: Complete Passive Sentences",
          instructions: "Fill in each gap with is made or are made.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Paper [0] from old newspapers. | New bins [1] from plastic. | The article [2] by Minh.",
              skillTag: "grammar",
              topicTag,
              explanation: "is made; are made; is written — bị động đơn giản.",
              template:
                "Paper [0] from old newspapers. New bins [1] from plastic. The article [2] by Minh.",
              correctAnswers: ["is made", "are made", "is written"],
              acceptableAnswers: [
                ["is made", "Is made"],
                ["are made", "Are made"],
                ["is written", "Is written", "was written", "Was written"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-passive-check",
          title: "Check: Passive Challenge",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Plastic is made into bins — is + past participle.",
              correct: "Plastic is made into new bins.",
              wrong: [
                "Plastic is make into new bins.",
                "Plastic are made into new bins.",
              ],
              distractorNotes: ["Wrong participle", "Plastic is singular"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "New paper _____ from paper pupils bring from home.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is made — paper (uncountable/singular) + is made.",
              correct: "is made",
              wrong: ["are made", "is make"],
              distractorNotes: ["Paper takes is", "Need made"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Trees are planted — plural subject + are.",
              correct: "Trees are planted near the playground.",
              wrong: [
                "Trees is planted near the playground.",
                "Trees are plant near the playground.",
              ],
              distractorNotes: ["Wrong be verb", "Wrong participle"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-passive-apply",
          title: "Apply: Build Passive Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: New bins / are / made / from / recycled / plastic.",
              skillTag: "grammar",
              topicTag,
              explanation: "New bins are made from recycled plastic.",
              words: ["New bins", "are", "made", "from", "recycled", "plastic."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Paper / is / made / from / old / newspapers.",
              skillTag: "grammar",
              topicTag,
              explanation: "Paper is made from old newspapers.",
              words: ["Paper", "is", "made", "from", "old", "newspapers."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-passive-review",
          title: "Review: Is Made / Are Made Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Glass jars _____ from recycled glass.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are made — jars (plural) + are made.",
              correct: "are made",
              wrong: ["is made", "are make"],
              distractorNotes: ["Jars is plural", "Need past participle"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh's article _____ for the school board.",
              skillTag: "grammar",
              topicTag,
              explanation: "Was written / is written — article (singular).",
              correct: "was written",
              wrong: ["were written", "was write"],
              distractorNotes: ["Article is singular", "Need past participle"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which question is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Is paper made from trees? — passive question with is.",
              correct: "Is paper made from trees?",
              wrong: [
                "Does paper made from trees?",
                "Is paper make from trees?",
              ],
              distractorNotes: ["Wrong auxiliary", "Wrong participle"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-must-mustnt",
      title: "Lesson 2: Must and Mustn't",
      learningObjective:
        "Use must and mustn't to talk about eco rules and responsibilities.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-must-learn",
          title: "Learn: Must and Mustn't",
          instructions: "Choose the correct word or sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "We _____ sort waste carefully. (important rule)",
              skillTag: "grammar",
              topicTag,
              explanation: "Must — quy tắc bắt buộc: phải phân loại rác.",
              correct: "must",
              wrong: ["mustn't", "is made"],
              distractorNotes: ["Not allowed — opposite", "Passive form"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "You _____ throw rubbish on the ground. (not allowed)",
              skillTag: "grammar",
              topicTag,
              explanation: "Mustn't — không được vứt rác xuống đất.",
              correct: "mustn't",
              wrong: ["must", "are recycled"],
              distractorNotes: ["Required — opposite", "Passive form"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "We must protect nature — must + base verb.",
              correct: "We must protect nature.",
              wrong: [
                "We must to protect nature.",
                "We must protects nature.",
              ],
              distractorNotes: ["Must + to (wrong)", "Must + -s (wrong)"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Students _____ wear gloves during cleanup.",
              skillTag: "grammar",
              topicTag,
              explanation: "Must — quy định phải đeo găng.",
              correct: "must",
              wrong: ["mustn't", "is recycled"],
              distractorNotes: ["Opposite meaning", "Passive"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-must-practice",
          title: "Practice: Complete Must/Mustn't",
          instructions: "Fill in each gap with must or mustn't.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: We [0] protect rainforests. | You [1] drop plastic in the ocean. | We [2] waste clean water.",
              skillTag: "grammar",
              topicTag,
              explanation: "must; mustn't; mustn't — quy tắc môi trường.",
              template:
                "We [0] protect rainforests. You [1] drop plastic in the ocean. We [2] waste clean water.",
              correctAnswers: ["must", "mustn't", "mustn't"],
              acceptableAnswers: [
                ["must", "Must"],
                ["mustn't", "Mustn't", "must not", "Must not"],
                ["mustn't", "Mustn't", "must not", "Must not"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-must-check",
          title: "Check: Must and Mustn't Challenge",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "You mustn't leave sharp bottles — mustn't + base verb.",
              correct: "You mustn't leave sharp bottles on the ground.",
              wrong: [
                "You mustn't to leave sharp bottles.",
                "You mustn't leaves sharp bottles.",
              ],
              distractorNotes: ["Mustn't + to", "Mustn't + -s"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh said we _____ drop plastic in the ocean.",
              skillTag: "grammar",
              topicTag,
              explanation: "Mustn't — không được vứt nhựa xuống biển.",
              correct: "mustn't",
              wrong: ["must", "is made"],
              distractorNotes: ["Opposite", "Passive"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "We must put rubbish in bins — must + base verb.",
              correct: "We must put rubbish in the right bins.",
              wrong: [
                "We must putting rubbish in bins.",
                "We must to put rubbish in bins.",
              ],
              distractorNotes: ["Must + -ing", "Must + to"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-must-apply",
          title: "Apply: Order Rule Sentences",
          instructions: "Put the words in order to make correct sentences.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: We / must / protect / our / planet.",
              skillTag: "grammar",
              topicTag,
              explanation: "We must protect our planet.",
              words: ["We", "must", "protect", "our", "planet."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: You / mustn't / throw / waste / on / the / ground.",
              skillTag: "grammar",
              topicTag,
              explanation: "You mustn't throw waste on the ground.",
              words: ["You", "mustn't", "throw", "waste", "on", "the", "ground."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-must-review",
          title: "Review: Must and Mustn't Mix",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "The earth _____ stay clean. (important)",
              skillTag: "grammar",
              topicTag,
              explanation: "Must — Trái Đất phải giữ sạch.",
              correct: "must",
              wrong: ["mustn't", "is recycled"],
              distractorNotes: ["Opposite", "Passive"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which rule uses mustn't correctly?",
              skillTag: "grammar",
              topicTag,
              explanation: "Mustn't drop — cấm vứt rác.",
              correct: "People mustn't drop plastic in rivers.",
              wrong: [
                "People mustn't to drop plastic.",
                "People mustn't drops plastic.",
              ],
              distractorNotes: ["Mustn't + to", "Mustn't + -s"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We _____ plan our recycling project. (teacher's rule)",
              skillTag: "grammar",
              topicTag,
              explanation: "Must — cô giáo: chúng ta phải lên kế hoạch.",
              correct: "must",
              wrong: ["mustn't", "are made"],
              distractorNotes: ["Not allowed", "Passive"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-passive-must-mixed",
      title: "Lesson 3: Passive and Must — Mixed Review",
      learningObjective:
        "Choose passive forms and must/mustn't correctly in mixed eco sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-mixed-learn",
          title: "Learn: Passive and Rules Together",
          instructions: "Choose who or which — passive or must.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Plastic bottles _____ on Fridays.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are recycled — bottles (plural) + are recycled.",
              correct: "are recycled",
              wrong: ["is recycled", "must recycle"],
              distractorNotes: ["Singular form", "Active rule, not passive"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "We _____ throw rubbish on the ground.",
              skillTag: "grammar",
              topicTag,
              explanation: "Mustn't — không được vứt rác.",
              correct: "mustn't",
              wrong: ["is made", "are recycled"],
              distractorNotes: ["Passive made", "Passive recycled"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Old paper _____ at school.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is recycled — paper + is recycled.",
              correct: "is recycled",
              wrong: ["are recycled", "must recycled"],
              distractorNotes: ["Paper takes is", "Must + base verb recycle"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We _____ protect oceans on our planet.",
              skillTag: "grammar",
              topicTag,
              explanation: "Must protect — phải bảo vệ đại dương.",
              correct: "must",
              wrong: ["is made", "are made"],
              distractorNotes: ["Passive forms", "Passive forms"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-practice",
          title: "Practice: Passive or Must",
          instructions: "Fill in each gap with the correct form.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: The plastic [0] at our school. | We [1] sort waste carefully. | New bins [2] from recycled plastic.",
              skillTag: "grammar",
              topicTag,
              explanation: "is recycled; must; are made — hỗn hợp bị động và must.",
              template:
                "The plastic [0] at our school. We [1] sort waste carefully. New bins [2] from recycled plastic.",
              correctAnswers: ["is recycled", "must", "are made"],
              acceptableAnswers: [
                ["is recycled", "Is recycled"],
                ["must", "Must"],
                ["are made", "Are made"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-check",
          title: "Check: Mixed Grammar Challenge",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Plastic is recycled + we must protect — both correct.",
              correct: "Plastic is recycled and we must protect nature.",
              wrong: [
                "Plastic is recycle and we must to protect nature.",
                "Plastic are recycled and we must protects nature.",
              ],
              distractorNotes: ["Wrong participle and must+to", "Agreement and must+-s"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They _____ drop plastic in the ocean. Paper _____ every week.",
              skillTag: "grammar",
              topicTag,
              explanation: "Mustn't; is recycled — quy tắc + bị động.",
              correct: "mustn't … is recycled",
              wrong: ["must … are recycled", "mustn't … is recycle"],
              distractorNotes: ["Wrong rule", "Wrong participle"],
              difficultyRating: 3,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Waste must be sorted — must + passive idea at Flyers level.",
              correct: "We must put waste in the right bins.",
              wrong: [
                "We mustn't put waste in the right bins.",
                "Waste must putting in bins.",
              ],
              distractorNotes: ["Opposite meaning", "Must + -ing"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-apply",
          title: "Apply: Build Mixed Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Old bottles / are / recycled / on / Fridays.",
              skillTag: "grammar",
              topicTag,
              explanation: "Old bottles are recycled on Fridays.",
              words: ["Old bottles", "are", "recycled", "on", "Fridays."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: We / mustn't / drop / plastic / in / the / ocean.",
              skillTag: "grammar",
              topicTag,
              explanation: "We mustn't drop plastic in the ocean.",
              words: ["We", "mustn't", "drop", "plastic", "in", "the", "ocean."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-review",
          title: "Review: Passive and Must Mix",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Twenty bottles _____ last week. They _____ again on Friday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Were collected; are recycled — passive past and present.",
              correct: "were collected … are recycled",
              wrong: ["was collected … is recycled", "were collect … are recycle"],
              distractorNotes: ["Singular with bottles", "Wrong participles"],
              difficultyRating: 3,
            }),
            buildMcq({
              questionText: "Mum said you _____ leave sharp bottles on the ground.",
              skillTag: "grammar",
              topicTag,
              explanation: "Mustn't — mẹ cảnh báo không được để chai sắc.",
              correct: "mustn't",
              wrong: ["must", "is made"],
              distractorNotes: ["Opposite", "Passive"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "New paper _____ from newspapers pupils bring from home.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is made — giấy mới được làm từ báo cũ.",
              correct: "is made",
              wrong: ["are made", "must made"],
              distractorNotes: ["Paper takes is", "Must + base verb make"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
