/** Flyers U2 — listening lessons (3 × 5 exercises). */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptEcoClub,
  listeningScriptCleanup,
  listeningAnswerKeys,
  topicTag,
}) {
  const ecoClub = listeningScriptEcoClub;
  const cleanup = listeningScriptCleanup;
  const keysEco = listeningAnswerKeys.ecoClub;
  const keysCleanup = listeningAnswerKeys.cleanup;

  return [
    {
      slug: "listening-eco-club",
      title: "Lesson 1: Eco Club Meeting",
      learningObjective:
        "Listen to an eco club dialogue and extract specific information.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-eco-learn",
          title: "Learn: Planning Recycling",
          instructions: "Listen to the teacher, Minh and Linh. Answer the questions.",
          sortOrder: 0,
          script: ecoClub,
          answerKey: keysEco,
          questions: [
            buildMcq({
              questionText: "What must the eco club plan today?",
              skillTag: "listening",
              topicTag,
              explanation: "Plan our recycling project — lên kế hoạch tái chế.",
              correct: "Their recycling project",
              wrong: ["A birthday party", "A trip to Da Nang"],
              distractorNotes: ["Not a party", "Not in dialogue"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "How much plastic waste did they collect last week?",
              skillTag: "listening",
              topicTag,
              explanation: "Twenty bottles — hai mươi chai.",
              correct: "Twenty bottles",
              wrong: ["Five bags", "Three trees"],
              distractorNotes: ["Bags from cleanup dialogue", "Trees planted next week"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-eco-practice",
          title: "Practice: When and What",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: ecoClub,
          answerKey: keysEco,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "When are the bottles recycled?",
              skillTag: "listening",
              topicTag,
              explanation: "They are recycled on Fridays — thứ Sáu.",
              correct: "On Fridays",
              wrong: ["On Sundays only", "Every morning"],
              distractorNotes: ["Sunday is cleanup", "Not said"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "New paper is made from _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Paper you bring from home — báo/giấy mang từ nhà.",
              correct: "paper pupils bring from home",
              wrong: ["plastic bottles only", "food waste"],
              distractorNotes: ["Plastic makes bins", "Not mentioned"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-eco-check",
          title: "Check: Eco Club Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: ecoClub,
          answerKey: keysEco,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What does Linh say about the ocean?",
              skillTag: "listening",
              topicTag,
              explanation: "We mustn't drop plastic in the ocean — không vứt nhựa xuống biển.",
              correct: "We mustn't drop plastic there",
              wrong: ["We must drop plastic there", "The ocean is not on our planet"],
              distractorNotes: ["Opposite rule", "Minh says protect planet"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What will they do next Friday?",
              skillTag: "listening",
              topicTag,
              explanation: "Plant trees near the playground — trồng cây gần sân chơi.",
              correct: "Plant trees near the playground",
              wrong: ["Visit West Lake", "Write a party invitation"],
              distractorNotes: ["Cleanup is different day", "Not a party"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh says we must protect _____ on our planet.",
              skillTag: "listening",
              topicTag,
              explanation: "Rainforests and oceans — rừng mưa và đại dương.",
              correct: "rainforests and oceans",
              wrong: ["only classrooms", "birthday cakes"],
              distractorNotes: ["Too small", "Not in dialogue"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-eco-apply",
          title: "Apply: Match Eco Club Facts",
          instructions: "Listen again. Match each detail to the correct fact.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: ecoClub },
          questions: [
            buildMatching({
              questionText: "Match each speaker or detail from the dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Linh paper; teacher Friday; Minh protect; twenty bottles.",
              pairs: [
                { left: "Linh", right: "asks about paper made from newspapers" },
                { left: "Teacher", right: "says bottles are recycled on Fridays" },
                { left: "Last week", right: "twenty bottles collected" },
                { left: "Next Friday", right: "plant trees near playground" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-eco-review",
          title: "Review: Eco Club Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: ecoClub,
          answerKey: keysEco,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Where does the eco club meeting take place?",
              skillTag: "listening",
              topicTag,
              explanation: "School classroom after lessons — phòng học sau giờ học.",
              correct: "In a school classroom",
              wrong: ["At West Lake", "In Minh's kitchen"],
              distractorNotes: ["Cleanup setting", "Not mentioned"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh says pollution hurts _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Pollution hurts fish — cá trong đại dương.",
              correct: "fish",
              wrong: ["football players", "birthday guests"],
              distractorNotes: ["Not in dialogue", "Not in dialogue"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-community-cleanup",
      title: "Lesson 2: Community Cleanup",
      learningObjective:
        "Listen for several facts in a community cleanup dialogue.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-cleanup-learn",
          title: "Learn: Cleanup near the Lake",
          instructions: "Listen to Mum, Minh and Linh. Answer the questions.",
          sortOrder: 0,
          script: cleanup,
          answerKey: keysCleanup,
          questions: [
            buildMcq({
              questionText: "What are Minh and Linh helping with?",
              skillTag: "listening",
              topicTag,
              explanation: "Community cleanup — dọn dẹp cộng đồng.",
              correct: "A community cleanup",
              wrong: ["A school exam", "A family birthday party"],
              distractorNotes: ["Not an exam", "Not a party"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What kind of waste does Minh see near the lake?",
              skillTag: "listening",
              topicTag,
              explanation: "A lot of plastic waste — nhiều rác nhựa.",
              correct: "Plastic waste",
              wrong: ["Only paper", "Only food"],
              distractorNotes: ["Plastic specified", "Not specified"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cleanup-practice",
          title: "Practice: Rules and Progress",
          instructions: "Listen again. Focus on rules and bags.",
          sortOrder: 1,
          script: cleanup,
          answerKey: keysCleanup,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "What mustn't they do with sharp bottles?",
              skillTag: "listening",
              topicTag,
              explanation: "Mustn't leave them on the ground — không để trên mặt đất.",
              correct: "Leave them on the ground",
              wrong: ["Put them in bags", "Recycle them at school"],
              distractorNotes: ["They should bag them", "Recycling is later at school"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How many bags have they filled already?",
              skillTag: "listening",
              topicTag,
              explanation: "We filled two bags already — hai túi.",
              correct: "Two",
              wrong: ["Three", "Twenty"],
              distractorNotes: ["Three in reading passage total", "Twenty bottles in eco club"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cleanup-check",
          title: "Check: Cleanup Dialogue Details",
          instructions: "Listen to the full conversation again.",
          sortOrder: 2,
          script: cleanup,
          answerKey: keysCleanup,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Where is the plastic recycled?",
              skillTag: "listening",
              topicTag,
              explanation: "Recycled at our school — tái chế ở trường.",
              correct: "At their school",
              wrong: ["At the lake only", "In the ocean"],
              distractorNotes: ["Collected at lake", "Mustn't drop in ocean"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh says the earth must stay _____.",
              skillTag: "listening",
              topicTag,
              explanation: "The earth must stay clean — Trái Đất phải sạch.",
              correct: "clean",
              wrong: ["polluted", "empty"],
              distractorNotes: ["Opposite", "Not said"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How does Mum feel about the children?",
              skillTag: "listening",
              topicTag,
              explanation: "I'm proud of you — mẹ tự hào.",
              correct: "Proud",
              wrong: ["Angry", "Bored"],
              distractorNotes: ["Positive praise", "Not bored"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-cleanup-apply",
          title: "Apply: Order the Cleanup",
          instructions: "Put the ideas in the order they are discussed.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          content: { script: cleanup },
          questions: [
            buildMcq({
              questionText:
                "Correct order: (1) Mum proud (2) find plastic (3) must put in bags",
              skillTag: "listening",
              topicTag,
              explanation: "Thanks → find plastic → put in bags → rules → proud.",
              correct: "2 → 3 → 1",
              wrong: ["1 → 2 → 3", "3 → 1 → 2"],
              distractorNotes: ["Proud is near end", "Proud not first"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cleanup-review",
          title: "Review: Cleanup Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: cleanup,
          answerKey: keysCleanup,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "When does the cleanup happen?",
              skillTag: "listening",
              topicTag,
              explanation: "Sunday morning — Chủ nhật sáng.",
              correct: "Sunday morning",
              wrong: ["Friday after school", "Saturday party time"],
              distractorNotes: ["Friday is eco club", "Six o'clock party from U1"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh's last line says small actions protect _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Protect our planet for the future — hành tinh tương lai.",
              correct: "our planet",
              wrong: ["only the classroom", "birthday guests"],
              distractorNotes: ["Bigger than classroom", "Not party"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-eco-review",
      title: "Lesson 3: Review Both Dialogues",
      learningObjective:
        "Extract multiple pieces of information across two eco dialogues.",
      estimatedMinutes: 22,
      exercises: [
        buildListeningExercise({
          slug: "listening-review-learn",
          title: "Learn: Eco Club Reminder",
          instructions: "Listen to the eco club dialogue again.",
          sortOrder: 0,
          script: ecoClub,
          answerKey: keysEco,
          questions: [
            buildMcq({
              questionText: "Who leads the eco club meeting?",
              skillTag: "listening",
              topicTag,
              explanation: "Teacher welcomes and plans — cô giáo dẫn buổi họp.",
              correct: "The teacher",
              wrong: ["Minh's mum", "A doctor"],
              distractorNotes: ["Mum in cleanup only", "Not in dialogues"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Paper is made from old _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Linh asks: paper is made from old newspapers.",
              correct: "newspapers",
              wrong: ["plastic bottles", "birthday cakes"],
              distractorNotes: ["Plastic makes bins", "Not in dialogue"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-practice",
          title: "Practice: Cleanup Reminder",
          instructions: "Listen to the cleanup dialogue again.",
          sortOrder: 1,
          script: cleanup,
          answerKey: keysCleanup,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Where does the cleanup dialogue take place?",
              skillTag: "listening",
              topicTag,
              explanation: "Park near West Lake, Sunday morning — công viên gần Hồ Tây.",
              correct: "Park near West Lake",
              wrong: ["School classroom", "Hospital room"],
              distractorNotes: ["Eco club setting", "Not health unit"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How many more bags until they finish?",
              skillTag: "listening",
              topicTag,
              explanation: "One more and we finish — còn một túi nữa.",
              correct: "One more bag",
              wrong: ["Five more bags", "No bags left"],
              distractorNotes: ["Already two filled", "Still one to go"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-check",
          title: "Check: Mixed Eco Listening",
          instructions: "Listen to the cleanup dialogue. Harder questions.",
          sortOrder: 2,
          script: cleanup,
          answerKey: keysCleanup,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which detail is ONLY in the eco club dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Twenty bottles collected — chỉ trong hội thoại CLB.",
              correct: "Twenty bottles collected last week",
              wrong: ["Mum is proud", "Plastic recycled at school"],
              distractorNotes: ["Cleanup dialogue", "Both mention school recycling"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Both dialogues mention _____ rules.",
              skillTag: "listening",
              topicTag,
              explanation: "Must/mustn't in both — quy tắc must và mustn't.",
              correct: "must and mustn't",
              wrong: ["present perfect ever", "who and which"],
              distractorNotes: ["Flyers U1 grammar", "Flyers U1 grammar"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-review-apply",
          title: "Apply: Match Dialogue to Fact",
          instructions: "Listen, then match each fact to the correct dialogue.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: cleanup },
          questions: [
            buildMatching({
              questionText: "Match facts to Eco club or Cleanup dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Club: Fridays, trees; Cleanup: Mum, two bags, lake.",
              pairs: [
                { left: "Bottles recycled on Fridays", right: "Eco club dialogue" },
                { left: "Mum says don't leave sharp bottles", right: "Cleanup dialogue" },
                { left: "Plant trees next Friday", right: "Eco club dialogue" },
                { left: "Nature looks better already", right: "Cleanup dialogue" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-eco-review-final",
          title: "Review: Both Dialogues Mix",
          instructions: "Listen to the eco club dialogue. Final review.",
          sortOrder: 4,
          script: ecoClub,
          answerKey: keysEco,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which number is from the ECO CLUB dialogue only?",
              skillTag: "listening",
              topicTag,
              explanation: "Twenty bottles — chỉ CLB nói số chai tuần trước.",
              correct: "Twenty (bottles)",
              wrong: ["Two (bags)", "Three (bags from reading)"],
              distractorNotes: ["Cleanup bags", "Reading passage"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "In BOTH dialogues, students talk about protecting _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Planet/nature/earth — bảo vệ hành tinh và thiên nhiên.",
              correct: "nature or the planet",
              wrong: ["birthday parties only", "cousins in Da Nang"],
              distractorNotes: ["Not party focus", "Flyers U1 topic"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
