/** Flyers U2 — reading lessons (3 × 5 exercises). */

export function readingLessons({
  buildMcq,
  buildGapFill,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMinhEcoProject,
  topicTag,
}) {
  const passage = passageMinhEcoProject;

  return [
    {
      slug: "reading-gist-eco-project",
      title: "Lesson 1: Read for Gist",
      learningObjective:
        "Read a short text about an eco project and identify the main idea.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-gist-learn",
          title: "Learn: Minh's Eco Project",
          instructions: "Read the passage. Answer the questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "Who is the text mainly about?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh is eleven and lives in Hanoi — nhân vật chính.",
              correct: "Minh and his school eco club",
              wrong: ["Only Minh's mum", "A doctor in a hospital"],
              distractorNotes: ["Mum appears later", "Not in this text"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What is the text mainly about?",
              skillTag: "reading",
              topicTag,
              explanation: "Toàn bài về dự án sinh thái và bảo vệ môi trường.",
              correct: "A school eco project and protecting nature",
              wrong: ["Minh's holiday at the beach", "A football match"],
              distractorNotes: ["Not a holiday story", "Not in text"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-gist-practice",
          title: "Practice: School or Community?",
          instructions: "Read again. Decide where each event happens.",
          sortOrder: 1,
          passage,
          difficulty: 0.25,
          questions: [
            buildMcq({
              questionText: "Where does the eco club collect plastic waste?",
              skillTag: "reading",
              topicTag,
              explanation: "From classrooms at school — thu gom ở trường.",
              correct: "At school",
              wrong: ["Only at West Lake", "In the ocean"],
              distractorNotes: ["Cleanup is at lake", "Ocean is mentioned, not collection place"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Where did Mum take Minh and Linh on Sunday?",
              skillTag: "reading",
              topicTag,
              explanation: "Community cleanup near West Lake — cuối bài đọc.",
              correct: "Near West Lake",
              wrong: ["To the rainforest", "To Da Nang"],
              distractorNotes: ["Rainforest only in article topic", "Not in text"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-gist-check",
          title: "Check: Main Idea",
          instructions: "Read carefully. These questions need thinking.",
          sortOrder: 2,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What is the best title for this text?",
              skillTag: "reading",
              topicTag,
              explanation: "Chủ đề chính: dự án sinh thái ở trường Minh.",
              correct: "Minh's School Eco Project",
              wrong: ["Minh Visits Da Nang", "Minh's Birthday Party"],
              distractorNotes: ["Flyers U1 topic", "Not in text"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is NOT true about the text?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh felt proud — không nói cảm thấy buồn.",
              correct: "Minh felt sad because the cleanup failed.",
              wrong: [
                "Minh joined the eco club with Linh.",
                "Plastic is recycled at school.",
              ],
              distractorNotes: ["True in text", "True in text"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-gist-apply",
          title: "Apply: Match Story Events",
          instructions: "Use the passage. Match each detail to the correct fact.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each part of the story to what happens.",
              skillTag: "reading",
              topicTag,
              explanation: "Friday club; article; Sunday cleanup — ba phần chính.",
              pairs: [
                { left: "Every Friday", right: "eco club collects plastic at school" },
                { left: "Minh's article", right: "describes rainforests and oceans" },
                { left: "On Sunday", right: "community cleanup near West Lake" },
                { left: "At the end", right: "Minh feels proud" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-gist-review",
          title: "Review: Gist Mix",
          instructions: "Read the passage one more time. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "How old is Minh?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh is eleven — câu mở đầu.",
              correct: "Eleven",
              wrong: ["Nine", "Thirteen"],
              distractorNotes: ["Movers age", "Not in text"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Why did the school start an eco project?",
              skillTag: "reading",
              topicTag,
              explanation: "To protect nature and keep the environment clean.",
              correct: "To protect nature and keep the environment clean",
              wrong: ["To celebrate a birthday", "To visit another city"],
              distractorNotes: ["Not a party story", "Not a visit story"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-detail-eco",
      title: "Lesson 2: Find Specific Details",
      learningObjective:
        "Find specific facts about recycling, rules and cleanup in the text.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-detail-learn",
          title: "Learn: Recycling Details",
          instructions: "Read the passage. Find specific details.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What is made from recycled plastic?",
              skillTag: "reading",
              topicTag,
              explanation: "New bins are made from it — thùng mới từ nhựa tái chế.",
              correct: "New bins",
              wrong: ["New shoes", "Birthday cake"],
              distractorNotes: ["Not in text", "Not in text"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When does the club collect plastic waste?",
              skillTag: "reading",
              topicTag,
              explanation: "Every Friday — mỗi thứ Sáu.",
              correct: "Every Friday",
              wrong: ["Every Sunday", "Only in summer"],
              distractorNotes: ["Sunday is cleanup", "Not limited to summer"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-detail-practice",
          title: "Practice: Rules in the Text",
          instructions: "Read again. Choose the correct statement.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "What must students do with waste?",
              skillTag: "reading",
              topicTag,
              explanation: "We must sort waste carefully — phải phân loại cẩn thận.",
              correct: "Sort waste carefully",
              wrong: ["Throw it on the ground", "Burn all plastic"],
              distractorNotes: ["Mustn't throw on ground", "Not in text"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What mustn't students do?",
              skillTag: "reading",
              topicTag,
              explanation: "We mustn't throw rubbish on the ground.",
              correct: "Throw rubbish on the ground",
              wrong: ["Join the eco club", "Recycle paper"],
              distractorNotes: ["Minh and Linh joined", "Paper is recycled"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-detail-check",
          title: "Check: Detail Search",
          instructions: "Find the answers in the text.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Who wrote a short article for the school board?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh wrote a short article — Minh viết bài.",
              correct: "Minh",
              wrong: ["Linh only", "The teacher only"],
              distractorNotes: ["Minh wrote it", "Teacher gives rules, Minh writes article"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How many bags did they fill at the cleanup?",
              skillTag: "reading",
              topicTag,
              explanation: "They filled three bags with waste — ba túi.",
              correct: "Three",
              wrong: ["Two", "Ten"],
              distractorNotes: ["Two bags in listening dialogue", "Not in reading"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The article says pollution hurts animals in the _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Pollution hurts animals in the ocean — đại dương.",
              correct: "ocean",
              wrong: ["classroom", "playground only"],
              distractorNotes: ["Where club meets", "Trees planted there but pollution in ocean"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-detail-apply",
          title: "Apply: Complete from the Text",
          instructions: "Fill in the gaps using words from the passage.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: The plastic is [0] and new bins are [1] from it. We mustn't throw rubbish on the [2].",
              skillTag: "reading",
              topicTag,
              explanation: "recycled; made; ground — chi tiết bài đọc.",
              template:
                "The plastic is [0] and new bins are [1] from it. We mustn't throw rubbish on the [2].",
              correctAnswers: ["recycled", "made", "ground"],
              acceptableAnswers: [
                ["recycled", "Recycled"],
                ["made", "Made"],
                ["ground", "Ground"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-detail-review",
          title: "Review: Detail Mix",
          instructions: "Find the answers in the text again.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "What else is recycled besides plastic?",
              skillTag: "reading",
              topicTag,
              explanation: "Old paper is recycled too — giấy cũ cũng được tái chế.",
              correct: "Old paper",
              wrong: ["Food only", "Glass only"],
              distractorNotes: ["Not mentioned", "Not mentioned"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Why did Minh feel proud at the end?",
              skillTag: "reading",
              topicTag,
              explanation: "Small actions can protect the earth — hành động nhỏ bảo vệ Trái Đất.",
              correct: "Because small actions can protect the earth",
              wrong: [
                "Because he won a football game",
                "Because he never joined the club",
              ],
              distractorNotes: ["Not in text", "Opposite — he joined"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-text-type-purpose",
      title: "Lesson 3: Text Type and Purpose",
      learningObjective:
        "Identify the text type and purpose of Minh's article and the main passage.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-type-learn",
          title: "Learn: What Kind of Text?",
          instructions: "Read the passage. Think about text type.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "The main passage is best described as a _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Short story/report about an eco project — bài mô tả sự việc.",
              correct: "short report about a school project",
              wrong: ["recipe for cooking", "shopping list"],
              distractorNotes: ["Not instructions for food", "Not a list"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh's article for the school board is written to _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Asks everyone to help — thuyết phục mọi người giúp đỡ.",
              correct: "explain why nature needs protection and ask for help",
              wrong: ["sell plastic bottles", "invite guests to a party"],
              distractorNotes: ["Not selling", "Not a party invite"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-type-practice",
          title: "Practice: Purpose of Each Part",
          instructions: "Read again. Match purpose to each part.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Why does the teacher talk about must and mustn't?",
              skillTag: "reading",
              topicTag,
              explanation: "To give eco rules — đưa ra quy tắc môi trường.",
              correct: "To give rules about sorting waste",
              wrong: ["To tell a joke", "To describe a holiday"],
              distractorNotes: ["Serious rules", "Not a holiday"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The last paragraph about Sunday cleanup shows _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Community action outside school — hành động cộng đồng.",
              correct: "community action to keep nature clean",
              wrong: ["a classroom lesson only", "a science fiction story"],
              distractorNotes: ["Happens at lake", "Realistic story"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-type-check",
          title: "Check: Text Type Challenge",
          instructions: "Think about who wrote what and why.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Who is the audience for Minh's article?",
              skillTag: "reading",
              topicTag,
              explanation: "School board / everyone at school — bài cho hội đồng trường.",
              correct: "People at school (school board / classmates)",
              wrong: ["Only his mum", "People in another country only"],
              distractorNotes: ["Mum not the audience", "School focus"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which part is most like an INFORMATION text?",
              skillTag: "reading",
              topicTag,
              explanation: "Article describes rainforests, oceans, pollution — thông tin.",
              correct: "Minh's article about rainforests and oceans",
              wrong: ["The sentence 'Minh is eleven'", "Only the title"],
              distractorNotes: ["One fact only", "Title alone"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The writer's main purpose is to _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Encourage protecting nature — khuyến khích bảo vệ thiên nhiên.",
              correct: "encourage readers to protect the environment",
              wrong: ["advertise a new phone", "describe a football match"],
              distractorNotes: ["Not advertising", "Not sport"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-type-apply",
          title: "Apply: Match Text to Purpose",
          instructions: "Match each text part to its purpose.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each part of the passage to its purpose.",
              skillTag: "reading",
              topicTag,
              explanation: "Intro sets scene; rules teach; article informs; cleanup shows action.",
              pairs: [
                { left: "Opening paragraphs", right: "introduce the eco club and recycling" },
                { left: "Teacher's must/mustn't rules", right: "tell students what to do and not do" },
                { left: "Minh's article", right: "inform about planet, rainforests and oceans" },
                { left: "Sunday cleanup", right: "show real community action" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-type-review",
          title: "Review: Text Type and Purpose Mix",
          instructions: "Read and answer about text type and purpose.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "If this text were in a school magazine, it would be in the _____ section.",
              skillTag: "reading",
              topicTag,
              explanation: "Environment / eco news section — mục môi trường.",
              correct: "Environment or Eco News",
              wrong: ["Sports Results", "Cooking Recipes"],
              distractorNotes: ["Not about sport", "Not about food"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which question does Minh's article try to answer?",
              skillTag: "reading",
              topicTag,
              explanation: "Why rainforests and oceans are important — tại sao cần bảo vệ.",
              correct: "Why must we protect rainforests and oceans?",
              wrong: ["What time does the party start?", "How do you cook rice?"],
              distractorNotes: ["Party from U1", "Not cooking"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
