/** Flyers U2 — speaking lessons (3 × 5 exercises; only Check is AI). */

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [ecoCheck, pollutionCheck, cleanupCheck] = speakingChecks;

  return [
    {
      slug: "speaking-eco-club",
      title: "Lesson 1: Talk About the Eco Club",
      learningObjective:
        "Choose appropriate spoken phrases about the school eco club and recycling.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-eco-learn",
          title: "Learn: What to Say About Eco Club",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Someone asks: What does your eco club do? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Collects plastic + recycles — trả lời đầy đủ.",
              correct: "We collect plastic waste and recycle paper every Friday.",
              wrong: ["Eco club Friday plastic.", "We recycle party guests."],
              distractorNotes: ["Fragment", "Wrong topic"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best answer: What is made from recycled plastic?",
              skillTag: "speaking",
              topicTag,
              explanation: "New bins are made from it — câu bị động hoàn chỉnh.",
              correct: "New bins are made from recycled plastic.",
              wrong: ["Bins made plastic new.", "New bins is make from plastic."],
              distractorNotes: ["Fragment", "Wrong grammar"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-eco-practice",
          title: "Practice: Eco Club Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "What must students do with waste? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "We must sort waste carefully — quy tắc rõ ràng.",
              correct: "We must sort waste carefully into the right bins.",
              wrong: ["We must to sort waste careful.", "Must sort waste we."],
              distractorNotes: ["Must + to", "Wrong order"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What mustn't you do? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "You mustn't throw rubbish on the ground.",
              correct: "You mustn't throw rubbish on the ground.",
              wrong: ["You mustn't to throw rubbish.", "Mustn't throw you rubbish."],
              distractorNotes: ["Mustn't + to", "Wrong order"],
              difficultyRating: 2,
            }),
          ],
        }),
        ecoCheck,
        buildExercise({
          slug: "speaking-eco-apply",
          title: "Apply: Quick Eco Replies",
          instructions: "Choose the best short spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Teacher asks: Why join the eco club? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Want to protect nature — lý do rõ và đủ câu.",
              correct: "I want to protect nature and keep our environment clean.",
              wrong: ["Protect nature clean yes.", "I join eco because party."],
              distractorNotes: ["Too short", "Wrong reason"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-eco-review",
          title: "Review: Eco Club Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "When is plastic recycled? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "On Fridays — thời gian rõ ràng.",
              correct: "It is recycled on Fridays at our school.",
              wrong: ["Recycle Friday plastic.", "It recycled Fridays school."],
              distractorNotes: ["Fragment", "Missing is"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Describe the eco project. Best phrase:",
              skillTag: "speaking",
              topicTag,
              explanation: "Passive + must — mô tả dự án Flyers U2.",
              correct:
                "Plastic is recycled and we must protect rainforests and oceans.",
              wrong: ["Plastic recycle must rainforest.", "We must protects plastic ocean."],
              distractorNotes: ["Not a sentence", "Must + -s"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-pollution-planet",
      title: "Lesson 2: Talk About Pollution",
      learningObjective:
        "Use pollution, protect and planet vocabulary in short spoken answers.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-pollution-learn",
          title: "Learn: Pollution Speaking Phrases",
          instructions: "Choose the best thing to say about pollution.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Why is pollution dangerous? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Hurts fish in the ocean — câu hoàn chỉnh.",
              correct: "Pollution hurts fish and animals in the ocean.",
              wrong: ["Pollution ocean fish hurt.", "Pollution is party dangerous."],
              distractorNotes: ["Fragment", "Wrong context"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What must we protect? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Rainforests and oceans on our planet — cụ thể.",
              correct: "We must protect rainforests and oceans on our planet.",
              wrong: ["Must protect rainforest ocean.", "We must to protect planet."],
              distractorNotes: ["Not a full sentence", "Must + to"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-pollution-practice",
          title: "Practice: Rules for Nature",
          instructions: "Choose the correct spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "What mustn't people drop in rivers? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Plastic waste — không vứt nhựa xuống sông.",
              correct: "People mustn't drop plastic waste in rivers or lakes.",
              wrong: ["People mustn't to drop plastic.", "Mustn't people plastic drop."],
              distractorNotes: ["Mustn't + to", "Wrong order"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How can recycling help? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Less pollution is made — ít ô nhiễm hơn.",
              correct: "When waste is recycled, less pollution is made.",
              wrong: ["Recycle help pollution less.", "Recycling is made pollution."],
              distractorNotes: ["Fragment", "Confused passive"],
              difficultyRating: 2,
            }),
          ],
        }),
        pollutionCheck,
        buildExercise({
          slug: "speaking-pollution-apply",
          title: "Apply: Choose the Best Pollution Reply",
          instructions: "Pick the most natural spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Why is a clean earth important?",
              skillTag: "speaking",
              topicTag,
              explanation: "Important for everyone's future — lý do rõ.",
              correct: "A clean earth is important for everyone's future.",
              wrong: ["Clean earth future important everyone.", "Earth clean because party."],
              distractorNotes: ["Wrong order", "Wrong context"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-pollution-review",
          title: "Review: Pollution Speaking Quiz",
          instructions: "Choose the best answer using environment vocabulary.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Describe plastic near the lake. Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Plastic waste causes pollution — mô tả vấn đề.",
              correct: "There is a lot of plastic waste and it causes pollution.",
              wrong: ["Plastic lake waste pollution lot.", "Plastic is pollution lake."],
              distractorNotes: ["Fragment", "Wrong grammar"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best sentence with mustn't about the ocean:",
              skillTag: "speaking",
              topicTag,
              explanation: "We mustn't drop plastic in the ocean — như Linh nói.",
              correct: "We mustn't drop plastic in the ocean.",
              wrong: ["We must drop plastic in ocean.", "We mustn't to drop plastic ocean."],
              distractorNotes: ["Opposite meaning", "Mustn't + to"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-cleanup-community",
      title: "Lesson 3: Talk About a Cleanup",
      learningObjective:
        "Describe a community cleanup in extended spoken answers.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "speaking-cleanup-learn",
          title: "Learn: Cleanup Speaking Phrases",
          instructions: "Choose the best thing to say about a cleanup.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Tell me about Sunday cleanup. Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Where + who + what — câu mở đầu đầy đủ.",
              correct:
                "On Sunday Mum, Linh and I helped with a cleanup near West Lake.",
              wrong: ["Sunday cleanup West Lake Mum.", "Cleanup I Sunday lake plastic."],
              distractorNotes: ["Fragment", "Wrong order"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What did Mum warn you about? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Mustn't leave sharp bottles — cảnh báo của mẹ.",
              correct: "She said we mustn't leave sharp bottles on the ground.",
              wrong: ["Mum mustn't bottles sharp.", "She said must to leave bottles."],
              distractorNotes: ["Fragment", "Must + to"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-cleanup-practice",
          title: "Practice: Bags and Recycling",
          instructions: "Choose the best spoken answers.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Where is the plastic recycled? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "At our school — tái chế ở trường.",
              correct: "The plastic is recycled at our school.",
              wrong: ["Plastic recycle school.", "The plastic are recycled school."],
              distractorNotes: ["Missing is", "Wrong be verb"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How did you feel at the end? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Proud because small actions protect the planet.",
              correct: "I felt proud because small actions protect our planet.",
              wrong: ["Proud I planet actions small.", "I feel proud protect planet small."],
              distractorNotes: ["Wrong order", "Wrong tense mix"],
              difficultyRating: 2,
            }),
          ],
        }),
        cleanupCheck,
        buildExercise({
          slug: "speaking-cleanup-apply",
          title: "Apply: Tell About the Cleanup",
          instructions: "Choose the best cleanup description.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best short description of community cleanup:",
              skillTag: "speaking",
              topicTag,
              explanation: "Connected ideas: waste, bags, clean earth.",
              correct:
                "We collected plastic waste in bags. Nature looked cleaner and a clean earth is important.",
              wrong: [
                "Cleanup plastic bags earth nature must.",
                "We cleanup plastic and earth is recycle proud.",
              ],
              distractorNotes: ["Not sentences", "Ungrammatical"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-cleanup-review",
          title: "Review: Cleanup Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "What kind of waste did you find? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Plastic waste near the lake — như trong hội thoại.",
              correct: "We found a lot of plastic waste near the lake.",
              wrong: ["Found plastic waste lake lot.", "Plastic waste is find lake."],
              distractorNotes: ["Fragment", "Wrong grammar"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best pair: passive + must rule:",
              skillTag: "speaking",
              topicTag,
              explanation: "Plastic is recycled + we must put waste in bags.",
              correct:
                "Plastic is recycled at school. We must put waste in bags during cleanup.",
              wrong: [
                "Plastic is recycle and we must puts waste.",
                "Must recycled plastic we bags waste.",
              ],
              distractorNotes: ["Wrong participle and must+-s", "Meaningless"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
