/** Flyers U2 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-planet-nature",
      title: "Lesson 1: Planet and Nature",
      learningObjective:
        "Recognise and use planet, rainforest, ocean, nature, earth and environment.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-planet-learn",
          title: "Learn: Planet and Nature Words",
          instructions: "Read each clue. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Earth is the _____ we live on.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Planet (hành tinh) — Trái Đất là hành tinh chúng ta sống.",
              correct: "planet",
              wrong: ["ocean", "rainforest"],
              distractorNotes: ["Large body of water", "Type of forest"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Trees, animals and rivers are part of _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Nature (thiên nhiên) — cây, động vật, sông.",
              correct: "nature",
              wrong: ["pollution", "plastic"],
              distractorNotes: ["Dirty air or water", "Material, not all of nature"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Fish live in the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ocean (đại dương) — nơi cá sống.",
              correct: "ocean",
              wrong: ["rainforest", "environment"],
              distractorNotes: ["Forest on land", "Surroundings in general"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "A hot wet forest with many animals is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rainforest (rừng mưa) — rừng nhiệt đới ẩm nóng.",
              correct: "rainforest",
              wrong: ["planet", "waste"],
              distractorNotes: ["Whole world", "Rubbish"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-planet-practice",
          title: "Practice: Match Planet and Nature",
          instructions: "Match each word to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the planet and nature words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mỗi từ chỉ một khái niệm thiên nhiên cụ thể.",
              pairs: [
                { left: "planet", right: "a large body in space, like Earth" },
                { left: "earth", right: "the world we live on" },
                { left: "ocean", right: "a very large area of salt water" },
                { left: "rainforest", right: "a hot wet forest with many plants and animals" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-planet-check",
          title: "Check: Planet and Nature Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "We must protect our _____ for the future.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Planet (hành tinh) — bảo vệ hành tinh cho tương lai.",
              correct: "planet",
              wrong: ["pollution", "waste"],
              distractorNotes: ["Problem, not what we protect", "Rubbish"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh wants to keep the school _____ clean.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Environment (môi trường) — môi trường trường học.",
              correct: "environment",
              wrong: ["ocean", "rainforest"],
              distractorNotes: ["Water only", "Forest only"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "A clean _____ is important for everyone.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Earth (Trái Đất) — Trái Đất sạch quan trọng với mọi người.",
              correct: "earth",
              wrong: ["plastic", "recycle"],
              distractorNotes: ["Material", "Verb/action"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-planet-apply",
          title: "Apply: Complete Nature Sentences",
          instructions: "Fill in each gap with the correct word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Rainforests and [0] on our planet need protection. | Fish live in the [1]. | Linh loves walking in [2].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "oceans; ocean; nature — từ vựng thiên nhiên và hành tinh.",
              template:
                "Rainforests and [0] on our planet need protection. Fish live in the [1]. Linh loves walking in [2].",
              correctAnswers: ["oceans", "ocean", "nature"],
              acceptableAnswers: [
                ["oceans", "Oceans", "ocean", "Ocean"],
                ["ocean", "Ocean", "the ocean", "The ocean"],
                ["nature", "Nature"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-planet-review",
          title: "Review: Planet and Nature Mix",
          instructions: "Mixed review from this lesson. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Pollution hurts animals in the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ocean (đại dương) — ô nhiễm làm hại cá.",
              correct: "ocean",
              wrong: ["earth only", "recycle"],
              distractorNotes: ["Earth is the whole planet", "Verb, not place"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word means 'everything around us — air, land and water'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Environment (môi trường) — không khí, đất, nước xung quanh.",
              correct: "environment",
              wrong: ["nature only", "plastic"],
              distractorNotes: ["Nature is wider wild world", "Material"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh's article describes why _____ are important on our planet.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rainforests (rừng mưa) — bài viết nói về rừng mưa và đại dương.",
              correct: "rainforests",
              wrong: ["pollution", "waste"],
              distractorNotes: ["Problem, not place to protect", "Rubbish"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-pollution-protect",
      title: "Lesson 2: Pollution and Protect",
      learningObjective:
        "Use pollution, protect, plastic, waste and clean to talk about environmental problems.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-pollution-learn",
          title: "Learn: Pollution and Protect",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Dirty air and plastic in the sea cause _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Pollution (ô nhiễm) — rác và khí bẩn gây ô nhiễm.",
              correct: "pollution",
              wrong: ["nature", "recycle"],
              distractorNotes: ["Clean natural world", "Action to help"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "We must _____ rainforests and oceans.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Protect (bảo vệ) — phải bảo vệ rừng mưa và đại dương.",
              correct: "protect",
              wrong: ["pollute", "waste"],
              distractorNotes: ["Opposite meaning", "Noun for rubbish"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Bottles and bags are often made of _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Plastic (nhựa) — chai và túi thường làm bằng nhựa.",
              correct: "plastic",
              wrong: ["nature", "planet"],
              distractorNotes: ["Natural world", "Whole world"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Rubbish that people throw away is called _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Waste (rác thải) — rác người ta vứt bỏ.",
              correct: "waste",
              wrong: ["earth", "ocean"],
              distractorNotes: ["The planet", "Large water area"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-pollution-practice",
          title: "Practice: Match Pollution Words",
          instructions: "Match each word to the correct meaning or situation.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match pollution and protect words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ghép từ với nghĩa hoặc tình huống phù hợp.",
              pairs: [
                { left: "pollution", right: "dirty air, water or land that hurts nature" },
                { left: "protect", right: "keep nature safe from harm" },
                { left: "plastic", right: "material used for bottles and bags" },
                { left: "clean", right: "not dirty; free from rubbish" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-pollution-check",
          title: "Check: Pollution Quiz",
          instructions: "Choose the best answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Plastic waste near the lake is a kind of _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Pollution (ô nhiễm) — rác nhựa gần hồ gây ô nhiễm.",
              correct: "pollution",
              wrong: ["recycle", "rainforest"],
              distractorNotes: ["Action to fix problem", "Forest type"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The playground is _____ after the cleanup.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Clean (sạch) — sân chơi sạch sau dọn dẹp.",
              correct: "clean",
              wrong: ["pollution", "waste"],
              distractorNotes: ["Opposite of clean", "Rubbish left behind"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Small actions can _____ our planet.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Protect (bảo vệ) — hành động nhỏ bảo vệ hành tinh.",
              correct: "protect",
              wrong: ["pollute", "waste"],
              distractorNotes: ["Harm the planet", "Rubbish, not a verb here"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-pollution-apply",
          title: "Apply: Pollution Sentences",
          instructions: "Complete the sentences about pollution and cleanup.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: There is a lot of [0] waste near the lake. | We must [1] nature from pollution. | The earth must stay [2].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "plastic; protect; clean — nhựa, bảo vệ, sạch.",
              template:
                "There is a lot of [0] waste near the lake. We must [1] nature from pollution. The earth must stay [2].",
              correctAnswers: ["plastic", "protect", "clean"],
              acceptableAnswers: [
                ["plastic", "Plastic"],
                ["protect", "Protect"],
                ["clean", "Clean"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-pollution-review",
          title: "Review: Pollution and Protect Mix",
          instructions: "Mixed review. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "The club sorts _____ into different bins.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Waste (rác thải) — phân loại rác vào thùng.",
              correct: "waste",
              wrong: ["planet", "nature only"],
              distractorNotes: ["Whole world", "Too general — waste is rubbish"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We mustn't drop _____ in the ocean.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Plastic (nhựa) — không được vứt nhựa xuống biển.",
              correct: "plastic",
              wrong: ["nature", "earth"],
              distractorNotes: ["Natural world", "The whole planet"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word is a problem for fish in the ocean?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Pollution (ô nhiễm) — làm hại cá trong đại dương.",
              correct: "pollution",
              wrong: ["protect", "clean"],
              distractorNotes: ["Good action", "Good state"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-recycle-rules",
      title: "Lesson 3: Recycle and Rules",
      learningObjective:
        "Use recycle with must and mustn't to talk about eco rules and actions.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-recycle-learn",
          title: "Learn: Recycle and Rules",
          instructions: "Choose the word that best completes each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Old paper and plastic can be _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Recycled (tái chế) — giấy và nhựa cũ có thể tái chế.",
              correct: "recycled",
              wrong: ["polluted", "protected"],
              distractorNotes: ["Made dirty", "Kept safe — different action"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "We _____ sort waste into the right bins. (important rule)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Must (phải) — quy tắc quan trọng: phải phân loại rác.",
              correct: "must",
              wrong: ["mustn't", "recycle"],
              distractorNotes: ["Not allowed — opposite", "Verb for materials"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "You _____ throw rubbish on the ground. (not allowed)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mustn't (không được) — không được vứt rác xuống đất.",
              correct: "mustn't",
              wrong: ["must", "protect"],
              distractorNotes: ["Required — opposite", "Verb protect nature"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Our eco club _____ paper every Friday.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Recycles (tái chế) — câu lạc bộ tái chế giấy mỗi thứ Sáu.",
              correct: "recycles",
              wrong: ["pollutes", "protects"],
              distractorNotes: ["Makes dirty", "Keeps safe — different"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-recycle-practice",
          title: "Practice: Match Recycle and Rules",
          instructions: "Match each word or phrase to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match recycle and rule words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Recycle/must/mustn't — tái chế và quy tắc.",
              pairs: [
                { left: "recycle", right: "use old materials to make new things" },
                { left: "must", right: "have to do something — it is a rule" },
                { left: "mustn't", right: "not allowed to do something" },
                { left: "waste", right: "rubbish that is thrown away" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-recycle-check",
          title: "Check: Recycle and Rules Challenge",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "The plastic is _____ at our school.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Recycled (tái chế) — nhựa được tái chế ở trường.",
              correct: "recycled",
              wrong: ["polluted", "protected only"],
              distractorNotes: ["Made dirty", "Different action"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence uses must correctly?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "We must protect nature — must + động từ nguyên mẫu.",
              correct: "We must protect nature.",
              wrong: [
                "We must to protect nature.",
                "We must protects nature.",
              ],
              distractorNotes: ["Must + to (wrong)", "Must + -s (wrong)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh said: We _____ drop plastic in the ocean.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mustn't (không được) — không được vứt nhựa xuống biển.",
              correct: "mustn't",
              wrong: ["must", "recycle"],
              distractorNotes: ["Opposite — required", "Different meaning"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-recycle-apply",
          title: "Apply: Recycle and Rule Sentences",
          instructions: "Fill in with recycle, must or mustn't.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Paper is [0] every Friday. | We [1] put rubbish in bins. | You [2] leave sharp bottles on the ground.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "recycled; must; mustn't — tái chế và quy tắc.",
              template:
                "Paper is [0] every Friday. We [1] put rubbish in bins. You [2] leave sharp bottles on the ground.",
              correctAnswers: ["recycled", "must", "mustn't"],
              acceptableAnswers: [
                ["recycled", "Recycled"],
                ["must", "Must"],
                ["mustn't", "Mustn't", "must not", "Must not"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-recycle-review",
          title: "Review: Unit Vocabulary Mix",
          instructions: "Choose the best word from the whole unit.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "New bins are made when plastic is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Recycled (tái chế) — thùng mới làm từ nhựa tái chế.",
              correct: "recycled",
              wrong: ["polluted", "wasted only"],
              distractorNotes: ["Made dirty", "Thrown away without reuse"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Students _____ wear gloves during cleanup. (school rule)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Must (phải) — quy định phải đeo găng khi dọn dẹp.",
              correct: "must",
              wrong: ["mustn't", "recycle"],
              distractorNotes: ["Not allowed — opposite", "Process materials"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh joined the eco club to help the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Environment (môi trường) — tham gia CLB để giúp môi trường.",
              correct: "environment",
              wrong: ["pollution", "mustn't"],
              distractorNotes: ["Problem, not what we help", "Rule word only"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
