/** Flyers U1 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-present-perfect-ever-never",
      title: "Lesson 1: Present Perfect — Ever and Never",
      learningObjective:
        "Use present perfect with ever and never to talk about life experiences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-ever-learn",
          title: "Learn: Ever and Never",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "_____ you ever visited Da Nang?",
              skillTag: "grammar",
              topicTag,
              explanation: "Have you ever — câu hỏi kinh nghiệm với you.",
              correct: "Have",
              wrong: ["Has", "Did"],
              distractorNotes: ["For he/she/it", "Past simple, not experience"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh has _____ stayed by the sea before.",
              skillTag: "grammar",
              topicTag,
              explanation: "Has never — chưa từng ở gần biển.",
              correct: "never",
              wrong: ["ever", "always"],
              distractorNotes: ["Used in questions", "Opposite meaning"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "She has _____ invited so many guests.",
              skillTag: "grammar",
              topicTag,
              explanation: "Has never — chưa từng mời nhiều khách như vậy.",
              correct: "never",
              wrong: ["ever", "did"],
              distractorNotes: ["Question word", "Wrong tense"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "I have _____ been to a big family party here.",
              skillTag: "grammar",
              topicTag,
              explanation: "Have never — chưa từng tham gia tiệc lớn ở đây.",
              correct: "never",
              wrong: ["ever", "always"],
              distractorNotes: ["Question form", "Means many times"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-ever-practice",
          title: "Practice: Complete Ever/Never Sentences",
          instructions: "Fill in each gap with ever or never.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Have you [0] visited your cousin? | Minh has [1] stayed overnight with Nam. | I have [2] invited Linh to a party.",
              skillTag: "grammar",
              topicTag,
              explanation: "ever (question); never; never — kinh nghiệm sống.",
              template:
                "Have you [0] visited your cousin? Minh has [1] stayed overnight with Nam. I have [2] invited Linh to a party.",
              correctAnswers: ["ever", "never", "never"],
              acceptableAnswers: [
                ["ever", "Ever"],
                ["never", "Never"],
                ["never", "Never"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-ever-check",
          title: "Check: Present Perfect Challenge",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Have you ever + past participle visited.",
              correct: "Have you ever visited Hanoi?",
              wrong: [
                "Did you ever visited Hanoi?",
                "Have you ever visit Hanoi?",
              ],
              distractorNotes: ["Wrong auxiliary with visited", "Missing past participle"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Nam has _____ been to Hanoi.",
              skillTag: "grammar",
              topicTag,
              explanation: "Has never — Nam chưa từng đến Hà Nội.",
              correct: "never",
              wrong: ["ever", "always"],
              distractorNotes: ["Question word", "Opposite — he hasn't been"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Never đứng sau has/have, trước past participle.",
              correct: "I have never stayed with a cousin for so long.",
              wrong: [
                "I never have stayed with a cousin.",
                "I have stayed never with a cousin.",
              ],
              distractorNotes: ["Wrong word order", "Never after verb"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-ever-apply",
          title: "Apply: Build Experience Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Have / you / ever / visited / your aunt?",
              skillTag: "grammar",
              topicTag,
              explanation: "Have you ever visited your aunt?",
              words: ["Have", "you", "ever", "visited", "your aunt?"],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Minh / has / never / been / to Da Nang / before.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh has never been to Da Nang before.",
              words: ["Minh", "has", "never", "been", "to Da Nang", "before."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-ever-review",
          title: "Review: Ever and Never Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "_____ your cousin ever stayed with you?",
              skillTag: "grammar",
              topicTag,
              explanation: "Has your cousin — câu hỏi với third person.",
              correct: "Has",
              wrong: ["Have", "Did"],
              distractorNotes: ["For I/you/we/they", "Past simple"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We have _____ celebrated Uncle Binh's birthday together.",
              skillTag: "grammar",
              topicTag,
              explanation: "Have always — luôn ăn mừng cùng nhau (present perfect habit).",
              correct: "always",
              wrong: ["never", "ever"],
              distractorNotes: ["Opposite meaning", "Question word"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which question is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Have you ever + past participle stayed.",
              correct: "Have you ever stayed with a cousin?",
              wrong: [
                "Have you ever stay with a cousin?",
                "Did you ever stayed with a cousin?",
              ],
              distractorNotes: ["Missing past participle", "Wrong tense/auxiliary"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-relative-who",
      title: "Lesson 2: Relative Clauses — Who",
      learningObjective:
        "Use who to add information about people in relative clauses.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-who-learn",
          title: "Learn: Who for People",
          instructions: "Choose the correct relative pronoun or sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh has an aunt _____ lives in Da Nang.",
              skillTag: "grammar",
              topicTag,
              explanation: "Who — thay cho người (aunt).",
              correct: "who",
              wrong: ["which", "where"],
              distractorNotes: ["For things", "For places"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh is the neighbour _____ helped us.",
              skillTag: "grammar",
              topicTag,
              explanation: "Who — neighbour là người.",
              correct: "who",
              wrong: ["which", "what"],
              distractorNotes: ["For things", "Not a relative pronoun"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Who for cousin (person).",
              correct: "Nam is the cousin who is the same age as Minh.",
              wrong: [
                "Nam is the cousin which is the same age.",
                "Nam is the cousin where is the same age.",
              ],
              distractorNotes: ["Which for things", "Where for places"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "This is the guest _____ never visits us.",
              skillTag: "grammar",
              topicTag,
              explanation: "Who — guest là người.",
              correct: "who",
              wrong: ["which", "when"],
              distractorNotes: ["For things", "For time"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-who-practice",
          title: "Practice: Complete Who Clauses",
          instructions: "Fill in each gap with who.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: My aunt, [0] works at a hospital, welcomed Minh. | Linh is the neighbour [1] is our friend. | The cousin [2] lives in Da Nang is Nam.",
              skillTag: "grammar",
              topicTag,
              explanation: "who; who; who — mệnh đề quan hệ chỉ người.",
              template:
                "My aunt, [0] works at a hospital, welcomed Minh. Linh is the neighbour [1] is our friend. The cousin [2] lives in Da Nang is Nam.",
              correctAnswers: ["who", "who", "who"],
              acceptableAnswers: [
                ["who", "Who"],
                ["who", "Who"],
                ["who", "Who"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-who-check",
          title: "Check: Who Clauses",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Who for aunt (person), not which.",
              correct: "My aunt, who lives in Da Nang, invited us.",
              wrong: [
                "My aunt, which lives in Da Nang, invited us.",
                "My aunt, where lives in Da Nang, invited us.",
              ],
              distractorNotes: ["Which for things", "Where for places"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The relative _____ is a good friend of the family is Linh.",
              skillTag: "grammar",
              topicTag,
              explanation: "Who — Linh is a person.",
              correct: "who",
              wrong: ["which", "what"],
              distractorNotes: ["For things", "Not relative pronoun"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Who + is (no extra he/she).",
              correct: "My cousin, who is eleven, showed me the beach.",
              wrong: [
                "My cousin, who he is eleven, showed me the beach.",
                "My cousin, who is he eleven, showed me the beach.",
              ],
              distractorNotes: ["Extra pronoun he", "Wrong word order"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-who-apply",
          title: "Apply: Order Who Sentences",
          instructions: "Put the words in order to make correct sentences.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Linh / is / the neighbour / who / helped / us.",
              skillTag: "grammar",
              topicTag,
              explanation: "Linh is the neighbour who helped us.",
              words: ["Linh", "is", "the neighbour", "who", "helped", "us."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: My aunt, / who / lives / in Da Nang, / welcomed / Minh.",
              skillTag: "grammar",
              topicTag,
              explanation: "My aunt, who lives in Da Nang, welcomed Minh.",
              words: ["My aunt,", "who", "lives", "in Da Nang,", "welcomed", "Minh."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-who-review",
          title: "Review: Who Clauses Mix",
          instructions: "Choose the correct relative pronoun or sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Uncle Binh is the man _____ works near the beach.",
              skillTag: "grammar",
              topicTag,
              explanation: "Who — man là người.",
              correct: "who",
              wrong: ["which", "where"],
              distractorNotes: ["For things", "For places"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Who for grandmother (person).",
              correct: "My grandmother, who is seventy, is the oldest relative.",
              wrong: [
                "My grandmother, which is seventy, is the oldest.",
                "My grandmother, who she is seventy, is the oldest.",
              ],
              distractorNotes: ["Which for people", "Extra pronoun"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The guests _____ came to the party were all relatives.",
              skillTag: "grammar",
              topicTag,
              explanation: "Who — guests are people.",
              correct: "who",
              wrong: ["which", "when"],
              distractorNotes: ["For things", "For time"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-relative-which-mixed",
      title: "Lesson 3: Relative Clauses — Which and Mixed Review",
      learningObjective:
        "Use which for things and choose who or which correctly in mixed sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-which-learn",
          title: "Learn: Which for Things",
          instructions: "Choose who or which.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "The party, _____ was on Saturday, was wonderful.",
              skillTag: "grammar",
              topicTag,
              explanation: "Which — party là sự việc/vật.",
              correct: "which",
              wrong: ["who", "where"],
              distractorNotes: ["For people", "For places"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The house, _____ is near the beach, has a big garden.",
              skillTag: "grammar",
              topicTag,
              explanation: "Which — house là vật.",
              correct: "which",
              wrong: ["who", "when"],
              distractorNotes: ["For people", "For time"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Choose the correct word: The invitation _____ Aunt Hoa sent was beautiful.",
              skillTag: "grammar",
              topicTag,
              explanation: "Which — invitation là vật.",
              correct: "which",
              wrong: ["who", "whose"],
              distractorNotes: ["For people", "Shows possession — too advanced here"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "My cousin Nam, _____ is my age, lives in Da Nang.",
              skillTag: "grammar",
              topicTag,
              explanation: "Who — Nam is a person.",
              correct: "who",
              wrong: ["which", "what"],
              distractorNotes: ["For things", "Not a relative pronoun"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-which-practice",
          title: "Practice: Who or Which",
          instructions: "Fill in each gap with who or which.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: The party [0] was on Saturday had ten guests. | My aunt, [1] lives in Da Nang, invited us. | The cake [2] we ate was delicious.",
              skillTag: "grammar",
              topicTag,
              explanation: "which (party); who (aunt); which (cake) — người vs vật.",
              template:
                "The party [0] was on Saturday had ten guests. My aunt, [1] lives in Da Nang, invited us. The cake [2] we ate was delicious.",
              correctAnswers: ["which", "who", "which"],
              acceptableAnswers: [
                ["which", "Which"],
                ["who", "Who"],
                ["which", "Which"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-which-check",
          title: "Check: Who and Which",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Which for party (thing).",
              correct: "The party, which started at six, was great fun.",
              wrong: [
                "The party, who started at six, was great fun.",
                "The party, where started at six, was great fun.",
              ],
              distractorNotes: ["Who for people", "Where needs a place noun"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The neighbour _____ often helps Aunt Hoa is Linh.",
              skillTag: "grammar",
              topicTag,
              explanation: "Who — neighbour is a person.",
              correct: "who",
              wrong: ["which", "what"],
              distractorNotes: ["For things", "Not relative pronoun"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Mixed: who (cousin) + which (visit).",
              correct: "My cousin, who I have never visited, lives in Hue.",
              wrong: [
                "My cousin, which I have never visited, lives in Hue.",
                "My cousin, who I have never visit, lives in Hue.",
              ],
              distractorNotes: ["Which for person", "Missing past participle"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-which-apply",
          title: "Apply: Build Relative Clauses",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: The party, / which / was / on Saturday, / was / wonderful.",
              skillTag: "grammar",
              topicTag,
              explanation: "The party, which was on Saturday, was wonderful.",
              words: ["The party,", "which", "was", "on Saturday,", "was", "wonderful."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: I / have / never / visited / the city / which / is / by the sea.",
              skillTag: "grammar",
              topicTag,
              explanation: "I have never visited the city which is by the sea.",
              words: [
                "I",
                "have",
                "never",
                "visited",
                "the city",
                "which",
                "is",
                "by the sea.",
              ],
              correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-which-review",
          title: "Review: Present Perfect and Relatives Mix",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Minh has an aunt _____ lives in Da Nang.",
              skillTag: "grammar",
              topicTag,
              explanation: "Who — aunt is a person.",
              correct: "who",
              wrong: ["which", "where"],
              distractorNotes: ["For things", "For places"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Have you ever _____ a family party by the sea?",
              skillTag: "grammar",
              topicTag,
              explanation: "Ever + past participle attended (or been to).",
              correct: "been to",
              wrong: ["went to", "be to"],
              distractorNotes: ["Past simple with ever", "Wrong form"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The visit, _____ Minh enjoyed very much, lasted three days.",
              skillTag: "grammar",
              topicTag,
              explanation: "Which — visit is a thing/event.",
              correct: "which",
              wrong: ["who", "when"],
              distractorNotes: ["For people", "For time only"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
