/** Flyers U1 — listening lessons (3 × 5 exercises). */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptPartyInvite,
  listeningScriptCousinVisit,
  listeningAnswerKeys,
  topicTag,
}) {
  const partyInvite = listeningScriptPartyInvite;
  const cousinVisit = listeningScriptCousinVisit;
  const keysParty = listeningAnswerKeys.partyInvite;
  const keysCousin = listeningAnswerKeys.cousinVisit;

  return [
    {
      slug: "listening-party-invite",
      title: "Lesson 1: Inviting Guests",
      learningObjective:
        "Listen to a dialogue about inviting guests and extract specific information.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-party-learn",
          title: "Learn: Planning the Party",
          instructions: "Listen to Aunt Hoa and Minh. Answer the questions.",
          sortOrder: 0,
          script: partyInvite,
          answerKey: keysParty,
          questions: [
            buildMcq({
              questionText: "What do they need to do for Saturday's party?",
              skillTag: "listening",
              topicTag,
              explanation: "We need to invite more guests — mời thêm khách.",
              correct: "Invite more guests",
              wrong: ["Buy a birthday cake", "Visit Hanoi"],
              distractorNotes: ["Không nhắc mua bánh", "Không trong hội thoại"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Have they invited neighbour Linh yet?",
              skillTag: "listening",
              topicTag,
              explanation: "Yes, I invited her yesterday — đã mời hôm qua.",
              correct: "Yes, yesterday",
              wrong: ["No, not yet", "Yes, on Saturday"],
              distractorNotes: ["Đã mời rồi", "Saturday là giờ party"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-party-practice",
          title: "Practice: Relatives and Time",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: partyInvite,
          answerKey: keysParty,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "How many relatives from Hue has Aunt Hoa invited?",
              skillTag: "listening",
              topicTag,
              explanation: "I've invited five relatives — năm người họ hàng.",
              correct: "Five",
              wrong: ["Three", "Ten"],
              distractorNotes: ["Ba ngày ở lại", "Số guests không nói"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What time does the party start?",
              skillTag: "listening",
              topicTag,
              explanation: "The party starts at six o'clock — 6 giờ.",
              correct: "Six o'clock",
              wrong: ["Seven thirty", "Nine o'clock"],
              distractorNotes: ["Giờ học", "Giờ ngủ"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-party-check",
          title: "Check: Party Invite Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: partyInvite,
          answerKey: keysParty,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What did Linh say when Aunt Hoa invited her?",
              skillTag: "listening",
              topicTag,
              explanation: "She said yes — đồng ý đến.",
              correct: "Yes",
              wrong: ["No", "Maybe next week"],
              distractorNotes: ["Không từ chối", "Không nhắc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh has never been to _____.",
              skillTag: "listening",
              topicTag,
              explanation: "I've never been to a big family party here — chưa từng dự tiệc lớn ở đây.",
              correct: "a big family party here",
              wrong: ["Da Nang", "his aunt's hospital"],
              distractorNotes: ["Đang ở Đà Nẵng", "Không nhắc bệnh viện"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What will they do when guests arrive?",
              skillTag: "listening",
              topicTag,
              explanation: "We will welcome all the guests at the door — chào đón ở cửa.",
              correct: "Welcome them at the door",
              wrong: ["Take them to the beach", "Serve dinner in the kitchen only"],
              distractorNotes: ["Không nhắc biển", "Không chi tiết bữa ăn"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-party-apply",
          title: "Apply: Match Party Facts",
          instructions: "Listen again. Match each detail to the correct fact.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: partyInvite },
          questions: [
            buildMatching({
              questionText: "Match each person or detail from the dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Linh neighbour; Hue relatives; Saturday party; welcome at door.",
              pairs: [
                { left: "Linh", right: "neighbour invited yesterday" },
                { left: "Hue", right: "five relatives invited" },
                { left: "Saturday", right: "party day" },
                { left: "Six o'clock", right: "party start time" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-party-review",
          title: "Review: Party Invite Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: partyInvite,
          answerKey: keysParty,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Who does Minh ask about first?",
              skillTag: "listening",
              topicTag,
              explanation: "Have you invited our neighbour Linh yet? — hỏi về Linh trước.",
              correct: "Neighbour Linh",
              wrong: ["Relatives from Hue", "Uncle Binh"],
              distractorNotes: ["Hỏi sau", "Không nhắc tên"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Can Minh help with the party?",
              skillTag: "listening",
              topicTag,
              explanation: "Can you help? — cô hỏi Minh giúp chào khách.",
              correct: "Yes, Aunt Hoa asks him to help",
              wrong: ["No, he must stay in Hanoi", "Only cousin Nam can help"],
              distractorNotes: ["Minh đang ở Đà Nẵng", "Không nhắc Nam"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-cousin-stay",
      title: "Lesson 2: Cousin Visit Plans",
      learningObjective:
        "Listen for specific information about staying with relatives and future visits.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-cousin-learn",
          title: "Learn: Staying with Nam",
          instructions: "Listen to Minh and his cousin Nam. Answer the questions.",
          sortOrder: 0,
          script: cousinVisit,
          answerKey: keysCousin,
          questions: [
            buildMcq({
              questionText: "What does Nam ask Minh to do?",
              skillTag: "listening",
              topicTag,
              explanation: "Can you stay one more night? — ở thêm một đêm.",
              correct: "Stay one more night",
              wrong: ["Visit Hanoi today", "Invite ten guests"],
              distractorNotes: ["Hanoi là kế hoạch sau", "Party dialogue khác"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Why does Nam want Minh to stay longer?",
              skillTag: "listening",
              topicTag,
              explanation: "My birthday is tomorrow — sinh nhật Nam ngày mai.",
              correct: "Nam's birthday is tomorrow",
              wrong: ["The party is on Sunday", "Minh has never seen the beach"],
              distractorNotes: ["Party thứ Bảy", "Đã thấy beach trong bài đọc"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cousin-practice",
          title: "Practice: How Long Can Minh Stay?",
          instructions: "Listen again. Focus on dates and places.",
          sortOrder: 1,
          script: cousinVisit,
          answerKey: keysCousin,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "How long can Minh stay according to his aunt?",
              skillTag: "listening",
              topicTag,
              explanation: "You can stay until Sunday — đến Chủ nhật.",
              correct: "Until Sunday",
              wrong: ["Until Saturday only", "One more week"],
              distractorNotes: ["Party thứ Bảy", "Không nói một tuần"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Has Nam ever visited Hanoi?",
              skillTag: "listening",
              topicTag,
              explanation: "No, I have never been there — chưa từng đến Hà Nội.",
              correct: "No, never",
              wrong: ["Yes, last summer", "Yes, every year"],
              distractorNotes: ["Không từng", "Không nói thường xuyên"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cousin-check",
          title: "Check: Cousin Dialogue Details",
          instructions: "Listen to the full conversation again.",
          sortOrder: 2,
          script: cousinVisit,
          answerKey: keysCousin,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Minh has never stayed with a cousin for _____.",
              skillTag: "listening",
              topicTag,
              explanation: "For so long — chưa từng ở với cousin lâu thế.",
              correct: "so long",
              wrong: ["one night", "a whole year"],
              distractorNotes: ["Đang xin ở thêm", "Không nói một năm"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When does Nam want to visit Minh?",
              skillTag: "listening",
              topicTag,
              explanation: "I want to visit you next summer — hè tới.",
              correct: "Next summer",
              wrong: ["Tomorrow", "Next Saturday"],
              distractorNotes: ["Sinh nhật ngày mai", "Party thứ Bảy"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who will welcome Nam if he visits Hanoi?",
              skillTag: "listening",
              topicTag,
              explanation: "My neighbour Linh will welcome you — Linh chào đón.",
              correct: "Neighbour Linh",
              wrong: ["Aunt Hoa", "Uncle Binh"],
              distractorNotes: ["Ở Đà Nẵng", "Ở Đà Nẵng"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-cousin-apply",
          title: "Apply: Order the Plans",
          instructions: "Put the ideas in the order they are discussed.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          content: { script: cousinVisit },
          questions: [
            buildMcq({
              questionText:
                "Correct order: (1) visit Hanoi (2) stay until Sunday (3) stay one more night",
              skillTag: "listening",
              topicTag,
              explanation: "Stay one more night → until Sunday → visit Hanoi next summer.",
              correct: "3 → 2 → 1",
              wrong: ["1 → 2 → 3", "2 → 1 → 3"],
              distractorNotes: ["Hanoi là kế hoạch sau", "Sunday trước one more night"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cousin-review",
          title: "Review: Cousin Visit Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: cousinVisit,
          answerKey: keysCousin,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "What do Minh and Nam plan at the end?",
              skillTag: "listening",
              topicTag,
              explanation: "Let's plan the visit now — lên kế hoạch thăm Hà Nội.",
              correct: "Nam's visit to Hanoi",
              wrong: ["Another party in Da Nang", "A trip to Hue"],
              distractorNotes: ["Party đã có", "Hue chỉ trong dialogue mời khách"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh and Nam want to _____ together in Hanoi.",
              skillTag: "listening",
              topicTag,
              explanation: "We can celebrate together — ăn mừng cùng nhau.",
              correct: "celebrate",
              wrong: ["invite five relatives", "stay by the sea"],
              distractorNotes: ["Dialogue party khác", "Đà Nẵng gần biển"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-family-review",
      title: "Lesson 3: Review Both Dialogues",
      learningObjective:
        "Extract specific information across two family dialogues.",
      estimatedMinutes: 22,
      exercises: [
        buildListeningExercise({
          slug: "listening-review-learn",
          title: "Learn: Party Invite Reminder",
          instructions: "Listen to the party invite dialogue again.",
          sortOrder: 0,
          script: partyInvite,
          answerKey: keysParty,
          questions: [
            buildMcq({
              questionText: "Where does the party invite dialogue take place?",
              skillTag: "listening",
              topicTag,
              explanation: "Aunt Hoa's kitchen in Da Nang — bếp cô ở Đà Nẵng.",
              correct: "Aunt Hoa's kitchen in Da Nang",
              wrong: ["Minh's bedroom in Hanoi", "On the beach"],
              distractorNotes: ["Cousin dialogue setting", "Không trong audio"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Relatives from _____ are coming to the party.",
              skillTag: "listening",
              topicTag,
              explanation: "Your relatives from Hue — họ hàng từ Huế.",
              correct: "Hue",
              wrong: ["Hanoi", "London"],
              distractorNotes: ["Minh sống Hà Nội", "Không nhắc"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-practice",
          title: "Practice: Cousin Dialogue Reminder",
          instructions: "Listen to the cousin dialogue again.",
          sortOrder: 1,
          script: cousinVisit,
          answerKey: keysCousin,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Where are Minh and Nam talking?",
              skillTag: "listening",
              topicTag,
              explanation: "Minh's bedroom in Da Nang — phòng ngủ buổi tối.",
              correct: "In a bedroom in Da Nang",
              wrong: ["In Aunt Hoa's kitchen", "At school in Hanoi"],
              distractorNotes: ["Party dialogue", "Không ở trường"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Nam has never been to _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Have you ever visited Hanoi? — No, never been there.",
              correct: "Hanoi",
              wrong: ["Da Nang", "Hue"],
              distractorNotes: ["Nam sống Đà Nẵng", "Hue trong dialogue khác"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-check",
          title: "Check: Mixed Family Listening",
          instructions: "Listen to the cousin dialogue. Harder questions.",
          sortOrder: 2,
          script: cousinVisit,
          answerKey: keysCousin,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which detail is ONLY in the party invite dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Five relatives from Hue — chỉ có khi mời khách.",
              correct: "Five relatives from Hue",
              wrong: ["Stay until Sunday", "Plan a visit to Hanoi"],
              distractorNotes: ["Cousin dialogue", "Cousin dialogue"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Both dialogues mention _____ Linh.",
              skillTag: "listening",
              topicTag,
              explanation: "Neighbour Linh in both — mời tiệc và chào đón ở Hà Nội.",
              correct: "neighbour",
              wrong: ["cousin", "aunt"],
              distractorNotes: ["Nam là cousin", "Hoa là aunt"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-review-apply",
          title: "Apply: Match Dialogue to Fact",
          instructions: "Listen, then match each fact to the correct dialogue.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: cousinVisit },
          questions: [
            buildMatching({
              questionText: "Match facts to Party invite or Cousin visit dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Party: six o'clock, welcome guests; Cousin: Sunday, next summer.",
              pairs: [
                { left: "Party starts at six o'clock", right: "Party invite dialogue" },
                { left: "Minh can stay until Sunday", right: "Cousin visit dialogue" },
                { left: "Welcome guests at the door", right: "Party invite dialogue" },
                { left: "Visit Hanoi next summer", right: "Cousin visit dialogue" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-family-review-final",
          title: "Review: Both Dialogues Mix",
          instructions: "Listen to the party invite dialogue. Final review.",
          sortOrder: 4,
          script: partyInvite,
          answerKey: keysParty,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which time is from the PARTY dialogue only?",
              skillTag: "listening",
              topicTag,
              explanation: "Six o'clock party start — chỉ trong hội thoại mời khách.",
              correct: "Six o'clock (party start)",
              wrong: ["Until Sunday", "Next summer"],
              distractorNotes: ["Cousin dialogue", "Cousin dialogue"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh says he has never been to a big family party _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Here — ở Đà Nẵng, chưa từng dự tiệc lớn tại đây.",
              correct: "here",
              wrong: ["in Hanoi", "with cousin Nam"],
              distractorNotes: ["Đang nói về Đà Nẵng", "Đã ở với Nam"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
