/** Flyers U1 — speaking lessons (3 × 5 exercises; only Check is AI). */

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [visitCheck, partyCheck, familyCheck] = speakingChecks;

  return [
    {
      slug: "speaking-visit-relatives",
      title: "Lesson 1: Talk About Visiting Relatives",
      learningObjective:
        "Choose appropriate spoken phrases about visiting aunt, uncle and cousin.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-visit-learn",
          title: "Learn: What to Say About a Visit",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Someone asks: Have you ever visited Da Nang? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes + past visit — trả lời kinh nghiệm tự nhiên.",
              correct: "Yes, I visited my aunt there last month.",
              wrong: ["Yes, I visit my aunt last month.", "Visit Da Nang yes."],
              distractorNotes: ["Wrong tense", "Not a sentence"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best answer: Who did you stay with?",
              skillTag: "speaking",
              topicTag,
              explanation: "I stayed with my aunt, uncle and cousin — đầy đủ câu.",
              correct: "I stayed with my aunt, uncle and cousin.",
              wrong: ["Stay aunt uncle.", "I staying with my cousin."],
              distractorNotes: ["Fragment", "Wrong form"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-visit-practice",
          title: "Practice: Visit Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Have you ever stayed by the sea? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "No, never + before — present perfect chuẩn.",
              correct: "No, I have never stayed by the sea before.",
              wrong: ["No, I never have stayed by sea.", "No, never I stayed sea."],
              distractorNotes: ["Wrong order", "Wrong order"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What did your cousin show you? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "My cousin showed me the beach — câu hoàn chỉnh.",
              correct: "My cousin showed me the beach.",
              wrong: ["Cousin beach show.", "My cousin showing me beach."],
              distractorNotes: ["Fragment", "Wrong tense"],
              difficultyRating: 2,
            }),
          ],
        }),
        visitCheck,
        buildExercise({
          slug: "speaking-visit-apply",
          title: "Apply: Quick Visit Replies",
          instructions: "Choose the best short spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Aunt Hoa asks: Did you enjoy your stay? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes + want to visit again — phản hồi tích cực đầy đủ.",
              correct: "Yes, I loved it. I want to visit again next summer.",
              wrong: ["Yes enjoy stay.", "I never visit again yes."],
              distractorNotes: ["Too short", "Opposite meaning"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-visit-review",
          title: "Review: Visit Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "How long did you stay? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "I stayed for three days — thời gian rõ ràng.",
              correct: "I stayed for three days.",
              wrong: ["Stay three days.", "I staying for three day."],
              distractorNotes: ["Fragment", "Wrong grammar"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Describe your aunt. Best phrase:",
              skillTag: "speaking",
              topicTag,
              explanation: "My aunt, who works at a hospital, welcomed me — mệnh đề who.",
              correct: "My aunt, who works at a hospital, welcomed me.",
              wrong: ["My aunt which hospital works.", "Aunt who she doctor."],
              distractorNotes: ["Which for people", "Extra pronoun"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-party-guests",
      title: "Lesson 2: Talk About a Party",
      learningObjective:
        "Use invite, guest, welcome and celebrate in short spoken answers.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-party-learn",
          title: "Learn: Party Speaking Phrases",
          instructions: "Choose the best thing to say about a party.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Have you ever been to a big family party? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes + when/where — trả lời đầy đủ kinh nghiệm.",
              correct: "Yes, I went to my uncle's birthday party in Da Nang.",
              wrong: ["Yes party big family.", "I have go to party last Saturday."],
              distractorNotes: ["Fragment", "Wrong tense mix"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Who did you invite? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "I invited our neighbour and some relatives — cụ thể.",
              correct: "I invited our neighbour and five relatives.",
              wrong: ["Invite neighbour relatives.", "I inviting neighbour yesterday."],
              distractorNotes: ["Not a sentence", "Wrong form"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-party-practice",
          title: "Practice: Guests and Welcome",
          instructions: "Choose the correct spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "What time does the party start? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "It starts at six o'clock — giờ rõ ràng.",
              correct: "It starts at six o'clock on Saturday.",
              wrong: ["Party six Saturday.", "It start at six on Saturday."],
              distractorNotes: ["Fragment", "Wrong verb form"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Did you help welcome the guests? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, I helped welcome people at the door — chi tiết.",
              correct: "Yes, I helped welcome guests at the door.",
              wrong: ["Yes welcome I guests door.", "Yes, I welcoming guests."],
              distractorNotes: ["Wrong order", "Wrong tense"],
              difficultyRating: 2,
            }),
          ],
        }),
        partyCheck,
        buildExercise({
          slug: "speaking-party-apply",
          title: "Apply: Choose the Best Party Reply",
          instructions: "Pick the most natural spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "How did you celebrate your uncle's birthday?",
              skillTag: "speaking",
              topicTag,
              explanation: "We ate cake and listened to music — mô tả cụ thể.",
              correct: "We ate cake and listened to music with many guests.",
              wrong: ["Celebrate cake music uncle.", "We celebrating with cake musics."],
              distractorNotes: ["Not coherent", "Wrong form"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-party-review",
          title: "Review: Party Speaking Quiz",
          instructions: "Choose the best answer using party vocabulary.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "How many guests came to the party? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "About ten guests — số lượng ước lượng tự nhiên.",
              correct: "There were about ten guests and many relatives.",
              wrong: ["Ten guest relative party.", "There was ten guests come."],
              distractorNotes: ["Not a sentence", "Agreement error"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Have you ever invited a neighbour to a party? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, I invited her yesterday — present perfect/past phù hợp.",
              correct: "Yes, I invited my neighbour Linh yesterday.",
              wrong: ["Yes, I have invite neighbour yesterday.", "Invite neighbour yes party."],
              distractorNotes: ["Wrong participle", "Fragment"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-extended-family",
      title: "Lesson 3: Describe Extended Family",
      learningObjective:
        "Describe relatives and neighbours in extended spoken answers.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "speaking-family-learn",
          title: "Learn: Family and Neighbour Phrases",
          instructions: "Choose the best thing to say about your extended family.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Tell me about a relative in another city. Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "My aunt, who lives in Da Nang, is a doctor — who-clause.",
              correct: "My aunt Hoa, who lives in Da Nang, works at a hospital.",
              wrong: ["Aunt Da Nang hospital.", "My aunt which live Da Nang."],
              distractorNotes: ["Too short", "Which for people"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Do you know your neighbours well? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, my neighbour is my good friend — câu đầy đủ.",
              correct: "Yes, my neighbour Linh is my good friend.",
              wrong: ["Neighbour friend yes.", "Yes, neighbour Linh friend me."],
              distractorNotes: ["Fragment", "Wrong order"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-family-practice",
          title: "Practice: Cousins and Relatives",
          instructions: "Choose the best spoken answers.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Do you have a cousin who lives near you? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "My cousin lives in another city — trả lời thật, câu hoàn chỉnh.",
              correct: "No, my cousin Nam lives in Da Nang, not near me.",
              wrong: ["Cousin Nam Da Nang no near.", "No cousin I have near."],
              distractorNotes: ["Fragment", "Wrong order"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Have you ever invited a neighbour to your home? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, I invited her to a birthday party — chi tiết.",
              correct: "Yes, I invited her to a small party last month.",
              wrong: ["Yes invite neighbour home.", "I have never invite neighbour."],
              distractorNotes: ["Fragment", "Wrong form"],
              difficultyRating: 2,
            }),
          ],
        }),
        familyCheck,
        buildExercise({
          slug: "speaking-family-apply",
          title: "Apply: Tell About Your Family",
          instructions: "Choose the best extended family description.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best short description of extended family:",
              skillTag: "speaking",
              topicTag,
              explanation: "Connected ideas: aunt + cousin + neighbour + experience.",
              correct:
                "I have an aunt in Da Nang and a cousin my age. My neighbour Linh, who is a good friend, sometimes celebrates with us.",
              wrong: [
                "Aunt cousin neighbour party visit.",
                "I have aunt who she cousin neighbour Linh.",
              ],
              distractorNotes: ["Not sentences", "Ungrammatical"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-family-review",
          title: "Review: Extended Family Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Who is the oldest relative you mentioned? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "My grandmother, who is seventy, is the oldest — who-clause.",
              correct: "My grandmother, who is seventy, is the oldest.",
              wrong: ["Grandmother seventy oldest.", "My grandmother which oldest."],
              distractorNotes: ["Fragment", "Which for people"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Compare experiences: I have never… / I have already… Best pair:",
              skillTag: "speaking",
              topicTag,
              explanation: "Never stayed so long; already promised to visit — như Minh.",
              correct:
                "I have never stayed with a cousin for so long. I have already promised to visit again.",
              wrong: [
                "I never have already stayed cousin visit.",
                "Already never I cousin stay visit.",
              ],
              distractorNotes: ["Meaningless", "Wrong order"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
