/** Flyers U1 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-extended-family",
      title: "Lesson 1: Extended Family",
      learningObjective:
        "Recognise and use cousin, aunt, uncle and relative in sentences about family.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-family-learn",
          title: "Learn: Extended Family Words",
          instructions: "Read each clue. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Your mother's sister is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Aunt (cô/dì) — chị/em gái của mẹ hoặc bố.",
              correct: "aunt",
              wrong: ["cousin", "neighbour"],
              distractorNotes: ["Child of your aunt", "Lives next door, not family"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Your father's brother is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Uncle (chú/bác) — anh/em trai của bố hoặc mẹ.",
              correct: "uncle",
              wrong: ["guest", "aunt"],
              distractorNotes: ["Party visitor", "Female relative"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Nam is the son of Minh's aunt. Nam is Minh's _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cousin (anh/chị/em họ) — con của cô/chú/bác.",
              correct: "cousin",
              wrong: ["neighbour", "uncle"],
              distractorNotes: ["Not in the family", "Older male relative"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Aunts, uncles and cousins are all _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Relative (người thân) — thành viên trong họ hàng.",
              correct: "relatives",
              wrong: ["guests", "neighbours"],
              distractorNotes: ["Party visitors", "People next door"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-family-practice",
          title: "Practice: Match Family Words",
          instructions: "Match each word to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the extended family words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mỗi từ chỉ một mối quan hệ gia đình cụ thể.",
              pairs: [
                { left: "aunt", right: "your parent's sister" },
                { left: "uncle", right: "your parent's brother" },
                { left: "cousin", right: "your aunt's or uncle's child" },
                { left: "relative", right: "a person in your family" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-family-check",
          title: "Check: Family Words Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh is visiting his _____ Hoa in Da Nang.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Aunt Hoa — cô/dì của Minh ở Đà Nẵng.",
              correct: "aunt",
              wrong: ["cousin", "neighbour"],
              distractorNotes: ["Nam is the cousin", "Linh is the neighbour"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Uncle Binh is Minh's _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Uncle (chú/bác) — anh/em trai của bố hoặc mẹ.",
              correct: "uncle",
              wrong: ["cousin", "guest"],
              distractorNotes: ["Child of aunt/uncle", "Party visitor"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They invited many _____ to the birthday party.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Relatives (người thân) — họ hàng được mời dự tiệc.",
              correct: "relatives",
              wrong: ["neighbours only", "homework"],
              distractorNotes: ["Not just neighbours", "Not a family word"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-family-apply",
          title: "Apply: Complete Family Sentences",
          instructions: "Fill in each gap with the correct word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh visited his [0] in Da Nang. | His [1] Nam is the same age. | Uncle Binh is Minh's father's [2].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "aunt; cousin; brother — extended family relationships.",
              template:
                "Minh visited his [0] in Da Nang. His [1] Nam is the same age. Uncle Binh is Minh's father's [2].",
              correctAnswers: ["aunt", "cousin", "brother"],
              acceptableAnswers: [
                ["aunt", "Aunt"],
                ["cousin", "Cousin"],
                ["brother", "Brother"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-family-review",
          title: "Review: Extended Family Mix",
          instructions: "Mixed review from this lesson. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Your aunt's daughter is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cousin (anh/chị/em họ) — con của cô/dì.",
              correct: "cousin",
              wrong: ["uncle", "neighbour"],
              distractorNotes: ["Male relative", "Not family"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh has never seen so many _____!",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cousins — nhiều anh chị em họ ở bữa tiệc.",
              correct: "cousins",
              wrong: ["guests only", "neighbours"],
              distractorNotes: ["Text mentions cousins specifically", "Next-door people"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word means 'a person in your family'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Relative (người thân) — thành viên họ hàng.",
              correct: "relative",
              wrong: ["guest", "invite"],
              distractorNotes: ["Party visitor", "Verb, not a person"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-visits-and-guests",
      title: "Lesson 2: Visits, Guests and Neighbours",
      learningObjective:
        "Use neighbour, guest, invite and visit to talk about social visits.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-visits-learn",
          title: "Learn: Visits and Guests",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Linh lives next door. She is Minh's _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Neighbour (hàng xóm) — người sống bên cạnh.",
              correct: "neighbour",
              wrong: ["cousin", "relative"],
              distractorNotes: ["Family member", "Broader family term"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "People who come to a party are called _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Guests (khách) — người được mời đến.",
              correct: "guests",
              wrong: ["cousins", "homework"],
              distractorNotes: ["Only family", "Not a social word"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Aunt Hoa wants to _____ Linh to the party.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Invite (mời) — gửi lời mời đến bữa tiệc.",
              correct: "invite",
              wrong: ["visit", "stay"],
              distractorNotes: ["Go to see someone", "Remain overnight"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh _____ his aunt and uncle in Da Nang last month.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Visited (thăm) — đi gặp người thân ở nơi khác.",
              correct: "visited",
              wrong: ["invited", "celebrated"],
              distractorNotes: ["Ask someone to come", "Have a party"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-visits-practice",
          title: "Practice: Match Visits and Guests",
          instructions: "Match each word to the correct meaning or situation.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match visits, guests and neighbours.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ghép từ với nghĩa hoặc tình huống phù hợp.",
              pairs: [
                { left: "neighbour", right: "person who lives near your home" },
                { left: "guest", right: "person invited to your house or party" },
                { left: "invite", right: "ask someone to come to an event" },
                { left: "visit", right: "go to see someone at their home" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-visits-check",
          title: "Check: Visits Quiz",
          instructions: "Choose the best answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Have you invited our _____ Linh yet?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Neighbour Linh — hàng xóm được mời dự tiệc.",
              correct: "neighbour",
              wrong: ["cousin", "guest"],
              distractorNotes: ["Nam is the cousin", "Linh is not yet a guest"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They will _____ all the guests at the door.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Welcome (chào đón) — đón khách ở cửa.",
              correct: "welcome",
              wrong: ["invite", "visit"],
              distractorNotes: ["Already invited", "Go to see someone"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh has never _____ Da Nang before.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Visited (thăm) — kinh nghiệm đi thăm Đà Nẵng.",
              correct: "visited",
              wrong: ["invited", "stayed"],
              distractorNotes: ["Ask someone to come", "Remain there — different focus"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-visits-apply",
          title: "Apply: Visit Sentences",
          instructions: "Complete the sentences about Minh's visit.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Aunt Hoa [0] Linh to the party. | Minh [1] his aunt last month. | Ten [2] came on Saturday.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "invited; visited; guests — mời, thăm, khách.",
              template:
                "Aunt Hoa [0] Linh to the party. Minh [1] his aunt last month. Ten [2] came on Saturday.",
              correctAnswers: ["invited", "visited", "guests"],
              acceptableAnswers: [
                ["invited", "Invited"],
                ["visited", "Visited"],
                ["guests", "Guests"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-visits-review",
          title: "Review: Visits and Guests Mix",
          instructions: "Mixed review. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "A person who lives next to you is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Neighbour (hàng xóm) — ở bên cạnh nhà bạn.",
              correct: "neighbour",
              wrong: ["guest", "relative"],
              distractorNotes: ["Party visitor", "Family member"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We need to _____ more people to the party.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Invite (mời) thêm người đến bữa tiệc.",
              correct: "invite",
              wrong: ["visit", "stay"],
              distractorNotes: ["Go see someone", "Remain overnight"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "I want to _____ my cousin in Hanoi next summer.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Visit (thăm) — đi gặp anh em họ.",
              correct: "visit",
              wrong: ["welcome", "celebrate"],
              distractorNotes: ["Receive at home", "Have a party"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-stay-and-celebrate",
      title: "Lesson 3: Staying and Celebrating",
      learningObjective:
        "Use stay, welcome, party and celebrate to talk about visits and events.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-celebrate-learn",
          title: "Learn: Stay and Celebrate",
          instructions: "Choose the word that best completes each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh will _____ with his aunt for three days.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Stay (ở lại) — ở nhà cô/chú vài ngày.",
              correct: "stay",
              wrong: ["invite", "visit"],
              distractorNotes: ["Ask someone to come", "Go for a short trip"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "They _____ him warmly at the door.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Welcomed (chào đón) — đón tiếp nồng nhiệt.",
              correct: "welcomed",
              wrong: ["invited", "visited"],
              distractorNotes: ["Sent an invitation", "Went to see"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The family had a _____ on Saturday evening.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Party (bữa tiệc) — tổ chức vào tối thứ Bảy.",
              correct: "party",
              wrong: ["neighbour", "relative"],
              distractorNotes: ["Person, not event", "Family member"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "They _____ Uncle Binh's birthday with cake and music.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Celebrated (ăn mừng) — tổ chức sinh nhật.",
              correct: "celebrated",
              wrong: ["visited", "stayed"],
              distractorNotes: ["Went to see", "Remained overnight"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-celebrate-practice",
          title: "Practice: Match Stay and Celebrate",
          instructions: "Match each word to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match staying and celebrating words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Stay/welcome/party/celebrate — bốn từ về thăm và tiệc.",
              pairs: [
                { left: "stay", right: "remain at someone's home overnight" },
                { left: "welcome", right: "greet someone when they arrive" },
                { left: "party", right: "a social event with food and friends" },
                { left: "celebrate", right: "do something special for a happy occasion" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-celebrate-check",
          title: "Check: Stay and Celebrate Challenge",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh has never _____ by the sea before.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Stayed (ở lại) — chưa từng ở gần biển.",
              correct: "stayed",
              wrong: ["invited", "visited"],
              distractorNotes: ["Ask to come", "Short visit — text says stay"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Can you _____ one more night, Minh?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Stay (ở thêm) — ở lại thêm một đêm.",
              correct: "stay",
              wrong: ["visit", "invite"],
              distractorNotes: ["Go see someone", "Ask someone to come"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence uses celebrate correctly?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Celebrate + occasion — celebrate a birthday.",
              correct: "We celebrate birthdays with cake.",
              wrong: [
                "We celebrate to the party.",
                "I celebrate my aunt yesterday.",
              ],
              distractorNotes: ["Wrong preposition", "Wrong tense with yesterday"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-celebrate-apply",
          title: "Apply: Party and Visit Sentences",
          instructions: "Fill in with stay, welcome, party or celebrate.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: They [0] all the guests at the door. | The [1] was on Saturday. | We [2] Uncle Binh's birthday.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "welcomed; party; celebrated — chào đón, tiệc, ăn mừng.",
              template:
                "They [0] all the guests at the door. The [1] was on Saturday. We [2] Uncle Binh's birthday.",
              correctAnswers: ["welcomed", "party", "celebrated"],
              acceptableAnswers: [
                ["welcomed", "Welcomed", "welcome", "Welcome"],
                ["party", "Party"],
                ["celebrated", "Celebrated"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-celebrate-review",
          title: "Review: Unit Vocabulary Mix",
          instructions: "Choose the best word from the whole unit.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Minh _____ for three days with his aunt in Da Nang.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Stayed (ở lại) — ba ngày ở nhà cô.",
              correct: "stayed",
              wrong: ["invited", "welcomed"],
              distractorNotes: ["Ask to come", "Greet at door"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh is the _____ who often helps Aunt Hoa.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Neighbour (hàng xóm) — người hay giúp cô Hoa.",
              correct: "neighbour",
              wrong: ["cousin", "guest"],
              distractorNotes: ["Family member", "Party visitor"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Many _____ came to the family party on Saturday.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Relatives (người thân) — họ hàng đến dự tiệc.",
              correct: "relatives",
              wrong: ["parties", "visits"],
              distractorNotes: ["Events, not people", "Actions, not people"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
