/** Starters U3 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-adjective-noun",
      title: "Lesson 1: Adjective + Noun",
      learningObjective:
        "Use colour adjectives before nouns: a red shirt, blue trousers.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-adj-noun-learn",
          title: "Learn: Colour Before Noun",
          instructions: "Choose the correct word order.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Which phrase is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "A red shirt — màu đứng TRƯỚC danh từ trong tiếng Anh.",
              correct: "a red shirt",
              wrong: ["a shirt red", "red a shirt"],
              distractorNotes: ["Thứ tự tiếng Việt — sai", "Mạo từ sai vị trí"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mai has _____ .",
              skillTag: "grammar",
              topicTag,
              explanation: "Blue trousers — màu + danh từ.",
              correct: "blue trousers",
              wrong: ["trousers blue", "a trousers blue"],
              distractorNotes: ["Thứ tự sai", "Trousers không cần a"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Anna wears _____ .",
              skillTag: "grammar",
              topicTag,
              explanation: "A yellow hat — a + màu + danh từ số ít.",
              correct: "a yellow hat",
              wrong: ["a hat yellow", "yellow hat a"],
              distractorNotes: ["Thứ tự sai", "Mạo từ cuối câu"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which phrase describes Mai's jacket?",
              skillTag: "grammar",
              topicTag,
              explanation: "A black jacket — màu trước jacket.",
              correct: "a black jacket",
              wrong: ["a jacket black", "black a jacket"],
              distractorNotes: ["Thứ tự sai", "Mạo từ sai"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-adj-noun-practice",
          title: "Practice: Adjective + Noun Gap Fill",
          instructions: "Complete with the correct colour + noun order.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: a [0] dress | [1] shoes | a [2] hat",
              skillTag: "grammar",
              topicTag,
              explanation: "green dress; yellow shoes; white hat — màu trước danh từ.",
              template: "a [0] dress | [1] shoes | a [2] hat",
              correctAnswers: ["green", "yellow", "white"],
              acceptableAnswers: [
                ["green", "Green"],
                ["yellow", "Yellow"],
                ["white", "White"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-adj-noun-check",
          title: "Check: Adjective + Noun Quiz",
          instructions: "Choose the best answer. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Mum says: Put on your _____ .",
              skillTag: "grammar",
              topicTag,
              explanation: "Red shirt — màu trước shirt (listening script).",
              correct: "red shirt",
              wrong: ["shirt red", "a shirt is red"],
              distractorNotes: ["Thứ tự sai", "Thừa is"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which phrase is wrong?",
              skillTag: "grammar",
              topicTag,
              explanation: "Dress green sai — phải green dress hoặc a green dress.",
              correct: "a dress green",
              wrong: ["a green dress", "green shoes"],
              distractorNotes: ["Đúng", "Đúng — shoes số nhiều không cần a"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "At the shop: a _____ jacket",
              skillTag: "grammar",
              topicTag,
              explanation: "Blue jacket — Look at this blue jacket.",
              correct: "blue",
              wrong: ["jacket", "shop"],
              distractorNotes: ["Danh từ, không phải màu", "Không phải màu"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-adj-noun-apply",
          title: "Apply: Order Adjective + Noun",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: a / red / shirt",
              skillTag: "grammar",
              topicTag,
              explanation: "A red shirt — a + màu + danh từ.",
              words: ["a", "red", "shirt"],
              correctOrder: [0, 1, 2],
            }),
            buildSentenceOrdering({
              questionText: "Make: blue / trousers",
              skillTag: "grammar",
              topicTag,
              explanation: "Blue trousers — màu + danh từ (không cần a).",
              words: ["blue", "trousers"],
              correctOrder: [0, 1],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-adj-noun-review",
          title: "Review: Adjective + Noun Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best phrase for Nam's shoes:",
              skillTag: "grammar",
              topicTag,
              explanation: "Blue shoes — màu trước danh từ.",
              correct: "blue shoes",
              wrong: ["shoes blue", "a blue shoes"],
              distractorNotes: ["Thứ tự sai", "Shoes số nhiều — không a"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "I like the _____ shirt.",
              skillTag: "grammar",
              topicTag,
              explanation: "Yellow shirt — the + màu + danh từ.",
              correct: "yellow",
              wrong: ["shirt", "like"],
              distractorNotes: ["Danh từ đã có sau", "Động từ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We buy _____ trousers.",
              skillTag: "grammar",
              topicTag,
              explanation: "White trousers — màu trước trousers.",
              correct: "white",
              wrong: ["trousers", "buy"],
              distractorNotes: ["Danh từ sau rồi", "Động từ"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-verb-be-description",
      title: "Lesson 2: Verb Be for Description",
      learningObjective:
        "Use It is / They are + colour to describe clothes.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "grammar-be-learn",
          title: "Learn: It is / They are + Colour",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "My dress _____ green.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is — dress số ít → It is / My dress is.",
              correct: "is",
              wrong: ["are", "am"],
              distractorNotes: ["Are cho số nhiều", "Am chỉ với I"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "My shoes _____ yellow.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are — shoes số nhiều → are.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is cho số ít", "Am chỉ với I"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best answer: What colour is your hat? — _____",
              skillTag: "grammar",
              topicTag,
              explanation: "It is white. — trả lời màu mũ.",
              correct: "It is white.",
              wrong: ["They are white.", "It white is."],
              distractorNotes: ["Hat số ít — they sai", "Sai thứ tự"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The trousers _____ blue.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are — trousers luôn số nhiều → are.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is cho số ít", "Am với I"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-be-practice",
          title: "Practice: is/are + Colour Gap Fill",
          instructions: "Complete with is or are and a colour.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: My dress [0] green. | My shoes [1] yellow. | It [2] white.",
              skillTag: "grammar",
              topicTag,
              explanation: "is (dress); are (shoes); is (hat/it).",
              template: "My dress [0] green. My shoes [1] yellow. It [2] white.",
              correctAnswers: ["is", "are", "is"],
              acceptableAnswers: [["is"], ["are"], ["is"]],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-be-check",
          title: "Check: Verb Be Description Quiz",
          instructions: "Choose the correct form. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Mai's jacket _____ black.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is — jacket số ít.",
              correct: "is",
              wrong: ["are", "am"],
              distractorNotes: ["Are số nhiều", "Am với I"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "They are blue. — shoes/trousers số nhiều.",
              correct: "They are blue.",
              wrong: ["They is blue.", "It are blue."],
              distractorNotes: ["They + is sai", "It + are sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "\"It is green!\" says Mai. \"It\" means her _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Dress — What colour is your dress? It is green!",
              correct: "dress",
              wrong: ["shoes", "hat"],
              distractorNotes: ["Giày vàng", "Mũ trắng"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-be-apply",
          title: "Apply: Order Description Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: It / is / green.",
              skillTag: "grammar",
              topicTag,
              explanation: "It is green. — mô tả màu một vật.",
              words: ["It", "is", "green."],
              correctOrder: [0, 1, 2],
            }),
            buildSentenceOrdering({
              questionText: "Make: My / shoes / are / yellow.",
              skillTag: "grammar",
              topicTag,
              explanation: "My shoes are yellow. — số nhiều + are.",
              words: ["My", "shoes", "are", "yellow."],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-be-review",
          title: "Review: Verb Be Description Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Nam's shoes _____ blue.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are — shoes số nhiều.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is số ít", "Am với I"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What colour _____ your dress?",
              skillTag: "grammar",
              topicTag,
              explanation: "Is — dress số ít → What colour is…?",
              correct: "is",
              wrong: ["are", "am"],
              distractorNotes: ["Are với số nhiều", "Am với I"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The shop shoes _____ black.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are — shoes luôn số nhiều.",
              correct: "are",
              wrong: ["is", "be"],
              distractorNotes: ["Is số ít", "Be không đúng mẫu Starters"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-colours-clothes-mixed",
      title: "Lesson 3: Mixed Grammar",
      learningObjective:
        "Use adjective + noun and is/are descriptions together in context.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "grammar-mixed-learn",
          title: "Learn: Mixed Patterns",
          instructions: "Choose the correct word or phrase.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "_____ colour is your dress?",
              skillTag: "grammar",
              topicTag,
              explanation: "What colour — câu hỏi màu chuẩn.",
              correct: "What",
              wrong: ["How", "Where"],
              distractorNotes: ["How hỏi cách/tuổi", "Where hỏi nơi"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "She has _____ .",
              skillTag: "grammar",
              topicTag,
              explanation: "A blue dress — màu trước danh từ.",
              correct: "a blue dress",
              wrong: ["a dress blue", "blue a dress"],
              distractorNotes: ["Thứ tự sai", "Mạo từ sai"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Your dress _____ yellow.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is — dress số ít (listening script).",
              correct: "is",
              wrong: ["are", "am"],
              distractorNotes: ["Are số nhiều", "Am với I"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best reply: What colour are your shoes? — _____",
              skillTag: "grammar",
              topicTag,
              explanation: "They are green. — shoes số nhiều.",
              correct: "They are green.",
              wrong: ["It is green.", "They is green."],
              distractorNotes: ["It số ít", "They + is sai"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-practice",
          title: "Practice: Mixed Gap Fill",
          instructions: "Complete with What, is, are or a colour.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] colour is your hat? | It [1] white. | My shoes [2] black.",
              skillTag: "grammar",
              topicTag,
              explanation: "What; is; are — hỏi màu và mô tả.",
              template: "[0] colour is your hat? It [1] white. My shoes [2] black.",
              correctAnswers: ["What", "is", "are"],
              acceptableAnswers: [
                ["What", "what"],
                ["is"],
                ["are"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-check",
          title: "Check: Mixed Grammar Quiz",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Her dress is green. — Her + danh từ + is + màu.",
              correct: "Her dress is green.",
              wrong: ["Her green is dress.", "Her dress green is."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum: Is your hat white? Mai: _____",
              skillTag: "grammar",
              topicTag,
              explanation: "Yes. It is white. — khẳng định + mô tả.",
              correct: "Yes. It is white.",
              wrong: ["Yes. They are white.", "Yes. It white is."],
              distractorNotes: ["Hat số ít", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "I like the red hat. The hat _____ red.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is — hat số ít.",
              correct: "is",
              wrong: ["are", "am"],
              distractorNotes: ["Are số nhiều", "Am với I"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-apply",
          title: "Apply: Order Mixed Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: What / colour / is / your / dress?",
              skillTag: "grammar",
              topicTag,
              explanation: "What colour is your dress? — câu hỏi màu.",
              words: ["What", "colour", "is", "your", "dress?"],
              correctOrder: [0, 1, 2, 3, 4],
            }),
            buildSentenceOrdering({
              questionText: "Make: Put / on / your / red / shirt.",
              skillTag: "grammar",
              topicTag,
              explanation: "Put on your red shirt. — mệnh lệnh + màu + danh từ.",
              words: ["Put", "on", "your", "red", "shirt."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-review",
          title: "Review: Mixed Grammar",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Anna's hat _____ yellow.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is — hat số ít.",
              correct: "is",
              wrong: ["are", "am"],
              distractorNotes: ["Are số nhiều", "Am với I"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which question asks about colour?",
              skillTag: "grammar",
              topicTag,
              explanation: "What colour is your dress? — hỏi màu.",
              correct: "What colour is your dress?",
              wrong: ["Where is your dress?", "How many dresses?"],
              distractorNotes: ["Hỏi nơi", "Hỏi số lượng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai wears a white hat. The hat _____ white.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is — hat số ít, lặp lại mô tả.",
              correct: "is",
              wrong: ["are", "have"],
              distractorNotes: ["Are số nhiều", "Have = sở hữu số lượng"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
