/** Starters U3 — listening lessons (3 × 5 exercises). Text-only: colour + clothes in dialogue. */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptGettingDressed,
  listeningScriptClothesShopping,
  listeningAnswerKeys,
  topicTag,
}) {
  const gettingDressed = listeningScriptGettingDressed;
  const clothesShopping = listeningScriptClothesShopping;
  const keysDressed = listeningAnswerKeys.gettingDressed;
  const keysShopping = listeningAnswerKeys.clothesShopping;

  return [
    {
      slug: "listening-getting-dressed",
      title: "Lesson 1: Getting Dressed",
      learningObjective:
        "Listen to Mai and Mum and identify colours and clothes while getting dressed.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-dressed-learn",
          title: "Learn: Listen — Getting Dressed",
          instructions: "Listen to the conversation. Choose the correct answer.",
          sortOrder: 0,
          script: gettingDressed,
          answerKey: keysDressed,
          questions: [
            buildMcq({
              questionText: "What does Mum tell Mai to put on first?",
              skillTag: "listening",
              topicTag,
              explanation: "Put on your red shirt.",
              correct: "Red shirt",
              wrong: ["Blue trousers", "Green shoes"],
              distractorNotes: ["Quần hỏi sau", "Giày nói sau"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What colour are Mai's shoes?",
              skillTag: "listening",
              topicTag,
              explanation: "Your shoes are green.",
              correct: "Green",
              wrong: ["Yellow", "Blue"],
              distractorNotes: ["Màu váy", "Màu quần"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-dressed-practice",
          title: "Practice: More from Getting Dressed",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: gettingDressed,
          answerKey: keysDressed,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Mai asks about her blue _____.",
              skillTag: "listening",
              topicTag,
              explanation: "And my blue trousers?",
              correct: "trousers",
              wrong: ["dress", "hat"],
              distractorNotes: ["Váy hỏi sau", "Mũ hỏi sau"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What colour is Mai's dress?",
              skillTag: "listening",
              topicTag,
              explanation: "Your dress is yellow.",
              correct: "Yellow",
              wrong: ["Green", "Red"],
              distractorNotes: ["Màu trong bài đọc khác", "Màu áo"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-dressed-check",
          title: "Check: Getting Dressed Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: gettingDressed,
          answerKey: keysDressed,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Is Mai's hat white?",
              skillTag: "listening",
              topicTag,
              explanation: "Yes. It is white.",
              correct: "Yes, it is white.",
              wrong: ["No, it is yellow.", "No, it is black."],
              distractorNotes: ["Màu mũ Anna", "Màu jacket"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai's jacket is _____.",
              skillTag: "listening",
              topicTag,
              explanation: "My jacket is black.",
              correct: "black",
              wrong: ["white", "blue"],
              distractorNotes: ["Màu mũ", "Màu quần"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-dressed-apply",
          title: "Apply: Match Getting Dressed Facts",
          instructions: "Listen again. Match each item to its colour.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: gettingDressed, answerKey: keysDressed },
          questions: [
            buildMatching({
              questionText: "Match clothes to colours from the dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Shirt=red; trousers=blue; shoes=green; dress=yellow; hat=white.",
              pairs: [
                { left: "shirt", right: "red" },
                { left: "trousers", right: "blue" },
                { left: "shoes", right: "green" },
                { left: "dress", right: "yellow" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-dressed-review",
          title: "Review: Getting Dressed Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: gettingDressed,
          answerKey: keysDressed,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Who gives Mai instructions?",
              skillTag: "listening",
              topicTag,
              explanation: "Mum tells Mai what to wear.",
              correct: "Mum",
              wrong: ["Anna", "Nam"],
              distractorNotes: ["Anna không có", "Nam không có"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai asks: What colour is my _____?",
              skillTag: "listening",
              topicTag,
              explanation: "What colour is my dress?",
              correct: "dress",
              wrong: ["shirt", "jacket"],
              distractorNotes: ["Áo đã biết màu", "Jacket Mai tự nói"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "At the end Mai says she is _____.",
              skillTag: "listening",
              topicTag,
              explanation: "I am ready!",
              correct: "ready",
              wrong: ["sad", "hungry"],
              distractorNotes: ["Không nêu", "Không nêu"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-shopping-with-mum",
      title: "Lesson 2: Shopping with Mum",
      learningObjective:
        "Listen to Mai and Mum at a clothes shop and identify colours and items.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-shop-learn",
          title: "Learn: Listen at the Shop",
          instructions: "Listen to the shopping dialogue. Answer the questions.",
          sortOrder: 0,
          script: clothesShopping,
          answerKey: keysShopping,
          questions: [
            buildMcq({
              questionText: "What colour is the jacket Mum shows?",
              skillTag: "listening",
              topicTag,
              explanation: "Look at this blue jacket.",
              correct: "Blue",
              wrong: ["Black", "Red"],
              distractorNotes: ["Màu giày", "Màu mũ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mai likes the _____ shirt.",
              skillTag: "listening",
              topicTag,
              explanation: "I like the yellow shirt.",
              correct: "yellow",
              wrong: ["green", "white"],
              distractorNotes: ["Màu váy ở nhà", "Màu quần mua"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-shop-practice",
          title: "Practice: More from the Shop",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: clothesShopping,
          answerKey: keysShopping,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "The shoes in the shop are _____.",
              skillTag: "listening",
              topicTag,
              explanation: "The shoes are black.",
              correct: "black",
              wrong: ["yellow", "blue"],
              distractorNotes: ["Màu shirt", "Màu jacket"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai thinks the _____ hat is nice.",
              skillTag: "listening",
              topicTag,
              explanation: "The red hat is nice.",
              correct: "red",
              wrong: ["white", "green"],
              distractorNotes: ["Màu quần", "Màu váy nhà"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-shop-check",
          title: "Check: Shopping Listening Quiz",
          instructions: "Listen one more time. Choose carefully.",
          sortOrder: 2,
          script: clothesShopping,
          answerKey: keysShopping,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "They buy _____ trousers.",
              skillTag: "listening",
              topicTag,
              explanation: "We buy white trousers too.",
              correct: "white",
              wrong: ["blue", "black"],
              distractorNotes: ["Màu jacket", "Màu giày"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai's dress at home is _____.",
              skillTag: "listening",
              topicTag,
              explanation: "My dress is green at home.",
              correct: "green",
              wrong: ["yellow", "red"],
              distractorNotes: ["Màu shirt shop", "Màu hat"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-shop-apply",
          title: "Apply: Match Shop Items",
          instructions: "Listen again. Match shop items to colours.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: clothesShopping, answerKey: keysShopping },
          questions: [
            buildMatching({
              questionText: "Match items at the shop to their colours.",
              skillTag: "listening",
              topicTag,
              explanation: "Jacket=blue; shirt=yellow; shoes=black; hat=red; trousers=white.",
              pairs: [
                { left: "jacket", right: "blue" },
                { left: "shirt", right: "yellow" },
                { left: "shoes", right: "black" },
                { left: "hat", right: "red" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-shop-review",
          title: "Review: Shopping Dialogue Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: clothesShopping,
          answerKey: keysShopping,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Mai says: Thank you, _____!",
              skillTag: "listening",
              topicTag,
              explanation: "Thank you, Mum!",
              correct: "Mum",
              wrong: ["Anna", "Nam"],
              distractorNotes: ["Anna không có", "Nam không có"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum says Mai has many _____ today.",
              skillTag: "listening",
              topicTag,
              explanation: "You have many colours today!",
              correct: "colours",
              wrong: ["shoes only", "numbers"],
              distractorNotes: ["Chỉ giày", "Không nói số"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Does Mai like the black shoes?",
              skillTag: "listening",
              topicTag,
              explanation: "Yes! — Mai likes the black shoes.",
              correct: "Yes",
              wrong: ["No", "Not in the dialogue"],
              distractorNotes: ["Mai nói Yes", "Có trong hội thoại"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-mixed-colour-item",
      title: "Lesson 3: Mixed Colour + Item",
      learningObjective:
        "Review both listening scripts and answer mixed colour + clothes MCQs.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-mixed-learn",
          title: "Learn: Dressed Dialogue Again",
          instructions: "Listen to getting dressed. Answer about colour + item.",
          sortOrder: 0,
          script: gettingDressed,
          answerKey: keysDressed,
          questions: [
            buildMcq({
              questionText: "Colour + item: Mai's shirt is _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Red shirt — Put on your red shirt.",
              correct: "red",
              wrong: ["blue", "green"],
              distractorNotes: ["Màu quần", "Màu giày"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Colour + item: Mai's hat is _____.",
              skillTag: "listening",
              topicTag,
              explanation: "White — It is white.",
              correct: "white",
              wrong: ["yellow", "black"],
              distractorNotes: ["Màu váy", "Màu jacket"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-practice",
          title: "Practice: Shop Colour + Item",
          instructions: "Listen to shopping. Focus on colour + clothes pairs.",
          sortOrder: 1,
          script: clothesShopping,
          answerKey: keysShopping,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "At the shop: a blue _____",
              skillTag: "listening",
              topicTag,
              explanation: "Blue jacket.",
              correct: "jacket",
              wrong: ["hat", "dress"],
              distractorNotes: ["Red hat", "Green dress at home"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They buy white _____.",
              skillTag: "listening",
              topicTag,
              explanation: "White trousers.",
              correct: "trousers",
              wrong: ["shoes", "shirt"],
              distractorNotes: ["Black shoes", "Yellow shirt"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-check",
          title: "Check: Mixed Colour + Item Quiz",
          instructions: "Listen to getting dressed one final time.",
          sortOrder: 2,
          script: gettingDressed,
          answerKey: keysDressed,
          difficulty: 0.36,
          questions: [
            buildMcq({
              questionText: "Which colour + item do you hear in the dressed dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Green shoes — Your shoes are green.",
              correct: "green shoes",
              wrong: ["red dress", "black hat"],
              distractorNotes: ["Dress is yellow", "Hat is white"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which pair is NOT in the getting dressed dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Black jacket Mai says herself — not from Mum's colour list first. Red hat is only in shop.",
              correct: "red hat",
              wrong: ["red shirt", "blue trousers"],
              distractorNotes: ["Có trong dialogue", "Có trong dialogue"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-mixed-apply",
          title: "Apply: Match Both Dialogues",
          instructions: "Listen to the shop. Match facts to dressed or shop.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: clothesShopping, answerKey: keysShopping },
          questions: [
            buildMatching({
              questionText: "Match colour + item to dressed or shop dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Green shoes=dressed; black shoes=shop; yellow dress=dressed; yellow shirt=shop.",
              pairs: [
                { left: "green shoes", right: "getting dressed" },
                { left: "black shoes", right: "clothes shopping" },
                { left: "yellow dress", right: "getting dressed" },
                { left: "yellow shirt", right: "clothes shopping" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-review",
          title: "Review: Full Colour + Item Recall",
          instructions: "Listen to shopping and answer — full review.",
          sortOrder: 4,
          script: clothesShopping,
          answerKey: keysShopping,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Both dialogues mention Mai. Who is always with her?",
              skillTag: "listening",
              topicTag,
              explanation: "Mum — in bedroom and shop.",
              correct: "Mum",
              wrong: ["Anna", "Teacher"],
              distractorNotes: ["Anna chỉ bài đọc", "Không có giáo viên"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which colour appears in BOTH dialogues?",
              skillTag: "listening",
              topicTag,
              explanation: "Blue — blue trousers (dressed) and blue jacket (shop).",
              correct: "blue",
              wrong: ["pink", "grey"],
              distractorNotes: ["Không có pink", "Không có grey"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best summary: the listening lessons are about _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Colours and clothes in dialogues — text-only listen and choose.",
              correct: "colours and clothes with Mai and Mum",
              wrong: ["numbers and days", "animals at the zoo"],
              distractorNotes: ["Unit 2", "Unit 4"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
