/** Starters U3 — speaking lessons (3 × 5 exercises; only Check is AI). */

const MAI_DRESSED_SCENE =
  "Mai's bedroom on a sunny morning. Mai is eight. She has a red shirt and blue trousers in her cupboard. She wears a green dress, yellow shoes, a white hat and a black jacket. Her brother Nam has blue shoes. Her friend Anna wears a yellow hat. Mum helps Mai get dressed.";

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [clothesCheck, maiOutfitCheck, shoppingCheck] = speakingChecks;

  return [
    {
      slug: "speaking-clothes-and-colours",
      title: "Lesson 1: Talk About Clothes and Colours",
      learningObjective:
        "Answer simple questions about clothes and colours with short phrases.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-clothes-learn",
          title: "Learn: What to Say About Clothes",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { sceneDescription: MAI_DRESSED_SCENE },
          questions: [
            buildMcq({
              questionText: "Someone asks: What colour is your dress? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "It is green. / My dress is green.",
              correct: "It is green.",
              wrong: ["They are green.", "Green is it."],
              distractorNotes: ["Dress số ít", "Sai thứ tự"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Someone asks: What are you wearing on your feet? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Shoes. / Yellow shoes. / My shoes are yellow.",
              correct: "My shoes are yellow.",
              wrong: ["My shoes is yellow.", "Shoes yellow my."],
              distractorNotes: ["Is số ít", "Sai thứ tự"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-clothes-practice",
          title: "Practice: Clothes Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { sceneDescription: MAI_DRESSED_SCENE },
          questions: [
            buildMcq({
              questionText: "Mum asks: Is your hat white? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes. It is white.",
              correct: "Yes. It is white.",
              wrong: ["Yes. They are white.", "Yes. White it is."],
              distractorNotes: ["Hat số ít", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Friend asks: Do you have a jacket? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes. My jacket is black.",
              correct: "Yes. My jacket is black.",
              wrong: ["Yes. My black is jacket.", "Yes. Jacket black my."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        clothesCheck,
        buildExercise({
          slug: "speaking-clothes-apply",
          title: "Apply: Quick Clothes Replies",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Describe your shirt colour. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "My shirt is red. — mẫu mô tả.",
              correct: "My shirt is red.",
              wrong: ["My red is shirt.", "Shirt my red is."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say one clothes word + colour. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Blue trousers. / A blue jacket.",
              correct: "Blue trousers.",
              wrong: ["Trousers blue.", "Blue is trousers."],
              distractorNotes: ["Thứ tự sai khi viết", "Thừa is"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-clothes-review",
          title: "Review: Clothes Speaking",
          instructions: "Choose the best spoken reply.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "What colour are your shoes? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "They are yellow. / My shoes are yellow.",
              correct: "They are yellow.",
              wrong: ["It is yellow.", "They is yellow."],
              distractorNotes: ["It số ít", "They + is sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Point to your hat and say:",
              skillTag: "speaking",
              topicTag,
              explanation: "A white hat. / My hat is white.",
              correct: "My hat is white.",
              wrong: ["My white is hat.", "Hat white my."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum says: Put on your red shirt. You repeat:",
              skillTag: "speaking",
              topicTag,
              explanation: "Put on your red shirt. — lặp mệnh lệnh.",
              correct: "Put on your red shirt.",
              wrong: ["Put on your shirt red.", "Red shirt put on your."],
              distractorNotes: ["Màu sau danh từ", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-mais-outfit",
      title: "Lesson 2: Describe Mai's Clothes",
      learningObjective:
        "Answer questions about Mai's outfit using short phrases.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-mai-learn",
          title: "Learn: Mai's Outfit Phrases",
          instructions: "Read the scene description. Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { sceneDescription: MAI_DRESSED_SCENE },
          questions: [
            buildMcq({
              questionText: "What colour is Mai's dress? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Green. / It is green.",
              correct: "Green.",
              wrong: ["Yellow.", "Red."],
              distractorNotes: ["Màu giày", "Màu áo tủ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What colour is Mai's jacket? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Black.",
              correct: "Black.",
              wrong: ["White.", "Blue."],
              distractorNotes: ["Màu mũ", "Màu quần Nam"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-mai-practice",
          title: "Practice: Mai Outfit Questions",
          instructions: "Choose what you would say about Mai.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { sceneDescription: MAI_DRESSED_SCENE },
          questions: [
            buildMcq({
              questionText: "Examiner: What is Mai wearing on her head? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "A white hat.",
              correct: "A white hat.",
              wrong: ["A hat white.", "White a hat."],
              distractorNotes: ["Thứ tự sai", "Mạo từ sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: What colour are Mai's shoes? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yellow. / They are yellow.",
              correct: "They are yellow.",
              wrong: ["It is yellow.", "Yellow is they."],
              distractorNotes: ["It số ít", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        maiOutfitCheck,
        buildExercise({
          slug: "speaking-mai-apply",
          title: "Apply: Mai Outfit Speaking",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Say what Nam wears on his feet. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Blue shoes. / His shoes are blue.",
              correct: "His shoes are blue.",
              wrong: ["His shoes is blue.", "Blue his shoes are."],
              distractorNotes: ["Is số ít", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna's hat is yellow. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Anna wears a yellow hat.",
              correct: "Anna wears a yellow hat.",
              wrong: ["Anna wears a hat yellow.", "Yellow hat Anna wears a."],
              distractorNotes: ["Màu sau danh từ", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-mai-review",
          title: "Review: Mai Outfit Speaking Mix",
          instructions: "Choose the best phrase.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Mai says: It is green! She talks about her _____.",
              skillTag: "speaking",
              topicTag,
              explanation: "Dress — What colour is your dress?",
              correct: "dress",
              wrong: ["shoes", "jacket"],
              distractorNotes: ["Giày vàng", "Áo khoác đen"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Describe Mai's full outfit in one phrase. Best start:",
              skillTag: "speaking",
              topicTag,
              explanation: "Mai wears a green dress… — mô tả trang phục.",
              correct: "Mai wears a green dress and yellow shoes.",
              wrong: ["Mai green dress wears.", "Dress green Mai wears a."],
              distractorNotes: ["Sai thứ tự", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna says: You look nice! You reply:",
              skillTag: "speaking",
              topicTag,
              explanation: "Thank you! — phản hồi lịch sự.",
              correct: "Thank you!",
              wrong: ["Green dress.", "White hat."],
              distractorNotes: ["Không trả lời lời khen", "Không trả lời lời khen"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-shopping-colours",
      title: "Lesson 3: Clothes Shopping Speaking",
      learningObjective:
        "Choose and say appropriate replies about colours at a clothes shop.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-shop-learn",
          title: "Learn: Shop Colour Replies",
          instructions: "Choose the best reply in each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: {
            sceneDescription:
              "Mai and Mum are at a clothes shop. Mum shows a blue jacket. Mai likes a yellow shirt. The shoes are black. There is a red hat. They buy white trousers.",
          },
          questions: [
            buildMcq({
              questionText: "Mum asks: Do you like the black shoes? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes! — như trong script.",
              correct: "Yes!",
              wrong: ["No.", "Green dress."],
              distractorNotes: ["Mai nói Yes", "Không liên quan"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mum shows a jacket. You say the colour:",
              skillTag: "speaking",
              topicTag,
              explanation: "Blue. / It is blue.",
              correct: "Blue.",
              wrong: ["Red.", "Yellow."],
              distractorNotes: ["Màu mũ", "Màu shirt"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-shop-practice",
          title: "Practice: More Shop Situations",
          instructions: "Choose what you would say at the shop.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: {
            sceneDescription:
              "Mai and Mum are at a clothes shop. Mum shows a blue jacket. Mai likes a yellow shirt. The shoes are black. There is a red hat. They buy white trousers.",
          },
          questions: [
            buildMcq({
              questionText: "Say which shirt you like. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I like the yellow shirt.",
              correct: "I like the yellow shirt.",
              wrong: ["I like the shirt yellow.", "Yellow I like shirt the."],
              distractorNotes: ["Màu sau danh từ", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The red hat is nice. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "The red hat is nice. — lặp ý Mai.",
              correct: "The red hat is nice.",
              wrong: ["The hat red is nice.", "Red the hat nice is."],
              distractorNotes: ["Màu sau danh từ", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        shoppingCheck,
        buildExercise({
          slug: "speaking-shop-apply",
          title: "Apply: Quick Shop Replies",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Mum buys trousers. You say the colour:",
              skillTag: "speaking",
              topicTag,
              explanation: "White trousers.",
              correct: "White trousers.",
              wrong: ["Trousers white.", "White is trousers."],
              distractorNotes: ["Thứ tự sai", "Thừa is"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Thank Mum for shopping. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Thank you, Mum!",
              correct: "Thank you, Mum!",
              wrong: ["Thank Mum you.", "Mum thank you."],
              distractorNotes: ["Sai thứ tự", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-shop-review",
          title: "Review: Shopping Speaking Mix",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "At the shop, shoes are _____. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Black. / They are black.",
              correct: "They are black.",
              wrong: ["It is black.", "They is black."],
              distractorNotes: ["It số ít", "They + is sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say one sentence with jacket + colour. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "A blue jacket. / The jacket is blue.",
              correct: "A blue jacket.",
              wrong: ["A jacket blue.", "Blue a jacket."],
              distractorNotes: ["Màu sau danh từ", "Mạo từ sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum says you have many colours. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes! / I have many colours today!",
              correct: "Yes! I have many colours!",
              wrong: ["No colours.", "Many I colours have."],
              distractorNotes: ["Trái script", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
