/** Starters U3 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-colours",
      title: "Lesson 1: Colours",
      learningObjective:
        "Recognise and use red, blue, green, yellow, black and white in short sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-colours-learn",
          title: "Learn: Basic Colours",
          instructions: "Read each sentence. Choose the best colour.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Apples and fire are often _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Red (đỏ) — màu phổ biến của táo và lửa.",
              correct: "red",
              wrong: ["blue", "green"],
              distractorNotes: ["Xanh dương — trời/biển", "Xanh lá — cây cỏ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The sky on a sunny day is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Blue (xanh dương) — màu bầu trời.",
              correct: "blue",
              wrong: ["yellow", "black"],
              distractorNotes: ["Vàng — mặt trời", "Đen — ban đêm"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Grass and leaves are usually _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Green (xanh lá) — màu của cỏ và lá.",
              correct: "green",
              wrong: ["red", "white"],
              distractorNotes: ["Đỏ — không phải cây", "Trắng — tuyết/milk"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The sun and bananas are often _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Yellow (vàng) — màu mặt trời và chuối.",
              correct: "yellow",
              wrong: ["blue", "black"],
              distractorNotes: ["Xanh dương", "Đen"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-colours-practice",
          title: "Practice: Match Colours",
          instructions: "Match each colour to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the colours to their Vietnamese meanings.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mỗi màu khớp nghĩa tiếng Việt. black/white hay bị đảo.",
              pairs: [
                { left: "red", right: "màu đỏ" },
                { left: "blue", right: "màu xanh dương" },
                { left: "black", right: "màu đen" },
                { left: "white", right: "màu trắng" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-colours-check",
          title: "Check: Colours Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Mai's dress in the story is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Green — bài đọc: She puts on a green dress.",
              correct: "green",
              wrong: ["yellow", "red"],
              distractorNotes: ["Màu giày Mai", "Màu áo trong tủ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Snow and milk are usually _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "White (trắng) — tuyết và sữa.",
              correct: "white",
              wrong: ["black", "green"],
              distractorNotes: ["Đen — ban đêm", "Xanh lá"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Night and Mai's jacket are _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Black — Mai has a black jacket.",
              correct: "black",
              wrong: ["white", "blue"],
              distractorNotes: ["Màu mũ Mai", "Màu quần Nam"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-colours-apply",
          title: "Apply: Colours in Sentences",
          instructions: "Complete each sentence with the correct colour.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: My shirt is [0]. | The sky is [1]. | Anna's hat is [2].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "red (áo); blue (trời/Nam's shoes); yellow (mũ Anna).",
              template: "My shirt is [0]. The sky is [1]. Anna's hat is [2].",
              correctAnswers: ["red", "blue", "yellow"],
              acceptableAnswers: [
                ["red", "Red"],
                ["blue", "Blue"],
                ["yellow", "Yellow"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-colours-review",
          title: "Review: Colours Mix",
          instructions: "Mixed review. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which word is a colour, not clothes?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Green là màu. Shirt và dress là quần áo.",
              correct: "green",
              wrong: ["shirt", "dress"],
              distractorNotes: ["Quần áo", "Quần áo"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai's shoes are _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Yellow — Her shoes are yellow.",
              correct: "yellow",
              wrong: ["green", "black"],
              distractorNotes: ["Màu váy", "Màu áo khoác"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Nam's shoes are _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Blue — Her brother Nam has blue shoes.",
              correct: "blue",
              wrong: ["red", "white"],
              distractorNotes: ["Màu áo Mai", "Màu mũ Mai"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-clothes",
      title: "Lesson 2: Clothes",
      learningObjective:
        "Recognise shirt, trousers, dress, shoes, hat and jacket in context.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-clothes-learn",
          title: "Learn: Clothes Words",
          instructions: "Read each clue. Choose the best clothes word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "You wear this on your top. It has buttons.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Shirt (áo sơ mi) — mặc trên thân.",
              correct: "shirt",
              wrong: ["shoes", "trousers"],
              distractorNotes: ["Đi trên chân", "Mặc dưới thân"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "You wear these on your legs. They are long.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Trousers (quần dài) — mặc ở chân.",
              correct: "trousers",
              wrong: ["dress", "hat"],
              distractorNotes: ["Váy — một mảnh", "Đội trên đầu"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Girls often wear this one piece.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Dress (váy) — trang phục một mảnh.",
              correct: "dress",
              wrong: ["jacket", "shirt"],
              distractorNotes: ["Áo khoác ngoài", "Áo sơ mi riêng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "You wear these on your feet.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Shoes (giày) — đi trên chân.",
              correct: "shoes",
              wrong: ["hat", "jacket"],
              distractorNotes: ["Đội trên đầu", "Mặc ngoài áo"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-clothes-practice",
          title: "Practice: Match Clothes",
          instructions: "Match each word to what you wear it on.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match clothes to where you wear them.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hat=đầu; jacket=thân ngoài; shoes=chân; shirt=thân trên.",
              pairs: [
                { left: "hat", right: "on your head" },
                { left: "jacket", right: "over your shirt" },
                { left: "shoes", right: "on your feet" },
                { left: "shirt", right: "on your top" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-clothes-check",
          title: "Check: Clothes Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "You wear this on your head when it is sunny.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hat (mũ) — đội trên đầu.",
              correct: "hat",
              wrong: ["dress", "trousers"],
              distractorNotes: ["Váy", "Quần"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When it is cold, you wear a warm _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Jacket (áo khoác) — mặc ngoài khi lạnh.",
              correct: "jacket",
              wrong: ["shoes", "hat"],
              distractorNotes: ["Giày — không giữ ấm thân", "Mũ — nhỏ hơn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai puts on a green _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Dress — She puts on a green dress.",
              correct: "dress",
              wrong: ["shirt", "jacket"],
              distractorNotes: ["Áo đỏ trong tủ", "Áo khoác đen"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-clothes-apply",
          title: "Apply: Clothes in Sentences",
          instructions: "Complete each sentence with the correct clothes word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: Put on your red [0]. | My [1] are yellow. | She wears a white [2].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "shirt; shoes; hat — theo câu chuyện Mai.",
              template: "Put on your red [0]. My [1] are yellow. She wears a white [2].",
              correctAnswers: ["shirt", "shoes", "hat"],
              acceptableAnswers: [
                ["shirt", "Shirt"],
                ["shoes", "Shoes"],
                ["hat", "Hat"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-clothes-review",
          title: "Review: Clothes Mix",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which word is NOT clothes?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Blue là màu. Shirt, dress, shoes là quần áo.",
              correct: "blue",
              wrong: ["shirt", "dress"],
              distractorNotes: ["Quần áo", "Quần áo"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai's black _____ keeps her warm.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Jacket — She wears a black jacket.",
              correct: "jacket",
              wrong: ["hat", "dress"],
              distractorNotes: ["Mũ — nhỏ hơn", "Váy xanh"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Blue _____ are in Mai's cupboard.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Trousers — blue trousers in cupboard.",
              correct: "trousers",
              wrong: ["shoes", "hat"],
              distractorNotes: ["Giày vàng trên chân", "Mũ trắng"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-colours-and-clothes-mix",
      title: "Lesson 3: Colours and Clothes Mix",
      learningObjective:
        "Use hat, jacket, black and white with other colour and clothes words.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-mix-learn",
          title: "Learn: Colour + Clothes",
          instructions: "Read each phrase. Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "a _____ hat",
              skillTag: "vocabulary",
              topicTag,
              explanation: "White — Mai wears a white hat.",
              correct: "white",
              wrong: ["shirt", "dress"],
              distractorNotes: ["Quần áo, không phải màu", "Quần áo"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "a black _____",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Jacket — Mai has a black jacket.",
              correct: "jacket",
              wrong: ["yellow", "green"],
              distractorNotes: ["Màu, không phải quần áo", "Màu"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Anna wears a _____ hat.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Yellow — Anna wears a yellow hat.",
              correct: "yellow",
              wrong: ["trousers", "jacket"],
              distractorNotes: ["Quần", "Áo khoác"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The shop has _____ shoes.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Black — The shoes are black (shopping script).",
              correct: "black",
              wrong: ["hat", "shirt"],
              distractorNotes: ["Mũ", "Áo"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mix-practice",
          title: "Practice: Match Colour + Item",
          instructions: "Match each clothes item to its colour in Mai's story.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match Mai's clothes to their colours.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Shirt=red; dress=green; shoes=yellow; hat=white; jacket=black.",
              pairs: [
                { left: "shirt", right: "red" },
                { left: "dress", right: "green" },
                { left: "shoes", right: "yellow" },
                { left: "hat", right: "white" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mix-check",
          title: "Check: Colours and Clothes Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which pair is correct?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "a red shirt — màu trước danh từ.",
              correct: "a red shirt",
              wrong: ["a shirt red", "red a shirt"],
              distractorNotes: ["Thứ tự tiếng Việt", "Mạo từ sai vị trí"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai's _____ is black.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Jacket — black jacket.",
              correct: "jacket",
              wrong: ["dress", "shoes"],
              distractorNotes: ["Váy xanh", "Giày vàng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They buy _____ trousers at the shop.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "White — We buy white trousers (shopping script).",
              correct: "white",
              wrong: ["jacket", "hat"],
              distractorNotes: ["Quần áo", "Quần áo"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mix-apply",
          title: "Apply: Complete Colour + Clothes",
          instructions: "Complete with colour or clothes words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: a [0] jacket | [1] trousers | a [2] hat",
              skillTag: "vocabulary",
              topicTag,
              explanation: "blue (shop); white (shop); yellow (Anna).",
              template: "a [0] jacket | [1] trousers | a [2] hat",
              correctAnswers: ["blue", "white", "yellow"],
              acceptableAnswers: [
                ["blue", "Blue"],
                ["white", "White"],
                ["yellow", "Yellow"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mix-review",
          title: "Review: Full Vocabulary Mix",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which item does Mai NOT wear in the story?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mai wears shirt, dress, shoes, hat, jacket. Blue trousers are in cupboard.",
              correct: "blue trousers (she keeps them, wears dress)",
              wrong: ["green dress", "white hat"],
              distractorNotes: ["Mai mặc váy xanh", "Mai đội mũ trắng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Grass is green. The sun is often _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Yellow — mặt trời thường vàng.",
              correct: "yellow",
              wrong: ["black", "white"],
              distractorNotes: ["Đen — ban đêm", "Trắng — mây"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You put _____ on before you go outside in the rain.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Jacket — áo khoác che mưa/lạnh.",
              correct: "a jacket",
              wrong: ["a hat only", "shoes only"],
              distractorNotes: ["Mũ một mình chưa đủ", "Giày không che thân"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
