/** Starters U3 — writing lessons (3 × 5 exercises; only Check is AI). */

export function writingLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  writingChecks,
  topicTag,
}) {
  const [clothesColourCheck, maisOutfitCheck, adjNounCheck] = writingChecks;

  return [
    {
      slug: "writing-clothes-and-colours",
      title: "Lesson 1: Write About Clothes and Colours",
      learningObjective:
        "Write short phrases about clothes and their colours.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-clothes-learn",
          title: "Learn: Clothes + Colour Frames",
          instructions: "Complete the sentences about clothes and colours.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: My shirt [0] red. | My shoes [1] blue. | It [2] green.",
              skillTag: "writing",
              topicTag,
              explanation: "is (shirt); are (shoes); is (dress/it).",
              template: "My shirt [0] red. My shoes [1] blue. It [2] green.",
              correctAnswers: ["is", "are", "is"],
              acceptableAnswers: [["is"], ["are"], ["is"]],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-clothes-practice",
          title: "Practice: Order Clothes Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: My / dress / is / green.",
              skillTag: "writing",
              topicTag,
              explanation: "My dress is green. — viết mô tả váy.",
              words: ["My", "dress", "is", "green."],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: a / red / shirt",
              skillTag: "writing",
              topicTag,
              explanation: "A red shirt — màu trước danh từ.",
              words: ["a", "red", "shirt"],
              correctOrder: [0, 1, 2],
              difficultyRating: 2,
            }),
          ],
        }),
        clothesColourCheck,
        buildExercise({
          slug: "writing-clothes-apply",
          title: "Apply: Choose the Best Sentence",
          instructions: "Choose the best written sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best sentence about shoes:",
              skillTag: "writing",
              topicTag,
              explanation: "My shoes are yellow. — số nhiều + are.",
              correct: "My shoes are yellow.",
              wrong: ["My shoes is yellow.", "Yellow are my shoes."],
              distractorNotes: ["Is số ít", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best phrase for a hat:",
              skillTag: "writing",
              topicTag,
              explanation: "A white hat — a + màu + danh từ.",
              correct: "a white hat",
              wrong: ["a hat white", "white a hat"],
              distractorNotes: ["Thứ tự sai", "Mạo từ sai"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-clothes-review",
          title: "Review: Clothes Writing",
          instructions: "Complete the writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 4,
          questions: [
            buildGapFill({
              questionText: "Complete: I have a [0] jacket. | Her hat [1] yellow. | The trousers [2] blue.",
              skillTag: "writing",
              topicTag,
              explanation: "black; is; are — màu + is/are.",
              template: "I have a [0] jacket. Her hat [1] yellow. The trousers [2] blue.",
              correctAnswers: ["black", "is", "are"],
              acceptableAnswers: [
                ["black", "Black"],
                ["is"],
                ["are"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "writing-mais-outfit",
      title: "Lesson 2: Write About Mai's Outfit",
      learningObjective:
        "Write short sentences describing Mai's clothes from the unit story.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-mai-learn",
          title: "Learn: Mai's Outfit Frames",
          instructions: "Complete each sentence about Mai.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: Mai's dress [0] green. | Her shoes [1] yellow. | Her hat [2] white.",
              skillTag: "writing",
              topicTag,
              explanation: "is; are; is — theo bài đọc Mai.",
              template: "Mai's dress [0] green. Her shoes [1] yellow. Her hat [2] white.",
              correctAnswers: ["is", "are", "is"],
              acceptableAnswers: [["is"], ["are"], ["is"]],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-mai-practice",
          title: "Practice: Order Mai's Sentences",
          instructions: "Put words in order to make sentences.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: It / is / green!",
              skillTag: "writing",
              topicTag,
              explanation: "It is green! — Mai trả lời Mum.",
              words: ["It", "is", "green!"],
              correctOrder: [0, 1, 2],
            }),
            buildSentenceOrdering({
              questionText: "Make: Mai / has / a / black / jacket.",
              skillTag: "writing",
              topicTag,
              explanation: "Mai has a black jacket.",
              words: ["Mai", "has", "a", "black", "jacket."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        maisOutfitCheck,
        buildExercise({
          slug: "writing-mai-apply",
          title: "Apply: More Mai Frames",
          instructions: "Complete the writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: Nam's shoes [0] blue. | Anna's hat [1] yellow. | Mai [2] happy.",
              skillTag: "writing",
              topicTag,
              explanation: "are; is; is — mô tả người khác.",
              template: "Nam's shoes [0] blue. Anna's hat [1] yellow. Mai [2] happy.",
              correctAnswers: ["are", "is", "is"],
              acceptableAnswers: [["are"], ["is"], ["is"]],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-mai-review",
          title: "Review: Mai Outfit Writing Quiz",
          instructions: "Choose the best sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best sentence about Mai's dress:",
              skillTag: "writing",
              topicTag,
              explanation: "Her dress is green. — đúng ngữ pháp.",
              correct: "Her dress is green.",
              wrong: ["Her green is dress.", "Her dress are green."],
              distractorNotes: ["Sai trật tự", "Are số ít sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best sentence about Mai's jacket:",
              skillTag: "writing",
              topicTag,
              explanation: "She wears a black jacket.",
              correct: "She wears a black jacket.",
              wrong: ["She wears a jacket black.", "Black jacket she wears a."],
              distractorNotes: ["Màu sau danh từ", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai's shoes are yellow. Another way to write:",
              skillTag: "writing",
              topicTag,
              explanation: "They are yellow. — thay shoes bằng they.",
              correct: "They are yellow.",
              wrong: ["It is yellow.", "They is yellow."],
              distractorNotes: ["It số ít", "They + is sai"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "writing-adjective-noun-order",
      title: "Lesson 3: Write Colour + Noun Order",
      learningObjective:
        "Write short phrases using adjective before noun (a red shirt).",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-adj-learn",
          title: "Learn: Adjective + Noun Writing",
          instructions: "Complete sentences with colour before noun.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: a [0] shirt | [1] trousers | a [2] hat",
              skillTag: "writing",
              topicTag,
              explanation: "red; blue; white — màu trước danh từ.",
              template: "a [0] shirt | [1] trousers | a [2] hat",
              correctAnswers: ["red", "blue", "white"],
              acceptableAnswers: [
                ["red", "Red"],
                ["blue", "Blue"],
                ["white", "White"],
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-adj-practice",
          title: "Practice: Order Colour Phrases",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: blue / trousers",
              skillTag: "writing",
              topicTag,
              explanation: "Blue trousers — màu + danh từ.",
              words: ["blue", "trousers"],
              correctOrder: [0, 1],
            }),
            buildSentenceOrdering({
              questionText: "Make: a / yellow / hat",
              skillTag: "writing",
              topicTag,
              explanation: "A yellow hat.",
              words: ["a", "yellow", "hat"],
              correctOrder: [0, 1, 2],
              difficultyRating: 2,
            }),
          ],
        }),
        adjNounCheck,
        buildExercise({
          slug: "writing-adj-apply",
          title: "Apply: Write Colour + Noun",
          instructions: "Complete the gap-fill writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: I like the [0] shirt. | a [1] jacket | [2] shoes",
              skillTag: "writing",
              topicTag,
              explanation: "yellow; blue; black — shop dialogue.",
              template: "I like the [0] shirt. a [1] jacket [2] shoes",
              correctAnswers: ["yellow", "blue", "black"],
              acceptableAnswers: [
                ["yellow", "Yellow"],
                ["blue", "Blue"],
                ["black", "Black"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-adj-review",
          title: "Review: Adjective + Noun Writing Mix",
          instructions: "Choose or complete colour + noun frames.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best written phrase:",
              skillTag: "writing",
              topicTag,
              explanation: "A green dress — màu trước danh từ.",
              correct: "a green dress",
              wrong: ["a dress green", "green a dress"],
              distractorNotes: ["Thứ tự sai", "Mạo từ sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which is wrong to write?",
              skillTag: "writing",
              topicTag,
              explanation: "Shoes red sai — phải red shoes hoặc My shoes are red.",
              correct: "shoes red",
              wrong: ["red shoes", "My shoes are red."],
              distractorNotes: ["Đúng cụm", "Đúng câu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Put on your _____ . (from listening)",
              skillTag: "writing",
              topicTag,
              explanation: "Red shirt — Put on your red shirt.",
              correct: "red shirt",
              wrong: ["shirt red", "red a shirt"],
              distractorNotes: ["Thứ tự sai", "Thừa a"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
