/** Starters U5 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-its-weather",
      title: "Lesson 1: It's + Weather",
      learningObjective:
        "Use It's + weather adjective to describe the day.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-weather-learn",
          title: "Learn: It's + Weather Adjective",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "The sun is out. You say: _____ sunny today.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's — It is sunny today.",
              correct: "It's",
              wrong: ["They", "These"],
              distractorNotes: ["They không dùng với thời tiết", "These = đồ vật số nhiều"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Rain falls from the sky. Best sentence:",
              skillTag: "grammar",
              topicTag,
              explanation: "It's rainy. — mô tả trời mưa.",
              correct: "It's rainy.",
              wrong: ["They rainy.", "It rainy."],
              distractorNotes: ["They sai", "Thiếu is"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Look outside! _____ windy today.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's windy — gió mạnh hôm nay.",
              correct: "It's",
              wrong: ["Those", "Are"],
              distractorNotes: ["Those + danh từ", "Are không đứng một mình"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Many clouds in the sky. You say:",
              skillTag: "grammar",
              topicTag,
              explanation: "It's cloudy. — có nhiều mây.",
              correct: "It's cloudy.",
              wrong: ["It's cloud.", "They are cloudy."],
              distractorNotes: ["Cloud = danh từ mây", "They không dùng thời tiết"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-weather-practice",
          title: "Practice: Weather Gap Fill",
          instructions: "Complete with It's or a weather word.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] rainy. | [1] sunny and cloudy. | The [2] is strong.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's; It's; wind — It's + tính từ; the wind.",
              template: "[0] rainy. [1] sunny and cloudy. The [2] is strong.",
              correctAnswers: ["It's", "It's", "wind"],
              acceptableAnswers: [
                ["It's", "It is", "its"],
                ["It's", "It is"],
                ["wind", "Wind"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-weather-check",
          title: "Check: It's + Weather Quiz",
          instructions: "Choose the best answer. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "It's rainy and windy. — hai tính từ thời tiết.",
              correct: "It's rainy and windy.",
              wrong: ["They is rainy.", "It are windy."],
              distractorNotes: ["They is sai", "It are sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Today we stay inside because _____ rainy.",
              skillTag: "grammar",
              topicTag,
              explanation: "it's — because it's rainy.",
              correct: "it's",
              wrong: ["these", "those"],
              distractorNotes: ["These = đồ gần", "Those = đồ xa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is wrong?",
              skillTag: "grammar",
              topicTag,
              explanation: "It sunny sai — cần It's / It is.",
              correct: "It sunny today.",
              wrong: ["It's sunny today.", "It's cloudy."],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-weather-apply",
          title: "Apply: Order Weather Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: It's / rainy / and / windy.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's rainy and windy. — It's + tính từ + and + tính từ.",
              words: ["It's", "rainy", "and", "windy."],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: Look / at / the / clouds!",
              skillTag: "grammar",
              topicTag,
              explanation: "Look at the clouds! — mệnh lệnh + the + plural.",
              words: ["Look", "at", "the", "clouds!"],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-weather-review",
          title: "Review: It's + Weather Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Dad asks: Is it sunny? Anna says: No. _____ rainy.",
              skillTag: "grammar",
              topicTag,
              explanation: "It's — No. It's rainy.",
              correct: "It's",
              wrong: ["These", "Those"],
              distractorNotes: ["These = đồ chơi", "Those = đồ xa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When the sun comes out, you say:",
              skillTag: "grammar",
              topicTag,
              explanation: "It's sunny and cloudy. — từ bài đọc.",
              correct: "It's sunny and cloudy.",
              wrong: ["They sunny.", "It's sun."],
              distractorNotes: ["They sai", "Sun = danh từ mặt trời"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best sentence about strong air outside:",
              skillTag: "grammar",
              topicTag,
              explanation: "The wind is strong. — the + wind + is.",
              correct: "The wind is strong.",
              wrong: ["The wind are strong.", "Wind is strong the."],
              distractorNotes: ["Wind số ít → is", "Thứ tự từ sai"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-plural-kites",
      title: "Lesson 2: Plural — Two Kites",
      learningObjective:
        "Add -s to toy nouns after numbers: two kites, three balloons.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "grammar-plural-learn",
          title: "Learn: Plural Toy Nouns",
          instructions: "Choose the correct plural form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "One kite, two _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Kites — kite + s = kites.",
              correct: "kites",
              wrong: ["kite", "kiting"],
              distractorNotes: ["Số ít sau two", "Không phải từ tiếng Anh"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "I have two _____. (balloon)",
              skillTag: "grammar",
              topicTag,
              explanation: "Balloons — two balloons.",
              correct: "balloons",
              wrong: ["balloon", "balloonies"],
              distractorNotes: ["Số ít", "Sai chính tả"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Those _____ are on the chair.",
              skillTag: "grammar",
              topicTag,
              explanation: "Balloons — Those balloons (số nhiều).",
              correct: "balloons",
              wrong: ["balloon", "balloons is"],
              distractorNotes: ["Số ít với those", "Không phải đáp án"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Anna says: Those _____ are fun!",
              skillTag: "grammar",
              topicTag,
              explanation: "Puzzles — Those puzzles are fun.",
              correct: "puzzles",
              wrong: ["puzzle", "puzzles is"],
              distractorNotes: ["Số ít", "Không phải đáp án"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-plural-practice",
          title: "Practice: Plural Gap Fill",
          instructions: "Complete with the correct plural form.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: two [0] | three [1] | Those [2] are red and blue.",
              skillTag: "grammar",
              topicTag,
              explanation: "kites; balloons; balloons — thêm -s.",
              template: "two [0] | three [1] | Those [2] are red and blue.",
              correctAnswers: ["kites", "balloons", "balloons"],
              acceptableAnswers: [
                ["kites", "Kites"],
                ["balloons", "Balloons"],
                ["balloons", "Balloons"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-plural-check",
          title: "Check: Plural Toys Quiz",
          instructions: "Choose the correct form. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "I have two kites. — two + plural.",
              correct: "I have two kites.",
              wrong: ["I have two kite.", "I has two kites."],
              distractorNotes: ["Thiếu -s", "Has với I sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Those puzzles _____ fun.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are — puzzles số nhiều → are.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is số ít", "Am với I"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which is wrong?",
              skillTag: "grammar",
              topicTag,
              explanation: "Two balloon sai — phải two balloons.",
              correct: "two balloon",
              wrong: ["two balloons", "two kites"],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-plural-apply",
          title: "Apply: Order Plural Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: I / have / two / kites.",
              skillTag: "grammar",
              topicTag,
              explanation: "I have two kites. — số + plural.",
              words: ["I", "have", "two", "kites."],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: Those / balloons / are / red / and / blue.",
              skillTag: "grammar",
              topicTag,
              explanation: "Those balloons are red and blue. — those + plural + are.",
              words: ["Those", "balloons", "are", "red", "and", "blue."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-plural-review",
          title: "Review: Plural Toys Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Mai says: Those _____ are on the chair.",
              skillTag: "grammar",
              topicTag,
              explanation: "Balloons — Those balloons are on the chair.",
              correct: "balloons",
              wrong: ["balloon", "balloons is"],
              distractorNotes: ["Số ít", "Không phải đáp án"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Complete: two _____ (robot — more than one)",
              skillTag: "grammar",
              topicTag,
              explanation: "Robots — two robots.",
              correct: "robots",
              wrong: ["robot", "roboties"],
              distractorNotes: ["Số ít", "Sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "These toys _____ on the table.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are — toys số nhiều.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is số ít", "Am với I"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-these-those",
      title: "Lesson 3: These and Those",
      learningObjective:
        "Use these for toys near and those for toys farther away.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "grammar-these-learn",
          title: "Learn: These vs Those",
          instructions: "Choose the correct word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Toys in Mai's hands. She says: _____ are my toys.",
              skillTag: "grammar",
              topicTag,
              explanation: "These — gần người nói → these.",
              correct: "These",
              wrong: ["Those", "That"],
              distractorNotes: ["Those = xa hơn", "That số ít"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Balloons on the chair across the room. Mum says: _____ balloons are red.",
              skillTag: "grammar",
              topicTag,
              explanation: "Those — xa hơn → those.",
              correct: "Those",
              wrong: ["These", "This"],
              distractorNotes: ["These = gần", "This số ít"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best sentence: toys near Mai",
              skillTag: "grammar",
              topicTag,
              explanation: "These are my favourite toys.",
              correct: "These are my favourite toys.",
              wrong: ["Those are my favourite toys near me.", "These is my toys."],
              distractorNotes: ["Gần dùng these", "These + is sai"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Puzzles on a far shelf. Best phrase:",
              skillTag: "grammar",
              topicTag,
              explanation: "Those puzzles — xa → those.",
              correct: "Those puzzles",
              wrong: ["These puzzles here", "Those puzzle"],
              distractorNotes: ["These = gần", "Puzzle số ít"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-these-practice",
          title: "Practice: These/Those Gap Fill",
          instructions: "Complete with these or those.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] are my toys. | [1] balloons are on the chair. | [2] puzzles are fun!",
              skillTag: "grammar",
              topicTag,
              explanation: "These (gần); Those (xa); Those (xa).",
              template: "[0] are my toys. [1] balloons are on the chair. [2] puzzles are fun!",
              correctAnswers: ["These", "Those", "Those"],
              acceptableAnswers: [
                ["These", "these"],
                ["Those", "those"],
                ["Those", "those"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-these-check",
          title: "Check: These/Those Quiz",
          instructions: "Choose the best answer. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "These are my toys. — these + are + plural.",
              correct: "These are my toys.",
              wrong: ["These is my toys.", "Those are my toys in my hands."],
              distractorNotes: ["Is sai", "Trong tay → these"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Kite by the door (far). Mai says:",
              skillTag: "grammar",
              topicTag,
              explanation: "That kite is by the door. — xa, số ít → that.",
              correct: "That kite is by the door.",
              wrong: ["This kite is by the door far.", "Those kite is by the door."],
              distractorNotes: ["Xa dùng that", "Those + kite số ít sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is wrong?",
              skillTag: "grammar",
              topicTag,
              explanation: "Those is balloons sai — Those balloons are…",
              correct: "Those is balloons.",
              wrong: ["Those balloons are red.", "These are my toys."],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-these-apply",
          title: "Apply: Order These/Those Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: These / are / my / toys.",
              skillTag: "grammar",
              topicTag,
              explanation: "These are my toys. — these + are + sở hữu + danh từ.",
              words: ["These", "are", "my", "toys."],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: Those / balloons / are / on / the / chair.",
              skillTag: "grammar",
              topicTag,
              explanation: "Those balloons are on the chair. — those + plural + are.",
              words: ["Those", "balloons", "are", "on", "the", "chair."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-these-review",
          title: "Review: These/Those Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Mai holds teddy and doll. She says:",
              skillTag: "grammar",
              topicTag,
              explanation: "These are my favourite toys. — đang cầm = gần.",
              correct: "These are my favourite toys.",
              wrong: ["Those are my favourite toys.", "These is my toy."],
              distractorNotes: ["Those = xa", "Is sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Balloons on the chair across the room:",
              skillTag: "grammar",
              topicTag,
              explanation: "Those balloons are red and blue.",
              correct: "Those balloons are red and blue.",
              wrong: ["These balloons are red and blue.", "Those balloon is red."],
              distractorNotes: ["Gần → these", "Balloon số ít"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Complete: _____ puzzles are fun! (far shelf)",
              skillTag: "grammar",
              topicTag,
              explanation: "Those — xa → those puzzles.",
              correct: "Those",
              wrong: ["These", "This"],
              distractorNotes: ["These = gần", "This số ít"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
