/** Starters U5 — listening lessons (3 × 5 exercises). Text-only MCQ — no image_selection. */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptMaiToys,
  listeningScriptAnnaWeather,
  listeningAnswerKeys,
  topicTag,
}) {
  const maiToys = listeningScriptMaiToys;
  const annaWeather = listeningScriptAnnaWeather;
  const keysMai = listeningAnswerKeys.maiToys;
  const keysAnna = listeningAnswerKeys.annaWeather;

  return [
    {
      slug: "listening-mai-favourite-toys",
      title: "Lesson 1: Mai's Favourite Toys",
      learningObjective:
        "Listen to Mai and Mum and identify favourite toys indoors.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-mai-learn",
          title: "Learn: Listen — Mai's Toys",
          instructions: "Listen to the conversation. Choose the correct answer.",
          sortOrder: 0,
          script: maiToys,
          answerKey: keysMai,
          questions: [
            buildMcq({
              questionText: "Mai likes her teddy and her _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Doll — I like my teddy and my doll.",
              correct: "doll",
              wrong: ["kite", "cloud"],
              distractorNotes: ["Kite — outside later", "Cloud — weather"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What does Nam have?",
              skillTag: "listening",
              topicTag,
              explanation: "Robot — Nam has a robot.",
              correct: "a robot",
              wrong: ["a doll", "a cloud"],
              distractorNotes: ["Mai's toy", "Weather word"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mai-practice",
          title: "Practice: More from Mai's Dialogue",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: maiToys,
          answerKey: keysMai,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Where is Nam's puzzle?",
              skillTag: "listening",
              topicTag,
              explanation: "On the table — His puzzle is on the table.",
              correct: "on the table",
              wrong: ["in the garden", "at the shop"],
              distractorNotes: ["Kite outside", "Không mua đồ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Those _____ are red and blue.",
              skillTag: "listening",
              topicTag,
              explanation: "Balloons — Those balloons are red and blue.",
              correct: "balloons",
              wrong: ["kites", "clouds"],
              distractorNotes: ["Diều", "Mây trên trời"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mai-check",
          title: "Check: Mai's Toys Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: maiToys,
          answerKey: keysMai,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Mai says: These are my favourite _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Toys — These are my favourite toys.",
              correct: "toys",
              wrong: ["clouds", "wind"],
              distractorNotes: ["Thời tiết", "Gió"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Today is _____. We stay inside.",
              skillTag: "listening",
              topicTag,
              explanation: "Rainy — Today is rainy.",
              correct: "rainy",
              wrong: ["sunny", "robot"],
              distractorNotes: ["Nắng — sau", "Đồ chơi"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-mai-apply",
          title: "Apply: Match Mai's Dialogue Facts",
          instructions: "Listen again. Match each toy to its fact.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: maiToys, answerKey: keysMai },
          questions: [
            buildMatching({
              questionText: "Match toys from the dialogue to facts.",
              skillTag: "listening",
              topicTag,
              explanation: "Teddy+doll=Mai favourite; robot=Nam; puzzle=on table; balloons=red and blue.",
              pairs: [
                { left: "teddy and doll", right: "Mai's favourites" },
                { left: "robot", right: "Nam has it" },
                { left: "puzzle", right: "on the table" },
                { left: "balloons", right: "red and blue" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mai-review",
          title: "Review: Mai's Toys Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: maiToys,
          answerKey: keysMai,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Who asks about favourite toys?",
              skillTag: "listening",
              topicTag,
              explanation: "Mum asks Mai about favourite toys.",
              correct: "Mum",
              wrong: ["Anna", "Dad"],
              distractorNotes: ["Anna — lesson 2", "Dad — lesson 2"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai uses 'These' for her _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Favourite toys — These are my favourite toys.",
              correct: "favourite toys",
              wrong: ["balloons on the chair", "clouds outside"],
              distractorNotes: ["Those balloons", "Weather"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best summary: the dialogue is about _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Mai's toys on a rainy day indoors.",
              correct: "Mai's toys on a rainy day",
              wrong: ["flying a kite outside", "buying clothes"],
              distractorNotes: ["Lesson 2", "Unit 3"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-anna-weather-kite",
      title: "Lesson 2: Anna, Weather and Kite",
      learningObjective:
        "Listen to Dad, Anna and Mai about weather and the kite.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-anna-learn",
          title: "Learn: Listen — Weather and Kite",
          instructions: "Listen to the dialogue. Answer the questions.",
          sortOrder: 0,
          script: annaWeather,
          answerKey: keysAnna,
          questions: [
            buildMcq({
              questionText: "Anna says: It is rainy and _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Windy — It is rainy and windy.",
              correct: "windy",
              wrong: ["sunny", "teddy"],
              distractorNotes: ["Not yet sunny", "Toy"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Anna can see _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Clouds — I can see clouds.",
              correct: "clouds",
              wrong: ["kites", "robots"],
              distractorNotes: ["Kite — by door", "Robot — Nam"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-anna-practice",
          title: "Practice: More from Weather Dialogue",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: annaWeather,
          answerKey: keysAnna,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Can they fly the kite now?",
              skillTag: "listening",
              topicTag,
              explanation: "No — Not now. When it is sunny…",
              correct: "No",
              wrong: ["Yes", "Maybe at the shop"],
              distractorNotes: ["Dad says not now", "Không mua"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The _____ is strong today.",
              skillTag: "listening",
              topicTag,
              explanation: "Wind — The wind is strong today!",
              correct: "wind",
              wrong: ["puzzle", "doll"],
              distractorNotes: ["Toy", "Toy"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-anna-check",
          title: "Check: Weather and Kite Quiz",
          instructions: "Listen one more time. Choose carefully.",
          sortOrder: 2,
          script: annaWeather,
          answerKey: keysAnna,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "That _____ is by the door.",
              skillTag: "listening",
              topicTag,
              explanation: "Kite — That kite is by the door.",
              correct: "kite",
              wrong: ["robot", "cloud"],
              distractorNotes: ["Nam's toy", "Sky"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna has a blue _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Balloon — I have a blue balloon.",
              correct: "balloon",
              wrong: ["kite", "puzzle"],
              distractorNotes: ["Mai's kite", "Nam's puzzle"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-anna-apply",
          title: "Apply: Match Weather and Toy Facts",
          instructions: "Listen again. Match facts from the dialogue.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: annaWeather, answerKey: keysAnna },
          questions: [
            buildMatching({
              questionText: "Match facts from the weather dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Weather=rainy+windy; clouds=Anna sees; kite=by door; puzzles=those, fun.",
              pairs: [
                { left: "weather now", right: "rainy and windy" },
                { left: "Anna sees", right: "clouds" },
                { left: "kite", right: "by the door" },
                { left: "puzzles", right: "those, fun" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-anna-review",
          title: "Review: Weather Dialogue Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: annaWeather,
          answerKey: keysAnna,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Dad asks: Is it _____?",
              skillTag: "listening",
              topicTag,
              explanation: "Sunny — Is it sunny?",
              correct: "sunny",
              wrong: ["rainy", "robot"],
              distractorNotes: ["Anna says no — rainy", "Toy"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai says: These are my toys _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Inside — These are my toys inside.",
              correct: "inside",
              wrong: ["outside", "at the zoo"],
              distractorNotes: ["Kite later outside", "Unit 4"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When can they go outside?",
              skillTag: "listening",
              topicTag,
              explanation: "When it is sunny — Dad's answer.",
              correct: "when it is sunny",
              wrong: ["now", "never"],
              distractorNotes: ["Not now", "Dad says when sunny"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-mixed-toys-weather",
      title: "Lesson 3: Mixed Text MCQ",
      learningObjective:
        "Review both listening scripts with mixed text-only MCQs.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-mixed-learn",
          title: "Learn: Mai's Toys Again",
          instructions: "Listen to Mai's toys dialogue. Choose the best answer.",
          sortOrder: 0,
          script: maiToys,
          answerKey: keysMai,
          questions: [
            buildMcq({
              questionText: "Choose the best answer: Mai's favourite toys include a _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Teddy — teddy and doll.",
              correct: "teddy",
              wrong: ["cloud", "wind"],
              distractorNotes: ["Weather", "Weather"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Choose the best answer: They play with toys because it is _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Rainy — Today is rainy.",
              correct: "rainy",
              wrong: ["sunny", "cloudy only"],
              distractorNotes: ["Later sunny", "Rainy in dialogue"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-practice",
          title: "Practice: Weather Text MCQ",
          instructions: "Listen to Anna and weather. Choose the best answer.",
          sortOrder: 1,
          script: annaWeather,
          answerKey: keysAnna,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Choose the best answer: Anna can see _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Clouds — I can see clouds.",
              correct: "clouds",
              wrong: ["two robots", "a shop"],
              distractorNotes: ["Nam has one robot", "Không mua"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Choose the best answer: Those _____ are fun!",
              skillTag: "listening",
              topicTag,
              explanation: "Puzzles — Those puzzles are fun!",
              correct: "puzzles",
              wrong: ["clouds", "wind"],
              distractorNotes: ["Sky", "Air"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-check",
          title: "Check: Mixed Listening Quiz",
          instructions: "Listen to the weather dialogue one final time.",
          sortOrder: 2,
          script: annaWeather,
          answerKey: keysAnna,
          difficulty: 0.36,
          questions: [
            buildMcq({
              questionText: "Which toy + fact do you hear in the weather dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Blue balloon — Anna has a blue balloon.",
              correct: "blue balloon",
              wrong: ["red robot on table", "teddy favourite"],
              distractorNotes: ["Mai's toys dialogue", "Mai's toys dialogue"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which pair is NOT in the weather dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Red and blue balloons — only in Mai's toys dialogue.",
              correct: "red and blue balloons",
              wrong: ["rainy and windy", "kite by the door"],
              distractorNotes: ["Có", "Có"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-mixed-apply",
          title: "Apply: Match Both Dialogues",
          instructions: "Listen to Mai's toys. Match facts to dialogue 1 or 2.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: maiToys, answerKey: keysMai },
          questions: [
            buildMatching({
              questionText: "Match facts to Mai's toys (1) or weather (2) dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Teddy+doll=1; rainy stay inside=1; clouds=2; kite by door=2.",
              pairs: [
                { left: "teddy and doll favourites", right: "dialogue 1 — Mai's toys" },
                { left: "rainy — stay inside", right: "dialogue 1 — Mai's toys" },
                { left: "see clouds", right: "dialogue 2 — weather" },
                { left: "kite by the door", right: "dialogue 2 — weather" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-review",
          title: "Review: Full Toys and Weather Listening",
          instructions: "Listen to the weather dialogue and answer — full review.",
          sortOrder: 4,
          script: annaWeather,
          answerKey: keysAnna,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Both dialogues mention Mai. Who is with her in dialogue 2?",
              skillTag: "listening",
              topicTag,
              explanation: "Anna and Dad — speakers in weather dialogue.",
              correct: "Anna and Dad",
              wrong: ["Mum only", "Nam only"],
              distractorNotes: ["Mum in dialogue 1", "Nam not in dialogue 2"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word appears in BOTH dialogues?",
              skillTag: "listening",
              topicTag,
              explanation: "Toys — play with toys / these are my toys.",
              correct: "toys",
              wrong: ["elephant", "jacket"],
              distractorNotes: ["Unit 4", "Unit 3 clothes"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best summary: the listening lessons are about _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Toys indoors and weather — text-only listen and choose.",
              correct: "toys and weather with Mai's family and friends",
              wrong: ["animals at the zoo", "numbers and time"],
              distractorNotes: ["Unit 4", "Unit 2"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
