/** Starters U5 — reading lessons (3 × 5 exercises). Text-only — no images. */

export function readingLessons({
  buildMcq,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMaiToysAndRain,
  topicTag,
}) {
  const passage = passageMaiToysAndRain;

  return [
    {
      slug: "reading-toy-weather-words",
      title: "Lesson 1: Toy and Weather Words",
      learningObjective:
        "Read toy and weather words in context and match them to meanings.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-words-learn",
          title: "Learn: Read Toy and Weather Words",
          instructions: "Read the text. Then answer the questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What is the main idea of the text?",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation:
                "Bài về đồ chơi trong nhà ngày mưa và thả diều khi trời nắng.",
              correct: "Toys on a rainy day and a kite outside.",
              wrong: ["Mai goes shopping for clothes.", "Mai learns about animals."],
              distractorNotes: ["Unit 3 — quần áo", "Unit 4 — động vật"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which word means 'gấu bông'?",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "Teddy = gấu bông — Mai plays with her teddy.",
              correct: "teddy",
              wrong: ["robot", "cloud"],
              distractorNotes: ["Người máy", "Mây"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-words-practice",
          title: "Practice: More Words in the Text",
          instructions: "Read again. Find more toy and weather words.",
          sortOrder: 1,
          passage,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "It is a rainy and _____ day.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Windy — rainy and windy day.",
              correct: "windy",
              wrong: ["sunny", "robot"],
              distractorNotes: ["Sunny — phần sau", "Đồ chơi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Nam has a robot and a _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Puzzle — Nam has a robot and a puzzle.",
              correct: "puzzle",
              wrong: ["kite", "cloud"],
              distractorNotes: ["Diều — ngoài vườn sau", "Mây trên trời"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-words-check",
          title: "Check: Words in Text Quiz",
          instructions: "Read carefully. Choose the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Which toy word is NOT in the text?",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "Doll có trong bài. Robot, puzzle, teddy, kite, balloon có. Shop không có.",
              correct: "shop",
              wrong: ["doll", "kite"],
              distractorNotes: ["Có — Mai's doll", "Có — red kite"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna has a blue _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Balloon — Anna has a blue balloon.",
              correct: "balloon",
              wrong: ["robot", "puzzle"],
              distractorNotes: ["Nam's toy", "Nam's toy"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-words-apply",
          title: "Apply: Match Words to Descriptions",
          instructions: "Use the text. Match words to descriptions.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match words from the text to short descriptions.",
              skillTag: "reading",
              topicTag,
              explanation: "Teddy/doll=Mai plays; robot/puzzle=Nam; kite=red, outside; rainy+windy=start.",
              pairs: [
                { left: "teddy", right: "Mai plays with it" },
                { left: "robot", right: "Nam has it" },
                { left: "kite", right: "red, flies outside" },
                { left: "rainy", right: "stay inside" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-words-review",
          title: "Review: Toy and Weather Words Mix",
          instructions: "Read the text again. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Mum says: Look at the _____!",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Clouds — Look at the clouds!",
              correct: "clouds",
              wrong: ["kites", "robots"],
              distractorNotes: ["Diều — sau", "Robot — Nam"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The word 'wind' in the text means:",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "Wind = gió — The wind is strong.",
              correct: "moving air outside",
              wrong: ["a toy", "rain from the sky"],
              distractorNotes: ["Đồ chơi", "Mưa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Those _____ are on the chair.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Balloons — Those balloons are on the chair.",
              correct: "balloons",
              wrong: ["clouds", "puzzles"],
              distractorNotes: ["Mây trên trời", "Trên bàn"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-rainy-day",
      title: "Lesson 2: Rainy Day Indoors",
      learningObjective:
        "Read about staying inside on a rainy and windy day.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-rainy-learn",
          title: "Learn: Read About the Rainy Day",
          instructions: "Read the first part. Answer the questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What is the weather like at the start?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Rainy and windy — It is a rainy and windy day.",
              correct: "Rainy and windy",
              wrong: ["Sunny and hot", "Snowy and cold"],
              distractorNotes: ["Phần sau — nắng", "Không có tuyết"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Where do Mai, Nam and Anna stay?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Inside — stay inside.",
              correct: "Inside",
              wrong: ["At the park", "At the shop"],
              distractorNotes: ["Ra ngoài sau", "Không đi mua"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-rainy-practice",
          title: "Practice: More Rainy Day Details",
          instructions: "Read again. Answer about toys inside.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "What does Mai play with?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Teddy and doll — Mai plays with her teddy and her doll.",
              correct: "teddy and doll",
              wrong: ["kite only", "balloon only"],
              distractorNotes: ["Diều — sau, ngoài trời", "Balloon — Anna sau"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What do they do together?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "A puzzle — They do a puzzle together.",
              correct: "a puzzle",
              wrong: ["fly a kite", "buy toys"],
              distractorNotes: ["Khi nắng", "Không mua đồ"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-rainy-check",
          title: "Check: Rainy Day Quiz",
          instructions: "Read carefully. Choose the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.35,
          questions: [
            buildMcq({
              questionText: "Mai says: These are my _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Toys — These are my toys.",
              correct: "toys",
              wrong: ["clouds", "wind"],
              distractorNotes: ["Mây", "Gió"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who looks out of the window?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Mum — Mum looks out of the window.",
              correct: "Mum",
              wrong: ["Anna", "Dad"],
              distractorNotes: ["Anna bạn Mai", "Dad — phần sau"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-rainy-apply",
          title: "Apply: Match Rainy Day Facts",
          instructions: "Match each fact to the text.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match rainy-day facts from the reading.",
              skillTag: "reading",
              topicTag,
              explanation: "Weather=rainy+windy; Mai=teddy+doll; Nam=robot+puzzle; Mum=clouds.",
              pairs: [
                { left: "weather at start", right: "rainy and windy" },
                { left: "Mai's toys", right: "teddy and doll" },
                { left: "Nam's toys", right: "robot and puzzle" },
                { left: "Mum sees", right: "clouds" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-rainy-review",
          title: "Review: Rainy Day Mix",
          instructions: "Read and answer — mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.33,
          questions: [
            buildMcq({
              questionText: "Why do they stay inside at first?",
              skillTag: "reading",
              topicTag,
              assessmentType: "inference",
              explanation: "Because it is rainy and windy.",
              correct: "Bad weather — rain and wind",
              wrong: ["They are at school", "They have no toys"],
              distractorNotes: ["Ở nhà", "Có nhiều đồ chơi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "His puzzle is on the _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Table — His puzzle is on the table (listening); reading: puzzle with Nam.",
              correct: "table",
              wrong: ["chair", "garden"],
              distractorNotes: ["Balloons on chair", "Kite in garden"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Complete: They stay _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Inside — stay inside on rainy day.",
              correct: "inside",
              wrong: ["outside", "at the zoo"],
              distractorNotes: ["Ra ngoài sau", "Unit 4 zoo"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-toys-weather-together",
      title: "Lesson 3: Toys and Weather Together",
      learningObjective:
        "Find details about going outside with a kite when weather changes.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-together-learn",
          title: "Learn: Read the Sunny Part",
          instructions: "Read about when the sun comes out. Answer the questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "When the sun comes out, it is sunny and _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Cloudy — sunny and cloudy.",
              correct: "cloudy",
              wrong: ["rainy", "robot"],
              distractorNotes: ["Trước đó mưa", "Đồ chơi"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What does Dad say Mai can do?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Fly kite — You can fly your kite outside!",
              correct: "fly her kite outside",
              wrong: ["stay inside", "buy a doll"],
              distractorNotes: ["Trước đó", "Không mua"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-together-practice",
          title: "Practice: Kite and Wind Details",
          instructions: "Read again. Find more details outside.",
          sortOrder: 1,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Mai runs into the garden with her _____ kite.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Red — her red kite.",
              correct: "red",
              wrong: ["blue", "rainy"],
              distractorNotes: ["Blue = Anna's balloon", "Thời tiết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The wind is _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Strong — The wind is strong.",
              correct: "strong",
              wrong: ["small", "sleepy"],
              distractorNotes: ["Không mô tả", "Không nêu"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-together-check",
          title: "Check: Toys and Weather Quiz",
          instructions: "Read one more time. Harder questions.",
          sortOrder: 2,
          passage,
          difficulty: 0.38,
          questions: [
            buildMcq({
              questionText: "Anna has a blue _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Balloon — Anna has a blue balloon.",
              correct: "balloon",
              wrong: ["kite", "puzzle"],
              distractorNotes: ["Mai's kite is red", "Nam's puzzle"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How do they feel at the end?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Happy — They have a happy day.",
              correct: "happy",
              wrong: ["sad", "angry"],
              distractorNotes: ["Trái nghĩa", "Không nêu"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-together-apply",
          title: "Apply: Match Toys and Weather Facts",
          instructions: "Match people, toys and weather to facts.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match facts from the full reading.",
              skillTag: "reading",
              topicTag,
              explanation: "Start=rainy+windy; Dad=kite outside; Mai=red kite; Anna=blue balloon; end=happy.",
              pairs: [
                { left: "start of day", right: "rainy and windy" },
                { left: "Dad", right: "fly kite outside" },
                { left: "Mai outside", right: "red kite" },
                { left: "Anna", right: "blue balloon" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-together-review",
          title: "Review: Full Reading Mix",
          instructions: "Find details in the text.",
          sortOrder: 4,
          passage,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "The text is mainly about:",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation: "Rainy day toys inside + sunny kite and balloon outside.",
              correct: "toys and weather with Mai, Nam and Anna",
              wrong: ["animals at the zoo", "colours and clothes"],
              distractorNotes: ["Unit 4", "Unit 3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai is _____ years old.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Eight — Mai is eight.",
              correct: "eight",
              wrong: ["six", "ten"],
              distractorNotes: ["Không nêu", "Không nêu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence uses these/those correctly from the text?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "These are my toys / Those balloons are on the chair.",
              correct: "Those balloons are on the chair.",
              wrong: ["These balloons are far away.", "Those is my toys."],
              distractorNotes: ["Balloons on chair = those", "Those is sai"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
