/** Starters U5 — speaking lessons (3 × 5 exercises; only Check is AI). */

const MAI_INDOOR_SCENE =
  "Mai's home on a rainy and windy day. Mai is eight. She plays with her teddy and doll inside. Her brother Nam has a robot and a puzzle on the table. Red and blue balloons are on the chair. Her friend Anna visits. Mum says they must stay inside. Clouds are in the sky.";

const MAI_OUTDOOR_SCENE =
  "Later the sun comes out. It is sunny and cloudy. Mai, Nam and Anna go into the garden. Mai flies her red kite. The wind is strong. Anna holds a blue balloon. Dad says they can play outside now. Toys stay inside; the kite and balloon are outside.";

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [toysCheck, weatherCheck, theseCheck] = speakingChecks;

  return [
    {
      slug: "speaking-toys",
      title: "Lesson 1: Talk About Toys",
      learningObjective:
        "Answer simple questions about toys with short phrases.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-toys-learn",
          title: "Learn: What to Say About Toys",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { sceneDescription: MAI_INDOOR_SCENE },
          questions: [
            buildMcq({
              questionText: "Someone asks: Do you have toys? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes. / Yes, I have toys.",
              correct: "Yes. I have toys.",
              wrong: ["No toys ever.", "Yes. I have clouds."],
              distractorNotes: ["Mai có đồ chơi", "Clouds = thời tiết"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Someone asks: What is your favourite toy? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "My teddy. / I like my teddy and doll.",
              correct: "I like my teddy and doll.",
              wrong: ["I like rainy.", "I like wind."],
              distractorNotes: ["Thời tiết", "Gió"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-toys-practice",
          title: "Practice: Toy Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { sceneDescription: MAI_INDOOR_SCENE },
          questions: [
            buildMcq({
              questionText: "Mum asks: What does Nam have? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "A robot. / Nam has a robot.",
              correct: "A robot.",
              wrong: ["A cloud.", "Rainy."],
              distractorNotes: ["Mây", "Thời tiết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Friend asks: Where is the puzzle? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "On the table.",
              correct: "On the table.",
              wrong: ["In the sky.", "It is windy."],
              distractorNotes: ["Trên trời", "Thời tiết"],
              difficultyRating: 2,
            }),
          ],
        }),
        toysCheck,
        buildExercise({
          slug: "speaking-toys-apply",
          title: "Apply: Quick Toy Replies",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Point to toys in your hands. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "These are my toys.",
              correct: "These are my toys.",
              wrong: ["Those are my toys here.", "These is my toy."],
              distractorNotes: ["Gần → these", "Is sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say what Anna likes. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "She likes her doll. / Anna likes her doll.",
              correct: "Anna likes her doll.",
              wrong: ["Anna likes clouds.", "Anna is windy."],
              distractorNotes: ["Mây", "Windy = có gió"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-toys-review",
          title: "Review: Toy Speaking",
          instructions: "Choose the best spoken reply.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "How many balloons on the chair? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Two. / Red and blue balloons.",
              correct: "Two balloons.",
              wrong: ["One cloud.", "Zero toys."],
              distractorNotes: ["Mây", "Có balloons"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Describe Nam's toys. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "A robot and a puzzle.",
              correct: "A robot and a puzzle.",
              wrong: ["A kite and wind.", "Rainy and cloudy."],
              distractorNotes: ["Kite — Mai", "Thời tiết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say one sentence with these + toys. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "These are my toys.",
              correct: "These are my toys.",
              wrong: ["These is my toys.", "Those are my toys in my hands."],
              distractorNotes: ["Is sai", "Gần → these"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-weather",
      title: "Lesson 2: Talk About the Weather",
      learningObjective:
        "Answer questions about weather with It's + adjective.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-weather-learn",
          title: "Learn: Weather Speaking Phrases",
          instructions: "Read the scene description. Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { sceneDescription: MAI_INDOOR_SCENE },
          questions: [
            buildMcq({
              questionText: "What is the weather like? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "It's rainy and windy.",
              correct: "It's rainy and windy.",
              wrong: ["They rainy.", "It sunny."],
              distractorNotes: ["They sai", "Thiếu is"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mum says: Look at the sky! You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Clouds! / Look at the clouds!",
              correct: "Look at the clouds!",
              wrong: ["Look at the robots!", "Look at the puzzle!"],
              distractorNotes: ["Robot Nam", "Puzzle trên bàn"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-weather-practice",
          title: "Practice: Weather Questions",
          instructions: "Choose what you would say about the weather.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { sceneDescription: MAI_INDOOR_SCENE },
          questions: [
            buildMcq({
              questionText: "Examiner: Is it sunny now? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "No. It's rainy.",
              correct: "No. It's rainy.",
              wrong: ["Yes. It's rainy.", "No. They sunny."],
              distractorNotes: ["Mưa không nắng", "They sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: Can you fly a kite now? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "No. We stay inside.",
              correct: "No. We stay inside.",
              wrong: ["Yes. It is rainy.", "Yes. The puzzle flies."],
              distractorNotes: ["Mưa — ở trong", "Puzzle không bay"],
              difficultyRating: 2,
            }),
          ],
        }),
        weatherCheck,
        buildExercise({
          slug: "speaking-weather-apply",
          title: "Apply: Weather Speaking",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Describe the wind. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "The wind is strong.",
              correct: "The wind is strong.",
              wrong: ["The wind are strong.", "The windy is strong."],
              distractorNotes: ["Wind số ít", "Windy = tính từ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say it's cloudy later. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "It's sunny and cloudy.",
              correct: "It's sunny and cloudy.",
              wrong: ["It's cloud.", "They cloudy."],
              distractorNotes: ["Cloud = danh từ", "They sai"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-weather-review",
          title: "Review: Weather Speaking Mix",
          instructions: "Choose the best phrase.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Why stay inside? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Because it's rainy and windy.",
              correct: "Because it's rainy and windy.",
              wrong: ["Because it's sunny.", "Because toys are clouds."],
              distractorNotes: ["Nắng — ra ngoài", "Clouds không phải toys"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna sees clouds. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I can see clouds.",
              correct: "I can see clouds.",
              wrong: ["I can see kites inside.", "I can see robots in the sky."],
              distractorNotes: ["Kite — cửa", "Robot — bàn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say: It's _____. (windy)",
              skillTag: "speaking",
              topicTag,
              explanation: "It's windy.",
              correct: "It's windy.",
              wrong: ["It windy.", "They windy."],
              distractorNotes: ["Thiếu is", "They sai"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-these-those",
      title: "Lesson 3: These and Those Speaking",
      learningObjective:
        "Use these, those, and plurals when talking about toys.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-these-learn",
          title: "Learn: These/Those Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { sceneDescription: MAI_OUTDOOR_SCENE },
          questions: [
            buildMcq({
              questionText: "Examiner: Point to toys near you. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "These are my toys.",
              correct: "These are my toys.",
              wrong: ["Those are my toys here.", "These is my toy."],
              distractorNotes: ["Gần → these", "Is sai"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Examiner: Balloons on the chair (far). You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Those balloons are red and blue.",
              correct: "Those balloons are on the chair.",
              wrong: ["These balloons are far.", "Those balloon is red."],
              distractorNotes: ["Xa → those", "Balloon số ít"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-these-practice",
          title: "Practice: More These/Those Replies",
          instructions: "Choose what you would say.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { sceneDescription: MAI_OUTDOOR_SCENE },
          questions: [
            buildMcq({
              questionText: "Kite by the door. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "That kite is by the door.",
              correct: "That kite is by the door.",
              wrong: ["This kite is by the door far.", "Those kite is by the door."],
              distractorNotes: ["Xa → that", "Those + kite số ít"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna: Those puzzles are fun! You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes! Those puzzles are fun!",
              correct: "Yes! Those puzzles are fun!",
              wrong: ["Yes! These puzzles are far.", "Yes! Those puzzle is fun."],
              distractorNotes: ["Xa → those", "Puzzle số ít"],
              difficultyRating: 2,
            }),
          ],
        }),
        theseCheck,
        buildExercise({
          slug: "speaking-these-apply",
          title: "Apply: Quick These/Those Replies",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Say: two kites. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Two kites. — plural -s.",
              correct: "Two kites.",
              wrong: ["Two kite.", "Two kiting."],
              distractorNotes: ["Thiếu -s", "Sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai flies her kite outside. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Mai flies her red kite.",
              correct: "Mai flies her red kite.",
              wrong: ["Mai flies her red kites inside.", "Mai flies cloudy."],
              distractorNotes: ["One kite", "Cloudy = thời tiết"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-these-review",
          title: "Review: These/Those Speaking Mix",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "These are my favourite _____. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Toys — from listening script.",
              correct: "toys",
              wrong: ["clouds", "wind"],
              distractorNotes: ["Thời tiết", "Gió"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Those balloons _____ red and blue. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Are — balloons số nhiều.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is số ít", "Am với I"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say one sentence with those + plural toy. Best:",
              skillTag: "speaking",
              topicTag,
              explanation: "Those balloons are on the chair.",
              correct: "Those balloons are on the chair.",
              wrong: ["Those balloon is on the chair.", "These balloons are far away."],
              distractorNotes: ["Balloon số ít", "Xa → those OK nhưng câu mẫu chair"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
