/** Starters U5 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-toys",
      title: "Lesson 1: Toys",
      learningObjective:
        "Recognise and use doll, kite, teddy and robot in short sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-toys-learn",
          title: "Learn: Toy Words",
          instructions: "Read each clue. Choose the best toy.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "You hug this soft toy at night.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Teddy (gấu bông) — đồ chơi mềm để ôm.",
              correct: "teddy",
              wrong: ["robot", "kite"],
              distractorNotes: ["Robot cứng, có nút", "Diều bay ngoài trời"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "You fly this on a windy day outside.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Kite (diều) — thả khi có gió.",
              correct: "kite",
              wrong: ["doll", "puzzle"],
              distractorNotes: ["Búp bê cầm tay", "Xếp hình trên bàn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "A girl often plays with this toy person.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Doll (búp bê) — đồ chơi hình người.",
              correct: "doll",
              wrong: ["balloon", "cloud"],
              distractorNotes: ["Bóng bay", "Mây — không phải đồ chơi"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Nam has a red _____ that can move.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Robot — Nam has a red robot.",
              correct: "robot",
              wrong: ["teddy", "wind"],
              distractorNotes: ["Gấu bông mềm", "Gió — thời tiết"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-toys-practice",
          title: "Practice: Match Toys",
          instructions: "Match each toy to its Vietnamese meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match toys to their Vietnamese meanings.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Doll=búp bê; kite=diều; teddy=gấu bông; robot=người máy.",
              pairs: [
                { left: "doll", right: "búp bê" },
                { left: "kite", right: "diều" },
                { left: "teddy", right: "gấu bông" },
                { left: "robot", right: "người máy (đồ chơi)" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-toys-check",
          title: "Check: Toys Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Mai plays with her teddy and her _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Doll — Mai plays with her teddy and her doll.",
              correct: "doll",
              wrong: ["cloud", "rainy"],
              distractorNotes: ["Mây — thời tiết", "Tính từ thời tiết"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Dad says Mai can fly her _____ outside.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Kite — fly your kite outside.",
              correct: "kite",
              wrong: ["puzzle", "robot"],
              distractorNotes: ["Xếp hình trong nhà", "Robot trên bàn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which toy is soft and you can hug?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Teddy — soft toy to hug.",
              correct: "teddy",
              wrong: ["robot", "kite"],
              distractorNotes: ["Robot cứng", "Diều giấy/vải bay"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-toys-apply",
          title: "Apply: Toys in Sentences",
          instructions: "Complete each sentence with the correct toy word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: Mai has a [0]. | Nam has a [1]. | Fly the [2] outside.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "teddy/doll; robot; kite — đồ chơi Mai và Nam.",
              template: "Mai has a [0]. Nam has a [1]. Fly the [2] outside.",
              correctAnswers: ["teddy", "robot", "kite"],
              acceptableAnswers: [
                ["teddy", "Teddy", "doll", "Doll"],
                ["robot", "Robot"],
                ["kite", "Kite"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-toys-review",
          title: "Review: Toys Mix",
          instructions: "Mixed review. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which word means 'diều'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Kite = diều.",
              correct: "kite",
              wrong: ["doll", "balloon"],
              distractorNotes: ["Búp bê", "Bóng bay"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna likes her _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Doll — Anna likes her doll (from listening).",
              correct: "doll",
              wrong: ["cloud", "windy"],
              distractorNotes: ["Mây", "Có gió — không phải đồ chơi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which toy does Nam have on the table?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Puzzle — His puzzle is on the table (listening).",
              correct: "puzzle",
              wrong: ["kite", "cloud"],
              distractorNotes: ["Diều ở cửa", "Mây trên trời"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-toys-weather",
      title: "Lesson 2: More Toys and Weather",
      learningObjective:
        "Recognise puzzle, balloon, sunny and rainy in context.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-weather-toys-learn",
          title: "Learn: Toys and Weather Words",
          instructions: "Read each clue. Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "You put many small pieces together to make a picture.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Puzzle (xếp hình) — ghép mảnh thành hình.",
              correct: "puzzle",
              wrong: ["balloon", "kite"],
              distractorNotes: ["Bóng bay phồng", "Diều bay"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "This round toy floats in the air when you blow it.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Balloon (bóng bay) — thổi phồng, bay lên.",
              correct: "balloon",
              wrong: ["robot", "cloud"],
              distractorNotes: ["Robot đi bộ", "Mây trên trời thật"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The sun is in the sky. It is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Sunny (nắng) — có nắng, trời đẹp.",
              correct: "sunny",
              wrong: ["rainy", "robot"],
              distractorNotes: ["Mưa — trái nghĩa", "Đồ chơi"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Water falls from the sky. It is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rainy (mưa) — trời mưa.",
              correct: "rainy",
              wrong: ["sunny", "teddy"],
              distractorNotes: ["Nắng", "Gấu bông"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-weather-toys-practice",
          title: "Practice: Match Toys and Weather",
          instructions: "Match each word to a short description.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match words to descriptions.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Puzzle=pieces on table; balloon=blue/red float; sunny=sun out; rainy=stay inside.",
              pairs: [
                { left: "puzzle", right: "pieces on the table" },
                { left: "balloon", right: "red and blue, on the chair" },
                { left: "sunny", right: "sun comes out" },
                { left: "rainy", right: "stay inside" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-weather-toys-check",
          title: "Check: Toys and Weather Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Today is _____. We stay inside.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rainy — Today is rainy. We stay inside.",
              correct: "rainy",
              wrong: ["sunny", "doll"],
              distractorNotes: ["Nắng — ra ngoài", "Đồ chơi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Those _____ are red and blue.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Balloons — Those balloons are red and blue.",
              correct: "balloons",
              wrong: ["kites", "clouds"],
              distractorNotes: ["Diều — một cái", "Mây trên trời"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They do a _____ together inside.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Puzzle — They do a puzzle together.",
              correct: "puzzle",
              wrong: ["kite", "wind"],
              distractorNotes: ["Diều ngoài trời", "Gió — danh từ"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-weather-toys-apply",
          title: "Apply: Toys and Weather Sentences",
          instructions: "Complete each sentence.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: It is [0]. | Anna has a blue [1]. | They do a [2].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "rainy/sunny; balloon; puzzle — thời tiết và đồ chơi.",
              template: "It is [0]. Anna has a blue [1]. They do a [2].",
              correctAnswers: ["rainy", "balloon", "puzzle"],
              acceptableAnswers: [
                ["rainy", "Rainy", "sunny", "Sunny"],
                ["balloon", "Balloon"],
                ["puzzle", "Puzzle"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-weather-toys-review",
          title: "Review: Toys and Weather Mix",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "When it is _____, Mai flies her kite outside.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Sunny — When the sun comes out, it is sunny.",
              correct: "sunny",
              wrong: ["rainy", "puzzle"],
              distractorNotes: ["Mưa — ở trong", "Đồ chơi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word is a weather word, not a toy?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rainy là thời tiết. Balloon, puzzle, robot là đồ chơi.",
              correct: "rainy",
              wrong: ["balloon", "robot"],
              distractorNotes: ["Đồ chơi", "Đồ chơi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum says: Look at the _____!",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Clouds — Look at the clouds!",
              correct: "clouds",
              wrong: ["robots", "teddy"],
              distractorNotes: ["Robot số nhiều", "Gấu bông"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-cloud-wind",
      title: "Lesson 3: Cloud, Wind, Cloudy and Windy",
      learningObjective:
        "Use cloud, wind, cloudy and windy with toy words.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-cloud-learn",
          title: "Learn: Cloud and Wind Words",
          instructions: "Read each clue. Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "White or grey things in the sky.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cloud (mây) — đám mây trên trời.",
              correct: "cloud",
              wrong: ["balloon", "puzzle"],
              distractorNotes: ["Bóng bay trong nhà", "Xếp hình"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Air that moves fast — good for flying a kite.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Wind (gió) — gió mạnh thả diều.",
              correct: "wind",
              wrong: ["rainy", "doll"],
              distractorNotes: ["Mưa", "Búp bê"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Many clouds in the sky. It is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cloudy (có mây) — sunny and cloudy.",
              correct: "cloudy",
              wrong: ["sunny", "robot"],
              distractorNotes: ["Nắng — có thể cả hai", "Đồ chơi"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The _____ is strong today. Hold your kite!",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Wind — The wind is strong.",
              correct: "wind",
              wrong: ["puzzle", "teddy"],
              distractorNotes: ["Xếp hình", "Gấu bông"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-cloud-practice",
          title: "Practice: Match Cloud and Wind",
          instructions: "Match each word to its Vietnamese meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match weather words to Vietnamese meanings.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cloud=mây; wind=gió; cloudy=có mây; windy=có gió.",
              pairs: [
                { left: "cloud", right: "mây" },
                { left: "wind", right: "gió" },
                { left: "cloudy", right: "có mây, nhiều mây" },
                { left: "windy", right: "có gió, nhiều gió" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-cloud-check",
          title: "Check: Cloud and Wind Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "It is rainy and _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Windy — It is rainy and windy.",
              correct: "windy",
              wrong: ["teddy", "robot"],
              distractorNotes: ["Gấu bông", "Robot"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna says: I can see _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Clouds — I can see clouds.",
              correct: "clouds",
              wrong: ["kites", "puzzles"],
              distractorNotes: ["Diều", "Xếp hình"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "It is sunny and _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cloudy — sunny and cloudy.",
              correct: "cloudy",
              wrong: ["rainy", "doll"],
              distractorNotes: ["Mưa — khác đoạn sau", "Búp bê"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-cloud-apply",
          title: "Apply: Weather and Toys Together",
          instructions: "Complete each sentence.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: Look at the [0]! | The [1] is strong. | Fly the [2] outside.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "clouds; wind; kite — mây, gió, diều.",
              template: "Look at the [0]! The [1] is strong. Fly the [2] outside.",
              correctAnswers: ["clouds", "wind", "kite"],
              acceptableAnswers: [
                ["clouds", "Clouds", "cloud", "Cloud"],
                ["wind", "Wind"],
                ["kite", "Kite"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-cloud-review",
          title: "Review: Full Vocabulary",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "How many words are in this unit's vocabulary bank?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Twelve words: doll, kite, teddy, robot, puzzle, balloon, sunny, rainy, cloud, wind, cloudy, windy.",
              correct: "twelve",
              wrong: ["eight", "twenty"],
              distractorNotes: ["Chỉ 10 từ map gốc", "Quá nhiều"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which pair is correct?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Wind = gió; windy = có gió. Cloud = mây; cloudy = có mây.",
              correct: "windy = có gió",
              wrong: ["windy = mây", "cloudy = diều"],
              distractorNotes: ["Windy = gió", "Cloudy = có mây"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The wind is strong — good for a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Kite — strong wind helps fly a kite.",
              correct: "kite",
              wrong: ["puzzle", "doll"],
              distractorNotes: ["Xếp hình trong nhà", "Búp bê trong nhà"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
