/** Starters U5 — writing lessons (3 × 5 exercises; only Check is AI). */

export function writingLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  writingChecks,
  topicTag,
}) {
  const [toysCheck, weatherCheck, theseCheck] = writingChecks;

  return [
    {
      slug: "writing-toys",
      title: "Lesson 1: Write About Toys",
      learningObjective:
        "Write short phrases about toys using these and plural forms.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-toys-learn",
          title: "Learn: Toy Writing Frames",
          instructions: "Complete the sentences about toys.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: These are my [0]. | Nam has a [1]. | I like my [2].",
              skillTag: "writing",
              topicTag,
              explanation: "toys; robot; teddy/doll — khung viết đồ chơi.",
              template: "These are my [0]. Nam has a [1]. I like my [2].",
              correctAnswers: ["toys", "robot", "teddy"],
              acceptableAnswers: [
                ["toys", "Toys"],
                ["robot", "Robot"],
                ["teddy", "Teddy", "doll", "Doll"],
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-toys-practice",
          title: "Practice: Order Toy Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: These / are / my / toys.",
              skillTag: "writing",
              topicTag,
              explanation: "These are my toys. — viết về đồ chơi gần.",
              words: ["These", "are", "my", "toys."],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: Nam / has / a / robot.",
              skillTag: "writing",
              topicTag,
              explanation: "Nam has a robot. — câu về đồ chơi Nam.",
              words: ["Nam", "has", "a", "robot."],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
          ],
        }),
        toysCheck,
        buildExercise({
          slug: "writing-toys-apply",
          title: "Apply: Choose the Best Toy Sentence",
          instructions: "Choose the best written sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best sentence about Mai's toys:",
              skillTag: "writing",
              topicTag,
              explanation: "These are my toys. — these + are + plural.",
              correct: "These are my toys.",
              wrong: ["These is my toys.", "Those are my toys in my hands."],
              distractorNotes: ["Is sai", "Gần → these"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best sentence about balloons:",
              skillTag: "writing",
              topicTag,
              explanation: "Those balloons are red and blue.",
              correct: "Those balloons are red and blue.",
              wrong: ["Those balloon is red.", "These balloons are far."],
              distractorNotes: ["Balloon số ít", "Gần → these"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-toys-review",
          title: "Review: Toy Writing",
          instructions: "Complete the writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 4,
          questions: [
            buildGapFill({
              questionText: "Complete: Mai plays with her [0]. | Anna likes her [1]. | Two [2] are fun.",
              skillTag: "writing",
              topicTag,
              explanation: "teddy; doll; puzzles/kites — đồ chơi unit.",
              template: "Mai plays with her [0]. Anna likes her [1]. Two [2] are fun.",
              correctAnswers: ["teddy", "doll", "puzzles"],
              acceptableAnswers: [
                ["teddy", "Teddy", "doll", "Doll"],
                ["doll", "Doll"],
                ["puzzles", "Puzzles", "kites", "Kites", "balloons", "Balloons"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "writing-weather",
      title: "Lesson 2: Write About the Weather",
      learningObjective:
        "Write short sentences about weather with It's + adjective.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-weather-learn",
          title: "Learn: Weather Writing Frames",
          instructions: "Complete each sentence about the weather.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] rainy. | [1] sunny and cloudy. | The [2] is strong.",
              skillTag: "writing",
              topicTag,
              explanation: "It's; It's; wind — khung thời tiết.",
              template: "[0] rainy. [1] sunny and cloudy. The [2] is strong.",
              correctAnswers: ["It's", "It's", "wind"],
              acceptableAnswers: [
                ["It's", "It is"],
                ["It's", "It is"],
                ["wind", "Wind"],
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-weather-practice",
          title: "Practice: Order Weather Sentences",
          instructions: "Put words in order to make sentences.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: It's / rainy / and / windy.",
              skillTag: "writing",
              topicTag,
              explanation: "It's rainy and windy. — mô tả trời.",
              words: ["It's", "rainy", "and", "windy."],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: Look / at / the / clouds!",
              skillTag: "writing",
              topicTag,
              explanation: "Look at the clouds! — Mum in reading.",
              words: ["Look", "at", "the", "clouds!"],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
          ],
        }),
        weatherCheck,
        buildExercise({
          slug: "writing-weather-apply",
          title: "Apply: More Weather Frames",
          instructions: "Complete the writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: We stay [0]. | Anna sees [1]. | Fly the kite when [2].",
              skillTag: "writing",
              topicTag,
              explanation: "inside; clouds; sunny — thời tiết và hoạt động.",
              template: "We stay [0]. Anna sees [1]. Fly the kite when [2].",
              correctAnswers: ["inside", "clouds", "sunny"],
              acceptableAnswers: [
                ["inside", "Inside"],
                ["clouds", "Clouds"],
                ["sunny", "Sunny", "it's sunny", "It is sunny"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-weather-review",
          title: "Review: Weather Writing Quiz",
          instructions: "Choose the best sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best sentence about today:",
              skillTag: "writing",
              topicTag,
              explanation: "It's rainy and windy. — từ bài đọc.",
              correct: "It's rainy and windy.",
              wrong: ["They rainy and windy.", "It rainy and windy."],
              distractorNotes: ["They sai", "Thiếu is"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best sentence when sun comes out:",
              skillTag: "writing",
              topicTag,
              explanation: "It's sunny and cloudy.",
              correct: "It's sunny and cloudy.",
              wrong: ["It's sun and cloud.", "They are sunny."],
              distractorNotes: ["Sun/cloud danh từ", "They sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The wind is _____.",
              skillTag: "writing",
              topicTag,
              explanation: "Strong — The wind is strong.",
              correct: "strong",
              wrong: ["rainy", "teddy"],
              distractorNotes: ["Thời tiết khác", "Đồ chơi"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "writing-these-those",
      title: "Lesson 3: Write These and Those",
      learningObjective:
        "Write short phrases using these, those, and plural toy nouns.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-these-learn",
          title: "Learn: These/Those Writing",
          instructions: "Complete sentences with these or those.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] are my toys. | [1] balloons are on the chair. | two [2]",
              skillTag: "writing",
              topicTag,
              explanation: "These; Those; kites — these/those + plural.",
              template: "[0] are my toys. [1] balloons are on the chair. two [2]",
              correctAnswers: ["These", "Those", "kites"],
              acceptableAnswers: [
                ["These", "these"],
                ["Those", "those"],
                ["kites", "Kites", "balloons", "Balloons"],
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-these-practice",
          title: "Practice: Order These/Those Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Those / puzzles / are / fun!",
              skillTag: "writing",
              topicTag,
              explanation: "Those puzzles are fun! — Anna in listening.",
              words: ["Those", "puzzles", "are", "fun!"],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: That / kite / is / by / the / door.",
              skillTag: "writing",
              topicTag,
              explanation: "That kite is by the door. — xa, số ít.",
              words: ["That", "kite", "is", "by", "the", "door."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        theseCheck,
        buildExercise({
          slug: "writing-these-apply",
          title: "Apply: Write These/Those Frames",
          instructions: "Complete the gap-fill writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] are my favourite toys. | [1] balloons are red. | I have two [2].",
              skillTag: "writing",
              topicTag,
              explanation: "These; Those; kites/balloons — hỗn hợp.",
              template: "[0] are my favourite toys. [1] balloons are red. I have two [2].",
              correctAnswers: ["These", "Those", "kites"],
              acceptableAnswers: [
                ["These", "these"],
                ["Those", "those"],
                ["kites", "Kites", "balloons", "Balloons"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-these-review",
          title: "Review: These/Those Writing Mix",
          instructions: "Choose or complete frames.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best written phrase:",
              skillTag: "writing",
              topicTag,
              explanation: "Two kites — số + plural.",
              correct: "two kites",
              wrong: ["two kite", "two kiting"],
              distractorNotes: ["Thiếu -s", "Sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which is wrong to write?",
              skillTag: "writing",
              topicTag,
              explanation: "These is my toys sai — These are my toys.",
              correct: "These is my toys.",
              wrong: ["These are my toys.", "Those balloons are blue."],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Balloons on the chair (far). Best:",
              skillTag: "writing",
              topicTag,
              explanation: "Those balloons are on the chair.",
              correct: "Those balloons are on the chair.",
              wrong: ["These balloons are on the chair far.", "Those balloon is on the chair."],
              distractorNotes: ["Xa → those", "Balloon số ít"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
