/** KET U1 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-perfect-for-since",
      title: "Lesson 1: Present Perfect — For and Since",
      learningObjective:
        "Use present perfect with for and since to talk about study duration.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "grammar-perfect-learn",
          title: "Learn: For and Since",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "I _____ English for two years.",
              skillTag: "grammar",
              topicTag,
              explanation: "For + khoảng thời gian → have studied.",
              correct: "have studied",
              wrong: ["study", "am studying"],
              distractorNotes: ["Present simple", "Present continuous"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh has studied English _____ Year 6.",
              skillTag: "grammar",
              topicTag,
              explanation: "Since + mốc thời gian (Year 6).",
              correct: "since",
              wrong: ["for", "from"],
              distractorNotes: ["For + period", "Less common here"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "She has revised every evening _____ Monday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Since Monday — mốc bắt đầu ôn tập.",
              correct: "since",
              wrong: ["for", "during"],
              distractorNotes: ["For + duration", "During không với present perfect"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "We have had the same timetable _____ one semester.",
              skillTag: "grammar",
              topicTag,
              explanation: "For one semester — khoảng thời gian.",
              correct: "for",
              wrong: ["since", "during"],
              distractorNotes: ["Since + point", "During"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-perfect-practice",
          title: "Practice: Complete For/Since",
          instructions: "Fill in each gap with for or since.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I have lived on campus [0] September. | They have studied Maths [1] three years. | Linh has revised [2] Monday.",
              skillTag: "grammar",
              topicTag,
              explanation: "since; for; since — mốc vs khoảng thời gian.",
              template:
                "I have lived on campus [0] September. They have studied Maths [1] three years. Linh has revised [2] Monday.",
              correctAnswers: ["since", "for", "since"],
              acceptableAnswers: [
                ["since", "Since"],
                ["for", "For"],
                ["since", "Since"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-perfect-check",
          title: "Check: Present Perfect Challenge",
          instructions: "Choose the correct answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "I have studied English since Year 6 — since + point.",
              correct: "I have studied English since Year 6.",
              wrong: [
                "I have studied English for Year 6.",
                "I study English since Year 6.",
              ],
              distractorNotes: ["For + period", "Wrong tense"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh _____ every evening since Monday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Has revised — present perfect với she.",
              correct: "has revised",
              wrong: ["have revised", "has revise"],
              distractorNotes: ["Wrong person", "Wrong participle"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How long have you _____ at this school?",
              skillTag: "grammar",
              topicTag,
              explanation: "Have you studied — present perfect question.",
              correct: "studied",
              wrong: ["study", "studying"],
              distractorNotes: ["Need past participle", "Wrong form"],
              difficultyRating: 3,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-perfect-apply",
          title: "Apply: Build the Sentence",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: I / have studied / English / since / Year 6.",
              skillTag: "grammar",
              topicTag,
              explanation: "I have studied English since Year 6.",
              words: ["I", "have studied", "English", "since", "Year 6."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: She / has revised / every evening / for / three days.",
              skillTag: "grammar",
              topicTag,
              explanation: "She has revised every evening for three days.",
              words: ["She", "has revised", "every evening", "for", "three days."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-perfect-review",
          title: "Review: For/Since Mix",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "We have done revision _____ Monday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Since Monday — mốc thời gian.",
              correct: "since",
              wrong: ["for", "during"],
              distractorNotes: ["For + three days etc.", "During"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They have studied Maths _____ three years.",
              skillTag: "grammar",
              topicTag,
              explanation: "For three years — khoảng thời gian.",
              correct: "for",
              wrong: ["since", "from"],
              distractorNotes: ["Since + point", "Less common"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-have-need-to",
      title: "Lesson 2: Have to and Need to",
      learningObjective:
        "Use have to and need to to talk about school rules and study obligations.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "grammar-obligation-learn",
          title: "Learn: School Rules",
          instructions: "Choose the correct phrase.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Students _____ bring their ID to the library.",
              skillTag: "grammar",
              topicTag,
              explanation: "Students (plural) → have to.",
              correct: "have to",
              wrong: ["has to", "having to"],
              distractorNotes: ["Singular only", "Wrong form"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "You _____ finish your assignment before the deadline.",
              skillTag: "grammar",
              topicTag,
              explanation: "Need to + base verb.",
              correct: "need to",
              wrong: ["need", "needs to"],
              distractorNotes: ["Missing to", "Wrong person"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh _____ finish her history assignment this month.",
              skillTag: "grammar",
              topicTag,
              explanation: "Has to — she + obligation.",
              correct: "has to",
              wrong: ["have to", "need"],
              distractorNotes: ["Plural", "Missing to"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-obligation-practice",
          title: "Practice: Complete Obligations",
          instructions: "Fill in have to, has to or need to.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I [0] finish my assignment. | She [1] work harder at maths. | We [2] to be quiet in the library.",
              skillTag: "grammar",
              topicTag,
              explanation: "have to; needs to; have — need to / have to.",
              template:
                "I [0] finish my assignment. She [1] work harder at maths. We [2] to be quiet in the library.",
              correctAnswers: ["have to", "needs to", "have"],
              acceptableAnswers: [
                ["have to", "Have to", "need to", "Need to"],
                ["needs to", "Needs to", "has to", "Has to"],
                ["have", "Have", "need", "Need"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-obligation-check",
          title: "Check: Obligation Challenge",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Linh doesn't _____ go to revision club.",
              skillTag: "grammar",
              topicTag,
              explanation: "Doesn't have to — không bắt buộc.",
              correct: "have to",
              wrong: ["has to", "need"],
              distractorNotes: ["Affirmative only", "Missing to"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Students need to bring their ID.",
              correct: "Students need to bring their student ID.",
              wrong: [
                "Students need bring their student ID.",
                "Students needs to bring their student ID.",
              ],
              distractorNotes: ["Missing to", "Wrong agreement"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You don't _____ to attend revision club, but it helps.",
              skillTag: "grammar",
              topicTag,
              explanation: "Don't have to — negative obligation.",
              correct: "have",
              wrong: ["has", "need"],
              distractorNotes: ["Wrong after don't", "Don't need to also OK but have fits gap"],
              difficultyRating: 3,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-obligation-apply",
          title: "Apply: Order the Rules",
          instructions: "Put words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Students / have to / bring / their ID / to the library.",
              skillTag: "grammar",
              topicTag,
              explanation: "Students have to bring their ID to the library.",
              words: ["Students", "have to", "bring", "their ID", "to the library."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-obligation-review",
          title: "Review: Have to / Need to Mix",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "I _____ more time to finish my assignment.",
              skillTag: "grammar",
              topicTag,
              explanation: "Need more time — need + noun (no to).",
              correct: "need",
              wrong: ["have", "needs"],
              distractorNotes: ["Have to + verb", "Wrong person"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "She _____ to bring her ID every day.",
              skillTag: "grammar",
              topicTag,
              explanation: "Has to bring — school rule.",
              correct: "has",
              wrong: ["have", "having"],
              distractorNotes: ["Plural", "Wrong form"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-study-review",
      title: "Lesson 3: Grammar Review — Study Time",
      learningObjective:
        "Mix present perfect for/since with have to/need to in study contexts.",
      estimatedMinutes: 23,
      exercises: [
        buildExercise({
          slug: "grammar-mixed-learn",
          title: "Learn: Choose the Correct Form",
          instructions: "Pick the best grammar for each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Linh has revised every evening since Monday because she _____ finish her assignment.",
              skillTag: "grammar",
              topicTag,
              explanation: "Has to finish — nghĩa vụ với bài tập.",
              correct: "has to",
              wrong: ["have to", "has finish"],
              distractorNotes: ["Wrong person", "Wrong form"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "I have studied here _____ two years.",
              skillTag: "grammar",
              topicTag,
              explanation: "For two years — duration.",
              correct: "for",
              wrong: ["since", "during"],
              distractorNotes: ["Since + point", "During"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-practice",
          title: "Practice: Complete the Paragraph",
          instructions: "Fill in the gaps.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Linh [0] studied English since Year 6. | She [1] to finish her assignment. | Students [2] to bring their ID.",
              skillTag: "grammar",
              topicTag,
              explanation: "has; has; need — mixed grammar review.",
              template:
                "Linh [0] studied English since Year 6. She [1] to finish her assignment. Students [2] to bring their ID.",
              correctAnswers: ["has", "has", "need"],
              acceptableAnswers: [
                ["has", "Has"],
                ["has", "Has", "needs", "Needs"],
                ["need", "Need", "have", "Have"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-check",
          title: "Check: Mixed Grammar Challenge",
          instructions: "Harder questions — choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is NOT correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Need finish thiếu to — sai ngữ pháp.",
              correct: "You need finish your homework tonight.",
              wrong: [
                "I have revised since Monday.",
                "She has to bring her student ID.",
              ],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh doesn't have to go to revision club, but she _____ extra help.",
              skillTag: "grammar",
              topicTag,
              explanation: "Needs — need + noun (extra help).",
              correct: "needs",
              wrong: ["need", "has to"],
              distractorNotes: ["Wrong person", "Has to + verb, not noun"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How long _____ you had the same timetable?",
              skillTag: "grammar",
              topicTag,
              explanation: "Have you had — present perfect question.",
              correct: "have",
              wrong: ["has", "do"],
              distractorNotes: ["Wrong person", "Wrong auxiliary"],
              difficultyRating: 3,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-apply",
          title: "Apply: Build Study Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: I / don't have to / go / to revision club.",
              skillTag: "grammar",
              topicTag,
              explanation: "I don't have to go to revision club.",
              words: ["I", "don't have to", "go", "to revision club."],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: She / has revised / every evening / since / Monday.",
              skillTag: "grammar",
              topicTag,
              explanation: "She has revised every evening since Monday.",
              words: ["She", "has revised", "every evening", "since", "Monday."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-review",
          title: "Review: Full Grammar Mix",
          instructions: "Final grammar review.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "We have had the same timetable _____ one semester.",
              skillTag: "grammar",
              topicTag,
              explanation: "For one semester.",
              correct: "for",
              wrong: ["since", "during"],
              distractorNotes: ["Since + point", "During"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You _____ to email your work or bring a printed copy.",
              skillTag: "grammar",
              topicTag,
              explanation: "Need to — from Ms Tran's announcement.",
              correct: "need",
              wrong: ["needs", "having"],
              distractorNotes: ["Wrong person", "Wrong form"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
