/** KET U1 — listening lessons (3 × 5 exercises). Announcements: library notice + assignment deadline. */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptLibraryNotice,
  listeningScriptAssignmentDeadline,
  listeningAnswerKeys,
  topicTag,
}) {
  const libraryNotice = listeningScriptLibraryNotice;
  const assignmentDeadline = listeningScriptAssignmentDeadline;
  const keysLibrary = listeningAnswerKeys.libraryNotice;
  const keysAssignment = listeningAnswerKeys.assignmentDeadline;

  return [
    {
      slug: "listening-library-notice",
      title: "Lesson 1: Library Revision Announcement",
      learningObjective:
        "Listen to a school announcement about library revision week and extract specific information.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-library-learn",
          title: "Learn: Extra Library Hours",
          instructions: "Listen to the announcement. Answer the questions.",
          sortOrder: 0,
          script: libraryNotice,
          answerKey: keysLibrary,
          questions: [
            buildMcq({
              questionText: "What is the main topic of the announcement?",
              skillTag: "listening",
              topicTag,
              explanation: "Library open for extra study hours during revision week.",
              correct: "Extra library hours during revision week",
              wrong: ["A timetable change for English", "Graduation day plans"],
              distractorNotes: ["Script assignment khác", "Không nhắc"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When is the library open on Thursday?",
              skillTag: "listening",
              topicTag,
              explanation: "Monday–Thursday: 3:30 p.m. – 6:00 p.m.",
              correct: "3:30 p.m. – 6:00 p.m.",
              wrong: ["All day", "It is closed"],
              distractorNotes: ["Chỉ buổi chiều", "Friday đóng cửa"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-library-practice",
          title: "Practice: Rules and Deadlines",
          instructions: "Listen again. Focus on rules and dates.",
          sortOrder: 1,
          script: libraryNotice,
          answerKey: keysLibrary,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "What must students bring every day?",
              skillTag: "listening",
              topicTag,
              explanation: "Bring your student ID every day.",
              correct: "Their student ID",
              wrong: ["A mobile phone", "Their assignment"],
              distractorNotes: ["Phones must be silent", "Assignment không bắt buộc mang"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When must all books be returned?",
              skillTag: "listening",
              topicTag,
              explanation: "Before the deadline: Friday 7 March.",
              correct: "Before Friday 7 March",
              wrong: ["On 14 March", "Next Friday at three o'clock"],
              distractorNotes: ["Cuối revision week", "Deadline bài tập khác"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-library-check",
          title: "Check: Library Announcement Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: libraryNotice,
          answerKey: keysLibrary,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Why is the library closed on Friday?",
              skillTag: "listening",
              topicTag,
              explanation: "Friday: CLOSED (staff meeting).",
              correct: "Staff meeting",
              wrong: ["Exam results day", "Students graduate"],
              distractorNotes: ["Không nhắc", "Không nhắc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who can help students find resources for an assignment?",
              skillTag: "listening",
              topicTag,
              explanation: "Speak to Ms Tran at the information desk.",
              correct: "Ms Tran",
              wrong: ["Mr Davies", "Linh's form teacher"],
              distractorNotes: ["Timetable announcement", "Không trong audio này"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Students can use the library for homework, exam preparation and _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Quiet revision after school — ba mục đích trong thông báo.",
              correct: "quiet revision",
              wrong: ["graduation ceremony", "salary advice"],
              distractorNotes: ["Không liên quan", "Unit Work and Jobs"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-library-apply",
          title: "Apply: Match Library Facts",
          instructions: "Listen again. Match each detail to the correct fact.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: libraryNotice },
          questions: [
            buildMatching({
              questionText: "Match each item from the library announcement.",
              skillTag: "listening",
              topicTag,
              explanation: "Friday closed; books 7 March; Ms Tran help; campus website details.",
              pairs: [
                { left: "Friday", right: "library closed (staff meeting)" },
                { left: "Books", right: "return before 7 March" },
                { left: "Assignment help", right: "ask Ms Tran at the desk" },
                { left: "Full details", right: "campus website or notice board" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-library-review",
          title: "Review: Library Announcement Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: libraryNotice,
          answerKey: keysLibrary,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Revision week runs from 10 to _____ March.",
              skillTag: "listening",
              topicTag,
              explanation: "10–14 March — ngày trong thông báo.",
              correct: "14",
              wrong: ["7", "30"],
              distractorNotes: ["Deadline trả sách", "Không nhắc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mobile phones in the library must be _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Mobile phones must be silent in the library.",
              correct: "silent",
              wrong: ["loud", "off campus"],
              distractorNotes: ["Ngược nghĩa", "Không nói mang ra ngoài"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-assignment-deadline",
      title: "Lesson 2: Assignment Deadline Reminder",
      learningObjective:
        "Listen for the main idea and key details in a classroom announcement about an assignment deadline.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-deadline-learn",
          title: "Learn: Ms Tran's Reminder",
          instructions: "Listen to Ms Tran. Answer the questions.",
          sortOrder: 0,
          script: assignmentDeadline,
          answerKey: keysAssignment,
          questions: [
            buildMcq({
              questionText: "What is the announcement mainly about?",
              skillTag: "listening",
              topicTag,
              explanation: "Reminder about the history assignment deadline.",
              correct: "An assignment deadline",
              wrong: ["A timetable change", "A library staff meeting"],
              distractorNotes: ["Script library khác", "Staff meeting là thư viện"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which subject is the assignment for?",
              skillTag: "listening",
              topicTag,
              explanation: "Your history assignment — bài tập lịch sử.",
              correct: "History",
              wrong: ["English", "Science"],
              distractorNotes: ["Ms Tran dạy English nhưng bài là history", "Science trong timetable khác"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-deadline-practice",
          title: "Practice: Deadline and Help",
          instructions: "Listen again. Focus on dates and places.",
          sortOrder: 1,
          script: assignmentDeadline,
          answerKey: keysAssignment,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "When is the deadline?",
              skillTag: "listening",
              topicTag,
              explanation: "Next Friday at three o'clock.",
              correct: "Next Friday at three o'clock",
              wrong: ["This Wednesday in the library", "7 March"],
              distractorNotes: ["Wednesday là revision club", "7 March là trả sách"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Where can students get extra help?",
              skillTag: "listening",
              topicTag,
              explanation: "Revision club in the library on Wednesday.",
              correct: "Revision club in the library on Wednesday",
              wrong: ["At the lecture hall on Friday", "On the campus website only"],
              distractorNotes: ["Friday là deadline", "Website không nhắc ở đây"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-deadline-check",
          title: "Check: Assignment Announcement Details",
          instructions: "Listen to the full announcement again.",
          sortOrder: 2,
          script: assignmentDeadline,
          answerKey: keysAssignment,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What must students write about?",
              skillTag: "listening",
              topicTag,
              explanation: "Life on campus one hundred years ago.",
              correct: "Life on campus one hundred years ago",
              wrong: ["Their favourite subject", "A part-time job interview"],
              distractorNotes: ["Không phải chủ đề", "Unit Work and Jobs"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How can students submit their work?",
              skillTag: "listening",
              topicTag,
              explanation: "Email your work or bring a printed copy.",
              correct: "Email or bring a printed copy",
              wrong: ["Only on the notice board", "Only by phone call"],
              distractorNotes: ["Notice board không nộp bài", "Không nhắc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What happens to late work?",
              skillTag: "listening",
              topicTag,
              explanation: "Late work will lose marks.",
              correct: "It will lose marks",
              wrong: ["It will be accepted with a gift", "It can be submitted next semester"],
              distractorNotes: ["Không nhắc", "Không nhắc"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-deadline-apply",
          title: "Apply: Order the Announcement",
          instructions: "Put the ideas in the order they are mentioned.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          content: { script: assignmentDeadline },
          questions: [
            buildMcq({
              questionText:
                "Correct order: (1) revision club help (2) assignment topic (3) deadline time",
              skillTag: "listening",
              topicTag,
              explanation: "Topic → deadline → help with revision club.",
              correct: "2 → 3 → 1",
              wrong: ["1 → 2 → 3", "3 → 1 → 2"],
              distractorNotes: ["Help sau deadline", "Deadline không đầu tiên"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-deadline-review",
          title: "Review: Deadline Announcement Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: assignmentDeadline,
          answerKey: keysAssignment,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Who gives the announcement?",
              skillTag: "listening",
              topicTag,
              explanation: "Ms Tran, English teacher — nhắc bài history.",
              correct: "Ms Tran",
              wrong: ["Mr Davies", "Linh"],
              distractorNotes: ["Timetable announcement", "Linh là học sinh"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Students need to _____ before they leave the lesson.",
              skillTag: "listening",
              topicTag,
              explanation: "Remember the deadline — don't forget the deadline.",
              correct: "remember the deadline",
              wrong: ["graduate this semester", "return all library books today"],
              distractorNotes: ["Không nhắc", "Library deadline khác"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-study-review",
      title: "Lesson 3: Review Both Announcements",
      learningObjective:
        "Understand the main idea across two school announcements about study and deadlines.",
      estimatedMinutes: 22,
      exercises: [
        buildListeningExercise({
          slug: "listening-review-learn",
          title: "Learn: Library Announcement Reminder",
          instructions: "Listen to the library revision announcement again.",
          sortOrder: 0,
          script: libraryNotice,
          answerKey: keysLibrary,
          questions: [
            buildMcq({
              questionText: "Where does the library announcement take place?",
              skillTag: "listening",
              topicTag,
              explanation: "School library revision week — thông báo PA hoặc hội trường.",
              correct: "At the school library during revision week",
              wrong: ["In Ms Tran's classroom", "At a university lecture"],
              distractorNotes: ["Classroom là deadline script", "University là tương lai Linh"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Students can use the library for exam preparation and _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Homework, exam preparation and quiet revision.",
              correct: "homework",
              wrong: ["salary negotiation", "retirement planning"],
              distractorNotes: ["Unit Work and Jobs", "Không liên quan"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-practice",
          title: "Practice: Deadline Announcement Reminder",
          instructions: "Listen to the assignment deadline announcement again.",
          sortOrder: 1,
          script: assignmentDeadline,
          answerKey: keysAssignment,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "The assignment is about life on campus _____ years ago.",
              skillTag: "listening",
              topicTag,
              explanation: "One hundred years ago — chủ đề bài tập.",
              correct: "one hundred",
              wrong: ["two", "four"],
              distractorNotes: ["Không nói hai", "Four là graduate Linh"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Late work will _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Late work will lose marks.",
              correct: "lose marks",
              wrong: ["get a free book", "change the timetable"],
              distractorNotes: ["Library benefit khác", "Timetable script khác"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-check",
          title: "Check: Mixed Announcement Listening",
          instructions: "Listen to the assignment announcement. Harder questions.",
          sortOrder: 2,
          script: assignmentDeadline,
          answerKey: keysAssignment,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which detail is ONLY in the library announcement?",
              skillTag: "listening",
              topicTag,
              explanation: "Friday closed for staff meeting — chỉ thư viện.",
              correct: "Friday library closed (staff meeting)",
              wrong: ["History assignment topic", "Email or print your work"],
              distractorNotes: ["Deadline script", "Deadline script"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Both announcements mention _____ in some way.",
              skillTag: "listening",
              topicTag,
              explanation: "Revision — revision week và revision club.",
              correct: "revision",
              wrong: ["graduation", "salary"],
              distractorNotes: ["Không nhắc", "Không liên quan"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-review-apply",
          title: "Apply: Match Announcement to Fact",
          instructions: "Match each fact to the correct announcement.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: assignmentDeadline },
          questions: [
            buildMatching({
              questionText: "Match facts to Library notice or Assignment deadline announcement.",
              skillTag: "listening",
              topicTag,
              explanation: "Library: hours, student ID; Assignment: Friday 3pm, history topic.",
              pairs: [
                { left: "Bring student ID every day", right: "Library notice announcement" },
                { left: "Deadline next Friday at 3 p.m.", right: "Assignment deadline announcement" },
                { left: "Books return before 7 March", right: "Library notice announcement" },
                { left: "Write about campus 100 years ago", right: "Assignment deadline announcement" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-study-review-final",
          title: "Review: Both Announcements Mix",
          instructions: "Listen to the library announcement. Final review.",
          sortOrder: 4,
          script: libraryNotice,
          answerKey: keysLibrary,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which time is from the LIBRARY announcement only?",
              skillTag: "listening",
              topicTag,
              explanation: "3:30 p.m. – 6:00 p.m. weekday hours — chỉ thư viện.",
              correct: "3:30 p.m. – 6:00 p.m. (weekday library hours)",
              wrong: ["Next Friday at three o'clock", "Before 7 March book return"],
              distractorNotes: ["Assignment deadline", "Cũng library nhưng là ngày không giờ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Ms Tran is mentioned in _____ announcement(s).",
              skillTag: "listening",
              topicTag,
              explanation: "Library desk help và assignment reminder — cả hai.",
              correct: "both",
              wrong: ["the library notice only", "the assignment deadline only"],
              distractorNotes: ["Cũng nhắc ở deadline", "Cũng nhắc ở library"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
