/** KET U1 — reading lessons (3 × 5 exercises). Signs/notices + Linh school life passage. */

export function readingLessons({
  buildMcq,
  buildGapFill,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageLinhSchoolLife,
  topicTag,
}) {
  const passage = passageLinhSchoolLife;

  return [
    {
      slug: "reading-detail-school-life",
      title: "Lesson 1: Find School Life Details",
      learningObjective:
        "Find specific facts about Linh's study routine, subjects and obligations in a short text.",
      estimatedMinutes: 22,
      exercises: [
        buildReadingExercise({
          slug: "reading-school-learn",
          title: "Learn: Linh at West Hill",
          instructions: "Read the passage. Answer the detail questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "How old is Linh?",
              skillTag: "reading",
              topicTag,
              explanation: "Linh is thirteen — đoạn mở đầu bài đọc.",
              correct: "Thirteen",
              wrong: ["Eleven", "Fifteen"],
              distractorNotes: ["Tuổi Movers/Flyers", "Không có trong bài"],
              assessmentType: "detail",
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Where does Linh study?",
              skillTag: "reading",
              topicTag,
              explanation: "West Hill Secondary School on the main campus.",
              correct: "West Hill Secondary School",
              wrong: ["A university campus", "GreenMart supermarket"],
              distractorNotes: ["Chỉ nhắc lecture trong tương lai", "Unit khác"],
              assessmentType: "detail",
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-school-practice",
          title: "Practice: Assignment and Revision",
          instructions: "Read again. Find details about Linh's work this month.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "What assignment does Linh have to finish?",
              skillTag: "reading",
              topicTag,
              explanation: "History assignment about campus life one hundred years ago.",
              correct: "A history assignment about campus life",
              wrong: ["An English exam in May", "A maths timetable change"],
              distractorNotes: ["Exam nhắc ở chỗ khác", "Timetable trong listening"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How long has Linh revised every evening?",
              skillTag: "reading",
              topicTag,
              explanation: "She has revised every evening since Monday — present perfect + since.",
              correct: "Since Monday",
              wrong: ["For Monday", "Since last semester"],
              distractorNotes: ["For + khoảng thời gian", "Semester là thời gian khác"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-school-check",
          title: "Check: School Life Detail Search",
          instructions: "Read carefully. These questions need thinking.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "What must students bring to use the library after school?",
              skillTag: "reading",
              topicTag,
              explanation: "Students need to bring their student ID — quy định bắt buộc.",
              correct: "Their student ID",
              wrong: ["A printed assignment", "Their timetable only"],
              distractorNotes: ["Nộp bài là việc khác", "Timetable không thay ID"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is NOT true about Linh?",
              skillTag: "reading",
              topicTag,
              explanation: "Linh doesn't have to go to revision club — không bắt buộc.",
              correct: "Linh has to attend revision club every Wednesday.",
              wrong: [
                "Linh has studied English since Year 6.",
                "The deadline for her assignment is next Friday.",
              ],
              distractorNotes: ["Đúng trong bài", "Đúng trong bài"],
              assessmentType: "inference",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh's favourite subject is English, but she needs to work harder at _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Needs to work harder at maths — câu đối chiếu trong bài.",
              correct: "maths",
              wrong: ["history", "science"],
              distractorNotes: ["Môn bài tập hiện tại", "Không nhắc tới"],
              assessmentType: "vocabulary_in_context",
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-school-apply",
          title: "Apply: Match School Facts",
          instructions: "Use the passage. Match each detail to the correct fact.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each topic to the correct detail from the text.",
              skillTag: "reading",
              topicTag,
              explanation: "English since Year 6; deadline Friday; Ms Tran help; graduate four years.",
              pairs: [
                { left: "English", right: "studied since Year 6" },
                { left: "Assignment deadline", right: "next Friday" },
                { left: "Extra help", right: "Ms Tran at revision club" },
                { left: "Graduate", right: "in four years" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-school-review",
          title: "Review: School Life Detail Mix",
          instructions: "Read the passage one more time. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "How long has Linh had the same timetable?",
              skillTag: "reading",
              topicTag,
              explanation: "Has had the same timetable for one semester — present perfect + for.",
              correct: "For one semester",
              wrong: ["Since one semester", "For Monday"],
              distractorNotes: ["Since + mốc thời gian", "Monday là revision"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What does Linh hope to do one day?",
              skillTag: "reading",
              topicTag,
              explanation: "Visit a university lecture one day — ước mơ tương lai.",
              correct: "Visit a university lecture",
              wrong: ["Retire from school", "Change her semester today"],
              distractorNotes: ["Không liên quan", "Không trong bài"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-gist-notices",
      title: "Lesson 2: Skim Signs and Notices",
      learningObjective:
        "Skim a school notice embedded in the text to identify the main message and key rules.",
      estimatedMinutes: 22,
      exercises: [
        buildReadingExercise({
          slug: "reading-notice-learn",
          title: "Learn: Library Notice Gist",
          instructions: "Read the passage. Focus on the LIBRARY NOTICE section.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "When is the library open on Thursday during revision week?",
              skillTag: "reading",
              topicTag,
              explanation: "Monday–Thursday: 3:30–6:00 p.m. — giờ mở cửa trong thông báo.",
              correct: "3:30 p.m. – 6:00 p.m.",
              wrong: ["All morning", "It is closed"],
              distractorNotes: ["Chỉ buổi chiều", "Friday mới đóng"],
              assessmentType: "detail",
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Why is the library closed on Friday?",
              skillTag: "reading",
              topicTag,
              explanation: "Friday: CLOSED — staff meeting trong notice.",
              correct: "Staff meeting",
              wrong: ["Exam results day", "Semester ends"],
              distractorNotes: ["Không nhắc", "Không nhắc"],
              assessmentType: "detail",
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-notice-practice",
          title: "Practice: Notice Vocabulary",
          instructions: "Read the notice again. Choose the correct meaning.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "In the notice, 'revision week' means a time when students _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Revision week = tuần ôn tập trước kỳ thi.",
              correct: "study again before exams",
              wrong: ["graduate from school", "change their timetable permanently"],
              distractorNotes: ["Graduate là mục tiêu Linh", "Timetable tạm thời"],
              assessmentType: "vocabulary_in_context",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When must all books be returned?",
              skillTag: "reading",
              topicTag,
              explanation: "All books must be returned before 7 March — deadline trong notice.",
              correct: "Before 7 March",
              wrong: ["On 14 March", "Next Friday only"],
              distractorNotes: ["Cuối revision week", "Deadline bài tập Linh"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-notice-check",
          title: "Check: Main Idea of the Notice",
          instructions: "Skim the notice. Answer about main idea and structure.",
          sortOrder: 2,
          passage,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "What is the main purpose of the library notice?",
              skillTag: "reading",
              topicTag,
              explanation: "Thông báo giờ mở cửa thư viện trong revision week.",
              correct: "To tell students about extra library hours during revision week",
              wrong: ["To announce exam results", "To invite students to a lecture"],
              distractorNotes: ["Không nhắc", "Lecture hall chỉ là vị trí dán notice"],
              assessmentType: "main_idea",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Put the notice sections in order: (1) Opening hours (2) Revision week dates (3) Book return rule",
              skillTag: "reading",
              topicTag,
              explanation: "Dates → hours → rules — thứ tự trong notice.",
              correct: "2 → 1 → 3",
              wrong: ["1 → 2 → 3", "3 → 1 → 2"],
              distractorNotes: ["Dates trước hours", "Rules ở cuối"],
              assessmentType: "sequencing",
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-notice-apply",
          title: "Apply: Complete from the Notice",
          instructions: "Fill in the gaps using words from the notice.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: Revision week is [0]–14 March. The library is open Monday–Thursday, [1]–6:00 p.m. All books must be returned before [2] March.",
              skillTag: "reading",
              topicTag,
              explanation: "10; 3:30; 7 — chi tiết từ thông báo thư viện.",
              template:
                "Revision week is [0]–14 March. The library is open Monday–Thursday, [1]–6:00 p.m. All books must be returned before [2] March.",
              correctAnswers: ["10", "3:30", "7"],
              acceptableAnswers: [
                ["10", "10th"],
                ["3:30", "3.30", "3:30 p.m."],
                ["7", "7th"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-notice-review",
          title: "Review: Notice Skim Mix",
          instructions: "Skim the notice one more time. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Where is the notice posted?",
              skillTag: "reading",
              topicTag,
              explanation: "Posted outside the lecture hall — vị trí trong bài.",
              correct: "Outside the lecture hall",
              wrong: ["On the campus website only", "In Linh's history classroom"],
              distractorNotes: ["Website là nguồn khác", "Không nói lớp history"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which day can students NOT use the library during revision week?",
              skillTag: "reading",
              topicTag,
              explanation: "Friday: CLOSED — thứ Sáu đóng cửa.",
              correct: "Friday",
              wrong: ["Thursday", "Monday"],
              distractorNotes: ["Thursday mở cửa", "Monday mở cửa"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-mixed-study",
      title: "Lesson 3: Reading Review — Details and Gist",
      learningObjective:
        "Combine detail search and gist skimming across Linh's school life text and the library notice.",
      estimatedMinutes: 23,
      exercises: [
        buildReadingExercise({
          slug: "reading-mixed-learn",
          title: "Learn: Obligations in the Text",
          instructions: "Read the full passage. Answer about have to and need to.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "Linh _____ finish her history assignment this month.",
              skillTag: "reading",
              topicTag,
              explanation: "Has to finish — nghĩa vụ bắt buộc với bài tập.",
              correct: "has to",
              wrong: ["needs", "hopes to"],
              distractorNotes: ["Need to + động từ khác", "Hy vọng, không bắt buộc"],
              assessmentType: "grammar_in_context",
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Students _____ bring their student ID to the library.",
              skillTag: "reading",
              topicTag,
              explanation: "Need to bring — quy định thư viện.",
              correct: "need to",
              wrong: ["have to graduate", "want to"],
              distractorNotes: ["Graduate không liên quan", "Want to yếu hơn need to"],
              assessmentType: "grammar_in_context",
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-mixed-practice",
          title: "Practice: For and Since",
          instructions: "Read again. Find present perfect time expressions.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Linh has studied English _____ Year 6.",
              skillTag: "reading",
              topicTag,
              explanation: "Since Year 6 — mốc thời gian bắt đầu.",
              correct: "since",
              wrong: ["for", "from"],
              distractorNotes: ["For + khoảng thời gian", "From ít dùng với present perfect"],
              assessmentType: "grammar_in_context",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "She has had the same timetable _____ one semester.",
              skillTag: "reading",
              topicTag,
              explanation: "For one semester — khoảng thời gian.",
              correct: "for",
              wrong: ["since", "during"],
              distractorNotes: ["Since + mốc", "During không đi với have had"],
              assessmentType: "grammar_in_context",
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-mixed-check",
          title: "Check: Detail vs Main Idea",
          instructions: "Decide whether each question needs detail or gist.",
          sortOrder: 2,
          passage,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which question needs you to skim for gist, not search for one word?",
              skillTag: "reading",
              topicTag,
              explanation: "Main purpose of the library notice — cần hiểu toàn bộ thông điệp.",
              correct: "What is the main purpose of the library notice?",
              wrong: ["When is the deadline for Linh's assignment?", "How old is Linh?"],
              distractorNotes: ["Chi tiết cụ thể", "Chi tiết cụ thể"],
              assessmentType: "strategy",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which detail appears in BOTH Linh's story and the library notice?",
              skillTag: "reading",
              topicTag,
              explanation: "Revision week / revision — xuất hiện ở cả hai phần.",
              correct: "Revision",
              wrong: ["Graduation", "A science lecture"],
              distractorNotes: ["Chỉ trong kế hoạch Linh", "Không nhắc"],
              assessmentType: "inference",
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-mixed-apply",
          title: "Apply: Match Text Section to Skill",
          instructions: "Match each reading task to the best strategy.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each question type to the best reading strategy.",
              skillTag: "reading",
              topicTag,
              explanation: "Gist = skim notice; detail = find deadline; grammar = for/since; order = notice structure.",
              pairs: [
                { left: "Main purpose of the notice", right: "Skim for gist" },
                { left: "Linh's assignment deadline", right: "Find a specific detail" },
                { left: "Since Monday / for one semester", right: "Check grammar in context" },
                { left: "Order of notice sections", right: "Skim structure quickly" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-mixed-review",
          title: "Review: School Reading Mix",
          instructions: "Read and answer — mixed detail and gist review.",
          sortOrder: 4,
          passage,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Linh has revised every evening since Monday because _____.",
              skillTag: "reading",
              topicTag,
              explanation: "The deadline is next Friday — lý do ôn tập.",
              correct: "the deadline is next Friday",
              wrong: ["the library is closed on Friday", "she has to graduate this year"],
              distractorNotes: ["Lý do đóng thư viện", "Graduate sau bốn năm"],
              assessmentType: "inference",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The whole passage is mainly about _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Linh's school life + revision week notice — chủ đề education and study.",
              correct: "a student's study life and a school library notice",
              wrong: ["how to apply for a part-time job", "a family visit to Da Nang"],
              distractorNotes: ["Unit Work and Jobs", "Unit Family Flyers"],
              assessmentType: "main_idea",
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
