/** KET U1 — speaking lessons (3 × 5 exercises; only Check is AI). */

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [studyHabitsCheck, assignmentCheck, schoolLifeCheck] = speakingChecks;

  return [
    {
      slug: "speaking-study-habits",
      title: "Lesson 1: Talk About Study Habits",
      learningObjective:
        "Choose appropriate spoken phrases about subjects, timetable and revision.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-study-learn",
          title: "Learn: What to Say About Studying",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Examiner: What is your favourite subject? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Favourite subject + tên môn — cấu trúc phỏng vấn A2.",
              correct: "My favourite subject is English.",
              wrong: ["My favourite deadline is Friday.", "My favourite campus is big."],
              distractorNotes: ["Deadline không phải subject", "Collocation sai"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Examiner: Where do you usually do your homework? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I usually do my homework in the library — địa điểm trên campus.",
              correct: "I usually do my homework in the library.",
              wrong: ["I usually do my homework on the deadline.", "I usually graduate in the library."],
              distractorNotes: ["Deadline là thời gian", "Sai động từ"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-study-practice",
          title: "Practice: For and Since Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "How long have you studied at this school? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "I have studied here for two years — present perfect + for.",
              correct: "I have studied here for two years.",
              wrong: ["I have studied here since two years.", "I study here for two years."],
              distractorNotes: ["Since + mốc", "Present simple với for"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How long have you studied English? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "I have studied English since Year 6 — since + mốc.",
              correct: "I have studied English since Year 6.",
              wrong: ["I have studied English for Year 6.", "I study English since Year 6."],
              distractorNotes: ["For + duration", "Wrong tense"],
              difficultyRating: 2,
            }),
          ],
        }),
        studyHabitsCheck,
        buildExercise({
          slug: "speaking-study-apply",
          title: "Apply: Quick Study Replies",
          instructions: "Choose the best short spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Examiner: Do you use the school library? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes + when/why — trả lời đầy đủ kinh nghiệm.",
              correct: "Yes, I go there after school to revise for exams.",
              wrong: ["Yes library I go.", "Yes, I library revision week."],
              distractorNotes: ["Fragment", "Not a sentence"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-study-review",
          title: "Review: Study Habits Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Examiner: When do you check your timetable? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I check it every Sunday evening — thói quen rõ ràng.",
              correct: "I check my timetable every Sunday evening.",
              wrong: ["I check timetable Sunday.", "I am check timetable every Sunday."],
              distractorNotes: ["Fragment", "Wrong form"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: Do you do revision before exams? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, I revise every evening during revision week.",
              correct: "Yes, I revise every evening during revision week.",
              wrong: ["Yes revision I every evening.", "Yes, I revising every evening."],
              distractorNotes: ["Wrong order", "Wrong tense"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-assignment-deadline",
      title: "Lesson 2: Talk About Assignments",
      learningObjective:
        "Use assignment, deadline and need to/have to in short spoken answers.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-assignment-learn",
          title: "Learn: Assignment Speaking Phrases",
          instructions: "Choose the best thing to say about homework.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Examiner: Tell me about your history assignment. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Topic + deadline — mô tả cụ thể như Linh.",
              correct: "I have to write about campus life one hundred years ago. The deadline is next Friday.",
              wrong: ["History assignment campus graduate.", "I have write campus assignment Friday deadline."],
              distractorNotes: ["Fragment", "Wrong grammar"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Examiner: Do you need help with your work? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, I need help from my teacher / revision club.",
              correct: "Yes, I need help. I can go to revision club on Wednesday.",
              wrong: ["Yes need help I teacher.", "Yes, I needing help Wednesday."],
              distractorNotes: ["Wrong order", "Wrong form"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-assignment-practice",
          title: "Practice: Obligations at School",
          instructions: "Choose the correct spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "What do you have to bring to the library? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "I have to bring my student ID — quy định trường.",
              correct: "I have to bring my student ID.",
              wrong: ["I have bring student ID must.", "I bringing student ID have to."],
              distractorNotes: ["Wrong form", "Wrong order"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Must you go to revision club? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "No, I don't have to, but I want extra help.",
              correct: "No, I don't have to, but I want to go for extra help.",
              wrong: ["No, I not have to go revision.", "No have to revision club I."],
              distractorNotes: ["Missing auxiliary", "Fragment"],
              difficultyRating: 2,
            }),
          ],
        }),
        assignmentCheck,
        buildExercise({
          slug: "speaking-assignment-apply",
          title: "Apply: Choose the Best Assignment Reply",
          instructions: "Pick the most natural spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Examiner: How do you submit your assignment? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Email or printed copy — như thông báo Ms Tran.",
              correct: "I can email it to my teacher or bring a printed copy.",
              wrong: ["Email print assignment teacher copy.", "I submit assignment email print only must."],
              distractorNotes: ["Not coherent", "Awkward grammar"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-assignment-review",
          title: "Review: Assignment Speaking Quiz",
          instructions: "Choose the best answer using assignment vocabulary.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Examiner: What happens if you miss the deadline? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Late work will lose marks — từ thông báo.",
              correct: "Late work will lose marks.",
              wrong: ["Late work lose marks will I.", "Late assignment no marks have."],
              distractorNotes: ["Wrong order", "Fragment"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: How long have you worked on this assignment? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I have worked on it since Monday — present perfect + since.",
              correct: "I have worked on it since Monday.",
              wrong: ["I have worked on it for Monday.", "I work on it since Monday."],
              distractorNotes: ["For + duration", "Wrong tense"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-school-life",
      title: "Lesson 3: Describe School Life",
      learningObjective:
        "Describe campus, semester and future study plans in extended spoken answers.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "speaking-school-learn",
          title: "Learn: School Life Phrases",
          instructions: "Choose the best thing to say about your school.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Examiner: Tell me about your school campus. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Campus + facility — câu hoàn chỉnh A2.",
              correct: "My school is on the main campus. There is a library and a lecture hall.",
              wrong: ["Campus main school library.", "My campus which big school."],
              distractorNotes: ["Too short", "Ungrammatical"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Examiner: What year are you in? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I am in Year 8 — Linh is thirteen, secondary student.",
              correct: "I am in Year 8 at secondary school.",
              wrong: ["I am Year 8 in.", "Year eight I am school."],
              distractorNotes: ["Missing preposition", "Wrong order"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-school-practice",
          title: "Practice: Future Study Plans",
          instructions: "Choose the best spoken answers.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Examiner: When do you want to graduate? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I hope to graduate in four years — kế hoạch tương lai.",
              correct: "I hope to graduate in four years.",
              wrong: ["I hope graduate four years in.", "Graduate I hope four years."],
              distractorNotes: ["Missing to", "Wrong order"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: Have you ever been to a university lecture? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "No, not yet, but I want to visit one day.",
              correct: "No, not yet, but I want to visit one day.",
              wrong: ["No never lecture university I.", "No, I never visit lecture university yet."],
              distractorNotes: ["Fragment", "Awkward order"],
              difficultyRating: 2,
            }),
          ],
        }),
        schoolLifeCheck,
        buildExercise({
          slug: "speaking-school-apply",
          title: "Apply: Tell About Your School",
          instructions: "Choose the best school life description.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best short description of your study life:",
              skillTag: "speaking",
              topicTag,
              explanation: "Connected ideas: school + subject + assignment + revision.",
              correct:
                "I study at West Hill Secondary. My favourite subject is English, but I need to work harder at maths. I have revised every evening since Monday because of my history assignment.",
              wrong: [
                "School subject assignment revision deadline.",
                "I have study since for assignment need graduate.",
              ],
              distractorNotes: ["Not sentences", "Ungrammatical"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-school-review",
          title: "Review: School Life Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Examiner: How long have you had the same timetable? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "For one semester — present perfect + for.",
              correct: "I have had the same timetable for one semester.",
              wrong: ["I have had timetable since one semester.", "I had timetable for semester one."],
              distractorNotes: ["Since + point", "Past simple"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Compare: I have to… / I don't have to… Best pair:",
              skillTag: "speaking",
              topicTag,
              explanation: "Have to finish assignment; don't have to go to revision club — như Linh.",
              correct:
                "I have to finish my assignment this month. I don't have to go to revision club, but I want extra help.",
              wrong: [
                "I have to don't have to assignment revision.",
                "Don't have to I have finish assignment club.",
              ],
              distractorNotes: ["Meaningless", "Wrong order"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
