/** KET U1 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-education-words",
      title: "Lesson 1: Education and Study Words",
      learningObjective:
        "Recognise and use subject, timetable, assignment, deadline and revision in sentences.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "vocab-education-learn",
          title: "Learn: Education Word Match",
          instructions: "Read each clue. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "A chart showing when each class happens is called a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Timetable (thời khóa biểu) cho biết giờ học từng môn.",
              correct: "timetable",
              wrong: ["deadline", "semester"],
              distractorNotes: ["Hạn nộp bài", "Học kỳ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The last day you can hand in your work is the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Deadline (hạn chót) là ngày/giờ cuối cùng phải nộp bài.",
              correct: "deadline",
              wrong: ["campus", "lecture"],
              distractorNotes: ["Khuôn viên trường", "Bài giảng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Work your teacher asks you to do and submit is an _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Assignment (bài nộp) là bài tập giáo viên giao.",
              correct: "assignment",
              wrong: ["revision", "graduate"],
              distractorNotes: ["Ôn tập", "Tốt nghiệp"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Studying again before a test is called _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Revision (ôn tập) là học lại trước kỳ thi.",
              correct: "revision",
              wrong: ["homework", "subject"],
              distractorNotes: ["Bài về nhà hàng ngày", "Môn học"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-education-practice",
          title: "Practice: Match Education Words",
          instructions: "Match each word to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the education words to their meanings.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mỗi từ khớp với một nghĩa rõ ràng.",
              pairs: [
                { left: "subject", right: "a school topic such as Maths or English" },
                { left: "exam", right: "a formal test of your knowledge" },
                { left: "library", right: "a quiet place to study and borrow books" },
                { left: "semester", right: "half of the school year" },
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-education-check",
          title: "Check: Vocab Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Maths, English and Science are school _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Subjects (môn học) — các lĩnh vực học.",
              correct: "subjects",
              wrong: ["libraries", "campuses"],
              distractorNotes: ["Nơi học", "Khu trường"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When you finish school successfully, you _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Graduate (tốt nghiệp) — hoàn thành chương trình.",
              correct: "graduate",
              wrong: ["revise", "assign"],
              distractorNotes: ["Ôn tập", "Không đúng dạng động từ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh checks the _____ to see when her next class is.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Timetable — thời khóa biểu cho biết giờ học.",
              correct: "timetable",
              wrong: ["deadline", "lecture"],
              distractorNotes: ["Hạn nộp bài", "Một buổi giảng"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-education-apply",
          title: "Apply: Complete the School Sentences",
          instructions: "Fill in each gap with the correct word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: My favourite [0] is English. | The [1] for the history assignment is next Friday. | I do [2] in the library before exams.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "subject; deadline; revision — ba từ cốt lõi unit.",
              template:
                "My favourite [0] is English. The [1] for the history assignment is next Friday. I do [2] in the library before exams.",
              correctAnswers: ["subject", "deadline", "revision"],
              acceptableAnswers: [
                ["subject", "Subject"],
                ["deadline", "Deadline"],
                ["revision", "Revision"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-education-review",
          title: "Review: Education Vocabulary Mix",
          instructions: "Choose the best word from the unit.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "The school _____ includes the library and lecture hall.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Campus (khuôn viên) — toàn bộ khu trường.",
              correct: "campus",
              wrong: ["semester", "assignment"],
              distractorNotes: ["Học kỳ", "Bài tập"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh has to finish her history _____ this month.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Assignment — bài tập cần nộp.",
              correct: "assignment",
              wrong: ["graduate", "timetable"],
              distractorNotes: ["Tốt nghiệp", "Thời khóa biểu"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-campus-study",
      title: "Lesson 2: Campus and Study Places",
      learningObjective:
        "Use campus, library, lecture, exam and homework in school contexts.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "vocab-campus-learn",
          title: "Learn: Places and Work",
          instructions: "Choose the best word for each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "A formal talk given to many students is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Lecture (bài giảng) — buổi nói trước nhiều học sinh.",
              correct: "lecture",
              wrong: ["homework", "deadline"],
              distractorNotes: ["Bài về nhà", "Hạn chót"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Work you do at home after school is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Homework (bài tập về nhà) — làm ở nhà sau giờ học.",
              correct: "homework",
              wrong: ["revision", "graduate"],
              distractorNotes: ["Ôn thi", "Tốt nghiệp"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh does her homework in the school _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Library — nơi yên tĩnh để học trên campus.",
              correct: "library",
              wrong: ["semester", "subject"],
              distractorNotes: ["Học kỳ", "Môn học"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-campus-practice",
          title: "Practice: Match Campus Words",
          instructions: "Match each word to the correct meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match campus and study words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Campus = grounds; homework = work at home; exam = test.",
              pairs: [
                { left: "campus", right: "the buildings and grounds of a school" },
                { left: "homework", right: "work you do at home after lessons" },
                { left: "exam", right: "a formal test at the end of a course" },
                { left: "lecture", right: "a talk given to a large group of students" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-campus-check",
          title: "Check: Campus Vocabulary Challenge",
          instructions: "Choose the correct answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "During revision week, the _____ stays open until six p.m.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Library mở cửa thêm giờ trong tuần ôn tập.",
              correct: "library",
              wrong: ["lecture hall only", "semester"],
              distractorNotes: ["Lecture hall chỉ là vị trí notice", "Học kỳ không mở cửa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh hopes to visit a university _____ one day.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "University lecture — buổi giảng đại học.",
              correct: "lecture",
              wrong: ["homework", "deadline"],
              distractorNotes: ["Bài về nhà", "Hạn chót"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We have two _____ each school year.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Semesters (học kỳ) — chia năm học.",
              correct: "semesters",
              wrong: ["assignments", "campuses"],
              distractorNotes: ["Bài tập", "Nhiều campus không phổ biến"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-campus-apply",
          title: "Apply: Complete Campus Sentences",
          instructions: "Fill in the gaps with unit words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I do my [0] in the library on the main [1]. | We have an English [2] in May.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "homework; campus; exam — ngữ cảnh trường học.",
              template:
                "I do my [0] in the library on the main [1]. We have an English [2] in May.",
              correctAnswers: ["homework", "campus", "exam"],
              acceptableAnswers: [
                ["homework", "Homework"],
                ["campus", "Campus"],
                ["exam", "Exam"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-campus-review",
          title: "Review: Campus Word Mix",
          instructions: "Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "The notice is posted outside the _____ hall.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Lecture hall — hành lang bài giảng.",
              correct: "lecture",
              wrong: ["homework", "graduate"],
              distractorNotes: ["Không phải địa điểm", "Động từ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Don't forget your _____ before the exam.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Revision — ôn tập trước kỳ thi.",
              correct: "revision",
              wrong: ["campus", "timetable"],
              distractorNotes: ["Khu trường", "Thời khóa biểu"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-study-review",
      title: "Lesson 3: Unit Vocabulary Review",
      learningObjective:
        "Recall and use all twelve education and study words across contexts.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "vocab-review-learn",
          title: "Learn: Quick Word Check",
          instructions: "Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Linh has had the same _____ for one semester.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Timetable — thời khóa biểu không đổi.",
              correct: "timetable",
              wrong: ["graduate", "lecture"],
              distractorNotes: ["Tốt nghiệp", "Bài giảng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Students need to return library books before the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Deadline 7 March trong notice.",
              correct: "deadline",
              wrong: ["subject", "semester"],
              distractorNotes: ["Môn học", "Học kỳ"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-review-practice",
          title: "Practice: Match All Unit Words",
          instructions: "Match words to meanings — full unit review.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match each education word to its meaning.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ôn toàn bộ từ vựng unit Education and Study.",
              pairs: [
                { left: "assignment", right: "work the teacher asks you to submit" },
                { left: "graduate", right: "to finish school successfully" },
                { left: "revision", right: "studying again before a test" },
                { left: "subject", right: "an area of study like Science" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-review-check",
          title: "Check: Full Vocabulary Quiz",
          instructions: "Harder questions — no hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which word means the same as 'hand in by Friday'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Deadline = hạn nộp bài.",
              correct: "deadline",
              wrong: ["campus", "lecture"],
              distractorNotes: ["Khu trường", "Bài giảng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh wants to _____ in four years.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Graduate — tốt nghiệp trung học.",
              correct: "graduate",
              wrong: ["revise", "assign"],
              distractorNotes: ["Ôn tập", "Không đúng dạng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence uses 'subject' correctly?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Favourite subject is English — collocation chuẩn.",
              correct: "My favourite subject is English.",
              wrong: [
                "My favourite subject is on the deadline.",
                "I subject English every day.",
              ],
              distractorNotes: ["Nonsense", "Wrong word class"],
              difficultyRating: 3,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-review-apply",
          title: "Apply: Linh's School Week",
          instructions: "Complete the paragraph with unit words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Linh checks her [0] every Sunday. | She has a history [1] due next Friday. | She studies on the [2] and does [3] in the library.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "timetable; assignment; campus; revision/homework — ngữ cảnh Linh.",
              template:
                "Linh checks her [0] every Sunday. She has a history [1] due next Friday. She studies on the [2] and does [3] in the library.",
              correctAnswers: ["timetable", "assignment", "campus", "revision"],
              acceptableAnswers: [
                ["timetable", "Timetable"],
                ["assignment", "Assignment"],
                ["campus", "Campus"],
                ["revision", "Revision", "homework", "Homework"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-review-final",
          title: "Review: Education Vocabulary Final",
          instructions: "Final mixed quiz.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Revision club meets in the _____ on Wednesday.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Library — nơi học revision club.",
              correct: "library",
              wrong: ["semester", "graduate"],
              distractorNotes: ["Học kỳ", "Tốt nghiệp"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The history _____ is about campus life one hundred years ago.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Assignment — chủ đề bài tập.",
              correct: "assignment",
              wrong: ["exam", "timetable"],
              distractorNotes: ["Kỳ thi chung", "Thời khóa biểu"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
