/** Movers U2 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-have-got",
      title: "Lesson 1: Have Got",
      learningObjective:
        "Use have got / has got to describe symptoms (I've got a headache).",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-havegot-learn",
          title: "Learn: Have Got",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh _____ a headache.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh (he) → has got.",
              correct: "has got",
              wrong: ["have got", "got have"],
              distractorNotes: ["I/you/we/they", "Sai trật tự"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "I _____ a stomach ache today.",
              skillTag: "grammar",
              topicTag,
              explanation: "I → have got.",
              correct: "have got",
              wrong: ["has got", "got has"],
              distractorNotes: ["He/she", "Sai trật tự"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "I've got a headache — rút gọn và có mạo từ a.",
              correct: "I've got a headache.",
              wrong: ["I have got headache.", "I've got headache."],
              distractorNotes: ["Thiếu a", "Thiếu a"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ you got a toothache?",
              skillTag: "grammar",
              topicTag,
              explanation: "Have you got — câu hỏi yes/no.",
              correct: "Have",
              wrong: ["Has", "Do"],
              distractorNotes: ["He/she/it", "Do you have cũng đúng nhưng câu này dùng Have got"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-havegot-practice",
          title: "Practice: Complete Have Got",
          instructions: "Fill in have got or has got.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I [0] a headache. | Minh [1] a bad tooth. | We [2] stomach aches today.",
              skillTag: "grammar",
              topicTag,
              explanation: "have got; has got; have got — I/Minh/we.",
              template:
                "I [0] a headache. Minh [1] a bad tooth. We [2] stomach aches today.",
              correctAnswers: ["have got", "has got", "have got"],
              acceptableAnswers: [
                ["have got", "'ve got"],
                ["has got", "'s got"],
                ["have got", "'ve got"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-havegot-check",
          title: "Check: Have Got Challenge",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh tells the doctor: I _____ a headache.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh nói về bản thân → I've got.",
              correct: "'ve got",
              wrong: ["'s got", "got"],
              distractorNotes: ["He/she form", "Thiếu have"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which question is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Have you got a headache? — câu hỏi chuẩn.",
              correct: "Have you got a headache?",
              wrong: ["You have got a headache?", "Have you got headache?"],
              distractorNotes: ["Không đảo trợ động từ", "Thiếu a"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "She _____ a pain in her head.",
              skillTag: "grammar",
              topicTag,
              explanation: "She → has got.",
              correct: "has got",
              wrong: ["have got", "got have"],
              distractorNotes: ["I/you/we", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-havegot-apply",
          title: "Apply: Build Have Got Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: I've / got / a / headache / today.",
              skillTag: "grammar",
              topicTag,
              explanation: "I've got a headache today.",
              words: ["I've", "got", "a", "headache", "today."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Minh / has / got / a / bad / tooth.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh has got a bad tooth.",
              words: ["Minh", "has", "got", "a", "bad", "tooth."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-havegot-review",
          title: "Review: Have Got Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "They _____ stomach aches after lunch.",
              skillTag: "grammar",
              topicTag,
              explanation: "They → have got.",
              correct: "have got",
              wrong: ["has got", "'s got"],
              distractorNotes: ["He/she/it", "He/she/it"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "He's got a toothache — he has got rút gọn.",
              correct: "He's got a toothache.",
              wrong: ["He have got a toothache.", "He got a toothache have."],
              distractorNotes: ["Sai ngôi", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "_____ she got a headache?",
              skillTag: "grammar",
              topicTag,
              explanation: "Has she got — câu hỏi với she.",
              correct: "Has",
              wrong: ["Have", "Does"],
              distractorNotes: ["I/you/we/they", "Does she have cũng được nhưng không khớp got"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-should-advice",
      title: "Lesson 2: Should for Advice",
      learningObjective:
        "Use should and shouldn't to give simple health advice.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-should-learn",
          title: "Learn: Should + Verb",
          instructions: "Choose the correct advice sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "You are ill. You _____ rest at home.",
              skillTag: "grammar",
              topicTag,
              explanation: "Should + động từ nguyên mẫu rest.",
              correct: "should",
              wrong: ["should to", "shoulds"],
              distractorNotes: ["Không có to", "Không thêm -s"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "You should take medicine — should + take.",
              correct: "You should take this medicine.",
              wrong: ["You should to take this medicine.", "You should takes medicine."],
              distractorNotes: ["Thừa to", "Sai -s"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When you are ill, you _____ go to school.",
              skillTag: "grammar",
              topicTag,
              explanation: "Shouldn't — lời khuyên phủ định.",
              correct: "shouldn't",
              wrong: ["should", "don't should"],
              distractorNotes: ["Ngược nghĩa", "Không dùng don't should"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The doctor says: You _____ drink water.",
              skillTag: "grammar",
              topicTag,
              explanation: "Should drink — lời khuyên tích cực.",
              correct: "should",
              wrong: ["should to", "shoulding"],
              distractorNotes: ["Thừa to", "Không tồn tại"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-should-practice",
          title: "Practice: Should or Shouldn't",
          instructions: "Complete with should or shouldn't.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: You [0] rest when you are ill. | You [1] play football today. | You [2] take your medicine.",
              skillTag: "grammar",
              topicTag,
              explanation: "should; shouldn't; should — nghỉ/uống thuốc nên; chơi bóng không nên.",
              template:
                "You [0] rest when you are ill. You [1] play football today. You [2] take your medicine.",
              correctAnswers: ["should", "shouldn't", "should"],
              acceptableAnswers: [
                ["should", "Should"],
                ["shouldn't", "should not", "Shouldn't"],
                ["should", "Should"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-should-check",
          title: "Check: Advice Challenge",
          instructions: "Choose the best advice.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh has got a headache. Best advice:",
              skillTag: "grammar",
              topicTag,
              explanation: "You should rest — nghỉ khi đau đầu.",
              correct: "You should rest at home.",
              wrong: ["You should to rest at home.", "You should rests at home."],
              distractorNotes: ["Thừa to", "Sai -s"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is NOT good advice?",
              skillTag: "grammar",
              topicTag,
              explanation: "You shouldn't eat bad food — đúng; câu sai là should to go.",
              correct: "You should to go to school when you are ill.",
              wrong: [
                "You should see a doctor.",
                "You shouldn't eat bad food.",
              ],
              distractorNotes: ["Lời khuyên đúng", "Lời khuyên đúng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum says: He _____ see a doctor.",
              skillTag: "grammar",
              topicTag,
              explanation: "Should see — he should + see.",
              correct: "should",
              wrong: ["should to", "shoulds"],
              distractorNotes: ["Thừa to", "Sai -s"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-should-apply",
          title: "Apply: Order Advice Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: You / should / rest / and / take / medicine.",
              skillTag: "grammar",
              topicTag,
              explanation: "You should rest and take medicine.",
              words: ["You", "should", "rest", "and", "take", "medicine."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: You / shouldn't / go / to / school / today.",
              skillTag: "grammar",
              topicTag,
              explanation: "You shouldn't go to school today.",
              words: ["You", "shouldn't", "go", "to", "school", "today."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-should-review",
          title: "Review: Should Mix",
          instructions: "Choose the correct advice sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "You should drink water — should + drink.",
              correct: "You should drink water when you are ill.",
              wrong: ["You should to drink water.", "You should drinks water."],
              distractorNotes: ["Thừa to", "Sai -s"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh is ill. She _____ play outside.",
              skillTag: "grammar",
              topicTag,
              explanation: "Shouldn't — không nên chơi ngoài trời.",
              correct: "shouldn't",
              wrong: ["should", "shouldn't to"],
              distractorNotes: ["Ngược nghĩa", "Không có to"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The doctor says: You _____ take this medicine twice a day.",
              skillTag: "grammar",
              topicTag,
              explanation: "Should take — lời dặn của bác sĩ.",
              correct: "should",
              wrong: ["should to", "shoulding"],
              distractorNotes: ["Thừa to", "Sai dạng"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-feel-health",
      title: "Lesson 3: Feel + Adjective & Health Questions",
      learningObjective:
        "Use feel sick/ill and ask health questions with Do you feel…? / Have you got…?",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-feel-learn",
          title: "Learn: Feel Sick / Feel Ill",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh _____ sick at school.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh (he) → feels sick.",
              correct: "feels",
              wrong: ["feel", "feeling"],
              distractorNotes: ["I/you/we", "Cần am/is/are"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "I don't _____ well today.",
              skillTag: "grammar",
              topicTag,
              explanation: "Feel well — feel + adjective.",
              correct: "feel",
              wrong: ["feels", "feeling"],
              distractorNotes: ["He/she form", "Thiếu am"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ you feel ill?",
              skillTag: "grammar",
              topicTag,
              explanation: "Do you feel — câu hỏi present simple.",
              correct: "Do",
              wrong: ["Does", "Are"],
              distractorNotes: ["He/she", "Are you ill — khác cấu trúc"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "She feels ill — feel + ill, không thêm a.",
              correct: "She feels ill today.",
              wrong: ["She feels a ill today.", "She feel ill today."],
              distractorNotes: ["Ill không dùng a", "Thiếu -s"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-feel-practice",
          title: "Practice: Complete Health Sentences",
          instructions: "Fill in the gaps.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh [0] sick at school. | [1] you feel ill? | Yes, I [2] got a headache.",
              skillTag: "grammar",
              topicTag,
              explanation: "feels; Do; have/'ve — cảm giác, câu hỏi, triệu chứng.",
              template:
                "Minh [0] sick at school. [1] you feel ill? Yes, I [2] got a headache.",
              correctAnswers: ["feels", "Do", "have"],
              acceptableAnswers: [
                ["feels", "Feels"],
                ["Do", "do"],
                ["have", "'ve", "Have"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-feel-check",
          title: "Check: Health Questions",
          instructions: "Choose the correct question or answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which question is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Do you feel sick? — câu hỏi chuẩn.",
              correct: "Do you feel sick?",
              wrong: ["You feel sick?", "Do you feels sick?"],
              distractorNotes: ["Thiếu Do", "Sai -s"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best answer: Have you got a headache?",
              skillTag: "grammar",
              topicTag,
              explanation: "Yes, I've got a headache — trả lời ngắn tự nhiên.",
              correct: "Yes, I've got a headache.",
              wrong: ["Yes, I have got a headache wrong.", "Yes, got I headache."],
              distractorNotes: ["Thừa wrong", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The teacher says: Minh _____ sick.",
              skillTag: "grammar",
              topicTag,
              explanation: "Feels sick — he feels.",
              correct: "feels",
              wrong: ["feel", "feeling"],
              distractorNotes: ["I/you", "Thiếu is"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-feel-apply",
          title: "Apply: Build Health Questions",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Do / you / feel / sick / today?",
              skillTag: "grammar",
              topicTag,
              explanation: "Do you feel sick today?",
              words: ["Do", "you", "feel", "sick", "today?"],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Have / you / got / a / stomach / ache?",
              skillTag: "grammar",
              topicTag,
              explanation: "Have you got a stomach ache?",
              words: ["Have", "you", "got", "a", "stomach", "ache?"],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-feel-review",
          title: "Review: Feel and Questions Mix",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "I feel sick — I + feel.",
              correct: "I feel sick and I've got a headache.",
              wrong: ["I feels sick.", "I feel sickly and have got headache."],
              distractorNotes: ["Sai -s", "Sai từ và thiếu a"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "_____ Minh feel ill today?",
              skillTag: "grammar",
              topicTag,
              explanation: "Does Minh feel — third person question.",
              correct: "Does",
              wrong: ["Do", "Is"],
              distractorNotes: ["I/you/we", "Is Minh ill — khác"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best advice after 'I feel ill':",
              skillTag: "grammar",
              topicTag,
              explanation: "You should rest — kết hợp feel ill + should.",
              correct: "You should rest and see a doctor.",
              wrong: ["You should to rest.", "You should rests."],
              distractorNotes: ["Thừa to", "Sai -s"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
