/** Movers U2 — listening lessons (3 × 5 exercises). */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptDoctor,
  listeningScriptCallMum,
  listeningAnswerKeys,
  topicTag,
}) {
  const doctor = listeningScriptDoctor;
  const callMum = listeningScriptCallMum;
  const keysDoctor = listeningAnswerKeys.doctor;
  const keysCall = listeningAnswerKeys.callMum;

  return [
    {
      slug: "listening-at-doctor",
      title: "Lesson 1: At the Doctor",
      learningObjective:
        "Listen to a doctor dialogue and understand symptoms and advice.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-doctor-learn",
          title: "Learn: At the Doctor",
          instructions: "Listen to Minh and the doctor. Answer the questions.",
          sortOrder: 0,
          script: doctor,
          answerKey: keysDoctor,
          questions: [
            buildMcq({
              questionText: "What has Minh got?",
              skillTag: "listening",
              topicTag,
              explanation: "I've got a headache, Doctor.",
              correct: "A headache",
              wrong: ["A broken arm", "A football injury"],
              distractorNotes: ["Arm not broken", "Not mentioned"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Does Minh have a stomach ache?",
              skillTag: "listening",
              topicTag,
              explanation: "Yes, my stomach hurts.",
              correct: "Yes",
              wrong: ["No", "Not in the dialogue"],
              distractorNotes: ["He says yes", "Clearly stated"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-doctor-practice",
          title: "Practice: More Doctor Details",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: doctor,
          answerKey: keysDoctor,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "What else is wrong with Minh?",
              skillTag: "listening",
              topicTag,
              explanation: "You've got a bad tooth.",
              correct: "A bad tooth",
              wrong: ["A bad arm", "He is not ill"],
              distractorNotes: ["Arm is fine", "Doctor treats him"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What should Minh do today?",
              skillTag: "listening",
              topicTag,
              explanation: "You should rest today.",
              correct: "Rest",
              wrong: ["Go to school", "Play football"],
              distractorNotes: ["Opposite advice", "Not mentioned"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-doctor-check",
          title: "Check: Doctor Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: doctor,
          answerKey: keysDoctor,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "How often should Minh take the medicine?",
              skillTag: "listening",
              topicTag,
              explanation: "Take this medicine twice a day.",
              correct: "Twice a day",
              wrong: ["Once a week", "Never"],
              distractorNotes: ["Wrong frequency", "Doctor gives medicine"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who says Minh can go home?",
              skillTag: "listening",
              topicTag,
              explanation: "Nurse: You can go home now, Minh.",
              correct: "The nurse",
              wrong: ["Linh", "Minh's teacher"],
              distractorNotes: ["Not in this dialogue", "Not in this dialogue"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-doctor-apply",
          title: "Apply: Match Doctor Advice",
          instructions: "Listen again. Match each problem to the advice.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: doctor },
          questions: [
            buildMatching({
              questionText: "Match symptoms to doctor's advice.",
              skillTag: "listening",
              topicTag,
              explanation: "Headache/tooth → rest and medicine.",
              pairs: [
                { left: "headache", right: "rest today" },
                { left: "bad tooth", right: "see the doctor's check" },
                { left: "need medicine", right: "take it twice a day" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-doctor-review",
          title: "Review: Doctor Dialogue Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: doctor,
          answerKey: keysDoctor,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Minh says: I've got a _____, Doctor.",
              skillTag: "listening",
              topicTag,
              explanation: "Headache — đau đầu.",
              correct: "headache",
              wrong: ["hospital", "medicine"],
              distractorNotes: ["Nơi", "Thuốc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The doctor tells Minh to take _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Take this medicine — uống thuốc.",
              correct: "medicine",
              wrong: ["football", "homework"],
              distractorNotes: ["Không liên quan", "Không liên quan"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-call-mum",
      title: "Lesson 2: Calling Mum from School",
      learningObjective:
        "Listen to a school phone call and understand a simple health context.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-call-learn",
          title: "Learn: Phone Call from School",
          instructions: "Listen to the teacher, Mum and Minh. Answer the questions.",
          sortOrder: 0,
          script: callMum,
          answerKey: keysCall,
          questions: [
            buildMcq({
              questionText: "Who calls Minh's mum?",
              skillTag: "listening",
              topicTag,
              explanation: "This is Minh's teacher — giáo viên gọi.",
              correct: "Minh's teacher",
              wrong: ["Linh", "The doctor"],
              distractorNotes: ["Friend", "Later at hospital"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "How does Minh feel?",
              skillTag: "listening",
              topicTag,
              explanation: "Minh feels sick. He's got a headache.",
              correct: "Sick with a headache",
              wrong: ["Happy and well", "Excited about football"],
              distractorNotes: ["Opposite", "Not mentioned"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-call-practice",
          title: "Practice: Listen for Advice",
          instructions: "Listen again. Focus on should and advice.",
          sortOrder: 1,
          script: callMum,
          answerKey: keysCall,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "Should Mum come to school?",
              skillTag: "listening",
              topicTag,
              explanation: "Yes, please. He's resting in the office.",
              correct: "Yes",
              wrong: ["No", "Not mentioned"],
              distractorNotes: ["Teacher asks her to come", "Clearly stated"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum says Minh should _____.",
              skillTag: "listening",
              topicTag,
              explanation: "He should see a doctor.",
              correct: "see a doctor",
              wrong: ["play football", "do homework first"],
              distractorNotes: ["Not appropriate", "Not in call"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-call-check",
          title: "Check: Phone Call Details",
          instructions: "Listen to the full conversation again.",
          sortOrder: 2,
          script: callMum,
          answerKey: keysCall,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What doesn't hurt according to Minh?",
              skillTag: "listening",
              topicTag,
              explanation: "Mum, my arm doesn't hurt. It's my head.",
              correct: "His arm",
              wrong: ["His head", "His stomach"],
              distractorNotes: ["Head hurts", "Not mentioned in call"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Where will they go?",
              skillTag: "listening",
              topicTag,
              explanation: "We'll go to the hospital.",
              correct: "The hospital",
              wrong: ["The park", "Football field"],
              distractorNotes: ["Not mentioned", "Not mentioned"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Where is Minh resting before Mum arrives?",
              skillTag: "listening",
              topicTag,
              explanation: "He's resting in the office.",
              correct: "In the school office",
              wrong: ["In the hospital", "In the playground"],
              distractorNotes: ["Not yet", "Too active"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-call-apply",
          title: "Apply: Order the Phone Call",
          instructions: "Put the events in the order you hear them.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          content: { script: callMum },
          questions: [
            buildMcq({
              questionText:
                "Correct order: (1) Mum will come (2) Teacher says Minh feels sick (3) They will go to hospital",
              skillTag: "listening",
              topicTag,
              explanation: "Teacher explains → Mum comes → hospital plan.",
              correct: "2 → 1 → 3",
              wrong: ["1 → 2 → 3", "3 → 2 → 1"],
              distractorNotes: ["Mum comes after news", "Hospital after Mum decides"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-call-review",
          title: "Review: Phone Call Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: callMum,
          answerKey: keysCall,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Minh's got a _____.",
              skillTag: "listening",
              topicTag,
              explanation: "He's got a headache — đau đầu.",
              correct: "headache",
              wrong: ["football", "homework"],
              distractorNotes: ["Không liên quan", "Không liên quan"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum says: Don't worry. We'll go to the _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Hospital — bệnh viện.",
              correct: "hospital",
              wrong: ["school", "park"],
              distractorNotes: ["Đang ở trường", "Không phù hợp"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-health-review",
      title: "Lesson 3: Review Both Dialogues",
      learningObjective:
        "Understand health problems and advice across two short dialogues.",
      estimatedMinutes: 22,
      exercises: [
        buildListeningExercise({
          slug: "listening-health-review-learn",
          title: "Learn: Doctor Reminder",
          instructions: "Listen to the doctor dialogue again.",
          sortOrder: 0,
          script: doctor,
          answerKey: keysDoctor,
          questions: [
            buildMcq({
              questionText: "Who asks: What's wrong?",
              skillTag: "listening",
              topicTag,
              explanation: "Doctor: Hello Minh. What's wrong?",
              correct: "The doctor",
              wrong: ["The nurse first", "Mum"],
              distractorNotes: ["Nurse speaks later", "Not in this dialogue"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh should _____ today.",
              skillTag: "listening",
              topicTag,
              explanation: "You should rest today.",
              correct: "rest",
              wrong: ["go to school", "play sport"],
              distractorNotes: ["Opposite", "Not advised"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-health-review-practice",
          title: "Practice: Phone Call Reminder",
          instructions: "Listen to the school phone call again.",
          sortOrder: 1,
          script: callMum,
          answerKey: keysCall,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "The teacher calls Minh's _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Hello, Mrs Tran — gọi mẹ.",
              correct: "mum",
              wrong: ["doctor", "friend Linh"],
              distractorNotes: ["Doctor later", "Linh not in call"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum will come to school because Minh _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Minh feels sick — cần mẹ đến.",
              correct: "feels sick",
              wrong: ["won a prize", "needs homework help"],
              distractorNotes: ["Not mentioned", "Not the reason"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-health-review-check",
          title: "Check: Mixed Health Listening",
          instructions: "Listen to the doctor dialogue. Harder questions.",
          sortOrder: 2,
          script: doctor,
          answerKey: keysDoctor,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which symptom is ONLY mentioned in the doctor dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Bad tooth — bác sĩ mở miệng kiểm tra răng.",
              correct: "A bad tooth",
              wrong: ["Arm pain", "Broken leg"],
              distractorNotes: ["Arm doesn't hurt in phone call", "Not mentioned"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Both dialogues mention Minh's _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Headache in both — đau đầu.",
              correct: "headache",
              wrong: ["football", "birthday"],
              distractorNotes: ["Not in dialogues", "Not in dialogues"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-health-review-apply",
          title: "Apply: Match Dialogue to Fact",
          instructions: "Match each fact to the correct dialogue.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: callMum },
          questions: [
            buildMatching({
              questionText: "Match facts to Doctor or Phone call dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Doctor: tooth/medicine; Phone: teacher/office/hospital plan.",
              pairs: [
                { left: "Take medicine twice a day", right: "Doctor dialogue" },
                { left: "Minh rests in the school office", right: "Phone call dialogue" },
                { left: "Open your mouth please", right: "Doctor dialogue" },
                { left: "We'll go to the hospital", right: "Phone call dialogue" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-health-review-final",
          title: "Review: Both Dialogues Mix",
          instructions: "Listen to the phone call. Final review.",
          sortOrder: 4,
          script: callMum,
          answerKey: keysCall,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which place is in the phone call but NOT the doctor room?",
              skillTag: "listening",
              topicTag,
              explanation: "School office — Minh nghỉ ở văn phòng trường.",
              correct: "School office",
              wrong: ["Hospital room", "Doctor's desk"],
              distractorNotes: ["Hospital planned later", "Doctor dialogue setting"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh tells Mum his _____ doesn't hurt.",
              skillTag: "listening",
              topicTag,
              explanation: "My arm doesn't hurt — cánh tay không đau.",
              correct: "arm",
              wrong: ["head", "tooth"],
              distractorNotes: ["Head hurts", "Not in phone call"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
