/** Movers U2 — reading lessons (3 × 5 exercises). */

export function readingLessons({
  buildMcq,
  buildGapFill,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMinhFeelsIll,
  topicTag,
}) {
  const passage = passageMinhFeelsIll;

  return [
    {
      slug: "reading-gist-feeling-ill",
      title: "Lesson 1: Read for Gist",
      learningObjective:
        "Read a short text about feeling ill and identify the main idea.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-gist-learn",
          title: "Learn: Minh Feels Ill",
          instructions: "Read the passage. Answer the questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "Who is the text about?",
              skillTag: "reading",
              topicTag,
              explanation: "The text is about Minh, a nine-year-old boy in Hanoi.",
              correct: "A boy called Minh",
              wrong: ["A girl called Linh", "Only the doctor"],
              distractorNotes: ["Linh only sends a message", "Minh is the main character"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What is the text mainly about?",
              skillTag: "reading",
              topicTag,
              explanation: "Toàn bài kể Minh ốm và đi bệnh viện.",
              correct: "Minh feeling ill and going to hospital",
              wrong: ["Minh's football game", "Minh's holiday"],
              distractorNotes: ["Not in the text", "Not in the text"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-gist-practice",
          title: "Practice: School or Hospital?",
          instructions: "Read again. Decide where each event happens.",
          sortOrder: 1,
          passage,
          difficulty: 0.25,
          questions: [
            buildMcq({
              questionText: "Where does Minh first feel sick?",
              skillTag: "reading",
              topicTag,
              explanation: "At school Minh tells his teacher — ốm ở trường trước.",
              correct: "At school",
              wrong: ["At the hospital", "At home only"],
              distractorNotes: ["Later in story", "Goes home after hospital"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Where does the doctor look at Minh's tooth?",
              skillTag: "reading",
              topicTag,
              explanation: "At the hospital — bác sĩ khám ở bệnh viện.",
              correct: "At the hospital",
              wrong: ["At school", "In the park"],
              distractorNotes: ["Teacher calls mum at school", "Not mentioned"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-gist-check",
          title: "Check: Main Idea",
          instructions: "Read carefully. These questions need thinking.",
          sortOrder: 2,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What is the best title for this text?",
              skillTag: "reading",
              topicTag,
              explanation: "Chủ đề chính: Minh ốm → Minh Feels Ill.",
              correct: "Minh Feels Ill",
              wrong: ["Minh Plays Football", "Minh's Birthday Party"],
              distractorNotes: ["Not in text", "Not in text"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is NOT true about Minh?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh goes to hospital — không ở nhà suốt.",
              correct: "Minh stays at home all day and never goes to hospital.",
              wrong: [
                "Minh has got a headache.",
                "The doctor tells him to rest.",
              ],
              distractorNotes: ["True in text", "True in text"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-gist-apply",
          title: "Apply: Match Story Events",
          instructions: "Use the passage. Match each person to what they do.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each person to their action in the story.",
              skillTag: "reading",
              topicTag,
              explanation: "Teacher calls mum; nurse checks arm; doctor gives advice.",
              pairs: [
                { left: "Teacher", right: "calls Minh's mum" },
                { left: "Nurse", right: "checks Minh's arm" },
                { left: "Doctor", right: "says Minh should rest" },
                { left: "Linh", right: "sends Get well soon message" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-gist-review",
          title: "Review: Story Overview",
          instructions: "Read the passage one more time. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Where does Minh live?",
              skillTag: "reading",
              topicTag,
              explanation: "He lives in Hanoi — đoạn đầu bài đọc.",
              correct: "Hanoi",
              wrong: ["London", "Ho Chi Minh City"],
              distractorNotes: ["Không có trong bài", "Sai thành phố"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What should Minh do at home?",
              skillTag: "reading",
              topicTag,
              explanation: "Rest on the sofa — nghỉ ngơi ở nhà.",
              correct: "Rest",
              wrong: ["Go to school", "Play football"],
              distractorNotes: ["Đang ốm", "Không phù hợp"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-detail-health",
      title: "Lesson 2: Find Details",
      learningObjective:
        "Find specific symptoms, people and advice in a health text.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-detail-learn",
          title: "Learn: Find the Symptoms",
          instructions: "Read the passage. Find the details.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What has Minh got at the start?",
              skillTag: "reading",
              topicTag,
              explanation: "He has got a headache and his stomach hurts.",
              correct: "A headache and stomach pain",
              wrong: ["A broken arm", "A toothache only"],
              distractorNotes: ["Arm is checked, not broken", "Tooth found later at hospital"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Who takes Minh to the hospital?",
              skillTag: "reading",
              topicTag,
              explanation: "Mum takes Minh to the hospital.",
              correct: "His mum",
              wrong: ["Linh", "The teacher"],
              distractorNotes: ["Sends message later", "Calls mum but doesn't drive"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-detail-practice",
          title: "Practice: True or False?",
          instructions: "Read again. Choose the correct statement.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "The nurse checks Minh's arm.",
              skillTag: "reading",
              topicTag,
              explanation: "A kind nurse checks his arm — đúng.",
              correct: "True",
              wrong: ["False", "Not in the text"],
              distractorNotes: ["Clearly stated", "It is in the text"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh should take medicine once a year.",
              skillTag: "reading",
              topicTag,
              explanation: "Twice a day — không phải once a year.",
              correct: "False",
              wrong: ["True", "Not in the text"],
              distractorNotes: ["Wrong frequency", "Frequency is mentioned"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-detail-check",
          title: "Check: Detail Search",
          instructions: "Find the answers in the text.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "What does the doctor look at?",
              skillTag: "reading",
              topicTag,
              explanation: "The doctor looks at Minh's tooth.",
              correct: "Minh's tooth",
              wrong: ["Minh's arm only", "Minh's homework"],
              distractorNotes: ["Nurse checks arm", "Not in text"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How often should Minh take the medicine?",
              skillTag: "reading",
              topicTag,
              explanation: "Take this medicine twice a day.",
              correct: "Twice a day",
              wrong: ["Once a week", "Never"],
              distractorNotes: ["Wrong frequency", "Doctor gives medicine"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What message does Linh send?",
              skillTag: "reading",
              topicTag,
              explanation: "Get well soon! — chúc mau khỏe.",
              correct: "Get well soon!",
              wrong: ["See you at school!", "Let's play football!"],
              distractorNotes: ["Minh is ill", "Not appropriate"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-detail-apply",
          title: "Apply: Complete from the Text",
          instructions: "Fill in the gaps using words from the passage.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh has got a [0]. | Mum takes him to the [1]. | The doctor says he should [2].",
              skillTag: "reading",
              topicTag,
              explanation: "headache; hospital; rest — chi tiết từ bài đọc.",
              template:
                "Minh has got a [0]. Mum takes him to the [1]. The doctor says he should [2].",
              correctAnswers: ["headache", "hospital", "rest"],
              acceptableAnswers: [
                ["headache", "Headache"],
                ["hospital", "Hospital"],
                ["rest", "Rest"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-detail-review",
          title: "Review: Detail Search Mix",
          instructions: "Find the answers in the text again.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "What hurts besides Minh's head?",
              skillTag: "reading",
              topicTag,
              explanation: "His stomach hurts — đau bụng.",
              correct: "His stomach",
              wrong: ["His arm", "His tooth first"],
              distractorNotes: ["Checked but not main start symptom", "Found at hospital"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Where does Minh rest at the end?",
              skillTag: "reading",
              topicTag,
              explanation: "Rests on the sofa at home.",
              correct: "On the sofa at home",
              wrong: ["At school", "In the hospital bed all night"],
              distractorNotes: ["Already left school", "Goes home"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-match-definitions",
      title: "Lesson 3: Match Definitions to Words",
      learningObjective:
        "Match health word definitions to the correct vocabulary (reading skill).",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-definitions-learn",
          title: "Learn: What Do the Words Mean?",
          instructions: "Read the passage. Match meanings to words.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "A pain in your head is a _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Headache — đau ở đầu.",
              correct: "headache",
              wrong: ["medicine", "hospital"],
              distractorNotes: ["Thuốc chữa, không phải triệu chứng", "Nơi khám"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "A person who treats sick people is a _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Doctor — bác sĩ.",
              correct: "doctor",
              wrong: ["nurse", "medicine"],
              distractorNotes: ["Y tá hỗ trợ", "Thuốc"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-definitions-practice",
          title: "Practice: Match Definitions",
          instructions: "Match each definition to the correct word.",
          exerciseType: "matching",
          sortOrder: 1,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each definition to the health word.",
              skillTag: "reading",
              topicTag,
              explanation: "Đọc định nghĩa và ghép đúng từ vựng unit.",
              pairs: [
                { left: "not well; sick", right: "ill" },
                { left: "something you take when you are ill", right: "medicine" },
                { left: "a place where sick people get help", right: "hospital" },
                { left: "stop activity to get better", right: "rest" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-definitions-check",
          title: "Check: Definition Challenge",
          instructions: "Read the passage. Choose the word for each definition.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Which word means 'feel unwell'?",
              skillTag: "reading",
              topicTag,
              explanation: "Feel sick — cảm thấy mệt/ốm.",
              correct: "feel sick",
              wrong: ["rest", "doctor"],
              distractorNotes: ["Hành động nghỉ", "Người"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word is a body part in your mouth?",
              skillTag: "reading",
              topicTag,
              explanation: "Tooth — răng trong miệng.",
              correct: "tooth",
              wrong: ["arm", "head"],
              distractorNotes: ["Cánh tay", "Đầu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who checks Minh's arm in the story?",
              skillTag: "reading",
              topicTag,
              explanation: "The nurse — y tá.",
              correct: "The nurse",
              wrong: ["Linh", "The teacher"],
              distractorNotes: ["Friend", "Calls mum only"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-definitions-apply",
          title: "Apply: Complete the Definitions",
          instructions: "Fill in the health word for each clue.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: Pain in head = [0]. | Not well = [1]. | Person at hospital who helps doctor = [2].",
              skillTag: "reading",
              topicTag,
              explanation: "headache; ill; nurse — định nghĩa từ vựng.",
              template:
                "Pain in head = [0]. Not well = [1]. Person at hospital who helps doctor = [2].",
              correctAnswers: ["headache", "ill", "nurse"],
              acceptableAnswers: [
                ["headache", "Headache"],
                ["ill", "Ill"],
                ["nurse", "Nurse"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-definitions-review",
          title: "Review: Definitions Mix",
          instructions: "Choose the word that matches each meaning.",
          exerciseType: "matching",
          sortOrder: 4,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Review: match definitions to words.",
              skillTag: "reading",
              topicTag,
              explanation: "Ôn ghép định nghĩa — kỹ năng đọc Movers.",
              pairs: [
                { left: "the middle part of your body where food goes", right: "stomach" },
                { left: "you do this when you are tired or ill", right: "rest" },
                { left: "pain in your head", right: "headache" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
