/** Movers U2 — speaking lessons (3 × 5 exercises; only Check is AI). */

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [symptomsCheck, adviceCheck, doctorCheck] = speakingChecks;

  return [
    {
      slug: "speaking-symptoms",
      title: "Lesson 1: Talk About Symptoms",
      learningObjective:
        "Choose appropriate spoken phrases about feeling ill.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-symptoms-learn",
          title: "Learn: What to Say When Ill",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Someone asks: How do you feel? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I feel sick — câu trả lời tự nhiên.",
              correct: "I feel sick today.",
              wrong: ["Feel sick I.", "I am feel sick."],
              distractorNotes: ["Sai trật tự", "Thừa am"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best answer: Have you got a headache?",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, I've got a headache — trả lời đầy đủ.",
              correct: "Yes, I've got a headache.",
              wrong: ["Yes, headache got I.", "Yes, I have headache."],
              distractorNotes: ["Sai trật tự", "Thiếu a"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-symptoms-practice",
          title: "Practice: Symptom Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Your stomach hurts. Best thing to say:",
              skillTag: "speaking",
              topicTag,
              explanation: "My stomach hurts — nói rõ triệu chứng.",
              correct: "My stomach hurts.",
              wrong: ["Stomach my hurt.", "I stomach hurting."],
              distractorNotes: ["Sai trật tự", "Sai ngữ pháp"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Tell the teacher you are ill. Best sentence:",
              skillTag: "speaking",
              topicTag,
              explanation: "I feel sick — thông báo lịch sự.",
              correct: "Teacher, I feel sick. I have got a headache.",
              wrong: ["Sick feel teacher.", "Ill I am headache got."],
              distractorNotes: ["Không thành câu", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        symptomsCheck,
        buildExercise({
          slug: "speaking-symptoms-apply",
          title: "Apply: Quick Symptom Replies",
          instructions: "Choose the best short spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Doctor asks: What's wrong? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I've got a headache — trả lời bác sĩ.",
              correct: "I've got a headache, Doctor.",
              wrong: ["Headache got.", "I am headache doctor."],
              distractorNotes: ["Quá ngắn", "Sai ngữ pháp"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-symptoms-review",
          title: "Review: Symptom Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Describe your pain. Best phrase:",
              skillTag: "speaking",
              topicTag,
              explanation: "My head hurts — mô tả đau đầu.",
              correct: "My head hurts. I've got a headache.",
              wrong: ["Head hurt my.", "Hurts head I got."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say you cannot go to school. Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "I am ill — không đi học vì ốm.",
              correct: "I am ill so I cannot go to school.",
              wrong: ["School no ill.", "Cannot school I ill am."],
              distractorNotes: ["Không thành câu", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-advice",
      title: "Lesson 2: Give Health Advice",
      learningObjective:
        "Use should and shouldn't in short spoken advice.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-advice-learn",
          title: "Learn: Say Should / Shouldn't",
          instructions: "Choose the best spoken advice.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Your friend is ill. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "You should rest — lời khuyên chuẩn.",
              correct: "You should rest at home.",
              wrong: ["You should to rest.", "You should rests."],
              distractorNotes: ["Thừa to", "Sai -s"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Friend has a headache. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "You shouldn't play football — không nên chơi.",
              correct: "You shouldn't play football today.",
              wrong: ["You shouldn't to play.", "You shouldn't plays."],
              distractorNotes: ["Thừa to", "Sai -s"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-advice-practice",
          title: "Practice: Medicine Advice",
          instructions: "Choose the correct spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Doctor's advice — best thing to repeat:",
              skillTag: "speaking",
              topicTag,
              explanation: "You should take this medicine — nhắc lại lời bác sĩ.",
              correct: "You should take this medicine twice a day.",
              wrong: ["You should to take medicine.", "Take should you medicine."],
              distractorNotes: ["Thừa to", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum says Minh should see a doctor. Best reply:",
              skillTag: "speaking",
              topicTag,
              explanation: "OK, we'll go to the hospital — đồng ý hợp lý.",
              correct: "OK, Mum. We'll go to the hospital.",
              wrong: ["Hospital go OK.", "Mum doctor should OK."],
              distractorNotes: ["Sai trật tự", "Không thành câu"],
              difficultyRating: 2,
            }),
          ],
        }),
        adviceCheck,
        buildExercise({
          slug: "speaking-advice-apply",
          title: "Apply: Choose the Best Advice",
          instructions: "Pick the most natural spoken advice.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Linh has a headache. Best advice:",
              skillTag: "speaking",
              topicTag,
              explanation: "Rest + drink water — lời khuyên đơn giản.",
              correct: "You should rest and drink water.",
              wrong: ["Rest should water drink you.", "You should rests water."],
              distractorNotes: ["Sai trật tự", "Sai -s"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-advice-review",
          title: "Review: Advice Speaking Quiz",
          instructions: "Choose the best advice using should.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "When you are ill, best advice to yourself:",
              skillTag: "speaking",
              topicTag,
              explanation: "I should rest — tự nhắc bản thân.",
              correct: "I should rest and take my medicine.",
              wrong: ["I should to rest medicine.", "Rest I should medicine take."],
              distractorNotes: ["Thừa to", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What shouldn't you do when ill?",
              skillTag: "speaking",
              topicTag,
              explanation: "You shouldn't go to school — nghỉ học.",
              correct: "You shouldn't go to school.",
              wrong: ["You shouldn't to go school.", "You shouldn't goes school."],
              distractorNotes: ["Thừa to", "Sai -s"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-doctor-visit",
      title: "Lesson 3: Talk About the Doctor",
      learningObjective:
        "Describe a doctor or hospital visit in short spoken answers.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-doctor-learn",
          title: "Learn: Hospital Phrases",
          instructions: "Choose the best thing to say about the doctor.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Where did you go when you were ill? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "I went to the hospital — trả lời địa điểm.",
              correct: "I went to the hospital with my mum.",
              wrong: ["Hospital went I mum.", "I go hospital ill."],
              distractorNotes: ["Sai trật tự", "Sai thì"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What did the doctor say? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "You should rest — lời bác sĩ.",
              correct: "The doctor said I should rest and take medicine.",
              wrong: ["Doctor rest medicine said.", "Said doctor I rest should."],
              distractorNotes: ["Không thành câu", "Sai trật tự"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-doctor-practice",
          title: "Practice: Nurse and Doctor",
          instructions: "Choose the best spoken answers about the hospital.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Who checked your arm? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "The nurse checked my arm — y tá.",
              correct: "The nurse checked my arm.",
              wrong: ["Nurse arm my checked.", "My arm nurse check."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What did the doctor look at? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "My tooth — bác sĩ xem răng.",
              correct: "The doctor looked at my tooth.",
              wrong: ["Tooth doctor my.", "Looked tooth doctor I."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        doctorCheck,
        buildExercise({
          slug: "speaking-doctor-apply",
          title: "Apply: Tell the Story",
          instructions: "Choose the best short spoken description.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best short story about Minh's day:",
              skillTag: "speaking",
              topicTag,
              explanation: "Feel sick → hospital → rest — thứ tự rõ.",
              correct:
                "Minh felt sick at school. Mum took him to hospital. The doctor said he should rest.",
              wrong: ["Sick school hospital rest Minh.", "Minh hospital sick doctor rest should."],
              distractorNotes: ["Không thành câu", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-doctor-review",
          title: "Review: Doctor Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "What do you say to a sick friend? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Get well soon! — chúc mau khỏe.",
              correct: "Get well soon, Linh!",
              wrong: ["Well get soon Linh.", "Linh soon well get."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Describe the doctor's advice. Best pair:",
              skillTag: "speaking",
              topicTag,
              explanation: "Rest + medicine — như trong bài.",
              correct: "You should rest. You should take medicine twice a day.",
              wrong: ["Rest should medicine you.", "You rests medicine should."],
              distractorNotes: ["Sai trật tự", "Sai -s"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
