/** Movers U2 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-body-parts",
      title: "Lesson 1: Body Parts",
      learningObjective:
        "Recognise and use head, stomach, tooth and arm in short health sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-body-learn",
          title: "Learn: Body Part Words",
          instructions: "Read each clue. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "You think with this part of your body. It is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Head (đầu) — nơi bạn suy nghĩ và thường bị đau đầu.",
              correct: "head",
              wrong: ["arm", "tooth"],
              distractorNotes: ["Cánh tay", "Răng — trong miệng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh's _____ hurts after he eats bad food.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Stomach (bụng/dạ dày) — đau bụng sau khi ăn.",
              correct: "stomach",
              wrong: ["head", "arm"],
              distractorNotes: ["Đau đầu", "Cánh tay"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The doctor looks inside Minh's mouth at his _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Tooth (răng) — bác sĩ kiểm tra răng trong miệng.",
              correct: "tooth",
              wrong: ["head", "stomach"],
              distractorNotes: ["Ở trên cơ thể", "Ở bụng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The nurse checks Minh's _____ at the hospital.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Arm (cánh tay) — y tá kiểm tra cánh tay.",
              correct: "arm",
              wrong: ["tooth", "medicine"],
              distractorNotes: ["Trong miệng", "Là thuốc, không phải bộ phận"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-body-practice",
          title: "Practice: Match Body Parts",
          instructions: "Match each word to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the body part words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mỗi từ chỉ một bộ phận cơ thể rõ ràng.",
              pairs: [
                { left: "head", right: "the top part of your body with your brain" },
                { left: "stomach", right: "the middle part of your body where food goes" },
                { left: "tooth", right: "hard white part in your mouth for biting" },
                { left: "arm", right: "the part between your shoulder and your hand" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-body-check",
          title: "Check: Body Parts Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "I've got a pain in my _____. (thinking part)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Head — đau ở đầu.",
              correct: "head",
              wrong: ["arm", "stomach"],
              distractorNotes: ["Cánh tay", "Bụng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "My _____ hurts. I shouldn't eat more food.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Stomach — đau bụng, không nên ăn thêm.",
              correct: "stomach",
              wrong: ["head", "tooth"],
              distractorNotes: ["Đau đầu", "Đau răng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Open your mouth. The doctor checks your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Tooth — bác sĩ xem răng trong miệng.",
              correct: "tooth",
              wrong: ["arm", "head"],
              distractorNotes: ["Không trong miệng", "Không trong miệng"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-body-apply",
          title: "Apply: Complete Body Sentences",
          instructions: "Fill in each gap with the correct body word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: My [0] hurts. | The nurse checks my [1]. | The doctor looks at my [2].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "head; arm; tooth — ba bộ phận khác nhau.",
              template:
                "My [0] hurts. The nurse checks my [1]. The doctor looks at my [2].",
              correctAnswers: ["head", "arm", "tooth"],
              acceptableAnswers: [
                ["head", "Head"],
                ["arm", "Arm"],
                ["tooth", "Tooth"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-body-review",
          title: "Review: Body Parts Mix",
          instructions: "Mixed review from this lesson. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Minh has got a pain in his _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Head — đau đầu trong bài đọc.",
              correct: "head",
              wrong: ["arm", "medicine"],
              distractorNotes: ["Không đau tay", "Thuốc không phải bộ phận"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Food goes to your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Stomach — thức ăn vào dạ dày.",
              correct: "stomach",
              wrong: ["head", "arm"],
              distractorNotes: ["Đầu", "Tay"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You use your _____ to hold things.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Arm — cánh tay giúp cầm đồ (cùng với tay).",
              correct: "arm",
              wrong: ["tooth", "head"],
              distractorNotes: ["Răng không cầm", "Đầu không cầm"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-people-places",
      title: "Lesson 2: People and Places",
      learningObjective:
        "Use doctor, hospital and nurse to talk about getting help when ill.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-people-learn",
          title: "Learn: Doctor, Nurse, Hospital",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "A _____ helps sick people and gives medicine.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Doctor (bác sĩ) — chữa bệnh và kê thuốc.",
              correct: "doctor",
              wrong: ["hospital", "head"],
              distractorNotes: ["Là nơi, không phải người", "Bộ phận cơ thể"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mum takes Minh to the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hospital (bệnh viện) — nơi khám bệnh.",
              correct: "hospital",
              wrong: ["doctor", "tooth"],
              distractorNotes: ["Là người", "Răng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "A _____ checks Minh's arm at the hospital.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Nurse (y tá) — hỗ trợ bác sĩ, kiểm tra bệnh nhân.",
              correct: "nurse",
              wrong: ["doctor", "medicine"],
              distractorNotes: ["Bác sĩ khác vai trò", "Thuốc không phải người"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The _____ says: 'You should rest and take medicine.'",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Doctor — bác sĩ đưa lời khuyên y tế.",
              correct: "doctor",
              wrong: ["hospital", "arm"],
              distractorNotes: ["Tòa nhà không nói", "Bộ phận cơ thể"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-people-practice",
          title: "Practice: Match People and Places",
          instructions: "Match each word to the correct description.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match health people and places.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Doctor, nurse, hospital — vai trò và địa điểm khác nhau.",
              pairs: [
                { left: "doctor", right: "a person who treats sick people" },
                { left: "nurse", right: "a person who helps the doctor and patients" },
                { left: "hospital", right: "a place where sick people go for help" },
                { left: "medicine", right: "something you take when you are ill" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-people-check",
          title: "Check: People and Places Quiz",
          instructions: "Choose the best answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Where does Minh go when he is very ill?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hospital — bệnh viện trong bài đọc.",
              correct: "the hospital",
              wrong: ["the park", "school only"],
              distractorNotes: ["Công viên", "Trường không đủ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who checks Minh's arm?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Nurse — y tá kiểm tra cánh tay.",
              correct: "The nurse",
              wrong: ["Linh", "The teacher only"],
              distractorNotes: ["Bạn học", "Giáo viên gọi mẹ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The _____ looks at Minh's tooth.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Doctor — bác sĩ xem răng.",
              correct: "doctor",
              wrong: ["nurse", "hospital"],
              distractorNotes: ["Y tá kiểm tra tay", "Là nơi"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-people-apply",
          title: "Apply: Hospital Sentences",
          instructions: "Complete the sentences about the hospital.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Mum takes Minh to the [0]. | A [1] checks his arm. | The [2] gives him medicine.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "hospital; nurse; doctor — thứ tự hợp lý.",
              template:
                "Mum takes Minh to the [0]. A [1] checks his arm. The [2] gives him medicine.",
              correctAnswers: ["hospital", "nurse", "doctor"],
              acceptableAnswers: [
                ["hospital", "Hospital"],
                ["nurse", "Nurse"],
                ["doctor", "Doctor"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-people-review",
          title: "Review: People and Places Mix",
          instructions: "Mixed review. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "A person who works at a hospital and helps the doctor is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Nurse (y tá) — hỗ trợ bác sĩ.",
              correct: "nurse",
              wrong: ["doctor", "medicine"],
              distractorNotes: ["Bác sĩ", "Thuốc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh is ill, so he goes to the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hospital — đi bệnh viện khi ốm nặng.",
              correct: "hospital",
              wrong: ["head", "arm"],
              distractorNotes: ["Bộ phận cơ thể", "Bộ phận cơ thể"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The _____ tells Minh to take medicine.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Doctor — bác sĩ kê thuốc.",
              correct: "doctor",
              wrong: ["nurse", "Linh"],
              distractorNotes: ["Y tá thường hỗ trợ", "Bạn gửi tin nhắn"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-feeling-unwell",
      title: "Lesson 3: Feeling Unwell",
      learningObjective:
        "Use ill, headache, medicine, rest and feel sick to describe health problems.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-unwell-learn",
          title: "Learn: Illness Words",
          instructions: "Choose the word that best completes each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh is _____ and cannot go to school.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ill (ốm) — không đi học được.",
              correct: "ill",
              wrong: ["rest", "hospital"],
              distractorNotes: ["Là động từ nghỉ", "Là nơi"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "I've got a _____. My head hurts.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Headache (đau đầu) — đau ở đầu.",
              correct: "headache",
              wrong: ["tooth", "arm"],
              distractorNotes: ["Đau răng", "Đau tay"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "You should take this _____ twice a day.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Medicine (thuốc) — uống thuốc theo chỉ dẫn.",
              correct: "medicine",
              wrong: ["head", "doctor"],
              distractorNotes: ["Bộ phận cơ thể", "Người"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When you are ill, you should _____ at home.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rest (nghỉ ngơi) — nghỉ ở nhà khi ốm.",
              correct: "rest",
              wrong: ["feel sick", "hospital"],
              distractorNotes: ["Mô tả cảm giác", "Là nơi"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-unwell-practice",
          title: "Practice: Match Illness Words",
          instructions: "Match each word or phrase to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the illness vocabulary.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ill, headache, feel sick, rest, medicine — từ về ốm và chữa trị.",
              pairs: [
                { left: "ill", right: "not well; sick" },
                { left: "headache", right: "pain in your head" },
                { left: "feel sick", right: "feel unwell or want to vomit" },
                { left: "rest", right: "stop activity and relax to get better" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-unwell-check",
          title: "Check: Illness Challenge",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh _____ at school. His teacher calls his mum.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Feels sick — cảm thấy mệt/ốm ở trường.",
              correct: "feels sick",
              wrong: ["rests", "takes medicine"],
              distractorNotes: ["Nghỉ ngơi sau đó", "Uống thuốc sau"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The doctor says Minh is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ill — bác sĩ nói Minh bị ốm.",
              correct: "ill",
              wrong: ["rest", "hospital"],
              distractorNotes: ["Là hành động", "Là nơi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "I've got a headache — cấu trúc have got + triệu chứng.",
              correct: "I've got a headache.",
              wrong: ["I have got headache.", "I've got headache ill."],
              distractorNotes: ["Thiếu a", "Thừa từ ill"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-unwell-apply",
          title: "Apply: How Do You Feel?",
          instructions: "Fill in with ill, headache, medicine or rest.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I feel sick. I've got a [0]. | The doctor gives me [1]. | I should [2] at home because I am [3].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "headache; medicine; rest; ill — câu chuyện ốm điển hình.",
              template:
                "I feel sick. I've got a [0]. The doctor gives me [1]. I should [2] at home because I am [3].",
              correctAnswers: ["headache", "medicine", "rest", "ill"],
              acceptableAnswers: [
                ["headache", "Headache"],
                ["medicine", "Medicine"],
                ["rest", "Rest"],
                ["ill", "Ill"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-unwell-review",
          title: "Review: Illness Words Mix",
          instructions: "Choose the best illness word.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "When your head hurts, you've got a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Headache — đau đầu.",
              correct: "headache",
              wrong: ["stomach", "arm"],
              distractorNotes: ["Đau bụng", "Đau tay"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You are _____ so you shouldn't go to school.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ill — ốm thì nên nghỉ học.",
              correct: "ill",
              wrong: ["medicine", "doctor"],
              distractorNotes: ["Thuốc", "Người"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The doctor says: You should _____ and take medicine.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rest — nghỉ ngơi kết hợp uống thuốc.",
              correct: "rest",
              wrong: ["feel sick", "hospital"],
              distractorNotes: ["Mô tả cảm giác", "Là nơi"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
