/** Flyers U3 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-past-irregular",
      title: "Lesson 1: Past Simple — went, saw, had",
      learningObjective:
        "Use irregular past verbs went, saw and had in festival stories.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-past-learn",
          title: "Learn: went / saw / had",
          instructions: "Choose the correct past form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Last Tet we _____ to my grandparents' house.",
              skillTag: "grammar",
              topicTag,
              explanation: "Went — động từ đi bất quy tắc ở quá khứ.",
              correct: "went",
              wrong: ["goed", "go"],
              distractorNotes: ["Goed is wrong", "Present tense"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh _____ bright fireworks in the night sky.",
              skillTag: "grammar",
              topicTag,
              explanation: "Saw — quá khứ của see, không dùng seed.",
              correct: "saw",
              wrong: ["seed", "see"],
              distractorNotes: ["Wrong past form", "Present tense"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "We _____ a big family party with traditional food.",
              skillTag: "grammar",
              topicTag,
              explanation: "Had — quá khứ của have, không dùng haved.",
              correct: "had",
              wrong: ["haved", "have"],
              distractorNotes: ["Wrong past form", "Present tense"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh _____ to school in her ao dai costume.",
              skillTag: "grammar",
              topicTag,
              explanation: "Went — chuyển động trong quá khứ dùng went.",
              correct: "went",
              wrong: ["goed", "gone only"],
              distractorNotes: ["Goed is wrong", "Gone needs have/has"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-past-practice",
          title: "Practice: Complete Past Sentences",
          instructions: "Fill in each gap with went, saw or had.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: We [0] to the city centre. | They [1] a long parade. | Grandma [2] food ready.",
              skillTag: "grammar",
              topicTag,
              explanation: "went; saw; had — ba động từ bất quy tắc.",
              template:
                "We [0] to the city centre. They [1] a long parade. Grandma [2] food ready.",
              correctAnswers: ["went", "saw", "had"],
              acceptableAnswers: [
                ["went", "Went"],
                ["saw", "Saw", "seen"],
                ["had", "Had"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-past-check",
          title: "Check: Past Irregular Challenge",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "We went to the parade — went không có goed.",
              correct: "We went to the parade in the city centre.",
              wrong: [
                "We goed to the parade in the city centre.",
                "We go to the parade yesterday.",
              ],
              distractorNotes: ["Goed is wrong", "Yesterday needs past"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "I saw fireworks — saw là quá khứ của see.",
              correct: "I saw fireworks and clapped loudly.",
              wrong: [
                "I seed fireworks and clapped loudly.",
                "I see fireworks last night.",
              ],
              distractorNotes: ["Seed is wrong", "Last night needs saw"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Last year we _____ seats near the front of the parade.",
              skillTag: "grammar",
              topicTag,
              explanation: "Had — có chỗ ngồi = had seats.",
              correct: "had",
              wrong: ["haved", "have"],
              distractorNotes: ["Wrong past form", "Present with last year"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-past-apply",
          title: "Apply: Build Past Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Last Tet / we / went / to / the / parade.",
              skillTag: "grammar",
              topicTag,
              explanation: "Last Tet we went to the parade.",
              words: ["Last Tet", "we", "went", "to", "the", "parade."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Minh / saw / bright / fireworks / at / the / lake.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh saw bright fireworks at the lake.",
              words: ["Minh", "saw", "bright", "fireworks", "at", "the", "lake."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-past-review",
          title: "Review: went / saw / had Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "The family _____ early so they could see the national parade.",
              skillTag: "grammar",
              topicTag,
              explanation: "Went — đi sớm = went early.",
              correct: "went",
              wrong: ["goed", "goes"],
              distractorNotes: ["Goed is wrong", "Present -s form"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh _____ his school flag when the band passed.",
              skillTag: "grammar",
              topicTag,
              explanation: "Saw — nhìn thấy cờ = saw.",
              correct: "saw",
              wrong: ["seed", "sees"],
              distractorNotes: ["Wrong past", "Present tense"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "They had a wonderful holiday — had không có haved.",
              correct: "They had a wonderful holiday.",
              wrong: [
                "They haved a wonderful holiday.",
                "They have a wonderful holiday last year.",
              ],
              distractorNotes: ["Haved is wrong", "Last year needs had"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-when-clauses",
      title: "Lesson 2: When Clauses",
      learningObjective:
        "Use when-clauses to link events: When we arrived, ...",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-when-learn",
          title: "Learn: When we arrived, ...",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "_____ we arrived, we saw red decorations.",
              skillTag: "grammar",
              topicTag,
              explanation: "When — mệnh đề thời gian bắt đầu bằng When.",
              correct: "When",
              wrong: ["Where", "What"],
              distractorNotes: ["Place word", "Question word"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When we arrived, Grandma _____ food ready.",
              skillTag: "grammar",
              topicTag,
              explanation: "Had — quá khứ: đã chuẩn bị sẵn.",
              correct: "had",
              wrong: ["have", "has"],
              distractorNotes: ["Present base", "Present -s"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When the music started, Linh _____ to dance.",
              skillTag: "grammar",
              topicTag,
              explanation: "Began — bắt đầu múa (past); began hoặc started đều được.",
              correct: "began",
              wrong: ["begin", "begins"],
              distractorNotes: ["Present base", "Present -s"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "When we arrived, we saw food — cả hai động từ quá khứ.",
              correct: "When we arrived, we saw lucky money on the table.",
              wrong: [
                "When we arrive, we saw lucky money.",
                "When we arrived we saw lucky money.",
              ],
              distractorNotes: ["Arrive should be arrived", "Need comma after clause"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-when-practice",
          title: "Practice: Complete When Clauses",
          instructions: "Fill in each gap.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: [0] we arrived, we saw decorations. | When the parade finished, everyone [1] to the lake. | When Minh [2] the fireworks, he clapped.",
              skillTag: "grammar",
              topicTag,
              explanation: "When; went; saw — mệnh đề when + quá khứ.",
              template:
                "[0] we arrived, we saw decorations. When the parade finished, everyone [1] to the lake. When Minh [2] the fireworks, he clapped.",
              correctAnswers: ["When", "went", "saw"],
              acceptableAnswers: [
                ["When", "when"],
                ["went", "Went"],
                ["saw", "Saw"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-when-check",
          title: "Check: When Clause Challenge",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "When we arrived, we saw dancers — comma sau mệnh đề when.",
              correct: "When we arrived, we saw dancers in bright costumes.",
              wrong: [
                "When we arrived we see dancers.",
                "When we arrive, we saw dancers.",
              ],
              distractorNotes: ["See should be saw", "Arrive should be arrived"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When the band passed, Minh _____ his school flag.",
              skillTag: "grammar",
              topicTag,
              explanation: "Saw — quá khứ của see.",
              correct: "saw",
              wrong: ["see", "seed"],
              distractorNotes: ["Present tense", "Wrong past form"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "When we arrive at the gym, we will set up — tương lai trong hội thoại kế hoạch.",
              correct: "When we arrive, we will set up the stage first.",
              wrong: [
                "When we arrived, we will set up the stage.",
                "When we arrive, we set up the stage tomorrow.",
              ],
              distractorNotes: ["Mixed past + will awkward here", "Tomorrow needs will"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-when-apply",
          title: "Apply: Order When Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: When / we / arrived, / we / saw / fireworks.",
              skillTag: "grammar",
              topicTag,
              explanation: "When we arrived, we saw fireworks.",
              words: ["When", "we", "arrived,", "we", "saw", "fireworks."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: When / the / music / started, / Linh / began / to / dance.",
              skillTag: "grammar",
              topicTag,
              explanation: "When the music started, Linh began to dance.",
              words: ["When", "the", "music", "started,", "Linh", "began", "to", "dance."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-when-review",
          title: "Review: When Clauses Mix",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "When they _____ at school, they saw costumes and music.",
              skillTag: "grammar",
              topicTag,
              explanation: "Arrived — đến trường trong quá khứ.",
              correct: "arrived",
              wrong: ["arrive", "arrives"],
              distractorNotes: ["Present", "Third person -s"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which when-clause is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "When Linh saw the fireworks, she had a big smile.",
              correct: "When Linh saw the fireworks, she had a big smile.",
              wrong: [
                "When Linh see the fireworks, she had a smile.",
                "When Linh saw the fireworks she have a smile.",
              ],
              distractorNotes: ["See should be saw", "Have should be had"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When the parade _____, everyone went to the lake.",
              skillTag: "grammar",
              topicTag,
              explanation: "Finished — diễu hành kết thúc (quá khứ).",
              correct: "finished",
              wrong: ["finish", "finishes"],
              distractorNotes: ["Present base", "Present -s"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-past-when-mixed",
      title: "Lesson 3: Past and When — Mixed Review",
      learningObjective:
        "Choose went, saw, had and when-clauses correctly in festival sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-mixed-learn",
          title: "Learn: Past and When Together",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "When we arrived, we _____ decorations and lucky money.",
              skillTag: "grammar",
              topicTag,
              explanation: "Saw — nhìn thấy trong quá khứ.",
              correct: "saw",
              wrong: ["see", "seed"],
              distractorNotes: ["Present", "Wrong past"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "We _____ to the national parade and _____ a wonderful holiday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Went … had — hai động từ bất quy tắc.",
              correct: "went … had",
              wrong: ["goed … haved", "go … have"],
              distractorNotes: ["Wrong past forms", "Present tense"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When Minh _____ the fireworks, he clapped loudly.",
              skillTag: "grammar",
              topicTag,
              explanation: "Saw — thấy pháo hoa.",
              correct: "saw",
              wrong: ["see", "sees"],
              distractorNotes: ["Present base", "Present -s"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When we _____ at the gym last time, we saw a dance on stage.",
              skillTag: "grammar",
              topicTag,
              explanation: "Went — đi đến phòng gym.",
              correct: "went",
              wrong: ["goed", "go"],
              distractorNotes: ["Goed is wrong", "Present"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-practice",
          title: "Practice: Past or When",
          instructions: "Fill in each gap with the correct form.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: When we [0], Grandma had food ready. | We [1] to the parade. | When Linh [2] the music, she smiled.",
              skillTag: "grammar",
              topicTag,
              explanation: "arrived; went; heard/saw — hỗn hợp when + quá khứ.",
              template:
                "When we [0], Grandma had food ready. We [1] to the parade. When Linh [2] the music, she smiled.",
              correctAnswers: ["arrived", "went", "heard"],
              acceptableAnswers: [
                ["arrived", "Arrived"],
                ["went", "Went"],
                ["heard", "Heard", "saw", "Saw"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-check",
          title: "Check: Mixed Grammar Challenge",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "When we arrived, we saw fireworks — cả hai quá khứ.",
              correct: "When we arrived, we saw fireworks by the lake.",
              wrong: [
                "When we arrive, we saw fireworks by the lake.",
                "When we arrived we see fireworks by the lake.",
              ],
              distractorNotes: ["Arrive → arrived", "See → saw"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Last Tet we _____ home after the party and _____ a rest.",
              skillTag: "grammar",
              topicTag,
              explanation: "Went … had — về nhà và nghỉ ngơi.",
              correct: "went … had",
              wrong: ["goed … haved", "went … have"],
              distractorNotes: ["Wrong past forms", "Have should be had"],
              difficultyRating: 3,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "When they saw the parade, they went early next year too.",
              correct: "When they saw the parade, they clapped loudly.",
              wrong: [
                "When they see the parade, they clapped loudly.",
                "When they saw the parade, they clap loudly.",
              ],
              distractorNotes: ["See → saw", "Clap → clapped"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-apply",
          title: "Apply: Build Mixed Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: When / we / arrived, / we / had / a / family / party.",
              skillTag: "grammar",
              topicTag,
              explanation: "When we arrived, we had a family party.",
              words: ["When", "we", "arrived,", "we", "had", "a", "family", "party."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: We / went / to / the / parade / and / saw / fireworks.",
              skillTag: "grammar",
              topicTag,
              explanation: "We went to the parade and saw fireworks.",
              words: ["We", "went", "to", "the", "parade", "and", "saw", "fireworks."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-review",
          title: "Review: Past and When Mix",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "When we had the festival last year, Minh _____ a wonderful dance.",
              skillTag: "grammar",
              topicTag,
              explanation: "Saw — thấy múa trên sân khấu.",
              correct: "saw",
              wrong: ["seed", "see"],
              distractorNotes: ["Wrong past", "Present"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Dad said we _____ early so we could see the parade clearly.",
              skillTag: "grammar",
              topicTag,
              explanation: "Went — đi sớm.",
              correct: "went",
              wrong: ["goed", "goes"],
              distractorNotes: ["Goed wrong", "Present -s"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When the fireworks _____, everyone clapped.",
              skillTag: "grammar",
              topicTag,
              explanation: "Started — bắt đầu (quá khứ).",
              correct: "started",
              wrong: ["start", "starting"],
              distractorNotes: ["Present base", "Continuous form"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
