/** Flyers U3 — listening lessons (3 × 5 exercises). */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptSchoolFestival,
  listeningScriptNationalParade,
  listeningAnswerKeys,
  topicTag,
}) {
  const schoolFestival = listeningScriptSchoolFestival;
  const nationalParade = listeningScriptNationalParade;
  const keysSchool = listeningAnswerKeys.schoolFestival;
  const keysParade = listeningAnswerKeys.nationalParade;

  return [
    {
      slug: "listening-school-festival",
      title: "Lesson 1: School Festival Planning",
      learningObjective:
        "Listen to an extended dialogue about planning a school culture festival.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-school-learn",
          title: "Learn: Planning the Festival",
          instructions: "Listen to the teacher, Minh and Linh. Answer the questions.",
          sortOrder: 0,
          script: schoolFestival,
          answerKey: keysSchool,
          questions: [
            buildMcq({
              questionText: "What must the culture club plan?",
              skillTag: "listening",
              topicTag,
              explanation: "School culture festival for next month — lễ hội tháng tới.",
              correct: "Their school culture festival",
              wrong: ["A science exam", "An eco cleanup only"],
              distractorNotes: ["Not exam", "Eco from U2"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When is the festival?",
              skillTag: "listening",
              topicTag,
              explanation: "For next month — tháng tới.",
              correct: "Next month",
              wrong: ["Tomorrow morning", "Last year only"],
              distractorNotes: ["Not tomorrow", "Last year is past reference"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-practice",
          title: "Practice: Costumes and Stage",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: schoolFestival,
          answerKey: keysSchool,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "What will each class wear for the parade?",
              skillTag: "listening",
              topicTag,
              explanation: "Traditional costume — trang phục truyền thống.",
              correct: "A traditional costume",
              wrong: ["School uniform only", "Football kits"],
              distractorNotes: ["Costume specified", "Not sport"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Where did they go last time?",
              skillTag: "listening",
              topicTag,
              explanation: "We went to the gym — phòng gym.",
              correct: "The gym",
              wrong: ["Hoan Kiem Lake", "Grandparents' house"],
              distractorNotes: ["Lake from reading", "Family house"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-check",
          title: "Check: School Festival Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: schoolFestival,
          answerKey: keysSchool,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What did Minh see at last year's festival?",
              skillTag: "listening",
              topicTag,
              explanation: "A wonderful dance on stage — múa trên sân khấu.",
              correct: "A wonderful dance on stage",
              wrong: ["Only fireworks", "Plastic waste bins"],
              distractorNotes: ["Lights instead of fireworks", "Eco U2"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When they arrive, what will they set up first?",
              skillTag: "listening",
              topicTag,
              explanation: "Set up the stage first — dựng sân khấu trước.",
              correct: "The stage",
              wrong: ["Fireworks", "Lucky money tables"],
              distractorNotes: ["Maybe lights not fireworks", "Tet custom at home"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What happens after the show?",
              skillTag: "listening",
              topicTag,
              explanation: "Invite parents for a small party — tiệc nhỏ cho phụ huynh.",
              correct: "A small party for parents",
              wrong: ["A national parade", "Community cleanup"],
              distractorNotes: ["Parade is different dialogue", "Eco U2"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-school-apply",
          title: "Apply: Match Festival Planning Facts",
          instructions: "Listen again. Match each detail to the correct fact.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: schoolFestival },
          questions: [
            buildMatching({
              questionText: "Match each speaker or detail from the dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "Minh dance; Linh costumes; teacher gym; party after show.",
              pairs: [
                { left: "Minh", right: "saw a wonderful dance last year" },
                { left: "Linh", right: "asks about costumes and music" },
                { left: "Teacher", right: "says set up stage when they arrive" },
                { left: "After the show", right: "small party for parents" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-review",
          title: "Review: School Festival Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: schoolFestival,
          answerKey: keysSchool,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Where does the culture club meeting take place?",
              skillTag: "listening",
              topicTag,
              explanation: "School classroom after lessons — phòng học.",
              correct: "In a school classroom",
              wrong: ["At Hoan Kiem Lake", "In a hospital"],
              distractorNotes: ["Parade setting", "Not health"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Instead of fireworks they may use _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Maybe just colourful lights — đèn màu thay pháo hoa.",
              correct: "colourful lights",
              wrong: ["plastic bins", "science tests"],
              distractorNotes: ["Eco U2", "Not science"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-national-parade",
      title: "Lesson 2: National Parade",
      learningObjective:
        "Follow an extended family dialogue about watching a national parade.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-parade-learn",
          title: "Learn: The Parade Starts",
          instructions: "Listen to Dad, Minh and Linh. Answer the questions.",
          sortOrder: 0,
          script: nationalParade,
          answerKey: keysParade,
          questions: [
            buildMcq({
              questionText: "What is starting when Dad speaks?",
              skillTag: "listening",
              topicTag,
              explanation: "The national parade is starting — diễu hành quốc gia.",
              correct: "The national parade",
              wrong: ["A school exam", "A cooking class"],
              distractorNotes: ["Not exam", "Not cooking"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When they arrived, what did they see?",
              skillTag: "listening",
              topicTag,
              explanation: "Dancers in bright costumes — vũ công trang phục sặc sỡ.",
              correct: "Dancers in bright costumes",
              wrong: ["Only fireworks", "Empty streets"],
              distractorNotes: ["Fireworks tonight", "Parade is full"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-parade-practice",
          title: "Practice: Music and Flags",
          instructions: "Listen again. Focus on music and the parade.",
          sortOrder: 1,
          script: nationalParade,
          answerKey: keysParade,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "What does Linh love in the parade?",
              skillTag: "listening",
              topicTag,
              explanation: "I love the music — âm nhạc.",
              correct: "The music",
              wrong: ["The homework", "The recycling bins"],
              distractorNotes: ["Not school work", "Eco U2"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What did Minh see when the band passed?",
              skillTag: "listening",
              topicTag,
              explanation: "Our school flag in the parade — cờ trường.",
              correct: "Their school flag",
              wrong: ["A birthday cake", "Plastic waste"],
              distractorNotes: ["Not party food", "Eco U2"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-parade-check",
          title: "Check: Parade Dialogue Details",
          instructions: "Listen to the full conversation again.",
          sortOrder: 2,
          script: nationalParade,
          answerKey: keysParade,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Why did they go early today?",
              skillTag: "listening",
              topicTag,
              explanation: "So we can see everything clearly — nhìn rõ hơn.",
              correct: "To see everything clearly",
              wrong: ["To clean the house", "To write a school project"],
              distractorNotes: ["Tet custom first", "Project later"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What will they do tonight?",
              skillTag: "listening",
              topicTag,
              explanation: "Watch fireworks by the lake — pháo hoa ven hồ.",
              correct: "Watch fireworks by the lake",
              wrong: ["Plant trees at school", "Recycle paper only"],
              distractorNotes: ["Eco U2 trees", "Eco U2 recycle"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Watching fireworks is described as a _____ custom.",
              skillTag: "listening",
              topicTag,
              explanation: "It is a Tet custom — phong tục Tết.",
              correct: "Tet",
              wrong: ["football", "science"],
              distractorNotes: ["Not sport", "Not science"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-parade-apply",
          title: "Apply: Order the Parade Day",
          instructions: "Put the ideas in the order they are discussed.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          content: { script: nationalParade },
          questions: [
            buildMcq({
              questionText:
                "Correct order: (1) fireworks tonight (2) parade starts (3) ice cream after parade",
              skillTag: "listening",
              topicTag,
              explanation: "Parade starts → ice cream → fireworks tonight.",
              correct: "2 → 3 → 1",
              wrong: ["1 → 2 → 3", "3 → 1 → 2"],
              distractorNotes: ["Fireworks is last", "Ice cream not first"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-parade-review",
          title: "Review: Parade Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: nationalParade,
          answerKey: keysParade,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Where does the parade dialogue take place?",
              skillTag: "listening",
              topicTag,
              explanation: "City street near Hoan Kiem Lake — phố gần hồ Gươm.",
              correct: "City street near Hoan Kiem Lake",
              wrong: ["School classroom", "Grandma's kitchen"],
              distractorNotes: ["School festival meeting", "Family party place"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh says festivals bring the whole _____ together.",
              skillTag: "listening",
              topicTag,
              explanation: "Whole city together — cả thành phố.",
              correct: "city",
              wrong: ["classroom", "recycling bin"],
              distractorNotes: ["Too small", "Eco U2"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-festival-review",
      title: "Lesson 3: Mixed Extended Dialogues",
      learningObjective:
        "Extract multiple pieces of information across two festival dialogues.",
      estimatedMinutes: 22,
      exercises: [
        buildListeningExercise({
          slug: "listening-review-learn",
          title: "Learn: School Festival Reminder",
          instructions: "Listen to the school festival dialogue again.",
          sortOrder: 0,
          script: schoolFestival,
          answerKey: keysSchool,
          questions: [
            buildMcq({
              questionText: "Who leads the culture club meeting?",
              skillTag: "listening",
              topicTag,
              explanation: "Teacher welcomes and plans — cô giáo.",
              correct: "The teacher",
              wrong: ["Minh's dad", "A doctor"],
              distractorNotes: ["Dad in parade dialogue", "Not health"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh asks if they can celebrate with _____ and music.",
              skillTag: "listening",
              topicTag,
              explanation: "National traditions with costumes and music — trang phục.",
              correct: "costumes",
              wrong: ["plastic waste", "science books"],
              distractorNotes: ["Eco U2", "Not science"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-practice",
          title: "Practice: Parade Reminder",
          instructions: "Listen to the national parade dialogue again.",
          sortOrder: 1,
          script: nationalParade,
          answerKey: keysParade,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "What did they have last year near the front?",
              skillTag: "listening",
              topicTag,
              explanation: "Seats near the front — chỗ ngồi gần phía trước.",
              correct: "Seats near the front",
              wrong: ["No parade at all", "Only online music"],
              distractorNotes: ["Parade happened", "Live parade now"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "After the parade they can celebrate with _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Celebrate with ice cream — kem.",
              correct: "ice cream",
              wrong: ["homework", "recycling bins"],
              distractorNotes: ["Not school work", "Eco U2"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-check",
          title: "Check: Mixed Festival Listening",
          instructions: "Listen to the parade dialogue. Harder questions.",
          sortOrder: 2,
          script: nationalParade,
          answerKey: keysParade,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which detail is ONLY in the school festival dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Set up the stage in the gym — chỉ hội thoại trường.",
              correct: "Set up the stage in the gym",
              wrong: ["School flag in parade", "Fireworks tonight"],
              distractorNotes: ["Parade dialogue", "Parade dialogue tonight"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Both dialogues mention _____ traditions or celebrations.",
              skillTag: "listening",
              topicTag,
              explanation: "National/culture traditions and festivals — văn hóa lễ hội.",
              correct: "culture and festival",
              wrong: ["plastic recycling only", "who and which clauses only"],
              distractorNotes: ["Eco U2 focus", "Flyers U1 grammar"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-review-apply",
          title: "Apply: Match Dialogue to Fact",
          instructions: "Listen, then match each fact to the correct dialogue.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: nationalParade },
          questions: [
            buildMatching({
              questionText: "Match facts to School festival or Parade dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "School: stage, party; Parade: flag, fireworks, ice cream.",
              pairs: [
                { left: "Small party for parents", right: "School festival dialogue" },
                { left: "School flag in the parade", right: "National parade dialogue" },
                { left: "Wonderful dance last year", right: "School festival dialogue" },
                { left: "Fireworks tonight by the lake", right: "National parade dialogue" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-final",
          title: "Review: Both Dialogues Mix",
          instructions: "Listen to the school festival dialogue. Final review.",
          sortOrder: 4,
          script: schoolFestival,
          answerKey: keysSchool,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which word appears in BOTH dialogues?",
              skillTag: "listening",
              topicTag,
              explanation: "Music in both — nhạc ở cả hai.",
              correct: "music",
              wrong: ["ice cream only", "recycling only"],
              distractorNotes: ["Parade only", "Eco U2 only"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "In BOTH dialogues, speakers use past verbs like went, saw or had.",
              skillTag: "listening",
              topicTag,
              explanation: "Minh: When we had… I saw…; Parade: We went… I saw… — đúng.",
              correct: "True",
              wrong: ["False — only future tense", "False — no past verbs"],
              distractorNotes: ["Past verbs appear", "Past verbs appear"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
