/** Flyers U3 — reading lessons (3 × 5 exercises). */

export function readingLessons({
  buildMcq,
  buildGapFill,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMinhFestival,
  topicTag,
}) {
  const passage = passageMinhFestival;

  return [
    {
      slug: "reading-chronological-links",
      title: "Lesson 1: Understand Chronological Links",
      learningObjective:
        "Follow chronological links (first, when, then, after) in a festival text.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-chrono-learn",
          title: "Learn: Order of Events",
          instructions: "Read the passage. Answer the questions about order.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What did Minh and Linh do FIRST before going to grandparents'?",
              skillTag: "reading",
              topicTag,
              explanation: "First they helped Mum clean the house — câu đầu có First.",
              correct: "Helped Mum clean the house",
              wrong: ["Watched fireworks", "Wrote a school project"],
              distractorNotes: ["Happens at night later", "Happens at end"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When they arrived at grandparents' house, what did they see?",
              skillTag: "reading",
              topicTag,
              explanation: "Red decorations and lucky money — mệnh đề When we arrived.",
              correct: "Red decorations and lucky money",
              wrong: ["Only fireworks", "A school stage"],
              distractorNotes: ["Fireworks later at lake", "School not at grandparents"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-chrono-practice",
          title: "Practice: Then and After",
          instructions: "Read again. Focus on then and after.",
          sortOrder: 1,
          passage,
          difficulty: 0.25,
          questions: [
            buildMcq({
              questionText: "What happened AFTER the parade finished?",
              skillTag: "reading",
              topicTag,
              explanation: "Everyone went to Hoan Kiem Lake — sau diễu hành.",
              correct: "They went to Hoan Kiem Lake",
              wrong: ["They cleaned the house", "They arrived at grandparents'"],
              distractorNotes: ["Happens first", "Before parade"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "In the AFTERNOON the family went to _____.",
              skillTag: "reading",
              topicTag,
              explanation: "City centre — đoạn In the afternoon.",
              correct: "the city centre",
              wrong: ["school only", "grandparents' kitchen only"],
              distractorNotes: ["School project at end", "Morning at grandparents"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-chrono-check",
          title: "Check: Chronological Links",
          instructions: "Read carefully. These questions need thinking about order.",
          sortOrder: 2,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Which is the correct order of events?",
              skillTag: "reading",
              topicTag,
              explanation: "Clean → grandparents → parade → fireworks → school project.",
              correct: "Clean house → grandparents → parade → fireworks → write for school",
              wrong: [
                "Fireworks → clean house → parade",
                "School project → parade → clean house",
              ],
              distractorNotes: ["Fireworks not first", "Project at end not start"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When did Minh see fireworks?",
              skillTag: "reading",
              topicTag,
              explanation: "After going to the lake when parade finished — ban đêm.",
              correct: "After the parade, at the lake at night",
              wrong: ["Before cleaning the house", "At grandparents' in the morning only"],
              distractorNotes: ["Too early", "Morning was party food"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which linking word introduces what Minh saw at grandparents'?",
              skillTag: "reading",
              topicTag,
              explanation: "When they arrived — mệnh đề thời gian When.",
              correct: "When",
              wrong: ["Because", "Although"],
              distractorNotes: ["Reason word", "Contrast word"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-chrono-apply",
          title: "Apply: Match Story Order",
          instructions: "Use the passage. Match each time link to what happens.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each chronological link to the event.",
              skillTag: "reading",
              topicTag,
              explanation: "First clean; When arrived see decorations; After parade lake; At end write.",
              pairs: [
                { left: "First", right: "Minh and Linh clean the house" },
                { left: "When they arrived", right: "they saw decorations and lucky money" },
                { left: "In the afternoon", right: "they watched a parade" },
                { left: "When the parade finished", right: "they went to the lake for fireworks" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-chrono-review",
          title: "Review: Chronological Mix",
          instructions: "Read the passage one more time. Mixed review of order.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What happened immediately BEFORE the family went to the city centre?",
              skillTag: "reading",
              topicTag,
              explanation: "Family party at grandparents' with traditional food — buổi sáng/trưa.",
              correct: "A family party at grandparents' house",
              wrong: ["Writing the school project", "Only watching fireworks"],
              distractorNotes: ["Project at very end", "Fireworks after parade"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "At the END of the holiday Minh _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Felt happy and wrote about the festival — đoạn cuối.",
              correct: "felt happy and wrote about the festival",
              wrong: ["cleaned the house again", "went to school in costume only"],
              distractorNotes: ["Cleaning was first", "Costume worn earlier"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-festival-narrative",
      title: "Lesson 2: Festival Narrative",
      learningObjective:
        "Understand the main events and characters in Minh's Tet holiday story.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-narrative-learn",
          title: "Learn: Minh's Tet Story",
          instructions: "Read the passage. Answer about the story.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "Who is the text mainly about?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh is eleven and lives in Hanoi — nhân vật chính.",
              correct: "Minh and his family during Tet",
              wrong: ["Only the school teacher", "A doctor in a hospital"],
              distractorNotes: ["Teacher not main focus", "Not health unit"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What special holiday is the text about?",
              skillTag: "reading",
              topicTag,
              explanation: "Last Tet was a special national holiday — Tết.",
              correct: "Tet (Vietnamese New Year)",
              wrong: ["Summer sports day", "A science exam"],
              distractorNotes: ["Not sports", "Not exam"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-narrative-practice",
          title: "Practice: People and Places",
          instructions: "Read again. Choose the correct statement.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Who helped Mum clean the house?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh and his sister Linh — câu mở đầu.",
              correct: "Minh and Linh",
              wrong: ["Only Dad", "Only Grandma"],
              distractorNotes: ["Dad not mentioned cleaning", "Grandma at her house later"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Where did the family watch the parade?",
              skillTag: "reading",
              topicTag,
              explanation: "City centre — trung tâm thành phố.",
              correct: "In the city centre",
              wrong: ["Only at school", "In the ocean"],
              distractorNotes: ["School project later", "Ocean from U2 only"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-narrative-check",
          title: "Check: Narrative Details",
          instructions: "Find the answers in the text.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "What costume did Minh wear?",
              skillTag: "reading",
              topicTag,
              explanation: "Colourful ao dai costume — trang phục áo dài.",
              correct: "A colourful ao dai",
              wrong: ["A football uniform", "A doctor's coat"],
              distractorNotes: ["Not sport", "Not health"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What was in the parade besides dancers?",
              skillTag: "reading",
              topicTag,
              explanation: "Music and dance groups — nhạc và múa.",
              correct: "Music and dance groups",
              wrong: ["Only plastic waste", "Science experiments"],
              distractorNotes: ["Eco U2 topic", "Not science unit"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who had prepared food for the family party?",
              skillTag: "reading",
              topicTag,
              explanation: "Grandma had prepared a big family party — bà nấu.",
              correct: "Grandma",
              wrong: ["The eco club teacher", "Minh's pen friend"],
              distractorNotes: ["School club from listening", "Not in text"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-narrative-apply",
          title: "Apply: Complete from the Text",
          instructions: "Fill in the gaps using words from the passage.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh wore a colourful ao dai [0]. | They watched a long [1] with music. | They saw bright [2] in the night sky.",
              skillTag: "reading",
              topicTag,
              explanation: "costume; parade; fireworks — chi tiết câu chuyện.",
              template:
                "Minh wore a colourful ao dai [0]. They watched a long [1] with music. They saw bright [2] in the night sky.",
              correctAnswers: ["costume", "parade", "fireworks"],
              acceptableAnswers: [
                ["costume", "Costume"],
                ["parade", "Parade"],
                ["fireworks", "Fireworks"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-narrative-review",
          title: "Review: Festival Narrative Mix",
          instructions: "Find the answers in the text again.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Why did Minh write about the festival?",
              skillTag: "reading",
              topicTag,
              explanation: "For his school project — cuối bài đọc.",
              correct: "For his school project",
              wrong: ["To sell costumes", "To invite guests to a football match"],
              distractorNotes: ["Not selling", "Not sport"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What did everyone do when they saw the fireworks?",
              skillTag: "reading",
              topicTag,
              explanation: "They clapped loudly — vỗ tay.",
              correct: "They clapped loudly",
              wrong: ["They went home immediately", "They cleaned the house"],
              distractorNotes: ["Still at lake", "Cleaning was first event"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-detail-inference",
      title: "Lesson 3: Detail and Inference",
      learningObjective:
        "Find specific details and make simple inferences from the festival text.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-inference-learn",
          title: "Learn: Customs and Traditions",
          instructions: "Read the passage. Think about customs.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "Cleaning the house before Tet is described as _____.",
              skillTag: "reading",
              topicTag,
              explanation: "An old custom before every festival — phong tục cũ.",
              correct: "an old custom",
              wrong: ["a new school rule", "a science experiment"],
              distractorNotes: ["Not school rule", "Not science"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Wearing ao dai is called an important _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Important tradition in Vietnam — truyền thống.",
              correct: "tradition",
              wrong: ["pollution problem", "recycling bin"],
              distractorNotes: ["Eco U2", "Eco U2"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-inference-practice",
          title: "Practice: Infer Feelings and Reasons",
          instructions: "Read again. Choose the best inference.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Why did Minh feel happy at the end?",
              skillTag: "reading",
              topicTag,
              explanation: "Wonderful holiday with family and festival events — suy luận tích cực.",
              correct: "He enjoyed Tet with family traditions and celebrations",
              wrong: ["He failed his school project", "He did not see the parade"],
              distractorNotes: ["He wrote project successfully", "He watched parade"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Why does Minh tell his class that customs matter?",
              skillTag: "reading",
              topicTag,
              explanation: "Text says he told class why customs and traditions matter — kết nối văn hóa.",
              correct: "To explain why culture and traditions are important",
              wrong: ["To ask for plastic waste", "To sell fireworks tickets"],
              distractorNotes: ["Eco topic", "Not selling"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-inference-check",
          title: "Check: Detail and Inference",
          instructions: "Think carefully about details not stated directly.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Which detail is NOT in the text?",
              skillTag: "reading",
              topicTag,
              explanation: "Text never mentions ice cream — không có kem.",
              correct: "Minh ate ice cream after the parade.",
              wrong: [
                "Grandma made traditional food.",
                "Minh wore ao dai.",
              ],
              distractorNotes: ["True in text", "True in text"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We can infer that Tet is a _____ holiday for Minh's family.",
              skillTag: "reading",
              topicTag,
              explanation: "Special national holiday — quan trọng với gia đình.",
              correct: "important national",
              wrong: ["boring ordinary", "short unimportant"],
              distractorNotes: ["Opposite of happy ending", "Text says long holiday feel"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The fireworks happened near _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Hoan Kiem Lake — hồ Gươm.",
              correct: "Hoan Kiem Lake",
              wrong: ["West Lake only", "Minh's classroom"],
              distractorNotes: ["West Lake from U2 cleanup", "School later for project"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-inference-apply",
          title: "Apply: Match Details to Meaning",
          instructions: "Match each detail to what it shows.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each detail to what it tells us.",
              skillTag: "reading",
              topicTag,
              explanation: "Lucky money custom; ao dai tradition; parade celebration; project sharing.",
              pairs: [
                { left: "Lucky money on the table", right: "a Tet custom at grandparents'" },
                { left: "Ao dai costume", right: "an important Vietnamese tradition" },
                { left: "Parade with music", right: "public celebration in the city" },
                { left: "School project", right: "Minh shares festival experience with class" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-inference-review",
          title: "Review: Detail and Inference Mix",
          instructions: "Read and answer about details and inference.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "How old is Minh?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh is eleven — câu mở đầu.",
              correct: "Eleven",
              wrong: ["Nine", "Thirteen"],
              distractorNotes: ["Movers age", "Not in text"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence best summarises the text?",
              skillTag: "reading",
              topicTag,
              explanation: "Tet holiday with customs, parade and fireworks — tóm tắt toàn bài.",
              correct: "Minh's family celebrates Tet with customs, a parade and fireworks.",
              wrong: [
                "Minh recycles plastic at an eco club.",
                "Minh visits cousins in Da Nang for a birthday.",
              ],
              distractorNotes: ["Flyers U2", "Flyers U1"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
