/** KET U2 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-simple-vs-continuous",
      title: "Lesson 1: Present Simple vs Present Continuous",
      learningObjective:
        "Choose present simple for habits and present continuous for temporary work situations.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "grammar-tenses-learn",
          title: "Learn: Choose the Correct Form",
          instructions: "Choose the best verb form for each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "I _____ in a bookshop every Saturday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Every Saturday = thói quen → present simple: work.",
              correct: "work",
              wrong: ["am working", "worked"],
              distractorNotes: ["Hành động tạm thời", "Quá khứ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "She _____ for an interview right now.",
              skillTag: "grammar",
              topicTag,
              explanation: "Right now = đang diễn ra → is preparing.",
              correct: "is preparing",
              wrong: ["prepares", "prepared"],
              distractorNotes: ["Thói quen", "Quá khứ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "They _____ hiring new staff at the moment.",
              skillTag: "grammar",
              topicTag,
              explanation: "At the moment → are hiring (present continuous).",
              correct: "are",
              wrong: ["is", "do"],
              distractorNotes: ["Sai chủ ngữ số nhiều", "Sai trợ động từ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "My colleague usually _____ his shift at nine.",
              skillTag: "grammar",
              topicTag,
              explanation: "Usually = thói quen → starts (present simple).",
              correct: "starts",
              wrong: ["is starting", "start"],
              distractorNotes: ["Không phải 'bây giờ'", "Thiếu -s với he"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-tenses-practice",
          title: "Practice: Complete the Grammar",
          instructions: "Fill in each gap with the correct form.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I [0] in a bookshop. | She [1] an interview today. | They [2] hiring staff this month.",
              skillTag: "grammar",
              topicTag,
              explanation: "work; is having; are — simple vs continuous.",
              template:
                "I [0] in a bookshop. She [1] an interview today. They [2] hiring staff this month.",
              correctAnswers: ["work", "is having", "are"],
              acceptableAnswers: [
                ["work", "Work"],
                ["is having", "Is having"],
                ["are", "Are"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-tenses-check",
          title: "Check: Tense Challenge",
          instructions: "Choose the correct answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "My employer usually _____ me on the last Friday of the month.",
              skillTag: "grammar",
              topicTag,
              explanation: "Usually = thói quen → pays (present simple).",
              correct: "pays",
              wrong: ["is paying", "pay"],
              distractorNotes: ["Đang diễn ra", "Sai với my employer"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Tom _____ as a waiter, but this month he is training to be a manager.",
              skillTag: "grammar",
              topicTag,
              explanation: "Việc thường xuyên → works; tháng này → is training.",
              correct: "works",
              wrong: ["is working", "worked"],
              distractorNotes: ["Nghe như chỉ bây giờ", "Quá khứ"],
              difficultyRating: 3,
            }),
            buildMcq({
              questionText: "Which sentence is NOT correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "I am work — thiếu -ing sau am.",
              correct: "I am work in a café.",
              wrong: [
                "I work in a café every Saturday.",
                "She is working on her CV now.",
              ],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-tenses-apply",
          title: "Apply: Build the Sentence",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: She / is / preparing / for / an interview / now.",
              skillTag: "grammar",
              topicTag,
              explanation: "She is preparing for an interview now.",
              words: ["She", "is", "preparing", "for", "an interview", "now."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: My colleague / usually / starts / his shift / at nine.",
              skillTag: "grammar",
              topicTag,
              explanation: "My colleague usually starts his shift at nine.",
              words: ["My colleague", "usually", "starts", "his shift", "at nine."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-tenses-review",
          title: "Review: Simple vs Continuous Mix",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Linh _____ extra shifts this week because the shop is busy.",
              skillTag: "grammar",
              topicTag,
              explanation: "This week = tạm thời → is working.",
              correct: "is working",
              wrong: ["works", "worked"],
              distractorNotes: ["Thói quen", "Quá khứ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The manager _____ three people every month.",
              skillTag: "grammar",
              topicTag,
              explanation: "Every month = thói quen → interviews.",
              correct: "interviews",
              wrong: ["is interviewing", "interview"],
              distractorNotes: ["Chỉ bây giờ", "Thiếu -s"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-wh-questions",
      title: "Lesson 2: Wh- Questions",
      learningObjective:
        "Form Wh- questions in present simple and present continuous about work.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "grammar-wh-learn",
          title: "Learn: Wh- Question Words",
          instructions: "Choose the correct Wh- word or auxiliary.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "_____ does your shift start?",
              skillTag: "grammar",
              topicTag,
              explanation: "When — hỏi thời gian ca làm.",
              correct: "When",
              wrong: ["What", "Who"],
              distractorNotes: ["Hỏi vật", "Hỏi người"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Where _____ you work?",
              skillTag: "grammar",
              topicTag,
              explanation: "Where do you work? — present simple với you.",
              correct: "do",
              wrong: ["are", "does"],
              distractorNotes: ["Cần -ing", "Sai ngôi"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What _____ your colleague doing at the moment?",
              skillTag: "grammar",
              topicTag,
              explanation: "What is your colleague doing? — present continuous.",
              correct: "is",
              wrong: ["does", "do"],
              distractorNotes: ["Present simple", "Sai ngôi"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-wh-practice",
          title: "Practice: Complete Wh- Questions",
          instructions: "Fill in the gaps.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: [0] do you work? | [1] is your salary? | [2] are you working extra shifts?",
              skillTag: "grammar",
              topicTag,
              explanation: "Where; How much; Why — Wh- words cho công việc.",
              template:
                "[0] do you work? [1] is your salary? [2] are you working extra shifts?",
              correctAnswers: ["Where", "How much", "Why"],
              acceptableAnswers: [
                ["Where", "where"],
                ["How much", "how much"],
                ["Why", "why"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-wh-check",
          title: "Check: Wh- Question Challenge",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "_____ are you working extra shifts this week?",
              skillTag: "grammar",
              topicTag,
              explanation: "Why — hỏi lý do làm ca thêm.",
              correct: "Why",
              wrong: ["When", "Who"],
              distractorNotes: ["Hỏi thời gian", "Hỏi người"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How many hours _____ you work each week?",
              skillTag: "grammar",
              topicTag,
              explanation: "Do you work — present simple question với you.",
              correct: "do",
              wrong: ["are", "does"],
              distractorNotes: ["Cần -ing", "Sai ngôi"],
              difficultyRating: 3,
            }),
            buildMcq({
              questionText: "Which question is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Where do you work? — đúng trật tự câu hỏi.",
              correct: "Where do you work?",
              wrong: ["Where you work?", "Where do you working?"],
              distractorNotes: ["Thiếu do", "Sai dạng động từ"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-wh-apply",
          title: "Apply: Order the Question",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Where / do / you / work?",
              skillTag: "grammar",
              topicTag,
              explanation: "Where do you work?",
              words: ["Where", "do", "you", "work?"],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: What / is / the manager / doing / now?",
              skillTag: "grammar",
              topicTag,
              explanation: "What is the manager doing now?",
              words: ["What", "is", "the manager", "doing", "now?"],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-wh-review",
          title: "Review: Wh- Questions Mix",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "_____ job do you want?",
              skillTag: "grammar",
              topicTag,
              explanation: "What job do you want? — What + danh từ.",
              correct: "What",
              wrong: ["When", "How much"],
              distractorNotes: ["Hỏi thời gian", "Hỏi tiền"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who _____ the manager interviewing today?",
              skillTag: "grammar",
              topicTag,
              explanation: "Who is the manager interviewing? — present continuous.",
              correct: "is",
              wrong: ["does", "do"],
              distractorNotes: ["Present simple", "Sai trợ động từ"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-work-review",
      title: "Lesson 3: Mixed Grammar Review",
      learningObjective:
        "Mix present simple, present continuous and Wh- questions in work contexts.",
      estimatedMinutes: 23,
      exercises: [
        buildExercise({
          slug: "grammar-mixed-learn",
          title: "Learn: Choose the Correct Form",
          instructions: "Pick the best grammar for each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Linh _____ for an interview this week because she _____ a part-time job.",
              skillTag: "grammar",
              topicTag,
              explanation: "Is preparing (bây giờ); wants (mong muốn chung).",
              correct: "is preparing … wants",
              wrong: ["prepares … is wanting", "is preparing … is wanting"],
              distractorNotes: ["Sai thì", "Want hiếm dùng continuous"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ does your employer pay you?",
              skillTag: "grammar",
              topicTag,
              explanation: "When — hỏi thời gian trả lương.",
              correct: "When",
              wrong: ["What", "Who"],
              distractorNotes: ["Hỏi vật", "Hỏi người"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-practice",
          title: "Practice: Complete the Paragraph",
          instructions: "Fill in the gaps.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I [0] in a bookshop every Saturday. | [1] do you work? | She [2] training with a new colleague this week.",
              skillTag: "grammar",
              topicTag,
              explanation: "work; Where; is — mixed grammar.",
              template:
                "I [0] in a bookshop every Saturday. [1] do you work? She [2] training with a new colleague this week.",
              correctAnswers: ["work", "Where", "is"],
              acceptableAnswers: [
                ["work", "Work"],
                ["Where", "where"],
                ["is", "Is"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-check",
          title: "Check: Mixed Grammar Challenge",
          instructions: "Harder questions — choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is NOT correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "What she is doing? — sai trật tự.",
              correct: "What she is doing now?",
              wrong: [
                "Where do you work?",
                "She is preparing for an interview.",
              ],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The manager usually _____ interviews on Monday mornings.",
              skillTag: "grammar",
              topicTag,
              explanation: "Does — present simple với he/she + usually.",
              correct: "does",
              wrong: ["is", "do"],
              distractorNotes: ["Continuous", "Sai ngôi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Why _____ they hiring new staff at the moment?",
              skillTag: "grammar",
              topicTag,
              explanation: "Are they hiring — present continuous question.",
              correct: "are",
              wrong: ["do", "is"],
              distractorNotes: ["Cần base verb", "Sai số"],
              difficultyRating: 3,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-apply",
          title: "Apply: Build Work Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: How much / salary / do / you / get?",
              skillTag: "grammar",
              topicTag,
              explanation: "How much salary do you get?",
              words: ["How much", "salary", "do", "you", "get?"],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: I / am / working / the evening shift / on Fridays.",
              skillTag: "grammar",
              topicTag,
              explanation: "I am working the evening shift on Fridays.",
              words: ["I", "am", "working", "the evening shift", "on Fridays."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-review",
          title: "Review: Full Grammar Mix",
          instructions: "Final grammar review.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Tom _____ in a bookshop for six months. (past experience, now finished)",
              skillTag: "grammar",
              topicTag,
              explanation: "Worked — quá khứ đơn cho kinh nghiệm đã qua.",
              correct: "worked",
              wrong: ["works", "is working"],
              distractorNotes: ["Hiện tại", "Đang làm"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "_____ is your colleague doing right now?",
              skillTag: "grammar",
              topicTag,
              explanation: "What is your colleague doing? — Wh- + continuous.",
              correct: "What",
              wrong: ["When", "How much"],
              distractorNotes: ["Hỏi thời gian", "Hỏi tiền"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
