/** KET U2 — listening lessons (3 × 5 exercises). Job interview + career/shift talk. */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptJobInterview,
  listeningScriptShiftTalk,
  listeningAnswerKeys,
  topicTag,
}) {
  const jobInterview = listeningScriptJobInterview;
  const shiftTalk = listeningScriptShiftTalk;
  const keysInterview = listeningAnswerKeys.jobInterview;
  const keysShift = listeningAnswerKeys.shiftTalk;

  return [
    {
      slug: "listening-job-interview",
      title: "Lesson 1: Job Interview",
      learningObjective:
        "Listen to a job interview and extract factual information about experience, salary and shifts.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-interview-learn",
          title: "Learn: Café Interview",
          instructions: "Listen to the interview. Answer the questions.",
          sortOrder: 0,
          script: jobInterview,
          answerKey: keysInterview,
          questions: [
            buildMcq({
              questionText: "What job did Tom apply for?",
              skillTag: "listening",
              topicTag,
              explanation: "Tom applied for the part-time waiter job.",
              correct: "Part-time waiter",
              wrong: ["Shop manager", "Bookshop assistant"],
              distractorNotes: ["Ms Lee is manager", "Past job, not application"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Where did Tom get his work experience?",
              skillTag: "listening",
              topicTag,
              explanation: "He worked in a bookshop for six months.",
              correct: "In a bookshop",
              wrong: ["In a café", "In an office"],
              distractorNotes: ["Interview at café", "Not mentioned"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-interview-practice",
          title: "Practice: More from the Interview",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: jobInterview,
          answerKey: keysInterview,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "What is the salary?",
              skillTag: "listening",
              topicTag,
              explanation: "The salary is eight pounds an hour.",
              correct: "Eight pounds an hour",
              wrong: ["Ten pounds an hour", "Minimum wage only"],
              distractorNotes: ["Not stated", "Advert says above minimum"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When can Tom work?",
              skillTag: "listening",
              topicTag,
              explanation: "He can work the evening shift on Fridays.",
              correct: "Friday evenings",
              wrong: ["Saturday mornings", "Every weekday"],
              distractorNotes: ["From job advert", "He is studying"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-interview-check",
          title: "Check: Interview Listening Challenge",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: jobInterview,
          answerKey: keysInterview,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Who will email Tom about the start date?",
              skillTag: "listening",
              topicTag,
              explanation: "The employer will email you next Monday.",
              correct: "The employer",
              wrong: ["Tom's colleague", "Ms Lee personally tonight"],
              distractorNotes: ["Colleagues mentioned differently", "Next Monday, not tonight"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Tom says his colleagues were very _____.",
              skillTag: "listening",
              topicTag,
              explanation: "My colleagues were very helpful — bookshop experience.",
              correct: "helpful",
              wrong: ["expensive", "retired"],
              distractorNotes: ["Không liên quan", "Sai nghĩa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Tom is _____ now, but free on Friday evenings.",
              skillTag: "listening",
              topicTag,
              explanation: "I am studying now — present continuous.",
              correct: "studying",
              wrong: ["retiring", "managing"],
              distractorNotes: ["Không nhắc", "Ms Lee is manager"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-interview-apply",
          title: "Apply: Match What You Heard",
          instructions: "Listen again. Match each item to the correct detail.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: jobInterview },
          questions: [
            buildMatching({
              questionText: "Match each item from the café interview.",
              skillTag: "listening",
              topicTag,
              explanation: "Bookshop six months; eight pounds; Friday evenings.",
              pairs: [
                { left: "Tom's past job", right: "Bookshop for six months" },
                { left: "Salary offered", right: "Eight pounds an hour" },
                { left: "Shift discussed", right: "Friday evenings" },
                { left: "Start date news", right: "Email next Monday" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-interview-review",
          title: "Review: Interview Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: jobInterview,
          answerKey: keysInterview,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "The interview takes place at a _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Job Interview at a Café — setting in script title.",
              correct: "café",
              wrong: ["bookshop", "hospital"],
              distractorNotes: ["Tom's past job", "Career advice unit"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Ms Lee asks about Tom's _____ with customers.",
              skillTag: "listening",
              topicTag,
              explanation: "Tell me about your experience — have you worked with customers?",
              correct: "experience",
              wrong: ["salary", "retirement"],
              distractorNotes: ["Salary asked later", "Not mentioned"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-career-advice",
      title: "Lesson 2: Career Advice",
      learningObjective:
        "Listen to a career advice call and extract facts about training, experience and part-time work.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-career-learn",
          title: "Learn: Linh's Career Call",
          instructions: "Listen to the phone call. Answer the questions.",
          sortOrder: 0,
          script: shiftTalk,
          answerKey: keysShift,
          questions: [
            buildMcq({
              questionText: "What did Linh have yesterday?",
              skillTag: "listening",
              topicTag,
              explanation: "Interview for a nurse assistant course yesterday.",
              correct: "An interview for a nurse assistant course",
              wrong: ["A job at a hospital", "A meeting with her employer"],
              distractorNotes: ["Not yet employed", "Advisor call is today"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What kind of career advice does Linh want?",
              skillTag: "listening",
              topicTag,
              explanation: "Advice about her career after school.",
              correct: "Career advice after school",
              wrong: ["Salary negotiation only", "When to retire today"],
              distractorNotes: ["Not main topic", "Retire mentioned differently"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-career-practice",
          title: "Practice: Experience and Training",
          instructions: "Listen again. Focus on advice details.",
          sortOrder: 1,
          script: shiftTalk,
          answerKey: keysShift,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "When should Linh apply for training programmes?",
              skillTag: "listening",
              topicTag,
              explanation: "Apply before September.",
              correct: "Before September",
              wrong: ["After she retires", "Next Monday only"],
              distractorNotes: ["Retire different context", "Monday is Tom's email"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What does the advisor suggest for more experience?",
              skillTag: "listening",
              topicTag,
              explanation: "Have you thought about volunteering?",
              correct: "Volunteering in a hospital",
              wrong: ["Working a night shift only", "Getting a higher salary now"],
              distractorNotes: ["Shift mentioned separately", "Not the advice"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-career-check",
          title: "Check: Career Advice Challenge",
          instructions: "Listen carefully. Harder questions.",
          sortOrder: 2,
          script: shiftTalk,
          answerKey: keysShift,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Linh also wants a part-time job with a _____ shift.",
              skillTag: "listening",
              topicTag,
              explanation: "Weekend shift and study — Saturday shift builds skills.",
              correct: "weekend",
              wrong: ["night only", "retirement"],
              distractorNotes: ["Not specified as night", "Wrong meaning"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The advisor says a Saturday shift can build useful _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Saturday shift can build useful skills.",
              correct: "skills",
              wrong: ["salaries", "retirements"],
              distractorNotes: ["Salary not focus", "Wrong word"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh says she likes _____ people.",
              skillTag: "listening",
              topicTag,
              explanation: "I like helping people — opening of call.",
              correct: "helping",
              wrong: ["retiring", "interviewing"],
              distractorNotes: ["Wrong verb", "Had interview, not liking it"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-career-apply",
          title: "Apply: Match Career Call Facts",
          instructions: "Match each detail to the correct fact.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: shiftTalk },
          questions: [
            buildMatching({
              questionText: "Match items from Linh's career advice call.",
              skillTag: "listening",
              topicTag,
              explanation: "Nurse course interview; apply September; volunteering; weekend shift.",
              pairs: [
                { left: "Yesterday", right: "interview for nurse assistant course" },
                { left: "Apply for training", right: "before September" },
                { left: "More experience", right: "volunteering in a hospital" },
                { left: "Part-time work", right: "weekend shift while studying" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-career-review",
          title: "Review: Career Advice Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: shiftTalk,
          answerKey: keysShift,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Who is speaking to Linh?",
              skillTag: "listening",
              topicTag,
              explanation: "Career advisor — role in script.",
              correct: "A career advisor",
              wrong: ["Ms Pham the shop manager", "Tom the waiter"],
              distractorNotes: ["Reading advert", "Interview script"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh needs more experience in a _____.",
              skillTag: "listening",
              topicTag,
              explanation: "You need more experience in a hospital.",
              correct: "hospital",
              wrong: ["bookshop only", "retirement home for managers"],
              distractorNotes: ["Tom's job", "Distorted"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-work-review",
      title: "Lesson 3: Mixed Listening Review",
      learningObjective:
        "Extract factual information across the job interview and career advice recordings.",
      estimatedMinutes: 22,
      exercises: [
        buildListeningExercise({
          slug: "listening-mixed-learn",
          title: "Learn: Interview Reminder",
          instructions: "Listen to the café interview again.",
          sortOrder: 0,
          script: jobInterview,
          answerKey: keysInterview,
          questions: [
            buildMcq({
              questionText: "Tom applied for the job last _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Applied last week — opening of Tom's answer.",
              correct: "week",
              wrong: ["month", "year"],
              distractorNotes: ["Không nói", "Không nói"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The interview is between Tom and _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Ms Lee, café manager — speakers in script.",
              correct: "Ms Lee",
              wrong: ["Linh", "The career advisor"],
              distractorNotes: ["Shift talk character", "Different recording"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-practice",
          title: "Practice: Career Call Reminder",
          instructions: "Listen to the career advice call again.",
          sortOrder: 1,
          script: shiftTalk,
          answerKey: keysShift,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Many students do part-time work with a weekend shift and _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Weekend shift and study — advisor's answer.",
              correct: "study",
              wrong: ["retire", "interview only"],
              distractorNotes: ["Different meaning", "Not the pair"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh's career interest involves _____ people.",
              skillTag: "listening",
              topicTag,
              explanation: "I like helping people — nursing direction.",
              correct: "helping",
              wrong: ["paying", "retiring"],
              distractorNotes: ["Wrong verb", "Wrong context"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-check",
          title: "Check: Mixed Listening Challenge",
          instructions: "Listen to the interview. Which detail is ONLY in that recording?",
          sortOrder: 2,
          script: jobInterview,
          answerKey: keysInterview,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which detail is ONLY in the café interview?",
              skillTag: "listening",
              topicTag,
              explanation: "Eight pounds an hour salary — chỉ phỏng vấn café.",
              correct: "Salary of eight pounds an hour",
              wrong: ["Nurse assistant course interview", "Apply before September"],
              distractorNotes: ["Career call", "Career call"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Both recordings mention _____ in some way.",
              skillTag: "listening",
              topicTag,
              explanation: "Interview — Tom's job interview and Linh's course interview.",
              correct: "an interview",
              wrong: ["retirement today", "Ms Pham the manager"],
              distractorNotes: ["Not in both", "Only reading"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-mixed-apply",
          title: "Apply: Match Recording to Fact",
          instructions: "Match each fact to the correct recording.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: jobInterview },
          questions: [
            buildMatching({
              questionText: "Match facts to Café interview or Career advice call.",
              skillTag: "listening",
              topicTag,
              explanation: "Eight pounds = café; volunteering = career; Friday shift = café; September apply = career.",
              pairs: [
                { left: "Eight pounds an hour", right: "Café job interview" },
                { left: "Volunteering in a hospital", right: "Career advice call" },
                { left: "Friday evening shift", right: "Café job interview" },
                { left: "Apply before September", right: "Career advice call" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-review",
          title: "Review: Both Recordings Mix",
          instructions: "Listen to the career call. Final review.",
          sortOrder: 4,
          script: shiftTalk,
          answerKey: keysShift,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which character is a secondary student (13)?",
              skillTag: "listening",
              topicTag,
              explanation: "Linh — KET character continuing from Unit 1.",
              correct: "Linh",
              wrong: ["Tom", "Ms Lee"],
              distractorNotes: ["Job applicant", "Café manager"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Work _____ is discussed in BOTH recordings.",
              skillTag: "listening",
              topicTag,
              explanation: "Experience — Tom's customer experience; Linh needs hospital experience.",
              correct: "experience",
              wrong: ["retirement age only", "free books benefit"],
              distractorNotes: ["Not both", "Reading advert only"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
