/** KET U2 — reading lessons (3 × 5 exercises). Job advert: gist, scan, detail + inference. */

export function readingLessons({
  buildMcq,
  buildGapFill,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageJobAdvert,
  topicTag,
}) {
  const passage = passageJobAdvert;

  return [
    {
      slug: "reading-gist-advert",
      title: "Lesson 1: Gist — Job Advertisement",
      learningObjective:
        "Skim a job advertisement to identify the main purpose and general job type.",
      estimatedMinutes: 22,
      exercises: [
        buildReadingExercise({
          slug: "reading-gist-learn",
          title: "Learn: Read the Job Advert",
          instructions: "Read the advertisement. Answer about the main idea.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What is the main purpose of this advertisement?",
              skillTag: "reading",
              topicTag,
              explanation: "NOW HIRING part-time shop assistant — tuyển dụng.",
              correct: "To recruit a part-time shop assistant",
              wrong: ["To announce a book sale", "To describe Ms Pham retiring"],
              distractorNotes: ["Không nhắc sale", "Ms Pham bắt đầu từ sinh viên"],
              assessmentType: "main_idea",
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What kind of job is offered?",
              skillTag: "reading",
              topicTag,
              explanation: "Part-time shop assistant on weekends.",
              correct: "Part-time shop assistant",
              wrong: ["Full-time manager", "Publishing career only"],
              distractorNotes: ["Part-time, không full-time", "Publishing là lĩnh vực, không phải job title"],
              assessmentType: "main_idea",
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-gist-practice",
          title: "Practice: Skim for General Information",
          instructions: "Read again. Answer gist questions.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Where is the shop located?",
              skillTag: "reading",
              topicTag,
              explanation: "Busy city centre shop — trung tâm thành phố.",
              correct: "In the city centre",
              wrong: ["On a university campus", "In a hospital"],
              distractorNotes: ["Không nhắc", "Không liên quan"],
              assessmentType: "main_idea",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who started at the bookshop as a student?",
              skillTag: "reading",
              topicTag,
              explanation: "Ms Pham started here as a student — cuối quảng cáo.",
              correct: "Ms Pham",
              wrong: ["Tom", "Linh"],
              distractorNotes: ["Nhân vật listening", "Nhân vật unit khác"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-gist-check",
          title: "Check: Main Idea Challenge",
          instructions: "Read carefully. These questions need thinking.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "The advert is mainly for students who want to _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Weekend part-time job + career advice for publishing.",
              correct: "work part-time and build career skills",
              wrong: ["retire early", "apply for a manager job only"],
              distractorNotes: ["Retire không phải mục đích", "Shop assistant, không chỉ manager"],
              assessmentType: "main_idea",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which section tells you HOW to get the job?",
              skillTag: "reading",
              topicTag,
              explanation: "HOW TO APPLY — gửi email trước 30 April.",
              correct: "HOW TO APPLY",
              wrong: ["REQUIREMENTS", "BENEFITS"],
              distractorNotes: ["Yêu cầu, không cách nộp", "Phúc lợi"],
              assessmentType: "main_idea",
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-gist-apply",
          title: "Apply: Match Section to Purpose",
          instructions: "Match each advert section to its purpose.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each section to what it tells you.",
              skillTag: "reading",
              topicTag,
              explanation: "Requirements = what you need; Benefits = extras; Apply = how to send application.",
              pairs: [
                { left: "REQUIREMENTS", right: "what skills and hours you need" },
                { left: "BENEFITS", right: "salary, free books and career advice" },
                { left: "HOW TO APPLY", right: "email before 30 April" },
                { left: "Job description", right: "duties with colleagues on weekends" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-gist-review",
          title: "Review: Gist Skim Mix",
          instructions: "Skim the advert one more time. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Greenway Bookshop is looking for someone friendly to join the _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Join our team — làm việc cùng đội.",
              correct: "team",
              wrong: ["salary", "retirement plan"],
              distractorNotes: ["Lương là benefit", "Không nhắc"],
              assessmentType: "vocabulary_in_context",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The whole advert is about _____ at Greenway Bookshop.",
              skillTag: "reading",
              topicTag,
              explanation: "Work and jobs — tuyển part-time shop assistant.",
              correct: "a part-time job opportunity",
              wrong: ["a family holiday", "a school timetable change"],
              distractorNotes: ["Unit khác", "Unit Education"],
              assessmentType: "main_idea",
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-scan-advert",
      title: "Lesson 2: Scan for Specific Information",
      learningObjective:
        "Scan the job advertisement for salary, shift times, deadlines and requirements.",
      estimatedMinutes: 22,
      exercises: [
        buildReadingExercise({
          slug: "reading-scan-learn",
          title: "Learn: Find Key Facts",
          instructions: "Scan the advert for specific details.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What days does the shop assistant work?",
              skillTag: "reading",
              topicTag,
              explanation: "Saturday and Sunday — REQUIREMENTS.",
              correct: "Saturday and Sunday",
              wrong: ["Monday to Friday", "Only Saturday"],
              distractorNotes: ["Weekdays không nhắc", "Sunday cũng cần"],
              assessmentType: "detail",
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When is the apply-by deadline?",
              skillTag: "reading",
              topicTag,
              explanation: "Before 30 April — HOW TO APPLY.",
              correct: "Before 30 April",
              wrong: ["Before 7 March", "Next Monday"],
              distractorNotes: ["Ngày khác unit", "Start date email"],
              assessmentType: "detail",
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-scan-practice",
          title: "Practice: Scan for Numbers and Times",
          instructions: "Find numbers, times and amounts quickly.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "What time is the Saturday shift?",
              skillTag: "reading",
              topicTag,
              explanation: "Saturday shift from 9 a.m. to 5 p.m.",
              correct: "9 a.m. to 5 p.m.",
              wrong: ["3 p.m. to 6 p.m.", "8 p.m. to midnight"],
              distractorNotes: ["Giờ thư viện U1", "Không nhắc"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How much experience do applicants need?",
              skillTag: "reading",
              topicTag,
              explanation: "At least one year of customer service experience.",
              correct: "At least one year",
              wrong: ["No experience", "Three years"],
              distractorNotes: ["Cần kinh nghiệm", "Chỉ một năm"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-scan-check",
          title: "Check: Detail Search Challenge",
          instructions: "Scan carefully. Harder detail questions.",
          sortOrder: 2,
          passage,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "What email address should applicants use?",
              skillTag: "reading",
              topicTag,
              explanation: "jobs@greenwaybooks.co.uk — HOW TO APPLY.",
              correct: "jobs@greenwaybooks.co.uk",
              wrong: ["ms.pham@school.edu", "careers@hospital.uk"],
              distractorNotes: ["Không có", "Unit khác"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When do staff get free books?",
              skillTag: "reading",
              topicTag,
              explanation: "Free books after three months — BENEFITS.",
              correct: "After three months",
              wrong: ["After one year", "On the first day"],
              distractorNotes: ["Một năm là experience", "Không nói ngay"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The hourly salary is _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Above the minimum wage — BENEFITS.",
              correct: "above the minimum wage",
              wrong: ["eight pounds exactly", "not mentioned"],
              distractorNotes: ["Từ listening café", "Có nhắc mức tương đối"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-scan-apply",
          title: "Apply: Match Facts from the Advert",
          instructions: "Match each topic to a fact from the advertisement.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each item to the correct fact.",
              skillTag: "reading",
              topicTag,
              explanation: "Salary above minimum; Apply 30 April; Manager Ms Pham; Shift Sat 9–5.",
              pairs: [
                { left: "Salary", right: "above the minimum wage" },
                { left: "Apply by", right: "email before 30 April" },
                { left: "Manager", right: "Ms Pham" },
                { left: "Saturday shift", right: "9 a.m. to 5 p.m." },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-scan-review",
          title: "Review: Scan Detail Mix",
          instructions: "Scan and answer — mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Applicants must be able to work on _____ and Sunday.",
              skillTag: "reading",
              topicTag,
              explanation: "Saturday and Sunday — REQUIREMENTS.",
              correct: "Saturday",
              wrong: ["Friday", "Monday"],
              distractorNotes: ["Friday là listening", "Weekday không yêu cầu"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Successful candidates will be contacted for an _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Contact for an interview — HOW TO APPLY.",
              correct: "interview",
              wrong: ["salary raise", "retirement"],
              distractorNotes: ["Không nhắc", "Không liên quan"],
              assessmentType: "vocabulary_in_context",
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-detail-inference",
      title: "Lesson 3: Detail and Inference",
      learningObjective:
        "Answer detail, vocabulary-in-context and inference questions about the job advert.",
      estimatedMinutes: 23,
      exercises: [
        buildReadingExercise({
          slug: "reading-detail-learn",
          title: "Learn: Words in the Advert",
          instructions: "Read the advert. Answer vocabulary questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "In the advert, 'shift' refers to _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Saturday shift 9–5 = một ca làm việc cụ thể.",
              correct: "a fixed period of work time",
              wrong: ["the salary amount", "a job interview"],
              distractorNotes: ["Salary riêng biệt", "Interview là buổi gặp"],
              assessmentType: "vocabulary_in_context",
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The 'employer' in the advert is _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Greenway Bookshop / the company hiring — employer offers salary.",
              correct: "Greenway Bookshop (the company hiring)",
              wrong: ["Tom the waiter", "Linh the student"],
              distractorNotes: ["Listening character", "Career advice character"],
              assessmentType: "vocabulary_in_context",
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-detail-practice",
          title: "Practice: Inference Questions",
          instructions: "Read again. Think about implied meaning.",
          sortOrder: 1,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Why does Ms Pham mention her own story?",
              skillTag: "reading",
              topicTag,
              explanation: "Job helped build career skills — khuyến khích ứng viên.",
              correct: "To show the job can help your career",
              wrong: ["To explain the salary", "To say when to retire"],
              distractorNotes: ["Salary liệt kê riêng", "Retire không phải thông điệp"],
              assessmentType: "inference",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which requirement suggests the job involves talking to customers?",
              skillTag: "reading",
              topicTag,
              explanation: "Good communication skills + customer service experience.",
              correct: "Good communication skills",
              wrong: ["Free books after three months", "Career advice for publishing"],
              distractorNotes: ["Benefit", "Benefit khác"],
              assessmentType: "inference",
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-detail-check",
          title: "Check: Detail and Order",
          instructions: "Read one more time. Harder questions.",
          sortOrder: 2,
          passage,
          difficulty: 0.35,
          questions: [
            buildMcq({
              questionText: "Put the sections in order: (1) Requirements (2) How to apply (3) Job description and benefits",
              skillTag: "reading",
              topicTag,
              explanation: "Mô tả + benefits → requirements → how to apply.",
              correct: "3 → 1 → 2",
              wrong: ["1 → 2 → 3", "2 → 3 → 1"],
              distractorNotes: ["Requirements sau mô tả", "Apply cuối cùng"],
              assessmentType: "sequencing",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is NOT true according to the advert?",
              skillTag: "reading",
              topicTag,
              explanation: "No experience required — sai, cần ít nhất một năm.",
              correct: "No experience is required for this job.",
              wrong: [
                "The employer offers training.",
                "Staff can get free books after three months.",
              ],
              distractorNotes: ["Đúng — training mentioned", "Đúng — benefits"],
              assessmentType: "inference",
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-detail-apply",
          title: "Apply: Complete from the Advert",
          instructions: "Fill in gaps using facts from the advert.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete from the advert: Apply by email before [0] April. | Work the Saturday [1] from 9 to 5. | Need [2] year of customer service experience.",
              skillTag: "reading",
              topicTag,
              explanation: "30; shift; one — chi tiết scan từ quảng cáo.",
              template:
                "Apply by email before [0] April. Work the Saturday [1] from 9 to 5. Need [2] year of customer service experience.",
              correctAnswers: ["30", "shift", "one"],
              acceptableAnswers: [
                ["30", "30th"],
                ["shift", "Shift"],
                ["one", "One", "1"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-detail-review",
          title: "Review: Reading Mix",
          instructions: "Mixed detail and inference review.",
          sortOrder: 4,
          passage,
          difficulty: 0.35,
          questions: [
            buildMcq({
              questionText: "Duties include helping customers, organising books and _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Working a Saturday shift — job description.",
              correct: "working a Saturday shift",
              wrong: ["retiring at sixty-five", "graduating from university"],
              distractorNotes: ["Không liên quan", "Unit Education"],
              assessmentType: "detail",
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The advert suggests this job is good for students who want a career in _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Career advice for students who want to work in publishing.",
              correct: "publishing",
              wrong: ["medicine only", "retirement planning"],
              distractorNotes: ["Linh nursing là listening", "Không liên quan"],
              assessmentType: "inference",
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
