/** KET U2 — speaking lessons (3 × 5 exercises; only Check is AI). */

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [jobCheck, interviewCheck, careerCheck] = speakingChecks;

  return [
    {
      slug: "speaking-part-time-job",
      title: "Lesson 1: Talk About Your Job",
      learningObjective:
        "Choose appropriate spoken phrases about part-time jobs, colleagues and shifts.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-job-learn",
          title: "Learn: What to Say About Work",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Examiner: Where do you work? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I work in a bookshop on Saturdays — present simple + place.",
              correct: "I work in a bookshop on Saturdays.",
              wrong: ["I am work in a bookshop.", "I working in a bookshop."],
              distractorNotes: ["Wrong auxiliary", "Missing auxiliary"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Examiner: What is your colleague doing now? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "She is helping a customer — present continuous.",
              correct: "She is helping a customer.",
              wrong: ["She helps a customer now.", "She help a customer now."],
              distractorNotes: ["Simple present for now", "Wrong verb form"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-job-practice",
          title: "Practice: Shift and Salary Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Examiner: When does your shift start? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "It starts at nine o'clock — câu trả lời phỏng vấn A2.",
              correct: "It starts at nine o'clock in the morning.",
              wrong: ["It is start at nine.", "It starting at nine."],
              distractorNotes: ["Wrong form", "Missing auxiliary"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: What is your salary? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "My salary is eight pounds an hour — từ listening context.",
              correct: "My salary is eight pounds an hour.",
              wrong: ["My salary is interview hour.", "Salary I eight pounds."],
              distractorNotes: ["Nonsense", "Wrong order"],
              difficultyRating: 2,
            }),
          ],
        }),
        jobCheck,
        buildExercise({
          slug: "speaking-job-apply",
          title: "Apply: Quick Work Replies",
          instructions: "Choose the best short spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Examiner: Do you have a part-time job? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes + what + where — trả lời đầy đủ.",
              correct: "Yes, I work part-time in a bookshop on weekends.",
              wrong: ["Yes part-time I work bookshop.", "Yes, I part-time job bookshop."],
              distractorNotes: ["Wrong order", "Not a sentence"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-job-review",
          title: "Review: Job Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Examiner: What are you doing this week at work? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I am training with my manager this week — present continuous.",
              correct: "I am training with my manager this week.",
              wrong: ["I train with my manager usually.", "I am train with my manager."],
              distractorNotes: ["Habit, not this week", "Wrong -ing form"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: Who are your colleagues? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "My colleagues are very friendly — mô tả ngắn.",
              correct: "My colleagues are very friendly and helpful.",
              wrong: ["My colleagues is salary shift.", "Colleagues friendly very I."],
              distractorNotes: ["Nonsense", "Wrong order"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-job-interview",
      title: "Lesson 2: Talk About an Interview",
      learningObjective:
        "Use interview, apply and experience vocabulary in short spoken answers.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-interview-learn",
          title: "Learn: Interview Speaking Phrases",
          instructions: "Choose the best thing to say about interviews.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Examiner: Tell me about your work experience. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I worked in a café for six months — kinh nghiệm quá khứ.",
              correct: "I worked in a café for six months.",
              wrong: ["I retire in a café.", "My salary is experience."],
              distractorNotes: ["Wrong verb", "Nonsense"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Examiner: Have you ever had a job interview? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, I had an interview for a shop assistant job last week.",
              correct: "Yes, I had an interview for a shop assistant job last week.",
              wrong: ["Yes interview I shop last.", "Yes, I interviewing shop job."],
              distractorNotes: ["Wrong order", "Wrong form"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-interview-practice",
          title: "Practice: Application Replies",
          instructions: "Choose the correct spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Examiner: What job did you apply for? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I applied for a part-time job at Greenway Bookshop.",
              correct: "I applied for a part-time job at Greenway Bookshop.",
              wrong: ["I apply part-time Greenway bookshop job.", "Applied I job part-time."],
              distractorNotes: ["Wrong tense/order", "Wrong order"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: What did the manager ask you? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "The manager asked about my experience with customers.",
              correct: "The manager asked about my experience with customers.",
              wrong: ["Manager ask experience customers my.", "The manager salary shift interview."],
              distractorNotes: ["Wrong tense", "Fragment"],
              difficultyRating: 2,
            }),
          ],
        }),
        interviewCheck,
        buildExercise({
          slug: "speaking-interview-apply",
          title: "Apply: Choose the Best Interview Reply",
          instructions: "Pick the most natural spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Examiner: When can you work? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I can work the weekend shift — availability rõ ràng.",
              correct: "I can work the weekend shift.",
              wrong: ["I can weekend shift work I.", "Weekend shift can work."],
              distractorNotes: ["Wrong order", "Fragment"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-interview-review",
          title: "Review: Interview Speaking Quiz",
          instructions: "Choose the best answer using interview vocabulary.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Examiner: A friend asks about your interview yesterday. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "It went well. The manager asked about my experience.",
              correct: "It went well. The manager asked about my experience.",
              wrong: ["It went well. The manager asked about my retire.", "It went well. I shift at the manager."],
              distractorNotes: ["Wrong word", "Nonsense"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: Why do you want this job? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I want to build skills for my career — lý do hợp lý A2.",
              correct: "I want to build skills for my career.",
              wrong: ["I want salary retire interview.", "Career I want build skills job."],
              distractorNotes: ["Fragment list", "Wrong order"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-career-plans",
      title: "Lesson 3: Describe Career Plans",
      learningObjective:
        "Describe career plans, experience and retirement in extended spoken answers.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "speaking-career-learn",
          title: "Learn: Career Phrases",
          instructions: "Choose the best thing to say about your future.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Examiner: What career would you like? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I would like a career in nursing — như Linh trong listening.",
              correct: "I would like a career in nursing.",
              wrong: ["I would like interview in nursing.", "I would shift in nursing."],
              distractorNotes: ["Wrong noun", "Wrong word"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Examiner: Do you want a career in business? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, I want a career in business because I like working with people.",
              correct: "Yes, I want a career in business because I like working with people.",
              wrong: ["Yes, I want interview in business.", "Yes, I shift in business."],
              distractorNotes: ["Wrong noun", "Wrong word"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-career-practice",
          title: "Practice: Experience and Retire",
          instructions: "Choose the best spoken answers.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Examiner: When do people usually retire in your country? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Many people retire at sixty or sixty-five.",
              correct: "Many people retire at sixty or sixty-five.",
              wrong: ["Many people retire at experience.", "Retire people sixty many."],
              distractorNotes: ["Wrong word", "Wrong order"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: What is your employer like? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "My employer is fair and pays a good salary.",
              correct: "My employer is fair and pays a good salary.",
              wrong: ["My employer is interview and career.", "My employer is colleague every day."],
              distractorNotes: ["Wrong word class", "Awkward meaning"],
              difficultyRating: 2,
            }),
          ],
        }),
        careerCheck,
        buildExercise({
          slug: "speaking-career-apply",
          title: "Apply: Tell About Your Career",
          instructions: "Choose the best career description.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best short description of your career plans:",
              skillTag: "speaking",
              topicTag,
              explanation: "Connected ideas: experience + career + part-time job.",
              correct:
                "I have some volunteering experience. I would like a career in nursing. I also want a part-time job to build skills.",
              wrong: [
                "Career experience shift salary interview.",
                "I have career since for experience retire.",
              ],
              distractorNotes: ["Not sentences", "Ungrammatical"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-career-review",
          title: "Review: Career Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Examiner: Why do you want a part-time job? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "To earn money and build skills after school.",
              correct: "I want to earn money and build skills after school.",
              wrong: ["I want retire salary interview.", "Part-time job I want money skills."],
              distractorNotes: ["Wrong words", "Wrong order"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Your employer asks why you are late for your shift. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I'm sorry. The bus was late this morning — lịch sự + lý do.",
              correct: "I'm sorry. The bus was late this morning.",
              wrong: ["I'm sorry. I retire this morning.", "I'm sorry. My salary was late."],
              distractorNotes: ["Wrong verb", "Illogical reason"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
