/** KET U2 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-workplace-people",
      title: "Lesson 1: Workplace People",
      learningObjective:
        "Recognise and use colleague, employer, manager and job in work contexts.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "vocab-workplace-learn",
          title: "Learn: People at Work",
          instructions: "Read each clue. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "A person who works with you at the same company is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Colleague (đồng nghiệp) là người làm cùng công ty.",
              correct: "colleague",
              wrong: ["employer", "salary"],
              distractorNotes: ["Người trả lương", "Tiền lương, không phải người"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The person or company that pays you to work is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Employer (chủ lao động) trả lương cho bạn.",
              correct: "employer",
              wrong: ["colleague", "shift"],
              distractorNotes: ["Đồng cấp", "Ca làm việc"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The boss who interviews new staff is the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Manager (quản lý) phỏng vấn nhân viên mới.",
              correct: "manager",
              wrong: ["colleague", "career"],
              distractorNotes: ["Đồng nghiệp", "Sự nghiệp dài hạn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Paid work that you do regularly is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Job (công việc) — công việc có trả lương.",
              correct: "job",
              wrong: ["interview", "retire"],
              distractorNotes: ["Buổi phỏng vấn", "Nghỉ hưu"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-workplace-practice",
          title: "Practice: Match Workplace People",
          instructions: "Match each word to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the workplace people words to their meanings.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Colleague = co-worker; employer = pays you; manager = boss.",
              pairs: [
                { left: "colleague", right: "someone who works with you" },
                { left: "employer", right: "the person or company that pays you" },
                { left: "manager", right: "the person in charge of a team or shop" },
                { left: "job", right: "paid work that you do" },
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-workplace-check",
          title: "Check: Workplace People Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Ms Pham is the shop _____. She interviews new staff.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Manager phỏng vấn nhân viên — vai trò quản lý.",
              correct: "manager",
              wrong: ["colleague", "employer"],
              distractorNotes: ["Đồng cấp", "Chủ lao động rộng hơn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Tom's _____ were very helpful on his first day.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Colleagues — đồng nghiệp giúp ngày đầu.",
              correct: "colleagues",
              wrong: ["salaries", "interviews"],
              distractorNotes: ["Tiền lương", "Buổi phỏng vấn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The _____ will email you about the start date.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Employer — chủ lao động gửi email về ngày bắt đầu.",
              correct: "employer",
              wrong: ["shift", "career"],
              distractorNotes: ["Ca làm", "Sự nghiệp"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-workplace-apply",
          title: "Apply: Complete Workplace Sentences",
          instructions: "Fill in each gap with the correct word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: My [0] helped me on my first day. | The [1] interviewed three people. | I want a part-time [2] at the bookshop.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "colleague; manager; job — ngữ cảnh nơi làm việc.",
              template:
                "My [0] helped me on my first day. The [1] interviewed three people. I want a part-time [2] at the bookshop.",
              correctAnswers: ["colleague", "manager", "job"],
              acceptableAnswers: [
                ["colleague", "Colleague"],
                ["manager", "Manager"],
                ["job", "Job"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-workplace-review",
          title: "Review: Workplace People Mix",
          instructions: "Choose the best word from the unit.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Your _____ pays your salary every month.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Employer trả lương hàng tháng.",
              correct: "employer",
              wrong: ["colleague", "interview"],
              distractorNotes: ["Đồng nghiệp không trả lương", "Buổi phỏng vấn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh wants a weekend _____ at Greenway Bookshop.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Job — công việc cuối tuần.",
              correct: "job",
              wrong: ["retire", "shift only"],
              distractorNotes: ["Nghỉ hưu", "Shift là ca, không phải công việc"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-job-process",
      title: "Lesson 2: Job Process",
      learningObjective:
        "Use interview, apply, experience and career when talking about getting a job.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "vocab-process-learn",
          title: "Learn: Getting a Job",
          instructions: "Choose the best word for each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "A formal meeting where an employer asks you questions is an _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Interview (phỏng vấn) — buổi hỏi đáp khi xin việc.",
              correct: "interview",
              wrong: ["career", "shift"],
              distractorNotes: ["Sự nghiệp dài hạn", "Ca làm việc"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "To send a request for a job, you _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Apply (nộp đơn) — gửi đơn xin việc.",
              correct: "apply",
              wrong: ["retire", "shift"],
              distractorNotes: ["Nghỉ hưu", "Ca làm"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Skills you gain from doing a job is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Experience (kinh nghiệm) — kỹ năng thu được khi làm việc.",
              correct: "experience",
              wrong: ["salary", "colleague"],
              distractorNotes: ["Tiền lương", "Người"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-process-practice",
          title: "Practice: Match Job Process Words",
          instructions: "Match each word to the correct meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match job process words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Apply = send application; career = long-term path.",
              pairs: [
                { left: "apply", right: "to send a request for a job" },
                { left: "interview", right: "a formal meeting with an employer" },
                { left: "experience", right: "skills gained from doing work" },
                { left: "career", right: "the path of jobs over many years" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-process-check",
          title: "Check: Job Process Challenge",
          instructions: "Choose the correct answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Before the interview, you should _____ online with your CV.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Apply — nộp đơn trước phỏng vấn.",
              correct: "apply",
              wrong: ["retire", "shift"],
              distractorNotes: ["Nghỉ hưu", "Ca làm"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The advert says you need at least one year of customer service _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Experience — yêu cầu kinh nghiệm trong quảng cáo.",
              correct: "experience",
              wrong: ["salary", "employer"],
              distractorNotes: ["Lương", "Chủ lao động"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Ms Pham says the job helped her build skills for her _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Career — sự nghiệp lâu dài.",
              correct: "career",
              wrong: ["shift", "interview"],
              distractorNotes: ["Ca làm", "Buổi phỏng vấn"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-process-apply",
          title: "Apply: Complete Job Process Sentences",
          instructions: "Fill in the gaps with unit words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Send an email to [0] before 30 April. | We will contact you for an [1]. | You need one year of [2].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "apply; interview; experience — quy trình xin việc.",
              template:
                "Send an email to [0] before 30 April. We will contact you for an [1]. You need one year of [2].",
              correctAnswers: ["apply", "interview", "experience"],
              acceptableAnswers: [
                ["apply", "Apply"],
                ["interview", "Interview"],
                ["experience", "Experience"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-process-review",
          title: "Review: Job Process Word Mix",
          instructions: "Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Linh had an _____ for a nurse assistant course yesterday.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Interview — buổi phỏng vấn khóa học.",
              correct: "interview",
              wrong: ["salary", "shift"],
              distractorNotes: ["Lương", "Ca làm"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The path of jobs you have over many years is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Career — sự nghiệp dài hạn.",
              correct: "career",
              wrong: ["experience only", "employer"],
              distractorNotes: ["Chỉ kinh nghiệm", "Chủ lao động"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-work-conditions",
      title: "Lesson 3: Work Conditions",
      learningObjective:
        "Use salary, shift, part-time and retire in work and career contexts.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "vocab-conditions-learn",
          title: "Learn: Pay and Hours",
          instructions: "Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "The money you receive from your job is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Salary (lương) — tiền nhận từ công việc.",
              correct: "salary",
              wrong: ["shift", "interview"],
              distractorNotes: ["Ca làm", "Phỏng vấn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "A fixed period of work time is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Shift (ca làm) — khoảng thời gian làm việc cố định.",
              correct: "shift",
              wrong: ["career", "apply"],
              distractorNotes: ["Sự nghiệp", "Nộp đơn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Working fewer hours than a full week is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Part-time (bán thời gian) — làm ít giờ hơn toàn thời gian.",
              correct: "part-time",
              wrong: ["retire", "employer"],
              distractorNotes: ["Nghỉ hưu", "Chủ lao động"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-conditions-practice",
          title: "Practice: Match Work Conditions",
          instructions: "Match each word to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match work condition words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Retire = stop working permanently; part-time = fewer hours.",
              pairs: [
                { left: "salary", right: "money you receive from your job" },
                { left: "shift", right: "a fixed period of work time" },
                { left: "part-time", right: "working fewer hours than full-time" },
                { left: "retire", right: "to stop working permanently because of age" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-conditions-check",
          title: "Check: Work Conditions Quiz",
          instructions: "Harder questions — no hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "The salary is eight pounds an _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hour — lương theo giờ trong phỏng vấn café.",
              correct: "hour",
              wrong: ["shift", "interview"],
              distractorNotes: ["Ca làm", "Phỏng vấn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Tom works three evenings a week. He has a _____ job.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Part-time — làm vài buổi mỗi tuần.",
              correct: "part-time",
              wrong: ["retire", "employer"],
              distractorNotes: ["Nghỉ hưu", "Chủ lao động"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When you stop working permanently because of age, you _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Retire (nghỉ hưu) — ngừng làm việc vĩnh viễn.",
              correct: "retire",
              wrong: ["apply", "interview"],
              distractorNotes: ["Nộp đơn", "Phỏng vấn"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-conditions-apply",
          title: "Apply: Linh's Work Week",
          instructions: "Complete the paragraph with unit words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I want a [0] job on weekends. | I work the Saturday [1] from 9 to 5. | The [2] is above the minimum wage. | Many people [3] at sixty-five.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "part-time; shift; salary; retire — điều kiện làm việc.",
              template:
                "I want a [0] job on weekends. I work the Saturday [1] from 9 to 5. The [2] is above the minimum wage. Many people [3] at sixty-five.",
              correctAnswers: ["part-time", "shift", "salary", "retire"],
              acceptableAnswers: [
                ["part-time", "Part-time"],
                ["shift", "Shift"],
                ["salary", "Salary"],
                ["retire", "Retire"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-conditions-review",
          title: "Review: Full Vocabulary Final",
          instructions: "Final mixed quiz on all twelve words.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which word means the same as 'hand in your application'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Apply = nộp đơn xin việc.",
              correct: "apply",
              wrong: ["retire", "shift"],
              distractorNotes: ["Nghỉ hưu", "Ca làm"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence uses 'colleague' correctly?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "My colleague helped me — collocation chuẩn.",
              correct: "My colleague helped me on my first day.",
              wrong: [
                "My colleague is eight pounds an hour.",
                "I colleague every Saturday shift.",
              ],
              distractorNotes: ["Nonsense", "Wrong word class"],
              difficultyRating: 3,
            }),
          ],
        }),
      ],
    },
  ];
}
