import { composeGoldMockManifest } from "@/lib/cambridge-assessment/gold-mocks/gold-mock-compose";
import {
  goldGapFill,
  goldMatching,
  goldMcq,
  goldReadingComprehension,
  goldSpeaking,
  goldWriting,
  listeningAudio,
  uniquifyQuestionStems,
} from "@/lib/cambridge-assessment/gold-mocks/gold-mock-helpers";

const QUESTIONS = [
  goldMatching({
    questionRef: "fgm3-001",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 1,
    points: 1,
    difficulty: "easy",
    topicTag: "nature_reserve",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["nature", "places"],
    skillTag: "listening",
    questionText: "Listen. Which woman is Dr Tan?",
    pairs: [{ leftText: "Dr Tan", rightText: "Woman pointing at birds with binoculars" }],
    content: {
      transcriptSnippet: "This is Dr Tan. She's pointing at birds with her binoculars.",
      audioCue: "name_introduction",
    },
  }),

  goldMatching({
    questionRef: "fgm3-002",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 2,
    points: 1,
    difficulty: "easy",
    topicTag: "beach_day",
    grammarTags: ["possessives"],
    vocabularyTopics: ["leisure", "nature"],
    skillTag: "listening",
    questionText: "Listen. Which boy is Hugo?",
    pairs: [{ leftText: "Hugo", rightText: "Boy building a sandcastle near the sea" }],
    content: {
      transcriptSnippet: "Hugo's building a sandcastle near the sea.",
      audioCue: "name_introduction",
    },
  }),

  goldMatching({
    questionRef: "fgm3-003",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 3,
    points: 1,
    difficulty: "medium",
    topicTag: "forest_walk",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["nature", "feelings"],
    skillTag: "listening",
    questionText: "Listen. Which girl is Mei?",
    pairs: [{ leftText: "Mei", rightText: "Girl sketching flowers in a woodland notebook" }],
    content: {
      transcriptSnippet: "Mei is sketching wild flowers in her woodland notebook.",
      audioCue: "name_introduction",
    },
  }),

  goldMatching({
    questionRef: "fgm3-004",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 4,
    points: 1,
    difficulty: "medium",
    topicTag: "picnic_park",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["leisure", "food"],
    skillTag: "listening",
    questionText: "Listen. Which man is Mr Costa?",
    pairs: [{ leftText: "Mr Costa", rightText: "Man playing guitar while people relax on the grass" }],
    content: {
      transcriptSnippet: "Mr Costa plays guitar while families relax on the grass every Sunday.",
      audioCue: "name_introduction",
    },
  }),

  goldMatching({
    questionRef: "fgm3-005",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 5,
    points: 1,
    difficulty: "easy",
    topicTag: "zoo_visit",
    grammarTags: ["have_got"],
    vocabularyTopics: ["nature", "animals"],
    skillTag: "listening",
    questionText: "Listen. Which girl is Ruby?",
    pairs: [{ leftText: "Ruby", rightText: "Girl wearing a hat with a butterfly badge" }],
    content: {
      transcriptSnippet: "Ruby's got a hat with a bright butterfly badge on it.",
      audioCue: "name_introduction",
    },
  }),

  goldMatching({
    questionRef: "fgm3-006",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 6,
    points: 1,
    difficulty: "hard",
    topicTag: "river_cleanup",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["nature", "environment"],
    skillTag: "listening",
    questionText: "Listen. Which boy is Samir?",
    pairs: [{ leftText: "Samir", rightText: "Boy standing beside a canoe on the riverbank" }],
    content: {
      transcriptSnippet: "Samir is standing beside a canoe on the riverbank with his team.",
      audioCue: "name_introduction",
    },
  }),

  goldMatching({
    questionRef: "fgm3-007",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 7,
    points: 1,
    difficulty: "hard",
    topicTag: "sunset_hill",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["nature", "feelings"],
    skillTag: "listening",
    questionText: "Listen. Which woman is the ranger?",
    pairs: [{ leftText: "The ranger", rightText: "Woman showing a map at the hilltop viewpoint" }],
    content: {
      transcriptSnippet: "The ranger showed a trail map at the hilltop viewpoint yesterday evening.",
      audioCue: "name_introduction",
    },
  }),

  goldGapFill({
    questionRef: "fgm3-008",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 8,
    points: 1,
    difficulty: "easy",
    topicTag: "weather_forecast",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["weather", "nature"],
    skillTag: "listening",
    questionText: "Listen and write. How many degrees will it be tomorrow?",
    template: "Tomorrow the temperature will be [0] degrees.",
    correctAnswers: ["nineteen", "19"],
    content: {
      transcriptSnippet: "Tomorrow the temperature will be nineteen degrees with sunny spells.",
    },
  }),

  goldGapFill({
    questionRef: "fgm3-009",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 9,
    points: 1,
    difficulty: "medium",
    topicTag: "nature_trail",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["nature", "animals"],
    skillTag: "listening",
    questionText: "Listen and write. Which animal are the children looking for?",
    template: "The children are looking for a [0].",
    correctAnswers: ["deer"],
    content: {
      transcriptSnippet: "The children are looking for a deer on the nature trail.",
    },
  }),

  goldGapFill({
    questionRef: "fgm3-010",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 10,
    points: 1,
    difficulty: "medium",
    topicTag: "cinema_times",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["leisure", "time"],
    skillTag: "listening",
    questionText: "Listen and write. What time does the film start?",
    template: "The film starts at [0].",
    correctAnswers: ["quarter past four", "4:15", "four fifteen"],
    content: {
      transcriptSnippet: "The film starts at quarter past four this afternoon.",
    },
  }),

  goldGapFill({
    questionRef: "fgm3-011",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 11,
    points: 1,
    difficulty: "easy",
    topicTag: "camping_trip",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["nature", "leisure"],
    skillTag: "listening",
    questionText: "Listen and write. How many nights are they going to camp?",
    template: "They are going to camp for [0] nights.",
    correctAnswers: ["two", "2"],
    content: {
      transcriptSnippet: "They are going to camp for two nights in the forest.",
    },
  }),

  goldGapFill({
    questionRef: "fgm3-012",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 12,
    points: 1,
    difficulty: "hard",
    topicTag: "waterfall_visit",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["nature", "places"],
    skillTag: "listening",
    questionText: "Listen and write. When did the waterfall path open?",
    template: "The waterfall path opened in [0].",
    correctAnswers: ["two thousand twenty", "2020"],
    content: {
      transcriptSnippet: "The waterfall path opened in two thousand twenty.",
    },
  }),

  goldGapFill({
    questionRef: "fgm3-013",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 13,
    points: 1,
    difficulty: "hard",
    topicTag: "swimming_lake",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["leisure", "sports"],
    skillTag: "listening",
    questionText: "Listen and write. Who swam across the lake fastest?",
    template: "The fastest swimmer was [0].",
    correctAnswers: ["Ivy"],
    content: {
      transcriptSnippet: "Ivy swam across the lake faster than anyone else in the group.",
    },
  }),

  goldGapFill({
    questionRef: "fgm3-014",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 14,
    points: 1,
    difficulty: "medium",
    topicTag: "picnic_recipe",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["food", "leisure"],
    skillTag: "listening",
    questionText: "Listen and write. How many apples do you need for the picnic?",
    template: "You need [0] apples.",
    correctAnswers: ["six", "6"],
    content: {
      transcriptSnippet: "You need six apples for the picnic fruit salad.",
    },
  }),

  goldMcq({
    questionRef: "fgm3-015",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 15,
    points: 1,
    difficulty: "easy",
    topicTag: "birdwatching",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["nature", "animals"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What are the children watching in the trees?",
    choices: [
      { text: "Colourful birds", isCorrect: true },
      { text: "Traffic lights", isCorrect: false },
      { text: "Television screens", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "The children are watching colourful birds in the trees near the lake.",
    },
  }),

  goldMcq({
    questionRef: "fgm3-016",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 16,
    points: 1,
    difficulty: "medium",
    topicTag: "theme_park",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["leisure", "feelings"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What can visitors do at the theme park?",
    choices: [
      { text: "Ride a wooden roller coaster", isCorrect: true },
      { text: "Sleep under the sea", isCorrect: false },
      { text: "Cook in a science lab", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "At the theme park visitors can ride a fast wooden roller coaster.",
    },
  }),

  goldMcq({
    questionRef: "fgm3-017",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 17,
    points: 1,
    difficulty: "medium",
    topicTag: "stormy_hike",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["nature", "weather"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What happened during the hike?",
    choices: [
      { text: "It started raining heavily", isCorrect: true },
      { text: "They found a shopping mall", isCorrect: false },
      { text: "They flew in a helicopter", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "During the hike it started raining heavily so they put on waterproof jackets.",
    },
  }),

  goldMcq({
    questionRef: "fgm3-018",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 18,
    points: 1,
    difficulty: "easy",
    topicTag: "leisure_centre",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["leisure", "sports"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What does the leisure centre offer on Fridays?",
    choices: [
      { text: "Swimming and badminton", isCorrect: true },
      { text: "Horse riding lessons", isCorrect: false },
      { text: "Car repairs", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "The leisure centre offers swimming and badminton on Fridays.",
    },
  }),

  goldMcq({
    questionRef: "fgm3-019",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 19,
    points: 1,
    difficulty: "hard",
    topicTag: "cave_tour",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["nature", "places"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Where is the cave entrance?",
    choices: [
      { text: "At the bottom of the cliff path", isCorrect: true },
      { text: "On the school roof", isCorrect: false },
      { text: "Inside the supermarket", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "The cave entrance is at the bottom of the cliff path by the sea.",
    },
  }),

  goldMcq({
    questionRef: "fgm3-020",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 20,
    points: 1,
    difficulty: "hard",
    topicTag: "holiday_plan",
    grammarTags: ["future_will"],
    vocabularyTopics: ["leisure", "travel"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What will the family do on the first day of their holiday?",
    choices: [
      { text: "Explore a coastal nature reserve", isCorrect: true },
      { text: "Stay in bed all day", isCorrect: false },
      { text: "Take an exam", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "On the first day of their holiday the family will explore a coastal nature reserve.",
    },
  }),

  goldMcq({
    questionRef: "fgm3-021",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 21,
    points: 1,
    difficulty: "medium",
    topicTag: "wildlife_talk",
    grammarTags: ["superlatives"],
    vocabularyTopics: ["nature", "animals"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Which animal was the most surprising to see?",
    choices: [
      { text: "The otter", isCorrect: true },
      { text: "The goldfish in a bowl", isCorrect: false },
      { text: "The toy dinosaur", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "The otter was the most surprising animal to see on the river walk.",
    },
  }),

  goldMcq({
    questionRef: "fgm3-022",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 22,
    points: 1,
    difficulty: "easy",
    topicTag: "park_scene",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["nature", "colours"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Colour the flowers in the planter. Which colour?",
    choices: [
      { text: "Bright pink", isCorrect: true },
      { text: "Grey", isCorrect: false },
      { text: "Black", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Colour the flowers in the planter bright pink.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMcq({
    questionRef: "fgm3-023",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 23,
    points: 1,
    difficulty: "medium",
    topicTag: "park_scene",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["leisure", "nature"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Draw a kite in the sky. Where?",
    choices: [
      { text: "Above the picnic area", isCorrect: true },
      { text: "Under the bench", isCorrect: false },
      { text: "Inside the pond", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Draw a kite in the sky above the picnic area.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMcq({
    questionRef: "fgm3-024",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 24,
    points: 1,
    difficulty: "easy",
    topicTag: "park_scene",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["feelings", "clothes"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Colour the girl's scarf. Which colour?",
    choices: [
      { text: "Sky blue", isCorrect: true },
      { text: "Dark brown", isCorrect: false },
      { text: "Orange", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Colour the girl's scarf sky blue.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMcq({
    questionRef: "fgm3-025",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 25,
    points: 1,
    difficulty: "hard",
    topicTag: "park_scene",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["nature", "places"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Draw an arrow from the boy to the lake. Which picture?",
    choices: [
      { text: "Boy facing the lake", isCorrect: true },
      { text: "Boy walking away from the park", isCorrect: false },
      { text: "Boy inside a bus", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Draw an arrow from the boy to the lake.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMcq({
    questionRef: "fgm3-026",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 26,
    points: 1,
    difficulty: "medium",
    topicTag: "park_scene",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["nature", "animals"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Draw two ducks on the pond. How many?",
    choices: [
      { text: "Two ducks", isCorrect: true },
      { text: "One duck", isCorrect: false },
      { text: "Five ducks", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Draw two ducks on the pond near the reeds.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMcq({
    questionRef: "fgm3-027",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 27,
    points: 1,
    difficulty: "hard",
    topicTag: "park_scene",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["leisure"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Colour the picnic blanket. Which colour?",
    choices: [
      { text: "Red and white checks", isCorrect: true },
      { text: "Plain silver", isCorrect: false },
      { text: "Dark purple only", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Colour the picnic blanket red and white checks.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMcq({
    questionRef: "fgm3-028",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 28,
    points: 1,
    difficulty: "medium",
    topicTag: "park_scene",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["nature", "leisure"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Draw a butterfly near the flowers. Which picture?",
    choices: [
      { text: "Butterfly beside the flower bed", isCorrect: true },
      { text: "Butterfly on the moon", isCorrect: false },
      { text: "Butterfly under the road", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Draw a butterfly beside the flower bed.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMatching({
    questionRef: "fgm3-029",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 29,
    points: 1,
    difficulty: "easy",
    topicTag: "woodland",
    grammarTags: ["articles"],
    vocabularyTopics: ["nature"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "meadow", rightText: "Grassy field full of wild flowers" }],
  }),

  goldMatching({
    questionRef: "fgm3-030",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 30,
    points: 1,
    difficulty: "medium",
    topicTag: "emotions",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "relieved", rightText: "Feeling happy because a worry has gone" }],
  }),

  goldMatching({
    questionRef: "fgm3-031",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 31,
    points: 1,
    difficulty: "easy",
    topicTag: "weekend_fun",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["leisure"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "board game", rightText: "Game you play on a table with pieces and rules" }],
  }),

  goldMatching({
    questionRef: "fgm3-032",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 32,
    points: 1,
    difficulty: "medium",
    topicTag: "coastline",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["nature", "places"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "cliff", rightText: "High rock face beside the sea" }],
  }),

  goldMatching({
    questionRef: "fgm3-033",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 33,
    points: 1,
    difficulty: "hard",
    topicTag: "feelings_face",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "embarrassed", rightText: "Feeling shy or uncomfortable in front of others" }],
  }),

  goldMatching({
    questionRef: "fgm3-034",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 34,
    points: 1,
    difficulty: "easy",
    topicTag: "outdoor_fun",
    grammarTags: ["possessives"],
    vocabularyTopics: ["leisure", "sports"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "frisbee", rightText: "Flat disc you throw and catch in the park" }],
  }),

  goldMatching({
    questionRef: "fgm3-035",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 35,
    points: 1,
    difficulty: "hard",
    topicTag: "wildlife",
    grammarTags: ["superlatives"],
    vocabularyTopics: ["nature", "animals"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "habitat", rightText: "Natural home where an animal or plant lives" }],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-036",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 36,
    points: 1,
    difficulty: "easy",
    topicTag: "butterfly_garden",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["nature", "animals"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "The school butterfly garden attracts bees and colourful insects every spring.",
    choices: [
      { text: "Garden with butterflies and flowers", isCorrect: true },
      { text: "Busy motorway", isCorrect: false },
      { text: "Underground train", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-037",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 37,
    points: 1,
    difficulty: "medium",
    topicTag: "concert_excited",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["leisure", "feelings"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "The crowd is cheering because their favourite band is playing on stage.",
    choices: [
      { text: "Excited crowd at a concert", isCorrect: true },
      { text: "Empty library", isCorrect: false },
      { text: "Quiet hospital ward", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-038",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 38,
    points: 1,
    difficulty: "hard",
    topicTag: "forest_rescue",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["nature", "feelings"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "Last week rangers rescued a young fox that was trapped near the forest path.",
    choices: [
      { text: "Rangers helping a fox", isCorrect: true },
      { text: "Children in a maths lesson", isCorrect: false },
      { text: "Shoppers in a mall", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-039",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 39,
    points: 1,
    difficulty: "medium",
    topicTag: "holiday_packing",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["leisure", "travel"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "We are going to pack swimming costumes and sun hats for our lakeside holiday.",
    choices: [
      { text: "Family packing holiday bags", isCorrect: true },
      { text: "Snowboarding competition", isCorrect: false },
      { text: "Factory machine", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-040",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 40,
    points: 1,
    difficulty: "easy",
    topicTag: "calm_lake",
    grammarTags: ["have_got"],
    vocabularyTopics: ["nature", "leisure"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "The lake has got clear water and small boats for visitors to rent.",
    choices: [
      { text: "Calm lake with rental boats", isCorrect: true },
      { text: "Desert road", isCorrect: false },
      { text: "Office desk", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-041",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 41,
    points: 1,
    difficulty: "hard",
    topicTag: "worried_climber",
    grammarTags: ["past_continuous"],
    vocabularyTopics: ["feelings", "nature"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "While the wind was blowing, the climber was feeling nervous on the narrow ridge.",
    choices: [
      { text: "Climber on a windy ridge", isCorrect: true },
      { text: "Person sleeping peacefully", isCorrect: false },
      { text: "Cooking in a kitchen", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-042",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 42,
    points: 1,
    difficulty: "medium",
    topicTag: "film_night",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["leisure", "friends"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "Friends can borrow films from the library and watch them together at home.",
    choices: [
      { text: "Friends watching a film at home", isCorrect: true },
      { text: "Farmers harvesting wheat", isCorrect: false },
      { text: "Divers in a coral cave", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-043",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 43,
    points: 1,
    difficulty: "medium",
    topicTag: "rainforest_article",
    grammarTags: ["past_simple", "present_simple"],
    vocabularyTopics: ["nature", "environment"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Rainforest Diary — Day 2\n\nWe walked beneath tall trees and heard monkeys calling above us. Our guide explained how plants and animals depend on each other. Yesterday we saw a bright tree frog near a stream. Tonight we are going to camp beside a waterfall and listen for night birds. Protecting the forest is important for the whole planet.",
    choices: [
      { text: "They heard monkeys in the rainforest.", isCorrect: true },
      { text: "They camped in a shopping centre.", isCorrect: false },
      { text: "They saw no animals.", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-044",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 44,
    points: 1,
    difficulty: "hard",
    topicTag: "lighthouse_history",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["nature", "places"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Harbour Lighthouse was built in 1871 on a rocky headland. Keepers guided ships safely for many years before modern radar existed. During a fierce storm in 1953, the lamp stayed lit all night. Today visitors can climb the tower and learn about sea rescue. On clear evenings the view of the coastline is breathtaking.",
    choices: [
      { text: "The lighthouse helped guide ships.", isCorrect: true },
      { text: "It was built last month.", isCorrect: false },
      { text: "Visitors cannot enter the tower.", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-045",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 45,
    points: 1,
    difficulty: "medium",
    topicTag: "feelings_blog",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["feelings", "school"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "My Feelings Journal\n\nI am preparing for the school play and I feel excited but also a little nervous. My friends are practising their lines in the drama room. We are helping each other remember when to speak. The teacher says it is normal to feel worried before a performance. I think the audience will enjoy the story.",
    choices: [
      { text: "The writer feels excited and a little nervous.", isCorrect: true },
      { text: "The writer feels bored and angry.", isCorrect: false },
      { text: "There is no school play.", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-046",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 46,
    points: 1,
    difficulty: "easy",
    topicTag: "leisure_magazine",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["leisure", "sports"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Summer Leisure Guide\n\nSwimmers must shower before entering the pool. You mustn't run on the wet floor because it is slippery. The outdoor cinema shows family films every Friday. Tennis courts are free before ten o'clock in the morning. Next week the park is going to host a kite-flying festival.",
    choices: [
      { text: "The outdoor cinema shows films on Fridays.", isCorrect: true },
      { text: "Runners can sprint on the wet floor.", isCorrect: false },
      { text: "The tennis courts are always closed.", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-047",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 47,
    points: 1,
    difficulty: "hard",
    topicTag: "lost_trail",
    grammarTags: ["past_continuous"],
    vocabularyTopics: ["nature", "feelings"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "When the forest path split in two directions, Leo felt confused. He was checking the map while his sister was listening for the stream they had crossed earlier. They were getting tired because the sun was setting quickly. A ranger appeared with a torch and calmly led them back to the campsite. Leo felt grateful and promised to stay on marked trails.",
    choices: [
      { text: "A ranger helped them return to the campsite.", isCorrect: true },
      { text: "They continued deeper into the forest alone.", isCorrect: false },
      { text: "They were at the cinema.", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-048",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 48,
    points: 1,
    difficulty: "medium",
    topicTag: "activity_comparison",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["leisure", "feelings"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Reading a book by the lake is quieter than playing volleyball on the beach. Some people find fishing more relaxing than cycling uphill. Others say team sports feel more exciting than sitting still. Doctors remind us that different leisure activities suit different moods, and it is good to try more than one.",
    choices: [
      { text: "Different activities suit different moods.", isCorrect: true },
      { text: "Everyone prefers the same activity.", isCorrect: false },
      { text: "Reading is always louder than volleyball.", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "fgm3-049",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 49,
    points: 1,
    difficulty: "hard",
    topicTag: "nature_festival",
    grammarTags: ["superlatives"],
    vocabularyTopics: ["nature", "leisure"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "The Lakeside Nature Festival was the most popular event of the summer. The bird-watching walk was the quietest activity, but the canoe race was the most thrilling. Many families said the sunset picnic was the most beautiful moment of the day. The recycled-art workshop was the most creative stall. Visitors agreed the lake setting was the best part of the festival.",
    choices: [
      { text: "Many families enjoyed the sunset picnic.", isCorrect: true },
      { text: "No one watched birds.", isCorrect: false },
      { text: "The festival happened indoors.", isCorrect: false },
    ],
  }),

  goldWriting({
    questionRef: "fgm3-050",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 50,
    points: 1,
    difficulty: "medium",
    topicTag: "nature_trip_message",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["nature", "friends"],
    skillTag: "writing",
    questionText: "Write a message about a nature trip you are planning.",
    cambridgeTaskType: "write_note",
    prompt:
      "Write a message to a friend about a nature trip you are planning. Say where you are going, what you hope to see, and why you think your friend would enjoy it.",
    minWords: 25,
    maxWords: 60,
    taskDescription: "Invite your friend on a nature trip.",
    requiredPoints: [
      "Say where you are going",
      "Explain what you hope to see or do",
      "Say why your friend might enjoy it",
      "Ask your friend to come with you",
    ],
  }),

  goldWriting({
    questionRef: "fgm3-051",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 51,
    points: 1,
    difficulty: "easy",
    topicTag: "feelings_note",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["feelings", "friends"],
    skillTag: "writing",
    questionText: "Write a note to a friend about how you felt after an event.",
    cambridgeTaskType: "write_note",
    prompt:
      "Write a note to a friend explaining how you felt after a school event or performance. Describe what happened and why you felt that way.",
    minWords: 22,
    maxWords: 55,
    taskDescription: "Describe your feelings after an event.",
    requiredPoints: [
      "Say which event you are writing about",
      "Describe how you felt and why",
      "Mention one thing that happened",
      "Ask your friend about a similar experience",
    ],
  }),

  goldWriting({
    questionRef: "fgm3-052",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 52,
    points: 1,
    difficulty: "medium",
    topicTag: "leisure_recommendation",
    grammarTags: ["past_simple", "present_simple"],
    vocabularyTopics: ["leisure"],
    skillTag: "writing",
    questionText: "Write a note recommending a leisure activity.",
    cambridgeTaskType: "write_note",
    prompt:
      "Write a note to a classmate recommending a leisure activity you tried recently. Explain what you did and give your honest opinion.",
    minWords: 25,
    maxWords: 60,
    taskDescription: "Recommend a leisure activity.",
    requiredPoints: [
      "Say which activity you tried",
      "Describe what you did",
      "Give your opinion and reasons",
      "Say who else might enjoy it",
    ],
  }),

  goldWriting({
    questionRef: "fgm3-053",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 53,
    points: 1,
    difficulty: "medium",
    topicTag: "story_forest",
    grammarTags: ["past_simple", "past_continuous"],
    vocabularyTopics: ["nature", "feelings"],
    skillTag: "writing",
    questionText: "Write a story called 'The Whispering Trees'.",
    cambridgeTaskType: "write_story",
    prompt:
      "Write a story called 'The Whispering Trees'. Include what the characters discovered in the forest, how they felt, and how the adventure ended.",
    minWords: 40,
    maxWords: 95,
    taskDescription: "Write a forest adventure story.",
    requiredPoints: [
      "Set the story in a natural place",
      "Include a surprise or problem",
      "Describe how characters felt",
      "Explain how the story ended",
    ],
  }),

  goldWriting({
    questionRef: "fgm3-054",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 54,
    points: 1,
    difficulty: "hard",
    topicTag: "story_holiday",
    grammarTags: ["past_simple", "linking_words"],
    vocabularyTopics: ["leisure", "feelings"],
    skillTag: "writing",
    questionText: "Write a story about a holiday that did not go as planned.",
    cambridgeTaskType: "write_story",
    prompt:
      "Write a story about a holiday that did not go as planned. Describe what went wrong, how the characters felt, and what they did next.",
    minWords: 45,
    maxWords: 100,
    taskDescription: "Write a holiday story with a problem.",
    requiredPoints: [
      "Explain what the characters expected",
      "Describe the problem that happened",
      "Say how the characters felt",
      "Explain what they did in the end",
    ],
  }),

  goldWriting({
    questionRef: "fgm3-055",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 55,
    points: 1,
    difficulty: "medium",
    topicTag: "waterfall_scene",
    grammarTags: ["present_continuous", "prepositions"],
    vocabularyTopics: ["nature", "leisure"],
    skillTag: "writing",
    questionText: "Read the scene below. Write about the waterfall scene.",
    cambridgeTaskType: "picture_description",
    prompt:
      "Read the scene below. Write three or four sentences about the waterfall scene. Say what people and animals are doing and describe the natural surroundings.",
    minWords: 15,
    maxWords: 50,
    taskDescription: "Describe the waterfall scene.",
    requiredPoints: [
      "Describe the natural surroundings",
      "Say what at least two people or animals are doing",
      "Add a detail that shows how the place feels",
    ],
  }),

  goldWriting({
    questionRef: "fgm3-056",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 56,
    points: 1,
    difficulty: "hard",
    topicTag: "leisure_park",
    grammarTags: ["there_is_are", "comparatives"],
    vocabularyTopics: ["leisure", "nature"],
    skillTag: "writing",
    questionText: "Read the scene below. Write about the leisure park.",
    cambridgeTaskType: "picture_description",
    prompt:
      "Read the scene below. Write three or four sentences about the leisure park. Compare two areas and say what visitors are enjoying.",
    minWords: 15,
    maxWords: 55,
    taskDescription: "Describe the leisure park.",
    requiredPoints: [
      "Compare two areas or activities in the picture",
      "Say what visitors are enjoying",
      "Use your own words to describe the atmosphere",
    ],
  }),

  goldSpeaking({
    questionRef: "fgm3-057",
    partSlug: "speaking-part-1",
    sectionSlug: "speaking",
    sortOrder: 57,
    points: 5,
    difficulty: "medium",
    topicTag: "park_differences",
    grammarTags: ["there_is_are", "prepositions"],
    vocabularyTopics: ["nature", "leisure"],
    skillTag: "speaking",
    questionText: "Read the two scenes below. Tell your partner about the differences.",
    cambridgeTaskType: "speaking_picture_description",
    prompt:
      "Read the two descriptions of a nature park. Tell your partner about five differences between them. Describe what you see and how the scene feels.",
    taskDescription: `Scene A: A nature park with hikers on a forest trail, a canoe on the lake, and sunny weather.
Scene B: The same park with hikers in raincoats, no canoe, and dark clouds.`,
    maxDurationSeconds: 120,
    followUpQuestions: [
      "What is different about the trees in Scene B?",
      "How many people are sitting by the lake in Scene A?",
      "Is there a kite in both scenes?",
      "Where is the dog in Scene B?",
      "What colour are the flowers in Scene A?",
    ],
  }),

  goldSpeaking({
    questionRef: "fgm3-058",
    partSlug: "speaking-part-2",
    sectionSlug: "speaking",
    sortOrder: 58,
    points: 5,
    difficulty: "easy",
    topicTag: "about_nature_feelings",
    grammarTags: ["present_simple", "present_continuous"],
    vocabularyTopics: ["nature", "feelings", "leisure"],
    skillTag: "speaking",
    questionText: "Answer the examiner's questions about nature, feelings and free time.",
    cambridgeTaskType: "speaking_personal_questions",
    prompt:
      "The examiner will ask you about nature, how you feel in different situations, and how you spend your free time. Answer in your own words and give examples from your life.",
    maxDurationSeconds: 180,
    followUpQuestions: [
      "Tell me about a place in nature you like visiting. Why do you enjoy it?",
      "How do you usually feel before a test or performance?",
      "What do you like doing with friends at the weekend?",
      "Describe a time when you felt proud of something you did.",
      "If you could spend a day anywhere outdoors, where would you go and why?",
    ],
  }),

  goldSpeaking({
    questionRef: "fgm3-059",
    partSlug: "speaking-part-3",
    sectionSlug: "speaking",
    sortOrder: 59,
    points: 5,
    difficulty: "hard",
    topicTag: "story_camping",
    grammarTags: ["past_simple", "past_continuous"],
    vocabularyTopics: ["nature", "feelings", "leisure"],
    skillTag: "speaking",
    questionText: "Use the story outline and tell the story.",
    cambridgeTaskType: "speaking_storytelling",
    prompt:
      "Use the story outline to tell the story of a family camping trip by the lake. Describe what happened, how people felt at different moments, and how the trip ended.",
    taskDescription: `Story outline:
1. A family arrives at a lakeside campsite.
2. Heavy rain starts and everyone looks worried.
3. They shelter in their tent and stay warm.
4. The rain stops and they watch stars in the clear night sky.`,
    maxDurationSeconds: 180,
    followUpQuestions: [
      "Why did the family choose to camp by the lake?",
      "What happened when the weather changed?",
      "How did the family feel during the problem?",
      "What did they do to stay comfortable?",
      "How did they feel when they saw the stars?",
    ],
  }),
];

export const FLYERS_GOLD_MOCK_3 = composeGoldMockManifest({
  level: "flyers",
  goldMockId: "flyers-gold-mock-3",
  title: "Cambridge Flyers Gold Mock 3",
  description:
    "Manually authored A2 Flyers gold mock 3 — nature, feelings and leisure themes with open-ended writing and natural speaking prompts.",
  questions: uniquifyQuestionStems(QUESTIONS),
  parts: [
    listeningAudio(
      "listening-part-1",
      1,
      "Link names to descriptions",
      "Examiner: Look at the pictures. Listen and draw a line from each name to the correct person.\n\nThis is Dr Tan. She's pointing at birds with her binoculars.\nHugo's building a sandcastle near the sea.\nMei is sketching wild flowers in her woodland notebook.\nMr Costa plays guitar while families relax on the grass every Sunday.\nRuby's got a hat with a bright butterfly badge on it.\nSamir is standing beside a canoe on the riverbank with his team.\nThe ranger showed a trail map at the hilltop viewpoint yesterday evening."
    ),
    listeningAudio(
      "listening-part-2",
      2,
      "Write words or numbers",
      "Examiner: Listen and write the missing word or number.\n\nTomorrow the temperature will be nineteen degrees with sunny spells.\nThe children are looking for a deer on the nature trail.\nThe film starts at quarter past four this afternoon.\nThey are going to camp for two nights in the forest.\nThe waterfall path opened in two thousand twenty.\nIvy swam across the lake faster than anyone else in the group.\nYou need six apples for the picnic fruit salad."
    ),
    listeningAudio(
      "listening-part-3",
      3,
      "Choose the correct answer",
      "Examiner: Listen and Choose the correct answer.\n\nThe children are watching colourful birds in the trees near the lake.\nAt the theme park visitors can ride a fast wooden roller coaster.\nDuring the hike it started raining heavily so they put on waterproof jackets.\nThe leisure centre offers swimming and badminton on Fridays.\nThe cave entrance is at the bottom of the cliff path by the sea.\nOn the first day of their holiday the family will explore a coastal nature reserve.\nThe otter was the most surprising animal to see on the river walk."
    ),
    listeningAudio(
      "listening-part-4",
      4,
      "Colour and draw",
      "Examiner: Listen and colour or draw.\n\nColour the flowers in the planter bright pink.\nDraw a kite in the sky above the picnic area.\nColour the girl's scarf sky blue.\nDraw an arrow from the boy to the lake.\nDraw two ducks on the pond near the reeds.\nColour the picnic blanket red and white checks.\nDraw a butterfly beside the flower bed."
    ),
  ],
});
