import { composeGoldMockManifest } from "@/lib/cambridge-assessment/gold-mocks/gold-mock-compose";
import {
  goldGapFill,
  goldMatching,
  goldMcq,
  goldReadingComprehension,
  goldSpeaking,
  goldWriting,
  listeningAudio,
  readingSectionSlug,
} from "@/lib/cambridge-assessment/gold-mocks/gold-mock-helpers";

const RW = readingSectionSlug("ket");
let sort = 0;

const KET_RW3_PASSAGE = `Last Saturday, our class visited the city science museum. We arrived at ten o'clock and met our guide, Mr Patel. First, we watched a short film about planets. Then we tried interactive experiments in the energy room. My favourite part was the robot workshop, where we programmed a small robot to move in a square. At lunchtime, we ate sandwiches in the café and talked about what we had learned. Before we left, the museum shop sold postcards and science kits. Everyone agreed it was an interesting and fun trip.`;

const KET_RW4_TEXT =
  "Many teenagers enjoy learning English through films and music. When you watch a film in English, you can hear natural (1) ___ and learn new expressions. Some students write down useful phrases and (2) ___ them later. Reading short stories is also helpful because you see grammar in (3) ___. Online language apps can remind you to study every day and track your (4) ___. However, the best way to improve is to use English regularly with other (5) ___. Joining a conversation club at school gives you a chance to speak without (6) ___.";

const ketQuestions = [
  // ── rw-part-1: signs & messages (6 MCQ) ──────────────────────────────────
  goldMcq({
    questionRef: "kgm-001",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "transport",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["transport"],
    skillTag: "reading",
    questionText: "NO ENTRY — Staff only beyond this point.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Visitors may go through if they ask.", isCorrect: false },
      { text: "Only workers can go past this door.", isCorrect: true },
      { text: "The exit is closed for cleaning.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-002",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "leisure",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["leisure"],
    skillTag: "reading",
    questionText: "Library closed for repairs until 15 March.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "You can borrow books today.", isCorrect: false },
      { text: "The library will open again after 15 March.", isCorrect: true },
      { text: "Repairs finished yesterday.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-003",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "food",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["food"],
    skillTag: "reading",
    questionText: "Café special: Buy one sandwich, get a free drink.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Drinks are cheaper than sandwiches.", isCorrect: false },
      { text: "You receive a drink at no extra cost with a sandwich.", isCorrect: true },
      { text: "Sandwiches are free today.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-004",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["future_will"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Parents' evening — Thursday 6 p.m. Please book online.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Parents must make an appointment on the website.", isCorrect: true },
      { text: "The meeting is only for teachers.", isCorrect: false },
      { text: "Parents should arrive without booking.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-005",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "sports",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["sports"],
    skillTag: "reading",
    questionText: "Sports hall in use — basketball training until 5 p.m.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "You can play football there now.", isCorrect: false },
      { text: "The hall is busy because of basketball practice.", isCorrect: true },
      { text: "Training finished at 3 p.m.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-006",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "travel",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["travel"],
    skillTag: "reading",
    questionText: "Flight delayed — new departure time 18:40, Gate 12.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Passengers should go to Gate 12 later than planned.", isCorrect: true },
      { text: "The flight has been cancelled.", isCorrect: false },
      { text: "Gate 12 is closed.", isCorrect: false },
    ],
  }),

  // ── rw-part-2: multiple matching (7) ─────────────────────────────────────
  goldMatching({
    questionRef: "kgm-007",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "hobbies",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["hobbies"],
    skillTag: "reading",
    questionText: "Who enjoys painting landscapes?",
    pairs: [{ leftText: "Elena", rightText: "paints landscapes in her free time" }],
  }),
  goldMatching({
    questionRef: "kgm-008",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "sports",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["sports"],
    skillTag: "reading",
    questionText: "Who trains for swimming competitions?",
    pairs: [{ leftText: "Omar", rightText: "swims every morning before school" }],
  }),
  goldMatching({
    questionRef: "kgm-009",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "technology",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["technology"],
    skillTag: "reading",
    questionText: "Who is learning to build mobile apps?",
    pairs: [{ leftText: "Priya", rightText: "is taking an online coding course" }],
  }),
  goldMatching({
    questionRef: "kgm-010",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "music",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "Who played guitar in a school concert last term?",
    pairs: [{ leftText: "Luca", rightText: "performed with the school band" }],
  }),
  goldMatching({
    questionRef: "kgm-011",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "nature",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["nature"],
    skillTag: "reading",
    questionText: "Who volunteers at an animal rescue centre?",
    pairs: [{ leftText: "Hana", rightText: "helps look after rescued dogs" }],
  }),
  goldMatching({
    questionRef: "kgm-012",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "food",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["food"],
    skillTag: "reading",
    questionText: "Who is going to start a cooking blog?",
    pairs: [{ leftText: "Diego", rightText: "plans to share family recipes online" }],
  }),
  goldMatching({
    questionRef: "kgm-013",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "community",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["community"],
    skillTag: "reading",
    questionText: "Who has organised a neighbourhood clean-up day?",
    pairs: [{ leftText: "Aisha", rightText: "has invited local families to collect litter" }],
  }),

  // ── rw-part-3: reading comprehension (5) ─────────────────────────────────
  goldReadingComprehension({
    questionRef: "kgm-014",
    partSlug: "rw-part-3",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "What time did the class arrive at the museum?",
    passage: KET_RW3_PASSAGE,
    choices: [
      { text: "At ten o'clock", isCorrect: true },
      { text: "At lunchtime", isCorrect: false },
      { text: "Before the shop opened", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "kgm-015",
    partSlug: "rw-part-3",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "technology",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["technology"],
    skillTag: "reading",
    questionText: "What did the students do in the robot workshop?",
    passage: KET_RW3_PASSAGE,
    choices: [
      { text: "They programmed a robot to move in a square.", isCorrect: true },
      { text: "They watched a film about robots.", isCorrect: false },
      { text: "They bought a science kit.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "kgm-016",
    partSlug: "rw-part-3",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "leisure",
    grammarTags: ["superlatives"],
    vocabularyTopics: ["leisure"],
    skillTag: "reading",
    questionText: "Which activity did the writer like most?",
    passage: KET_RW3_PASSAGE,
    choices: [
      { text: "The robot workshop", isCorrect: true },
      { text: "The planet film", isCorrect: false },
      { text: "Eating in the café", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "kgm-017",
    partSlug: "rw-part-3",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "food",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["food"],
    skillTag: "reading",
    questionText: "What did the class eat at lunchtime?",
    passage: KET_RW3_PASSAGE,
    choices: [
      { text: "Sandwiches", isCorrect: true },
      { text: "Hot meals from the restaurant", isCorrect: false },
      { text: "Nothing — they left early", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "kgm-018",
    partSlug: "rw-part-3",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "shopping",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["shopping"],
    skillTag: "reading",
    questionText: "What could students buy before leaving?",
    passage: KET_RW3_PASSAGE,
    choices: [
      { text: "Postcards and science kits", isCorrect: true },
      { text: "Tickets for another visit", isCorrect: false },
      { text: "Robot parts", isCorrect: false },
    ],
  }),

  // ── rw-part-4: multiple-choice cloze (6) ─────────────────────────────────
  goldMcq({
    questionRef: "kgm-019",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["articles"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Gap (1): natural ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 0 },
    choices: [
      { text: "speech", isCorrect: true },
      { text: "speeches", isCorrect: false },
      { text: "speaking", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-020",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Gap (2): ___ them later",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 1 },
    choices: [
      { text: "review", isCorrect: true },
      { text: "reviewed", isCorrect: false },
      { text: "reviewing", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-021",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Gap (3): grammar in ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 2 },
    choices: [
      { text: "context", isCorrect: true },
      { text: "contexts", isCorrect: false },
      { text: "contextual", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-022",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "technology",
    grammarTags: ["articles"],
    vocabularyTopics: ["technology"],
    skillTag: "reading",
    questionText: "Gap (4): track your ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 3 },
    choices: [
      { text: "progress", isCorrect: true },
      { text: "progresses", isCorrect: false },
      { text: "progressive", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-023",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "friends",
    grammarTags: ["articles"],
    vocabularyTopics: ["friends"],
    skillTag: "reading",
    questionText: "Gap (5): with other ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 4 },
    choices: [
      { text: "people", isCorrect: true },
      { text: "person", isCorrect: false },
      { text: "peoples", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-024",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "feelings",
    grammarTags: ["articles"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "Gap (6): speak without ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 5 },
    choices: [
      { text: "fear", isCorrect: true },
      { text: "afraid", isCorrect: false },
      { text: "fearful", isCorrect: false },
    ],
  }),

  // ── rw-part-5: open cloze (6) ────────────────────────────────────────────
  goldGapFill({
    questionRef: "kgm-025",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "travel",
    grammarTags: ["articles"],
    vocabularyTopics: ["travel"],
    skillTag: "reading",
    questionText: "We took ___ train to the coast.",
    template: "We took [0] train to the coast.",
    correctAnswers: ["the"],
  }),
  goldGapFill({
    questionRef: "kgm-026",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "weather",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["weather"],
    skillTag: "reading",
    questionText: "It ___ raining when we arrived.",
    template: "It [0] raining when we arrived.",
    correctAnswers: ["was"],
  }),
  goldGapFill({
    questionRef: "kgm-027",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "home",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["home"],
    skillTag: "reading",
    questionText: "She is interested ___ learning Spanish.",
    template: "She is interested [0] learning Spanish.",
    correctAnswers: ["in"],
  }),
  goldGapFill({
    questionRef: "kgm-028",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "health",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["health"],
    skillTag: "reading",
    questionText: "Walking is ___ than driving in the city centre.",
    template: "Walking is [0] than driving in the city centre.",
    correctAnswers: ["healthier"],
  }),
  goldGapFill({
    questionRef: "kgm-029",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "jobs",
    grammarTags: ["relative_clauses"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "The woman ___ works in the bookshop is my aunt.",
    template: "The woman [0] works in the bookshop is my aunt.",
    correctAnswers: ["who"],
  }),
  goldGapFill({
    questionRef: "kgm-030",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "environment",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["environment"],
    skillTag: "reading",
    questionText: "We ___ recycle plastic bottles at school.",
    template: "We [0] recycle plastic bottles at school.",
    correctAnswers: ["must"],
  }),

  // ── rw-part-6 & 7: writing ─────────────────────────────────────────────────
  goldWriting({
    questionRef: "kgm-031",
    partSlug: "rw-part-6",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 15,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["future_will", "imperatives"],
    vocabularyTopics: ["school"],
    skillTag: "writing",
    questionText: "Write an email to your English teacher.",
    cambridgeTaskType: "write_email",
    prompt:
      "Your English class is going on a trip to the theatre next Friday. Write an email to your teacher.",
    taskDescription: "Write 25–35 words. Include all three points.",
    minWords: 25,
    maxWords: 35,
    requiredPoints: [
      "Say whether you can come on the trip",
      "Explain how you will travel to the theatre",
      "Ask one question about the visit",
    ],
  }),
  goldWriting({
    questionRef: "kgm-032",
    partSlug: "rw-part-7",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 15,
    difficulty: "medium",
    topicTag: "leisure",
    grammarTags: ["past_simple", "linking_words"],
    vocabularyTopics: ["leisure"],
    skillTag: "writing",
    questionText: "Write a story about a lost dog.",
    cambridgeTaskType: "write_story",
    prompt:
      "Your English teacher has asked you to write a story. Your story must begin with this sentence: 'The dog ran into the park.'",
    taskDescription: "Write 35 words or more.",
    minWords: 35,
    maxWords: 100,
  }),

  // ── listening-part-1: MCQ pictures (5) ────────────────────────────────────
  goldMcq({
    questionRef: "kgm-033",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "food",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["food"],
    skillTag: "listening",
    questionText: "What is the woman buying?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Apples", isCorrect: true },
      { text: "Bread", isCorrect: false },
      { text: "Cheese", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-034",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "transport",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["transport"],
    skillTag: "listening",
    questionText: "Where are the children waiting?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "At a bus stop", isCorrect: true },
      { text: "At a train station", isCorrect: false },
      { text: "Outside a café", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-035",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "sports",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["sports"],
    skillTag: "listening",
    questionText: "What sport are they playing?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Tennis", isCorrect: true },
      { text: "Football", isCorrect: false },
      { text: "Swimming", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-036",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "home",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["home"],
    skillTag: "listening",
    questionText: "What is the man doing in the kitchen?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Washing dishes", isCorrect: true },
      { text: "Cooking pasta", isCorrect: false },
      { text: "Making coffee", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-037",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "weather",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["weather"],
    skillTag: "listening",
    questionText: "What is the weather like?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "It is snowing", isCorrect: true },
      { text: "It is sunny", isCorrect: false },
      { text: "It is windy", isCorrect: false },
    ],
  }),

  // ── listening-part-2: MCQ questions (5) ────────────────────────────────────
  goldMcq({
    questionRef: "kgm-038",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "Why was the boy late for school?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "His alarm did not ring", isCorrect: true },
      { text: "He missed the bus", isCorrect: false },
      { text: "He lost his bag", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-039",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "hobbies",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["hobbies"],
    skillTag: "listening",
    questionText: "How often does Anna go to the gym?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Twice a week", isCorrect: true },
      { text: "Every day", isCorrect: false },
      { text: "Once a month", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-040",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "travel",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["travel"],
    skillTag: "listening",
    questionText: "Where are they going on holiday?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "To the mountains", isCorrect: true },
      { text: "To the beach", isCorrect: false },
      { text: "To a big city", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-041",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "technology",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["technology"],
    skillTag: "listening",
    questionText: "What has Tom already finished?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "His science project", isCorrect: true },
      { text: "His history homework", isCorrect: false },
      { text: "His maths test", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-042",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "health",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["health"],
    skillTag: "listening",
    questionText: "What does the doctor tell the patient to do?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Rest for two days", isCorrect: true },
      { text: "Take more exercise", isCorrect: false },
      { text: "Change his diet completely", isCorrect: false },
    ],
  }),

  // ── listening-part-3: gap fill (5) ───────────────────────────────────────
  goldGapFill({
    questionRef: "kgm-043",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "places",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["places"],
    skillTag: "listening",
    questionText: "The museum opens at ___ o'clock.",
    template: "The museum opens at [0] o'clock.",
    correctAnswers: ["nine", "9"],
  }),
  goldGapFill({
    questionRef: "kgm-044",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "transport",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["transport"],
    skillTag: "listening",
    questionText: "Meet me ___ the library entrance.",
    template: "Meet me [0] the library entrance.",
    correctAnswers: ["at"],
  }),
  goldGapFill({
    questionRef: "kgm-045",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "time",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["time"],
    skillTag: "listening",
    questionText: "The film starts at quarter ___ seven.",
    template: "The film starts at quarter [0] seven.",
    correctAnswers: ["past", "to"],
  }),
  goldGapFill({
    questionRef: "kgm-046",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "shopping",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["shopping"],
    skillTag: "listening",
    questionText: "Please bring a ___ of water.",
    template: "Please bring a [0] of water.",
    correctAnswers: ["bottle"],
  }),
  goldGapFill({
    questionRef: "kgm-047",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "jobs",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["jobs"],
    skillTag: "listening",
    questionText: "She ___ as a nurse in the local hospital.",
    template: "She [0] as a nurse in the local hospital.",
    correctAnswers: ["works", "worked"],
  }),

  // ── listening-part-4: MCQ monologue (5) ────────────────────────────────────
  goldMcq({
    questionRef: "kgm-048",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "animals",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["animals"],
    skillTag: "listening",
    questionText: "What is the speaker's favourite animal?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Dolphins", isCorrect: true },
      { text: "Horses", isCorrect: false },
      { text: "Rabbits", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-049",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "culture",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "When did the speaker learn to play the piano?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "At the age of seven", isCorrect: true },
      { text: "At secondary school", isCorrect: false },
      { text: "Last year", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-050",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "environment",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["environment"],
    skillTag: "listening",
    questionText: "Why does the speaker recycle at home?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "To protect the environment", isCorrect: true },
      { text: "Because it is the law", isCorrect: false },
      { text: "To save money on bills", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-051",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "family",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["family"],
    skillTag: "listening",
    questionText: "Who does the speaker usually cook dinner with?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Her grandmother", isCorrect: true },
      { text: "Her brother", isCorrect: false },
      { text: "Her neighbour", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm-052",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "community",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["community"],
    skillTag: "listening",
    questionText: "What is the main reason the speaker joined the club?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "To meet people with similar interests", isCorrect: true },
      { text: "To improve his grades", isCorrect: false },
      { text: "To prepare for a job", isCorrect: false },
    ],
  }),

  // ── listening-part-5: multiple matching (5) ────────────────────────────────
  goldMatching({
    questionRef: "kgm-053",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "leisure",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["leisure"],
    skillTag: "listening",
    questionText: "Which activity takes place on Monday?",
    pairs: [{ leftText: "Monday", rightText: "drama club" }],
  }),
  goldMatching({
    questionRef: "kgm-054",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "sports",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["sports"],
    skillTag: "listening",
    questionText: "Which activity takes place on Tuesday?",
    pairs: [{ leftText: "Tuesday", rightText: "basketball practice" }],
  }),
  goldMatching({
    questionRef: "kgm-055",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "culture",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "Which activity takes place on Wednesday?",
    pairs: [{ leftText: "Wednesday", rightText: "choir rehearsal" }],
  }),
  goldMatching({
    questionRef: "kgm-056",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "technology",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["technology"],
    skillTag: "listening",
    questionText: "Which activity takes place on Thursday?",
    pairs: [{ leftText: "Thursday", rightText: "coding workshop" }],
  }),
  goldMatching({
    questionRef: "kgm-057",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "nature",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["nature"],
    skillTag: "listening",
    questionText: "Which activity takes place on Friday?",
    pairs: [{ leftText: "Friday", rightText: "gardening club" }],
  }),

  // ── speaking (2) ───────────────────────────────────────────────────────────
  goldSpeaking({
    questionRef: "kgm-058",
    partSlug: "speaking-part-1",
    sectionSlug: "speaking",
    sortOrder: ++sort,
    points: 20,
    difficulty: "medium",
    topicTag: "friends",
    grammarTags: ["present_simple", "question_forms"],
    vocabularyTopics: ["friends", "school"],
    skillTag: "speaking",
    questionText: "Answer the examiner's questions about you and your daily life.",
    cambridgeTaskType: "conversation",
    prompt: "The examiner will ask you about yourself, your family, and your free time.",
    maxDurationSeconds: 120,
    followUpQuestions: [
      "Where do you live?",
      "What do you enjoy doing at the weekend?",
      "Tell me about your best friend.",
    ],
  }),
  goldSpeaking({
    questionRef: "kgm-059",
    partSlug: "speaking-part-2",
    sectionSlug: "speaking",
    sortOrder: ++sort,
    points: 20,
    difficulty: "medium",
    topicTag: "places",
    grammarTags: ["present_continuous", "prepositions"],
    vocabularyTopics: ["places", "leisure"],
    skillTag: "speaking",
    questionText: "Read the scene description and describe what you see.",
    cambridgeTaskType: "picture_description_speaking",
    prompt:
      "Read the scene description. Describe what you can see and say how the people might be feeling.",
    taskDescription: "Scene: A group of teenagers are in a city park on a sunny afternoon. Some are sitting on benches talking, others are playing with a ball near a fountain.",
    maxDurationSeconds: 120,
  }),
];

export const KET_GOLD_MOCK_1 = composeGoldMockManifest({
  level: "ket",
  goldMockId: "ket-gold-mock-1",
  title: "A2 Key Gold Mock 1",
  description:
    "M3.1 academic reference mock for A2 Key for Schools — full reading & writing, listening, and speaking form.",
  questions: ketQuestions,
  parts: [
    listeningAudio(
      "listening-part-1",
      1,
      "Part 1 — Listen and choose the correct answer",
      "Woman: I'd like six of those red apples, please. Shop assistant: Here you are. That's three pounds."
    ),
    listeningAudio(
      "listening-part-2",
      2,
      "Part 2 — Listen and choose the best answer",
      "Boy: Sorry I'm late, Miss. My alarm didn't go off this morning. Teacher: Please try to be on time tomorrow."
    ),
    listeningAudio(
      "listening-part-3",
      3,
      "Part 3 — Listen and complete each gap",
      "Guide: Welcome to the city museum. We open at nine o'clock. Meet your group at the library entrance at half past eight."
    ),
    listeningAudio(
      "listening-part-4",
      4,
      "Part 4 — Listen to the monologue",
      "Speaker: My favourite animals are dolphins because they are intelligent and friendly. I first saw them on a family holiday."
    ),
    listeningAudio(
      "listening-part-5",
      5,
      "Part 5 — Listen and match each day to an activity",
      "Coordinator: On Monday we have drama club, on Tuesday basketball, Wednesday choir, Thursday coding, and Friday gardening."
    ),
  ],
});
