import { composeGoldMockManifest } from "@/lib/cambridge-assessment/gold-mocks/gold-mock-compose";
import {
  goldGapFill,
  goldMatching,
  goldMcq,
  goldReadingComprehension,
  goldSpeaking,
  goldWriting,
  listeningAudio,
  readingSectionSlug,
  uniquifyQuestionStems,
} from "@/lib/cambridge-assessment/gold-mocks/gold-mock-helpers";

const RW = readingSectionSlug("ket");
let sort = 0;

const KET_RW3_PASSAGE = `Our school drama club is preparing a comedy for the end-of-term show. Twenty students from Years 9 and 10 meet every Wednesday after lessons in the hall. The drama teacher, Ms Ortiz, has written a script about a group of friends who enter a talent competition. Rehearsals started six weeks ago, and the students have already learned most of their lines. They are now practising dances and simple lighting changes. Tickets will go on sale next Monday for parents and local residents. The club hopes to raise money for new costumes and sound equipment. Everyone is excited because this is the first live performance since the school reopened the theatre.`;

const KET_RW4_TEXT =
  "Learning a musical instrument takes patience and regular (1) ___. Beginners should practise for short periods every day rather than one long session at the (2) ___. It helps to play pieces you enjoy, but your teacher may also give you exercises to improve your (3) ___. When you perform in front of others, try to stay calm and listen carefully to the (4) ___. Joining a school band or orchestra is a good way to meet people who share your (5) ___. Remember that progress may be slow at first, but consistent effort usually leads to better (6) ___ over time.";

const ketQuestions = [
  // ── rw-part-1: signs & messages (6 MCQ) — education, entertainment, social ─
  goldMcq({
    questionRef: "kgm3-001",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Exam results available online from 9 a.m. Friday.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Students can check results on the website on Friday morning.", isCorrect: true },
      { text: "Results are only given in person.", isCorrect: false },
      { text: "Results were published last week.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-002",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "culture",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "Cinema — Student tickets half price on weekdays.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Students pay less from Monday to Friday.", isCorrect: true },
      { text: "All tickets are free for students.", isCorrect: false },
      { text: "Prices are higher at the weekend.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-003",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "friends",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["friends"],
    skillTag: "reading",
    questionText: "Youth club — New members welcome. Join us on Thursdays.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Anyone can become a member and meet on Thursdays.", isCorrect: true },
      { text: "The club is only for existing members.", isCorrect: false },
      { text: "Meetings happen every day.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-004",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["future_will"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Science fair — Projects must be submitted by 3 p.m. on 12 May.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Students need to hand in projects before the deadline.", isCorrect: true },
      { text: "The fair has already finished.", isCorrect: false },
      { text: "Projects can be submitted any time.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-005",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "leisure",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["leisure"],
    skillTag: "reading",
    questionText: "Concert tonight — doors open 7 p.m., show starts 8 p.m.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "The performance begins at eight o'clock.", isCorrect: true },
      { text: "The concert was cancelled.", isCorrect: false },
      { text: "Doors close at seven.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-006",
    partSlug: "rw-part-1",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "community",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["community"],
    skillTag: "reading",
    questionText: "Charity fun run — Registration closes 48 hours before the event.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "You cannot register in the last two days before the run.", isCorrect: true },
      { text: "Registration is open until the race starts.", isCorrect: false },
      { text: "The event is only for charity workers.", isCorrect: false },
    ],
  }),

  // ── rw-part-2: multiple matching (7) ─────────────────────────────────────
  goldMatching({
    questionRef: "kgm3-007",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Who enjoys studying history?",
    pairs: [{ leftText: "Nadia", rightText: "reads books about ancient civilisations" }],
  }),
  goldMatching({
    questionRef: "kgm3-008",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "music",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["culture", "music"],
    skillTag: "reading",
    questionText: "Who plays the violin in the school orchestra?",
    pairs: [{ leftText: "Leo", rightText: "practises with the orchestra every Friday" }],
  }),
  goldMatching({
    questionRef: "kgm3-009",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "friends",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["friends"],
    skillTag: "reading",
    questionText: "Who is organising a surprise party?",
    pairs: [{ leftText: "Ines", rightText: "is planning a birthday celebration for her cousin" }],
  }),
  goldMatching({
    questionRef: "kgm3-010",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "leisure",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["leisure"],
    skillTag: "reading",
    questionText: "Who saw a famous band in concert last month?",
    pairs: [{ leftText: "Kai", rightText: "travelled to the capital for a live music festival" }],
  }),
  goldMatching({
    questionRef: "kgm3-011",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Who helps younger students with maths homework?",
    pairs: [{ leftText: "Amira", rightText: "volunteers in the after-school tutoring club" }],
  }),
  goldMatching({
    questionRef: "kgm3-012",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "culture",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "Who is going to perform in a street theatre festival?",
    pairs: [{ leftText: "Felix", rightText: "is rehearsing a comedy sketch with his classmates" }],
  }),
  goldMatching({
    questionRef: "kgm3-013",
    partSlug: "rw-part-2",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "community",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["community"],
    skillTag: "reading",
    questionText: "Who has created a social media group for new students?",
    pairs: [{ leftText: "Zara", rightText: "has invited classmates to share advice online" }],
  }),

  // ── rw-part-3: reading comprehension (5) ─────────────────────────────────
  goldReadingComprehension({
    questionRef: "kgm3-014",
    partSlug: "rw-part-3",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "When does the drama club meet?",
    passage: KET_RW3_PASSAGE,
    choices: [
      { text: "Every Wednesday after lessons", isCorrect: true },
      { text: "Every Monday morning", isCorrect: false },
      { text: "Only at weekends", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "kgm3-015",
    partSlug: "rw-part-3",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "culture",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "What is the school show about?",
    passage: KET_RW3_PASSAGE,
    choices: [
      { text: "Friends who enter a talent competition", isCorrect: true },
      { text: "A school trip to the theatre", isCorrect: false },
      { text: "A history lesson in the hall", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "kgm3-016",
    partSlug: "rw-part-3",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "What are the students practising now?",
    passage: KET_RW3_PASSAGE,
    choices: [
      { text: "Dances and lighting changes", isCorrect: true },
      { text: "Only their speaking lines", isCorrect: false },
      { text: "Ticket sales", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "kgm3-017",
    partSlug: "rw-part-3",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "community",
    grammarTags: ["future_will"],
    vocabularyTopics: ["community"],
    skillTag: "reading",
    questionText: "Who will be able to buy tickets?",
    passage: KET_RW3_PASSAGE,
    choices: [
      { text: "Parents and local residents", isCorrect: true },
      { text: "Only drama club members", isCorrect: false },
      { text: "Teachers only", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "kgm3-018",
    partSlug: "rw-part-3",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "school",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Why is everyone excited about the show?",
    passage: KET_RW3_PASSAGE,
    choices: [
      { text: "It is the first live performance since the theatre reopened", isCorrect: true },
      { text: "They have never rehearsed before", isCorrect: false },
      { text: "Tickets are free for all students", isCorrect: false },
    ],
  }),

  // ── rw-part-4: multiple-choice cloze (6) ─────────────────────────────────
  goldMcq({
    questionRef: "kgm3-019",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "music",
    grammarTags: ["articles"],
    vocabularyTopics: ["culture", "music"],
    skillTag: "reading",
    questionText: "Gap (1): patience and regular ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 0 },
    choices: [
      { text: "practice", isCorrect: true },
      { text: "practise", isCorrect: false },
      { text: "practised", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-020",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "time",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["time"],
    skillTag: "reading",
    questionText: "Gap (2): one long session at the ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 1 },
    choices: [
      { text: "weekend", isCorrect: true },
      { text: "weekends", isCorrect: false },
      { text: "weekend's", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-021",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "music",
    grammarTags: ["nouns"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "Gap (3): improve your ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 2 },
    choices: [
      { text: "technique", isCorrect: true },
      { text: "techniques", isCorrect: false },
      { text: "technical", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-022",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "music",
    grammarTags: ["articles"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "Gap (4): listen carefully to the ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 3 },
    choices: [
      { text: "music", isCorrect: true },
      { text: "musics", isCorrect: false },
      { text: "musical", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-023",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "friends",
    grammarTags: ["nouns"],
    vocabularyTopics: ["friends"],
    skillTag: "reading",
    questionText: "Gap (5): share your ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 4 },
    choices: [
      { text: "interest", isCorrect: true },
      { text: "interested", isCorrect: false },
      { text: "interesting", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-024",
    partSlug: "rw-part-4",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "school",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Gap (6): leads to better ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: KET_RW4_TEXT, gapIndex: 5 },
    choices: [
      { text: "results", isCorrect: true },
      { text: "resulting", isCorrect: false },
      { text: "resulted", isCorrect: false },
    ],
  }),

  // ── rw-part-5: open cloze (6) ────────────────────────────────────────────
  goldGapFill({
    questionRef: "kgm3-025",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["articles"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "She is ___ best student in our class.",
    template: "She is [0] best student in our class.",
    correctAnswers: ["the"],
  }),
  goldGapFill({
    questionRef: "kgm3-026",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "leisure",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["leisure"],
    skillTag: "reading",
    questionText: "We ___ a great film at the cinema yesterday.",
    template: "We [0] a great film at the cinema yesterday.",
    correctAnswers: ["saw", "watched"],
  }),
  goldGapFill({
    questionRef: "kgm3-027",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "friends",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["friends"],
    skillTag: "reading",
    questionText: "I met my friends ___ the youth club.",
    template: "I met my friends [0] the youth club.",
    correctAnswers: ["at"],
  }),
  goldGapFill({
    questionRef: "kgm3-028",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Group projects are ___ than working alone.",
    template: "Group projects are [0] than working alone.",
    correctAnswers: ["easier", "more fun"],
  }),
  goldGapFill({
    questionRef: "kgm3-029",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "culture",
    grammarTags: ["relative_clauses"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "The singer ___ won the competition lives nearby.",
    template: "The singer [0] won the competition lives nearby.",
    correctAnswers: ["who", "that"],
  }),
  goldGapFill({
    questionRef: "kgm3-030",
    partSlug: "rw-part-5",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "school",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Students ___ hand in homework on time.",
    template: "Students [0] hand in homework on time.",
    correctAnswers: ["must"],
  }),

  // ── rw-part-6 & 7: writing ─────────────────────────────────────────────────
  goldWriting({
    questionRef: "kgm3-031",
    partSlug: "rw-part-6",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 15,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["future_will", "imperatives"],
    vocabularyTopics: ["school"],
    skillTag: "writing",
    questionText: "Write an email to your English teacher.",
    cambridgeTaskType: "write_email",
    prompt:
      "Your class is organising a charity concert at school. Write an email to your English teacher.",
    taskDescription: "Write 25–35 words. Include all three points.",
    minWords: 25,
    maxWords: 35,
    requiredPoints: [
      "Say whether you can help before the concert",
      "Explain one job you could do",
      "Ask what time you should arrive on the day",
    ],
  }),
  goldWriting({
    questionRef: "kgm3-032",
    partSlug: "rw-part-7",
    sectionSlug: RW,
    sortOrder: ++sort,
    points: 15,
    difficulty: "medium",
    topicTag: "friends",
    grammarTags: ["past_simple", "linking_words"],
    vocabularyTopics: ["friends"],
    skillTag: "writing",
    questionText: "Write a story about meeting a new friend.",
    cambridgeTaskType: "write_story",
    prompt:
      "Your English teacher has asked you to write a story. Your story must begin with this sentence: 'I was nervous before the school party.'",
    taskDescription: "Write 35 words or more.",
    minWords: 35,
    maxWords: 100,
  }),

  // ── listening-part-1: MCQ pictures (5) ────────────────────────────────────
  goldMcq({
    questionRef: "kgm3-033",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "What is the girl doing in the classroom?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Writing on the board", isCorrect: true },
      { text: "Reading a magazine", isCorrect: false },
      { text: "Using a microscope", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-034",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "leisure",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["leisure"],
    skillTag: "listening",
    questionText: "What are the boys doing?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Playing video games", isCorrect: true },
      { text: "Playing chess", isCorrect: false },
      { text: "Building a model", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-035",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "culture",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "What instrument is the man playing?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "The guitar", isCorrect: true },
      { text: "The drums", isCorrect: false },
      { text: "The flute", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-036",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "friends",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["friends"],
    skillTag: "listening",
    questionText: "Where are the teenagers chatting?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "In a café", isCorrect: true },
      { text: "In a library", isCorrect: false },
      { text: "On a bus", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-037",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "leisure",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["leisure", "sports"],
    skillTag: "listening",
    questionText: "What is happening on stage?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "A dance performance", isCorrect: true },
      { text: "A magic show", isCorrect: false },
      { text: "A prize ceremony", isCorrect: false },
    ],
  }),

  // ── listening-part-2: MCQ questions (5) ────────────────────────────────────
  goldMcq({
    questionRef: "kgm3-038",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "Why did the boy miss the maths test?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "He was ill", isCorrect: true },
      { text: "He forgot his calculator", isCorrect: false },
      { text: "He arrived too early", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-039",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "leisure",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["leisure"],
    skillTag: "listening",
    questionText: "How often does Mia go to the cinema?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Once a month", isCorrect: true },
      { text: "Every weekend", isCorrect: false },
      { text: "Twice a week", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-040",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "friends",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["friends"],
    skillTag: "listening",
    questionText: "What are the friends going to do on Saturday?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Have a picnic in the park", isCorrect: true },
      { text: "Study for an exam", isCorrect: false },
      { text: "Visit a museum", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-041",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["school", "technology"],
    skillTag: "listening",
    questionText: "What prize did the team win?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "First place in the science competition", isCorrect: true },
      { text: "A sports trophy", isCorrect: false },
      { text: "A book voucher", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-042",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "culture",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "What does the teacher tell students about the performance?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "They must arrive thirty minutes early", isCorrect: true },
      { text: "They can wear casual clothes", isCorrect: false },
      { text: "They should bring their own microphones", isCorrect: false },
    ],
  }),

  // ── listening-part-3: gap fill (5) ───────────────────────────────────────
  goldGapFill({
    questionRef: "kgm3-043",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["numbers"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "The lecture begins at ___ o'clock.",
    template: "The lecture begins at [0] o'clock.",
    correctAnswers: ["eleven", "11"],
  }),
  goldGapFill({
    questionRef: "kgm3-044",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "friends",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["friends"],
    skillTag: "listening",
    questionText: "Let's meet ___ the school gate.",
    template: "Let's meet [0] the school gate.",
    correctAnswers: ["at", "outside"],
  }),
  goldGapFill({
    questionRef: "kgm3-045",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "culture",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "The exhibition closes ___ half past five.",
    template: "The exhibition closes [0] half past five.",
    correctAnswers: ["at"],
  }),
  goldGapFill({
    questionRef: "kgm3-046",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "leisure",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["leisure"],
    skillTag: "listening",
    questionText: "Don't forget to bring a ___ for the quiz team.",
    template: "Don't forget to bring a [0] for the quiz team.",
    correctAnswers: ["pen", "pencil"],
  }),
  goldGapFill({
    questionRef: "kgm3-047",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "school",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "She ___ in the school choir for three years.",
    template: "She [0] in the school choir for three years.",
    correctAnswers: ["sang", "has sung"],
  }),

  // ── listening-part-4: MCQ monologue (5) ────────────────────────────────────
  goldMcq({
    questionRef: "kgm3-048",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "What is the speaker's favourite subject?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Biology", isCorrect: true },
      { text: "Geography", isCorrect: false },
      { text: "Art", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-049",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "leisure",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["leisure"],
    skillTag: "listening",
    questionText: "When did the speaker join the film club?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "At the start of this term", isCorrect: true },
      { text: "Two years ago", isCorrect: false },
      { text: "During the summer holidays", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-050",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "friends",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["friends"],
    skillTag: "listening",
    questionText: "Why does the speaker enjoy group projects?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "She likes sharing ideas with classmates", isCorrect: true },
      { text: "They are always easy", isCorrect: false },
      { text: "She does not have to speak", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-051",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "culture",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "Which type of music does the speaker prefer?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Jazz", isCorrect: true },
      { text: "Heavy metal", isCorrect: false },
      { text: "Classical opera", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "kgm3-052",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "community",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["community"],
    skillTag: "listening",
    questionText: "What is the main reason the speaker joined the volunteer group?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "To meet people and help the local community", isCorrect: true },
      { text: "To improve his exam results", isCorrect: false },
      { text: "To learn a new language", isCorrect: false },
    ],
  }),

  // ── listening-part-5: multiple matching (5) ────────────────────────────────
  goldMatching({
    questionRef: "kgm3-053",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "Which club meets on Monday?",
    pairs: [{ leftText: "Monday", rightText: "debate club" }],
  }),
  goldMatching({
    questionRef: "kgm3-054",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "leisure",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["leisure"],
    skillTag: "listening",
    questionText: "Which activity is on Tuesday?",
    pairs: [{ leftText: "Tuesday", rightText: "film screening" }],
  }),
  goldMatching({
    questionRef: "kgm3-055",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "culture",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "Which event takes place on Wednesday?",
    pairs: [{ leftText: "Wednesday", rightText: "poetry reading" }],
  }),
  goldMatching({
    questionRef: "kgm3-056",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "friends",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["friends"],
    skillTag: "listening",
    questionText: "Which social event is planned for Thursday?",
    pairs: [{ leftText: "Thursday", rightText: "games night" }],
  }),
  goldMatching({
    questionRef: "kgm3-057",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "school",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "Which performance is on Friday?",
    pairs: [{ leftText: "Friday", rightText: "school talent show" }],
  }),

  // ── speaking (2) ───────────────────────────────────────────────────────────
  goldSpeaking({
    questionRef: "kgm3-058",
    partSlug: "speaking-part-1",
    sectionSlug: "speaking",
    sortOrder: ++sort,
    points: 20,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["present_simple", "question_forms"],
    vocabularyTopics: ["school", "friends"],
    skillTag: "speaking",
    questionText: "Answer the examiner's questions about school and your social life.",
    cambridgeTaskType: "conversation",
    prompt:
      "The examiner will ask you about your school, your favourite subjects, and how you spend time with friends.",
    maxDurationSeconds: 120,
    followUpQuestions: [
      "Which subject do you enjoy most at school?",
      "How do you usually relax after a busy week?",
      "Tell me about a club or activity you belong to.",
    ],
  }),
  goldSpeaking({
    questionRef: "kgm3-059",
    partSlug: "speaking-part-2",
    sectionSlug: "speaking",
    sortOrder: ++sort,
    points: 20,
    difficulty: "medium",
    topicTag: "leisure",
    grammarTags: ["present_continuous", "prepositions"],
    vocabularyTopics: ["leisure", "friends"],
    skillTag: "speaking",
    questionText: "Read the scene description and say what the people are doing.",
    cambridgeTaskType: "picture_description_speaking",
    prompt:
      "Read the scene description. Describe what you can see and say how the people might be feeling.",
    taskDescription: "Scene: Teenagers are at an outdoor concert. A band is playing on stage and the crowd is clapping and singing along.",
    maxDurationSeconds: 120,
  }),
];

export const KET_GOLD_MOCK_3 = composeGoldMockManifest({
  level: "ket",
  goldMockId: "ket-gold-mock-3",
  title: "A2 Key Gold Mock 3",
  description:
    "M4.1 academic mock for A2 Key — education, entertainment, and social themes across reading, writing, listening, and speaking.",
  questions: uniquifyQuestionStems(ketQuestions),
  parts: [
    listeningAudio(
      "listening-part-1",
      1,
      "Part 1 — Listen and choose the correct answer",
      "Teacher: Please write the answer on the board so everyone can see it. Student: OK, I'll write the example now."
    ),
    listeningAudio(
      "listening-part-2",
      2,
      "Part 2 — Listen and choose the best answer",
      "Boy: I couldn't do the maths test because I was ill. Teacher: Don't worry — you can take it next week."
    ),
    listeningAudio(
      "listening-part-3",
      3,
      "Part 3 — Listen and complete each gap",
      "Organiser: The lecture begins at eleven o'clock. Let's meet at the school gate. The exhibition closes at half past five."
    ),
    listeningAudio(
      "listening-part-4",
      4,
      "Part 4 — Listen to the monologue",
      "Speaker: My favourite subject is biology, and I joined the film club at the start of this term. I enjoy group projects because I like sharing ideas."
    ),
    listeningAudio(
      "listening-part-5",
      5,
      "Part 5 — Listen and match each day to an activity",
      "Coordinator: Debate club is on Monday, film screening Tuesday, poetry reading Wednesday, games night Thursday, and the talent show on Friday."
    ),
  ],
});
