import { composeGoldMockManifest } from "@/lib/cambridge-assessment/gold-mocks/gold-mock-compose";
import {
  goldGapFill,
  goldMatching,
  goldMcq,
  goldReadingComprehension,
  goldSpeaking,
  goldWriting,
  listeningAudio,
  uniquifyQuestionStems,
} from "@/lib/cambridge-assessment/gold-mocks/gold-mock-helpers";

const QUESTIONS = [
  goldMatching({
    questionRef: "mgm2-001",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 1,
    points: 1,
    difficulty: "easy",
    topicTag: "rainy_day",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["weather", "clothes"],
    skillTag: "listening",
    questionText: "Listen. Which girl is Emma?",
    pairs: [{ leftText: "Emma", rightText: "Girl holding a red umbrella" }],
    content: {
      transcriptSnippet: "This is Emma. She's holding a red umbrella because it's raining.",
      audioCue: "name_introduction",
    },
  }),

  goldMatching({
    questionRef: "mgm2-002",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 2,
    points: 1,
    difficulty: "easy",
    topicTag: "construction_job",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["jobs", "clothes"],
    skillTag: "listening",
    questionText: "Listen. Which boy is Sam?",
    pairs: [{ leftText: "Sam", rightText: "Boy wearing a yellow hard hat" }],
    content: {
      transcriptSnippet: "Sam is working on the building site. He's wearing a yellow hard hat.",
      audioCue: "name_introduction",
    },
  }),

  goldMatching({
    questionRef: "mgm2-003",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 3,
    points: 1,
    difficulty: "medium",
    topicTag: "computer_class",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["technology", "school"],
    skillTag: "listening",
    questionText: "Listen. Which girl is Lily?",
    pairs: [{ leftText: "Lily", rightText: "Girl using a laptop at her desk" }],
    content: {
      transcriptSnippet: "Lily always uses a laptop in computer class.",
      audioCue: "name_introduction",
    },
  }),

  goldMatching({
    questionRef: "mgm2-004",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 4,
    points: 1,
    difficulty: "medium",
    topicTag: "weather_report",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["weather", "jobs"],
    skillTag: "listening",
    questionText: "Listen. Which boy is Ben?",
    pairs: [{ leftText: "Ben", rightText: "Boy pointing at a weather map" }],
    content: {
      transcriptSnippet: "Ben is pointing at the weather map on the TV screen.",
      audioCue: "name_introduction",
    },
  }),

  goldMatching({
    questionRef: "mgm2-005",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 5,
    points: 1,
    difficulty: "medium",
    topicTag: "tech_repair",
    grammarTags: ["have_got"],
    vocabularyTopics: ["technology", "jobs"],
    skillTag: "listening",
    questionText: "Listen. Which girl is Zoe?",
    pairs: [{ leftText: "Zoe", rightText: "Girl fixing a computer with tools" }],
    content: {
      transcriptSnippet: "Zoe's got small tools and she's fixing a computer.",
      audioCue: "name_introduction",
    },
  }),

  goldMatching({
    questionRef: "mgm2-006",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 6,
    points: 1,
    difficulty: "hard",
    topicTag: "office_team",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["jobs", "technology"],
    skillTag: "listening",
    questionText: "Listen. Which boy is Jake?",
    pairs: [{ leftText: "Jake", rightText: "Boy standing between two computer screens" }],
    content: {
      transcriptSnippet: "Jake is standing between two computer screens in the office.",
      audioCue: "name_introduction",
    },
  }),

  goldGapFill({
    questionRef: "mgm2-007",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 7,
    points: 1,
    difficulty: "easy",
    topicTag: "weather_forecast",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["weather", "numbers"],
    skillTag: "listening",
    questionText: "Listen and write. What is the temperature today?",
    template: "The temperature is [0] degrees.",
    correctAnswers: ["twenty", "20"],
    content: {
      transcriptSnippet: "The temperature today is twenty degrees.",
    },
  }),

  goldGapFill({
    questionRef: "mgm2-008",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 8,
    points: 1,
    difficulty: "medium",
    topicTag: "parents_job",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["jobs", "family"],
    skillTag: "listening",
    questionText: "Listen and write. What is Dad's job?",
    template: "Dad is a [0].",
    correctAnswers: ["engineer"],
    content: {
      transcriptSnippet: "My dad is an engineer and he builds bridges.",
    },
  }),

  goldGapFill({
    questionRef: "mgm2-009",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 9,
    points: 1,
    difficulty: "medium",
    topicTag: "cloudy_sky",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["weather"],
    skillTag: "listening",
    questionText: "Listen and write. What is the weather like?",
    template: "The weather is [0].",
    correctAnswers: ["cloudy"],
    content: {
      transcriptSnippet: "Look outside. The weather is cloudy and grey.",
    },
  }),

  goldGapFill({
    questionRef: "mgm2-010",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 10,
    points: 1,
    difficulty: "medium",
    topicTag: "tech_shop",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["technology", "numbers"],
    skillTag: "listening",
    questionText: "Listen and write. How many computers are in the shop?",
    template: "There are [0] computers.",
    correctAnswers: ["eight", "8"],
    content: {
      transcriptSnippet: "There are eight computers in the technology shop.",
    },
  }),

  goldGapFill({
    questionRef: "mgm2-011",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 11,
    points: 1,
    difficulty: "medium",
    topicTag: "app_download",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["technology", "leisure"],
    skillTag: "listening",
    questionText: "Listen and write. What is the girl downloading?",
    template: "She is downloading a [0].",
    correctAnswers: ["game"],
    content: {
      transcriptSnippet: "She is downloading a new game on her tablet.",
    },
  }),

  goldGapFill({
    questionRef: "mgm2-012",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 12,
    points: 1,
    difficulty: "hard",
    topicTag: "weather_show",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["weather", "time"],
    skillTag: "listening",
    questionText: "Listen and write. What time does the weather show start?",
    template: "The show starts at [0].",
    correctAnswers: ["quarter past four", "4:15", "4.15"],
    content: {
      transcriptSnippet: "The weather show starts at quarter past four.",
    },
  }),

  goldMcq({
    questionRef: "mgm2-013",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 13,
    points: 1,
    difficulty: "easy",
    topicTag: "robot_club",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["technology", "school"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What are the children learning?",
    choices: [
      { text: "How to build robots", isCorrect: true },
      { text: "How to cook soup", isCorrect: false },
      { text: "How to ride horses", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "At robot club the children are learning how to build robots.",
    },
  }),

  goldMcq({
    questionRef: "mgm2-014",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 14,
    points: 1,
    difficulty: "medium",
    topicTag: "weather_app",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["technology", "weather"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What app does Maria use every morning?",
    choices: [
      { text: "A weather app", isCorrect: true },
      { text: "A cooking app", isCorrect: false },
      { text: "A music app", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Maria uses a weather app every morning before school.",
    },
  }),

  goldMcq({
    questionRef: "mgm2-015",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 15,
    points: 1,
    difficulty: "medium",
    topicTag: "music_robot",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["technology", "hobbies"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What can the robot do?",
    choices: [
      { text: "Play music", isCorrect: true },
      { text: "Fly a plane", isCorrect: false },
      { text: "Swim in the sea", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Our robot can play music when we clap our hands.",
    },
  }),

  goldMcq({
    questionRef: "mgm2-016",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 16,
    points: 1,
    difficulty: "medium",
    topicTag: "rain_forecast",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["weather"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What is the weather forecast for tomorrow?",
    choices: [
      { text: "Rain", isCorrect: true },
      { text: "Snow", isCorrect: false },
      { text: "Sunshine all day", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "The forecast says it is going to rain tomorrow.",
    },
  }),

  goldMcq({
    questionRef: "mgm2-017",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 17,
    points: 1,
    difficulty: "medium",
    topicTag: "video_project",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["technology", "school"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What do they use to film their project?",
    choices: [
      { text: "A tablet", isCorrect: true },
      { text: "A bicycle", isCorrect: false },
      { text: "A tennis racket", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "They use a tablet to film their school technology project.",
    },
  }),

  goldMcq({
    questionRef: "mgm2-018",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 18,
    points: 1,
    difficulty: "hard",
    topicTag: "drone_test",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["technology", "leisure"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What are they going to do this afternoon?",
    choices: [
      { text: "Test the new drone", isCorrect: true },
      { text: "Visit a farm", isCorrect: false },
      { text: "Sleep in class", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "This afternoon they are going to test the new drone in the playground.",
    },
  }),

  goldMcq({
    questionRef: "mgm2-019",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 19,
    points: 1,
    difficulty: "easy",
    topicTag: "office_picture",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["technology", "colours"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Colour the computer screen. Which colour?",
    choices: [
      { text: "Blue", isCorrect: true },
      { text: "Brown", isCorrect: false },
      { text: "Pink", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Colour the computer screen blue, please.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMcq({
    questionRef: "mgm2-020",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 20,
    points: 1,
    difficulty: "easy",
    topicTag: "office_picture",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["weather", "clothes"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Colour the raincoat on the chair. Which colour?",
    choices: [
      { text: "Yellow", isCorrect: true },
      { text: "Purple", isCorrect: false },
      { text: "Black", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Now colour the raincoat on the chair yellow.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMcq({
    questionRef: "mgm2-021",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 21,
    points: 1,
    difficulty: "medium",
    topicTag: "office_picture",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["weather", "places"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Draw a cloud above the building. Which picture is correct?",
    choices: [
      { text: "Cloud above the building", isCorrect: true },
      { text: "Cloud under the desk", isCorrect: false },
      { text: "Cloud inside the bag", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Draw a cloud above the building.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMcq({
    questionRef: "mgm2-022",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 22,
    points: 1,
    difficulty: "medium",
    topicTag: "office_picture",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["technology", "colours"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Colour the tablet case. Which colour?",
    choices: [
      { text: "Red", isCorrect: true },
      { text: "Green", isCorrect: false },
      { text: "Grey", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Colour the tablet case red.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMcq({
    questionRef: "mgm2-023",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 23,
    points: 1,
    difficulty: "easy",
    topicTag: "office_picture",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["weather", "home"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Draw a sun next to the window. Which picture is correct?",
    choices: [
      { text: "Sun beside the window", isCorrect: true },
      { text: "Sun under the table", isCorrect: false },
      { text: "Sun in the cupboard", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Draw a sun next to the window.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMcq({
    questionRef: "mgm2-024",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 24,
    points: 1,
    difficulty: "hard",
    topicTag: "office_picture",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["jobs", "technology"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Draw a line from the girl to the microphone. Which picture?",
    choices: [
      { text: "Girl pointing at microphone on desk", isCorrect: true },
      { text: "Girl far from microphone", isCorrect: false },
      { text: "Girl without a microphone", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Draw a line from the girl to the microphone on her desk.",
      taskProxy: "colour_and_draw",
    },
  }),

  goldMatching({
    questionRef: "mgm2-025",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 25,
    points: 1,
    difficulty: "easy",
    topicTag: "storm_vocab",
    grammarTags: ["articles"],
    vocabularyTopics: ["weather"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "thunderstorm", rightText: "Storm with loud thunder and rain" }],
  }),

  goldMatching({
    questionRef: "mgm2-026",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 26,
    points: 1,
    difficulty: "easy",
    topicTag: "space_job",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "astronaut", rightText: "Person who travels in space" }],
  }),

  goldMatching({
    questionRef: "mgm2-027",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 27,
    points: 1,
    difficulty: "easy",
    topicTag: "computer_parts",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["technology"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "keyboard", rightText: "Part of a computer with letters on it" }],
  }),

  goldMatching({
    questionRef: "mgm2-028",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 28,
    points: 1,
    difficulty: "medium",
    topicTag: "emergency_job",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "firefighter", rightText: "Person who puts out fires" }],
  }),

  goldMatching({
    questionRef: "mgm2-029",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 29,
    points: 1,
    difficulty: "medium",
    topicTag: "mobile_tech",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["technology"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "smartphone", rightText: "Small phone you can carry in your pocket" }],
  }),

  goldMatching({
    questionRef: "mgm2-030",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 30,
    points: 1,
    difficulty: "hard",
    topicTag: "weather_phenomenon",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["weather"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "lightning", rightText: "Bright flash of light in the sky during a storm" }],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-031",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 31,
    points: 1,
    difficulty: "medium",
    topicTag: "night_storm",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["weather", "home"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "The thunderstorm is very loud tonight and we can't sleep.",
    choices: [
      { text: "Dark sky with lightning", isCorrect: true },
      { text: "Sunny beach scene", isCorrect: false },
      { text: "Children eating ice cream", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-032",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 32,
    points: 1,
    difficulty: "easy",
    topicTag: "uncle_teacher",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["jobs", "technology"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "My uncle is teaching computer skills at our school.",
    choices: [
      { text: "Man helping children use computers", isCorrect: true },
      { text: "Man fishing in a river", isCorrect: false },
      { text: "Man cooking in a restaurant", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-033",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 33,
    points: 1,
    difficulty: "medium",
    topicTag: "weather_news",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["weather", "leisure"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "We watch the weather news on TV every evening after dinner.",
    choices: [
      { text: "Family watching weather on TV", isCorrect: true },
      { text: "Family swimming in a pool", isCorrect: false },
      { text: "Family sleeping in bed", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-034",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 34,
    points: 1,
    difficulty: "medium",
    topicTag: "nurse_uniform",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["jobs", "clothes"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "My mum wears a blue uniform when she works at the hospital.",
    choices: [
      { text: "Woman in blue nurse uniform", isCorrect: true },
      { text: "Woman in football kit", isCorrect: false },
      { text: "Woman in swimming costume", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-035",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 35,
    points: 1,
    difficulty: "easy",
    topicTag: "classroom_robot",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["technology", "school"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "The robot is moving around the classroom and saying hello.",
    choices: [
      { text: "Robot in a classroom", isCorrect: true },
      { text: "Robot in the ocean", isCorrect: false },
      { text: "Robot on a mountain", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-036",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 36,
    points: 1,
    difficulty: "hard",
    topicTag: "snowy_day",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["weather", "transport"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "It's snowing heavily so we can't ride our bikes to school today.",
    choices: [
      { text: "Snow falling, bikes in garage", isCorrect: true },
      { text: "Children cycling in sunshine", isCorrect: false },
      { text: "Boat on a calm lake", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-037",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 37,
    points: 1,
    difficulty: "easy",
    topicTag: "weather_club",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["weather", "school"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Hi! I'm Sofia and I'm in the weather club at school. Every Friday we check the thermometer and write a short forecast for our class. Last week we said it would be windy and we were right! I want to be a weather reporter when I'm older.",
    choices: [
      { text: "Sofia is in a weather club at school.", isCorrect: true },
      { text: "Sofia checks the weather on Mondays only.", isCorrect: false },
      { text: "Sofia wants to be a chef.", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-038",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 38,
    points: 1,
    difficulty: "medium",
    topicTag: "tech_fair",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["technology", "school"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Last Saturday our school had a technology fair. Students showed robots, tablets and a small drone. My team built a robot that could carry books. The judges gave us a prize for the best design. We were very proud.",
    choices: [
      { text: "The school had a technology fair on Saturday.", isCorrect: true },
      { text: "The robot could swim in water.", isCorrect: false },
      { text: "Nobody won a prize.", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-039",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 39,
    points: 1,
    difficulty: "medium",
    topicTag: "dad_new_job",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["jobs", "family"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "My dad started a new job at an office last month. He designs websites on his computer every day. Sometimes he works from home when the weather is bad. He says his job is interesting but he must finish projects on time.",
    choices: [
      { text: "Dad designs websites at his new job.", isCorrect: true },
      { text: "Dad drives a bus every day.", isCorrect: false },
      { text: "Dad never uses a computer.", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-040",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 40,
    points: 1,
    difficulty: "easy",
    topicTag: "learning_app",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["technology", "school"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Our teacher showed us a new app for learning English. You can listen to stories and record your voice. I use it for ten minutes after homework. The app tells me when I make a mistake with a word.",
    choices: [
      { text: "The app helps students learn English.", isCorrect: true },
      { text: "The app is only for cooking recipes.", isCorrect: false },
      { text: "Students cannot listen to stories.", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-041",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 41,
    points: 1,
    difficulty: "hard",
    topicTag: "storm_day_school",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["weather", "school"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Yesterday there was a big storm during school. The lights went out for five minutes and we stayed in our classroom. Our teacher read us a story by torch light. When the storm finished, we went home early because the bus could not come.",
    choices: [
      { text: "There was a storm at school yesterday.", isCorrect: true },
      { text: "The children went swimming during the storm.", isCorrect: false },
      { text: "School finished at the normal time.", isCorrect: false },
    ],
  }),

  goldReadingComprehension({
    questionRef: "mgm2-042",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 42,
    points: 1,
    difficulty: "hard",
    topicTag: "careers_day",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["jobs", "school"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Next week our school is going to have a careers day. A pilot, a scientist and a web designer will visit our class. We are going to ask them questions about their jobs. I am going to ask the scientist about space because I love stars and planets.",
    choices: [
      { text: "Different workers will visit the school next week.", isCorrect: true },
      { text: "Only football players will visit.", isCorrect: false },
      { text: "Careers day was last month.", isCorrect: false },
    ],
  }),

  goldWriting({
    questionRef: "mgm2-043",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 43,
    points: 1,
    difficulty: "easy",
    topicTag: "thunder_picture",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["weather"],
    skillTag: "writing",
    questionText: "Read the scene below. Write one sentence about the thunderstorm.",
    cambridgeTaskType: "write_sentence",
    prompt: "Read the scene below. Write one sentence about the thunderstorm.",
    minWords: 3,
    maxWords: 18,
    taskDescription: "Scene: Dark clouds are over a town and lightning is flashing during a thunderstorm.",
  }),

  goldWriting({
    questionRef: "mgm2-044",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 44,
    points: 1,
    difficulty: "easy",
    topicTag: "chef_kitchen",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["jobs", "food"],
    skillTag: "writing",
    questionText: "Read the scene below. Write one sentence about the chef.",
    cambridgeTaskType: "write_sentence",
    prompt: "Read the scene below. Write one sentence about the chef in the kitchen.",
    minWords: 3,
    maxWords: 18,
    taskDescription: "Scene: A chef in a white hat is cooking pasta in a busy restaurant kitchen.",
  }),

  goldWriting({
    questionRef: "mgm2-045",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 45,
    points: 1,
    difficulty: "medium",
    topicTag: "tech_class_note",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["technology", "school"],
    skillTag: "writing",
    questionText: "Write a note to your friend about today's technology lesson.",
    cambridgeTaskType: "write_note",
    prompt: "Write a note to your friend about today's technology lesson.",
    minWords: 15,
    maxWords: 40,
    taskDescription: "Tell your friend about the lesson.",
    requiredPoints: ["Say what you made", "Say what you liked", "Ask your friend a question"],
  }),

  goldWriting({
    questionRef: "mgm2-046",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 46,
    points: 1,
    difficulty: "medium",
    topicTag: "rainy_day_message",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["weather", "friends"],
    skillTag: "writing",
    questionText: "Write a message to your friend about a rainy day at home.",
    cambridgeTaskType: "write_note",
    prompt: "Write a message to your friend about a rainy day at home.",
    minWords: 15,
    maxWords: 45,
    taskDescription: "Tell your friend what you did indoors.",
    requiredPoints: ["Say what the weather was like", "Say what you did", "Say what you will do tomorrow"],
  }),

  goldWriting({
    questionRef: "mgm2-047",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 47,
    points: 1,
    difficulty: "medium",
    topicTag: "computer_lab",
    grammarTags: ["present_continuous", "prepositions"],
    vocabularyTopics: ["technology", "school"],
    skillTag: "writing",
    questionText: "Read the scene below. Write two or three sentences about the computer lab.",
    cambridgeTaskType: "picture_description",
    prompt: "Read the scene below. Write two or three sentences about the computer lab.",
    minWords: 8,
    maxWords: 30,
    taskDescription: "Describe the computer lab scene.",
    requiredPoints: ["Say what the children are doing", "Say what technology you can see"],
  }),

  goldWriting({
    questionRef: "mgm2-048",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 48,
    points: 1,
    difficulty: "hard",
    topicTag: "rainy_street",
    grammarTags: ["past_simple", "adverbs_frequency"],
    vocabularyTopics: ["weather", "transport"],
    skillTag: "writing",
    questionText: "Read the scene below. Write two or three sentences about the rainy street.",
    cambridgeTaskType: "picture_description",
    prompt: "Read the scene below. Write two or three sentences about the rainy street.",
    minWords: 8,
    maxWords: 35,
    taskDescription: "Describe the rainy street scene.",
    requiredPoints: ["Say what the weather is like", "Say what people are doing"],
  }),

  goldSpeaking({
    questionRef: "mgm2-049",
    partSlug: "speaking-part-1",
    sectionSlug: "speaking",
    sortOrder: 49,
    points: 5,
    difficulty: "medium",
    topicTag: "weather_differences",
    grammarTags: ["there_is_are", "prepositions"],
    vocabularyTopics: ["weather", "places"],
    skillTag: "speaking",
    questionText: "Read the two scenes below. Tell your partner about the differences.",
    cambridgeTaskType: "speaking_picture_description",
    prompt:
      "Read Scene A and Scene B below. Tell your partner about five differences between them.",
    taskDescription: `Scene A: A town street on a sunny day with people in T-shirts and open shop doors.
Scene B: The same street in heavy rain with umbrellas, wet roads, and closed café tables.`,
    maxDurationSeconds: 120,
    followUpQuestions: [
      "Is it sunny in Scene A?",
      "How many clouds are in Scene B?",
      "Are people wearing raincoats in Scene B?",
      "Where is the rainbow in Scene A?",
      "What is the boy holding in Scene B?",
    ],
  }),

  goldSpeaking({
    questionRef: "mgm2-050",
    partSlug: "speaking-part-2",
    sectionSlug: "speaking",
    sortOrder: 50,
    points: 5,
    difficulty: "easy",
    topicTag: "about_you_weather_tech",
    grammarTags: ["present_simple", "verb_be"],
    vocabularyTopics: ["weather", "technology", "school"],
    skillTag: "speaking",
    questionText: "Answer the examiner's questions about you.",
    cambridgeTaskType: "speaking_personal_questions",
    prompt:
      "Answer the examiner's questions about yourself, the weather where you live, and technology you use.",
    maxDurationSeconds: 180,
    followUpQuestions: [
      "What's your name and how old are you?",
      "What's the weather like today where you live?",
      "What technology do you use at home or school?",
      "What job would you like to have when you are older?",
      "Do you prefer sunny days or rainy days? Why?",
    ],
  }),

  goldSpeaking({
    questionRef: "mgm2-051",
    partSlug: "speaking-part-3",
    sectionSlug: "speaking",
    sortOrder: 51,
    points: 5,
    difficulty: "medium",
    topicTag: "story_lost_tablet",
    grammarTags: ["past_simple", "past_continuous"],
    vocabularyTopics: ["technology", "places", "feelings"],
    skillTag: "speaking",
    questionText: "Use the story outline and tell the story.",
    cambridgeTaskType: "speaking_storytelling",
    prompt: "Use the story outline to tell the story of how Tom found his lost tablet.",
    taskDescription: `Story outline:
1. Tom realises his tablet is missing and looks worried.
2. He searches his bag and asks his sister for help.
3. They find the tablet in the school library.
4. Tom smiles and thanks his sister.`,
    maxDurationSeconds: 180,
    followUpQuestions: [
      "Where did Tom look first?",
      "Who helped him?",
      "Where did he find the tablet?",
      "How did Tom feel at the end?",
      "What did he do when he found it?",
    ],
  }),
];

export const MOVERS_GOLD_MOCK_2 = composeGoldMockManifest({
  level: "movers",
  goldMockId: "movers-gold-mock-2",
  title: "Cambridge Movers Gold Mock 2",
  description:
    "Manually authored A1 Movers gold mock 2 — full 51-item form with Weather, Jobs, and Technology themes aligned to the M2.0 blueprint.",
  questions: uniquifyQuestionStems(QUESTIONS),
  parts: [
    listeningAudio(
      "listening-part-1",
      1,
      "Link names to descriptions",
      "Examiner: Look at the pictures. Listen and draw a line from each name to the correct person.\n\nThis is Emma. She's holding a red umbrella because it's raining.\nSam is working on the building site. He's wearing a yellow hard hat.\nLily always uses a laptop in computer class.\nBen is pointing at the weather map on the TV screen.\nZoe's got small tools and she's fixing a computer.\nJake is standing between two computer screens in the office."
    ),
    listeningAudio(
      "listening-part-2",
      2,
      "Write words or numbers",
      "Examiner: Listen and write the missing word or number.\n\nThe temperature today is twenty degrees.\nMy dad is an engineer and he builds bridges.\nLook outside. The weather is cloudy and grey.\nThere are eight computers in the technology shop.\nShe is downloading a new game on her tablet.\nThe weather show starts at quarter past four."
    ),
    listeningAudio(
      "listening-part-3",
      3,
      "Choose the correct answer",
      "Examiner: Listen and Choose the correct answer.\n\nAt robot club the children are learning how to build robots.\nMaria uses a weather app every morning before school.\nOur robot can play music when we clap our hands.\nThe forecast says it is going to rain tomorrow.\nThey use a tablet to film their school technology project.\nThis afternoon they are going to test the new drone in the playground."
    ),
    listeningAudio(
      "listening-part-4",
      4,
      "Colour and draw",
      "Examiner: Listen and colour or draw.\n\nColour the computer screen blue, please.\nNow colour the raincoat on the chair yellow.\nDraw a cloud above the building.\nColour the tablet case red.\nDraw a sun next to the window.\nDraw a line from the girl to the microphone on her desk."
    ),
  ],
});
