import { composeGoldMockManifest } from "@/lib/cambridge-assessment/gold-mocks/gold-mock-compose";
import {
  goldGapFill,
  goldMatching,
  goldMcq,
  goldReadingComprehension,
  goldSpeaking,
  goldWriting,
  listeningAudio,
  readingSectionSlug,
} from "@/lib/cambridge-assessment/gold-mocks/gold-mock-helpers";

const READING = readingSectionSlug("pet");
let sort = 0;

const PET_R3_PASSAGE = `When Maya moved to a new city for university, she felt nervous about making friends. During the first week, she joined a photography society because she loved taking pictures of street life. At the first meeting, members shared tips about lighting and composition. Maya volunteered to photograph the society's charity exhibition, which raised money for a local hospital. Working on the project helped her meet students from different courses. By the end of the term, she had not only improved her technical skills but also built a close group of friends who still travel together during holidays.`;

const PET_R4_TEXT =
  "Urban gardening has become popular among young professionals who live in flats. Many people grow herbs and vegetables on balconies because fresh produce (1) ___ expensive in supermarkets. Community gardens also offer shared spaces where neighbours can (2) ___ advice and tools. Experts recommend starting with easy plants such as lettuce or mint, which grow quickly and need little (3) ___. Some cities provide free workshops so residents learn how to compost and save (4) ___. Although space is limited, careful planning can turn a small corner into a productive and (5) ___ garden. In the long term, gardening can reduce stress and encourage people to spend more time (6) ___. ";

const PET_R6_PASSAGE = `[A] For centuries, people have looked to the night sky for navigation and inspiration. [B] Today, light pollution in cities makes it harder to see stars clearly. [C] However, dark-sky parks protect areas where astronomers and tourists can observe constellations. [D] These parks also support wildlife that depends on natural darkness. [E] As a result, several countries have introduced laws to reduce unnecessary outdoor lighting. [F] Visiting a dark-sky park can be an unforgettable experience for families and students alike.`;

const petQuestions = [
  // ── reading-part-1: signs (6 MCQ) ────────────────────────────────────────
  goldMcq({
    questionRef: "pgm-001",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "transport",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["transport"],
    skillTag: "reading",
    questionText: "Parking for permit holders only — all other vehicles will be removed.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Anyone may park here for one hour.", isCorrect: false },
      { text: "Only drivers with a permit can leave their car here.", isCorrect: true },
      { text: "Parking is free after 6 p.m.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-002",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "health",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["health"],
    skillTag: "reading",
    questionText: "Pharmacy closed — emergency prescriptions available at City Hospital.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "You can collect urgent medicine at the hospital.", isCorrect: true },
      { text: "The pharmacy opens at midnight.", isCorrect: false },
      { text: "No medicine is available today.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-003",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "leisure",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["leisure"],
    skillTag: "reading",
    questionText: "Exhibition ends Sunday — last entry 4:30 p.m.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Visitors cannot enter after half past four.", isCorrect: true },
      { text: "The exhibition continues next month.", isCorrect: false },
      { text: "Tickets are sold only online.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-004",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "shopping",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["shopping"],
    skillTag: "reading",
    questionText: "Winter sale — further reductions on selected coats this week only.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Coats will be cheaper for a limited time.", isCorrect: true },
      { text: "All clothes are half price.", isCorrect: false },
      { text: "The sale finished yesterday.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-005",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["future_will"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Exam results published online Friday — paper copies available on request.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Students can ask for a printed copy if they want one.", isCorrect: true },
      { text: "Results appear only on noticeboards.", isCorrect: false },
      { text: "Paper copies are not offered.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-006",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "environment",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["environment"],
    skillTag: "reading",
    questionText: "Reusable cups required — disposable cups no longer provided.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Customers must bring or buy a cup they can use again.", isCorrect: true },
      { text: "The café has stopped selling drinks.", isCorrect: false },
      { text: "Paper cups are free at the counter.", isCorrect: false },
    ],
  }),

  // ── reading-part-2: matching (5) ─────────────────────────────────────────
  goldMatching({
    questionRef: "pgm-007",
    partSlug: "reading-part-2",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "jobs",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "Which person works in a hospital?",
    pairs: [{ leftText: "Nadia", rightText: "is training to be a nurse" }],
  }),
  goldMatching({
    questionRef: "pgm-008",
    partSlug: "reading-part-2",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "travel",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel"],
    skillTag: "reading",
    questionText: "Which person cycled across Europe last summer?",
    pairs: [{ leftText: "Felix", rightText: "completed a charity bike tour" }],
  }),
  goldMatching({
    questionRef: "pgm-009",
    partSlug: "reading-part-2",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "technology",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["technology"],
    skillTag: "reading",
    questionText: "Which person is designing a language-learning app?",
    pairs: [{ leftText: "Sofia", rightText: "is building an app with classmates" }],
  }),
  goldMatching({
    questionRef: "pgm-010",
    partSlug: "reading-part-2",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "culture",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "Which person has written articles for a music magazine?",
    pairs: [{ leftText: "Jon", rightText: "has interviewed several local bands" }],
  }),
  goldMatching({
    questionRef: "pgm-011",
    partSlug: "reading-part-2",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "community",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["community"],
    skillTag: "reading",
    questionText: "Which person is going to organise a food bank collection?",
    pairs: [{ leftText: "Rosa", rightText: "plans to ask local shops for donations" }],
  }),

  // ── reading-part-3: long text (5) ────────────────────────────────────────
  goldReadingComprehension({
    questionRef: "pgm-012",
    partSlug: "reading-part-3",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Why did Maya join the photography society?",
    passage: PET_R3_PASSAGE,
    choices: [
      { text: "Because she enjoyed photographing street life", isCorrect: true },
      { text: "Because her course required it", isCorrect: false },
      { text: "Because she wanted to work in a hospital", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm-013",
    partSlug: "reading-part-3",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "community",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["community"],
    skillTag: "reading",
    questionText: "What charity project did Maya work on?",
    passage: PET_R3_PASSAGE,
    choices: [
      { text: "Photographing an exhibition for a hospital", isCorrect: true },
      { text: "Teaching children to use cameras", isCorrect: false },
      { text: "Selling photos in a supermarket", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm-014",
    partSlug: "reading-part-3",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "friends",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["friends"],
    skillTag: "reading",
    questionText: "How did the project help Maya socially?",
    passage: PET_R3_PASSAGE,
    choices: [
      { text: "She met students from different courses", isCorrect: true },
      { text: "She moved back to her hometown", isCorrect: false },
      { text: "She stopped attending meetings", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm-015",
    partSlug: "reading-part-3",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "travel",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel"],
    skillTag: "reading",
    questionText: "What does Maya do with her friends now?",
    passage: PET_R3_PASSAGE,
    choices: [
      { text: "They travel together during holidays", isCorrect: true },
      { text: "They only meet at society events", isCorrect: false },
      { text: "They study photography online", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm-016",
    partSlug: "reading-part-3",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "feelings",
    grammarTags: ["conjunctions"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "How did Maya feel at the beginning of the story?",
    passage: PET_R3_PASSAGE,
    choices: [
      { text: "Nervous about making friends", isCorrect: true },
      { text: "Angry about moving city", isCorrect: false },
      { text: "Bored with university life", isCorrect: false },
    ],
  }),

  // ── reading-part-4: MCQ cloze (6) ───────────────────────────────────────
  goldMcq({
    questionRef: "pgm-017",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "food",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["food"],
    skillTag: "reading",
    questionText: "Gap (1): fresh produce ___ expensive",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 0 },
    choices: [
      { text: "is", isCorrect: true },
      { text: "are", isCorrect: false },
      { text: "be", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-018",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "community",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["community"],
    skillTag: "reading",
    questionText: "Gap (2): can ___ advice",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 1 },
    choices: [
      { text: "exchange", isCorrect: true },
      { text: "exchanges", isCorrect: false },
      { text: "exchanging", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-019",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "nature",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["nature"],
    skillTag: "reading",
    questionText: "Gap (3): need little ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 2 },
    choices: [
      { text: "maintenance", isCorrect: true },
      { text: "maintain", isCorrect: false },
      { text: "maintained", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-020",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "environment",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["environment"],
    skillTag: "reading",
    questionText: "Gap (4): save ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 3 },
    choices: [
      { text: "water", isCorrect: true },
      { text: "watery", isCorrect: false },
      { text: "watering", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-021",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "home",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["home"],
    skillTag: "reading",
    questionText: "Gap (5): productive and ___ garden",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 4 },
    choices: [
      { text: "attractive", isCorrect: true },
      { text: "attract", isCorrect: false },
      { text: "attractively", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-022",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "health",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["health"],
    skillTag: "reading",
    questionText: "Gap (6): spend more time ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 5 },
    choices: [
      { text: "outdoors", isCorrect: true },
      { text: "outdoor", isCorrect: false },
      { text: "outside of", isCorrect: false },
    ],
  }),

  // ── reading-part-5: open cloze (6) ───────────────────────────────────────
  goldGapFill({
    questionRef: "pgm-023",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "work",
    grammarTags: ["articles"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "She found ___ interesting job in marketing.",
    template: "She found [0] interesting job in marketing.",
    correctAnswers: ["an"],
  }),
  goldGapFill({
    questionRef: "pgm-024",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "travel",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel"],
    skillTag: "reading",
    questionText: "We ___ our tickets online yesterday.",
    template: "We [0] our tickets online yesterday.",
    correctAnswers: ["booked", "bought"],
  }),
  goldGapFill({
    questionRef: "pgm-025",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "technology",
    grammarTags: ["relative_clauses"],
    vocabularyTopics: ["technology"],
    skillTag: "reading",
    questionText: "The laptop ___ I borrowed belongs to my cousin.",
    template: "The laptop [0] I borrowed belongs to my cousin.",
    correctAnswers: ["that", "which"],
  }),
  goldGapFill({
    questionRef: "pgm-026",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "sports",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["sports"],
    skillTag: "reading",
    questionText: "Running is ___ than cycling in hot weather.",
    template: "Running is [0] than cycling in hot weather.",
    correctAnswers: ["harder", "more tiring"],
  }),
  goldGapFill({
    questionRef: "pgm-027",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "culture",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "___ the film was long, the audience enjoyed it.",
    template: "[0] the film was long, the audience enjoyed it.",
    correctAnswers: ["Although", "Though"],
  }),
  goldGapFill({
    questionRef: "pgm-028",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "environment",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["environment"],
    skillTag: "reading",
    questionText: "Plastic waste ___ collected every Friday in our area.",
    template: "Plastic waste [0] collected every Friday in our area.",
    correctAnswers: ["is"],
  }),

  // ── reading-part-6: gapped text (6) ────────────────────────────────────
  goldReadingComprehension({
    questionRef: "pgm-029",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "nature",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["nature"],
    skillTag: "reading",
    questionText: "Which sentence best fits gap 1? (after the opening sentence about navigation)",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[B] Today, light pollution in cities makes it harder to see stars clearly.", isCorrect: true },
      { text: "[F] Visiting a dark-sky park can be an unforgettable experience for families and students alike.", isCorrect: false },
      { text: "[D] These parks also support wildlife that depends on natural darkness.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm-030",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "environment",
    grammarTags: ["conjunctions"],
    vocabularyTopics: ["environment"],
    skillTag: "reading",
    questionText: "Which sentence introduces a contrast after the problem of light pollution?",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[C] However, dark-sky parks protect areas where astronomers and tourists can observe constellations.", isCorrect: true },
      { text: "[A] For centuries, people have looked to the night sky for navigation and inspiration.", isCorrect: false },
      { text: "[E] As a result, several countries have introduced laws to reduce unnecessary outdoor lighting.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm-031",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "animals",
    grammarTags: ["pronouns"],
    vocabularyTopics: ["animals"],
    skillTag: "reading",
    questionText: "Which sentence explains a benefit of dark-sky parks for living things?",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[D] These parks also support wildlife that depends on natural darkness.", isCorrect: true },
      { text: "[B] Today, light pollution in cities makes it harder to see stars clearly.", isCorrect: false },
      { text: "[C] However, dark-sky parks protect areas where astronomers and tourists can observe constellations.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm-032",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "community",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["community"],
    skillTag: "reading",
    questionText: "Which sentence shows a consequence of protecting dark skies?",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[E] As a result, several countries have introduced laws to reduce unnecessary outdoor lighting.", isCorrect: true },
      { text: "[A] For centuries, people have looked to the night sky for navigation and inspiration.", isCorrect: false },
      { text: "[D] These parks also support wildlife that depends on natural darkness.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm-033",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "travel",
    grammarTags: ["superlatives"],
    vocabularyTopics: ["travel"],
    skillTag: "reading",
    questionText: "Which sentence would best conclude the text for general readers?",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[F] Visiting a dark-sky park can be an unforgettable experience for families and students alike.", isCorrect: true },
      { text: "[B] Today, light pollution in cities makes it harder to see stars clearly.", isCorrect: false },
      { text: "[E] As a result, several countries have introduced laws to reduce unnecessary outdoor lighting.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm-034",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "science",
    grammarTags: ["relative_clauses"],
    vocabularyTopics: ["nature"],
    skillTag: "reading",
    questionText: "Which sentence describes where people can study the stars today?",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[C] However, dark-sky parks protect areas where astronomers and tourists can observe constellations.", isCorrect: true },
      { text: "[A] For centuries, people have looked to the night sky for navigation and inspiration.", isCorrect: false },
      { text: "[F] Visiting a dark-sky park can be an unforgettable experience for families and students alike.", isCorrect: false },
    ],
  }),

  // ── writing (2) ──────────────────────────────────────────────────────────
  goldWriting({
    questionRef: "pgm-035",
    partSlug: "writing-part-1",
    sectionSlug: "writing",
    sortOrder: ++sort,
    points: 20,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["future_will", "linking_words"],
    vocabularyTopics: ["school", "technology"],
    skillTag: "writing",
    questionText: "Write an email in response to your English teacher.",
    cambridgeTaskType: "write_email",
    prompt:
      "Your English teacher has sent you an email about a project on local history. Write an email to your teacher.",
    taskDescription: "Write about 100 words. Answer all three points.",
    minWords: 100,
    maxWords: 120,
    requiredPoints: [
      "Explain which historical place you want to research",
      "Say why it interests you",
      "Ask for advice about useful sources",
    ],
  }),
  goldWriting({
    questionRef: "pgm-036",
    partSlug: "writing-part-2",
    sectionSlug: "writing",
    sortOrder: ++sort,
    points: 20,
    difficulty: "medium",
    topicTag: "travel",
    grammarTags: ["past_simple", "linking_words"],
    vocabularyTopics: ["travel", "feelings"],
    skillTag: "writing",
    questionText: "Write a story that begins with the sentence below.",
    cambridgeTaskType: "write_story",
    prompt:
      "Your teacher has asked you to write a story. Your story must begin with this sentence: 'The train was late, but I didn't mind.'",
    taskDescription: "Write about 100 words.",
    minWords: 100,
    maxWords: 130,
  }),

  // ── listening-part-1 (5) ─────────────────────────────────────────────────
  goldMcq({
    questionRef: "pgm-037",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "food",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["food"],
    skillTag: "listening",
    questionText: "What is the man ordering in the café?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "A chicken sandwich", isCorrect: true },
      { text: "A vegetable soup", isCorrect: false },
      { text: "A fruit salad", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-038",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "clothes",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["clothes"],
    skillTag: "listening",
    questionText: "What is the woman trying on in the shop?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "A blue jacket", isCorrect: true },
      { text: "A red scarf", isCorrect: false },
      { text: "Black boots", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-039",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "transport",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["transport"],
    skillTag: "listening",
    questionText: "Where are the tourists standing?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Near a tour bus", isCorrect: true },
      { text: "On a ferry", isCorrect: false },
      { text: "At a taxi rank", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-040",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "home",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["home"],
    skillTag: "listening",
    questionText: "What are the children doing in the garden?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Planting flowers", isCorrect: true },
      { text: "Building a treehouse", isCorrect: false },
      { text: "Playing football", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-041",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "sports",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["sports"],
    skillTag: "listening",
    questionText: "Which activity are the friends watching?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "A volleyball match", isCorrect: true },
      { text: "A cycling race", isCorrect: false },
      { text: "A swimming competition", isCorrect: false },
    ],
  }),

  // ── listening-part-2 (5) ─────────────────────────────────────────────────
  goldMcq({
    questionRef: "pgm-042",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "Why did the girl miss the chemistry lesson?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "She had a dentist appointment", isCorrect: true },
      { text: "She overslept", isCorrect: false },
      { text: "The classroom was closed", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-043",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "work",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["jobs"],
    skillTag: "listening",
    questionText: "What is the man going to do next month?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Start an internship", isCorrect: true },
      { text: "Move to another city", isCorrect: false },
      { text: "Take a holiday abroad", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-044",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "hobbies",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["hobbies"],
    skillTag: "listening",
    questionText: "How often does the club meet?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Every two weeks", isCorrect: true },
      { text: "Once a year", isCorrect: false },
      { text: "Three times a week", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-045",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "technology",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["technology"],
    skillTag: "listening",
    questionText: "What must students do before using the laptops?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Register their name online", isCorrect: true },
      { text: "Pay a deposit", isCorrect: false },
      { text: "Ask their parents for permission", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-046",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "family",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["family"],
    skillTag: "listening",
    questionText: "What has the woman recently celebrated?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Her parents' wedding anniversary", isCorrect: true },
      { text: "Her brother's graduation", isCorrect: false },
      { text: "Her cousin's birthday", isCorrect: false },
    ],
  }),

  // ── listening-part-3: gap fill (5) ───────────────────────────────────────
  goldGapFill({
    questionRef: "pgm-047",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "places",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["places"],
    skillTag: "listening",
    questionText: "The conference is held ___ the city hall.",
    template: "The conference is held [0] the city hall.",
    correctAnswers: ["in", "at"],
  }),
  goldGapFill({
    questionRef: "pgm-048",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "numbers",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["numbers"],
    skillTag: "listening",
    questionText: "Tickets cost ___ pounds for adults.",
    template: "Tickets cost [0] pounds for adults.",
    correctAnswers: ["fifteen", "15"],
  }),
  goldGapFill({
    questionRef: "pgm-049",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "weather",
    grammarTags: ["future_will"],
    vocabularyTopics: ["weather"],
    skillTag: "listening",
    questionText: "The forecast says it ___ rain later.",
    template: "The forecast says it [0] rain later.",
    correctAnswers: ["will"],
  }),
  goldGapFill({
    questionRef: "pgm-050",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "shopping",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["shopping"],
    skillTag: "listening",
    questionText: "Could you pick up a ___ of milk?",
    template: "Could you pick up a [0] of milk?",
    correctAnswers: ["bottle", "carton"],
  }),
  goldGapFill({
    questionRef: "pgm-051",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "work",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["jobs"],
    skillTag: "listening",
    questionText: "The report ___ sent to all staff yesterday.",
    template: "The report [0] sent to all staff yesterday.",
    correctAnswers: ["was"],
  }),

  // ── listening-part-4 (5) ─────────────────────────────────────────────────
  goldMcq({
    questionRef: "pgm-052",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "travel",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel"],
    skillTag: "listening",
    questionText: "Where did the speaker go on her first solo trip?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "To Portugal", isCorrect: true },
      { text: "To Canada", isCorrect: false },
      { text: "To Japan", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-053",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "culture",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "Why does the speaker enjoy live theatre?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Because each performance feels unique", isCorrect: true },
      { text: "Because tickets are always cheap", isCorrect: false },
      { text: "Because she wants to become an actor", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-054",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "environment",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["environment"],
    skillTag: "listening",
    questionText: "What change has the speaker made at home?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Using less single-use plastic", isCorrect: true },
      { text: "Installing solar panels", isCorrect: false },
      { text: "Growing all their vegetables", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-055",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "health",
    grammarTags: ["adverbs_frequency"],
    vocabularyTopics: ["health"],
    skillTag: "listening",
    questionText: "How often does the speaker go running?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Three times a week", isCorrect: true },
      { text: "Every morning", isCorrect: false },
      { text: "Only in winter", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm-056",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "community",
    grammarTags: ["conjunctions"],
    vocabularyTopics: ["community"],
    skillTag: "listening",
    questionText: "What advice does the speaker give to new volunteers?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Start with a small task and ask questions", isCorrect: true },
      { text: "Work alone until you feel confident", isCorrect: false },
      { text: "Focus only on fundraising", isCorrect: false },
    ],
  }),

  // ── listening-part-5: matching (5) ───────────────────────────────────────
  goldMatching({
    questionRef: "pgm-057",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "easy",
    topicTag: "leisure",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["leisure"],
    skillTag: "listening",
    questionText: "Which speaker talks about a film club?",
    pairs: [{ leftText: "Speaker 1", rightText: "film club on Thursdays" }],
  }),
  goldMatching({
    questionRef: "pgm-058",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "sports",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["sports"],
    skillTag: "listening",
    questionText: "Which speaker mentions a climbing wall?",
    pairs: [{ leftText: "Speaker 2", rightText: "indoor climbing sessions" }],
  }),
  goldMatching({
    questionRef: "pgm-059",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "medium",
    topicTag: "culture",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "Which speaker describes a pottery class?",
    pairs: [{ leftText: "Speaker 3", rightText: "pottery workshop" }],
  }),
  goldMatching({
    questionRef: "pgm-060",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "technology",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["technology"],
    skillTag: "listening",
    questionText: "Which speaker joined a robotics team?",
    pairs: [{ leftText: "Speaker 4", rightText: "school robotics team" }],
  }),
  goldMatching({
    questionRef: "pgm-061",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: ++sort,
    points: 1,
    difficulty: "hard",
    topicTag: "nature",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["nature"],
    skillTag: "listening",
    questionText: "Which speaker volunteers at a bird sanctuary?",
    pairs: [{ leftText: "Speaker 5", rightText: "bird sanctuary volunteer work" }],
  }),

  // ── speaking (3) ─────────────────────────────────────────────────────────
  goldSpeaking({
    questionRef: "pgm-062",
    partSlug: "speaking-part-1",
    sectionSlug: "speaking",
    sortOrder: ++sort,
    points: 25,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["present_simple", "question_forms"],
    vocabularyTopics: ["school", "hobbies"],
    skillTag: "speaking",
    questionText: "Answer the examiner's questions about your life and interests.",
    cambridgeTaskType: "conversation",
    prompt:
      "The examiner will ask about your daily routine, studies, and what you like doing in your free time.",
    maxDurationSeconds: 180,
    followUpQuestions: [
      "Tell me about the subjects you enjoy at school.",
      "What would you like to do after you finish school?",
      "How do you usually relax after a busy day?",
    ],
  }),
  goldSpeaking({
    questionRef: "pgm-063",
    partSlug: "speaking-part-2",
    sectionSlug: "speaking",
    sortOrder: ++sort,
    points: 25,
    difficulty: "medium",
    topicTag: "travel",
    grammarTags: ["present_continuous", "prepositions"],
    vocabularyTopics: ["travel", "places"],
    skillTag: "speaking",
    questionText: "Read the scene description and say what you think is happening.",
    cambridgeTaskType: "picture_description_speaking",
    prompt:
      "Read the scene description. Describe the place and the people, and explain why they might be there.",
    taskDescription: "Scene: Two friends are visiting a historic city. They are standing near an old bridge, taking photos, and reading a tourist map.",
    maxDurationSeconds: 180,
  }),
  goldSpeaking({
    questionRef: "pgm-064",
    partSlug: "speaking-part-3",
    sectionSlug: "speaking",
    sortOrder: ++sort,
    points: 25,
    difficulty: "medium",
    topicTag: "environment",
    grammarTags: ["modal_must", "linking_words"],
    vocabularyTopics: ["environment", "community"],
    skillTag: "speaking",
    questionText: "Discuss ways to make your neighbourhood more environmentally friendly.",
    cambridgeTaskType: "conversation",
    prompt:
      "Talk with your partner about things people could do to protect the environment in your area.",
    maxDurationSeconds: 240,
    followUpQuestions: [
      "Which idea would be easiest to start?",
      "What problems might people face?",
      "How could young people encourage others to take part?",
    ],
  }),
];

export const PET_GOLD_MOCK_1 = composeGoldMockManifest({
  level: "pet",
  goldMockId: "pet-gold-mock-1",
  title: "B1 Preliminary Gold Mock 1",
  description:
    "M3.1 academic reference mock for B1 Preliminary — reading, writing, listening, and speaking full form.",
  questions: petQuestions,
  parts: [
    listeningAudio(
      "listening-part-1",
      1,
      "Part 1 — Listen and choose the correct answer",
      "Man: Could I have the chicken sandwich and a glass of water, please? Waiter: Of course. I'll bring it to your table."
    ),
    listeningAudio(
      "listening-part-2",
      2,
      "Part 2 — Listen and choose the best answer",
      "Girl: I missed chemistry because I had a dentist appointment. Teacher: Remember to collect the notes from your partner."
    ),
    listeningAudio(
      "listening-part-3",
      3,
      "Part 3 — Listen and complete each gap",
      "Organiser: The conference is at the city hall. Adult tickets cost fifteen pounds. The weather forecast says it will rain later."
    ),
    listeningAudio(
      "listening-part-4",
      4,
      "Part 4 — Listen to the monologue",
      "Speaker: My first solo trip was to Portugal. I love live theatre because every performance feels different."
    ),
    listeningAudio(
      "listening-part-5",
      5,
      "Part 5 — Listen and match each speaker to an activity",
      "Five students describe clubs: film club, climbing wall, pottery class, robotics team, and bird sanctuary volunteering."
    ),
  ],
});
