import { composeGoldMockManifest } from "@/lib/cambridge-assessment/gold-mocks/gold-mock-compose";
import {
  goldGapFill,
  goldMatching,
  goldMcq,
  goldReadingComprehension,
  goldSpeaking,
  goldWriting,
  listeningAudio,
  readingSectionSlug,
  uniquifyQuestionStems,
} from "@/lib/cambridge-assessment/gold-mocks/gold-mock-helpers";

const READING = readingSectionSlug("pet");

const PET_R3_PASSAGE = `When Amira moved abroad for a summer internship at an international charity, she worried about communicating in English every day. Her mentor paired her with a local volunteer who showed her how to organise online meetings across time zones. Amira learned to write clear emails to partners in three countries and to listen carefully during video calls. By the end of the programme, she had helped launch a campaign about clean water in rural schools. The experience strengthened her confidence and showed her how global teamwork can improve communities far from home.`;

const PET_R4_TEXT =
  "Choosing a career path can feel stressful when friends already talk about university plans. Career advisers suggest exploring internships, part-time jobs, and volunteering to discover what skills you enjoy. Strong relationships with teachers and family often help teenagers handle pressure and make realistic goals. Global companies increasingly value employees who speak more than one language and understand different cultures. Some schools invite alumni to share stories about their first jobs, which makes future work seem less (1) ___. Mentors recommend practising interviews with a friend so answers sound natural rather than (2) ___. When students disagree with parents about career choices, calm conversations usually work better than (3) ___ arguments. International exchange programmes build friendships that last for years and open doors to (4) ___ opportunities. Employers also notice candidates who show empathy and communicate clearly in (5) ___ teams. In a connected world, combining personal relationships with global awareness can lead to a more (6) ___ career journey.";

const PET_R6_PASSAGE = `[A] Many teenagers stay in touch with friends who move to other countries. [B] Messaging apps make it easy to share news across continents within seconds. [C] However, long-distance friendships need trust and regular communication. [D] Some students schedule weekly video calls so they do not lose contact. [E] Cultural differences can cause misunderstandings, but they also teach patience. [F] Maintaining global relationships helps young people feel connected and more open-minded.`;

const petQuestions = [
  goldMcq({
    questionRef: "pgm3-001",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: 1,
    points: 1,
    difficulty: "easy",
    topicTag: "career",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "Careers fair — meet employers from twelve countries, hall open until 4 p.m.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Students can talk to international employers this afternoon.", isCorrect: true },
      { text: "The careers fair finished yesterday.", isCorrect: false },
      { text: "Only teachers may enter the hall.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-002",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: 2,
    points: 1,
    difficulty: "easy",
    topicTag: "global",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "Language exchange tonight — practise English and Spanish with visiting students.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "People can practise languages with visitors tonight.", isCorrect: true },
      { text: "Spanish classes are cancelled.", isCorrect: false },
      { text: "The exchange is for staff only.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-003",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: 3,
    points: 1,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "Peer support room — talk confidentially about friendship or family worries.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Students can discuss personal worries in private.", isCorrect: true },
      { text: "The room is for exam revision only.", isCorrect: false },
      { text: "Appointments are not available.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-004",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: 4,
    points: 1,
    difficulty: "medium",
    topicTag: "career",
    grammarTags: ["future_will"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "Internship applications close Monday — CV workshop Friday at 3 p.m.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Students can get CV help before the deadline.", isCorrect: true },
      { text: "Internships are already full.", isCorrect: false },
      { text: "The workshop is on Monday morning.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-005",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: 5,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "World cultures day — traditional food and music from five continents.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Visitors can experience food and music from many regions.", isCorrect: true },
      { text: "Only local food will be served.", isCorrect: false },
      { text: "The event is next month.", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-006",
    partSlug: "reading-part-1",
    sectionSlug: READING,
    sortOrder: 6,
    points: 1,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["modal_should"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Conflict resolution session — learn strategies for healthy discussions.",
    blueprintQuestionType: "mcq_single",
    choices: [
      { text: "Participants will learn how to discuss disagreements calmly.", isCorrect: true },
      { text: "The session teaches advanced maths.", isCorrect: false },
      { text: "Registration is not required.", isCorrect: false },
    ],
  }),
  goldMatching({
    questionRef: "pgm3-007",
    partSlug: "reading-part-2",
    sectionSlug: READING,
    sortOrder: 7,
    points: 1,
    difficulty: "medium",
    topicTag: "career",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "Who is doing a marketing internship?",
    pairs: [{ leftText: "Amira", rightText: "is working for an international charity" }],
  }),
  goldMatching({
    questionRef: "pgm3-008",
    partSlug: "reading-part-2",
    sectionSlug: READING,
    sortOrder: 8,
    points: 1,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "Who counsels students about friendship problems?",
    pairs: [{ leftText: "Ben", rightText: "runs a peer listening service" }],
  }),
  goldMatching({
    questionRef: "pgm3-009",
    partSlug: "reading-part-2",
    sectionSlug: READING,
    sortOrder: 9,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "Who hosts a podcast about working abroad?",
    pairs: [{ leftText: "Clara", rightText: "interviews graduates in different countries" }],
  }),
  goldMatching({
    questionRef: "pgm3-010",
    partSlug: "reading-part-2",
    sectionSlug: READING,
    sortOrder: 10,
    points: 1,
    difficulty: "hard",
    topicTag: "global",
    grammarTags: ["present_perfect"],
    vocabularyTopics: ["food"],
    skillTag: "reading",
    questionText: "Who has organised a multicultural food festival?",
    pairs: [{ leftText: "Diego", rightText: "has raised money for exchange trips" }],
  }),
  goldMatching({
    questionRef: "pgm3-011",
    partSlug: "reading-part-2",
    sectionSlug: READING,
    sortOrder: 11,
    points: 1,
    difficulty: "medium",
    topicTag: "career",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["health"],
    skillTag: "reading",
    questionText: "Who is going to apply for a nursing course?",
    pairs: [{ leftText: "Elena", rightText: "plans to study health care at college" }],
  }),
  goldReadingComprehension({
    questionRef: "pgm3-012",
    partSlug: "reading-part-3",
    sectionSlug: READING,
    sortOrder: 12,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "Why was Amira worried at first?",
    passage: PET_R3_PASSAGE,
    choices: [
      { text: "She had to use English every day abroad", isCorrect: true },
      { text: "She did not like charity work", isCorrect: false },
      { text: "She refused to attend meetings", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm3-013",
    partSlug: "reading-part-3",
    sectionSlug: READING,
    sortOrder: 13,
    points: 1,
    difficulty: "medium",
    topicTag: "career",
    grammarTags: ["infinitives"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "What did Amira learn to do?",
    passage: PET_R3_PASSAGE,
    choices: [
      { text: "Write clear emails to international partners", isCorrect: true },
      { text: "Translate documents into three languages", isCorrect: false },
      { text: "Design websites for local shops", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm3-014",
    partSlug: "reading-part-3",
    sectionSlug: READING,
    sortOrder: 14,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["community"],
    skillTag: "reading",
    questionText: "What campaign did Amira help launch?",
    passage: PET_R3_PASSAGE,
    choices: [
      { text: "A clean water project for rural schools", isCorrect: true },
      { text: "A music festival in her hometown", isCorrect: false },
      { text: "A sports competition for interns", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm3-015",
    partSlug: "reading-part-3",
    sectionSlug: READING,
    sortOrder: 15,
    points: 1,
    difficulty: "hard",
    topicTag: "relationships",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "What did the experience show Amira?",
    passage: PET_R3_PASSAGE,
    choices: [
      { text: "Global teamwork can improve distant communities", isCorrect: true },
      { text: "Internships are always easy", isCorrect: false },
      { text: "Video calls are unnecessary", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm3-016",
    partSlug: "reading-part-3",
    sectionSlug: READING,
    sortOrder: 16,
    points: 1,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["friends"],
    skillTag: "reading",
    questionText: "Who supported Amira at the start?",
    passage: PET_R3_PASSAGE,
    choices: [
      { text: "A local volunteer mentor", isCorrect: true },
      { text: "Her university professor only", isCorrect: false },
      { text: "A government official", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-017",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: 17,
    points: 1,
    difficulty: "easy",
    topicTag: "career",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "Gap (1): future work seem less ___",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 0 },
    choices: [
      { text: "intimidating", isCorrect: true },
      { text: "intimidate", isCorrect: false },
      { text: "intimidatingly", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-018",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: 18,
    points: 1,
    difficulty: "easy",
    topicTag: "career",
    grammarTags: ["adjectives"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "Gap (2): rather than ___ arguments",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 1 },
    choices: [
      { text: " rehearsed", isCorrect: true },
      { text: "rehearse", isCorrect: false },
      { text: "rehearsal", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-019",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: 19,
    points: 1,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "Gap (3): better than ___ arguments",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 2 },
    choices: [
      { text: " heated", isCorrect: true },
      { text: "heat", isCorrect: false },
      { text: "heating", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-020",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: 20,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["adjectives"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "Gap (4): doors to ___ opportunities",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 3 },
    choices: [
      { text: " international", isCorrect: true },
      { text: "internationally", isCorrect: false },
      { text: "internationality", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-021",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: 21,
    points: 1,
    difficulty: "hard",
    topicTag: "global",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "Gap (5): communicate in ___ teams",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 4 },
    choices: [
      { text: " diverse", isCorrect: true },
      { text: "diversity", isCorrect: false },
      { text: "diversify", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-022",
    partSlug: "reading-part-4",
    sectionSlug: READING,
    sortOrder: 22,
    points: 1,
    difficulty: "medium",
    topicTag: "career",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "Gap (6): more ___ career journey",
    blueprintQuestionType: "mcq_single",
    content: { passage: PET_R4_TEXT, gapIndex: 5 },
    choices: [
      { text: " rewarding", isCorrect: true },
      { text: "reward", isCorrect: false },
      { text: "rewards", isCorrect: false },
    ],
  }),
  goldGapFill({
    questionRef: "pgm3-023",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: 23,
    points: 1,
    difficulty: "easy",
    topicTag: "career",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "She applied ___ a summer internship in Geneva.",
    template: "She applied [0] a summer internship in Geneva.",
    correctAnswers: ["for"],
  }),
  goldGapFill({
    questionRef: "pgm3-024",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: 24,
    points: 1,
    difficulty: "easy",
    topicTag: "relationships",
    grammarTags: ["present_perfect"],
    vocabularyTopics: ["friends"],
    skillTag: "reading",
    questionText: "They have known each other ___ primary school.",
    template: "They have known each other [0] primary school.",
    correctAnswers: ["since"],
  }),
  goldGapFill({
    questionRef: "pgm3-025",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: 25,
    points: 1,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["conditionals"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "If you ___ politely, people usually listen.",
    template: "If you [0] politely, people usually listen.",
    correctAnswers: ["speak"],
  }),
  goldGapFill({
    questionRef: "pgm3-026",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: 26,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["relative_clauses"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "The colleague ___ advice I trust works in Berlin.",
    template: "The colleague [0] advice I trust works in Berlin.",
    correctAnswers: ["whose"],
  }),
  goldGapFill({
    questionRef: "pgm3-027",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: 27,
    points: 1,
    difficulty: "hard",
    topicTag: "global",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "Although the time zones were different, the team ___ successfully.",
    template: "Although the time zones were different, the team [0] successfully.",
    correctAnswers: ["collaborated","cooperated","worked"],
  }),
  goldGapFill({
    questionRef: "pgm3-028",
    partSlug: "reading-part-5",
    sectionSlug: READING,
    sortOrder: 28,
    points: 1,
    difficulty: "medium",
    topicTag: "career",
    grammarTags: ["passive_voice"],
    vocabularyTopics: ["jobs"],
    skillTag: "reading",
    questionText: "His CV ___ reviewed by two mentors yesterday.",
    template: "His CV [0] reviewed by two mentors yesterday.",
    correctAnswers: ["was"],
  }),
  goldReadingComprehension({
    questionRef: "pgm3-029",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: 29,
    points: 1,
    difficulty: "easy",
    topicTag: "relationships",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["friends"],
    skillTag: "reading",
    questionText: "Which sentence introduces friendships across borders?",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[A] Many teenagers stay in touch with friends who move to other countries.", isCorrect: true },
      { text: "[B] Messaging apps make it easy to share news across continents within seconds.", isCorrect: false },
      { text: "[F] Maintaining global relationships helps young people feel connected and more open-minded.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm3-030",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: 30,
    points: 1,
    difficulty: "easy",
    topicTag: "global",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["technology"],
    skillTag: "reading",
    questionText: "Which sentence explains how technology helps?",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[B] Messaging apps make it easy to share news across continents within seconds.", isCorrect: true },
      { text: "[A] Many teenagers stay in touch with friends who move to other countries.", isCorrect: false },
      { text: "[E] Cultural differences can cause misunderstandings, but they also teach patience.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm3-031",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: 31,
    points: 1,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["conjunctions"],
    vocabularyTopics: ["feelings"],
    skillTag: "reading",
    questionText: "Which sentence introduces a challenge?",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[C] However, long-distance friendships need trust and regular communication.", isCorrect: true },
      { text: "[D] Some students schedule weekly video calls so they do not lose contact.", isCorrect: false },
      { text: "[B] Messaging apps make it easy to share news across continents within seconds.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm3-032",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: 32,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["purpose_clauses"],
    vocabularyTopics: ["technology"],
    skillTag: "reading",
    questionText: "Which sentence describes a practical habit?",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[D] Some students schedule weekly video calls so they do not lose contact.", isCorrect: true },
      { text: "[C] However, long-distance friendships need trust and regular communication.", isCorrect: false },
      { text: "[A] Many teenagers stay in touch with friends who move to other countries.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm3-033",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: 33,
    points: 1,
    difficulty: "hard",
    topicTag: "global",
    grammarTags: ["conjunctions"],
    vocabularyTopics: ["culture"],
    skillTag: "reading",
    questionText: "Which sentence mentions cultural learning?",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[E] Cultural differences can cause misunderstandings, but they also teach patience.", isCorrect: true },
      { text: "[D] Some students schedule weekly video calls so they do not lose contact.", isCorrect: false },
      { text: "[F] Maintaining global relationships helps young people feel connected and more open-minded.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "pgm3-034",
    partSlug: "reading-part-6",
    sectionSlug: READING,
    sortOrder: 34,
    points: 1,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["friends"],
    skillTag: "reading",
    questionText: "Which sentence best concludes the text?",
    passage: PET_R6_PASSAGE,
    choices: [
      { text: "[F] Maintaining global relationships helps young people feel connected and more open-minded.", isCorrect: true },
      { text: "[A] Many teenagers stay in touch with friends who move to other countries.", isCorrect: false },
      { text: "[E] Cultural differences can cause misunderstandings, but they also teach patience.", isCorrect: false },
    ],
  }),
  goldWriting({
    questionRef: "pgm3-035",
    partSlug: "writing-part-1",
    sectionSlug: "writing",
    sortOrder: 35,
    points: 20,
    difficulty: "medium",
    topicTag: "career",
    grammarTags: ["future_will","linking_words"],
    vocabularyTopics: ["jobs","school"],
    skillTag: "writing",
    questionText: "Write an email in response to your English teacher.",
    cambridgeTaskType: "write_email",
    prompt: "Your English teacher has asked you to write about your future career plans. Write an email to your teacher.",
    taskDescription: "Write about 100 words. Answer all three points.",
    minWords: 100,
    maxWords: 120,
    requiredPoints: ["Describe a job or field you are interested in","Explain what skills or experience you need","Ask for advice about steps you could take now"],
  }),
  goldWriting({
    questionRef: "pgm3-036",
    partSlug: "writing-part-2",
    sectionSlug: "writing",
    sortOrder: 36,
    points: 20,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["past_simple","linking_words"],
    vocabularyTopics: ["friends","feelings"],
    skillTag: "writing",
    questionText: "Write a story that begins with the sentence below.",
    cambridgeTaskType: "write_story",
    prompt: "Your teacher has asked you to write a story. Your story must begin with this sentence: 'I had not seen my best friend for two years, but the message arrived at the perfect moment.'",
    taskDescription: "Write about 100 words.",
    minWords: 100,
    maxWords: 130,
    imageUrl: "/images/gold-mocks/pet-gold-mock-3-story.svg",
  }),
  goldMcq({
    questionRef: "pgm3-037",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 37,
    points: 1,
    difficulty: "easy",
    topicTag: "career",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["jobs"],
    skillTag: "listening",
    questionText: "What is the woman doing at the careers desk?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Asking about internship forms", isCorrect: true },
      { text: "Buying conference tickets", isCorrect: false },
      { text: "Returning library books", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-038",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 38,
    points: 1,
    difficulty: "easy",
    topicTag: "relationships",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["friends"],
    skillTag: "listening",
    questionText: "What are the friends doing in the park?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Celebrating a reunion with food", isCorrect: true },
      { text: "Practising for a sports match", isCorrect: false },
      { text: "Filming a travel advert", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-039",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 39,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["places"],
    skillTag: "listening",
    questionText: "Where are the students looking at a world map?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "In a geography classroom", isCorrect: true },
      { text: "At a bus station", isCorrect: false },
      { text: "In a swimming pool", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-040",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 40,
    points: 1,
    difficulty: "medium",
    topicTag: "career",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["jobs"],
    skillTag: "listening",
    questionText: "What is the man holding during the interview?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "A CV folder", isCorrect: true },
      { text: "A musical instrument", isCorrect: false },
      { text: "A cooking pan", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-041",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 41,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "What activity are the classmates organising?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "A pen-pal video exchange", isCorrect: true },
      { text: "A car wash fundraiser", isCorrect: false },
      { text: "A chess tournament", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-042",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 42,
    points: 1,
    difficulty: "easy",
    topicTag: "relationships",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["family"],
    skillTag: "listening",
    questionText: "Why did the girl miss the mentoring session?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "She had a family appointment", isCorrect: true },
      { text: "The mentor cancelled", isCorrect: false },
      { text: "She forgot her login details", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-043",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 43,
    points: 1,
    difficulty: "medium",
    topicTag: "career",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["jobs"],
    skillTag: "listening",
    questionText: "What is the boy going to do after school?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Attend a university open day", isCorrect: true },
      { text: "Fly to another country", isCorrect: false },
      { text: "Start a full-time job", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-044",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 44,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "How often does the language club meet?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Every Thursday", isCorrect: true },
      { text: "Once a term", isCorrect: false },
      { text: "Daily at lunchtime", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-045",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 45,
    points: 1,
    difficulty: "hard",
    topicTag: "career",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "What must participants bring to the workshop?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "A list of questions for alumni", isCorrect: true },
      { text: "A printed passport", isCorrect: false },
      { text: "Sports equipment", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-046",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 46,
    points: 1,
    difficulty: "hard",
    topicTag: "relationships",
    grammarTags: ["present_perfect"],
    vocabularyTopics: ["friends"],
    skillTag: "listening",
    questionText: "What has the speaker recently achieved?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Reconnecting with a friend abroad", isCorrect: true },
      { text: "Winning a national cooking prize", isCorrect: false },
      { text: "Moving to a new house", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-047",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 47,
    points: 1,
    difficulty: "easy",
    topicTag: "career",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["jobs"],
    skillTag: "listening",
    questionText: "Where did the speaker meet her mentor?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "At a school careers event", isCorrect: true },
      { text: "On a holiday cruise", isCorrect: false },
      { text: "At a music festival", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-048",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 48,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "Why does the speaker enjoy international projects?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Because she learns from different perspectives", isCorrect: true },
      { text: "Because travel is always free", isCorrect: false },
      { text: "Because she dislikes teamwork", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-049",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 49,
    points: 1,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["present_perfect"],
    vocabularyTopics: ["friends"],
    skillTag: "listening",
    questionText: "What change has the speaker made in friendships?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Scheduling regular calls with friends abroad", isCorrect: true },
      { text: "Stopping all social media use", isCorrect: false },
      { text: "Moving to another continent", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-050",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 50,
    points: 1,
    difficulty: "hard",
    topicTag: "career",
    grammarTags: ["adverbs_frequency"],
    vocabularyTopics: ["jobs"],
    skillTag: "listening",
    questionText: "How often does the speaker practise interview answers?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Twice a week", isCorrect: true },
      { text: "Every morning", isCorrect: false },
      { text: "Only before exams", isCorrect: false },
    ],
  }),
  goldMcq({
    questionRef: "pgm3-051",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 51,
    points: 1,
    difficulty: "hard",
    topicTag: "relationships",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["feelings"],
    skillTag: "listening",
    questionText: "What advice does the speaker give about disagreements?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Listen first and explain your view calmly", isCorrect: true },
      { text: "Avoid talking until the other person apologises", isCorrect: false },
      { text: "Ask a stranger to decide immediately", isCorrect: false },
    ],
  }),
  goldGapFill({
    questionRef: "pgm3-052",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 52,
    points: 1,
    difficulty: "easy",
    topicTag: "career",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["places"],
    skillTag: "listening",
    questionText: "The careers webinar starts ___ 5 p.m.",
    template: "The careers webinar starts [0] 5 p.m.",
    correctAnswers: ["at"],
  }),
  goldGapFill({
    questionRef: "pgm3-053",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 53,
    points: 1,
    difficulty: "easy",
    topicTag: "numbers",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["numbers"],
    skillTag: "listening",
    questionText: "Registration costs ___ pounds online.",
    template: "Registration costs [0] pounds online.",
    correctAnswers: ["ten","10"],
  }),
  goldGapFill({
    questionRef: "pgm3-054",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 54,
    points: 1,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["future_will"],
    vocabularyTopics: ["feelings"],
    skillTag: "listening",
    questionText: "The mentor says she ___ reply by Friday.",
    template: "The mentor says she [0] reply by Friday.",
    correctAnswers: ["will"],
  }),
  goldGapFill({
    questionRef: "pgm3-055",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 55,
    points: 1,
    difficulty: "medium",
    topicTag: "career",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["jobs"],
    skillTag: "listening",
    questionText: "Please write a short ___ about your goals.",
    template: "Please write a short [0] about your goals.",
    correctAnswers: ["paragraph","summary"],
  }),
  goldGapFill({
    questionRef: "pgm3-056",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 56,
    points: 1,
    difficulty: "hard",
    topicTag: "global",
    grammarTags: ["passive_voice"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "The invitation ___ sent to all final-year students.",
    template: "The invitation [0] sent to all final-year students.",
    correctAnswers: ["was"],
  }),
  goldMatching({
    questionRef: "pgm3-057",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: 57,
    points: 1,
    difficulty: "easy",
    topicTag: "career",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["health"],
    skillTag: "listening",
    questionText: "Which speaker talks about a hospital work experience?",
    pairs: [{ leftText: "Speaker 1", rightText: "shadowing nurses for a week" }],
  }),
  goldMatching({
    questionRef: "pgm3-058",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: 58,
    points: 1,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["friends"],
    skillTag: "listening",
    questionText: "Which speaker mentions a long-distance best friend?",
    pairs: [{ leftText: "Speaker 2", rightText: "weekly calls with a friend in Canada" }],
  }),
  goldMatching({
    questionRef: "pgm3-059",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: 59,
    points: 1,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["culture"],
    skillTag: "listening",
    questionText: "Which speaker describes a Model United Nations club?",
    pairs: [{ leftText: "Speaker 3", rightText: "debating global issues after school" }],
  }),
  goldMatching({
    questionRef: "pgm3-060",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: 60,
    points: 1,
    difficulty: "hard",
    topicTag: "career",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["technology"],
    skillTag: "listening",
    questionText: "Which speaker joined a coding internship?",
    pairs: [{ leftText: "Speaker 4", rightText: "building apps for a start-up" }],
  }),
  goldMatching({
    questionRef: "pgm3-061",
    partSlug: "listening-part-5",
    sectionSlug: "listening",
    sortOrder: 61,
    points: 1,
    difficulty: "hard",
    topicTag: "relationships",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "Which speaker volunteers as a peer mediator?",
    pairs: [{ leftText: "Speaker 5", rightText: "helping classmates resolve conflicts" }],
  }),
  goldSpeaking({
    questionRef: "pgm3-062",
    partSlug: "speaking-part-1",
    sectionSlug: "speaking",
    sortOrder: 62,
    points: 25,
    difficulty: "medium",
    topicTag: "career",
    grammarTags: ["present_simple","question_forms"],
    vocabularyTopics: ["jobs","school"],
    skillTag: "speaking",
    questionText: "Answer the examiner's questions about your studies and future plans.",
    cambridgeTaskType: "conversation",
    prompt: "The examiner will ask about your school subjects, career interests, and plans for the future.",
    maxDurationSeconds: 240,
    followUpQuestions: [
          "Which school subjects do you enjoy most? Why?",
          "Have you ever done work experience or volunteering?",
          "What kind of job would you like in the future?",
          "Do you prefer working alone or in a team?",
          "What skills do you think are important for your chosen career?"
    ]
  }),
  goldSpeaking({
    questionRef: "pgm3-063",
    partSlug: "speaking-part-2",
    sectionSlug: "speaking",
    sortOrder: 63,
    points: 25,
    difficulty: "medium",
    topicTag: "global",
    grammarTags: ["present_continuous","prepositions"],
    vocabularyTopics: ["culture","places"],
    skillTag: "speaking",
    questionText: "Describe the photograph and say what you think is happening.",
    cambridgeTaskType: "picture_description_speaking",
    prompt: "Look at the photograph. Describe the setting, the people, and what you think they are doing.",
    maxDurationSeconds: 240,
    imageUrl: "/images/gold-mocks/pet-gold-mock-3-speaking-photo.svg"
  }),
  goldSpeaking({
    questionRef: "pgm3-064",
    partSlug: "speaking-part-3",
    sectionSlug: "speaking",
    sortOrder: 64,
    points: 25,
    difficulty: "medium",
    topicTag: "relationships",
    grammarTags: ["modal_must","linking_words"],
    vocabularyTopics: ["friends","feelings"],
    skillTag: "speaking",
    questionText: "Discuss how young people can maintain strong relationships in a global world.",
    cambridgeTaskType: "conversation",
    prompt: "Talk with your partner about keeping friendships and family relationships healthy when people live far apart.",
    maxDurationSeconds: 300,
    followUpQuestions: [
          "What are the best ways to stay in touch with friends abroad?",
          "How can misunderstandings be avoided in online conversations?",
          "Should schools teach communication skills formally?",
          "What role do parents play in supporting friendships?",
          "How does social media help or harm relationships?",
          "Which habit has worked best for you or someone you know?"
    ]
  }),
];

export const PET_GOLD_MOCK_3 = composeGoldMockManifest({
  level: "pet",
  goldMockId: "pet-gold-mock-3",
  title: "B1 Preliminary Gold Mock 3",
  description: "M4.1 academic reference mock for B1 Preliminary — Career, Relationships, and Global topics across reading, writing, listening, and speaking.",
  questions: uniquifyQuestionStems(petQuestions),
  parts: [
    listeningAudio(
      "listening-part-1",
      1,
      "Part 1 — Listen and choose the correct picture",
      "Woman: I'm asking about internship forms at the careers desk. Friends: We're celebrating a reunion with food in the park."
    ),
    listeningAudio(
      "listening-part-2",
      2,
      "Part 2 — Listen and choose the best answer",
      "Girl: I missed mentoring because of a family appointment. Boy: After school I'm going to a university open day."
    ),
    listeningAudio(
      "listening-part-3",
      3,
      "Part 3 — Listen and complete each gap",
      "Organiser: The careers webinar starts at 5 p.m. Registration costs ten pounds. The mentor will reply by Friday."
    ),
    listeningAudio(
      "listening-part-4",
      4,
      "Part 4 — Listen to the monologue",
      "Speaker: I met my mentor at a school careers event. I schedule calls with friends abroad and practise interviews twice a week."
    ),
    listeningAudio(
      "listening-part-5",
      5,
      "Part 5 — Listen and match each speaker to an activity",
      "Five students describe hospital work experience, long-distance friendship, Model UN, coding internship, and peer mediation."
    ),
  ],
});
