import { composeGoldMockManifest } from "@/lib/cambridge-assessment/gold-mocks/gold-mock-compose";
import {
  buildQuestionsFromSlots,
  type GoldMockSlot,
} from "@/lib/cambridge-assessment/gold-mocks/gold-mock-slot-builder";
import { listeningAudio } from "@/lib/cambridge-assessment/gold-mocks/gold-mock-helpers";

/** M4.1 — Starters Gold Mock 3 (Food, Sports, Travel). */
const SLOTS: GoldMockSlot[] = [
  // ── Listening Part 1: Link names to descriptions ─────────────────────────────
  {
    kind: "matching",
    ref: "sgm3-001",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "sports_football",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["sports"],
    questionText: "Listen. Which boy is Jake?",
    leftText: "Jake",
    rightText: "Boy wearing a green football shirt",
    transcriptSnippet: "This is Jake. He's wearing a green football shirt today.",
  },
  {
    kind: "matching",
    ref: "sgm3-002",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "food_cooking",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["food"],
    questionText: "Listen. Which girl is Sofia?",
    leftText: "Sofia",
    rightText: "Girl holding a bowl of fruit",
    transcriptSnippet: "Sofia is holding a big bowl of fruit for the picnic.",
  },
  {
    kind: "matching",
    ref: "sgm3-003",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "travel_airport",
    grammarTags: ["have_got"],
    vocabularyTopics: ["travel"],
    questionText: "Listen. Which boy is Omar?",
    leftText: "Omar",
    rightText: "Boy with a blue suitcase",
    transcriptSnippet: "Omar has got a blue suitcase. He's ready to travel.",
  },
  {
    kind: "matching",
    ref: "sgm3-004",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "sports_swimming",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["sports"],
    questionText: "Listen. Which girl is Priya?",
    leftText: "Priya",
    rightText: "Girl in a red swimming cap",
    transcriptSnippet: "Priya is wearing a red swimming cap at the pool.",
  },
  {
    kind: "matching",
    ref: "sgm3-005",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "travel_train",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["travel", "food"],
    questionText: "Listen. Which boy is Finn?",
    leftText: "Finn",
    rightText: "Boy eating a sandwich on the train",
    transcriptSnippet: "Look at Finn. He's eating a sandwich on the train.",
  },

  // ── Listening Part 2: Write words or numbers ─────────────────────────────
  {
    kind: "gap_fill",
    ref: "sgm3-006",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "food_breakfast",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["food"],
    questionText: "Listen and write. What does Amy drink for breakfast?",
    template: "Amy drinks [0] for breakfast.",
    correctAnswers: ["milk"],
    transcriptSnippet: "Amy always drinks cold milk for breakfast.",
  },
  {
    kind: "gap_fill",
    ref: "sgm3-007",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "sports_tennis",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["sports"],
    questionText: "Listen and write. What sport does Carlos play?",
    template: "Carlos plays [0].",
    correctAnswers: ["tennis"],
    transcriptSnippet: "Carlos plays tennis every Tuesday after school.",
  },
  {
    kind: "gap_fill",
    ref: "sgm3-008",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "travel_holiday",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["travel"],
    questionText: "Listen and write. Where is the family going on holiday?",
    template: "The family is going to the [0].",
    correctAnswers: ["beach"],
    transcriptSnippet: "Next week the family is going to the beach for their holiday.",
  },
  {
    kind: "gap_fill",
    ref: "sgm3-009",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "food_lunch",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["food"],
    questionText: "Listen and write. How many sandwiches are in the box?",
    template: "There are [0] sandwiches in the box.",
    correctAnswers: ["four", "4"],
    transcriptSnippet: "There are four cheese sandwiches in the lunch box.",
  },
  {
    kind: "gap_fill",
    ref: "sgm3-010",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "travel_bus",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["travel", "colours"],
    questionText: "Listen and write. What colour is the tour bus?",
    template: "The tour bus is [0].",
    correctAnswers: ["yellow"],
    transcriptSnippet: "The big tour bus is yellow with black windows.",
  },

  // ── Listening Part 3: Choose the correct answer ───────────────────────────
  {
    kind: "mcq",
    ref: "sgm3-011",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "food_fruit",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["food"],
    questionText: "What is the girl eating?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "A strawberry", isCorrect: true },
      { text: "A shoe", isCorrect: false },
      { text: "A pencil", isCorrect: false },
    ],
    transcriptSnippet: "The girl is eating a big red strawberry.",
  },
  {
    kind: "mcq",
    ref: "sgm3-012",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "sports_basketball",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["sports"],
    questionText: "What are the boys playing?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Basketball", isCorrect: true },
      { text: "Chess", isCorrect: false },
      { text: "The piano", isCorrect: false },
    ],
    transcriptSnippet: "The boys are playing basketball in the sports hall.",
  },
  {
    kind: "mcq",
    ref: "sgm3-013",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "travel_plane",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["travel"],
    questionText: "Where is the plane?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "In the sky", isCorrect: true },
      { text: "Under the bed", isCorrect: false },
      { text: "In the fridge", isCorrect: false },
    ],
    transcriptSnippet: "The plane is flying high in the sky.",
  },
  {
    kind: "mcq",
    ref: "sgm3-014",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "food_restaurant",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["food", "places"],
    questionText: "What does Dad order at the café?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "A cup of tea", isCorrect: true },
      { text: "A pair of shoes", isCorrect: false },
      { text: "A tennis racket", isCorrect: false },
    ],
    transcriptSnippet: "Dad orders a cup of hot tea at the café.",
  },
  {
    kind: "mcq",
    ref: "sgm3-015",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "hard",
    topicTag: "travel_ferry",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["travel", "weather"],
    questionText: "What are the tourists doing on the ferry?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Looking at the sea and taking photos", isCorrect: true },
      { text: "Cooking dinner in a kitchen", isCorrect: false },
      { text: "Sleeping in class", isCorrect: false },
    ],
    transcriptSnippet: "The tourists are looking at the sea and taking photos on the ferry.",
  },

  // ── Listening Part 4: Colour and draw ────────────────────────────────────
  {
    kind: "mcq",
    ref: "sgm3-016",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "food_picnic",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["food", "colours"],
    questionText: "Colour the apple. Which colour?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Green", isCorrect: true },
      { text: "Silver", isCorrect: false },
      { text: "Pink", isCorrect: false },
    ],
    transcriptSnippet: "Colour the apple green, please.",
  },
  {
    kind: "mcq",
    ref: "sgm3-017",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "sports_ball",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["sports", "colours"],
    questionText: "Colour the football. Which colour?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Orange", isCorrect: true },
      { text: "Purple", isCorrect: false },
      { text: "White", isCorrect: false },
    ],
    transcriptSnippet: "Now colour the football orange.",
  },
  {
    kind: "mcq",
    ref: "sgm3-018",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "travel_map",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["travel"],
    questionText: "Draw an X on the airport on the map. Which option is correct?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "X marked on the airport symbol", isCorrect: true },
      { text: "X marked on the swimming pool", isCorrect: false },
      { text: "X marked on the zoo", isCorrect: false },
    ],
    transcriptSnippet: "Draw an X on the airport on the map.",
  },
  {
    kind: "mcq",
    ref: "sgm3-019",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "food_cake",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["food", "colours"],
    questionText: "Colour the birthday cake. Which colour?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Pink", isCorrect: true },
      { text: "Grey", isCorrect: false },
      { text: "Brown", isCorrect: false },
    ],
    transcriptSnippet: "Colour the birthday cake pink.",
  },
  {
    kind: "mcq",
    ref: "sgm3-020",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "hard",
    topicTag: "travel_boat",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["travel", "places"],
    questionText: "Draw a line from the boy to the boat. Which option is correct?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Boy standing next to the small boat", isCorrect: true },
      { text: "Boy sitting in a classroom", isCorrect: false },
      { text: "Boy sleeping in bed", isCorrect: false },
    ],
    transcriptSnippet: "Draw a line from the boy to the small boat on the lake.",
  },

  // ── RW Part 1: Match words to pictures ───────────────────────────────────
  {
    kind: "matching",
    ref: "sgm3-021",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "food",
    grammarTags: ["articles"],
    vocabularyTopics: ["food"],
    questionText: "Match the word to the description.",
    leftText: "sandwich",
    rightText: "Food with bread, cheese and salad inside",
  },
  {
    kind: "matching",
    ref: "sgm3-022",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "sports",
    grammarTags: ["articles"],
    vocabularyTopics: ["sports"],
    questionText: "Match the word to the description.",
    leftText: "helmet",
    rightText: "Hard hat you wear when riding a bike",
  },
  {
    kind: "matching",
    ref: "sgm3-023",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "travel",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["travel"],
    questionText: "Match the word to the description.",
    leftText: "passport",
    rightText: "Small book you need when you travel to another country",
  },
  {
    kind: "matching",
    ref: "sgm3-024",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "food_drink",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["food", "drink"],
    questionText: "Match the word to the description.",
    leftText: "lemonade",
    rightText: "Cold sweet drink made from lemons",
  },
  {
    kind: "matching",
    ref: "sgm3-025",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "medium",
    topicTag: "sports",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["sports", "places"],
    questionText: "Match the word to the description.",
    leftText: "stadium",
    rightText: "Big building where people watch football matches",
  },

  // ── RW Part 2: Read sentences and choose pictures ────────────────────────
  {
    kind: "reading_comprehension",
    ref: "sgm3-026",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "food_kitchen",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["food", "family"],
    questionText: "Read the sentence. Choose the best answer.",
    passage: "Grandpa is making vegetable soup in a big pot on the stove.",
    choices: [
      { text: "Old man cooking soup in a kitchen", isCorrect: true },
      { text: "Old man playing tennis", isCorrect: false },
      { text: "Old man sleeping on a bus", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm3-027",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "sports_running",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["sports"],
    questionText: "Read the sentence. Choose the best answer.",
    passage: "The children are running a race on the school sports field.",
    choices: [
      { text: "Children running on a sports field", isCorrect: true },
      { text: "Children eating cake at a party", isCorrect: false },
      { text: "Children reading books in a library", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm3-028",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "travel_station",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["travel"],
    questionText: "Read the sentence. Choose the best answer.",
    passage: "We are waiting for our train on platform three at the station.",
    choices: [
      { text: "Family waiting on a train platform", isCorrect: true },
      { text: "Family swimming in the sea", isCorrect: false },
      { text: "Family cooking pizza at home", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm3-029",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "medium",
    topicTag: "food_market",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["food", "shopping"],
    questionText: "Read the sentence. Choose the best answer.",
    passage: "Every Friday Dad buys fresh bread and grapes at the market.",
    choices: [
      { text: "Man buying bread and grapes at a market", isCorrect: true },
      { text: "Man playing basketball alone", isCorrect: false },
      { text: "Man flying a plane", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm3-030",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "hard",
    topicTag: "travel_camping",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["travel", "weather"],
    questionText: "Read the sentence. Choose the best answer.",
    passage: "It is getting dark, so we are putting up our tent at the campsite near the lake.",
    choices: [
      { text: "Family putting up a tent at a campsite", isCorrect: true },
      { text: "Family eating breakfast in a café", isCorrect: false },
      { text: "Family watching TV on the sofa", isCorrect: false },
    ],
  },

  // ── RW Part 3: Read and choose answers ───────────────────────────────────
  {
    kind: "reading_comprehension",
    ref: "sgm3-031",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "food_favourite",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["food"],
    questionText: "Read and choose the best answer.",
    passage:
      "My name is Marco. I am nine years old. My favourite food is pasta with tomato sauce. I don't like fish, but I love cheese on my pizza. On Saturdays I help Mum make pancakes for breakfast.",
    choices: [
      { text: "Marco's favourite food is pasta with tomato sauce.", isCorrect: true },
      { text: "Marco loves eating fish every day.", isCorrect: false },
      { text: "Marco never helps in the kitchen.", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm3-032",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "sports_club",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["sports"],
    questionText: "Read and choose the best answer.",
    passage:
      "I go to the Sports Club on Mondays and Wednesdays. I learn to swim in the pool and play badminton in the hall. My coach is called Mr Lee. He says I am getting faster every week.",
    choices: [
      { text: "The writer goes to the Sports Club twice a week.", isCorrect: true },
      { text: "The writer only plays football at the club.", isCorrect: false },
      { text: "Mr Lee is a maths teacher.", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm3-033",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "medium",
    topicTag: "travel_trip",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel", "family"],
    questionText: "Read and choose the best answer.",
    passage:
      "Last summer we flew to Spain for two weeks. We stayed in a hotel near the sea. Every morning we ate fresh fruit for breakfast and walked along the beach. I collected ten pretty shells.",
    choices: [
      { text: "They flew to Spain for their holiday.", isCorrect: true },
      { text: "They travelled to Spain by train.", isCorrect: false },
      { text: "They stayed in a tent in the mountains.", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm3-034",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "medium",
    topicTag: "food_party",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["food", "leisure"],
    questionText: "Read and choose the best answer.",
    passage:
      "Yesterday was Sports Day at school. After the races we had a big picnic. There were sandwiches, watermelon and juice for everyone. My team won the relay race and we got gold medals.",
    choices: [
      { text: "They had a picnic after Sports Day.", isCorrect: true },
      { text: "Nobody ate any food at Sports Day.", isCorrect: false },
      { text: "The writer's team lost every race.", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm3-035",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "hard",
    topicTag: "travel_museum",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["travel", "places"],
    questionText: "Read and choose the best answer.",
    passage:
      "Next month our class is going to the City Museum by coach. We can see old cars, dinosaur bones and a model of a spaceship. Our teacher says we must bring a packed lunch and a notebook to draw pictures.",
    choices: [
      { text: "The class is visiting the City Museum next month.", isCorrect: true },
      { text: "They are going to the museum by plane.", isCorrect: false },
      { text: "Students cannot bring any food on the trip.", isCorrect: false },
    ],
  },

  // ── RW Part 4: Writing ───────────────────────────────────────────────────
  {
    kind: "writing",
    ref: "sgm3-036",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    difficulty: "easy",
    topicTag: "food_table",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["food"],
    questionText: "Read the scene below. Write one sentence about the fruit on the table.",
    cambridgeTaskType: "write_sentence",
    prompt: "Read the scene below. Write one sentence about the fruit on the table.",
    minWords: 3,
    maxWords: 15,
    taskDescription: "Scene: There is a bowl of apples, bananas, and oranges on the kitchen table.",
  },
  {
    kind: "writing",
    ref: "sgm3-037",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    difficulty: "easy",
    topicTag: "sports_football",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["sports"],
    questionText: "Read the scene below. Write one sentence about the boy and the football.",
    cambridgeTaskType: "write_sentence",
    prompt: "Read the scene below. Write one sentence about the boy and the football.",
    minWords: 3,
    maxWords: 15,
    taskDescription: "Scene: A boy is kicking a football on a field near some trees.",
  },
  {
    kind: "writing",
    ref: "sgm3-038",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    difficulty: "medium",
    topicTag: "travel_airport",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["travel"],
    questionText: "Read the scene below. Write one sentence about the family at the airport.",
    cambridgeTaskType: "write_sentence",
    prompt: "Read the scene below. Write one sentence about the family at the airport.",
    minWords: 4,
    maxWords: 18,
    taskDescription: "Scene: A family is at the airport with suitcases, waiting near the check-in desk.",
  },
  {
    kind: "writing",
    ref: "sgm3-039",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    difficulty: "medium",
    topicTag: "sports_pool",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["sports", "places"],
    questionText: "Read the scene below. Write two or three sentences about the swimming pool.",
    cambridgeTaskType: "picture_description",
    prompt: "Read the scene below. Write two or three sentences about the swimming pool.",
    taskDescription: "Describe what you can see at the swimming pool.",
    minWords: 5,
    maxWords: 25,
    requiredPoints: ["Say who is at the pool", "Say what people are doing"],
  },
  {
    kind: "writing",
    ref: "sgm3-040",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    difficulty: "hard",
    topicTag: "travel_beach",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["travel", "food"],
    questionText: "Read the scene below. Write two or three sentences about the beach picnic.",
    cambridgeTaskType: "picture_description",
    prompt: "Read the scene below. Write two or three sentences about the beach picnic.",
    taskDescription: "Describe the beach and the food people are eating.",
    minWords: 5,
    maxWords: 25,
    requiredPoints: ["Say where the people are", "Say what food you can see"],
  },

  // ── Speaking ─────────────────────────────────────────────────────────────
  {
    kind: "speaking",
    ref: "sgm3-041",
    partSlug: "speaking-part-1",
    sectionSlug: "speaking",
    difficulty: "medium",
    topicTag: "sports_hall",
    grammarTags: ["there_is_are", "prepositions"],
    vocabularyTopics: ["sports", "places"],
    questionText: "Read the two scenes below. Tell your partner about the differences.",
    cambridgeTaskType: "speaking_picture_description",
    prompt:
      "Read Scene A and Scene B below. Tell your partner about five differences between them.",
    maxDurationSeconds: 120,
    taskDescription: "Scene A: A sports hall with a basketball on the floor, five children, and an open door.\nScene B: The same hall with a football, three children, and a closed door.",
    followUpQuestions: [
      "How many basketballs are on the floor in Scene A?",
      "What colour is the goal in Scene B?",
      "Is there a coach in both scenes?",
      "Where is the water bottle in Scene A?",
      "What are the children doing in Scene B?",
    ],
  },
  {
    kind: "speaking",
    ref: "sgm3-042",
    partSlug: "speaking-part-2",
    sectionSlug: "speaking",
    difficulty: "easy",
    topicTag: "about_you_food_sport",
    grammarTags: ["present_simple", "verb_be"],
    vocabularyTopics: ["food", "sports"],
    questionText: "Answer the examiner's questions about you.",
    cambridgeTaskType: "speaking_personal_questions",
    prompt:
      "Answer the examiner's questions about yourself, your favourite food and sports you like.",
    maxDurationSeconds: 180,
    followUpQuestions: [
      "What's your name?",
      "How old are you?",
      "What is your favourite food?",
      "What sport do you like playing?",
      "Have you ever travelled to another town or city?",
    ],
  },
  {
    kind: "speaking",
    ref: "sgm3-043",
    partSlug: "speaking-part-3",
    sectionSlug: "speaking",
    difficulty: "medium",
    topicTag: "story_train_trip",
    grammarTags: ["past_simple", "past_continuous"],
    vocabularyTopics: ["travel", "food", "family"],
    questionText: "Use the story outline and tell the story.",
    cambridgeTaskType: "speaking_storytelling",
    prompt: "Use the story outline to tell the story of Ana's train trip to the city.",
    maxDurationSeconds: 180,
    followUpQuestions: [
      "Who travelled with Ana?",
      "What did they buy at the station?",
      "What did Ana eat at the café?",
      "What did they see from the train window?",
      "What did Ana buy before going home?",
    ],
  },
];

const QUESTIONS = buildQuestionsFromSlots(SLOTS);

const composed = composeGoldMockManifest({
  level: "starters",
  goldMockId: "starters-gold-mock-3",
  title: "Cambridge Starters Gold Mock 3",
  description:
    "M4.1 manually authored Pre-A1 Starters gold mock — Food, Sports & Travel theme. Full 43-item form with listening, reading & writing, and speaking tasks aligned to the M2.0 blueprint.",
  questions: QUESTIONS,
  parts: [
    listeningAudio(
      "listening-part-1",
      1,
      "Link names to descriptions",
      `Examiner: Look at the pictures. Listen and draw a line from each name to the correct person.

This is Jake. He's wearing a green football shirt today.
Sofia is holding a big bowl of fruit for the picnic.
Omar has got a blue suitcase. He's ready to travel.
Priya is wearing a red swimming cap at the pool.
Look at Finn. He's eating a sandwich on the train.`
    ),
    listeningAudio(
      "listening-part-2",
      2,
      "Write words or numbers",
      `Examiner: Listen and write the missing word or number.

Amy always drinks cold milk for breakfast.
Carlos plays tennis every Tuesday after school.
Next week the family is going to the beach for their holiday.
There are four cheese sandwiches in the lunch box.
The big tour bus is yellow with black windows.`
    ),
    listeningAudio(
      "listening-part-3",
      3,
      "Choose the correct answer",
      `Examiner: Listen and Choose the correct answer.

The girl is eating a big red strawberry.
The boys are playing basketball in the sports hall.
The plane is flying high in the sky.
Dad orders a cup of hot tea at the café.
The tourists are looking at the sea and taking photos on the ferry.`
    ),
    listeningAudio(
      "listening-part-4",
      4,
      "Colour and draw",
      `Examiner: Listen and colour or draw.

Colour the apple green, please.
Now colour the football orange.
Draw an X on the airport on the map.
Colour the birthday cake pink.
Draw a line from the boy to the small boat on the lake.`
    ),
  ],
});

export const STARTERS_GOLD_MOCK_3 = composed;
