import { composeGoldMockManifest } from "@/lib/cambridge-assessment/gold-mocks/gold-mock-compose";
import {
  buildQuestionsFromSlots,
  type GoldMockSlot,
} from "@/lib/cambridge-assessment/gold-mocks/gold-mock-slot-builder";
import { listeningAudio } from "@/lib/cambridge-assessment/gold-mocks/gold-mock-helpers";

/** M4.1 — Starters Gold Mock 2 (Animals, Home, Park). */
const SLOTS: GoldMockSlot[] = [
  // ── Listening Part 1: Link names to pictures ─────────────────────────────
  {
    kind: "matching",
    ref: "sgm2-001",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "animals_pets",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["animals"],
    questionText: "Listen. Which boy is Max?",
    leftText: "Max",
    rightText: "Boy feeding a brown rabbit",
    transcriptSnippet: "This is Max. He's feeding a brown rabbit in the garden.",
  },
  {
    kind: "matching",
    ref: "sgm2-002",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "animals_pets",
    grammarTags: ["have_got"],
    vocabularyTopics: ["animals", "home"],
    questionText: "Listen. Which girl is Mia?",
    leftText: "Mia",
    rightText: "Girl holding a small kitten",
    transcriptSnippet: "Mia has got a small kitten. She's holding it carefully.",
  },
  {
    kind: "matching",
    ref: "sgm2-003",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "animals_birds",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["animals"],
    questionText: "Listen. Which boy is Leo?",
    leftText: "Leo",
    rightText: "Boy with a green parrot on his shoulder",
    transcriptSnippet: "Leo is wearing a blue shirt. A green parrot is on his shoulder.",
  },
  {
    kind: "matching",
    ref: "sgm2-004",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "animals_farm",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["animals", "places"],
    questionText: "Listen. Which girl is Eva?",
    leftText: "Eva",
    rightText: "Girl riding a white pony",
    transcriptSnippet: "Eva is riding a white pony near the farm gate.",
  },
  {
    kind: "matching",
    ref: "sgm2-005",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "park_ducks",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["animals", "park"],
    questionText: "Listen. Which boy is Hugo?",
    leftText: "Hugo",
    rightText: "Boy watching ducks on the pond",
    transcriptSnippet: "Look at Hugo. He's watching ducks on the pond in the park.",
  },

  // ── Listening Part 2: Write words or numbers ─────────────────────────────
  {
    kind: "gap_fill",
    ref: "sgm2-006",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "animals_pets",
    grammarTags: ["have_got"],
    vocabularyTopics: ["animals"],
    questionText: "Listen and write. What pet has Tom got?",
    template: "Tom has got a [0].",
    correctAnswers: ["dog"],
    transcriptSnippet: "Tom has got a friendly black and white dog. Its name is Patch.",
  },
  {
    kind: "gap_fill",
    ref: "sgm2-007",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "home_bedroom",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["animals", "home"],
    questionText: "Listen and write. Where does the hamster sleep?",
    template: "The hamster sleeps in its [0].",
    correctAnswers: ["cage"],
    transcriptSnippet: "The hamster sleeps in its cage next to the window.",
  },
  {
    kind: "gap_fill",
    ref: "sgm2-008",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "animals_fish",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["animals"],
    questionText: "Listen and write. How many fish are in the bowl?",
    template: "There are [0] fish in the bowl.",
    correctAnswers: ["three", "3"],
    transcriptSnippet: "There are three orange fish in the glass bowl.",
  },
  {
    kind: "gap_fill",
    ref: "sgm2-009",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "home_garden",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["animals", "home"],
    questionText: "Listen and write. What animal lives in the garden?",
    template: "A [0] lives in the garden.",
    correctAnswers: ["rabbit"],
    transcriptSnippet: "A little rabbit lives in the garden behind our house.",
  },
  {
    kind: "gap_fill",
    ref: "sgm2-010",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "animals_birds",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["animals", "colours"],
    questionText: "Listen and write. What colour is the bird?",
    template: "The bird is [0].",
    correctAnswers: ["orange"],
    transcriptSnippet: "The bird on the tree is orange and very noisy.",
  },

  // ── Listening Part 3: Tick the correct picture ───────────────────────────
  {
    kind: "mcq",
    ref: "sgm2-011",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "home_living_room",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["animals", "home"],
    questionText: "Where is the cat?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "On the sofa", isCorrect: true },
      { text: "In the bath", isCorrect: false },
      { text: "On the bus", isCorrect: false },
    ],
    transcriptSnippet: "The cat is sleeping on the sofa in the living room.",
  },
  {
    kind: "mcq",
    ref: "sgm2-012",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "animals_dog",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["animals", "food"],
    questionText: "What is the dog eating?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "A bone", isCorrect: true },
      { text: "A cake", isCorrect: false },
      { text: "An apple", isCorrect: false },
    ],
    transcriptSnippet: "The hungry dog is eating a big bone in the kitchen.",
  },
  {
    kind: "mcq",
    ref: "sgm2-013",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "animals_rabbit",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["animals", "food"],
    questionText: "What is the rabbit doing?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Eating carrots", isCorrect: true },
      { text: "Flying in the sky", isCorrect: false },
      { text: "Swimming in the sea", isCorrect: false },
    ],
    transcriptSnippet: "The rabbit is eating carrots near the fence.",
  },
  {
    kind: "mcq",
    ref: "sgm2-014",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "park_pond",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["animals", "park"],
    questionText: "Where are the ducks?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "On the pond", isCorrect: true },
      { text: "In the bedroom", isCorrect: false },
      { text: "On the roof", isCorrect: false },
    ],
    transcriptSnippet: "The ducks are on the pond near the big willow tree.",
  },
  {
    kind: "mcq",
    ref: "sgm2-015",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "hard",
    topicTag: "animals_horse",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["animals"],
    questionText: "What can the horse do?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Jump over the fence", isCorrect: true },
      { text: "Cook dinner", isCorrect: false },
      { text: "Read a book", isCorrect: false },
    ],
    transcriptSnippet: "The horse can jump over the fence very well.",
  },

  // ── Listening Part 4: Colour and draw ────────────────────────────────────
  {
    kind: "mcq",
    ref: "sgm2-016",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "animals_garden",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["animals", "colours"],
    questionText: "Colour the butterfly. Which colour?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Purple", isCorrect: true },
      { text: "Grey", isCorrect: false },
      { text: "Brown", isCorrect: false },
    ],
    transcriptSnippet: "Colour the butterfly purple, please.",
  },
  {
    kind: "mcq",
    ref: "sgm2-017",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "easy",
    topicTag: "home_kitchen",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["animals", "home"],
    questionText: "Colour the dog's bowl. Which colour?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Pink", isCorrect: true },
      { text: "Black", isCorrect: false },
      { text: "White", isCorrect: false },
    ],
    transcriptSnippet: "Now colour the dog's bowl pink.",
  },
  {
    kind: "mcq",
    ref: "sgm2-018",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "animals_puppy",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["animals"],
    questionText: "Draw a bone next to the puppy. Which picture shows this?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Bone beside the puppy", isCorrect: true },
      { text: "Bone on the roof", isCorrect: false },
      { text: "Bone inside the fridge", isCorrect: false },
    ],
    transcriptSnippet: "Draw a bone next to the puppy on the grass.",
  },
  {
    kind: "mcq",
    ref: "sgm2-019",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "medium",
    topicTag: "home_aquarium",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["animals", "colours"],
    questionText: "Colour the fish. Which colour?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Blue", isCorrect: true },
      { text: "Red", isCorrect: false },
      { text: "Yellow", isCorrect: false },
    ],
    transcriptSnippet: "Colour the fish in the bowl blue.",
  },
  {
    kind: "mcq",
    ref: "sgm2-020",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    skillTag: "listening",
    difficulty: "hard",
    topicTag: "park_horse",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["animals", "park"],
    questionText: "Draw a line from the girl to the horse. Which picture shows this?",
    blueprintQuestionType: "mcq_listening",
    choices: [
      { text: "Girl standing next to the horse", isCorrect: true },
      { text: "Girl sitting on a bench far away", isCorrect: false },
      { text: "Girl inside the café", isCorrect: false },
    ],
    transcriptSnippet: "Draw a line from the girl to the horse in the field.",
  },

  // ── RW Part 1: Match words to pictures ───────────────────────────────────
  {
    kind: "matching",
    ref: "sgm2-021",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "animals",
    grammarTags: ["articles"],
    vocabularyTopics: ["animals"],
    questionText: "Match the word to the picture.",
    leftText: "rabbit",
    rightText: "Small animal with long ears that hops",
  },
  {
    kind: "matching",
    ref: "sgm2-022",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "home_furniture",
    grammarTags: ["articles"],
    vocabularyTopics: ["home"],
    questionText: "Match the word to the picture.",
    leftText: "sofa",
    rightText: "Soft seat in the living room",
  },
  {
    kind: "matching",
    ref: "sgm2-023",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "park_play",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["park", "leisure"],
    questionText: "Match the word to the picture.",
    leftText: "swing",
    rightText: "Seat that moves back and forth in the park",
  },
  {
    kind: "matching",
    ref: "sgm2-024",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "animals_birds",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["animals"],
    questionText: "Match the word to the picture.",
    leftText: "duck",
    rightText: "Bird that swims on water",
  },
  {
    kind: "matching",
    ref: "sgm2-025",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "medium",
    topicTag: "home_rooms",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["home"],
    questionText: "Match the word to the picture.",
    leftText: "bedroom",
    rightText: "Room where you sleep at night",
  },

  // ── RW Part 2: Read sentences and choose pictures ────────────────────────
  {
    kind: "reading_comprehension",
    ref: "sgm2-026",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "home_kitchen",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["home", "family"],
    questionText: "Read the sentence. Choose the correct picture.",
    passage: "Dad is cooking pasta for dinner in the kitchen.",
    choices: [
      { text: "Man cooking in a kitchen", isCorrect: true },
      { text: "Man sleeping in bed", isCorrect: false },
      { text: "Man driving a car", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm2-027",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "home_bedroom",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["animals", "home"],
    questionText: "Read the sentence. Choose the correct picture.",
    passage: "The grey cat is sleeping on the bed in the bedroom.",
    choices: [
      { text: "Cat sleeping on a bed", isCorrect: true },
      { text: "Cat flying over a house", isCorrect: false },
      { text: "Cat eating soup at a table", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm2-028",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "park_playground",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["park", "leisure"],
    questionText: "Read the sentence. Choose the correct picture.",
    passage: "The children are playing on the swings and the slide in the park.",
    choices: [
      { text: "Children on swings and a slide", isCorrect: true },
      { text: "Children doing homework at desks", isCorrect: false },
      { text: "Children eating in a restaurant", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm2-029",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "medium",
    topicTag: "home_living_room",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["home", "leisure"],
    questionText: "Read the sentence. Choose the correct picture.",
    passage: "Grandma is reading a story book in the armchair by the window.",
    choices: [
      { text: "Old woman reading in an armchair", isCorrect: true },
      { text: "Old woman swimming in a pool", isCorrect: false },
      { text: "Old woman riding a bike", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm2-030",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "hard",
    topicTag: "park_kite",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["park", "weather"],
    questionText: "Read the sentence. Choose the correct picture.",
    passage: "It is windy today, so Ben is flying his kite high above the park trees.",
    choices: [
      { text: "Boy flying a kite in a windy park", isCorrect: true },
      { text: "Boy sitting quietly in a library", isCorrect: false },
      { text: "Boy eating ice cream indoors", isCorrect: false },
    ],
  },

  // ── RW Part 3: Read and choose answers ───────────────────────────────────
  {
    kind: "reading_comprehension",
    ref: "sgm2-031",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "animals_pets",
    grammarTags: ["have_got"],
    vocabularyTopics: ["animals", "home"],
    questionText: "Read and choose the best answer.",
    passage:
      "Hello! My name is Nina. I am seven years old. I have got a white rabbit called Floppy. Floppy lives in a hutch in our garden. Every morning I give him fresh carrots and water.",
    choices: [
      { text: "Nina has got a rabbit called Floppy.", isCorrect: true },
      { text: "Floppy is a big brown horse.", isCorrect: false },
      { text: "Floppy lives in Nina's bedroom.", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm2-032",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "easy",
    topicTag: "home_bedroom",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["home"],
    questionText: "Read and choose the best answer.",
    passage:
      "This is my bedroom. There is a blue bed, a desk and a big wardrobe. My hamster cage is on the desk. I keep my books and toys on the shelf above my bed.",
    choices: [
      { text: "There is a hamster cage on the desk.", isCorrect: true },
      { text: "The bed in the bedroom is red.", isCorrect: false },
      { text: "There are no books in the room.", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm2-033",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "medium",
    topicTag: "park_visit",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["park", "family"],
    questionText: "Read and choose the best answer.",
    passage:
      "Last Saturday we went to Riverside Park. My little brother fed the ducks and I played on the swings. Later we had a picnic under a big oak tree. We walked home when the sun went down.",
    choices: [
      { text: "They had a picnic in the park.", isCorrect: true },
      { text: "They went to the park on Monday.", isCorrect: false },
      { text: "Nobody fed the ducks.", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm2-034",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "medium",
    topicTag: "home_pets",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["animals", "home"],
    questionText: "Read and choose the best answer.",
    passage:
      "Our dog Rex is very clever. He can sit, fetch his ball and open the kitchen door with his paw. Rex sleeps in a basket next to the sofa. He loves going to the park with my dad.",
    choices: [
      { text: "Rex can fetch his ball.", isCorrect: true },
      { text: "Rex sleeps in the garden.", isCorrect: false },
      { text: "Rex cannot open any doors.", isCorrect: false },
    ],
  },
  {
    kind: "reading_comprehension",
    ref: "sgm2-035",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    skillTag: "reading",
    difficulty: "hard",
    topicTag: "animals_zoo",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["animals", "places"],
    questionText: "Read and choose the best answer.",
    passage:
      "Yesterday our class visited City Zoo. We saw giraffes, penguins and a sleepy tiger. The zookeeper told us the tiger eats meat twice a day. My favourite animals were the funny penguins.",
    choices: [
      { text: "The class visited the zoo yesterday.", isCorrect: true },
      { text: "They saw dolphins at the zoo.", isCorrect: false },
      { text: "The tiger eats fruit every day.", isCorrect: false },
    ],
  },

  // ── RW Part 4: Writing ───────────────────────────────────────────────────
  {
    kind: "writing",
    ref: "sgm2-036",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    difficulty: "easy",
    topicTag: "animals_pets",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["animals", "home"],
    questionText: "Look at the picture. Write one sentence about the boy and his dog.",
    cambridgeTaskType: "write_sentence",
    prompt: "Look at the picture. Write one sentence about the boy and his dog.",
    minWords: 3,
    maxWords: 15,
    imageUrl: "/images/gold-mocks/starters/sgm2-036-boy-dog-sofa.png",
  },
  {
    kind: "writing",
    ref: "sgm2-037",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    difficulty: "easy",
    topicTag: "home_kitchen",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["home", "family"],
    questionText: "Look at the picture. Write one sentence about Mum in the kitchen.",
    cambridgeTaskType: "write_sentence",
    prompt: "Look at the picture. Write one sentence about Mum in the kitchen.",
    minWords: 3,
    maxWords: 15,
    imageUrl: "/images/gold-mocks/starters/sgm2-037-mum-kitchen.png",
  },
  {
    kind: "writing",
    ref: "sgm2-038",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    difficulty: "medium",
    topicTag: "park_animals",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["park", "animals"],
    questionText: "Look at the picture. Write one sentence about the ducks on the pond.",
    cambridgeTaskType: "write_sentence",
    prompt: "Look at the picture. Write one sentence about the ducks on the pond.",
    minWords: 4,
    maxWords: 18,
    imageUrl: "/images/gold-mocks/starters/sgm2-038-ducks-pond.png",
  },
  {
    kind: "writing",
    ref: "sgm2-039",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    difficulty: "medium",
    topicTag: "park_playground",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["park", "leisure"],
    questionText: "Look at the picture. Write two or three sentences about the playground.",
    cambridgeTaskType: "picture_description",
    prompt: "Look at the picture. Write two or three sentences about the playground.",
    taskDescription: "Describe what you can see in the park playground picture.",
    minWords: 5,
    maxWords: 25,
    imageUrl: "/images/gold-mocks/starters/sgm2-039-playground.png",
    requiredPoints: ["Say what is in the playground", "Say what the children are doing"],
  },
  {
    kind: "writing",
    ref: "sgm2-040",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    difficulty: "hard",
    topicTag: "home_garden",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["home", "animals"],
    questionText: "Look at the picture. Write two or three sentences about the garden and the pets.",
    cambridgeTaskType: "picture_description",
    prompt: "Look at the picture. Write two or three sentences about the garden and the pets.",
    taskDescription: "Describe the garden and the animals you can see.",
    minWords: 5,
    maxWords: 25,
    imageUrl: "/images/gold-mocks/starters/sgm2-040-garden-pets.png",
    requiredPoints: ["Say what animals are in the garden", "Say what someone is doing"],
  },

  // ── Speaking ─────────────────────────────────────────────────────────────
  {
    kind: "speaking",
    ref: "sgm2-041",
    partSlug: "speaking-part-1",
    sectionSlug: "speaking",
    difficulty: "medium",
    topicTag: "park_scene",
    grammarTags: ["there_is_are", "prepositions"],
    vocabularyTopics: ["park", "animals"],
    questionText: "Look at the two pictures. Tell your partner about the differences.",
    cambridgeTaskType: "speaking_picture_description",
    prompt:
      "Look at the two pictures of a park. Tell your partner about five differences between them.",
    maxDurationSeconds: 120,
    imageUrl: "/images/gold-mocks/starters/sgm2-041-park-pair.png",
    followUpQuestions: [
      "How many ducks are on the pond in picture A?",
      "What colour is the bench in picture B?",
      "Is there a dog in both pictures?",
      "Where is the kite in picture A?",
      "What is the girl doing in picture B?",
    ],
  },
  {
    kind: "speaking",
    ref: "sgm2-042",
    partSlug: "speaking-part-2",
    sectionSlug: "speaking",
    difficulty: "easy",
    topicTag: "about_you_pets",
    grammarTags: ["present_simple", "verb_be"],
    vocabularyTopics: ["animals", "home"],
    questionText: "Answer the examiner's questions about you and your home.",
    cambridgeTaskType: "speaking_personal_questions",
    prompt:
      "Answer the examiner's questions about yourself, your home and any pets you have.",
    maxDurationSeconds: 180,
    followUpQuestions: [
      "What's your name?",
      "Where do you live — in a house or a flat?",
      "Have you got any pets?",
      "What is your favourite animal?",
      "What do you like doing in the park?",
    ],
  },
  {
    kind: "speaking",
    ref: "sgm2-043",
    partSlug: "speaking-part-3",
    sectionSlug: "speaking",
    difficulty: "medium",
    topicTag: "story_park_day",
    grammarTags: ["past_simple", "past_continuous"],
    vocabularyTopics: ["park", "animals", "family"],
    questionText: "Look at the pictures and tell the story.",
    cambridgeTaskType: "speaking_storytelling",
    prompt: "Look at these pictures and tell the story of Lily's day in the park with her dog.",
    maxDurationSeconds: 180,
    pictureSequence: [
      "/images/gold-mocks/starters/sgm2-043-story-1-leash.png",
      "/images/gold-mocks/starters/sgm2-043-story-2-pond.png",
      "/images/gold-mocks/starters/sgm2-043-story-3-icecream.png",
      "/images/gold-mocks/starters/sgm2-043-story-4-home.png",
    ],
    followUpQuestions: [
      "Who went to the park with Lily?",
      "What did they do at the pond?",
      "What did Lily eat?",
      "What was the weather like?",
      "What happened when they got home?",
    ],
  },
];

const QUESTIONS = buildQuestionsFromSlots(SLOTS);

const composed = composeGoldMockManifest({
  level: "starters",
  goldMockId: "starters-gold-mock-2",
  title: "Cambridge Starters Gold Mock 2",
  description:
    "M4.1 manually authored Pre-A1 Starters gold mock — Animals, Home & Park theme. Full 43-item form with listening, reading & writing, and speaking tasks aligned to the M2.0 blueprint.",
  questions: QUESTIONS,
  parts: [
    listeningAudio(
      "listening-part-1",
      1,
      "Link names to pictures",
      `Examiner: Look at the pictures. Listen and draw a line from each name to the correct person.

This is Max. He's feeding a brown rabbit in the garden.
Mia has got a small kitten. She's holding it carefully.
Leo is wearing a blue shirt. A green parrot is on his shoulder.
Eva is riding a white pony near the farm gate.
Look at Hugo. He's watching ducks on the pond in the park.`
    ),
    listeningAudio(
      "listening-part-2",
      2,
      "Write words or numbers",
      `Examiner: Listen and write the missing word or number.

Tom has got a friendly black and white dog. Its name is Patch.
The hamster sleeps in its cage next to the window.
There are three orange fish in the glass bowl.
A little rabbit lives in the garden behind our house.
The bird on the tree is orange and very noisy.`
    ),
    listeningAudio(
      "listening-part-3",
      3,
      "Tick the correct picture",
      `Examiner: Listen and tick the correct picture.

The cat is sleeping on the sofa in the living room.
The hungry dog is eating a big bone in the kitchen.
The rabbit is eating carrots near the fence.
The ducks are on the pond near the big willow tree.
The horse can jump over the fence very well.`
    ),
    listeningAudio(
      "listening-part-4",
      4,
      "Colour and draw",
      `Examiner: Listen and colour or draw.

Colour the butterfly purple, please.
Now colour the dog's bowl pink.
Draw a bone next to the puppy on the grass.
Colour the fish in the bowl blue.
Draw a line from the girl to the horse in the field.`
    ),
  ],
});

export const STARTERS_GOLD_MOCK_2 = composed;
