import { composeGoldMockManifest } from "@/lib/cambridge-assessment/gold-mocks/gold-mock-compose";
import {
  goldGapFill,
  goldMatching,
  goldMcq,
  goldReadingComprehension,
  goldSpeaking,
  goldWriting,
  listeningAudio,
} from "@/lib/cambridge-assessment/gold-mocks/gold-mock-helpers";

const QUESTIONS = [
  // ── Listening Part 1: Link names to descriptions (5 × audio_matching) ──────────
  goldMatching({
    questionRef: "sgm-001",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 1,
    points: 1,
    difficulty: "easy",
    topicTag: "school_friends",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["school", "friends"],
    skillTag: "listening",
    questionText: "Listen. Which boy is Tom?",
    pairs: [{ leftText: "Tom", rightText: "Boy with a red school bag" }],
    content: {
      transcriptSnippet: "This is Tom. He's got a red school bag.",
      audioCue: "name_introduction",
    },
  }),
  goldMatching({
    questionRef: "sgm-002",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 2,
    points: 1,
    difficulty: "easy",
    topicTag: "family",
    grammarTags: ["possessives"],
    vocabularyTopics: ["family"],
    skillTag: "listening",
    questionText: "Listen. Which girl is Anna?",
    pairs: [{ leftText: "Anna", rightText: "Girl with long brown hair" }],
    content: {
      transcriptSnippet: "Anna is my sister. She's got long brown hair.",
      audioCue: "name_introduction",
    },
  }),
  goldMatching({
    questionRef: "sgm-003",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 3,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "Listen. Which boy is Ben?",
    pairs: [{ leftText: "Ben", rightText: "Boy wearing glasses" }],
    content: {
      transcriptSnippet: "Ben wears glasses in class every day.",
      audioCue: "name_introduction",
    },
  }),
  goldMatching({
    questionRef: "sgm-004",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 4,
    points: 1,
    difficulty: "easy",
    topicTag: "friends",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["friends"],
    skillTag: "listening",
    questionText: "Listen. Which girl is Lucy?",
    pairs: [{ leftText: "Lucy", rightText: "Girl in a yellow T-shirt" }],
    content: {
      transcriptSnippet: "Lucy is my friend. She's wearing a yellow T-shirt today.",
      audioCue: "name_introduction",
    },
  }),
  goldMatching({
    questionRef: "sgm-005",
    partSlug: "listening-part-1",
    sectionSlug: "listening",
    sortOrder: 5,
    points: 1,
    difficulty: "medium",
    topicTag: "school_playground",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["school", "sports"],
    skillTag: "listening",
    questionText: "Listen. Which boy is Sam?",
    pairs: [{ leftText: "Sam", rightText: "Boy playing football" }],
    content: {
      transcriptSnippet: "Look at Sam. He's playing football in the playground.",
      audioCue: "name_introduction",
    },
  }),

  // ── Listening Part 2: Write words or numbers (5 × audio_gap_fill) ──────────
  goldGapFill({
    questionRef: "sgm-006",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 6,
    points: 1,
    difficulty: "easy",
    topicTag: "animals_pet",
    grammarTags: ["have_got"],
    vocabularyTopics: ["animals"],
    skillTag: "listening",
    questionText: "Listen and write. What pet has Sally got?",
    template: "Sally has got a [0].",
    correctAnswers: ["cat"],
    content: {
      transcriptSnippet: "Sally has got a small white cat. Its name is Snow.",
      expectedWordType: "noun",
    },
  }),
  goldGapFill({
    questionRef: "sgm-007",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 7,
    points: 1,
    difficulty: "easy",
    topicTag: "food_lunch",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["food"],
    skillTag: "listening",
    questionText: "Listen and write. What does Jack eat for lunch?",
    template: "Jack eats [0] for lunch.",
    correctAnswers: ["pizza"],
    content: {
      transcriptSnippet: "Jack loves pizza. He eats pizza for lunch on Fridays.",
      expectedWordType: "noun",
    },
  }),
  goldGapFill({
    questionRef: "sgm-008",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 8,
    points: 1,
    difficulty: "medium",
    topicTag: "weather",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["weather"],
    skillTag: "listening",
    questionText: "Listen and write. What is the weather like today?",
    template: "Today the weather is [0].",
    correctAnswers: ["sunny"],
    content: {
      transcriptSnippet: "It's a beautiful day. The weather is sunny and warm.",
      expectedWordType: "adjective",
    },
  }),
  goldGapFill({
    questionRef: "sgm-009",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 9,
    points: 1,
    difficulty: "medium",
    topicTag: "school_classroom",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["school"],
    skillTag: "listening",
    questionText: "Listen and write. How many books are on the teacher's desk?",
    template: "There are [0] books on the desk.",
    correctAnswers: ["seven", "7"],
    content: {
      transcriptSnippet: "There are seven books on the teacher's desk.",
      expectedWordType: "number",
    },
  }),
  goldGapFill({
    questionRef: "sgm-010",
    partSlug: "listening-part-2",
    sectionSlug: "listening",
    sortOrder: 10,
    points: 1,
    difficulty: "easy",
    topicTag: "clothes",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["clothes"],
    skillTag: "listening",
    questionText: "Listen and write. What colour is Emma's hat?",
    template: "Emma's hat is [0].",
    correctAnswers: ["blue"],
    content: {
      transcriptSnippet: "Emma is wearing a new blue hat today.",
      expectedWordType: "colour",
    },
  }),

  // ── Listening Part 3: Choose the correct answer (5 × mcq_listening) ─────────
  goldMcq({
    questionRef: "sgm-011",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 11,
    points: 1,
    difficulty: "easy",
    topicTag: "animals_farm",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["animals"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Where is the horse?",
    choices: [
      { text: "In the field", isCorrect: true },
      { text: "In the kitchen", isCorrect: false },
      { text: "On the bus", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "The horse is running in the field near the farm.",
    },
  }),
  goldMcq({
    questionRef: "sgm-012",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 12,
    points: 1,
    difficulty: "easy",
    topicTag: "food_breakfast",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["food", "drink"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What is Mum drinking?",
    choices: [
      { text: "Orange juice", isCorrect: true },
      { text: "Soup", isCorrect: false },
      { text: "Ice cream", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Mum is drinking a glass of orange juice at breakfast.",
    },
  }),
  goldMcq({
    questionRef: "sgm-013",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 13,
    points: 1,
    difficulty: "easy",
    topicTag: "leisure_toys",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["leisure", "home"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What is the boy playing with?",
    choices: [
      { text: "A toy train", isCorrect: true },
      { text: "A football", isCorrect: false },
      { text: "A kite", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "The boy is playing with his toy train on the floor.",
    },
  }),
  goldMcq({
    questionRef: "sgm-014",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 14,
    points: 1,
    difficulty: "medium",
    topicTag: "school_music",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["school", "hobbies"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What can the girl play?",
    choices: [
      { text: "The piano", isCorrect: true },
      { text: "The guitar", isCorrect: false },
      { text: "The drums", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "The girl can play the piano very well.",
    },
  }),
  goldMcq({
    questionRef: "sgm-015",
    partSlug: "listening-part-3",
    sectionSlug: "listening",
    sortOrder: 15,
    points: 1,
    difficulty: "hard",
    topicTag: "family_beach",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["family", "weather"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "What are Dad and Grandpa doing?",
    choices: [
      { text: "Building a sandcastle", isCorrect: true },
      { text: "Reading a book", isCorrect: false },
      { text: "Cooking fish", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Dad and Grandpa are building a big sandcastle on the beach.",
    },
  }),

  // ── Listening Part 4: Colour and draw proxy (5 × mcq_listening) ────────────
  goldMcq({
    questionRef: "sgm-016",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 16,
    points: 1,
    difficulty: "easy",
    topicTag: "animals_garden",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["animals", "colours"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Colour the bird. Which colour?",
    choices: [
      { text: "Green", isCorrect: true },
      { text: "Purple", isCorrect: false },
      { text: "Black", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Colour the bird green, please.",
      taskProxy: "colour_and_draw",
    },
  }),
  goldMcq({
    questionRef: "sgm-017",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 17,
    points: 1,
    difficulty: "easy",
    topicTag: "clothes_bedroom",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["clothes"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Colour the boy's T-shirt. Which colour?",
    choices: [
      { text: "Red", isCorrect: true },
      { text: "Brown", isCorrect: false },
      { text: "Grey", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Now colour the boy's T-shirt red.",
      taskProxy: "colour_and_draw",
    },
  }),
  goldMcq({
    questionRef: "sgm-018",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 18,
    points: 1,
    difficulty: "medium",
    topicTag: "home_garden",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["home", "nature"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Draw a sun in the sky. Where should it go?",
    choices: [
      { text: "Top left of the picture", isCorrect: true },
      { text: "Under the table", isCorrect: false },
      { text: "Inside the bag", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Draw a sun in the top left of the picture.",
      taskProxy: "colour_and_draw",
    },
  }),
  goldMcq({
    questionRef: "sgm-019",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 19,
    points: 1,
    difficulty: "medium",
    topicTag: "garden_art",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["colours", "nature"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Colour the flower. Which colour?",
    choices: [
      { text: "Yellow", isCorrect: true },
      { text: "Orange", isCorrect: false },
      { text: "Pink", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Colour the flower yellow.",
      taskProxy: "colour_and_draw",
    },
  }),
  goldMcq({
    questionRef: "sgm-020",
    partSlug: "listening-part-4",
    sectionSlug: "listening",
    sortOrder: 20,
    points: 1,
    difficulty: "hard",
    topicTag: "leisure_park",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["leisure", "places"],
    skillTag: "listening",
    blueprintQuestionType: "mcq_listening",
    questionText: "Draw a line from the girl to the swing. Which option is correct?",
    choices: [
      { text: "Girl standing next to the swing", isCorrect: true },
      { text: "Girl sitting on a bench far away", isCorrect: false },
      { text: "Girl inside the café", isCorrect: false },
    ],
    content: {
      transcriptSnippet: "Draw a line from the girl to the swing.",
      taskProxy: "colour_and_draw",
    },
  }),

  // ── RW Part 1: Match words to pictures (5 × matching) ──────────────────────
  goldMatching({
    questionRef: "sgm-021",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 21,
    points: 1,
    difficulty: "easy",
    topicTag: "animals",
    grammarTags: ["articles"],
    vocabularyTopics: ["animals"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "elephant", rightText: "Big grey animal with a long nose" }],
  }),
  goldMatching({
    questionRef: "sgm-022",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 22,
    points: 1,
    difficulty: "easy",
    topicTag: "food",
    grammarTags: ["articles"],
    vocabularyTopics: ["food"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "banana", rightText: "Long yellow fruit" }],
  }),
  goldMatching({
    questionRef: "sgm-023",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 23,
    points: 1,
    difficulty: "easy",
    topicTag: "clothes",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["clothes"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "trousers", rightText: "Clothes you wear on your legs" }],
  }),
  goldMatching({
    questionRef: "sgm-024",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 24,
    points: 1,
    difficulty: "easy",
    topicTag: "school",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["school"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "ruler", rightText: "Tool for drawing straight lines" }],
  }),
  goldMatching({
    questionRef: "sgm-025",
    partSlug: "rw-part-1",
    sectionSlug: "reading-writing",
    sortOrder: 25,
    points: 1,
    difficulty: "medium",
    topicTag: "weather",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["weather"],
    skillTag: "reading",
    questionText: "Match the word to the description.",
    pairs: [{ leftText: "cloud", rightText: "White or grey thing in the sky" }],
  }),

  // ── RW Part 2: Read sentences and choose pictures (5 × reading comp) ─────
  goldReadingComprehension({
    questionRef: "sgm-026",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 26,
    points: 1,
    difficulty: "easy",
    topicTag: "family_home",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["family", "home"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "My brother likes playing computer games in his bedroom.",
    choices: [
      { text: "Boy playing on a computer", isCorrect: true },
      { text: "Boy swimming in a pool", isCorrect: false },
      { text: "Boy riding a bike outside", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "sgm-027",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 27,
    points: 1,
    difficulty: "easy",
    topicTag: "animals_zoo",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["animals", "places"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "The monkeys are funny. They are jumping in the zoo.",
    choices: [
      { text: "Monkeys jumping in a zoo", isCorrect: true },
      { text: "Fish swimming in a bowl", isCorrect: false },
      { text: "Birds sitting on a house", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "sgm-028",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 28,
    points: 1,
    difficulty: "easy",
    topicTag: "food_market",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["food", "shopping"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "Mum buys apples and oranges at the market every Saturday.",
    choices: [
      { text: "Woman buying fruit at a market", isCorrect: true },
      { text: "Man cooking soup in a kitchen", isCorrect: false },
      { text: "Children eating ice cream at the cinema", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "sgm-029",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 29,
    points: 1,
    difficulty: "medium",
    topicTag: "school_lunch",
    grammarTags: ["have_got"],
    vocabularyTopics: ["school", "food"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "The children have got sandwiches and milk for lunch at school.",
    choices: [
      { text: "Children eating sandwiches at school", isCorrect: true },
      { text: "Children watching TV at home", isCorrect: false },
      { text: "Children sleeping in bed", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "sgm-030",
    partSlug: "rw-part-2",
    sectionSlug: "reading-writing",
    sortOrder: 30,
    points: 1,
    difficulty: "hard",
    topicTag: "weather_seasons",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["weather", "clothes"],
    skillTag: "reading",
    questionText: "Read the sentence. Choose the best answer.",
    passage: "It is raining today, so the children are wearing boots and coats.",
    choices: [
      { text: "Children in coats and boots in the rain", isCorrect: true },
      { text: "Children in shorts on a sunny beach", isCorrect: false },
      { text: "Children in pyjamas in bed", isCorrect: false },
    ],
  }),

  // ── RW Part 3: Read and choose answers (5 × reading comprehension) ─────────
  goldReadingComprehension({
    questionRef: "sgm-031",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 31,
    points: 1,
    difficulty: "easy",
    topicTag: "pets",
    grammarTags: ["have_got"],
    vocabularyTopics: ["animals", "family"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Hello! My name is Kim. I am eight years old. I have got a small brown dog. His name is Rocky. Rocky can run very fast. We play in the garden every day after school.",
    choices: [
      { text: "Kim has got a dog called Rocky.", isCorrect: true },
      { text: "Kim has got a cat called Rocky.", isCorrect: false },
      { text: "Rocky is a big black horse.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "sgm-032",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 32,
    points: 1,
    difficulty: "easy",
    topicTag: "school_day",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school", "time"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Our school starts at eight o'clock. We have English and Maths in the morning. After lunch we go to the playground. I like playing with my friends there.",
    choices: [
      { text: "The children play in the playground after lunch.", isCorrect: true },
      { text: "School starts at ten o'clock.", isCorrect: false },
      { text: "They only study English all day.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "sgm-033",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 33,
    points: 1,
    difficulty: "medium",
    topicTag: "birthday_party",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["family", "food", "leisure"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Last Sunday was my birthday. My grandma made a big chocolate cake. My cousins came to my house. We played games and opened presents. It was a great day!",
    choices: [
      { text: "The birthday party was last Sunday.", isCorrect: true },
      { text: "The cake was made of cheese.", isCorrect: false },
      { text: "Nobody came to the party.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "sgm-034",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 34,
    points: 1,
    difficulty: "medium",
    topicTag: "trip_zoo",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["animals", "transport"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Yesterday our class went to the zoo by bus. We saw lions, giraffes and penguins. The penguins can swim but they can't fly. My favourite animal was the tall giraffe.",
    choices: [
      { text: "The class went to the zoo by bus.", isCorrect: true },
      { text: "Penguins can fly very high.", isCorrect: false },
      { text: "They saw dolphins at the zoo.", isCorrect: false },
    ],
  }),
  goldReadingComprehension({
    questionRef: "sgm-035",
    partSlug: "rw-part-3",
    sectionSlug: "reading-writing",
    sortOrder: 35,
    points: 1,
    difficulty: "hard",
    topicTag: "weather_holiday",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["weather", "travel", "clothes"],
    skillTag: "reading",
    questionText: "Read and choose the best answer.",
    passage:
      "Next week my family is going to the beach. The weather forecast says it will be sunny and hot. I am going to take my swimsuit, sunglasses and a sun hat. I can't wait!",
    choices: [
      { text: "The family is going to the beach next week.", isCorrect: true },
      { text: "The weather will be cold and snowy.", isCorrect: false },
      { text: "They are going to the mountains.", isCorrect: false },
    ],
  }),

  // ── RW Part 4: Copy and complete writing (5 × writing) ─────────────────────
  goldWriting({
    questionRef: "sgm-036",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 36,
    points: 1,
    difficulty: "easy",
    topicTag: "family",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["family"],
    skillTag: "writing",
    questionText: "Read the scene below. Write one sentence about the girl and her mum.",
    cambridgeTaskType: "write_sentence",
    prompt: "Read the scene below. Write one sentence about the girl and her mum.",
    minWords: 3,
    maxWords: 15,
    taskDescription: "Scene: A girl and her mum are in the kitchen. Mum is washing vegetables and the girl is setting the table.",
  }),
  goldWriting({
    questionRef: "sgm-037",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 37,
    points: 1,
    difficulty: "easy",
    topicTag: "animals",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["animals"],
    skillTag: "writing",
    questionText: "Read the scene below. Write one sentence about the cat.",
    cambridgeTaskType: "write_sentence",
    prompt: "Read the scene below. Write one sentence about the cat.",
    minWords: 3,
    maxWords: 15,
    taskDescription: "Scene: A grey cat is sitting on the window sill and looking outside at the garden.",
  }),
  goldWriting({
    questionRef: "sgm-038",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 38,
    points: 1,
    difficulty: "medium",
    topicTag: "school",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["school"],
    skillTag: "writing",
    questionText: "Read the scene below. Write one sentence about what the children are doing.",
    cambridgeTaskType: "write_sentence",
    prompt: "Read the scene below. Write one sentence about what the children are doing.",
    minWords: 4,
    maxWords: 18,
    taskDescription: "Scene: Three children are in a classroom. They are drawing colourful pictures at their desks.",
  }),
  goldWriting({
    questionRef: "sgm-039",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 39,
    points: 1,
    difficulty: "medium",
    topicTag: "park_play",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["leisure", "places"],
    skillTag: "writing",
    questionText: "Read the scene below. Write two or three sentences about the park.",
    cambridgeTaskType: "picture_description",
    prompt: "Read the scene below. Write two or three sentences about the park.",
    taskDescription: "Describe what you can see in the park picture.",
    minWords: 5,
    maxWords: 25,
    requiredPoints: ["Say what is in the park", "Say what someone is doing"],
  }),
  goldWriting({
    questionRef: "sgm-040",
    partSlug: "rw-part-4",
    sectionSlug: "reading-writing",
    sortOrder: 40,
    points: 1,
    difficulty: "hard",
    topicTag: "weather_clothes",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["weather", "clothes"],
    skillTag: "writing",
    questionText: "Read the scene below. Write two or three sentences about the children in the rain.",
    cambridgeTaskType: "picture_description",
    prompt: "Read the scene below. Write two or three sentences about the children in the rain.",
    taskDescription: "Describe the weather and what the children are wearing.",
    minWords: 5,
    maxWords: 25,
    requiredPoints: ["Say what the weather is like", "Say what the children are wearing"],
  }),

  // ── Speaking Part 1: Find differences (1 × picture description, 5 pts) ─────
  goldSpeaking({
    questionRef: "sgm-041",
    partSlug: "speaking-part-1",
    sectionSlug: "speaking",
    sortOrder: 41,
    points: 5,
    difficulty: "medium",
    topicTag: "home_living_room",
    grammarTags: ["there_is_are", "prepositions"],
    vocabularyTopics: ["home", "leisure"],
    skillTag: "speaking",
    questionText: "Read the two scenes below. Tell your partner about the differences.",
    cambridgeTaskType: "speaking_picture_description",
    prompt:
      "Read Scene A and Scene B below. Tell your partner about five differences between them.",
    taskDescription: `Scene A: A living room with toys on the floor, a blue sofa, a lamp on the left table, and a cat under the chair.
Scene B: The same room with no toys on the floor, a red sofa, the lamp on the right table, and no cat.`,
    maxDurationSeconds: 120,
    followUpQuestions: [
      "How many toys are on the floor in Scene A?",
      "What colour is the sofa in Scene B?",
      "Is there a cat in both scenes?",
      "Where is the lamp in Scene A?",
      "What is on the table in Scene B?",
    ],
  }),

  // ── Speaking Part 2: Personal questions (1 × personal questions, 5 pts) ────
  goldSpeaking({
    questionRef: "sgm-042",
    partSlug: "speaking-part-2",
    sectionSlug: "speaking",
    sortOrder: 42,
    points: 5,
    difficulty: "easy",
    topicTag: "about_you",
    grammarTags: ["present_simple", "verb_be"],
    vocabularyTopics: ["family", "school", "hobbies"],
    skillTag: "speaking",
    questionText: "Answer the examiner's questions about you.",
    cambridgeTaskType: "speaking_personal_questions",
    prompt: "Answer the examiner's questions about yourself, your family and your school.",
    maxDurationSeconds: 180,
    followUpQuestions: [
      "What's your name?",
      "How old are you?",
      "Have you got any brothers or sisters?",
      "What is your favourite school subject?",
      "What do you like doing in your free time?",
    ],
  }),

  // ── Speaking Part 3: Picture story (1 × storytelling, 5 pts) ───────────────
  goldSpeaking({
    questionRef: "sgm-043",
    partSlug: "speaking-part-3",
    sectionSlug: "speaking",
    sortOrder: 43,
    points: 5,
    difficulty: "medium",
    topicTag: "story_beach_day",
    grammarTags: ["past_simple", "past_continuous"],
    vocabularyTopics: ["family", "weather", "food"],
    skillTag: "speaking",
    questionText: "Use the story outline and tell the story.",
    cambridgeTaskType: "speaking_storytelling",
    prompt: "Use the story outline to tell the story of Tom's day at the beach.",
    taskDescription: `Story outline:
1. Tom and his family drive to the beach in a red car.
2. They play on the sandy beach in the sunshine.
3. Tom eats a big ice cream.
4. They drive home tired but happy.`,
    maxDurationSeconds: 180,
    followUpQuestions: [
      "Who went to the beach with Tom?",
      "What did they do first?",
      "What did Tom eat?",
      "How was the weather?",
      "What happened at the end of the day?",
    ],
  }),
];

export const STARTERS_GOLD_MOCK_1 = composeGoldMockManifest({
  level: "starters",
  goldMockId: "starters-gold-mock-1",
  title: "Cambridge Starters Gold Mock 1",
  description:
    "Manually authored Pre-A1 Starters gold mock — full 43-item form with listening, reading & writing, and speaking tasks aligned to the M2.0 blueprint.",
  questions: QUESTIONS,
  parts: [
    listeningAudio(
      "listening-part-1",
      1,
      "Link names to descriptions",
      `Examiner: Look at the pictures. Listen and draw a line from each name to the correct person.

This is Tom. He's got a red school bag.
Anna is my sister. She's got long brown hair.
Ben wears glasses in class every day.
Lucy is my friend. She's wearing a yellow T-shirt today.
Look at Sam. He's playing football in the playground.`
    ),
    listeningAudio(
      "listening-part-2",
      2,
      "Write words or numbers",
      `Examiner: Listen and write the missing word or number.

Sally has got a small white cat. Its name is Snow.
Jack loves pizza. He eats pizza for lunch on Fridays.
It's a beautiful day. The weather is sunny and warm.
There are seven books on the teacher's desk.
Emma is wearing a new blue hat today.`
    ),
    listeningAudio(
      "listening-part-3",
      3,
      "Choose the correct answer",
      `Examiner: Listen and Choose the correct answer.

The horse is running in the field near the farm.
Mum is drinking a glass of orange juice at breakfast.
The boy is playing with his toy train on the floor.
The girl can play the piano very well.
Dad and Grandpa are building a big sandcastle on the beach.`
    ),
    listeningAudio(
      "listening-part-4",
      4,
      "Colour and draw",
      `Examiner: Listen and colour or draw.

Colour the bird green, please.
Now colour the boy's T-shirt red.
Draw a sun in the top left of the picture.
Colour the flower yellow.
Draw a line from the girl to the swing.`
    ),
  ],
});
