/** Movers U5 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-going-to",
      title: "Lesson 1: Going To",
      learningObjective:
        "Use am/is/are + going to + verb to talk about holiday plans.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-going-learn",
          title: "Learn: We're Going To Visit",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "We're going to visit the beach — are + going to + visit.",
              correct: "We're going to visit the beach.",
              wrong: ["We going to visit the beach.", "We're going visit the beach."],
              distractorNotes: ["Thiếu are", "Thiếu to"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh _____ going to pack his suitcase.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh is going to pack — he → is + going to.",
              correct: "is",
              wrong: ["are", "am"],
              distractorNotes: ["We/they → are", "I → am"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "They _____ going to stay at a hotel.",
              skillTag: "grammar",
              topicTag,
              explanation: "They are going to stay — they → are.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["He/she → is", "I → am"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Are you going to travel by _____?",
              skillTag: "grammar",
              topicTag,
              explanation: "Train — câu hỏi going to + travel by train.",
              correct: "train",
              wrong: ["went", "had"],
              distractorNotes: ["Quá khứ", "Quá khứ"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-going-practice",
          title: "Practice: Complete Going To",
          instructions: "Fill in am, is, are or going to.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: We [0] going to visit the beach. | Minh [1] going to pack his suitcase. | They [2] going to travel by train. | [3] you going to forget your passport?",
              skillTag: "grammar",
              topicTag,
              explanation: "are; is; are; Are — going to future.",
              template:
                "We [0] going to visit the beach. Minh [1] going to pack his suitcase. They [2] going to travel by train. [3] you going to forget your passport?",
              correctAnswers: ["are", "is", "are", "Are"],
              acceptableAnswers: [
                ["are", "Are"],
                ["is", "Is"],
                ["are", "Are"],
                ["Are", "are"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-going-check",
          title: "Check: Going To Challenge",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is NOT correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "We are going visit — sai, phải going to visit.",
              correct: "We are going visit the mountains.",
              wrong: ["We are going to visit the mountains.", "Minh is going to pack his bag."],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Dad says: We're going to visit the beach and the _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Mountains — trong bài đọc.",
              correct: "mountains",
              wrong: ["went", "saw"],
              distractorNotes: ["Quá khứ", "Quá khứ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best question about holiday plans:",
              skillTag: "grammar",
              topicTag,
              explanation: "Are you going to travel by train? — câu hỏi going to.",
              correct: "Are you going to travel by train?",
              wrong: ["You going to travel by train?", "Are you go to travel by train?"],
              distractorNotes: ["Thiếu are", "Sai cấu trúc"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-going-apply",
          title: "Apply: Build Going To Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: We / are / going / to / visit / the / beach.",
              skillTag: "grammar",
              topicTag,
              explanation: "We are going to visit the beach.",
              words: ["We", "are", "going", "to", "visit", "the", "beach."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Minh / is / going / to / pack / his / suitcase.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh is going to pack his suitcase.",
              words: ["Minh", "is", "going", "to", "pack", "his", "suitcase."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-going-review",
          title: "Review: Going To Mix",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Mum says: We're going to stay at a hotel near the _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Beach — khách sạn gần biển.",
              correct: "beach",
              wrong: ["went", "had"],
              distractorNotes: ["Quá khứ", "Quá khứ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "They are going to travel by boat and train.",
              correct: "They are going to travel by boat and train.",
              wrong: ["They going to travel by boat.", "They are going travel by train."],
              distractorNotes: ["Thiếu are", "Thiếu to"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh says: We're going to visit the beach _____!",
              skillTag: "grammar",
              topicTag,
              explanation: "Again — trong bài nghe Linh nói again.",
              correct: "again",
              wrong: ["yesterday", "went"],
              distractorNotes: ["Quá khứ", "Quá khứ"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-past-simple",
      title: "Lesson 2: Past Went, Saw, Had",
      learningObjective:
        "Use went, saw and had to talk about finished holiday events.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-past-learn",
          title: "Learn: Went, Saw, Had",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Last summer they _____ to the mountains.",
              skillTag: "grammar",
              topicTag,
              explanation: "Went — quá khứ của go.",
              correct: "went",
              wrong: ["go", "going"],
              distractorNotes: ["Hiện tại", "Going to / -ing"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh _____ a big waterfall near the hotel.",
              skillTag: "grammar",
              topicTag,
              explanation: "Saw — quá khứ của see.",
              correct: "saw",
              wrong: ["see", "seed"],
              distractorNotes: ["Hiện tại", "Sai chính tả"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "They _____ fish for lunch on the holiday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Had — quá khứ của have.",
              correct: "had",
              wrong: ["have", "haved"],
              distractorNotes: ["Hiện tại", "Sai quá khứ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "We had a picnic by the lake — had + picnic.",
              correct: "We had a picnic by the lake.",
              wrong: ["We have a picnic by the lake yesterday.", "We haved a picnic."],
              distractorNotes: ["Yesterday cần quá khứ", "Sai had"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-past-practice",
          title: "Practice: Complete Past Simple",
          instructions: "Fill in went, saw or had.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Last year we [0] to the mountains. | Minh [1] a waterfall. | We [2] a picnic. | Finally we [3] to the beach.",
              skillTag: "grammar",
              topicTag,
              explanation: "went; saw; had; went — quá khứ.",
              template:
                "Last year we [0] to the mountains. Minh [1] a waterfall. We [2] a picnic. Finally we [3] to the beach.",
              correctAnswers: ["went", "saw", "had", "went"],
              acceptableAnswers: [
                ["went", "Went"],
                ["saw", "Saw"],
                ["had", "Had"],
                ["went", "Went"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-past-check",
          title: "Check: Past Simple Challenge",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is NOT correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh goed — sai, phải went.",
              correct: "Minh goed to the beach last year.",
              wrong: ["Minh went to the beach last year.", "Minh saw lots of boats."],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Last summer Minh _____ a beautiful lake.",
              skillTag: "grammar",
              topicTag,
              explanation: "Saw — đã thấy hồ.",
              correct: "saw",
              wrong: ["see", "sees"],
              distractorNotes: ["Hiện tại", "Present simple"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They _____ fish for lunch on the holiday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Had — đã ăn cá.",
              correct: "had",
              wrong: ["have", "has"],
              distractorNotes: ["Hiện tại", "He/she → has"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-past-apply",
          title: "Apply: Order Past Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Last / summer / we / went / to / the / mountains.",
              skillTag: "grammar",
              topicTag,
              explanation: "Last summer we went to the mountains.",
              words: ["Last", "summer", "we", "went", "to", "the", "mountains."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Minh / saw / a / big / waterfall.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh saw a big waterfall.",
              words: ["Minh", "saw", "a", "big", "waterfall."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-past-review",
          title: "Review: Past Simple Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "First we went to the mountains. Then we _____ a waterfall.",
              skillTag: "grammar",
              topicTag,
              explanation: "Saw — thứ tự quá khứ trong bài nghe.",
              correct: "saw",
              wrong: ["see", "going to see"],
              distractorNotes: ["Hiện tại", "Tương lai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We _____ a picnic by a beautiful lake.",
              skillTag: "grammar",
              topicTag,
              explanation: "Had — đã dã ngoại.",
              correct: "had",
              wrong: ["have", "having"],
              distractorNotes: ["Hiện tại", "Continuous"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which time word goes with went/saw/had?",
              skillTag: "grammar",
              topicTag,
              explanation: "Last summer — quá khứ.",
              correct: "Last summer",
              wrong: ["Tomorrow", "We're going to"],
              distractorNotes: ["Tương lai", "Going to"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-plans-vs-past",
      title: "Lesson 3: Mixed Plans vs Past",
      learningObjective:
        "Use going to for plans and went/saw/had for finished holiday events.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-mixed-learn",
          title: "Learn: Plans vs Past",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "This year: We're going to visit the beach. Last year: We _____ to the mountains.",
              skillTag: "grammar",
              topicTag,
              explanation: "Went — năm ngoái dùng quá khứ.",
              correct: "went",
              wrong: ["are going", "going to"],
              distractorNotes: ["Tương lai", "Going to"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which pair is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Plans + past — going to visit / went to mountains.",
              correct: "We're going to visit the hotel. Last summer we went there.",
              wrong: ["We went to visit tomorrow. We are going to went.", "We going to saw the beach."],
              distractorNotes: ["Nhầm thì", "Sai nhiều chỗ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh is going to pack. Last year he _____ a waterfall.",
              skillTag: "grammar",
              topicTag,
              explanation: "Saw — quá khứ vs going to pack.",
              correct: "saw",
              wrong: ["sees", "is going to saw"],
              distractorNotes: ["Hiện tại", "Going to + saw sai"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Future plan: They _____ going to travel by train.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are — they are going to.",
              correct: "are",
              wrong: ["went", "had"],
              distractorNotes: ["Quá khứ", "Quá khứ"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-practice",
          title: "Practice: Plan or Past Gaps",
          instructions: "Fill in going to form or past verb.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: We [0] going to visit the beach. | Last year we [1] to the mountains. | Minh [2] a lake. | We [3] a picnic.",
              skillTag: "grammar",
              topicTag,
              explanation: "are; went; saw; had — tương lai vs quá khứ.",
              template:
                "We [0] going to visit the beach. Last year we [1] to the mountains. Minh [2] a lake. We [3] a picnic.",
              correctAnswers: ["are", "went", "saw", "had"],
              acceptableAnswers: [
                ["are", "Are"],
                ["went", "Went"],
                ["saw", "Saw"],
                ["had", "Had"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-check",
          title: "Check: Mixed Grammar Challenge",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "We're going to the beach. Last year we went to the mountains.",
              correct: "We're going to the beach. Last year we went to the mountains.",
              wrong: ["We went to the beach tomorrow. We are going to went.", "Last year we are going to saw."],
              distractorNotes: ["Nhầm thì", "Sai cấu trúc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh _____ lots of boats on the river last holiday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Saw — quá khứ.",
              correct: "saw",
              wrong: ["is going to see", "sees"],
              distractorNotes: ["Tương lai", "Hiện tại"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Dad says we're going to visit. Mum says last year we _____ fish for lunch.",
              skillTag: "grammar",
              topicTag,
              explanation: "Had — quá khứ.",
              correct: "had",
              wrong: ["have", "are going to have"],
              distractorNotes: ["Hiện tại", "Tương lai"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-apply",
          title: "Apply: Build Mixed Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: We / are / going / to / visit / the / beach / again.",
              skillTag: "grammar",
              topicTag,
              explanation: "We are going to visit the beach again.",
              words: ["We", "are", "going", "to", "visit", "the", "beach", "again."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Last / year / we / had / fish / for / lunch.",
              skillTag: "grammar",
              topicTag,
              explanation: "Last year we had fish for lunch.",
              words: ["Last", "year", "we", "had", "fish", "for", "lunch."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-review",
          title: "Review: Plans vs Past Mix",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best description: this holiday vs last holiday",
              skillTag: "grammar",
              topicTag,
              explanation: "Going to visit beach now; went to mountains last year.",
              correct: "We're going to visit the beach. Last summer we went to the mountains.",
              wrong: ["We went to visit tomorrow. We are going to had lunch.", "We going to went to the hotel."],
              distractorNotes: ["Nhầm thì", "Sai cấu trúc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh asks about last holiday. Minh uses:",
              skillTag: "grammar",
              topicTag,
              explanation: "Went, saw, had — kể chuyện quá khứ.",
              correct: "went, saw and had",
              wrong: ["going to, going to, going to", "am, is, are"],
              distractorNotes: ["Tương lai", "Hiện tại tiếp diễn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum plans the trip. She says:",
              skillTag: "grammar",
              topicTag,
              explanation: "We're going to stay at a hotel — going to.",
              correct: "We're going to stay at a hotel near the beach.",
              wrong: ["We stayed at a hotel tomorrow.", "We going to stayed at a hotel."],
              distractorNotes: ["Nhầm thì", "Sai cấu trúc"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
