/** Movers U5 — reading lessons (3 × 5 exercises). */

export function readingLessons({
  buildMcq,
  buildGapFill,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMinhHoliday,
  topicTag,
}) {
  const passage = passageMinhHoliday;

  return [
    {
      slug: "reading-order-events",
      title: "Lesson 1: Order Events",
      learningObjective:
        "Put holiday events in the correct chronological order using first, then, finally.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-order-learn",
          title: "Learn: First, Then, Finally",
          instructions: "Read the passage. Choose what happens first.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What happens FIRST in the text?",
              skillTag: "reading",
              topicTag,
              explanation: "First, Mum and Dad plan the trip — đoạn đầu.",
              correct: "Mum and Dad plan the trip",
              wrong: ["They arrive at the hotel", "Minh saw a waterfall last summer"],
              distractorNotes: ["Cuối hành trình", "Quá khứ — không phải thứ tự chuyến đi này"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What happens AFTER packing the suitcase?",
              skillTag: "reading",
              topicTag,
              explanation: "Then they travel to the station — sau khi xếp vali.",
              correct: "They travel to the station",
              wrong: ["Linh visits before the holiday", "They had fish for lunch last summer"],
              distractorNotes: ["Trước khi xếp vali", "Quá khứ năm ngoái"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-order-practice",
          title: "Practice: More Event Order",
          instructions: "Read again. Choose the correct order.",
          sortOrder: 1,
          passage,
          difficulty: 0.25,
          questions: [
            buildMcq({
              questionText: "What happens BEFORE they get on the train?",
              skillTag: "reading",
              topicTag,
              explanation: "They take a boat along the river — trước khi lên tàu.",
              correct: "They take a boat along the river",
              wrong: ["They swim at the beach", "They walk in the mountains"],
              distractorNotes: ["Sau khi đến khách sạn", "Sau khi đến khách sạn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What happens FINALLY in the trip story?",
              skillTag: "reading",
              topicTag,
              explanation: "Finally they arrive at the hotel — cuối hành trình.",
              correct: "They arrive at the hotel",
              wrong: ["Minh packs his suitcase", "Dad looks at the map"],
              distractorNotes: ["Đầu chuyến", "Đầu chuyến"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-order-check",
          title: "Check: Event Order Challenge",
          instructions: "Read carefully. Pick the correct order.",
          sortOrder: 2,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Which is the correct order?",
              skillTag: "reading",
              topicTag,
              explanation: "Plan → pack → boat → train → hotel.",
              correct: "Plan → pack → boat → train → hotel",
              wrong: ["Hotel → train → pack → plan", "Pack → hotel → plan → train"],
              distractorNotes: ["Ngược thứ tự", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "After the train, they _____",
              skillTag: "reading",
              topicTag,
              explanation: "Arrive at the hotel — sau tàu đến khách sạn.",
              correct: "arrive at the hotel",
              wrong: ["pack the suitcase", "look at the map at home"],
              distractorNotes: ["Trước chuyến đi", "Ở nhà trước khi đi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Before the train, they go by _____",
              skillTag: "reading",
              topicTag,
              explanation: "Boat — thuyền đến ga.",
              correct: "boat",
              wrong: ["passport", "waterfall"],
              distractorNotes: ["Giấy tờ", "Điểm tham quan sau này"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-order-apply",
          title: "Apply: Match Event to Order",
          instructions: "Match each event to first, then or finally.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each event to when it happens.",
              skillTag: "reading",
              topicTag,
              explanation: "First plan/pack; then boat/train; finally hotel.",
              pairs: [
                { left: "Dad plans with the map", right: "first" },
                { left: "Minh packs his suitcase", right: "first" },
                { left: "They get on the train", right: "then" },
                { left: "They arrive at the hotel", right: "finally" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-order-review",
          title: "Review: Event Order Mix",
          instructions: "Read the passage. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Which event comes between packing and arriving at the hotel?",
              skillTag: "reading",
              topicTag,
              explanation: "Boat and train travel — giữa xếp vali và đến khách sạn.",
              correct: "Boat to station, then train",
              wrong: ["Swim at the beach", "Last summer's waterfall"],
              distractorNotes: ["Sau khi đến khách sạn", "Quá khứ khác"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh visits Minh _____ the family holiday.",
              skillTag: "reading",
              topicTag,
              explanation: "Before — trước kỳ nghỉ.",
              correct: "before",
              wrong: ["after they arrive at the hotel", "finally at the beach"],
              distractorNotes: ["Sau chuyến đi", "Cuối bài"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-chronological",
      title: "Lesson 2: Chronological Narrative",
      learningObjective:
        "Follow a chronological holiday narrative from start to finish.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-chrono-learn",
          title: "Learn: Follow the Story",
          instructions: "Read the passage. What is the story about?",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What is the main story in order?",
              skillTag: "reading",
              topicTag,
              explanation: "Plan, pack, travel, stay at hotel — hành trình kỳ nghỉ.",
              correct: "Plan, pack, travel and stay at a hotel",
              wrong: ["Only last summer's trip", "Shopping at the market"],
              distractorNotes: ["Chỉ một phần quá khứ", "Unit khác"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Where does the family travel TO?",
              skillTag: "reading",
              topicTag,
              explanation: "Beach and mountains — đi biển và núi.",
              correct: "The beach and the mountains",
              wrong: ["Only Hanoi", "Only the train station"],
              distractorNotes: ["Xuất phát", "Chỉ ga — điểm giữa"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-chrono-practice",
          title: "Practice: Story Parts",
          instructions: "Read again. Choose the main point of each part.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "The beginning is mainly about:",
              skillTag: "reading",
              topicTag,
              explanation: "Planning and packing — đầu bài.",
              correct: "Planning and packing for the holiday",
              wrong: ["Swimming at the beach", "Last year's waterfall only"],
              distractorNotes: ["Cuối chuyến", "Chỉ quá khứ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The middle part is mainly about:",
              skillTag: "reading",
              topicTag,
              explanation: "Travel by boat and train — giữa bài.",
              correct: "Travel by boat and train",
              wrong: ["Collecting stamps", "Drawing pictures"],
              distractorNotes: ["Unit 4", "Unit 4"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-chrono-check",
          title: "Check: Chronological Challenge",
          instructions: "Find details in time order.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Which title fits the text best?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh's Family Holiday — tiêu đề bài đọc.",
              correct: "Minh's Family Holiday",
              wrong: ["Rainy Days in Hanoi", "At the Supermarket"],
              distractorNotes: ["Unit 3", "Unit 6"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "On the train, Minh and Linh _____",
              skillTag: "reading",
              topicTag,
              explanation: "Look at the map — trên tàu.",
              correct: "look at the map",
              wrong: ["pack the suitcase", "swim at the beach"],
              distractorNotes: ["Trước chuyến đi", "Sau khi đến"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "At the hotel they _____",
              skillTag: "reading",
              topicTag,
              explanation: "Swim at beach and walk in mountains — cuối bài.",
              correct: "swim at the beach and walk in the mountains",
              wrong: ["pack passports only", "plan the trip with Dad"],
              distractorNotes: ["Trước chuyến", "Đầu bài"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-chrono-apply",
          title: "Apply: Complete Story Gaps",
          instructions: "Fill in using the passage order.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: First Mum and Dad [0] the trip. | Then they travel by [1] and train. | Finally they arrive at the [2]. | Last summer they [3] to the mountains.",
              skillTag: "reading",
              topicTag,
              explanation: "plan; boat; hotel; went — thứ tự câu chuyện.",
              template:
                "First Mum and Dad [0] the trip. Then they travel by [1] and train. Finally they arrive at the [2]. Last summer they [3] to the mountains.",
              correctAnswers: ["plan", "boat", "hotel", "went"],
              acceptableAnswers: [
                ["plan", "Plan", "planned", "Planned"],
                ["boat", "Boat"],
                ["hotel", "Hotel"],
                ["went", "Went"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-chrono-review",
          title: "Review: Chronological Mix",
          instructions: "Find the story order again.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "The text tells the holiday story from:",
              skillTag: "reading",
              topicTag,
              explanation: "Before the trip to arriving and activities — đầu đến cuối.",
              correct: "before the trip to arriving and activities",
              wrong: ["only last summer backwards", "only the train ride"],
              distractorNotes: ["Không chỉ quá khứ ngược", "Chỉ một phần"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence best summarises the narrative?",
              skillTag: "reading",
              topicTag,
              explanation: "Family plans, travels by boat and train, stays at hotel near beach.",
              correct: "The family plans, travels by boat and train, and stays at a hotel near the beach.",
              wrong: ["Minh only collects stamps.", "It was rainy every day."],
              distractorNotes: ["Unit 4", "Unit 3"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-first-next-last",
      title: "Lesson 3: First, Next, Last Detail",
      learningObjective:
        "Find first, next and last details in a chronological holiday text.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-detail-learn",
          title: "Learn: First and Last Details",
          instructions: "Read the passage. Find specific details.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What does Minh put in his suitcase FIRST (in the list)?",
              skillTag: "reading",
              topicTag,
              explanation: "Map, passport, tickets — bài liệt kê map, passport, tickets.",
              correct: "A map, passport and train tickets",
              wrong: ["Only a hat and camera", "Fish for lunch"],
              distractorNotes: ["Không trong bài", "Quá khứ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What did Minh see LAST SUMMER?",
              skillTag: "reading",
              topicTag,
              explanation: "A big waterfall — cuối đoạn quá khứ.",
              correct: "A big waterfall",
              wrong: ["The train station", "Linh drawing"],
              distractorNotes: ["Giữa chuyến năm nay", "Unit 4"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-detail-practice",
          title: "Practice: Match First, Next, Last",
          instructions: "Match each detail to first, next or last in the story.",
          exerciseType: "matching",
          sortOrder: 1,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each detail to its place in the story.",
              skillTag: "reading",
              topicTag,
              explanation: "First plan; next travel; last hotel/arrive; past = last summer.",
              pairs: [
                { left: "Dad looks at the map", right: "first part" },
                { left: "Boat along the river", right: "next part" },
                { left: "Arrive at the hotel", right: "last part of trip" },
                { left: "Had fish for lunch", right: "last summer (past)" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-detail-check",
          title: "Check: Detail Challenge",
          instructions: "Read carefully. Choose the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "What is true about THIS holiday trip?",
              skillTag: "reading",
              topicTag,
              explanation: "Going to stay at hotel near beach — kế hoạch năm nay.",
              correct: "They're going to stay at a hotel near the beach",
              wrong: ["Minh saw a waterfall yesterday on this trip", "They only went to mountains"],
              distractorNotes: ["Quá khứ năm ngoái", "Cả biển và núi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What is true about LAST SUMMER only?",
              skillTag: "reading",
              topicTag,
              explanation: "Went to mountains, saw waterfall, had fish — quá khứ.",
              correct: "They went to the mountains and had fish for lunch",
              wrong: ["They take a boat to the station today", "Linh visits before the holiday"],
              distractorNotes: ["Chuyến năm nay", "Trước chuyến năm nay"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is NOT in the text?",
              skillTag: "reading",
              topicTag,
              explanation: "They fly by plane — không có máy bay trong bài.",
              correct: "They fly by plane to the hotel.",
              wrong: ["Minh packs his suitcase.", "They swim at the beach."],
              distractorNotes: ["Có trong bài", "Có trong bài"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-detail-apply",
          title: "Apply: Gap-Fill First/Last Details",
          instructions: "Fill in using the passage.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: First Dad looks at the [0]. | Next they take a [1] to the station. | At the hotel they swim at the [2]. | Last summer Minh [3] a waterfall.",
              skillTag: "reading",
              topicTag,
              explanation: "map; boat; beach; saw — chi tiết theo thứ tự.",
              template:
                "First Dad looks at the [0]. Next they take a [1] to the station. At the hotel they swim at the [2]. Last summer Minh [3] a waterfall.",
              correctAnswers: ["map", "boat", "beach", "saw"],
              acceptableAnswers: [
                ["map", "Map"],
                ["boat", "Boat"],
                ["beach", "Beach"],
                ["saw", "Saw"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-detail-review",
          title: "Review: First/Last Detail Mix",
          instructions: "Choose the best answer from the text.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          content: { passage },
          questions: [
            buildMcq({
              questionText: "Mum says they're going to stay at a hotel near the _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Beach — trên tàu mẹ nói.",
              correct: "beach",
              wrong: ["mountain only", "train station"],
              distractorNotes: ["Cũng visit núi nhưng hotel gần biển", "Ga — không ở"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The LAST sentence says the holiday was _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Wonderful — câu cuối bài.",
              correct: "wonderful",
              wrong: ["rainy", "boring"],
              distractorNotes: ["Không nói mưa", "Ngược nghĩa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who travels with Minh on the train?",
              skillTag: "reading",
              topicTag,
              explanation: "Linh — Minh and Linh look at the map.",
              correct: "Linh",
              wrong: ["Only Dad", "A teacher"],
              distractorNotes: ["Cả gia đình đi nhưng trên tàu nói Linh", "Không có"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
