/** Movers U5 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-holiday-places",
      title: "Lesson 1: Holiday Places",
      learningObjective:
        "Recognise and use holiday, beach, mountain and hotel in short sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-places-learn",
          title: "Learn: Holiday Place Words",
          instructions: "Read each clue. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "A time when you don't go to school and you travel is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Holiday (kỳ nghỉ) — thời gian đi chơi, nghỉ ngơi.",
              correct: "holiday",
              wrong: ["ticket", "suitcase"],
              distractorNotes: ["Vé — đồ mang theo", "Vali — đồ mang theo"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Sand and sea — you swim and play here. It is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Beach (bãi biển) — nơi có cát và biển.",
              correct: "beach",
              wrong: ["mountain", "hotel"],
              distractorNotes: ["Núi — cao, không có biển", "Khách sạn — nơi ở"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "A very high place with rocks and trees is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mountain (núi) — địa hình cao.",
              correct: "mountain",
              wrong: ["beach", "boat"],
              distractorNotes: ["Bãi biển — thấp, phẳng", "Thuyền — phương tiện"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "When you travel, you can sleep at a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hotel (khách sạn) — nơi ở khi đi nghỉ.",
              correct: "hotel",
              wrong: ["map", "passport"],
              distractorNotes: ["Bản đồ — giấy tờ", "Hộ chiếu — giấy tờ"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-places-practice",
          title: "Practice: Match Holiday Places",
          instructions: "Match each word to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the holiday place words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Holiday, beach, mountain, hotel — địa điểm nghỉ.",
              pairs: [
                { left: "holiday", right: "time away from school to travel" },
                { left: "beach", right: "sandy place by the sea" },
                { left: "mountain", right: "a very high place with rocks" },
                { left: "hotel", right: "a place to stay when you travel" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-places-check",
          title: "Check: Holiday Places Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "We're going to visit the _____ near the hotel.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Beach — bãi biển gần khách sạn.",
              correct: "beach",
              wrong: ["passport", "ticket"],
              distractorNotes: ["Hộ chiếu", "Vé"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Last year Minh went to the _____ with Dad.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mountains — đi núi năm ngoái.",
              correct: "mountains",
              wrong: ["beach only", "train station"],
              distractorNotes: ["Cũng có nhưng câu nói núi", "Ga tàu — không phải điểm đến chính"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh's family is going on _____ this summer.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Holiday — kỳ nghỉ mùa hè.",
              correct: "holiday",
              wrong: ["suitcase", "map"],
              distractorNotes: ["Vali — đồ đem", "Bản đồ — công cụ"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-places-apply",
          title: "Apply: Complete Place Sentences",
          instructions: "Fill in each gap with the correct place word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: We're going on [0] this summer. | We visit the [1] and the mountains. | We stay at a [2] near the beach. | Last year we went to the [3].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "holiday; beach; hotel; mountains — địa điểm nghỉ.",
              template:
                "We're going on [0] this summer. We visit the [1] and the mountains. We stay at a [2] near the beach. Last year we went to the [3].",
              correctAnswers: ["holiday", "beach", "hotel", "mountains"],
              acceptableAnswers: [
                ["holiday", "Holiday"],
                ["beach", "Beach"],
                ["hotel", "Hotel"],
                ["mountains", "Mountains", "mountain", "Mountain"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-places-review",
          title: "Review: Holiday Places Mix",
          instructions: "Mixed review from this lesson. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Where do you swim and play in the sand?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "At the beach — bãi biển.",
              correct: "at the beach",
              wrong: ["at the hotel desk", "on the train"],
              distractorNotes: ["Lễ tân khách sạn", "Trên tàu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We're going to stay at a _____ near the beach.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hotel — khách sạn gần biển.",
              correct: "hotel",
              wrong: ["mountain", "boat"],
              distractorNotes: ["Núi — không ở", "Thuyền — di chuyển"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh saw a waterfall in the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mountains — thác nước ở núi.",
              correct: "mountains",
              wrong: ["beach", "suitcase"],
              distractorNotes: ["Biển — không có thác", "Vali"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-travel-items",
      title: "Lesson 2: Travel Items",
      learningObjective:
        "Use suitcase, map, ticket and passport to talk about packing and travel.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-items-learn",
          title: "Learn: Travel Item Words",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "You pack your clothes in a _____ before a trip.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Suitcase (vali) — đựng quần áo khi đi.",
              correct: "suitcase",
              wrong: ["map", "beach"],
              distractorNotes: ["Bản đồ — giấy", "Bãi biển — địa điểm"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Dad looks at the _____ to find the way.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Map (bản đồ) — chỉ đường.",
              correct: "map",
              wrong: ["passport", "holiday"],
              distractorNotes: ["Hộ chiếu — giấy tờ", "Kỳ nghỉ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mum puts the train _____ in her bag.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Tickets (vé) — cần để lên tàu.",
              correct: "tickets",
              wrong: ["mountains", "hotels"],
              distractorNotes: ["Núi", "Khách sạn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Don't forget your _____ when you travel abroad.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Passport (hộ chiếu) — giấy tờ quan trọng.",
              correct: "passport",
              wrong: ["beach", "boat"],
              distractorNotes: ["Bãi biển", "Thuyền"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-items-practice",
          title: "Practice: Match Travel Items",
          instructions: "Match each word to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match suitcase, map, ticket and passport.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Suitcase, map, ticket, passport — đồ mang khi đi.",
              pairs: [
                { left: "suitcase", right: "a bag on wheels for clothes" },
                { left: "map", right: "a drawing that shows places and roads" },
                { left: "ticket", right: "a paper that lets you travel on a train" },
                { left: "passport", right: "an important book for travelling abroad" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-items-check",
          title: "Check: Travel Items Quiz",
          instructions: "Choose the best answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh packs his _____ before the holiday.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Suitcase — xếp vali trước khi đi.",
              correct: "suitcase",
              wrong: ["waterfall", "picnic"],
              distractorNotes: ["Thác nước — điểm tham quan", "Dã ngoại — hoạt động"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "On the train Minh and Linh look at the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Map — xem bản đồ trên tàu.",
              correct: "map",
              wrong: ["passport only", "hotel room"],
              distractorNotes: ["Hộ chiếu — không xem trên tàu", "Phòng khách sạn — sau này"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum says: Don't forget your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Passport — đừng quên hộ chiếu.",
              correct: "passport",
              wrong: ["beach", "mountain"],
              distractorNotes: ["Bãi biển", "Núi"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-items-apply",
          title: "Apply: Complete Travel Item Sentences",
          instructions: "Complete the sentences about travel items.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh packs his [0]. | Dad looks at the [1]. | Mum puts the train [2] in her bag. | Don't forget your [3]!",
              skillTag: "vocabulary",
              topicTag,
              explanation: "suitcase; map; tickets; passport — đồ mang theo.",
              template:
                "Minh packs his [0]. Dad looks at the [1]. Mum puts the train [2] in her bag. Don't forget your [3]!",
              correctAnswers: ["suitcase", "map", "tickets", "passport"],
              acceptableAnswers: [
                ["suitcase", "Suitcase"],
                ["map", "Map"],
                ["tickets", "Tickets", "ticket", "Ticket"],
                ["passport", "Passport"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-items-review",
          title: "Review: Travel Items Mix",
          instructions: "Mixed review. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which item do you need to get on the train?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "A ticket — cần vé tàu.",
              correct: "a ticket",
              wrong: ["a mountain", "a holiday"],
              distractorNotes: ["Núi — địa điểm", "Kỳ nghỉ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh has a _____ of the coast to help pack.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Map — bản đồ bờ biển.",
              correct: "map",
              wrong: ["suitcase", "passport"],
              distractorNotes: ["Vali", "Hộ chiếu — khác bản đồ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh puts his passport and tickets in his _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Bag/suitcase — trong bài nghe Minh bỏ vào túi/vali.",
              correct: "bag",
              wrong: ["beach", "waterfall"],
              distractorNotes: ["Bãi biển", "Thác nước"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-travel-verbs",
      title: "Lesson 3: Visit, Travel, Train and Boat",
      learningObjective:
        "Use visit, travel, train and boat in holiday and travel contexts.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-travel-learn",
          title: "Learn: Travel Action Words",
          instructions: "Choose the word that best completes each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "We're going to _____ the beach and the mountains.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Visit (thăm) — đi thăm địa điểm.",
              correct: "visit",
              wrong: ["pack", "forget"],
              distractorNotes: ["Xếp đồ", "Quên — nghĩa khác"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The family _____ to the station by boat.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Travels (du lịch/đi) — đi đến ga.",
              correct: "travels",
              wrong: ["visits", "packs"],
              distractorNotes: ["Thăm — điểm đến", "Xếp vali"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "They get on the _____ to go to the coast.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Train (tàu hỏa) — phương tiện đến biển.",
              correct: "train",
              wrong: ["map", "hotel"],
              distractorNotes: ["Bản đồ", "Khách sạn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "First they take a _____ along the river.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Boat (thuyền) — đi thuyền trên sông.",
              correct: "boat",
              wrong: ["passport", "ticket office"],
              distractorNotes: ["Hộ chiếu", "Phòng vé"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-travel-practice",
          title: "Practice: Match Travel Words",
          instructions: "Match each word to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match visit, travel, train and boat.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Visit, travel, train, boat — hành động và phương tiện.",
              pairs: [
                { left: "visit", right: "go to see a place" },
                { left: "travel", right: "go from one place to another" },
                { left: "train", right: "a long vehicle on rails" },
                { left: "boat", right: "a vehicle that moves on water" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-travel-check",
          title: "Check: Travel Words Challenge",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "We're going to _____ a hotel near the beach.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Visit/stay — going to visit or stay at hotel.",
              correct: "stay at",
              wrong: ["travel at", "boat at"],
              distractorNotes: ["Travel + to", "Boat — phương tiện"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "First the boat to the station, then the _____ to the hotel.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Train — sau thuyền là tàu.",
              correct: "train",
              wrong: ["beach", "mountain"],
              distractorNotes: ["Bãi biển — điểm đến", "Núi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh saw lots of _____ on the river last holiday.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Boats — nhiều thuyền trên sông.",
              correct: "boats",
              wrong: ["trains", "hotels"],
              distractorNotes: ["Tàu — trên đường ray", "Khách sạn"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-travel-apply",
          title: "Apply: Complete Travel Sentences",
          instructions: "Fill in with visit, travel, train or boat.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: We're going to [0] the beach. | The family [1] to the station. | They get on the [2]. | First they take a [3] on the river.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "visit; travels; train; boat — hành trình.",
              template:
                "We're going to [0] the beach. The family [1] to the station. They get on the [2]. First they take a [3] on the river.",
              correctAnswers: ["visit", "travels", "train", "boat"],
              acceptableAnswers: [
                ["visit", "Visit"],
                ["travels", "Travels", "travel", "Travel"],
                ["train", "Train"],
                ["boat", "Boat"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-travel-review",
          title: "Review: All Travel Words Mix",
          instructions: "Choose the best word from the whole unit.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "We're going to travel by _____ after the boat.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Train — tàu sau thuyền.",
              correct: "train",
              wrong: ["passport", "holiday"],
              distractorNotes: ["Hộ chiếu", "Kỳ nghỉ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Dad says we're going to _____ the mountains and the beach.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Visit — thăm núi và biển.",
              correct: "visit",
              wrong: ["pack", "forget"],
              distractorNotes: ["Xếp đồ", "Quên"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They _____ along the river to reach the station.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Take a boat / travel — đi thuyền trên sông.",
              correct: "take a boat",
              wrong: ["visit a map", "pack a train"],
              distractorNotes: ["Không hợp lý", "Không hợp lý"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
