/** Flyers U5 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-passive-built-invented",
      title: "Lesson 1: was built / was invented",
      learningObjective:
        "Use was/were + past participle to talk about inventions and projects.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-passive-learn",
          title: "Learn: was built / was invented",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Our robot _____ by the whole class last week.",
              skillTag: "grammar",
              topicTag,
              explanation: "Was built — was + past participle (built).",
              correct: "was built",
              wrong: ["was build", "built was"],
              distractorNotes: ["Thiếu past participle", "Sai thứ tự"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The microscope _____ long ago by a scientist.",
              skillTag: "grammar",
              topicTag,
              explanation: "Was invented — was + invented.",
              correct: "was invented",
              wrong: ["was invent", "invented was"],
              distractorNotes: ["Thiếu -ed", "Sai thứ tự"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The machine in the laboratory _____ last year.",
              skillTag: "grammar",
              topicTag,
              explanation: "Was built — máy được chế tạo năm ngoái.",
              correct: "was built",
              wrong: ["was builded", "built the machine was"],
              distractorNotes: ["Builded không đúng", "Word order wrong"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Electricity _____ through many experiments in history.",
              skillTag: "grammar",
              topicTag,
              explanation: "Was discovered — bị động với discover → discovered.",
              correct: "was discovered",
              wrong: ["was discover", "discovered was by"],
              distractorNotes: ["Thiếu -ed", "Fragment"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-passive-practice",
          title: "Practice: Complete Passive Forms",
          instructions: "Fill in each gap with the correct form.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: The robot was [0] by our class. | The telescope was [1] long ago. | The project was [2] yesterday.",
              skillTag: "grammar",
              topicTag,
              explanation: "built; invented; finished/built — past participle sau was.",
              template:
                "The robot was [0] by our class. The telescope was [1] long ago. The project was [2] yesterday.",
              correctAnswers: ["built", "invented", "finished"],
              acceptableAnswers: [
                ["built", "Built"],
                ["invented", "Invented"],
                ["finished", "Finished", "built", "Built", "completed", "Completed"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-passive-check",
          title: "Check: Passive Voice Challenge",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "The robot was built by Minh's class — was + built.",
              correct: "The robot was built by Minh's class.",
              wrong: [
                "The robot built by Minh's class.",
                "The robot was build by Minh's class.",
              ],
              distractorNotes: ["Thiếu was", "Build không phải participle"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "The microscope was invented long ago.",
              correct: "The microscope was invented long ago.",
              wrong: [
                "The microscope was invent long ago.",
                "The microscope invented was long ago.",
              ],
              distractorNotes: ["Invent không phải participle", "Word order wrong"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Our experiment _____ to show how energy works.",
              skillTag: "grammar",
              topicTag,
              explanation: "Was invented — thí nghiệm được thiết kế/phát minh.",
              correct: "was invented",
              wrong: ["was invent", "invented was"],
              distractorNotes: ["Thiếu -ed", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-passive-apply",
          title: "Apply: Build Passive Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: The / robot / was / built / by / our / class.",
              skillTag: "grammar",
              topicTag,
              explanation: "The robot was built by our class.",
              words: ["The", "robot", "was", "built", "by", "our", "class."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: The / telescope / was / invented / to / look / at / planets.",
              skillTag: "grammar",
              topicTag,
              explanation: "The telescope was invented to look at planets.",
              words: ["The", "telescope", "was", "invented", "to", "look", "at", "planets."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-passive-review",
          title: "Review: Passive Voice Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "The small machine in the laboratory _____ last month.",
              skillTag: "grammar",
              topicTag,
              explanation: "Was built — was + past participle.",
              correct: "was built",
              wrong: ["was build", "built was"],
              distractorNotes: ["Thiếu participle", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "The project was finished yesterday.",
              correct: "The project was finished yesterday.",
              wrong: [
                "The project finished was yesterday.",
                "The project was finish yesterday.",
              ],
              distractorNotes: ["Word order wrong", "Finish không phải participle"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The invention _____ by twelve students at the fair.",
              skillTag: "grammar",
              topicTag,
              explanation: "Was built — phát minh được làm bởi học sinh.",
              correct: "was built",
              wrong: ["was build", "built was by"],
              distractorNotes: ["Thiếu -t", "Fragment"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-could-might",
      title: "Lesson 2: Could / might for possibility",
      learningObjective:
        "Use could and might + base verb to express possibility in science contexts.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-could-learn",
          title: "Learn: could / might",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "The second result _____ be better tomorrow.",
              skillTag: "grammar",
              topicTag,
              explanation: "Might be — might + base verb (be).",
              correct: "might",
              wrong: ["mights", "might be better is"],
              distractorNotes: ["Không chia might", "Thừa từ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "We _____ test another battery in the laboratory.",
              skillTag: "grammar",
              topicTag,
              explanation: "Could test — could + base verb.",
              correct: "could test",
              wrong: ["could to test", "could testing"],
              distractorNotes: ["Could + to (×)", "Could + -ing (×)"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh _____ discover something useful with the microscope.",
              skillTag: "grammar",
              topicTag,
              explanation: "Could discover — could + discover.",
              correct: "could discover",
              wrong: ["could discovers", "could to discover"],
              distractorNotes: ["Could không chia -s", "Could + to (×)"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The robot _____ need more electricity to move.",
              skillTag: "grammar",
              topicTag,
              explanation: "Might need — might + need.",
              correct: "might need",
              wrong: ["might needs", "might to need"],
              distractorNotes: ["Might không chia -s", "Might + to (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-could-practice",
          title: "Practice: Complete could / might",
          instructions: "Fill in each gap.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: The result might [0] better. | We could [1] the laboratory again. | Linh might [2] a new planet.",
              skillTag: "grammar",
              topicTag,
              explanation: "be; use; discover — might/could + base verb.",
              template:
                "The result might [0] better. We could [1] the laboratory again. Linh might [2] a new planet.",
              correctAnswers: ["be", "use", "discover"],
              acceptableAnswers: [
                ["be", "Be"],
                ["use", "Use", "visit", "Visit"],
                ["discover", "Discover", "find", "Find"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-could-check",
          title: "Check: Could / might Challenge",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "The experiment might work — might + base verb.",
              correct: "The experiment might work if we use more electricity.",
              wrong: [
                "The experiment might works if we use more electricity.",
                "The experiment might to work if we use more electricity.",
              ],
              distractorNotes: ["Might + -s (×)", "Might + to (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "We could see another planet — could + see.",
              correct: "We could see another planet through the telescope tonight.",
              wrong: [
                "We could to see another planet through the telescope tonight.",
                "We could seeing another planet through the telescope tonight.",
              ],
              distractorNotes: ["Could + to (×)", "Could + -ing (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The invention _____ win first prize at the fair.",
              skillTag: "grammar",
              topicTag,
              explanation: "Might win — khả năng thắng giải.",
              correct: "might win",
              wrong: ["might wins", "might to win"],
              distractorNotes: ["Might + -s (×)", "Might + to (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-could-apply",
          title: "Apply: Order could / might Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: The / result / might / change / tomorrow.",
              skillTag: "grammar",
              topicTag,
              explanation: "The result might change tomorrow.",
              words: ["The", "result", "might", "change", "tomorrow."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: We / could / present / our / experiment / today.",
              skillTag: "grammar",
              topicTag,
              explanation: "We could present our experiment today.",
              words: ["We", "could", "present", "our", "experiment", "today."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-could-review",
          title: "Review: Could / might Mix",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "You _____ do research about the moon for next month.",
              skillTag: "grammar",
              topicTag,
              explanation: "Could do — could + base verb.",
              correct: "could do",
              wrong: ["could doing", "could to do"],
              distractorNotes: ["Could + -ing (×)", "Could + to (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Scientists _____ discover new planets with better telescopes.",
              skillTag: "grammar",
              topicTag,
              explanation: "Might discover — might + discover.",
              correct: "might discover",
              wrong: ["might discovers", "might to discover"],
              distractorNotes: ["Might + -s (×)", "Might + to (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "The robot might need more energy.",
              correct: "The robot might need more energy from the battery.",
              wrong: [
                "The robot might needs more energy from the battery.",
                "The robot might to need more energy from the battery.",
              ],
              distractorNotes: ["Might + -s (×)", "Might + to (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-science-mixed",
      title: "Lesson 3: Passive and Could/Might — Mixed",
      learningObjective:
        "Combine was built/was invented with could/might in science sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-mixed-learn",
          title: "Learn: Science Grammar Together",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "The robot was built by our class, and it _____ win a prize.",
              skillTag: "grammar",
              topicTag,
              explanation: "Might win — passive + might.",
              correct: "might",
              wrong: ["mights", "might to"],
              distractorNotes: ["Không chia might", "Might + to (×)"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The telescope was invented long ago, and we _____ use it tonight.",
              skillTag: "grammar",
              topicTag,
              explanation: "Could use — could + base verb.",
              correct: "could use",
              wrong: ["could to use", "could using"],
              distractorNotes: ["Could + to (×)", "Could + -ing (×)"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Our project was finished yesterday, so we _____ present the result today.",
              skillTag: "grammar",
              topicTag,
              explanation: "Could present — could + present.",
              correct: "could present",
              wrong: ["could presents", "could to present"],
              distractorNotes: ["Could + -s (×)", "Could + to (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The experiment was invented to show energy, and the result _____ change.",
              skillTag: "grammar",
              topicTag,
              explanation: "Might change — might + change.",
              correct: "might change",
              wrong: ["might changes", "might to change"],
              distractorNotes: ["Might + -s (×)", "Might + to (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-practice",
          title: "Practice: Mixed Science Grammar",
          instructions: "Fill in each gap with the correct form.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: The robot was [0] by our class. | It might [1] more electricity. | We could [2] the laboratory again.",
              skillTag: "grammar",
              topicTag,
              explanation: "built; need; use — passive + might/could + verb.",
              template:
                "The robot was [0] by our class. It might [1] more electricity. We could [2] the laboratory again.",
              correctAnswers: ["built", "need", "use"],
              acceptableAnswers: [
                ["built", "Built"],
                ["need", "Need"],
                ["use", "Use", "visit", "Visit"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-check",
          title: "Check: Mixed Grammar Challenge",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Was built + might need — cả hai cấu trúc đúng.",
              correct: "The robot was built last week, and it might need more electricity.",
              wrong: [
                "The robot built last week, and it might needs more electricity.",
                "The robot was build last week, and it might to need more electricity.",
              ],
              distractorNotes: ["Thiếu was + might -s", "Build + might to (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Was invented + could discover.",
              correct: "The microscope was invented long ago, and scientists could discover tiny cells.",
              wrong: [
                "The microscope was invent long ago, and scientists could to discover tiny cells.",
                "The microscope invented was long ago, and scientists could discovering tiny cells.",
              ],
              distractorNotes: ["Invent + could to (×)", "Word order + could -ing (×)"],
              difficultyRating: 3,
            }),
            buildMcq({
              questionText: "Our experiment was finished, so we _____ explain the result today.",
              skillTag: "grammar",
              topicTag,
              explanation: "Could explain — could + base verb.",
              correct: "could explain",
              wrong: ["could explains", "could to explain"],
              distractorNotes: ["Could + -s (×)", "Could + to (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-apply",
          title: "Apply: Build Mixed Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: The / invention / was / built / by / twelve / students.",
              skillTag: "grammar",
              topicTag,
              explanation: "The invention was built by twelve students.",
              words: ["The", "invention", "was", "built", "by", "twelve", "students."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: We / might / discover / something / new / with / the / microscope.",
              skillTag: "grammar",
              topicTag,
              explanation: "We might discover something new with the microscope.",
              words: ["We", "might", "discover", "something", "new", "with", "the", "microscope."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-review",
          title: "Review: Science Grammar Mix",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "The machine _____ in the laboratory last year.",
              skillTag: "grammar",
              topicTag,
              explanation: "Was built — passive voice.",
              correct: "was built",
              wrong: ["was build", "built was"],
              distractorNotes: ["Thiếu participle", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh _____ invent a better robot for the project.",
              skillTag: "grammar",
              topicTag,
              explanation: "Might invent — might + base verb.",
              correct: "might invent",
              wrong: ["might invents", "might to invent"],
              distractorNotes: ["Might + -s (×)", "Might + to (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Was invented + could test.",
              correct: "The experiment was invented to show energy, and we could test it again.",
              wrong: [
                "The experiment was invent to show energy, and we could to test it again.",
                "The experiment invented was to show energy, and we could testing it again.",
              ],
              distractorNotes: ["Invent + could to (×)", "Word order + could -ing (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
