/** Flyers U5 — listening lessons (3 × 5 exercises). */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptLabInterview,
  listeningScriptScienceFair,
  listeningAnswerKeys,
  topicTag,
}) {
  const labInterview = listeningScriptLabInterview;
  const scienceFair = listeningScriptScienceFair;
  const keysLab = listeningAnswerKeys.labInterview;
  const keysFair = listeningAnswerKeys.scienceFair;

  return [
    {
      slug: "listening-lab-interview",
      title: "Lesson 1: Interview in the Laboratory",
      learningObjective:
        "Track speakers in a short teacher interview about a science project.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-lab-learn",
          title: "Learn: Laboratory Interview",
          instructions: "Listen to Ms Nguyen, Minh and Linh. Answer the questions.",
          sortOrder: 0,
          script: labInterview,
          answerKey: keysLab,
          questions: [
            buildMcq({
              questionText: "Who says: \"We test batteries to find which gives more energy\"?",
              skillTag: "listening",
              topicTag,
              explanation: "Minh — câu nói của Minh trong phỏng vấn.",
              correct: "Minh",
              wrong: ["Linh", "Ms Nguyen"],
              distractorNotes: ["Linh talks about microscope", "Teacher asks questions"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What does Linh use in the laboratory?",
              skillTag: "listening",
              topicTag,
              explanation: "Microscope — I use the microscope to look at tiny parts.",
              correct: "A microscope",
              wrong: ["A telescope only", "A television screen"],
              distractorNotes: ["Telescope mentioned later by Linh", "Media U4"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-lab-practice",
          title: "Practice: Track Each Speaker",
          instructions: "Listen again. Who says each idea?",
          sortOrder: 1,
          script: labInterview,
          answerKey: keysLab,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "Who says the robot was built last week?",
              skillTag: "listening",
              topicTag,
              explanation: "Minh — Our robot was built last week.",
              correct: "Minh",
              wrong: ["Linh only", "Ms Nguyen"],
              distractorNotes: ["Linh talks about space after", "Teacher asks about robot"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who is curious about space and wants to discover planets?",
              skillTag: "listening",
              topicTag,
              explanation: "Linh — I'm curious about space... discover planets.",
              correct: "Linh",
              wrong: ["Minh", "The reporter"],
              distractorNotes: ["Minh talks batteries/robot", "Reporter in fair interview"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-lab-check",
          title: "Check: Lab Interview Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: labInterview,
          answerKey: keysLab,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What might change tomorrow according to Linh?",
              skillTag: "listening",
              topicTag,
              explanation: "The result — The result might change tomorrow.",
              correct: "The result",
              wrong: ["The television channel", "The national parade"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What research could they do for next month?",
              skillTag: "listening",
              topicTag,
              explanation: "About the moon — research about the moon for next month's fair.",
              correct: "Research about the moon",
              wrong: ["Research about comedy actors", "Research about fireworks"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What was their experiment invented to show?",
              skillTag: "listening",
              topicTag,
              explanation: "How energy works — show how energy works.",
              correct: "How energy works",
              wrong: ["How to watch television", "How to celebrate Tet"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-lab-apply",
          title: "Apply: Match Speaker to Statement",
          instructions: "Listen again. Match each speaker to what they say.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: labInterview },
          questions: [
            buildMatching({
              questionText: "Match each speaker to their statement.",
              skillTag: "listening",
              topicTag,
              explanation: "Minh: batteries/robot; Linh: microscope/space; Ms Nguyen: moon research.",
              pairs: [
                { left: "Minh", right: "tests batteries for energy" },
                { left: "Linh", right: "uses the microscope on tiny parts" },
                { left: "Ms Nguyen", right: "suggests research about the moon" },
                { left: "Linh", right: "is curious about discovering planets" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-lab-review",
          title: "Review: Lab Interview Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: labInterview,
          answerKey: keysLab,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Who asks Minh and Linh to tell about their science project?",
              skillTag: "listening",
              topicTag,
              explanation: "Ms Nguyen — giáo viên mở đầu phỏng vấn.",
              correct: "Ms Nguyen",
              wrong: ["Minh", "A school reporter"],
              distractorNotes: ["Student being interviewed", "Reporter in fair script"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What might the robot need according to Minh?",
              skillTag: "listening",
              topicTag,
              explanation: "More electricity — It might need more electricity.",
              correct: "More electricity",
              wrong: ["More comedy programmes", "More parade costumes"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-fair-interviews",
      title: "Lesson 2: Science Fair Interviews",
      learningObjective:
        "Track speakers in short reporter interviews at the science fair.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-fair-learn",
          title: "Learn: Science Fair Interview",
          instructions: "Listen to the reporter, Minh and Linh. Answer the questions.",
          sortOrder: 0,
          script: scienceFair,
          answerKey: keysFair,
          questions: [
            buildMcq({
              questionText: "Who asks: \"What is your project about?\"",
              skillTag: "listening",
              topicTag,
              explanation: "Reporter — phóng viên phỏng vấn Minh.",
              correct: "The reporter",
              wrong: ["Ms Nguyen", "Minh"],
              distractorNotes: ["Teacher in lab interview", "Student answers not asks"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What is the project about according to Minh?",
              skillTag: "listening",
              topicTag,
              explanation: "Electricity and energy — project about electricity and energy.",
              correct: "Electricity and energy",
              wrong: ["Cartoons and comedy", "Fireworks and parades"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-fair-practice",
          title: "Practice: Who Answers What?",
          instructions: "Listen again. Track each speaker.",
          sortOrder: 1,
          script: scienceFair,
          answerKey: keysFair,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "Who says the robot was built by twelve students?",
              skillTag: "listening",
              topicTag,
              explanation: "Linh — Yes, it was built by twelve students.",
              correct: "Linh",
              wrong: ["Minh", "The reporter"],
              distractorNotes: ["Minh talks about sun/energy", "Reporter asks questions"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who says they discovered the sun gives energy to the machine?",
              skillTag: "listening",
              topicTag,
              explanation: "Minh — We discovered that the sun gives energy.",
              correct: "Minh",
              wrong: ["Linh only", "Ms Nguyen"],
              distractorNotes: ["Linh talks about space poster", "Teacher not in this script"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-fair-check",
          title: "Check: Fair Interview Listening",
          instructions: "Listen to the full interview again.",
          sortOrder: 2,
          script: scienceFair,
          answerKey: keysFair,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What might win first prize?",
              skillTag: "listening",
              topicTag,
              explanation: "The invention — The invention might win first prize.",
              correct: "Their invention",
              wrong: ["The news programme", "The recycling project only"],
              distractorNotes: ["Media U4", "Eco U2 partial"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What did a scientist show them on a poster?",
              skillTag: "listening",
              topicTag,
              explanation: "A planet — scientist showed us a planet poster.",
              correct: "A planet",
              wrong: ["A comedy actor", "A traditional costume"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Could they use a telescope to learn about space?",
              skillTag: "listening",
              topicTag,
              explanation: "We might — Linh says We might!",
              correct: "Yes, they might",
              wrong: ["No, never", "Only Ms Nguyen can"],
              distractorNotes: ["Positive might answer", "Students are curious"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-fair-apply",
          title: "Apply: Order Interview Topics",
          instructions: "Put the interview topics in the order they are discussed.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          content: { script: scienceFair },
          questions: [
            buildMcq({
              questionText:
                "Correct order: (1) robot built by class (2) project topic (3) telescope and space",
              skillTag: "listening",
              topicTag,
              explanation: "Project topic → robot → discover sun → telescope/space.",
              correct: "2 → 1 → 3",
              wrong: ["1 → 3 → 2", "3 → 2 → 1"],
              distractorNotes: ["Project asked first", "Space is last"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-fair-review",
          title: "Review: Fair Interview Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: scienceFair,
          answerKey: keysFair,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Where did they do their experiment?",
              skillTag: "listening",
              topicTag,
              explanation: "In the laboratory — did an experiment in the laboratory.",
              correct: "In the laboratory",
              wrong: ["At the cinema", "At Hoan Kiem Lake"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How do Minh and Linh feel about space now?",
              skillTag: "listening",
              topicTag,
              explanation: "Curious — We're curious about space now.",
              correct: "Curious",
              wrong: ["Too bored", "Angry"],
              distractorNotes: ["Positive curiosity", "Not negative"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-science-review",
      title: "Lesson 3: Mixed Speaker Tracking",
      learningObjective:
        "Track speakers across short science interviews about projects and discoveries.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-mixed-learn",
          title: "Learn: Compare Two Interviews",
          instructions: "Listen to the laboratory interview. Who speaks most about the robot?",
          sortOrder: 0,
          script: labInterview,
          answerKey: keysLab,
          questions: [
            buildMcq({
              questionText: "In the lab interview, who talks most about the robot?",
              skillTag: "listening",
              topicTag,
              explanation: "Minh — robot built last week, might need electricity.",
              correct: "Minh",
              wrong: ["Linh only", "The reporter"],
              distractorNotes: ["Linh talks space after", "Reporter in fair only"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "In the lab interview, who suggests research about the moon?",
              skillTag: "listening",
              topicTag,
              explanation: "Ms Nguyen — You could do research about the moon.",
              correct: "Ms Nguyen",
              wrong: ["Minh", "Linh only"],
              distractorNotes: ["Students answer", "Linh wants planets not moon research idea"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-practice",
          title: "Practice: Fair Interview Speakers",
          instructions: "Listen to the science fair interview. Track speakers.",
          sortOrder: 1,
          script: scienceFair,
          answerKey: keysFair,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "Who answers the reporter's first question?",
              skillTag: "listening",
              topicTag,
              explanation: "Minh — Reporter asks Minh first, Minh answers about project.",
              correct: "Minh",
              wrong: ["Linh", "Ms Nguyen"],
              distractorNotes: ["Linh answers robot question", "Teacher not present"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who talks about being curious about space at the fair?",
              skillTag: "listening",
              topicTag,
              explanation: "Linh — We're curious about space now.",
              correct: "Linh",
              wrong: ["Minh only", "The reporter"],
              distractorNotes: ["Minh talks discovery/sun", "Reporter asks only"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-check",
          title: "Check: Mixed Interview Challenge",
          instructions: "Listen carefully to the fair interview.",
          sortOrder: 2,
          script: scienceFair,
          answerKey: keysFair,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What did they discover during research?",
              skillTag: "listening",
              topicTag,
              explanation: "The sun gives energy — discovered sun gives energy to machine.",
              correct: "The sun gives energy to their machine",
              wrong: ["Cartoons are too boring", "Fireworks lit the sky"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who asks about the robot being built by the class?",
              skillTag: "listening",
              topicTag,
              explanation: "Reporter — Linh, was the robot built by your class?",
              correct: "The reporter",
              wrong: ["Ms Nguyen", "Minh"],
              distractorNotes: ["Teacher in lab interview", "Minh is interviewed"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "In both interviews, what tool does Linh use or want for tiny or far things?",
              skillTag: "listening",
              topicTag,
              explanation: "Microscope in lab; telescope for planets — science tools.",
              correct: "Microscope and telescope",
              wrong: ["Television and radio", "Costume and parade"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-mixed-apply",
          title: "Apply: Match Interview to Speaker Line",
          instructions: "Match each line to the correct interview and speaker.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: labInterview },
          questions: [
            buildMatching({
              questionText: "Match statement to speaker (lab interview).",
              skillTag: "listening",
              topicTag,
              explanation: "Track speakers across lab interview lines.",
              pairs: [
                { left: "Ms Nguyen", right: "Tell me about your science project" },
                { left: "Minh", right: "Our robot was built last week" },
                { left: "Linh", right: "The result might change tomorrow" },
                { left: "Linh", right: "I want to discover planets with a telescope" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-review",
          title: "Review: Science Listening Mix",
          instructions: "Listen to the laboratory interview. Mixed review.",
          sortOrder: 4,
          script: labInterview,
          answerKey: keysLab,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "What do Minh and Linh test in the lab interview?",
              skillTag: "listening",
              topicTag,
              explanation: "Batteries — test batteries for energy.",
              correct: "Batteries",
              wrong: ["Television channels", "Parade costumes"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who says good scientists always check their work? (from reading — compare)",
              skillTag: "listening",
              topicTag,
              explanation: "Ms Nguyen in reading; in listening she asks about project — track teacher role.",
              correct: "Ms Nguyen (teacher guides the interview)",
              wrong: ["The reporter", "Grandma"],
              distractorNotes: ["Reporter in fair", "Not in unit"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
