/** Flyers U5 — reading lessons (3 × 5 exercises). */

export function readingLessons({
  buildMcq,
  buildGapFill,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMinhScience,
  topicTag,
}) {
  const passage = passageMinhScience;

  return [
    {
      slug: "reading-contextual-clues",
      title: "Lesson 1: Use Contextual Clues for Unknown Vocabulary",
      learningObjective:
        "Use nearby words in the text to guess the meaning of unfamiliar science words.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-clues-learn",
          title: "Learn: Guess from Context",
          instructions: "Read the passage. Use context to choose the best meaning.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText:
                'In "Linh looked through the microscope at tiny wires", what is a microscope?',
              skillTag: "reading",
              topicTag,
              explanation: "A tool to see very small things — nhìn dây nhỏ qua kính hiển vi.",
              correct: "A tool for looking at very small things",
              wrong: ["A room for experiments", "A planet in space"],
              distractorNotes: ["That is laboratory", "Space topic"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText:
                'In "test two small batteries... which battery gives more energy", what does test mean here?',
              skillTag: "reading",
              topicTag,
              explanation: "Try to see which works better — thử hai pin.",
              correct: "Try something to see which is better",
              wrong: ["Write a school exam", "Build a robot"],
              distractorNotes: ["School exam meaning", "Different action"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-clues-practice",
          title: "Practice: More Context Clues",
          instructions: "Read again. Use the sentences around each word.",
          sortOrder: 1,
          passage,
          difficulty: 0.25,
          questions: [
            buildMcq({
              questionText:
                'Near the window stood an old telescope. From context, a telescope is used to look at _____.',
              skillTag: "reading",
              topicTag,
              explanation: "Planets in space — poster of a planet, discover new worlds.",
              correct: "planets and stars far away",
              wrong: ["tiny cells in the laboratory", "batteries and electricity"],
              distractorNotes: ["Microscope context", "Battery test context"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText:
                'Ms Nguyen asked them to do research about electricity. Research here means _____.',
              skillTag: "reading",
              topicTag,
              explanation: "Careful study to find information — nghiên cứu về điện.",
              correct: "careful study to find information",
              wrong: ["a final exam mark", "a type of robot"],
              distractorNotes: ["School exam", "Machine"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-clues-check",
          title: "Check: Context Clue Challenge",
          instructions: "Read carefully. Use context to answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText:
                'Minh and Linh "were curious about which battery gives more energy". Curious means they _____.',
              skillTag: "reading",
              topicTag,
              explanation: "Wanted to know more — tò mò pin nào cho nhiều năng lượng.",
              correct: "wanted to know and learn more",
              wrong: ["were angry about the result", "finished the project"],
              distractorNotes: ["Negative emotion", "Project not finished yet"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText:
                'The robot "might need more electricity to move". From context, electricity is _____.',
              skillTag: "reading",
              topicTag,
              explanation: "Power for machines — điện giúp robot di chuyển.",
              correct: "power that makes machines work",
              wrong: ["a type of planet", "a science notebook"],
              distractorNotes: ["Space word", "Where results are written"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText:
                'They hope their project "was built well enough to win a prize". A project is _____.',
              skillTag: "reading",
              topicTag,
              explanation: "Planned school work — dự án khoa học.",
              correct: "planned work they finish over time",
              wrong: ["a tool for looking at the moon", "a person who does science"],
              distractorNotes: ["Telescope", "Scientist"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-clues-apply",
          title: "Apply: Complete from Context",
          instructions: "Fill in words you can guess from the passage.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                'Complete from the text: They test batteries for [0]. | Linh uses a [1] for tiny wires. | A [2] was used to discover new worlds.',
              skillTag: "reading",
              topicTag,
              explanation: "energy; microscope; telescope — từ ngữ cảnh trong bài.",
              template:
                "They test batteries for [0]. Linh uses a [1] for tiny wires. A [2] was used to discover new worlds.",
              correctAnswers: ["energy", "microscope", "telescope"],
              acceptableAnswers: [
                ["energy", "Energy"],
                ["microscope", "Microscope"],
                ["telescope", "Telescope"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-clues-review",
          title: "Review: Context Clues Mix",
          instructions: "Read the passage. Mixed review of contextual clues.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText:
                'From "Good scientists always check their work", a scientist is someone who _____.',
              skillTag: "reading",
              topicTag,
              explanation: "Does careful science work — nhà khoa học kiểm tra công việc.",
              correct: "does careful science work and checks results",
              wrong: ["only watches television", "sells tickets at a fair"],
              distractorNotes: ["Media U4", "Not in text"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText:
                'The "invention fair" is next Friday. From context, an invention is _____.',
              skillTag: "reading",
              topicTag,
              explanation: "Something new that was built or created — robot, machine.",
              correct: "something new that people built or created",
              wrong: ["a holiday parade", "a news programme"],
              distractorNotes: ["Festival U3", "Media U4"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-science-details",
      title: "Lesson 2: Science Project Details",
      learningObjective:
        "Find details about Minh and Linh's experiment and laboratory work.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-details-learn",
          title: "Learn: Who Does What?",
          instructions: "Read the passage. Who does each action?",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "Who looks through the microscope at tiny wires?",
              skillTag: "reading",
              topicTag,
              explanation: "Linh — Linh looked through the microscope.",
              correct: "Linh",
              wrong: ["Minh", "Ms Nguyen only"],
              distractorNotes: ["Minh writes results", "Teacher helps but Linh uses microscope"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Who writes each result in the notebook?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh — Minh wrote each result.",
              correct: "Minh",
              wrong: ["Linh", "The reporter"],
              distractorNotes: ["Linh uses microscope", "Not in reading passage"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-details-practice",
          title: "Practice: Experiment Details",
          instructions: "Read again. Choose the correct statement.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "What do Minh and Linh test in their experiment?",
              skillTag: "reading",
              topicTag,
              explanation: "Two small batteries — test two batteries for energy.",
              correct: "Two small batteries",
              wrong: ["Two telescopes", "Two comedy programmes"],
              distractorNotes: ["Tool not tested", "Media U4"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What does Ms Nguyen's research topic help them with?",
              skillTag: "reading",
              topicTag,
              explanation: "Electricity and energy — research about electricity and energy.",
              correct: "Electricity and energy",
              wrong: ["Fireworks and parades", "Television channels"],
              distractorNotes: ["Festival U3", "Media U4"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-details-check",
          title: "Check: Project Details",
          instructions: "Find the answers in the text.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "What does Minh say about the first test?",
              skillTag: "reading",
              topicTag,
              explanation: "The first test was good — câu nói của Minh.",
              correct: "The first test was good",
              wrong: ["The first test was too boring", "The first test was on a ship"],
              distractorNotes: ["Negative opinion", "Media scene U4"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What might be better tomorrow?",
              skillTag: "reading",
              topicTag,
              explanation: "The second result — second result might be better.",
              correct: "The second result",
              wrong: ["The first battery only", "The national parade"],
              distractorNotes: ["First test already good", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When is the class invention fair?",
              skillTag: "reading",
              topicTag,
              explanation: "Next Friday — invention fair is next Friday.",
              correct: "Next Friday",
              wrong: ["Last week", "Every evening"],
              distractorNotes: ["Robot built last week", "TV time U4"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-details-apply",
          title: "Apply: Match Person to Action",
          instructions: "Match each person to what they do in the text.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each person to their science action.",
              skillTag: "reading",
              topicTag,
              explanation: "Minh: writes results; Linh: microscope; Ms Nguyen: helps research.",
              pairs: [
                { left: "Minh", right: "writes each result in the notebook" },
                { left: "Linh", right: "looks through the microscope at tiny wires" },
                { left: "Ms Nguyen", right: "helps with research about electricity" },
                { left: "Minh and Linh", right: "test two small batteries" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-details-review",
          title: "Review: Science Details Mix",
          instructions: "Read and answer about the science project.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Where do Minh and Linh work on their project?",
              skillTag: "reading",
              topicTag,
              explanation: "School laboratory — first paragraph.",
              correct: "In the school laboratory",
              wrong: ["At the cinema", "At Hoan Kiem Lake"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What does Minh point at on the poster?",
              skillTag: "reading",
              topicTag,
              explanation: "A planet in space — poster of a planet.",
              correct: "A planet in space",
              wrong: ["A comedy actor", "A recycling bin"],
              distractorNotes: ["Media U4", "Eco U2"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-science-inference",
      title: "Lesson 3: Infer from Science Texts",
      learningObjective:
        "Use context and details to infer meaning and outcomes in science reading.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-infer-learn",
          title: "Learn: Infer Unknown Words",
          instructions: "Read and infer meanings from context.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText:
                'If something "was built well enough to win a prize", it was made _____.',
              skillTag: "reading",
              topicTag,
              explanation: "Well / carefully — đủ tốt để thắng giải.",
              correct: "carefully and to a good standard",
              wrong: ["quickly without checking", "only for television"],
              distractorNotes: ["Scientists check work", "Media U4"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText:
                'When Ms Nguyen says "You could discover something useful", she means they _____.',
              skillTag: "reading",
              topicTag,
              explanation: "Might find helpful information — có thể tìm điều hữu ích.",
              correct: "might find helpful new information",
              wrong: ["must fail the experiment", "cannot use the laboratory"],
              distractorNotes: ["Positive encouragement", "Opposite of could"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-infer-practice",
          title: "Practice: Infer Outcomes",
          instructions: "Read again. What can you infer?",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Why might the robot need more electricity?",
              skillTag: "reading",
              topicTag,
              explanation: "To move — it might need more electricity to move.",
              correct: "To move across the floor",
              wrong: ["To watch a comedy on television", "To celebrate Tet"],
              distractorNotes: ["Media U4", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What can you infer about Minh's interest in space?",
              skillTag: "reading",
              topicTag,
              explanation: "He is curious — points at planet poster, talks about telescope.",
              correct: "He is interested and curious about planets",
              wrong: ["He thinks space is too boring", "He never uses science tools"],
              distractorNotes: ["Opposite of text", "Uses microscope and talks telescope"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-infer-check",
          title: "Check: Inference Challenge",
          instructions: "Read carefully and infer the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "What will Minh and Linh probably do at the fair?",
              skillTag: "reading",
              topicTag,
              explanation: "Present experiment — could present their experiment.",
              correct: "Present their experiment and explain the robot",
              wrong: ["Watch fireworks at the lake", "Change television channels"],
              distractorNotes: ["Festival U3", "Media U4"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText:
                'From "Our robot was built last week", who built the robot?',
              skillTag: "reading",
              topicTag,
              explanation: "Their whole class — robot was built by whole class (also in listening).",
              correct: "Their whole class",
              wrong: ["Only Ms Nguyen", "A famous actor"],
              distractorNotes: ["Teacher helps not builds alone", "Media U4"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What does the word result refer to in the passage?",
              skillTag: "reading",
              topicTag,
              explanation: "What they find from testing batteries — written in notebook.",
              correct: "What they find out from testing the batteries",
              wrong: ["The name of a planet", "A type of costume"],
              distractorNotes: ["Space poster separate", "Festival U3"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-infer-apply",
          title: "Apply: Match Clue to Meaning",
          instructions: "Match each context clue to the word it helps you understand.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match context clue to vocabulary meaning.",
              skillTag: "reading",
              topicTag,
              explanation: "Context clues → energy, invention, discover, laboratory.",
              pairs: [
                { left: "gives more energy to their machine", right: "energy / test" },
                { left: "built last week by their whole class", right: "robot / invention" },
                { left: "discover new worlds with it", right: "telescope / discover" },
                { left: "school laboratory after lunch", right: "experiment / research" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-infer-review",
          title: "Review: Science Reading Mix",
          instructions: "Read the passage. Mixed review of clues and details.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Which word from context means 'try two batteries to compare them'?",
              skillTag: "reading",
              topicTag,
              explanation: "Test — had to test two small batteries.",
              correct: "test",
              wrong: ["invent", "celebrate"],
              distractorNotes: ["Create new thing", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "At the end, both friends hope their project _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Was built well enough to win — hy vọng thắng giải.",
              correct: "was built well enough to win a prize",
              wrong: ["was too boring for the audience", "was recycled at the lake"],
              distractorNotes: ["Media opinion", "Eco U2"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
