/** Flyers U5 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-science-lab",
      title: "Lesson 1: Science and the Laboratory",
      learningObjective:
        "Recognise and use science, scientist, laboratory, experiment, research, test and result.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-lab-learn",
          title: "Learn: Science and Lab Words",
          instructions: "Read each clue. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh loves _____ lessons at school in Hanoi.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Science (khoa học) — môn khoa học ở trường.",
              correct: "science",
              wrong: ["scientist", "space"],
              distractorNotes: ["Person not subject", "Outer space topic"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The _____ showed us how to use a microscope.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Scientist (nhà khoa học) — người hướng dẫn.",
              correct: "scientist",
              wrong: ["laboratory", "result"],
              distractorNotes: ["Place not person", "Outcome not person"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "We worked in the school _____ after lunch.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Laboratory (phòng thí nghiệm) — nơi làm thí nghiệm.",
              correct: "laboratory",
              wrong: ["planet", "robot"],
              distractorNotes: ["In space", "Machine not room"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Our _____ tested how plants need light to grow.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Experiment (thí nghiệm) — bài thử nghiệm.",
              correct: "experiment",
              wrong: ["electricity", "curious"],
              distractorNotes: ["Power type", "Adjective"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-lab-practice",
          title: "Practice: Match Lab Words",
          instructions: "Match each word to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match science and laboratory words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mỗi từ chỉ một khái niệm khoa học cụ thể.",
              pairs: [
                { left: "research", right: "careful study to find new information" },
                { left: "test", right: "try something to see if it works" },
                { left: "result", right: "what you find out after a test or experiment" },
                { left: "laboratory", right: "a special room where scientists do experiments" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-lab-check",
          title: "Check: Lab Vocabulary Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "The teacher asked us to do _____ about electricity.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Research (nghiên cứu) — nghiên cứu về điện.",
              correct: "research",
              wrong: ["robot", "planet"],
              distractorNotes: ["Machine", "In space"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh and Linh will _____ two different batteries.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Test (thử nghiệm) — thử hai loại pin.",
              correct: "test",
              wrong: ["discover", "invent"],
              distractorNotes: ["Find something new", "Create something new"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We wrote the _____ in our science notebook.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Result (kết quả) — ghi kết quả vào sổ.",
              correct: "result",
              wrong: ["machine", "telescope"],
              distractorNotes: ["Device", "Tool for space"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-lab-apply",
          title: "Apply: Complete Lab Sentences",
          instructions: "Fill in each gap with the correct word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh loves [0] at school. | We work in the [1]. | We wrote the [2] in our notebook.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "science; laboratory; result — từ phòng lab cơ bản.",
              template:
                "Minh loves [0] at school. We work in the [1]. We wrote the [2] in our notebook.",
              correctAnswers: ["science", "laboratory", "result"],
              acceptableAnswers: [
                ["science", "Science"],
                ["laboratory", "Laboratory", "lab", "Lab"],
                ["result", "Result", "results", "Results"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-lab-review",
          title: "Review: Science and Lab Mix",
          instructions: "Mixed review from this lesson. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which word means 'a special room for experiments'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Laboratory (phòng thí nghiệm) — phòng làm thí nghiệm.",
              correct: "laboratory",
              wrong: ["scientist", "result"],
              distractorNotes: ["Person", "Outcome"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Our _____ tested how plants need light.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Experiment (thí nghiệm) — bài thí nghiệm về cây.",
              correct: "experiment",
              wrong: ["energy", "space"],
              distractorNotes: ["Power", "Outer area"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "A _____ studies science and does research.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Scientist (nhà khoa học) — người nghiên cứu khoa học.",
              correct: "scientist",
              wrong: ["machine", "project only"],
              distractorNotes: ["Device", "Work not person"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-discovery-invention",
      title: "Lesson 2: Discovery and Invention",
      learningObjective:
        "Use discover, invent, invention, microscope, telescope, machine and robot.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-discovery-learn",
          title: "Learn: Discovery and Invention Words",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Scientists _____ new planets with a telescope.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Discover (khám phá) — khám phá hành tinh mới.",
              correct: "discover",
              wrong: ["invent", "test"],
              distractorNotes: ["Create new thing", "Try something"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "People _____ machines to make work easier.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Invent (phát minh) — phát minh máy móc.",
              correct: "invent",
              wrong: ["discover", "research"],
              distractorNotes: ["Find existing thing", "Study noun/verb mix"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The robot was an important _____ for the factory.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Invention (phát minh) — danh từ chỉ sáng chế.",
              correct: "invention",
              wrong: ["experiment", "curious"],
              distractorNotes: ["Test activity", "Adjective"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh looked at tiny cells through the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Microscope (kính hiển vi) — nhìn tế bào nhỏ.",
              correct: "microscope",
              wrong: ["telescope", "machine"],
              distractorNotes: ["Looks at far objects", "General device"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-discovery-practice",
          title: "Practice: Match Discovery Words",
          instructions: "Match each word to the correct meaning or situation.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match discovery and invention words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ghép từ khám phá/phát minh với nghĩa phù hợp.",
              pairs: [
                { left: "telescope", right: "a tool for looking at planets and stars in space" },
                { left: "machine", right: "equipment that helps people do work" },
                { left: "robot", right: "a machine that can move and do tasks" },
                { left: "discover", right: "find something that was not known before" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-discovery-check",
          title: "Check: Discovery Vocabulary Quiz",
          instructions: "Choose the best answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh used a _____ to look at the moon.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Telescope (kính thiên văn) — nhìn mặt trăng.",
              correct: "telescope",
              wrong: ["microscope", "laboratory"],
              distractorNotes: ["For tiny things", "Room not tool"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The old _____ in the laboratory still works well.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Machine (máy móc) — máy trong phòng lab.",
              correct: "machine",
              wrong: ["result", "science"],
              distractorNotes: ["Outcome", "Subject"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Our class built a small _____ for the science project.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Robot (robot) — làm robot cho dự án.",
              correct: "robot",
              wrong: ["planet", "research"],
              distractorNotes: ["In space", "Study activity"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-discovery-apply",
          title: "Apply: Discovery Sentences",
          instructions: "Complete the sentences about discovery and invention.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Scientists [0] new planets. | People [1] machines. | Linh used a [2] to look at cells.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "discover; invent; microscope — động từ và dụng cụ.",
              template:
                "Scientists [0] new planets. People [1] machines. Linh used a [2] to look at cells.",
              correctAnswers: ["discover", "invent", "microscope"],
              acceptableAnswers: [
                ["discover", "Discover"],
                ["invent", "Invent"],
                ["microscope", "Microscope"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-discovery-review",
          title: "Review: Discovery and Invention Mix",
          instructions: "Mixed review. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which tool helps you see planets in space?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Telescope (kính thiên văn) — nhìn hành tinh.",
              correct: "telescope",
              wrong: ["microscope", "experiment"],
              distractorNotes: ["For tiny objects", "Test activity"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The robot was an important _____ for the project.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Invention (phát minh) — sáng chế quan trọng.",
              correct: "invention",
              wrong: ["discover", "test"],
              distractorNotes: ["Verb", "Try verb"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word means 'find something new'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Discover (khám phá) — tìm ra điều mới.",
              correct: "discover",
              wrong: ["invent", "result"],
              distractorNotes: ["Create new thing", "Outcome"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-energy-space",
      title: "Lesson 3: Energy, Space and Review",
      learningObjective:
        "Use electricity, energy, space, planet, project, curious and review all twenty words.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-energy-learn",
          title: "Learn: Energy and Space Words",
          instructions: "Choose the word that best completes each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "The experiment needs _____ from a battery.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Electricity (điện) — thí nghiệm cần điện từ pin.",
              correct: "electricity",
              wrong: ["planet", "curious"],
              distractorNotes: ["In space", "Adjective"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The sun gives _____ to plants and machines.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Energy (năng lượng) — mặt trời cung cấp năng lượng.",
              correct: "energy",
              wrong: ["research", "microscope"],
              distractorNotes: ["Study", "Tool"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh is curious about planets in _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Space (không gian) — hành tinh trong vũ trụ.",
              correct: "space",
              wrong: ["laboratory", "result"],
              distractorNotes: ["Room at school", "Test outcome"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Earth is the _____ where we live.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Planet (hành tinh) — Trái Đất là hành tinh.",
              correct: "planet",
              wrong: ["robot", "test"],
              distractorNotes: ["Machine", "Try verb"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-energy-practice",
          title: "Practice: Match Energy and Space Words",
          instructions: "Match each word or phrase to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match energy, space and project words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Project, curious và từ năng lượng/vũ trụ.",
              pairs: [
                { left: "project", right: "a piece of work you plan and finish over time" },
                { left: "curious", right: "wanting to know or learn more about something" },
                { left: "electricity", right: "power that makes lights and machines work" },
                { left: "energy", right: "power from the sun, food or batteries" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-energy-check",
          title: "Check: Energy and Space Challenge",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Our science _____ is about energy and electricity.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Project (dự án) — dự án khoa học về năng lượng.",
              correct: "project",
              wrong: ["invention", "discover"],
              distractorNotes: ["Created thing", "Verb"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh is _____ about how the robot was built.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Curious (tò mò) — muốn biết cách robot được làm.",
              correct: "curious",
              wrong: ["electricity", "laboratory"],
              distractorNotes: ["Power noun", "Place"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word means 'power that makes machines work'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Electricity (điện) — điện làm máy hoạt động.",
              correct: "electricity",
              wrong: ["planet", "scientist"],
              distractorNotes: ["In space", "Person"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-energy-apply",
          title: "Apply: Energy and Space Sentences",
          instructions: "Fill in with energy and space words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: The sun gives [0] to plants. | Earth is a [1]. | Our science [2] is about electricity.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "energy; planet; project — năng lượng, hành tinh, dự án.",
              template:
                "The sun gives [0] to plants. Earth is a [1]. Our science [2] is about electricity.",
              correctAnswers: ["energy", "planet", "project"],
              acceptableAnswers: [
                ["energy", "Energy"],
                ["planet", "Planet"],
                ["project", "Project"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-energy-review",
          title: "Review: Unit Vocabulary Mix",
          instructions: "Choose the best word from the whole unit (all 20 words).",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "We worked in the school _____ after lunch.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Laboratory (phòng thí nghiệm) — làm việc sau bữa trưa.",
              correct: "laboratory",
              wrong: ["space", "planet"],
              distractorNotes: ["Outer area", "In space"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Scientists _____ new planets with a telescope.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Discover (khám phá) — khám phá hành tinh.",
              correct: "discover",
              wrong: ["invent", "test"],
              distractorNotes: ["Create new", "Try only"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The experiment needs _____ from a battery.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Electricity (điện) — cần điện từ pin.",
              correct: "electricity",
              wrong: ["curious", "result"],
              distractorNotes: ["Adjective", "Outcome"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh looked at tiny cells through the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Microscope (kính hiển vi) — quan sát tế bào.",
              correct: "microscope",
              wrong: ["telescope", "machine"],
              distractorNotes: ["For stars", "General device"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Our class built a small _____ for the project.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Robot (robot) — làm robot cho dự án.",
              correct: "robot",
              wrong: ["research", "science only"],
              distractorNotes: ["Study activity", "Subject not object"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We wrote the _____ in our science notebook.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Result (kết quả) — ghi kết quả thí nghiệm.",
              correct: "result",
              wrong: ["invention", "energy"],
              distractorNotes: ["Created thing", "Power type"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
