/** Movers U4 — listening lessons (3 × 5 exercises). */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptAfterSchool,
  listeningScriptCinemaPlans,
  listeningAnswerKeys,
  topicTag,
}) {
  const afterSchool = listeningScriptAfterSchool;
  const cinemaPlans = listeningScriptCinemaPlans;
  const keysAfterSchool = listeningAnswerKeys.afterSchool;
  const keysCinema = listeningAnswerKeys.cinemaPlans;

  return [
    {
      slug: "listening-after-school",
      title: "Lesson 1: After School Now",
      learningObjective:
        "Listen to an after-school dialogue and understand what is happening now.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-school-learn",
          title: "Learn: After School at Home",
          instructions: "Listen to Minh, Linh and Mum. Answer the questions.",
          sortOrder: 0,
          script: afterSchool,
          answerKey: keysAfterSchool,
          questions: [
            buildMcq({
              questionText: "What is Minh doing?",
              skillTag: "listening",
              topicTag,
              explanation: "I am reading a comic book — Minh nói với mẹ.",
              correct: "Reading a comic book",
              wrong: ["Drawing a cat", "Playing football now"],
              distractorNotes: ["Linh đang vẽ", "Sau này mới chơi"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What is Linh doing?",
              skillTag: "listening",
              topicTag,
              explanation: "I am drawing a cat — Linh trả lời.",
              correct: "Drawing a cat",
              wrong: ["Reading a comic", "Collecting stamps"],
              distractorNotes: ["Minh đọc comic", "Minh sưu tập tem"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-practice",
          title: "Practice: More After-School Details",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: afterSchool,
          answerKey: keysAfterSchool,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "What is Minh's hobby?",
              skillTag: "listening",
              topicTag,
              explanation: "Collecting stamps — mẹ hỏi và Minh xác nhận.",
              correct: "Collecting stamps",
              wrong: ["Dancing only", "Going to the cinema"],
              distractorNotes: ["Linh thích nhảy", "Cuối tuần"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What is Minh looking at now?",
              skillTag: "listening",
              topicTag,
              explanation: "A new stamp from Japan — đang xem tem.",
              correct: "A new stamp from Japan",
              wrong: ["A comic from Japan", "A concert ticket"],
              distractorNotes: ["Đọc comic nhưng xem tem", "Chủ nhật"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-check",
          title: "Check: After School Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: afterSchool,
          answerKey: keysAfterSchool,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What can they do after they finish?",
              skillTag: "listening",
              topicTag,
              explanation: "Play football outside — mẹ nói.",
              correct: "Play football outside",
              wrong: ["Go to the cinema now", "Go swimming in the kitchen"],
              distractorNotes: ["Thứ Bảy", "Không hợp lý"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh likes dancing, but right now she is _____",
              skillTag: "listening",
              topicTag,
              explanation: "Drawing — bây giờ đang vẽ.",
              correct: "drawing",
              wrong: ["dancing", "reading comics"],
              distractorNotes: ["Thích nhưng không làm bây giờ", "Minh đọc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What is the main idea of this dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Children tell Mum what they are doing after school.",
              correct: "What the children are doing after school",
              wrong: ["Plans for a holiday trip", "Yesterday's weather"],
              distractorNotes: ["Dialogue khác", "Unit 3"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-school-apply",
          title: "Apply: Match Person to Activity",
          instructions: "Listen again. Match each person to what they do.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: afterSchool },
          questions: [
            buildMatching({
              questionText: "Match each person to their activity.",
              skillTag: "listening",
              topicTag,
              explanation: "Minh reading; Linh drawing; both like football.",
              pairs: [
                { left: "Minh now", right: "reading a comic" },
                { left: "Linh now", right: "drawing a cat" },
                { left: "Minh's hobby", right: "collecting stamps" },
                { left: "Both like", right: "playing football" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-review",
          title: "Review: After School Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: afterSchool,
          answerKey: keysAfterSchool,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Mum asks: What are you _____?",
              skillTag: "listening",
              topicTag,
              explanation: "What are you doing? — câu hỏi mở đầu.",
              correct: "doing",
              wrong: ["liking", "collecting"],
              distractorNotes: ["Sở thích", "Hoạt động cụ thể"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh says: We like _____ football after school.",
              skillTag: "listening",
              topicTag,
              explanation: "Playing — like + playing football.",
              correct: "playing",
              wrong: ["reading", "drawing"],
              distractorNotes: ["Đọc sách", "Vẽ tranh"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-cinema-plans",
      title: "Lesson 2: Cinema and Concert Plans",
      learningObjective:
        "Listen for main ideas about cinema and concert weekend plans.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-cinema-learn",
          title: "Learn: Weekend Plans",
          instructions: "Listen to the family talking about the weekend.",
          sortOrder: 0,
          script: cinemaPlans,
          answerKey: keysCinema,
          questions: [
            buildMcq({
              questionText: "Where are they going on Saturday?",
              skillTag: "listening",
              topicTag,
              explanation: "To the cinema — Minh hỏi và mẹ đồng ý.",
              correct: "The cinema",
              wrong: ["The concert", "The supermarket"],
              distractorNotes: ["Chủ nhật", "Unit khác"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What is on Sunday?",
              skillTag: "listening",
              topicTag,
              explanation: "A concert in the park — mẹ nói.",
              correct: "A concert in the park",
              wrong: ["A cinema trip", "A football match only"],
              distractorNotes: ["Thứ Bảy", "Có thể chơi nhưng kế hoạch chính là concert"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cinema-practice",
          title: "Practice: Plan Details",
          instructions: "Listen again. Focus on details.",
          sortOrder: 1,
          script: cinemaPlans,
          answerKey: keysCinema,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "What kind of film do they want?",
              skillTag: "listening",
              topicTag,
              explanation: "An adventure film — Linh thích comic nên muốn phiêu lưu.",
              correct: "An adventure film",
              wrong: ["A concert film", "A stamp collection show"],
              distractorNotes: ["Concert — Chủ nhật", "Không trong bài"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Why is the concert perfect for Linh?",
              skillTag: "listening",
              topicTag,
              explanation: "She likes dancing — a concert is perfect.",
              correct: "She likes dancing",
              wrong: ["She likes collecting stamps", "She is reading now"],
              distractorNotes: ["Minh sưu tập", "Bây giờ"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cinema-check",
          title: "Check: Cinema Plans Listening",
          instructions: "Listen to the full conversation again.",
          sortOrder: 2,
          script: cinemaPlans,
          answerKey: keysCinema,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What is the main idea of this dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Weekend plans: cinema Saturday, concert Sunday.",
              correct: "Weekend cinema and concert plans",
              wrong: ["What they are doing right now", "Shopping for food"],
              distractorNotes: ["Dialogue 1", "Unit 6"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh likes swimming, but he thinks the concert _____",
              skillTag: "listening",
              topicTag,
              explanation: "Sounds fun — Minh nói concert sounds fun.",
              correct: "sounds fun",
              wrong: ["is boring", "is at the cinema"],
              distractorNotes: ["Ngược nghĩa", "Concert ở công viên"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum agrees: cinema on Saturday, concert on _____",
              skillTag: "listening",
              topicTag,
              explanation: "Sunday — cuối hội thoại.",
              correct: "Sunday",
              wrong: ["Monday", "Saturday again"],
              distractorNotes: ["Không nói", "Đã có cinema"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-cinema-apply",
          title: "Apply: Match Day to Plan",
          instructions: "Listen again. Match each day to the plan.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: cinemaPlans },
          questions: [
            buildMatching({
              questionText: "Match each day to the plan.",
              skillTag: "listening",
              topicTag,
              explanation: "Saturday cinema; Sunday concert; after cinema football maybe.",
              pairs: [
                { left: "Saturday", right: "go to the cinema" },
                { left: "Sunday", right: "concert in the park" },
                { left: "Linh wants", right: "an adventure film" },
                { left: "Minh also likes", right: "swimming in summer" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cinema-review",
          title: "Review: Cinema Plans Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: cinemaPlans,
          answerKey: keysCinema,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Linh likes reading _____, so she wants an adventure film.",
              skillTag: "listening",
              topicTag,
              explanation: "Comics — I like reading comics.",
              correct: "comics",
              wrong: ["stamps", "football rules"],
              distractorNotes: ["Minh sưu tập", "Không liên quan"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "After the cinema, can they play football?",
              skillTag: "listening",
              topicTag,
              explanation: "Minh asks — After the cinema, can we play football?",
              correct: "Minh asks about it",
              wrong: ["Mum says no", "They play now"],
              distractorNotes: ["Không từ chối", "Cuối tuần"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-hobbies-review",
      title: "Lesson 3: Mixed Main Idea Listening",
      learningObjective:
        "Understand the main idea across two short hobby dialogues.",
      estimatedMinutes: 22,
      exercises: [
        buildListeningExercise({
          slug: "listening-mixed-learn",
          title: "Learn: After School Reminder",
          instructions: "Listen to the after-school dialogue again.",
          sortOrder: 0,
          script: afterSchool,
          answerKey: keysAfterSchool,
          questions: [
            buildMcq({
              questionText: "Who asks: What are you doing?",
              skillTag: "listening",
              topicTag,
              explanation: "Mum — mở đầu dialogue.",
              correct: "Mum",
              wrong: ["Linh only", "A teacher"],
              distractorNotes: ["Linh trả lời", "Không có"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Main idea of dialogue 1:",
              skillTag: "listening",
              topicTag,
              explanation: "After-school activities happening now.",
              correct: "What children are doing now",
              wrong: ["Weekend cinema plans", "Weather yesterday"],
              distractorNotes: ["Dialogue 2", "Unit 3"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-practice",
          title: "Practice: Weekend Plans Reminder",
          instructions: "Listen to the cinema plans dialogue again.",
          sortOrder: 1,
          script: cinemaPlans,
          answerKey: keysCinema,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Main idea of dialogue 2:",
              skillTag: "listening",
              topicTag,
              explanation: "Plans for cinema and concert at the weekend.",
              correct: "Weekend cinema and concert plans",
              wrong: ["Drawing and reading now", "Collecting stamps at school"],
              distractorNotes: ["Dialogue 1", "Không phải ý chính"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which place is in BOTH dialogues?",
              skillTag: "listening",
              topicTag,
              explanation: "Home — after school at home; kitchen table for plans.",
              correct: "Home",
              wrong: ["The cinema only", "The beach"],
              distractorNotes: ["Chỉ dialogue 2", "Không có"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-check",
          title: "Check: Mixed Main Idea Listening",
          instructions: "Listen to after-school dialogue. Harder questions.",
          sortOrder: 2,
          script: afterSchool,
          answerKey: keysAfterSchool,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which hobby word is in BOTH dialogues?",
              skillTag: "listening",
              topicTag,
              explanation: "Dancing — Linh likes dancing in both (school / concert).",
              correct: "dancing",
              wrong: ["snow", "supermarket"],
              distractorNotes: ["Không có", "Unit khác"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which activity is ONLY in dialogue 1?",
              skillTag: "listening",
              topicTag,
              explanation: "Drawing a cat — Linh is drawing now.",
              correct: "Drawing a cat",
              wrong: ["Going to the cinema", "A concert in the park"],
              distractorNotes: ["Dialogue 2", "Dialogue 2"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-mixed-apply",
          title: "Apply: Match Dialogue to Main Idea",
          instructions: "Match each main idea to the correct dialogue.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: cinemaPlans },
          questions: [
            buildMatching({
              questionText: "Match main ideas to After School or Weekend Plans.",
              skillTag: "listening",
              topicTag,
              explanation: "Now activities vs weekend cinema/concert.",
              pairs: [
                { left: "Reading a comic now", right: "After School dialogue" },
                { left: "Cinema on Saturday", right: "Weekend Plans dialogue" },
                { left: "Collecting stamps hobby", right: "After School dialogue" },
                { left: "Concert on Sunday", right: "Weekend Plans dialogue" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-mixed-review",
          title: "Review: Both Dialogues Mix",
          instructions: "Listen to weekend plans. Final review.",
          sortOrder: 4,
          script: cinemaPlans,
          answerKey: keysCinema,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which sentence summarises BOTH dialogues best?",
              skillTag: "listening",
              topicTag,
              explanation: "Hobbies now and fun plans for the weekend.",
              correct: "Minh and Linh enjoy hobbies and have cinema and concert plans.",
              wrong: ["It was rainy yesterday.", "Minh works in an office."],
              distractorNotes: ["Unit 3", "Unit 7"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They like _____ football after school (dialogue 1).",
              skillTag: "listening",
              topicTag,
              explanation: "Playing — We like playing football.",
              correct: "playing",
              wrong: ["reading", "cinema"],
              distractorNotes: ["Đọc sách", "Cuối tuần"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
