/** Movers U4 — reading lessons (3 × 5 exercises). */

export function readingLessons({
  buildMcq,
  buildGapFill,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMinhHobbies,
  topicTag,
}) {
  const passage = passageMinhHobbies;

  return [
    {
      slug: "reading-choose-response",
      title: "Lesson 1: Choose the Best Response",
      learningObjective:
        "Read short conversations and choose the best response.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-response-learn",
          title: "Learn: Read the Conversation",
          instructions: "Read the passage. Choose the best response.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: 'Minh asks: "What are you doing?" Best response from Linh:',
              skillTag: "reading",
              topicTag,
              explanation: "I am drawing a cat — Linh trả lời trong bài.",
              correct: "I am drawing a cat.",
              wrong: ["I like swimming in summer.", "We are going to the cinema."],
              distractorNotes: ["Sở thích — không trả lời bây giờ", "Kế hoạch cuối tuần"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: 'Mum could ask: "Is collecting stamps your hobby?" Best answer from Minh:',
              skillTag: "reading",
              topicTag,
              explanation: "Yes! Collecting stamps is my favourite hobby.",
              correct: "Yes! Collecting stamps is my favourite hobby.",
              wrong: ["No, I am drawing a cat.", "I am going to the concert now."],
              distractorNotes: ["Linh đang vẽ", "Concert — Chủ nhật"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-response-practice",
          title: "Practice: More Conversation Responses",
          instructions: "Read again. Choose the best reply.",
          sortOrder: 1,
          passage,
          difficulty: 0.25,
          questions: [
            buildMcq({
              questionText: 'Friend asks: "Do you like dancing?" Linh would say:',
              skillTag: "reading",
              topicTag,
              explanation: "Yes, I like dancing at school — trong bài đọc.",
              correct: "Yes, I like dancing at school.",
              wrong: ["No, I am reading a comic.", "I collect stamps from Japan."],
              distractorNotes: ["Minh đọc comic", "Minh sưu tập tem"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: 'Minh asks about Saturday. Mum would say:',
              skillTag: "reading",
              topicTag,
              explanation: "We are going to the cinema on Saturday.",
              correct: "We are going to the cinema on Saturday.",
              wrong: ["I am drawing a cat now.", "I like swimming only."],
              distractorNotes: ["Linh bây giờ", "Chỉ một sở thích"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-response-check",
          title: "Check: Choose Response Challenge",
          instructions: "Read carefully. Pick the best response.",
          sortOrder: 2,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: 'Linh asks: "What is your favourite hobby?" Best answer from Minh:',
              skillTag: "reading",
              topicTag,
              explanation: "Collecting stamps — sở thích yêu thích của Minh.",
              correct: "Collecting stamps is my favourite hobby.",
              wrong: ["I am reading a comic now.", "There is a concert on Sunday."],
              distractorNotes: ["Đang làm bây giờ", "Kế hoạch — không phải hobby"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: 'Mum says there is a concert on Sunday. Best reply:',
              skillTag: "reading",
              topicTag,
              explanation: "Great! I like dancing, so a concert is fun.",
              wrong: ["I am drawing a cat.", "I am reading now."],
              correct: "Great! Linh likes dancing, so a concert will be fun!",
              distractorNotes: ["Không liên quan", "Không liên quan"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: 'Someone asks: "Are you playing football now?" Best answer:',
              skillTag: "reading",
              topicTag,
              explanation: "No, I am reading a comic. We can play football later.",
              correct: "No, I am reading a comic. We can play football later.",
              wrong: ["Yes, I am reading a comic.", "I like collecting stamps."],
              distractorNotes: ["Đang đọc không chơi bóng", "Không trả lời câu hỏi"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-response-apply",
          title: "Apply: Complete Conversation Gaps",
          instructions: "Fill in the best response words from the passage.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                'Complete: "What are you doing?" "I am [0] a cat." | "My hobby is [1] stamps." | "On Saturday we go to the [2]."',
              skillTag: "reading",
              topicTag,
              explanation: "drawing; collecting; cinema — hội thoại trong bài.",
              template:
                '"What are you doing?" "I am [0] a cat." "My hobby is [1] stamps." "On Saturday we go to the [2]."',
              correctAnswers: ["drawing", "collecting", "cinema"],
              acceptableAnswers: [
                ["drawing", "Drawing"],
                ["collecting", "Collecting"],
                ["cinema", "Cinema"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-response-review",
          title: "Review: Response Mix",
          instructions: "Read the passage. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: 'Best response to "Do you like playing football?"',
              skillTag: "reading",
              topicTag,
              explanation: "Yes, we like playing football after school.",
              correct: "Yes, we like playing football after school.",
              wrong: ["I am drawing a cat.", "I am going to the cinema now."],
              distractorNotes: ["Không liên quan", "Sai thời gian"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: 'Minh says: "I am reading a comic." Best follow-up question:',
              skillTag: "reading",
              topicTag,
              explanation: "Do you like reading comics? — hợp chủ đề.",
              correct: "Do you like reading comics?",
              wrong: ["Is it snowing today?", "Where is the hospital?"],
              distractorNotes: ["Unit thời tiết", "Unit sức khỏe"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-main-idea",
      title: "Lesson 2: Main Idea of Conversations",
      learningObjective:
        "Understand the main idea of short conversations about hobbies.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-main-learn",
          title: "Learn: What Is the Text About?",
          instructions: "Read the passage. What is the main idea?",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What is the main idea of this text?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh and Linh's hobbies and free-time activities — chủ đề chính.",
              correct: "Hobbies and free time after school",
              wrong: ["Weather and seasons", "Going to the doctor"],
              distractorNotes: ["Unit 3", "Unit 2"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What are Minh and Linh doing right now in the text?",
              skillTag: "reading",
              topicTag,
              explanation: "Reading and drawing — đoạn đầu bài đọc.",
              correct: "Reading a comic and drawing",
              wrong: ["Swimming and dancing", "Shopping at the market"],
              distractorNotes: ["Sở thích — không làm bây giờ", "Unit khác"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-main-practice",
          title: "Practice: Main Idea Details",
          instructions: "Read again. Choose the main point of each part.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "The middle part is mainly about:",
              skillTag: "reading",
              topicTag,
              explanation: "Minh's stamp hobby and weekend cinema/concert plans.",
              correct: "Minh's hobby and weekend plans",
              wrong: ["Yesterday's weather", "Minh's school subjects"],
              distractorNotes: ["Unit 3", "Không trong bài"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The last part is mainly about:",
              skillTag: "reading",
              topicTag,
              explanation: "What Minh and Linh like doing — swimming, dancing, football.",
              correct: "Things they like doing",
              wrong: ["What they are doing right now only", "A trip to the mountains"],
              distractorNotes: ["Cả sở thích lâu dài", "Không trong bài"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-main-check",
          title: "Check: Main Idea Challenge",
          instructions: "Find the main idea in the text.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Which title fits the text best?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh's Free Time — tiêu đề bài đọc.",
              correct: "Minh's Free Time",
              wrong: ["Rainy Days in Hanoi", "At the Supermarket"],
              distractorNotes: ["Unit 3", "Unit 6"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What is the main plan for the weekend?",
              skillTag: "reading",
              topicTag,
              explanation: "Cinema on Saturday and concert on Sunday.",
              correct: "Cinema and a concert",
              wrong: ["Only playing football", "Only collecting stamps"],
              distractorNotes: ["Cũng có nhưng không phải kế hoạch chính", "Sở thích hàng ngày"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who talks about hobbies in the conversation part?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh and Linh — What are you doing? I am drawing.",
              correct: "Minh and Linh",
              wrong: ["Only Mum", "A teacher"],
              distractorNotes: ["Mum kể cuối bài", "Không có"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-main-apply",
          title: "Apply: Match Part to Main Idea",
          instructions: "Match each part of the text to its main idea.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each part to its main idea.",
              skillTag: "reading",
              topicTag,
              explanation: "Now = reading/drawing; middle = stamps/cinema; end = likes.",
              pairs: [
                { left: "Right now", right: "reading and drawing" },
                { left: "Minh's hobby", right: "collecting stamps" },
                { left: "Weekend", right: "cinema and concert" },
                { left: "They like", right: "swimming, dancing, football" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-main-review",
          title: "Review: Main Idea Mix",
          instructions: "Find the main idea again.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "The text is mostly about activities:",
              skillTag: "reading",
              topicTag,
              explanation: "After school and at the weekend — thời gian rảnh.",
              correct: "after school and at the weekend",
              wrong: ["only at school in class", "only in winter"],
              distractorNotes: ["Sau giờ học", "Không chỉ mùa đông"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence best summarises the text?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh and Linh enjoy different hobbies and have fun plans.",
              correct: "Minh and Linh enjoy hobbies and have cinema and concert plans.",
              wrong: ["It was rainy yesterday.", "Minh works in a factory."],
              distractorNotes: ["Unit 3", "Unit 7"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-doing-vs-liking",
      title: "Lesson 3: Doing Now vs Liking",
      learningObjective:
        "Find details about what characters are doing now vs what they like.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-detail-learn",
          title: "Learn: Now or Like?",
          instructions: "Read the passage. Is it now or a hobby?",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "Minh is _____ a comic book right now.",
              skillTag: "reading",
              topicTag,
              explanation: "Reading — present continuous, bây giờ.",
              correct: "reading",
              wrong: ["liking", "collecting"],
              distractorNotes: ["Like + hobby", "Sở thích khác"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh _____ swimming in summer (every year).",
              skillTag: "reading",
              topicTag,
              explanation: "Likes — like + swimming, sở thích.",
              correct: "likes",
              wrong: ["is swimming now", "are swimming"],
              distractorNotes: ["Không nói bây giờ", "Minh → likes/is"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-detail-practice",
          title: "Practice: Match Now vs Like",
          instructions: "Match each sentence to 'now' or 'likes always'.",
          exerciseType: "matching",
          sortOrder: 1,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each idea to now or likes always.",
              skillTag: "reading",
              topicTag,
              explanation: "Reading/drawing = now; swimming/dancing/football = like.",
              pairs: [
                { left: "Minh is reading a comic", right: "happening now" },
                { left: "Linh is drawing a cat", right: "happening now" },
                { left: "Minh likes swimming", right: "likes always" },
                { left: "They like playing football", right: "likes always" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-detail-check",
          title: "Check: Detail Challenge",
          instructions: "Read carefully. Choose the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Which is true RIGHT NOW in the text?",
              skillTag: "reading",
              topicTag,
              explanation: "Linh is drawing — đang vẽ bây giờ.",
              correct: "Linh is drawing a cat.",
              wrong: ["Linh is at the cinema.", "Minh is swimming now."],
              distractorNotes: ["Cuối tuần", "Thích bơi — không làm bây giờ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which is true about HOBBIES (not right now)?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh collects stamps — sở thích sưu tập.",
              correct: "Minh collects stamps from many countries.",
              wrong: ["Minh is collecting stamps now.", "Linh is dancing now."],
              distractorNotes: ["Đang đọc comic", "Thích nhảy — không nhảy bây giờ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is NOT in the text?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh is playing football now — sai, đang đọc comic.",
              correct: "Minh is playing football right now.",
              wrong: ["Linh likes dancing at school.", "There is a concert on Sunday."],
              distractorNotes: ["Có trong bài", "Có trong bài"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-detail-apply",
          title: "Apply: Gap-Fill Now vs Like",
          instructions: "Fill in using the passage.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: Right now Minh is [0] a comic. | Linh is [1] a cat. | Minh likes [2] in summer. | They like [3] football.",
              skillTag: "reading",
              topicTag,
              explanation: "reading; drawing; swimming; playing — now vs like.",
              template:
                "Right now Minh is [0] a comic. Linh is [1] a cat. Minh likes [2] in summer. They like [3] football.",
              correctAnswers: ["reading", "drawing", "swimming", "playing"],
              acceptableAnswers: [
                ["reading", "Reading"],
                ["drawing", "Drawing"],
                ["swimming", "Swimming"],
                ["playing", "Playing"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-detail-review",
          title: "Review: Now vs Like Mix",
          instructions: "Choose the best answer from the text.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          content: { passage },
          questions: [
            buildMcq({
              questionText: "Linh likes _____ at school, but now she is drawing.",
              skillTag: "reading",
              topicTag,
              explanation: "Dancing — thích nhảy nhưng bây giờ đang vẽ.",
              correct: "dancing",
              wrong: ["reading", "collecting stamps"],
              distractorNotes: ["Minh đọc", "Minh sưu tập"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They are going to the cinema on _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Saturday — kế hoạch cuối tuần.",
              correct: "Saturday",
              wrong: ["Sunday", "every day after school"],
              distractorNotes: ["Concert — Chủ nhật", "Sau giờ học — khác"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What question does Minh ask Linh?",
              skillTag: "reading",
              topicTag,
              explanation: "What are you doing? — hội thoại trong bài.",
              correct: "What are you doing?",
              wrong: ["Do you like swimming?", "Was it rainy yesterday?"],
              distractorNotes: ["Câu hỏi khác", "Unit 3"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
