/** Movers U4 — speaking lessons (3 × 5 exercises; only Check is AI). */

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [nowCheck, hobbiesCheck, weekendCheck] = speakingChecks;

  return [
    {
      slug: "speaking-now-activity",
      title: "Lesson 1: Talk About Now",
      learningObjective:
        "Choose appropriate spoken phrases about activities happening now.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-now-learn",
          title: "Learn: What to Say About Now",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Mum asks: What are you doing? Minh says:",
              skillTag: "speaking",
              topicTag,
              explanation: "I am reading a comic book, Mum — trả lời tự nhiên.",
              correct: "I am reading a comic book, Mum.",
              wrong: ["I like reading comic Mum.", "Reading I am comic book."],
              distractorNotes: ["Sở thích — không trả lời bây giờ", "Sai trật tự"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best answer: What is Linh doing?",
              skillTag: "speaking",
              topicTag,
              explanation: "She is drawing a cat — present continuous.",
              correct: "She is drawing a cat. Look!",
              wrong: ["She likes drawing always now.", "She drawing is cat."],
              distractorNotes: ["Nhầm like vs is", "Thiếu is"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-now-practice",
          title: "Practice: Now Activity Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Minh asks: What are you doing? Linh says:",
              skillTag: "speaking",
              topicTag,
              explanation: "I am drawing a cat — trong bài đọc.",
              correct: "I am drawing a cat.",
              wrong: ["I like dancing at school.", "We are going to the cinema."],
              distractorNotes: ["Sở thích", "Cuối tuần"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum says: After you finish, you can play outside. Best reply:",
              skillTag: "speaking",
              topicTag,
              explanation: "Great! We like playing football — phản hồi tự nhiên.",
              correct: "Great! We like playing football after school.",
              wrong: ["Football playing great we like.", "Great football we playing like."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        nowCheck,
        buildExercise({
          slug: "speaking-now-apply",
          title: "Apply: Quick Now Replies",
          instructions: "Choose the best short spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Tell Mum what you are doing. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I am looking at my new stamp — trong bài nghe.",
              correct: "I am looking at my new stamp from Japan.",
              wrong: ["I like stamp Japan new looking.", "Looking stamp I Japan am new."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-now-review",
          title: "Review: Now Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Describe what Minh is doing now. Best phrase:",
              skillTag: "speaking",
              topicTag,
              explanation: "He is reading a comic book — mô tả bây giờ.",
              correct: "He is reading a comic book right now.",
              wrong: ["He likes reading always now is.", "He reading comic is book."],
              distractorNotes: ["Nhầm like", "Thiếu is"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Ask a friend what they are doing. Best question:",
              skillTag: "speaking",
              topicTag,
              explanation: "What are you doing? — câu hỏi chuẩn.",
              correct: "What are you doing?",
              wrong: ["What you doing are?", "What is you doing?"],
              distractorNotes: ["Sai trật tự", "You → are"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-hobbies",
      title: "Lesson 2: Talk About Hobbies",
      learningObjective:
        "Use like + -ing in short spoken answers about hobbies.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-hobbies-learn",
          title: "Learn: Hobby Phrases",
          instructions: "Choose the best thing to say about hobbies.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "What is your favourite hobby? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Collecting stamps is my favourite hobby — Minh.",
              correct: "Collecting stamps is my favourite hobby.",
              wrong: ["I am collecting stamps now always.", "Stamps collect favourite my is."],
              distractorNotes: ["Nhầm bây giờ", "Sai trật tự"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Do you like dancing? Linh would say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, I like dancing at school.",
              correct: "Yes, I like dancing at school.",
              wrong: ["Yes, I am dancing like school.", "Yes, I like dance at school."],
              distractorNotes: ["Sai am like", "Cần -ing"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-hobbies-practice",
          title: "Practice: Hobby Replies",
          instructions: "Choose the correct spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Do you like swimming? Best reply from Minh:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, I like swimming in summer.",
              wrong: ["Yes, I am swimming in summer always.", "Yes, I like swim in summer."],
              correct: "Yes, I like swimming in summer.",
              distractorNotes: ["Sở thích — không bơi bây giờ", "Cần -ing"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Do you like playing football? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, we like playing football after school.",
              correct: "Yes, we like playing football after school.",
              wrong: ["Yes, we are playing football like school.", "Yes, we like play football."],
              distractorNotes: ["Nhầm thì", "Cần -ing"],
              difficultyRating: 2,
            }),
          ],
        }),
        hobbiesCheck,
        buildExercise({
          slug: "speaking-hobbies-apply",
          title: "Apply: Tell About Hobbies",
          instructions: "Choose the best short spoken description.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best short story about Minh and Linh's hobbies:",
              skillTag: "speaking",
              topicTag,
              explanation: "Minh collects stamps; Linh likes dancing; both like football.",
              correct:
                "Minh's hobby is collecting stamps. Linh likes dancing at school. They both like playing football.",
              wrong: ["Minh stamps collect Linh dance football play both.", "Hobby Minh stamps dancing Linh school football."],
              distractorNotes: ["Không thành câu", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-hobbies-review",
          title: "Review: Hobbies Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Talk about reading. Best sentence:",
              skillTag: "speaking",
              topicTag,
              explanation: "I like reading comics — like + reading.",
              correct: "I like reading comics after school.",
              wrong: ["I am like reading comics.", "I like read comics after school."],
              distractorNotes: ["Sai am like", "Cần -ing"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Ask about a friend's hobby. Best question:",
              skillTag: "speaking",
              topicTag,
              explanation: "Do you like collecting stamps? — câu hỏi hợp lý.",
              correct: "Do you like collecting stamps?",
              wrong: ["Are you liking collect stamps?", "Do you like collect stamp?"],
              distractorNotes: ["Like không continuous", "Cần -ing"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-weekend-plans",
      title: "Lesson 3: Talk About Weekend Plans",
      learningObjective:
        "Describe cinema and concert plans in short spoken answers.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-weekend-learn",
          title: "Learn: Weekend Plan Phrases",
          instructions: "Choose the best thing to say about weekend plans.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Where are you going on Saturday? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "We are going to the cinema on Saturday.",
              correct: "We are going to the cinema on Saturday.",
              wrong: ["We like cinema going Saturday are.", "Saturday cinema we going to are."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What is on Sunday? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "There is a concert in the park on Sunday.",
              correct: "There is a concert in the park on Sunday.",
              wrong: ["There concert is park Sunday a in.", "Sunday park concert there is a."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-weekend-practice",
          title: "Practice: Plan Replies",
          instructions: "Choose the best spoken answers about plans.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Mum asks: What film do you want to see? Linh says:",
              skillTag: "speaking",
              topicTag,
              explanation: "I want an adventure film — thích comic.",
              correct: "I like reading comics, so I want an adventure film!",
              wrong: ["Adventure film want I comics reading like.", "I want film adventure comics."],
              distractorNotes: ["Sai trật tự", "Thiếu lý do"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Why is the concert perfect for Linh?",
              skillTag: "speaking",
              topicTag,
              explanation: "I like dancing, so a concert is perfect.",
              correct: "I like dancing, so a concert is perfect!",
              wrong: ["Dancing like I concert perfect is so.", "I am dancing concert perfect like."],
              distractorNotes: ["Sai trật tự", "Nhầm am vs like"],
              difficultyRating: 2,
            }),
          ],
        }),
        weekendCheck,
        buildExercise({
          slug: "speaking-weekend-apply",
          title: "Apply: Tell Weekend Plans",
          instructions: "Choose the best short spoken description.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best summary of the weekend plans:",
              skillTag: "speaking",
              topicTag,
              explanation: "Cinema Saturday, concert Sunday — thứ tự rõ.",
              correct: "On Saturday we are going to the cinema. On Sunday there is a concert in the park.",
              wrong: ["Saturday cinema Sunday concert we going park.", "Cinema Saturday concert Sunday park we is going."],
              distractorNotes: ["Không thành câu", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-weekend-review",
          title: "Review: Weekend Plans Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Ask Mum about the cinema. Best question:",
              skillTag: "speaking",
              topicTag,
              explanation: "Can we go to the cinema on Saturday? — như Minh.",
              correct: "Mum, can we go to the cinema on Saturday?",
              wrong: ["Mum cinema Saturday go we can?", "Can we cinema go Saturday Mum?"],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mum agrees to both plans. She says:",
              skillTag: "speaking",
              topicTag,
              explanation: "OK — cinema on Saturday, concert on Sunday!",
              correct: "OK — cinema on Saturday, concert on Sunday!",
              wrong: ["OK Sunday cinema Saturday concert on on.", "Cinema concert OK Saturday Sunday on."],
              distractorNotes: ["Sai trật tự", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
