/** Movers U4 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-hobby-words",
      title: "Lesson 1: Hobby Words",
      learningObjective:
        "Recognise and use hobby, drawing, dancing and collect in short sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-hobby-learn",
          title: "Learn: Hobby Vocabulary",
          instructions: "Read each clue. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Something you enjoy doing in your free time is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hobby (sở thích) — hoạt động bạn thích làm lúc rảnh.",
              correct: "hobby",
              wrong: ["stamp", "cinema"],
              distractorNotes: ["Một loại sưu tập", "Một địa điểm"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh is making pictures with a pencil. She is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Drawing (vẽ) — tạo hình bằng bút chì hoặc bút màu.",
              correct: "drawing",
              wrong: ["dancing", "collecting"],
              distractorNotes: ["Nhảy múa", "Sưu tập — không phải vẽ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Moving your body to music is called _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Dancing (nhảy múa) — di chuyển theo nhạc.",
              correct: "dancing",
              wrong: ["drawing", "reading"],
              distractorNotes: ["Vẽ tranh", "Đọc sách"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh wants to _____ stamps from many countries.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Collect (sưu tập) — gom và giữ nhiều thứ cùng loại.",
              correct: "collect",
              wrong: ["draw", "dance"],
              distractorNotes: ["Vẽ", "Nhảy"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-hobby-practice",
          title: "Practice: Match Hobby Words",
          instructions: "Match each word to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the hobby words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hobby, drawing, dancing, collect — từ về sở thích.",
              pairs: [
                { left: "hobby", right: "something fun you do in free time" },
                { left: "drawing", right: "making pictures with a pencil" },
                { left: "dancing", right: "moving your body to music" },
                { left: "collect", right: "keep many things of the same type" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-hobby-check",
          title: "Check: Hobby Words Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Collecting stamps is Minh's favourite _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hobby — sưu tập tem là sở thích của Minh.",
              correct: "hobby",
              wrong: ["cinema", "concert"],
              distractorNotes: ["Rạp phim", "Buổi hòa nhạc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh likes _____ at school.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Dancing — Linh thích nhảy múa ở trường.",
              correct: "dancing",
              wrong: ["stamps", "cinema"],
              distractorNotes: ["Tem thư", "Rạp phim"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Right now Linh is _____ a cat.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Drawing — Linh đang vẽ con mèo.",
              correct: "drawing",
              wrong: ["collecting", "swimming"],
              distractorNotes: ["Sưu tập", "Bơi lội"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-hobby-apply",
          title: "Apply: Complete Hobby Sentences",
          instructions: "Fill in each gap with the correct hobby word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Collecting stamps is Minh's [0]. | Linh is [1] a cat. | She likes [2] at school. | Minh wants to [3] more stamps.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "hobby; drawing; dancing; collect — từ bài đọc.",
              template:
                "Collecting stamps is Minh's [0]. Linh is [1] a cat. She likes [2] at school. Minh wants to [3] more stamps.",
              correctAnswers: ["hobby", "drawing", "dancing", "collect"],
              acceptableAnswers: [
                ["hobby", "Hobby"],
                ["drawing", "Drawing"],
                ["dancing", "Dancing"],
                ["collect", "Collect"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-hobby-review",
          title: "Review: Hobby Words Mix",
          instructions: "Mixed review from this lesson. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "What is Linh doing now in the text?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Drawing — Linh đang vẽ con mèo.",
              correct: "drawing",
              wrong: ["dancing", "collecting stamps"],
              distractorNotes: ["Thích nhưng không làm bây giờ", "Minh sưu tập tem"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word means 'keep many stamps'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Collect — sưu tập tem.",
              correct: "collect",
              wrong: ["draw", "dance"],
              distractorNotes: ["Vẽ", "Nhảy"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "A fun activity in free time is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hobby — sở thích, thú vui.",
              correct: "hobby",
              wrong: ["football only", "reading only"],
              distractorNotes: ["Chỉ một môn thể thao", "Chỉ một hoạt động"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-places-items",
      title: "Lesson 2: Places and Items",
      learningObjective:
        "Use stamp, comic, cinema and concert to talk about hobbies and plans.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-places-learn",
          title: "Learn: Stamps, Comics and Places",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh has a new _____ from Japan in his collection.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Stamp (tem thư) — vật sưu tập của Minh.",
              correct: "stamp",
              wrong: ["comic", "concert"],
              distractorNotes: ["Truyện tranh", "Buổi hòa nhạc"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh is reading a _____ book now.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Comic (truyện tranh) — sách có hình và lời thoại.",
              correct: "comic",
              wrong: ["stamp", "football"],
              distractorNotes: ["Tem thư", "Bóng đá"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "On Saturday they are going to the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cinema (rạp chiếu phim) — xem phim.",
              correct: "cinema",
              wrong: ["concert", "stamp shop"],
              distractorNotes: ["Hòa nhạc — Chủ nhật", "Không trong bài"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "There is a _____ in the park on Sunday.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Concert (buổi hòa nhạc) — nghe nhạc ngoài trời.",
              correct: "concert",
              wrong: ["cinema", "comic"],
              distractorNotes: ["Rạp phim — thứ Bảy", "Truyện tranh"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-places-practice",
          title: "Practice: Match Places and Items",
          instructions: "Match each word to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match stamps, comics, cinema and concert.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Stamp, comic, cinema, concert — đồ vật và địa điểm.",
              pairs: [
                { left: "stamp", right: "a small picture you put on a letter" },
                { left: "comic", right: "a book with pictures and speech bubbles" },
                { left: "cinema", right: "a place where you watch films" },
                { left: "concert", right: "a live music show" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-places-check",
          title: "Check: Places and Items Quiz",
          instructions: "Choose the best answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh collects _____ from many countries.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Stamps — Minh sưu tập tem.",
              correct: "stamps",
              wrong: ["comics only", "concerts"],
              distractorNotes: ["Đọc comic nhưng sưu tập tem", "Không sưu tập hòa nhạc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Where are Minh and Linh going on Saturday?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "The cinema — đi xem phim thứ Bảy.",
              correct: "the cinema",
              wrong: ["the concert", "school only"],
              distractorNotes: ["Concert — Chủ nhật", "Cuối tuần đi chơi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh likes reading _____, so she wants an adventure film.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Comics — trong bài nghe Linh thích truyện tranh.",
              correct: "comics",
              wrong: ["stamps", "football"],
              distractorNotes: ["Minh sưu tập tem", "Chơi bóng — khác đọc"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-places-apply",
          title: "Apply: Complete Place Sentences",
          instructions: "Complete the sentences about places and items.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh has a new [0] from Japan. | He is reading a [1] book. | On Saturday they go to the [2]. | On Sunday there is a [3] in the park.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "stamp; comic; cinema; concert — kế hoạch cuối tuần.",
              template:
                "Minh has a new [0] from Japan. He is reading a [1] book. On Saturday they go to the [2]. On Sunday there is a [3] in the park.",
              correctAnswers: ["stamp", "comic", "cinema", "concert"],
              acceptableAnswers: [
                ["stamp", "Stamp"],
                ["comic", "Comic"],
                ["cinema", "Cinema"],
                ["concert", "Concert"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-places-review",
          title: "Review: Places and Items Mix",
          instructions: "Mixed review. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "You watch a film at the _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cinema — rạp chiếu phim.",
              correct: "cinema",
              wrong: ["concert", "park only"],
              distractorNotes: ["Nghe nhạc", "Công viên có concert nhưng xem phim ở rạp"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which item is in Minh's stamp collection?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "A stamp from Japan — tem Nhật Bản.",
              correct: "a stamp from Japan",
              wrong: ["a comic from Japan", "a concert ticket"],
              distractorNotes: ["Truyện tranh", "Vé hòa nhạc — khác sưu tập"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "A live music show in the park is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Concert — buổi hòa nhạc.",
              correct: "concert",
              wrong: ["cinema", "comic"],
              distractorNotes: ["Rạp phim", "Truyện tranh"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-activities",
      title: "Lesson 3: Swimming, Playing, Reading and Football",
      learningObjective:
        "Use swimming, playing, reading and football in hobby and free-time contexts.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-activities-learn",
          title: "Learn: Activity Words",
          instructions: "Choose the word that best completes each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh likes _____ in summer when it is hot.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Swimming (bơi lội) — hoạt động mùa hè.",
              correct: "swimming",
              wrong: ["drawing", "collecting"],
              distractorNotes: ["Vẽ tranh", "Sưu tập tem"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "They like _____ football with friends after school.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Playing (chơi) — chơi bóng đá với bạn.",
              correct: "playing",
              wrong: ["reading", "dancing"],
              distractorNotes: ["Đọc sách", "Nhảy múa"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Right now Minh is _____ a comic book.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Reading (đọc) — đang đọc truyện tranh.",
              correct: "reading",
              wrong: ["swimming", "dancing"],
              distractorNotes: ["Bơi — không phải bây giờ", "Vẽ/nhảy"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "After school they play _____ in the park.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Football (bóng đá) — môn thể thao phổ biến.",
              correct: "football",
              wrong: ["comics", "concerts"],
              distractorNotes: ["Truyện tranh — đọc không chơi", "Buổi hòa nhạc"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-activities-practice",
          title: "Practice: Match Activity Words",
          instructions: "Match each word to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match swimming, playing, reading and football.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Swimming, playing, reading, football — hoạt động rảnh rỗi.",
              pairs: [
                { left: "swimming", right: "moving in water for fun or sport" },
                { left: "playing", right: "doing a game or sport for fun" },
                { left: "reading", right: "looking at words in a book" },
                { left: "football", right: "a team sport with a ball and goals" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-activities-check",
          title: "Check: Activity Words Challenge",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh is _____ a comic book now.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Reading — đang đọc truyện tranh.",
              correct: "reading",
              wrong: ["swimming", "playing football"],
              distractorNotes: ["Bơi — ở nhà đọc sách", "Chơi bóng — sau này"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They both like _____ football after school.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Playing — like + playing football.",
              correct: "playing",
              wrong: ["reading", "collecting"],
              distractorNotes: ["Đọc sách", "Sưu tập tem"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which activity is best in hot summer weather?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Swimming — bơi khi trời nóng.",
              correct: "swimming",
              wrong: ["reading comics inside only", "collecting stamps"],
              distractorNotes: ["Có thể làm nhưng không đặc trưng hè", "Mọi mùa"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-activities-apply",
          title: "Apply: Complete Activity Sentences",
          instructions: "Fill in with swimming, playing, reading or football.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh likes [0] in summer. | They like [1] football. | Right now he is [2] a comic. | Mum says they can play [3] outside.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "swimming; playing; reading; football — hoạt động trong unit.",
              template:
                "Minh likes [0] in summer. They like [1] football. Right now he is [2] a comic. Mum says they can play [3] outside.",
              correctAnswers: ["swimming", "playing", "reading", "football"],
              acceptableAnswers: [
                ["swimming", "Swimming"],
                ["playing", "Playing"],
                ["reading", "Reading"],
                ["football", "Football"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-activities-review",
          title: "Review: All Hobby Words Mix",
          instructions: "Choose the best word from the whole unit.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "After they finish drawing, they can play _____ outside.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Football — mẹ nói chơi bóng ngoài sân.",
              correct: "football",
              wrong: ["cinema", "concert"],
              distractorNotes: ["Cuối tuần", "Chủ nhật"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "_____ comics is fun for Minh every day.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Reading — đọc truyện tranh.",
              correct: "Reading",
              wrong: ["Playing", "Collecting"],
              distractorNotes: ["Chơi bóng", "Sưu tập tem"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh likes dancing. Minh likes _____ in summer.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Swimming — Minh thích bơi mùa hè.",
              correct: "swimming",
              wrong: ["football only", "concerts"],
              distractorNotes: ["Cũng thích bóng nhưng câu hỏi mùa hè", "Cuối tuần"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
