/** PET U1 — listening lessons (3 × 5 exercises). Speaker attitude and purpose in career and scholarship talks. */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptCareerTalk,
  listeningScriptScholarshipInfo,
  listeningAnswerKeys,
  topicTag,
}) {
  const careerTalk = listeningScriptCareerTalk;
  const scholarshipInfo = listeningScriptScholarshipInfo;
  const keysCareer = listeningAnswerKeys.careerTalk;
  const keysScholarship = listeningAnswerKeys.scholarshipInfo;

  return [
    {
      slug: "listening-career-talk",
      title: "Lesson 1: Career Talk — Attitude and Purpose",
      learningObjective:
        "Identify the speaker's purpose and attitude in a school career talk about engineering.",
      estimatedMinutes: 24,
      exercises: [
        buildListeningExercise({
          slug: "listening-career-learn",
          title: "Learn: Mr Davies' Purpose",
          instructions: "Listen to the career talk. Answer the questions.",
          sortOrder: 0,
          script: careerTalk,
          answerKey: keysCareer,
          questions: [
            buildMcq({
              questionText: "What is the main purpose of Mr Davies' talk?",
              skillTag: "listening",
              topicTag,
              explanation: "Help students think realistically about engineering careers.",
              correct: "To help students think realistically about engineering careers",
              wrong: ["To announce scholarship winners", "To change the school timetable"],
              distractorNotes: ["Scholarship script khác", "Không nhắc"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which careers does the talk focus on?",
              skillTag: "listening",
              topicTag,
              explanation: "Engineering careers — engineering pathways.",
              correct: "Engineering",
              wrong: ["Medicine only", "Teaching"],
              distractorNotes: ["Không nhắc", "Không nhắc"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-career-practice",
          title: "Practice: Speaker Attitude",
          instructions: "Listen again. Focus on the speaker's attitude.",
          sortOrder: 1,
          script: careerTalk,
          answerKey: keysCareer,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "How would you describe Mr Davies' attitude?",
              skillTag: "listening",
              topicTag,
              explanation: "Encouraging but honest — not just exciting parts, be realistic.",
              correct: "Encouraging but honest",
              wrong: ["Completely discouraging", "Uninterested and bored"],
              distractorNotes: ["Vẫn khuyến khích engineering", "Rất engaged"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What does Mr Davies say managers value more than perfect exam results?",
              skillTag: "listening",
              topicTag,
              explanation: "Curiosity matters more — every manager said the same.",
              correct: "Curiosity",
              wrong: ["High salary immediately", "Perfect grades only"],
              distractorNotes: ["Students want salary", "Ngược nghĩa"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-career-check",
          title: "Check: Career Talk Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: careerTalk,
          answerKey: keysCareer,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Why might students struggle if they chose engineering for the wrong reason?",
              skillTag: "listening",
              topicTag,
              explanation: "Only because it sounds impressive — might struggle later.",
              correct: "They chose it only because it sounds impressive",
              wrong: ["They visited too many companies", "They entered science competitions"],
              distractorNotes: ["Davies visited companies", "Đó là điều tích cực"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What does Mr Davies advise students to do before deciding?",
              skillTag: "listening",
              topicTag,
              explanation: "Research careers carefully before you decide.",
              correct: "Research careers carefully",
              wrong: ["Apply for scholarships immediately", "Avoid university completely"],
              distractorNotes: ["Scholarship script", "Khuyên cần degree"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Where can students get individual advice?",
              skillTag: "listening",
              topicTag,
              explanation: "Careers office — come to the careers office.",
              correct: "The careers office",
              wrong: ["The scholarship office only", "A partner university abroad"],
              distractorNotes: ["Scholarship coordinator", "Không nhắc"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-career-apply",
          title: "Apply: Match Career Talk Ideas",
          instructions: "Listen again. Match each idea to the speaker's message.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: careerTalk },
          questions: [
            buildMatching({
              questionText: "Match each topic to Mr Davies' message.",
              skillTag: "listening",
              topicTag,
              explanation: "Degree needed; curiosity; research; wrong reason = struggle.",
              pairs: [
                { left: "Engineering careers", right: "usually need a university degree" },
                { left: "What managers value", right: "curiosity over perfect grades" },
                { left: "Before deciding", right: "research careers carefully" },
                { left: "Choosing for impressiveness only", right: "you might struggle later" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-career-review",
          title: "Review: Career Talk Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: careerTalk,
          answerKey: keysCareer,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Students who enjoyed science competitions and problem-solving might find engineering _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Excellent choice — if you genuinely enjoyed…",
              correct: "an excellent choice",
              wrong: ["impossible", "unnecessary"],
              distractorNotes: ["Ngược nghĩa", "Ngược nghĩa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The speaker's purpose is to inform, not to _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Not just sell exciting online image — realistic advice.",
              correct: "mislead students with only exciting online images",
              wrong: ["give any advice at all", "mention university degrees"],
              distractorNotes: ["Có đưa advice", "Có nhắc degree"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-scholarship-info",
      title: "Lesson 2: Scholarship Session — Purpose and Tone",
      learningObjective:
        "Understand the purpose and tone of a scholarship information announcement.",
      estimatedMinutes: 24,
      exercises: [
        buildListeningExercise({
          slug: "listening-scholarship-learn",
          title: "Learn: Ms Lan's Announcement",
          instructions: "Listen to the scholarship session. Answer the questions.",
          sortOrder: 0,
          script: scholarshipInfo,
          answerKey: keysScholarship,
          questions: [
            buildMcq({
              questionText: "What is the purpose of Ms Lan's session?",
              skillTag: "listening",
              topicTag,
              explanation: "Explain the application process clearly.",
              correct: "To explain the scholarship application process",
              wrong: ["To interview students for jobs", "To announce exam results"],
              distractorNotes: ["Careers talk khác", "Không nhắc"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Who is the announcement for?",
              skillTag: "listening",
              topicTag,
              explanation: "Year 10 students — Attention Year 10 students.",
              correct: "Year 10 students",
              wrong: ["University graduates", "Primary school children"],
              distractorNotes: ["Chưa tốt nghiệp", "Quá nhỏ"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-scholarship-practice",
          title: "Practice: Tone and Requirements",
          instructions: "Listen again. Focus on tone and requirements.",
          sortOrder: 1,
          script: scholarshipInfo,
          answerKey: keysScholarship,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "How would you describe Ms Lan's tone?",
              skillTag: "listening",
              topicTag,
              explanation: "Formal but friendly — pleased to announce, encourages applications.",
              correct: "Formal but friendly and encouraging",
              wrong: ["Angry and discouraging", "Completely informal and joking"],
              distractorNotes: ["Khuyến khích apply", "School announcement formal"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What happens to incomplete application forms?",
              skillTag: "listening",
              topicTag,
              explanation: "Will not be considered — must be complete.",
              correct: "They will not be considered",
              wrong: ["They automatically win", "They get extra time"],
              distractorNotes: ["Không tự thắng", "Không nói gia hạn"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-scholarship-check",
          title: "Check: Scholarship Listening Details",
          instructions: "Listen to the full announcement again.",
          sortOrder: 2,
          script: scholarshipInfo,
          answerKey: keysScholarship,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "When is the application deadline?",
              skillTag: "listening",
              topicTag,
              explanation: "Friday fifteenth May at four p.m.",
              correct: "Friday 15 May at 4 p.m.",
              wrong: ["Next Thursday morning", "Last year in March"],
              distractorNotes: ["Session day khác", "Không nhắc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Besides grades, what does the programme look at?",
              skillTag: "listening",
              topicTag,
              explanation: "Ambitions, competition results and teacher recommendations.",
              correct: "Ambitions, competition results and teacher recommendations",
              wrong: ["Only perfect grades in every subject", "Only family income"],
              distractorNotes: ["Không cần perfect mọi môn", "Không chỉ income"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What must students ask their form teacher to upload?",
              skillTag: "listening",
              topicTag,
              explanation: "A reference letter — ask form teacher to upload.",
              correct: "A reference letter",
              wrong: ["Their tuition payment", "A university degree"],
              distractorNotes: ["Không nhắc", "Chưa có degree"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-scholarship-apply",
          title: "Apply: Order the Announcement",
          instructions: "Put the ideas in the order they are mentioned.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          content: { script: scholarshipInfo },
          questions: [
            buildMcq({
              questionText:
                "Correct order: (1) deadline (2) programme open (3) what forms need",
              skillTag: "listening",
              topicTag,
              explanation: "Open → process/requirements → deadline.",
              correct: "2 → 3 → 1",
              wrong: ["1 → 2 → 3", "3 → 1 → 2"],
              distractorNotes: ["Deadline cuối", "Deadline không đầu"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-scholarship-review",
          title: "Review: Scholarship Announcement Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: scholarshipInfo,
          answerKey: keysScholarship,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "A scholarship can cover part or all of your _____ fees.",
              skillTag: "listening",
              topicTag,
              explanation: "Tuition fees at partner universities abroad.",
              correct: "tuition",
              wrong: ["career", "ambition"],
              distractorNotes: ["Danh từ khác", "Danh từ khác"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Ms Lan especially encourages students who have prepared _____. ",
              skillTag: "listening",
              topicTag,
              explanation: "Qualifications or portfolio work — strongly encourage.",
              correct: "qualifications or portfolio work",
              wrong: ["only perfect exam results", "no teacher references"],
              distractorNotes: ["Không chỉ grades", "Cần reference"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-future-review",
      title: "Lesson 3: Review Both Talks",
      learningObjective:
        "Compare speaker purpose and attitude across career and scholarship talks.",
      estimatedMinutes: 26,
      exercises: [
        buildListeningExercise({
          slug: "listening-review-learn",
          title: "Learn: Career Talk Reminder",
          instructions: "Listen to the career talk again.",
          sortOrder: 0,
          script: careerTalk,
          answerKey: keysCareer,
          questions: [
            buildMcq({
              questionText: "Mr Davies understands students' ambition for a high salary, but he wants to be _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Honest — I want to be honest about engineering careers.",
              correct: "honest",
              wrong: ["silent", "unhelpful"],
              distractorNotes: ["Có nói nhiều", "Offers advice"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The talk takes place in the _____.",
              skillTag: "listening",
              topicTag,
              explanation: "School hall, career day — setting in script.",
              correct: "school hall",
              wrong: ["scholarship office", "university campus abroad"],
              distractorNotes: ["Scholarship setting", "Chưa đi học"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-practice",
          title: "Practice: Scholarship Talk Reminder",
          instructions: "Listen to the scholarship announcement again.",
          sortOrder: 1,
          script: scholarshipInfo,
          answerKey: keysScholarship,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Students should submit their form _____ and get a teacher reference.",
              skillTag: "listening",
              topicTag,
              explanation: "Submit online — form online + reference upload.",
              correct: "online",
              wrong: ["only by phone", "on the careers office board only"],
              distractorNotes: ["Không nhắc", "Scholarship office after school for help"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "If students need help, they should visit the scholarship office _____.",
              skillTag: "listening",
              topicTag,
              explanation: "After school — visit after school.",
              correct: "after school",
              wrong: ["during the career talk", "only on the deadline day"],
              distractorNotes: ["Career talk khác", "Không giới hạn một ngày"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-check",
          title: "Check: Mixed Talk Listening",
          instructions: "Compare both talks. Harder questions.",
          sortOrder: 2,
          script: scholarshipInfo,
          answerKey: keysScholarship,
          difficulty: 0.38,
          questions: [
            buildMcq({
              questionText: "Which detail is ONLY in the career talk?",
              skillTag: "listening",
              topicTag,
              explanation: "Managers value curiosity — chỉ Mr Davies.",
              correct: "Managers value curiosity over perfect grades",
              wrong: ["Application deadline 15 May", "Incomplete forms not considered"],
              distractorNotes: ["Scholarship talk", "Scholarship talk"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Both speakers encourage students to _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Prepare/plan carefully — research careers + prepare qualifications.",
              correct: "prepare and plan carefully for the future",
              wrong: ["avoid university completely", "choose careers only for money"],
              distractorNotes: ["Cả hai khuyên học/plan", "Davies cảnh báo chọn vì tiền"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-review-apply",
          title: "Apply: Match Talk to Purpose",
          instructions: "Match each purpose to the correct talk.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: careerTalk },
          questions: [
            buildMatching({
              questionText: "Match each purpose to Career talk or Scholarship announcement.",
              skillTag: "listening",
              topicTag,
              explanation: "Career = realistic advice; Scholarship = application process and deadline.",
              pairs: [
                { left: "Explain application process and deadline", right: "Scholarship announcement" },
                { left: "Warn about choosing careers for wrong reasons", right: "Career talk" },
                { left: "Cover tuition at partner universities", right: "Scholarship announcement" },
                { left: "Advise researching careers before deciding", right: "Career talk" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-future-review-final",
          title: "Review: Both Talks Mix",
          instructions: "Listen to the career talk. Final review.",
          sortOrder: 4,
          script: careerTalk,
          answerKey: keysCareer,
          difficulty: 0.38,
          questions: [
            buildMcq({
              questionText: "Which attitude word best describes BOTH speakers?",
              skillTag: "listening",
              topicTag,
              explanation: "Encouraging — Davies encouraging but honest; Lan encourages applications.",
              correct: "encouraging",
              wrong: ["discouraging", "indifferent"],
              distractorNotes: ["Cả hai supportive", "Cả hai engaged"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which topic connects Minh's blog, the career talk AND the scholarship talk?",
              skillTag: "listening",
              topicTag,
              explanation: "University / future education plans — chủ đề unit.",
              correct: "planning for university and future education",
              wrong: ["family holidays", "daily meal routines"],
              distractorNotes: ["Flyers", "Không liên quan"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
