/** PET U1 — speaking lessons (3 × 5 exercises; only Check is AI, MCQ elsewhere). */

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [ambitionCheck, scholarshipCheck, careerCheck] = speakingChecks;

  return [
    {
      slug: "speaking-ambitions",
      title: "Lesson 1: Talk About Ambitions",
      learningObjective:
        "Choose appropriate spoken phrases about career ambitions and university plans.",
      estimatedMinutes: 24,
      exercises: [
        buildExercise({
          slug: "speaking-ambition-learn",
          title: "Learn: What to Say About Ambitions",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Examiner: What is your main career ambition? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "My main ambition is to… — cấu trúc phỏng vấn B1.",
              correct: "My main ambition is to become a mechanical engineer.",
              wrong: ["My main tuition is engineering.", "My ambition career is scholarship."],
              distractorNotes: ["Tuition không phải ambition", "Collocation sai"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Examiner: How long have you wanted this career? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I have wanted… since primary school — present perfect + since.",
              correct: "I have wanted to be an engineer since primary school.",
              wrong: ["I have wanted since primary school for engineer.", "I wanted since primary school have."],
              distractorNotes: ["Thiếu to be", "Wrong order"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-ambition-practice",
          title: "Practice: Second Conditional Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "If you got a full scholarship, what would you study? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "If I got… I would enrol/study… — second conditional.",
              correct: "If I got a full scholarship, I would study mechanical engineering abroad.",
              wrong: ["If I get a scholarship, I study abroad.", "If I got scholarship I will study."],
              distractorNotes: ["First conditional", "Would + will"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What did you do last year to learn about university? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Last year I visited… — past simple + finished time.",
              correct: "Last year I visited a university open day.",
              wrong: ["I have visited a university open day last year.", "Last year I have visit open day."],
              distractorNotes: ["Present perfect + last year", "Wrong form"],
              difficultyRating: 2,
            }),
          ],
        }),
        ambitionCheck,
        buildExercise({
          slug: "speaking-ambition-apply",
          title: "Apply: Quick Ambition Replies",
          instructions: "Choose the best short spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Examiner: What is your opinion about tuition fees abroad? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Opinion + reason — B1 extended answer.",
              correct: "I think tuition fees are quite high, so scholarships are really important for many families.",
              wrong: ["Tuition fees abroad opinion high.", "Fees tuition I think scholarship."],
              distractorNotes: ["Fragment", "Not a sentence"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-ambition-review",
          title: "Review: Ambition Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Examiner: Where would you like to study? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "At a good university abroad — connected answer.",
              correct: "I would like to study at a good university abroad if I can get financial support.",
              wrong: ["University abroad study I like.", "Study university abroad good I."],
              distractorNotes: ["Wrong order", "Fragment"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: Have you gained any qualifications? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes, I have gained… — present perfect experience.",
              correct: "Yes, I have gained a qualification in computer programming.",
              wrong: ["Yes, I gained qualification last year have.", "Yes qualification programming I."],
              distractorNotes: ["Mixed tenses awkwardly", "Fragment"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-scholarships",
      title: "Lesson 2: Talk About Scholarships",
      learningObjective:
        "Use scholarship, application and deadline vocabulary in short spoken answers.",
      estimatedMinutes: 24,
      exercises: [
        buildExercise({
          slug: "speaking-scholarship-learn",
          title: "Learn: Scholarship Speaking Phrases",
          instructions: "Choose the best thing to say about scholarships.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Examiner: Tell me about the scholarship programme. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "It can cover tuition + application process — cụ thể B1.",
              correct: "It can cover part or all of my tuition fees at partner universities abroad.",
              wrong: ["Scholarship tuition career ambition programme.", "It cover fees tuition all me."],
              distractorNotes: ["Fragment", "Wrong grammar"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Examiner: When is the deadline? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Friday 15 May at four p.m. — từ listening.",
              correct: "The deadline is Friday 15 May at four p.m.",
              wrong: ["Deadline Friday May fifteen four.", "The deadline is next Thursday only."],
              distractorNotes: ["Fragment", "Session day khác deadline"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-scholarship-practice",
          title: "Practice: Application Speaking",
          instructions: "Choose the correct spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Have you ever applied for a scholarship? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "No, not yet, but I'm preparing — present perfect question.",
              correct: "No, I haven't applied yet, but I am preparing my form now.",
              wrong: ["No, I didn't applied yet never.", "No apply scholarship I not."],
              distractorNotes: ["Wrong form", "Fragment"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Do you agree that scholarships are only for perfect students? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "No, I don't agree — hard work and ambitions matter.",
              correct: "No, I don't agree. Hard work and clear ambitions matter too.",
              wrong: ["No agree I perfect students only not fair.", "No scholarships perfect only yes."],
              distractorNotes: ["Wrong order", "Unclear"],
              difficultyRating: 2,
            }),
          ],
        }),
        scholarshipCheck,
        buildExercise({
          slug: "speaking-scholarship-apply",
          title: "Apply: Choose the Best Scholarship Reply",
          instructions: "Pick the most natural spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Examiner: What would you do if you didn't get a scholarship? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "If I didn't get… I would study here first — second conditional.",
              correct: "If I didn't get a scholarship, I would probably study in Vietnam first and apply again later.",
              wrong: ["If I don't get scholarship I studied Vietnam.", "No scholarship I Vietnam study first."],
              distractorNotes: ["Wrong conditional", "Fragment"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-scholarship-review",
          title: "Review: Scholarship Speaking Quiz",
          instructions: "Choose the best answer using scholarship vocabulary.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Examiner: What do you need from your form teacher? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Upload a reference letter — từ scholarship announcement.",
              correct: "I need my form teacher to upload a reference letter for my application.",
              wrong: ["Form teacher reference upload I need letter.", "Teacher form letter reference need."],
              distractorNotes: ["Wrong order", "Fragment"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: What qualifications could help your application? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Programming qualification + competition results.",
              correct: "I have a programming qualification and I have entered science competitions this year.",
              wrong: ["Qualification programming competition entered I.", "I have qualification programming competition have entered."],
              distractorNotes: ["Fragment", "Repetition awkward"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-career-advice",
      title: "Lesson 3: Discuss Career Advice",
      learningObjective:
        "Discuss career talk purpose, speaker attitude and realistic planning in spoken answers.",
      estimatedMinutes: 26,
      exercises: [
        buildExercise({
          slug: "speaking-career-learn",
          title: "Learn: Career Talk Phrases",
          instructions: "Choose the best thing to say about career advice.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Examiner: What was the purpose of the last career talk? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Help us think realistically — từ career talk listening.",
              correct: "The purpose was to help us think realistically about engineering careers.",
              wrong: ["Purpose career talk engineering realistic think us.", "Talk career purpose scholarship application."],
              distractorNotes: ["Wrong order", "Scholarship khác"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Examiner: Was the speaker encouraging or discouraging? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Encouraging but honest — attitude Mr Davies.",
              correct: "He was encouraging but honest — not just the exciting parts online.",
              wrong: ["He discouraging completely was.", "Speaker attitude none."],
              distractorNotes: ["Sai attitude", "Fragment"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-career-practice",
          title: "Practice: Realistic Planning",
          instructions: "Choose the best spoken answers.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "If you chose a career only for money, what might happen? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "You might struggle — second conditional from career talk.",
              correct: "You might struggle later because you wouldn't enjoy the work.",
              wrong: ["You might struggle money career only chose.", "Struggle you career money only if."],
              distractorNotes: ["Wrong order", "Fragment"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What have you done this year to research careers? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Entered competitions + spoke to adviser — present perfect.",
              correct: "I have entered three science competitions and I spoke to our careers adviser.",
              wrong: ["I enter three competition this year research career.", "Research career I competitions three entered."],
              distractorNotes: ["Wrong tense", "Wrong order"],
              difficultyRating: 2,
            }),
          ],
        }),
        careerCheck,
        buildExercise({
          slug: "speaking-career-apply",
          title: "Apply: Tell About Career Planning",
          instructions: "Choose the best career planning description.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best short description of your future planning:",
              skillTag: "speaking",
              topicTag,
              explanation: "Connected ideas: ambition + research + conditional plan.",
              correct:
                "My ambition is to become an engineer. I have researched careers carefully, and if I got a scholarship, I would enrol abroad. Otherwise, I would study here first.",
              wrong: [
                "Ambition engineer scholarship research career enrol.",
                "I have since wanted if would career research money only.",
              ],
              distractorNotes: ["Not sentences", "Ungrammatical"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-career-review",
          title: "Review: Career Advice Speaking Quiz",
          instructions: "Choose the best spoken answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Examiner: What do managers value according to the career talk? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Curiosity more than perfect exam results.",
              correct: "They value curiosity more than perfect exam results.",
              wrong: ["Managers value perfect grades only curiosity not.", "Value curiosity managers they perfect."],
              distractorNotes: ["Ngược nghĩa", "Wrong order"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Compare: I have prepared… / If I got… Best pair:",
              skillTag: "speaking",
              topicTag,
              explanation: "Present perfect real prep + second conditional hypothetical enrol.",
              correct:
                "I have prepared well this year. If I got a scholarship, I would enrol in an engineering degree abroad.",
              wrong: [
                "I have prepared if I got scholarship would enrol.",
                "If I have prepared I got scholarship enrol would.",
              ],
              distractorNotes: ["Mixed wrongly", "Ungrammatical"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
