/** PET U1 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-future-plans",
      title: "Lesson 1: University and Career Words",
      learningObjective:
        "Recognise and use university, degree, career, ambition and scholarship in context.",
      estimatedMinutes: 24,
      exercises: [
        buildExercise({
          slug: "vocab-future-learn",
          title: "Learn: Future Plan Word Match",
          instructions: "Read each clue. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Money given to help a student pay for study is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Scholarship (học bổng) hỗ trợ chi phí học tập.",
              correct: "scholarship",
              wrong: ["tuition", "qualification"],
              distractorNotes: ["Học phí — phải trả", "Chứng chỉ — không phải tiền hỗ trợ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "A strong desire to achieve something important in life is an _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ambition (tham vọng) là mục tiêu lớn trong sự nghiệp.",
              correct: "ambition",
              wrong: ["degree", "career"],
              distractorNotes: ["Bằng cấp", "Nghề nghiệp — khái niệm rộng hơn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The job or profession you follow over many years is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Career (sự nghiệp) là con đường nghề nghiệp dài hạn.",
              correct: "career",
              wrong: ["university", "enrol"],
              distractorNotes: ["Nơi học", "Động từ đăng ký"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "After secondary school, many students go to _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "University (đại học) là bậc học sau trung học.",
              correct: "university",
              wrong: ["tuition", "scholarship"],
              distractorNotes: ["Học phí", "Học bổng"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-future-practice",
          title: "Practice: Match Future Plan Words",
          instructions: "Match each word to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the words to their meanings.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Degree = university qualification; tuition = fees; enrol = register to study.",
              pairs: [
                { left: "degree", right: "a university qualification in a subject" },
                { left: "tuition", right: "money you pay to attend a course" },
                { left: "enrol", right: "officially register to study at a school" },
                { left: "qualification", right: "a certificate showing your skills or training" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-future-check",
          title: "Check: Vocab Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh wants a mechanical engineering _____ at a good university.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Degree (chương trình/bằng) — mechanical engineering degree.",
              correct: "degree",
              wrong: ["tuition", "ambition"],
              distractorNotes: ["Học phí", "Tham vọng — không đi sau engineering"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "If he got a scholarship, he would _____ immediately.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Enrol (đăng ký nhập học) — would enrol in a degree.",
              correct: "enrol",
              wrong: ["tuition", "career"],
              distractorNotes: ["Danh từ", "Danh từ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Fees you pay to study at university are called _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Tuition (học phí) — tuition fees.",
              correct: "tuition",
              wrong: ["scholarship", "qualification"],
              distractorNotes: ["Tiền hỗ trợ", "Chứng chỉ"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-future-apply",
          title: "Apply: Complete the Sentences",
          instructions: "Fill in the gaps with words from the unit.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: My main [0] is to study engineering. | A full [1] could cover my [2] fees. | I have gained useful [3] in programming.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "ambition; scholarship; tuition; qualifications — từ vựng unit.",
              template:
                "My main [0] is to study engineering. A full [1] could cover my [2] fees. I have gained useful [3] in programming.",
              correctAnswers: ["ambition", "scholarship", "tuition", "qualifications"],
              acceptableAnswers: [
                ["ambition", "Ambition"],
                ["scholarship", "Scholarship"],
                ["tuition", "Tuition"],
                ["qualifications", "Qualification", "qualification"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-future-review",
          title: "Review: Future Plan Vocab Mix",
          instructions: "Choose the best word for each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Research different _____ before you choose your university course.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Careers (sự nghiệp) — research careers carefully.",
              correct: "careers",
              wrong: ["tuitions", "enrols"],
              distractorNotes: ["Học phí — không đếm số nhiều như vậy", "Động từ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "A partner university abroad might offer a partial _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Scholarship — partial scholarship covers part of fees.",
              correct: "scholarship",
              wrong: ["degree", "ambition"],
              distractorNotes: ["Bằng cấp", "Tham vọng"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-education-system",
      title: "Lesson 2: Qualifications and Applications",
      learningObjective:
        "Use qualification, enrol, tuition and scholarship in sentences about applying to university.",
      estimatedMinutes: 24,
      exercises: [
        buildExercise({
          slug: "vocab-apply-learn",
          title: "Learn: Application Vocabulary",
          instructions: "Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "A certificate showing you have completed a course is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Qualification (chứng chỉ/bằng cấp) chứng minh kỹ năng.",
              correct: "qualification",
              wrong: ["ambition", "career"],
              distractorNotes: ["Tham vọng", "Sự nghiệp"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "To _____ at university means to officially become a student there.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Enrol (đăng ký nhập học) — register as a student.",
              correct: "enrol",
              wrong: ["graduate", "compete"],
              distractorNotes: ["Tốt nghiệp", "Thi đấu"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-apply-practice",
          title: "Practice: Word in Context",
          instructions: "Choose the word that fits best.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "The scholarship programme can cover part or all of your _____ fees.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Tuition fees — học phí được học bổng chi trả.",
              correct: "tuition",
              wrong: ["ambition", "degree"],
              distractorNotes: ["Không collocation", "Degree fees ít dùng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh has already gained useful _____ in computer programming.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Qualifications — chứng chỉ lập trình.",
              correct: "qualifications",
              wrong: ["tuitions", "universities"],
              distractorNotes: ["Học phí", "Trường đại học"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-apply-check",
          title: "Check: Application Vocab Challenge",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which collocation is correct?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Apply for a scholarship — đăng ký xin học bổng.",
              correct: "apply for a scholarship",
              wrong: ["apply a scholarship", "apply to scholarship"],
              distractorNotes: ["Thiếu for", "Sai giới từ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence uses 'enrol' correctly?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Enrol in a degree — đăng ký vào chương trình.",
              correct: "He would enrol in a mechanical engineering degree.",
              wrong: [
                "He would enrol a mechanical engineering.",
                "He would enrol on scholarship money.",
              ],
              distractorNotes: ["Thiếu in + degree", "Enrol on scholarship sai"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-apply-apply",
          title: "Apply: Match Word to Context",
          instructions: "Match each word to the sentence it fits best.",
          exerciseType: "matching",
          sortOrder: 3,
          questions: [
            buildMatching({
              questionText: "Match each word to its best context.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ambition = goal; tuition = fees; qualification = certificate; university = place of study.",
              pairs: [
                { left: "ambition", right: "My main goal is to become an engineer" },
                { left: "tuition", right: "Fees abroad worry many families" },
                { left: "qualification", right: "A certificate from a programming course" },
                { left: "university", right: "Where you study for a degree after school" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-apply-review",
          title: "Review: Application Vocab Quiz",
          instructions: "Mixed review — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "An incomplete application form will not be _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Considered — không được xem xét (từ listening scholarship).",
              correct: "considered",
              wrong: ["enrolled", "graduated"],
              distractorNotes: ["Đăng ký học", "Tốt nghiệp"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "A _____ can cover part or all of your tuition at partner universities.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Scholarship — học bổng quốc tế.",
              correct: "scholarship",
              wrong: ["career", "ambition"],
              distractorNotes: ["Sự nghiệp", "Tham vọng"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-mixed-future",
      title: "Lesson 3: Vocabulary Review — Future Plans",
      learningObjective:
        "Review all unit vocabulary in mixed contexts about education and future plans.",
      estimatedMinutes: 25,
      exercises: [
        buildExercise({
          slug: "vocab-mixed-learn",
          title: "Learn: Quick Word Recall",
          instructions: "Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Engineering, medicine and law are examples of _____ paths.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Career paths — con đường sự nghiệp.",
              correct: "career",
              wrong: ["tuition", "enrol"],
              distractorNotes: ["Học phí", "Động từ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "A mechanical engineering _____ usually takes three or four years.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Degree — bằng đại học.",
              correct: "degree",
              wrong: ["scholarship", "ambition"],
              distractorNotes: ["Học bổng", "Tham vọng"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mixed-practice",
          title: "Practice: Synonym and Context",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "'Register to study' is closest in meaning to _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Enrol — đăng ký nhập học.",
              correct: "enrol",
              wrong: ["graduate", "compete"],
              distractorNotes: ["Tốt nghiệp", "Thi đấu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Hard work and clear _____ matter in scholarship applications.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ambitions — tham vọng rõ ràng.",
              correct: "ambitions",
              wrong: ["tuitions", "degrees"],
              distractorNotes: ["Học phí", "Bằng cấp"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mixed-check",
          title: "Check: Mixed Vocab Challenge",
          instructions: "Harder questions — no hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which word does NOT fit with 'fees'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ambition fees — không collocation; tuition fees đúng.",
              correct: "ambition",
              wrong: ["tuition", "university"],
              distractorNotes: ["Tuition fees", "University fees có thể dùng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh's programming certificate is an example of a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Qualification — chứng chỉ kỹ năng.",
              correct: "qualification",
              wrong: ["scholarship", "career"],
              distractorNotes: ["Học bổng", "Sự nghiệp"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mixed-apply",
          title: "Apply: Complete Minh's Sentences",
          instructions: "Fill in the gaps.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I want a [0] abroad, but [1] is expensive. | A [2] would help me [3] at a partner university.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "degree; tuition; scholarship; enrol — câu về kế hoạch học.",
              template:
                "I want a [0] abroad, but [1] is expensive. A [2] would help me [3] at a partner university.",
              correctAnswers: ["degree", "tuition", "scholarship", "enrol"],
              acceptableAnswers: [
                ["degree", "Degree"],
                ["tuition", "Tuition"],
                ["scholarship", "Scholarship"],
                ["enrol", "Enrol", "enroll", "Enroll"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-mixed-review",
          title: "Review: Unit Vocabulary Mix",
          instructions: "Final vocabulary review.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "The whole unit is mainly about education and _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Future plans — chủ đề unit PET U1.",
              correct: "future plans",
              wrong: ["family visits", "daily routines"],
              distractorNotes: ["Flyers U1", "Movers U1"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which three words are most closely connected?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Scholarship, tuition, enrol — quy trình xin học bổng và nhập học.",
              correct: "scholarship — tuition — enrol",
              wrong: [
                "career — tuition — exam",
                "ambition — library — homework",
              ],
              distractorNotes: ["Exam không phải từ unit", "Library/homework KET"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
