/** Starters U2 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-how-many",
      title: "Lesson 1: How Many?",
      learningObjective:
        "Use how many to ask about quantities and answer with numbers.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-how-many-learn",
          title: "Learn: How Many Questions",
          instructions: "Choose the correct word to complete each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "_____ books do you have? — I have three.",
              skillTag: "grammar",
              topicTag,
              explanation: "How many (bao nhiêu) hỏi số lượng danh từ đếm được.",
              correct: "How many",
              wrong: ["How old", "How"],
              distractorNotes: ["How old hỏi tuổi", "How một mình không đủ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ pencils are in your bag? — Five.",
              skillTag: "grammar",
              topicTag,
              explanation: "How many + danh từ số nhiều (pencils).",
              correct: "How many",
              wrong: ["How old", "What"],
              distractorNotes: ["Hỏi tuổi", "What hỏi vật/con người"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best answer: How many friends are here? — _____",
              skillTag: "grammar",
              topicTag,
              explanation: "Ten. / I have ten friends. — trả lời số lượng.",
              correct: "Ten.",
              wrong: ["I am ten.", "Tuesday."],
              distractorNotes: ["I am ten trả lời tuổi", "Tuesday là ngày"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "How many desks are in the class? — _____",
              skillTag: "grammar",
              topicTag,
              explanation: "Twenty — bài đọc: twenty desks.",
              correct: "Twenty.",
              wrong: ["I am twenty.", "On Tuesday."],
              distractorNotes: ["Tuổi, không phải số lượng", "Ngày"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-how-many-practice",
          title: "Practice: How Many Gap Fill",
          instructions: "Complete the questions and answers.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] books do you read? | I have [1] books. | [2] friends come to the party?",
              skillTag: "grammar",
              topicTag,
              explanation: "How many; three; How many — hỏi và trả lời số lượng.",
              template: "[0] books do you read? I have [1] books. [2] friends come to the party?",
              correctAnswers: ["How many", "three", "How many"],
              acceptableAnswers: [
                ["How many", "how many"],
                ["three", "Three"],
                ["How many", "how many"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-how-many-check",
          title: "Check: How Many Quiz",
          instructions: "Choose the best answer. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "_____ candles are on the cake? — Eight.",
              skillTag: "grammar",
              topicTag,
              explanation: "How many hỏi số lượng nến.",
              correct: "How many",
              wrong: ["How old", "What time"],
              distractorNotes: ["Hỏi tuổi", "Hỏi giờ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Teacher: How many pencils do you have? Mai: _____",
              skillTag: "grammar",
              topicTag,
              explanation: "I have five pencils. — trả lời how many.",
              correct: "I have five pencils.",
              wrong: ["I am five.", "I am five pencils."],
              distractorNotes: ["Trả lời tuổi", "Sai ngữ pháp"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which question asks about quantity?",
              skillTag: "grammar",
              topicTag,
              explanation: "How many friends — số lượng. How old — tuổi.",
              correct: "How many friends are here?",
              wrong: ["How old are you?", "What day is today?"],
              distractorNotes: ["Hỏi tuổi", "Hỏi ngày"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-how-many-apply",
          title: "Apply: Order How Many Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: How / many / books / do / you / have?",
              skillTag: "grammar",
              topicTag,
              explanation: "How many books do you have? — How many + danh từ + do you have?",
              words: ["How", "many", "books", "do", "you", "have?"],
              correctOrder: [0, 1, 2, 3, 4, 5],
            }),
            buildSentenceOrdering({
              questionText: "Make: I / have / ten / friends.",
              skillTag: "grammar",
              topicTag,
              explanation: "I have ten friends. — trả lời how many.",
              words: ["I", "have", "ten", "friends."],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-how-many-review",
          title: "Review: How Many Mix",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "How many brothers does Mai have? — _____",
              skillTag: "grammar",
              topicTag,
              explanation: "One. — I have one brother (từ unit 1, tiếp nối).",
              correct: "One.",
              wrong: ["I am one.", "Monday."],
              distractorNotes: ["Tuổi", "Ngày"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "_____ desks are in our class? — Twenty.",
              skillTag: "grammar",
              topicTag,
              explanation: "How many desks — hỏi số lượng bàn.",
              correct: "How many",
              wrong: ["How old", "How"],
              distractorNotes: ["Hỏi tuổi", "Thiếu many"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna asks: How many friends at the party? Best reply:",
              skillTag: "grammar",
              topicTag,
              explanation: "Ten friends. — số lượng bạn.",
              correct: "Ten friends.",
              wrong: ["I am ten.", "At three o'clock."],
              distractorNotes: ["Tuổi", "Giờ"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-how-old",
      title: "Lesson 2: How Old?",
      learningObjective:
        "Use how old to ask about age and answer with I am / He is + number.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "grammar-how-old-learn",
          title: "Learn: How Old Questions",
          instructions: "Choose the correct word to complete each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "_____ are you? — I am eight.",
              skillTag: "grammar",
              topicTag,
              explanation: "How old (bao nhiêu tuổi) hỏi tuổi.",
              correct: "How old",
              wrong: ["How many", "How"],
              distractorNotes: ["How many hỏi số lượng", "How một mình không đủ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ is your brother Nam? — He is six.",
              skillTag: "grammar",
              topicTag,
              explanation: "How old is + người — hỏi tuổi Nam.",
              correct: "How old",
              wrong: ["How many", "What"],
              distractorNotes: ["Hỏi số lượng", "What hỏi vật/danh tính"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best answer: How old is Anna? — _____",
              skillTag: "grammar",
              topicTag,
              explanation: "She is seven. — trả lời tuổi Anna.",
              correct: "She is seven.",
              wrong: ["She has seven.", "Seven friends."],
              distractorNotes: ["Have hỏi số lượng", "Số bạn, không phải tuổi"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mai says: I am eight _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Years old — I am eight years old (có thể rút gọn I am eight).",
              correct: "years old.",
              wrong: ["books.", "o'clock."],
              distractorNotes: ["Số lượng sách", "Giờ"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-how-old-practice",
          title: "Practice: How Old Gap Fill",
          instructions: "Complete the questions and answers.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] old are you? | I [1] eight. | [2] old is Nam? | He [3] six.",
              skillTag: "grammar",
              topicTag,
              explanation: "How; am; How; is — How old + am/is + số.",
              template: "[0] old are you? I [1] eight. [2] old is Nam? He [3] six.",
              correctAnswers: ["How", "am", "How", "is"],
              acceptableAnswers: [
                ["How", "how"],
                ["am"],
                ["How", "how"],
                ["is"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-how-old-check",
          title: "Check: How Old Quiz",
          instructions: "Choose the correct form. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Teacher: How old are you today, Mai? Mai: _____",
              skillTag: "grammar",
              topicTag,
              explanation: "I am eight today! — trả lời tuổi sinh nhật.",
              correct: "I am eight today!",
              wrong: ["I have eight today.", "Eight friends today."],
              distractorNotes: ["Have = số lượng", "Số bạn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "_____ is Anna? — She is seven.",
              skillTag: "grammar",
              topicTag,
              explanation: "How old is Anna? — hỏi tuổi.",
              correct: "How old",
              wrong: ["How many", "What time"],
              distractorNotes: ["Số lượng", "Giờ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence tells an age correctly?",
              skillTag: "grammar",
              topicTag,
              explanation: "He is six. — đúng mẫu how old.",
              correct: "He is six.",
              wrong: ["He has six.", "He is six books."],
              distractorNotes: ["Have = số lượng", "Sai nghĩa"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-how-old-apply",
          title: "Apply: Order Age Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: How / old / are / you?",
              skillTag: "grammar",
              topicTag,
              explanation: "How old are you? — câu hỏi tuổi chuẩn.",
              words: ["How", "old", "are", "you?"],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: I / am / eight / years / old.",
              skillTag: "grammar",
              topicTag,
              explanation: "I am eight years old. — trả lời tuổi đầy đủ.",
              words: ["I", "am", "eight", "years", "old."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-how-old-review",
          title: "Review: How Old Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Nam is Mai's brother. He _____ six.",
              skillTag: "grammar",
              topicTag,
              explanation: "He is six — is với he.",
              correct: "is",
              wrong: ["am", "are"],
              distractorNotes: ["Chỉ với I", "Dùng với they/you"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "_____ old are they? — They are seven and eight.",
              skillTag: "grammar",
              topicTag,
              explanation: "How old are they? — hỏi tuổi nhiều người.",
              correct: "How",
              wrong: ["How many", "What"],
              distractorNotes: ["Cần old sau How", "What không hỏi tuổi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "On her birthday, Mai says: I _____ eight today!",
              skillTag: "grammar",
              topicTag,
              explanation: "I am eight today — am với I.",
              correct: "am",
              wrong: ["is", "are"],
              distractorNotes: ["Không dùng với I", "Không dùng với I"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-numbers-in-context",
      title: "Lesson 3: Numbers and Days in Context",
      learningObjective:
        "Use numbers, days and time phrases together in short Starters sentences.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "grammar-numbers-learn",
          title: "Learn: Numbers and Days",
          instructions: "Choose the correct word or phrase.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Today is _____. Tomorrow is Tuesday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Monday — hôm nay thứ Hai, mai thứ Ba.",
              correct: "Monday",
              wrong: ["ten", "o'clock"],
              distractorNotes: ["Số", "Giờ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "My birthday is _____ Tuesday.",
              skillTag: "grammar",
              topicTag,
              explanation: "On + ngày — on Tuesday.",
              correct: "on",
              wrong: ["at", "how"],
              distractorNotes: ["At + giờ/o'clock", "How không đi với ngày"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The party starts _____ three o'clock.",
              skillTag: "grammar",
              topicTag,
              explanation: "At + giờ — at three o'clock.",
              correct: "at",
              wrong: ["on", "how many"],
              distractorNotes: ["On + ngày", "Không phải giới từ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "There are _____ desks in our class.",
              skillTag: "grammar",
              topicTag,
              explanation: "Twenty — số lượng danh từ số nhiều desks.",
              correct: "twenty",
              wrong: ["Tuesday", "birthday"],
              distractorNotes: ["Ngày", "Sự kiện"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-numbers-practice",
          title: "Practice: Days and Times Gap Fill",
          instructions: "Complete with numbers, days or prepositions.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: Today is [0]. | My birthday is [1] Tuesday. | The party is [2] three o'clock.",
              skillTag: "grammar",
              topicTag,
              explanation: "Monday; on; at — on + ngày, at + giờ.",
              template: "Today is [0]. My birthday is [1] Tuesday. The party is [2] three o'clock.",
              correctAnswers: ["Monday", "on", "at"],
              acceptableAnswers: [
                ["Monday", "monday"],
                ["on", "On"],
                ["at", "At"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-numbers-check",
          title: "Check: Numbers and Days Quiz",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "My birthday is on Tuesday. — on + ngày.",
              correct: "My birthday is on Tuesday.",
              wrong: ["My birthday is at Tuesday.", "My birthday is in Tuesday."],
              distractorNotes: ["At dùng với giờ", "In không dùng với ngày ở Starters"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "School starts at eight _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Eight o'clock — số + o'clock.",
              correct: "o'clock",
              wrong: ["Monday", "birthday"],
              distractorNotes: ["Ngày", "Sự kiện"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai is eight. Nam is six. Together they are _____ years old total? (8+6=14 — choose best Starters answer)",
              skillTag: "grammar",
              topicTag,
              explanation: "Starters tập trung nhận biết số riêng lẻ; câu đúng nhất: Mai is eight and Nam is six.",
              correct: "Mai is eight and Nam is six.",
              wrong: ["Mai is Monday.", "Eight o'clock six."],
              distractorNotes: ["Sai nghĩa", "Trộn giờ và số"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-numbers-apply",
          title: "Apply: Order Number Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Today / is / Monday.",
              skillTag: "grammar",
              topicTag,
              explanation: "Today is Monday. — mẫu nói ngày.",
              words: ["Today", "is", "Monday."],
              correctOrder: [0, 1, 2],
            }),
            buildSentenceOrdering({
              questionText: "Make: The / party / is / at / three / o'clock.",
              skillTag: "grammar",
              topicTag,
              explanation: "The party is at three o'clock.",
              words: ["The", "party", "is", "at", "three", "o'clock."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-numbers-review",
          title: "Review: Numbers and Days Mix",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Tomorrow is Tuesday. Today is _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Monday — ngày trước Tuesday.",
              correct: "Monday",
              wrong: ["ten", "birthday"],
              distractorNotes: ["Số", "Sự kiện"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How many + _____ = How many books?",
              skillTag: "grammar",
              topicTag,
              explanation: "How many đi trực tiếp với danh từ số nhiều (books).",
              correct: "books",
              wrong: ["old", "o'clock"],
              distractorNotes: ["How old", "Không phải danh từ đếm"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Ten friends come _____ Tuesday.",
              skillTag: "grammar",
              topicTag,
              explanation: "On Tuesday — on + ngày.",
              correct: "on",
              wrong: ["at", "how"],
              distractorNotes: ["At + giờ", "Không phải giới từ"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
