/** Starters U2 — listening lessons (3 × 5 exercises). */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptMaiAtSchool,
  listeningScriptBirthdayParty,
  listeningAnswerKeys,
  topicTag,
}) {
  const atSchool = listeningScriptMaiAtSchool;
  const birthdayParty = listeningScriptBirthdayParty;
  const keysSchool = listeningAnswerKeys.atSchool;
  const keysParty = listeningAnswerKeys.birthdayParty;

  return [
    {
      slug: "listening-mai-at-school",
      title: "Lesson 1: Mai at School",
      learningObjective:
        "Listen to Mai at school and identify ages, numbers and days.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-school-learn",
          title: "Learn: Listen at School",
          instructions: "Listen to the conversation. Choose the correct answer.",
          sortOrder: 0,
          script: atSchool,
          answerKey: keysSchool,
          questions: [
            buildMcq({
              questionText: "How old is Mai?",
              skillTag: "listening",
              topicTag,
              explanation: "Mai nói: I am eight.",
              correct: "Eight",
              wrong: ["Six", "Five"],
              distractorNotes: ["Tuổi Nam", "Số bút chì"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "How many pencils does Mai have?",
              skillTag: "listening",
              topicTag,
              explanation: "I have five pencils.",
              correct: "Five",
              wrong: ["Three", "Ten"],
              distractorNotes: ["Số sách", "Số bạn"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-practice",
          title: "Practice: More from At School",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: atSchool,
          answerKey: keysSchool,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "What day is today?",
              skillTag: "listening",
              topicTag,
              explanation: "Today is Monday.",
              correct: "Monday",
              wrong: ["Tuesday", "birthday"],
              distractorNotes: ["Ngày mai", "Sự kiện"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Tomorrow is Mai's _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Tomorrow is Tuesday. It is my birthday!",
              correct: "birthday",
              wrong: ["Monday", "party only"],
              distractorNotes: ["Hôm nay", "Chưa nói party"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-check",
          title: "Check: At School Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: atSchool,
          answerKey: keysSchool,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "How old is Nam?",
              skillTag: "listening",
              topicTag,
              explanation: "He is six.",
              correct: "Six",
              wrong: ["Eight", "Seven"],
              distractorNotes: ["Tuổi Mai", "Tuổi Anna"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What day is tomorrow?",
              skillTag: "listening",
              topicTag,
              explanation: "Tomorrow is Tuesday.",
              correct: "Tuesday",
              wrong: ["Monday", "today"],
              distractorNotes: ["Hôm nay", "Không phải tên ngày"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-school-apply",
          title: "Apply: Match At School Facts",
          instructions: "Listen again. Match each question to the answer.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: atSchool, answerKey: keysSchool },
          questions: [
            buildMatching({
              questionText: "Match questions to answers from the dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "How old=eight; pencils=five; today=Monday; Nam=six.",
              pairs: [
                { left: "How old is Mai?", right: "eight" },
                { left: "How many pencils?", right: "five" },
                { left: "Today is", right: "Monday" },
                { left: "How old is Nam?", right: "six" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-review",
          title: "Review: At School Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: atSchool,
          answerKey: keysSchool,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Who asks How old are you?",
              skillTag: "listening",
              topicTag,
              explanation: "Teacher: How old are you?",
              correct: "The teacher",
              wrong: ["Nam", "Anna"],
              distractorNotes: ["Nam được hỏi tuổi", "Anna không có"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai has _____ pencils.",
              skillTag: "listening",
              topicTag,
              explanation: "Five pencils.",
              correct: "five",
              wrong: ["three", "ten"],
              distractorNotes: ["Số sách bài đọc", "Số bạn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai is happy because tomorrow is her _____.",
              skillTag: "listening",
              topicTag,
              explanation: "It is my birthday!",
              correct: "birthday",
              wrong: ["Monday", "school"],
              distractorNotes: ["Ngày hôm nay", "Không phải lý do"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-birthday-party",
      title: "Lesson 2: Birthday Party",
      learningObjective:
        "Listen to a birthday party dialogue and extract ages, numbers and times.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-party-learn",
          title: "Learn: Listen at the Party",
          instructions: "Listen to the birthday party. Answer the first questions.",
          sortOrder: 0,
          script: birthdayParty,
          answerKey: keysParty,
          questions: [
            buildMcq({
              questionText: "How old is Mai today at the party?",
              skillTag: "listening",
              topicTag,
              explanation: "I am eight today!",
              correct: "Eight",
              wrong: ["Six", "Ten"],
              distractorNotes: ["Tuổi Nam", "Số bạn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What time does the party start?",
              skillTag: "listening",
              topicTag,
              explanation: "The party starts at three o'clock.",
              correct: "Three o'clock",
              wrong: ["Eight o'clock", "Ten o'clock"],
              distractorNotes: ["Giờ trường", "Số bạn"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-party-practice",
          title: "Practice: More from the Party",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: birthdayParty,
          answerKey: keysParty,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "How many friends are at the party?",
              skillTag: "listening",
              topicTag,
              explanation: "I have ten friends at my party.",
              correct: "Ten",
              wrong: ["Three", "Twenty"],
              distractorNotes: ["Số sách", "Số bàn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who says Happy birthday, Mai?",
              skillTag: "listening",
              topicTag,
              explanation: "Anna: Happy birthday, Mai!",
              correct: "Anna",
              wrong: ["Nam", "The teacher"],
              distractorNotes: ["Nam nói về giờ", "Không có"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-party-check",
          title: "Check: Party Listening Quiz",
          instructions: "Listen one more time. Choose carefully.",
          sortOrder: 2,
          script: birthdayParty,
          answerKey: keysParty,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "What day is it at the party?",
              skillTag: "listening",
              topicTag,
              explanation: "Today is Tuesday.",
              correct: "Tuesday",
              wrong: ["Monday", "birthday only"],
              distractorNotes: ["Hôm qua", "Không phải tên ngày"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who tells the party start time?",
              skillTag: "listening",
              topicTag,
              explanation: "Nam: The party starts at three o'clock.",
              correct: "Nam",
              wrong: ["Anna", "Mai"],
              distractorNotes: ["Anna hỏi số bạn", "Mai trả lời tuổi"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-party-apply",
          title: "Apply: Match Party Dialogue",
          instructions: "Listen again. Match each speaker to what they say.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: birthdayParty, answerKey: keysParty },
          questions: [
            buildMatching({
              questionText: "Match speakers to their key lines.",
              skillTag: "listening",
              topicTag,
              explanation: "Anna=Happy birthday; Mai=ten friends; Nam=three o'clock.",
              pairs: [
                { left: "Anna", right: "Happy birthday, Mai!" },
                { left: "Mai", right: "I have ten friends" },
                { left: "Nam", right: "at three o'clock" },
                { left: "Anna (last line)", right: "Today is Tuesday" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-party-review",
          title: "Review: Party Dialogue Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: birthdayParty,
          answerKey: keysParty,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Anna asks: How old are you today? Mai says:",
              skillTag: "listening",
              topicTag,
              explanation: "I am eight today!",
              correct: "I am eight today!",
              wrong: ["I have eight friends.", "Today is Monday."],
              distractorNotes: ["Số lượng", "Sai ngày"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Ten friends are at Mai's _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Ten friends at my party.",
              correct: "party",
              wrong: ["school", "Monday class"],
              distractorNotes: ["Ở trường bài khác", "Không phải ngữ cảnh"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The party is on _____ at three o'clock.",
              skillTag: "listening",
              topicTag,
              explanation: "Today is Tuesday — ngày tiệc.",
              correct: "Tuesday",
              wrong: ["Monday", "ten"],
              distractorNotes: ["Ngày hôm qua", "Số"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-ages-and-numbers-review",
      title: "Lesson 3: Ages and Numbers Review",
      learningObjective:
        "Review both listening scripts and extract ages, numbers and times.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-review-school-learn",
          title: "Learn: School Dialogue Again",
          instructions: "Listen to Mai at school. Answer the questions.",
          sortOrder: 0,
          script: atSchool,
          answerKey: keysSchool,
          questions: [
            buildMcq({
              questionText: "How many pencils does Mai have at school?",
              skillTag: "listening",
              topicTag,
              explanation: "Five pencils.",
              correct: "Five",
              wrong: ["Eight", "Three"],
              distractorNotes: ["Tuổi Mai", "Số sách"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mai's birthday is on _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Tomorrow is Tuesday. It is my birthday!",
              correct: "Tuesday",
              wrong: ["Monday", "today"],
              distractorNotes: ["Hôm nay", "Không phải tên ngày"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-party-practice",
          title: "Practice: Party Numbers",
          instructions: "Listen to the birthday party. Focus on numbers.",
          sortOrder: 1,
          script: birthdayParty,
          answerKey: keysParty,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "How many friends does Mai have at the party?",
              skillTag: "listening",
              topicTag,
              explanation: "Ten friends.",
              correct: "Ten",
              wrong: ["Five", "Three"],
              distractorNotes: ["Số bút chì bài school", "Số sách"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The party starts at _____ o'clock.",
              skillTag: "listening",
              topicTag,
              explanation: "At three o'clock.",
              correct: "three",
              wrong: ["eight", "ten"],
              distractorNotes: ["Tuổi Mai", "Số bạn"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-check",
          title: "Check: Ages and Numbers Quiz",
          instructions: "Listen to the school dialogue one final time.",
          sortOrder: 2,
          script: atSchool,
          answerKey: keysSchool,
          difficulty: 0.36,
          questions: [
            buildMcq({
              questionText: "Put in order: (1) how many pencils (2) how old is Mai (3) how old is Nam",
              skillTag: "listening",
              topicTag,
              explanation: "Hội thoại: tuổi Mai → bút chì → Monday → tuổi Nam.",
              correct: "2 → 1 → 3",
              wrong: ["1 → 2 → 3", "3 → 2 → 1"],
              distractorNotes: ["Tuổi Mai hỏi trước bút chì", "Nam ở cuối"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Both dialogues mention Mai's age as _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Eight in both school and party scripts.",
              correct: "eight",
              wrong: ["six", "ten"],
              distractorNotes: ["Tuổi Nam", "Số bạn"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-review-apply",
          title: "Apply: Match Both Dialogues",
          instructions: "Listen to the party. Match facts heard in both scripts.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: birthdayParty, answerKey: keysParty },
          questions: [
            buildMatching({
              questionText: "Match facts to where you hear them (school or party).",
              skillTag: "listening",
              topicTag,
              explanation: "Pencils=school; ten friends=party; Tuesday=both; eight=both.",
              pairs: [
                { left: "five pencils", right: "at school" },
                { left: "ten friends", right: "at the party" },
                { left: "Tuesday birthday", right: "both dialogues" },
                { left: "three o'clock", right: "at the party" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-final",
          title: "Review: Full Listening Recall",
          instructions: "Listen to the party and answer — full review.",
          sortOrder: 4,
          script: birthdayParty,
          answerKey: keysParty,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Anna says today is a great _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Today is Tuesday. It is a great day!",
              correct: "day",
              wrong: ["book", "pencil"],
              distractorNotes: ["Không nói sách", "Không nói bút"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai is eight. Nam is six. Who is older?",
              skillTag: "listening",
              topicTag,
              explanation: "Eight > six — Mai lớn hơn (Nam ở bài school).",
              correct: "Mai",
              wrong: ["Nam", "Anna"],
              distractorNotes: ["Six nhỏ hơn eight", "Anna seven — giữa hai nhưng câu hỏi Mai/Nam"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which number do you NOT hear in the party dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Party có eight, three, ten — không có twenty.",
              correct: "twenty",
              wrong: ["ten", "three"],
              distractorNotes: ["Có trong party", "Có trong party"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
