/** Starters U2 — reading lessons (3 × 5 exercises). */

export function readingLessons({
  buildMcq,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMaiWeek,
  topicTag,
}) {
  const passage = passageMaiWeek;

  return [
    {
      slug: "reading-mais-birthday-week",
      title: "Lesson 1: Mai's Birthday Week",
      learningObjective:
        "Read about Mai's week and answer questions about numbers and days.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-week-learn",
          title: "Learn: Read Mai's Week",
          instructions: "Read the text. Then answer the questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What is the main idea of the text?",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation:
                "Bài về tuần sinh nhật Mai: hôm nay Monday, mai Tuesday là sinh nhật.",
              correct: "Mai's birthday is coming on Tuesday.",
              wrong: ["Mai goes to the zoo.", "Mai talks about her pets."],
              distractorNotes: ["Không có sở thú", "Không có thú cưng"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "How old is Mai?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "I am eight years old.",
              correct: "Eight years old",
              wrong: ["Six years old", "Seven years old"],
              distractorNotes: ["Tuổi Nam", "Tuổi Anna"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-week-practice",
          title: "Practice: More from the Text",
          instructions: "Read again. Answer about days and numbers.",
          sortOrder: 1,
          passage,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "What day is today in the story?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Today is Monday.",
              correct: "Monday",
              wrong: ["Tuesday", "today"],
              distractorNotes: ["Ngày mai/sinh nhật", "Từ chung, không phải tên ngày"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "When is Mai's birthday?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Tuesday is my birthday!",
              correct: "Tuesday",
              wrong: ["Monday", "today only"],
              distractorNotes: ["Hôm nay", "Hôm nay chưa phải sinh nhật"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-week-check",
          title: "Check: Birthday Week Quiz",
          instructions: "Read carefully. Choose the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "How many books do they read at school on Monday?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "We read three books.",
              correct: "Three",
              wrong: ["Ten", "Twenty"],
              distractorNotes: ["Số bạn", "Số bàn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What time is the birthday party?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "At three o'clock.",
              correct: "Three o'clock",
              wrong: ["Eight o'clock", "Ten o'clock"],
              distractorNotes: ["Giờ trường không nêu", "Số bạn"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-week-apply",
          title: "Apply: Match Facts from the Text",
          instructions: "Use the text. Match each fact to the correct detail.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match people and things to facts from the text.",
              skillTag: "reading",
              topicTag,
              explanation: "Mai = eight; Nam = six; Anna = seven; party = ten friends.",
              pairs: [
                { left: "Mai", right: "eight years old" },
                { left: "Nam", right: "six years old" },
                { left: "Anna", right: "seven years old" },
                { left: "The party", right: "ten friends will come" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-week-review",
          title: "Review: Mai's Week Mix",
          instructions: "Read the text again. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "How many desks are in the class?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Twenty desks.",
              correct: "Twenty",
              wrong: ["Ten", "Three"],
              distractorNotes: ["Số bạn", "Số sách"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Tomorrow is Tuesday. Today is _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "inference",
              explanation: "Today is Monday — câu đầu bài.",
              correct: "Monday",
              wrong: ["Tuesday", "birthday"],
              distractorNotes: ["Ngày mai", "Sự kiện"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How old is Nam?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "My brother Nam is six.",
              correct: "Six years old",
              wrong: ["Eight years old", "Seven years old"],
              distractorNotes: ["Tuổi Mai", "Tuổi Anna"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-numbers-in-text",
      title: "Lesson 2: Numbers in the Text",
      learningObjective:
        "Find numbers for ages, quantities and time in Mai's birthday text.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-numbers-learn",
          title: "Learn: Find Numbers",
          instructions: "Read Mai's text. Answer about numbers.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "How many friends will come to the party?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Ten friends will come.",
              correct: "Ten",
              wrong: ["Three", "Twenty"],
              distractorNotes: ["Số sách", "Số bàn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Anna is _____ years old.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "My friend Anna is seven.",
              correct: "seven",
              wrong: ["six", "eight"],
              distractorNotes: ["Tuổi Nam", "Tuổi Mai"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-numbers-practice",
          title: "Practice: Ages and Quantities",
          instructions: "Read again. Answer about numbers in context.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Which number tells how many desks there are?",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "Twenty desks in our class.",
              correct: "twenty",
              wrong: ["ten", "three"],
              distractorNotes: ["Số bạn", "Số sách"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai will be eight _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "inference",
              explanation: "I am eight tomorrow — sinh nhật ngày mai.",
              correct: "tomorrow",
              wrong: ["on Monday", "at three o'clock"],
              distractorNotes: ["Hôm nay còn bảy... thực ra đã eight tomorrow", "Giờ tiệc"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-numbers-check",
          title: "Check: Numbers Reading Quiz",
          instructions: "Read carefully. Choose the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.35,
          questions: [
            buildMcq({
              questionText: "Put events in order: (1) read books (2) birthday party (3) today is Monday",
              skillTag: "reading",
              topicTag,
              assessmentType: "sequencing",
              explanation: "Hôm nay Monday → đọc sách → mai tiệc sinh nhật.",
              correct: "3 → 1 → 2",
              wrong: ["2 → 1 → 3", "1 → 3 → 2"],
              distractorNotes: ["Tiệc chưa diễn ra hôm nay", "Thiếu ngày đầu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The biggest number in the text is _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Twenty desks — số lớn nhất trong bài.",
              correct: "twenty",
              wrong: ["ten", "eight"],
              distractorNotes: ["Nhỏ hơn twenty", "Tuổi Mai"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-numbers-apply",
          title: "Apply: Match Numbers to Meaning",
          instructions: "Use the text. Match each number to what it counts.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match numbers to what they describe in the text.",
              skillTag: "reading",
              topicTag,
              explanation: "3=books; 6=Nam's age; 10=friends; 20=desks.",
              pairs: [
                { left: "three", right: "books read at school" },
                { left: "six", right: "Nam's age" },
                { left: "ten", right: "friends at the party" },
                { left: "twenty", right: "desks in the class" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-numbers-review",
          title: "Review: Numbers Reading Mix",
          instructions: "Read and answer — mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.33,
          questions: [
            buildMcq({
              questionText: "Three o'clock is the time of the _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "Birthday party at three o'clock.",
              correct: "birthday party",
              wrong: ["school start", "Monday class"],
              distractorNotes: ["Giờ trường không nêu", "Không phải giờ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who is the youngest: Mai, Nam or Anna?",
              skillTag: "reading",
              topicTag,
              assessmentType: "inference",
              explanation: "Nam is six — nhỏ nhất (Mai 8, Anna 7).",
              correct: "Nam",
              wrong: ["Mai", "Anna"],
              distractorNotes: ["Mai 8 tuổi", "Anna 7 tuổi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "At the end, how does Mai feel?",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation: "We are happy!",
              correct: "Happy",
              wrong: ["Sad", "Angry"],
              distractorNotes: ["Trái nghĩa", "Không có"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-days-and-time",
      title: "Lesson 3: Days and Time in Reading",
      learningObjective:
        "Recognise days, today and o'clock times in Mai's birthday week text.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-days-learn",
          title: "Learn: Days and Time",
          instructions: "Read the text. Answer about days and time.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "School activities on Monday include reading _____ books.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "We read three books on Monday.",
              correct: "three",
              wrong: ["ten", "twenty"],
              distractorNotes: ["Số bạn", "Số bàn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The party is on _____ at three o'clock.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "On Tuesday at three o'clock.",
              correct: "Tuesday",
              wrong: ["Monday", "today"],
              distractorNotes: ["Hôm nay", "Chưa phải ngày tiệc"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-days-practice",
          title: "Practice: Today and Tomorrow",
          instructions: "Read again. Answer about the timeline.",
          sortOrder: 1,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Why is today special for Mai?",
              skillTag: "reading",
              topicTag,
              assessmentType: "inference",
              explanation: "I am eight tomorrow — sinh nhật sắp tới.",
              correct: "Her birthday is tomorrow.",
              wrong: ["It is Monday only.", "She reads twenty books."],
              distractorNotes: ["Chưa đủ — còn sinh nhật", "Đọc three books"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "In 'Today is special', today refers to _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "Today is Monday in the story.",
              correct: "Monday",
              wrong: ["Tuesday", "three o'clock"],
              distractorNotes: ["Ngày mai", "Giờ"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-days-check",
          title: "Check: Days and Time Quiz",
          instructions: "Read one more time. Harder questions.",
          sortOrder: 2,
          passage,
          difficulty: 0.38,
          questions: [
            buildMcq({
              questionText: "Which day does Mai read books at school?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "At school on Monday.",
              correct: "Monday",
              wrong: ["Tuesday", "birthday only"],
              distractorNotes: ["Ngày tiệc", "Cả tuần"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Order the days: (1) birthday (2) today in story",
              skillTag: "reading",
              topicTag,
              assessmentType: "sequencing",
              explanation: "Today Monday (2) trước birthday Tuesday (1).",
              correct: "2 → 1",
              wrong: ["1 → 2", "At the same time"],
              distractorNotes: ["Sinh nhật sau hôm nay", "Không cùng ngày"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-days-apply",
          title: "Apply: Match Days to Events",
          instructions: "Match each day or time to an event from the text.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match days and times to events.",
              skillTag: "reading",
              topicTag,
              explanation: "Monday=read books; Tuesday=party; three o'clock=party time.",
              pairs: [
                { left: "Monday", right: "read three books at school" },
                { left: "Tuesday", right: "Mai's birthday party" },
                { left: "three o'clock", right: "party start time" },
                { left: "today (in story)", right: "Monday" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-days-review",
          title: "Review: Days and Time Mix",
          instructions: "Find days and times in the text.",
          sortOrder: 4,
          passage,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Mai's birthday is on _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Tuesday is my birthday!",
              correct: "Tuesday",
              wrong: ["Monday", "ten"],
              distractorNotes: ["Hôm nay", "Số"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The text is mainly about _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation: "Mai's birthday week — số, ngày và thời gian.",
              correct: "Mai's birthday week with numbers and days",
              wrong: ["Mai's family photo only", "Animals at the zoo"],
              distractorNotes: ["Unit 1 topic", "Không có trong bài"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Ten friends come on the day of the _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "inference",
              explanation: "Ten friends at birthday party on Tuesday.",
              correct: "birthday party",
              wrong: ["Monday school", "twenty desks"],
              distractorNotes: ["Ngày đọc sách", "Số bàn"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
