/** Starters U2 — speaking lessons (3 × 5 exercises; only Check is AI). */

const BIRTHDAY_WEEK_SCENE =
  "Mai's classroom on Monday. Mai is eight. Her brother Nam is six. Her friend Anna is seven. Tomorrow is Tuesday — Mai's birthday. The party will be at three o'clock. Ten friends will come.";

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [ageCheck, partyCheck, numbersCheck] = speakingChecks;

  return [
    {
      slug: "speaking-age-and-days",
      title: "Lesson 1: Talk About Age and Days",
      learningObjective:
        "Answer simple questions about age and days with short phrases.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-age-learn",
          title: "Learn: What to Say About Age",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { sceneDescription: BIRTHDAY_WEEK_SCENE },
          questions: [
            buildMcq({
              questionText: "Someone asks: How old are you? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I am eight. — trả lời tuổi.",
              correct: "I am eight.",
              wrong: ["I have eight.", "Eight friends."],
              distractorNotes: ["Have = số lượng", "Số bạn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Someone asks: What day is today? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Today is Monday. — nói ngày.",
              correct: "Today is Monday.",
              wrong: ["Monday today is.", "I am Monday."],
              distractorNotes: ["Sai thứ tự", "Sai nghĩa"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-age-practice",
          title: "Practice: Age and Day Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { sceneDescription: BIRTHDAY_WEEK_SCENE },
          questions: [
            buildMcq({
              questionText: "Teacher asks: How old is Nam? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "He is six. — tuổi Nam.",
              correct: "He is six.",
              wrong: ["He has six.", "She is six."],
              distractorNotes: ["Have = số lượng", "Nam là boy"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Friend asks: When is your birthday? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "On Tuesday. / My birthday is on Tuesday.",
              correct: "On Tuesday.",
              wrong: ["At Tuesday.", "Three o'clock."],
              distractorNotes: ["At + giờ", "Giờ tiệc"],
              difficultyRating: 2,
            }),
          ],
        }),
        ageCheck,
        buildExercise({
          slug: "speaking-age-apply",
          title: "Apply: Quick Age Replies",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Anna asks: How old are you today? (birthday) You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I am eight today! — sinh nhật.",
              correct: "I am eight today!",
              wrong: ["I have eight today.", "Eight o'clock today."],
              distractorNotes: ["Have = số lượng", "Giờ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You want to say tomorrow is Tuesday. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Tomorrow is Tuesday.",
              correct: "Tomorrow is Tuesday.",
              wrong: ["Tuesday is tomorrow is.", "I am Tuesday tomorrow."],
              distractorNotes: ["Sai thứ tự", "Sai nghĩa"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-age-review",
          title: "Review: Age and Days Speaking",
          instructions: "Choose the best spoken reply.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Introduce Anna's age. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "She is seven. — tuổi Anna.",
              correct: "She is seven.",
              wrong: ["She has seven.", "He is seven."],
              distractorNotes: ["Have = số lượng", "Anna là girl"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say how many books you read. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Three books. / I read three books.",
              correct: "I read three books.",
              wrong: ["I am three books.", "Three is Monday."],
              distractorNotes: ["Sai nghĩa", "Trộn số và ngày"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Teacher asks: How many pencils? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Five. / I have five pencils.",
              correct: "I have five pencils.",
              wrong: ["I am five.", "Five o'clock."],
              distractorNotes: ["Tuổi", "Giờ"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-birthday-party",
      title: "Lesson 2: Talk About the Birthday Party",
      learningObjective:
        "Answer questions about Mai's birthday party using numbers and time.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-party-learn",
          title: "Learn: Birthday Party Phrases",
          instructions: "Read the scene description. Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { sceneDescription: BIRTHDAY_WEEK_SCENE },
          questions: [
            buildMcq({
              questionText: "You wish Mai happy birthday. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Happy birthday, Mai! — lời chúc.",
              correct: "Happy birthday, Mai!",
              wrong: ["Happy Monday, Mai!", "Birthday happy Mai."],
              distractorNotes: ["Sai ngày", "Sai thứ tự"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The party is at three _____. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "At three o'clock.",
              correct: "o'clock.",
              wrong: ["Monday.", "friends."],
              distractorNotes: ["Ngày", "Số lượng"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-party-practice",
          title: "Practice: Party Questions",
          instructions: "Choose what you would say at the party.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { sceneDescription: BIRTHDAY_WEEK_SCENE },
          questions: [
            buildMcq({
              questionText: "Anna asks: How many friends are here? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Ten friends. — số lượng bạn.",
              correct: "Ten friends.",
              wrong: ["I am ten.", "At ten o'clock."],
              distractorNotes: ["Tuổi", "Giờ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Nam says the party starts at three o'clock. You repeat:",
              skillTag: "speaking",
              topicTag,
              explanation: "The party starts at three o'clock.",
              correct: "The party starts at three o'clock.",
              wrong: ["The party on three o'clock.", "Three party o'clock."],
              distractorNotes: ["On + ngày", "Sai cấu trúc"],
              difficultyRating: 2,
            }),
          ],
        }),
        partyCheck,
        buildExercise({
          slug: "speaking-party-apply",
          title: "Apply: Party Speaking",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "You tell Anna today is Tuesday. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Today is Tuesday.",
              correct: "Today is Tuesday.",
              wrong: ["Tuesday is today is.", "I am Tuesday."],
              distractorNotes: ["Sai thứ tự", "Sai nghĩa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You thank Anna for the birthday wish. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Thank you, Anna! — như trong script.",
              correct: "Thank you, Anna!",
              wrong: ["Birthday you, Anna!", "Anna thank you."],
              distractorNotes: ["Sai cấu trúc", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-party-review",
          title: "Review: Party Speaking Mix",
          instructions: "Choose the best phrase.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Say when the party is. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "At three o'clock on Tuesday.",
              correct: "At three o'clock on Tuesday.",
              wrong: ["On three o'clock at Tuesday.", "Three Tuesday o'clock."],
              distractorNotes: ["Sai giới từ", "Sai cấu trúc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How many friends at Mai's party? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Ten friends come to my party.",
              correct: "Ten friends come to my party.",
              wrong: ["I am ten friends.", "Ten o'clock friends."],
              distractorNotes: ["Sai nghĩa", "Trộn giờ và số"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "It is a great day! You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Today is Tuesday. It is a great day! — như Anna.",
              correct: "Today is Tuesday. It is a great day!",
              wrong: ["Ten is a great day.", "O'clock is great."],
              distractorNotes: ["Sai nghĩa", "Sai nghĩa"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-numbers-and-time",
      title: "Lesson 3: Numbers and Time Speaking",
      learningObjective:
        "Choose and say appropriate short replies about numbers and time.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-numbers-learn",
          title: "Learn: Number and Time Replies",
          instructions: "Choose the best reply in each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Teacher asks: How many books? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Three books. / I have three books.",
              correct: "Three books.",
              wrong: ["I am three.", "Three o'clock."],
              distractorNotes: ["Tuổi", "Giờ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Friend asks: What time is the party? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "At three o'clock.",
              correct: "At three o'clock.",
              wrong: ["On three o'clock.", "Three friends."],
              distractorNotes: ["On + ngày", "Số lượng"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-numbers-practice",
          title: "Practice: More Number Situations",
          instructions: "Choose what you would say.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Examiner: How many desks in your class? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Twenty desks. — từ bài đọc.",
              correct: "Twenty desks.",
              wrong: ["I am twenty.", "Twenty o'clock."],
              distractorNotes: ["Tuổi", "Giờ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You count: one, two, three, four, _____. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Five — thứ tự đếm.",
              correct: "five",
              wrong: ["Monday", "birthday"],
              distractorNotes: ["Ngày", "Sự kiện"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You finish talking about numbers happily. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "We are happy! — kết thúc tích cực.",
              correct: "We are happy!",
              wrong: ["Ten is happy.", "O'clock happy."],
              distractorNotes: ["Sai nghĩa", "Sai nghĩa"],
              difficultyRating: 2,
            }),
          ],
        }),
        numbersCheck,
        buildExercise({
          slug: "speaking-numbers-apply",
          title: "Apply: Quick Number Replies",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Someone says: Nice party! You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Thank you! — phản hồi lịch sự.",
              correct: "Thank you!",
              wrong: ["Ten friends.", "Three o'clock."],
              distractorNotes: ["Không trả lời lời khen", "Không phải câu trả lời phù hợp"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Teacher points to the clock at three. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "It is three o'clock.",
              correct: "It is three o'clock.",
              wrong: ["It is three Monday.", "Three is it."],
              distractorNotes: ["Trộn ngày", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-numbers-review",
          title: "Review: Numbers Speaking Mix",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "How old is Anna? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "She is seven.",
              correct: "She is seven.",
              wrong: ["She has seven.", "He is seven."],
              distractorNotes: ["Have = số lượng", "Anna là girl"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say one sentence about today. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Today is Monday. — mẫu câu ngày.",
              correct: "Today is Monday.",
              wrong: ["Monday is I.", "Today am Monday."],
              distractorNotes: ["Sai nghĩa", "Sai ngữ pháp"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Your brother is six. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "He is six. / My brother is six.",
              correct: "He is six.",
              wrong: ["She is six.", "He six is."],
              distractorNotes: ["Brother dùng he", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
