/** Starters U2 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-numbers-one-to-five",
      title: "Lesson 1: Numbers One to Five",
      learningObjective:
        "Recognise and use one, two, three, four and five in short sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-numbers-learn",
          title: "Learn: Numbers 1–5",
          instructions: "Read each sentence. Choose the best number.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "I have _____ brother. His name is Nam.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "One (một) — Mai có một anh trai trong unit.",
              correct: "one",
              wrong: ["two", "ten"],
              distractorNotes: ["Hai anh trai — không đúng câu chuyện Mai", "Quá nhiều"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "One plus one is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Two (hai) — 1 + 1 = 2.",
              correct: "two",
              wrong: ["three", "five"],
              distractorNotes: ["Ba — 1+1 không bằng 3", "Năm — quá lớn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mai reads _____ books at school on Monday.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Three (ba) — bài đọc: we read three books.",
              correct: "three",
              wrong: ["two", "twenty"],
              distractorNotes: ["Hai — không khớp bài đọc", "Hai mươi — quá nhiều"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which number comes after three?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Four (bốn) — thứ tự: one, two, three, four, five.",
              correct: "four",
              wrong: ["two", "ten"],
              distractorNotes: ["Đứng trước three", "Nhảy quá xa"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-numbers-practice",
          title: "Practice: Match Numbers 1–5",
          instructions: "Match each number to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the numbers to their values.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mỗi số khớp giá trị đếm. three và five hay bị đảo.",
              pairs: [
                { left: "one", right: "1" },
                { left: "two", right: "2" },
                { left: "three", right: "3" },
                { left: "four", right: "4" },
                { left: "five", right: "5" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-numbers-check",
          title: "Check: Numbers 1–5 Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "I have _____ pencils in my bag.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Five (năm) — câu mẫu unit: I have five pencils.",
              correct: "five",
              wrong: ["one", "twenty"],
              distractorNotes: ["Một — quá ít cho câu thường gặp", "Hai mươi — quá nhiều"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which number is between two and four?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Three (ba) — 2, 3, 4.",
              correct: "three",
              wrong: ["one", "five"],
              distractorNotes: ["Đứng trước two", "Đứng sau four"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Count: one, two, three, _____, five.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Four (bốn) — thứ tự đếm cơ bản.",
              correct: "four",
              wrong: ["ten", "two"],
              distractorNotes: ["Nhảy tới mười", "Đã nói two rồi"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-numbers-apply",
          title: "Apply: Numbers in Sentences",
          instructions: "Complete each sentence with the correct number.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: I have [0] brother. | She has [1] books. | We read [2] books.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "one (một anh trai); two (hai quyển); three (ba quyển ở trường).",
              template: "I have [0] brother. She has [1] books. We read [2] books.",
              correctAnswers: ["one", "two", "three"],
              acceptableAnswers: [
                ["one", "One"],
                ["two", "Two"],
                ["three", "Three"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-numbers-review",
          title: "Review: Numbers 1–5 Mix",
          instructions: "Mixed review. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "The smallest number here is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "One (1) là số nhỏ nhất trong nhóm 1–5.",
              correct: "one",
              wrong: ["five", "three"],
              distractorNotes: ["Lớn nhất trong nhóm", "Ở giữa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Two plus three equals _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Five (năm) — 2 + 3 = 5.",
              correct: "five",
              wrong: ["four", "one"],
              distractorNotes: ["2+3 không bằng 4", "Quá nhỏ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word is a number, not a day?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Four là số. Monday và Tuesday là ngày.",
              correct: "four",
              wrong: ["Monday", "Tuesday"],
              distractorNotes: ["Tên ngày", "Tên ngày"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-ten-twenty-time",
      title: "Lesson 2: Ten, Twenty and Time",
      learningObjective:
        "Recognise ten, twenty, o'clock, today and birthday in context.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-time-learn",
          title: "Learn: Bigger Numbers and Time",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "_____ friends come to Mai's party.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ten (mười) — bài đọc: Ten friends will come.",
              correct: "ten",
              wrong: ["two", "three"],
              distractorNotes: ["Quá ít cho bữa tiệc", "Ba — không khớp bài"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Our class has _____ desks.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Twenty (hai mươi) — bài đọc: twenty desks.",
              correct: "twenty",
              wrong: ["ten", "five"],
              distractorNotes: ["Mười — ít hơn trong bài", "Năm — quá ít"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The party is at three _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "O'clock (giờ) đi sau số để chỉ thời gian.",
              correct: "o'clock",
              wrong: ["birthday", "Monday"],
              distractorNotes: ["Sự kiện, không phải đơn vị giờ", "Ngày, không phải giờ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ is my birthday!",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Today (hôm nay) — Today is my birthday!",
              correct: "Today",
              wrong: ["Tuesday", "ten"],
              distractorNotes: ["Ngày cụ thể — câu dùng today", "Số, không phải thời gian"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-time-practice",
          title: "Practice: Match Time Words",
          instructions: "Match each word to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match numbers and time words to their meanings.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ten/twenty là số; o'clock chỉ giờ; birthday là sinh nhật.",
              pairs: [
                { left: "ten", right: "10" },
                { left: "twenty", right: "20" },
                { left: "o'clock", right: "used after a number for time" },
                { left: "birthday", right: "the day you were born" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-time-check",
          title: "Check: Time Words Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Happy _____, Mai!",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Birthday (sinh nhật) — Happy birthday!",
              correct: "birthday",
              wrong: ["Monday", "o'clock"],
              distractorNotes: ["Ngày thường", "Đơn vị giờ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which number is bigger: ten or twenty?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Twenty (20) lớn hơn ten (10).",
              correct: "twenty",
              wrong: ["ten", "five"],
              distractorNotes: ["Nhỏ hơn twenty", "Không nằm trong cặp so sánh"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "School starts at eight _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "O'clock — eight o'clock chỉ giờ.",
              correct: "o'clock",
              wrong: ["birthday", "today"],
              distractorNotes: ["Sự kiện", "Hôm nay — không chỉ giờ"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-time-apply",
          title: "Apply: Time in Sentences",
          instructions: "Complete each sentence with the correct word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] is Monday. | The party is at three [1]. | [2] friends will come.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Today; o'clock; ten — theo bài Mai's Birthday Week.",
              template: "[0] is Monday. The party is at three [1]. [2] friends will come.",
              correctAnswers: ["Today", "o'clock", "ten"],
              acceptableAnswers: [
                ["Today", "today"],
                ["o'clock", "O'clock"],
                ["ten", "Ten"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-time-review",
          title: "Review: Numbers and Time Mix",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Mai's class has how many desks?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Twenty desks — từ bài đọc unit.",
              correct: "twenty",
              wrong: ["ten", "three"],
              distractorNotes: ["Số bạn ở tiệc", "Số sách đọc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word means 'hôm nay'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Today = hôm nay.",
              correct: "today",
              wrong: ["Tuesday", "birthday"],
              distractorNotes: ["Thứ Ba", "Sinh nhật"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which phrase tells the time?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Three o'clock chỉ giờ. Ten friends nói số lượng.",
              correct: "three o'clock",
              wrong: ["ten friends", "twenty desks"],
              distractorNotes: ["Số lượng người", "Số lượng đồ vật"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-days-of-the-week",
      title: "Lesson 3: Days of the Week",
      learningObjective:
        "Recognise Monday, Tuesday, today and birthday in Mai's week.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-days-learn",
          title: "Learn: Monday and Tuesday",
          instructions: "Read each clue. Choose the day word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "The first day in Mai's story is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Monday (thứ Hai) — Today is Monday.",
              correct: "Monday",
              wrong: ["Tuesday", "today"],
              distractorNotes: ["Ngày hôm sau", "Từ chung, không phải tên ngày"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mai's birthday is on _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Tuesday (thứ Ba) — birthday on Tuesday.",
              correct: "Tuesday",
              wrong: ["Monday", "ten"],
              distractorNotes: ["Hôm nay trong bài", "Số, không phải ngày"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Tomorrow after Monday is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Tuesday — thứ tự ngày trong tuần.",
              correct: "Tuesday",
              wrong: ["Monday", "birthday"],
              distractorNotes: ["Hôm nay", "Sự kiện, không phải tên ngày"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ is a special day when you get one year older.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Birthday (sinh nhật) — ngày thêm tuổi.",
              correct: "birthday",
              wrong: ["Monday", "o'clock"],
              distractorNotes: ["Ngày thường", "Đơn vị giờ"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-days-practice",
          title: "Practice: Match Days and Events",
          instructions: "Match each word to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match days and time words to their meanings.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Monday/Tuesday là ngày; today = hôm nay; birthday = sinh nhật.",
              pairs: [
                { left: "Monday", right: "the first day in Mai's story" },
                { left: "Tuesday", right: "Mai's birthday day" },
                { left: "today", right: "this day now" },
                { left: "birthday", right: "a day you celebrate your age" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-days-check",
          title: "Check: Days Quiz",
          instructions: "Choose the best answer. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Today is Monday. Tomorrow is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Tuesday — ngày liền sau Monday.",
              correct: "Tuesday",
              wrong: ["Monday", "ten"],
              distractorNotes: ["Cùng ngày", "Số"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which day comes BEFORE Tuesday?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Monday đứng trước Tuesday.",
              correct: "Monday",
              wrong: ["Tuesday", "birthday"],
              distractorNotes: ["Cùng ngày hoặc sau", "Sự kiện"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The party is on Tuesday at three _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "O'clock — chỉ giờ sau số.",
              correct: "o'clock",
              wrong: ["Monday", "today"],
              distractorNotes: ["Ngày", "Hôm nay"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-days-apply",
          title: "Apply: Days in Context",
          instructions: "Complete the sentences with day and time words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] is Monday. | My [1] is on Tuesday. | [2] is special!",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Today; birthday; Today — theo câu chuyện Mai.",
              template: "[0] is Monday. My [1] is on Tuesday. [2] is special!",
              correctAnswers: ["Today", "birthday", "Today"],
              acceptableAnswers: [
                ["Today", "today"],
                ["birthday", "Birthday"],
                ["Today", "today"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-days-review",
          title: "Review: Days and Time Mix",
          instructions: "Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Mai reads three books on _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Monday — At school on Monday.",
              correct: "Monday",
              wrong: ["Tuesday", "ten"],
              distractorNotes: ["Ngày sinh nhật", "Số"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word is NOT a day of the week?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Birthday là sự kiện. Monday và Tuesday là ngày.",
              correct: "birthday",
              wrong: ["Monday", "Tuesday"],
              distractorNotes: ["Ngày trong tuần", "Ngày trong tuần"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How many friends come on Tuesday?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ten friends — từ bài đọc.",
              correct: "ten",
              wrong: ["three", "twenty"],
              distractorNotes: ["Số sách", "Số bàn"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
