/** Starters U2 — writing lessons (3 × 5 exercises; only Check is AI). */

export function writingLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  writingChecks,
  topicTag,
}) {
  const [ageDayCheck, birthdayCheck, numbersCheck] = writingChecks;

  return [
    {
      slug: "writing-age-and-days",
      title: "Lesson 1: Write About Age and Days",
      learningObjective:
        "Write short phrases about age and days of the week using unit vocabulary.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-age-learn",
          title: "Learn: Age and Day Frames",
          instructions: "Complete the sentences about age and days.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: I [0] eight. | [1] is Monday. | How [2] are you?",
              skillTag: "writing",
              topicTag,
              explanation: "am (I am); Today; old (How old).",
              template: "I [0] eight. [1] is Monday. How [2] are you?",
              correctAnswers: ["am", "Today", "old"],
              acceptableAnswers: [["am"], ["Today", "today"], ["old", "Old"]],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-age-practice",
          title: "Practice: Order Age Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: I / am / eight / years / old.",
              skillTag: "writing",
              topicTag,
              explanation: "I am eight years old. — viết tuổi.",
              words: ["I", "am", "eight", "years", "old."],
              correctOrder: [0, 1, 2, 3, 4],
            }),
            buildSentenceOrdering({
              questionText: "Make: Today / is / Monday.",
              skillTag: "writing",
              topicTag,
              explanation: "Today is Monday. — viết ngày.",
              words: ["Today", "is", "Monday."],
              correctOrder: [0, 1, 2],
              difficultyRating: 2,
            }),
          ],
        }),
        ageDayCheck,
        buildExercise({
          slug: "writing-age-apply",
          title: "Apply: Choose the Best Sentence",
          instructions: "Choose the best written sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best sentence about your age:",
              skillTag: "writing",
              topicTag,
              explanation: "I am eight. — đúng ngữ pháp Starters.",
              correct: "I am eight.",
              wrong: ["I eight am.", "Eight I am."],
              distractorNotes: ["Sai thứ tự từ", "Sai thứ tự từ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best sentence about today:",
              skillTag: "writing",
              topicTag,
              explanation: "Today is Monday. — mẫu viết ngày.",
              correct: "Today is Monday.",
              wrong: ["Monday is today is.", "Is today Monday."],
              distractorNotes: ["Sai thứ tự", "Thiếu cấu trúc câu"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-age-review",
          title: "Review: Age and Day Writing",
          instructions: "Complete the writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 4,
          questions: [
            buildGapFill({
              questionText: "Complete: How [0] is Nam? | He [1] six. | [2] is Tuesday.",
              skillTag: "writing",
              topicTag,
              explanation: "old; is; Tomorrow or Today — Tomorrow is Tuesday trong bài.",
              template: "How [0] is Nam? He [1] six. [2] is Tuesday.",
              correctAnswers: ["old", "is", "Tomorrow"],
              acceptableAnswers: [
                ["old", "Old"],
                ["is"],
                ["Tomorrow", "tomorrow", "Today", "today"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "writing-birthday-sentences",
      title: "Lesson 2: Write About Birthdays",
      learningObjective:
        "Write short sentences about birthdays, days and o'clock times.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-birthday-learn",
          title: "Learn: Birthday Writing Frames",
          instructions: "Complete each sentence about birthdays.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: My [0] is on Tuesday. | The party is at three [1]. | [2] friends will come.",
              skillTag: "writing",
              topicTag,
              explanation: "birthday; o'clock; Ten — theo bài Mai.",
              template: "My [0] is on Tuesday. The party is at three [1]. [2] friends will come.",
              correctAnswers: ["birthday", "o'clock", "Ten"],
              acceptableAnswers: [
                ["birthday", "Birthday"],
                ["o'clock", "O'clock"],
                ["Ten", "ten"],
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-birthday-practice",
          title: "Practice: Order Birthday Sentences",
          instructions: "Put words in order to make sentences.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Happy / birthday, / Mai!",
              skillTag: "writing",
              topicTag,
              explanation: "Happy birthday, Mai! — lời chúc.",
              words: ["Happy", "birthday,", "Mai!"],
              correctOrder: [0, 1, 2],
            }),
            buildSentenceOrdering({
              questionText: "Make: The / party / is / at / three / o'clock.",
              skillTag: "writing",
              topicTag,
              explanation: "The party is at three o'clock.",
              words: ["The", "party", "is", "at", "three", "o'clock."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        birthdayCheck,
        buildExercise({
          slug: "writing-birthday-apply",
          title: "Apply: More Birthday Frames",
          instructions: "Complete the writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] birthday, Anna! | [1] is my birthday. | I am [2] today!",
              skillTag: "writing",
              topicTag,
              explanation: "Happy; Today; eight — câu tiệc sinh nhật.",
              template: "[0] birthday, Anna! [1] is my birthday. I am [2] today!",
              correctAnswers: ["Happy", "Today", "eight"],
              acceptableAnswers: [
                ["Happy", "happy"],
                ["Today", "today"],
                ["eight", "Eight"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-birthday-review",
          title: "Review: Birthday Writing Quiz",
          instructions: "Choose the best sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best sentence about a birthday day:",
              skillTag: "writing",
              topicTag,
              explanation: "My birthday is on Tuesday. — on + ngày.",
              correct: "My birthday is on Tuesday.",
              wrong: ["My birthday at Tuesday.", "My birthday is Tuesday on."],
              distractorNotes: ["At + giờ", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best time phrase for a party:",
              skillTag: "writing",
              topicTag,
              explanation: "At three o'clock. — at + giờ.",
              correct: "At three o'clock.",
              wrong: ["On three o'clock.", "Three at o'clock."],
              distractorNotes: ["On + ngày", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence uses ten correctly?",
              skillTag: "writing",
              topicTag,
              explanation: "Ten friends come. — số lượng.",
              correct: "Ten friends come to my party.",
              wrong: ["I am ten friends.", "Ten is my birthday."],
              distractorNotes: ["Sai nghĩa", "Sai nghĩa"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "writing-numbers-and-time",
      title: "Lesson 3: Write With Numbers and Time",
      learningObjective:
        "Write short gap-fill frames and answers with numbers and time words.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-numbers-learn",
          title: "Learn: Number Writing Frames",
          instructions: "Complete sentences with numbers.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: I have [0] books. | [1] friends are here. | School starts at [2] o'clock.",
              skillTag: "writing",
              topicTag,
              explanation: "three; Ten; eight — số lượng và giờ.",
              template: "I have [0] books. [1] friends are here. School starts at [2] o'clock.",
              correctAnswers: ["three", "Ten", "eight"],
              acceptableAnswers: [
                ["three", "Three"],
                ["Ten", "ten"],
                ["eight", "Eight"],
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-numbers-practice",
          title: "Practice: Order Number Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: I / have / five / pencils.",
              skillTag: "writing",
              topicTag,
              explanation: "I have five pencils. — how many answer.",
              words: ["I", "have", "five", "pencils."],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: How / many / books / do / you / have?",
              skillTag: "writing",
              topicTag,
              explanation: "How many books do you have?",
              words: ["How", "many", "books", "do", "you", "have?"],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        numbersCheck,
        buildExercise({
          slug: "writing-numbers-apply",
          title: "Apply: Write With Numbers",
          instructions: "Complete the gap-fill writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: How [0] pencils? | I have [1]. | Our class has [2] desks.",
              skillTag: "writing",
              topicTag,
              explanation: "many; five; twenty — how many + số.",
              template: "How [0] pencils? I have [1]. Our class has [2] desks.",
              correctAnswers: ["many", "five", "twenty"],
              acceptableAnswers: [
                ["many", "Many"],
                ["five", "Five"],
                ["twenty", "Twenty"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-numbers-review",
          title: "Review: Numbers Writing Mix",
          instructions: "Choose or complete number writing frames.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best answer: How many friends?",
              skillTag: "writing",
              topicTag,
              explanation: "Ten friends. — trả lời số lượng.",
              correct: "Ten friends.",
              wrong: ["I am ten.", "Ten o'clock."],
              distractorNotes: ["Tuổi", "Giờ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Nam is six. Best written sentence:",
              skillTag: "writing",
              topicTag,
              explanation: "He is six. — viết tuổi người khác.",
              correct: "He is six.",
              wrong: ["He has six.", "Six he is."],
              distractorNotes: ["Have = số lượng", "Sai thứ tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which is correct?",
              skillTag: "writing",
              topicTag,
              explanation: "It is three o'clock. — viết giờ.",
              correct: "It is three o'clock.",
              wrong: ["It three is o'clock.", "Three is it o'clock."],
              distractorNotes: ["Sai thứ tự", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
