/** Starters U1 — listening lessons (3 × 5 exercises). */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptAtHome,
  listeningScriptAtSchool,
  listeningAnswerKeys,
  topicTag,
}) {
  const atHome = listeningScriptAtHome;
  const atSchool = listeningScriptAtSchool;
  const keysHome = listeningAnswerKeys.atHome;
  const keysSchool = listeningAnswerKeys.atSchool;

  return [
    {
      slug: "listening-introducing-friends",
      title: "Lesson 1: Introducing Friends",
      learningObjective:
        "Listen to a home conversation and identify names and relationships.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-home-learn",
          title: "Learn: Listen at Home",
          instructions: "Listen to the conversation. Choose the correct answer.",
          sortOrder: 0,
          script: atHome,
          answerKey: keysHome,
          questions: [
            buildMcq({
              questionText: "Who is the woman in the photo?",
              skillTag: "listening",
              topicTag,
              explanation: "Minh nói: This is my mother.",
              correct: "Minh's mother",
              wrong: ["Minh's sister", "Minh's teacher"],
              distractorNotes: ["Nữ nhưng không phải chị/em", "Không được nhắc"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What is the boy's name?",
              skillTag: "listening",
              topicTag,
              explanation: "Minh nói: His name is Duc.",
              correct: "Duc",
              wrong: ["Minh", "Lily"],
              distractorNotes: ["Tên người nói", "Tên bạn"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-home-practice",
          title: "Practice: More from At Home",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: atHome,
          answerKey: keysHome,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Who is Lily?",
              skillTag: "listening",
              topicTag,
              explanation: "She is my friend.",
              correct: "Minh's friend",
              wrong: ["Minh's sister", "Minh's mother"],
              distractorNotes: ["Minh nói no", "Đã xác định là mẹ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh says 'He is my brother.' Who is he?",
              skillTag: "listening",
              topicTag,
              explanation: "He = the boy — anh trai Duc của Minh.",
              correct: "Duc",
              wrong: ["Minh", "Lily"],
              distractorNotes: ["Minh đang nói", "Sẽ dùng she"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-home-check",
          title: "Check: At Home Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: atHome,
          answerKey: keysHome,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Is the girl Minh's sister?",
              skillTag: "listening",
              topicTag,
              explanation: "Is the girl your sister? — No. She is my friend.",
              correct: "No",
              wrong: ["Yes", "Maybe"],
              distractorNotes: ["Minh nói rõ No", "Câu trả lời rõ trong hội thoại"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How many people does Minh talk about (not counting himself)?",
              skillTag: "listening",
              topicTag,
              explanation: "Mother, brother Duc, friend Lily — ba người.",
              correct: "Three",
              wrong: ["Two", "Four"],
              distractorNotes: ["Thiếu một người", "Đếm cả examiner"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-home-apply",
          title: "Apply: Match At Home People",
          instructions: "Listen again. Match each name to their role.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: atHome, answerKey: keysHome },
          questions: [
            buildMatching({
              questionText: "Match names to relationships.",
              skillTag: "listening",
              topicTag,
              explanation: "Duc = brother; Lily = friend; woman = mother.",
              pairs: [
                { left: "Duc", right: "Minh's brother" },
                { left: "Lily", right: "Minh's friend" },
                { left: "The woman", right: "Minh's mother" },
                { left: "The boy", right: "He is my brother" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-home-review",
          title: "Review: At Home Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: atHome,
          answerKey: keysHome,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Who is Duc?",
              skillTag: "listening",
              topicTag,
              explanation: "He is my brother. His name is Duc.",
              correct: "Minh's brother",
              wrong: ["Minh's friend", "Minh's father"],
              distractorNotes: ["Lily là friend", "Không được nhắc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The examiner asks: Who is this? Minh says:",
              skillTag: "listening",
              topicTag,
              explanation: "Câu đầu: This is my mother.",
              correct: "This is my mother.",
              wrong: ["This is my sister.", "This is my friend."],
              distractorNotes: ["Chưa hỏi về em gái", "Bạn được nhắc sau"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Lily is a _____.",
              skillTag: "listening",
              topicTag,
              explanation: "She is my friend. Her name is Lily.",
              correct: "friend",
              wrong: ["sister", "mother"],
              distractorNotes: ["Minh nói no", "Đã là mẹ"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-at-school-focus",
      title: "Lesson 2: At School Dialogue",
      learningObjective:
        "Listen to a school conversation and identify family members.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-school-learn",
          title: "Learn: Listen at School",
          instructions: "Listen to the conversation at school. Answer the first questions.",
          sortOrder: 0,
          script: atSchool,
          answerKey: keysSchool,
          questions: [
            buildMcq({
              questionText: "Who is Lan?",
              skillTag: "listening",
              topicTag,
              explanation: "Hoa nói: She is my sister. Her name is Lan.",
              correct: "Hoa's sister",
              wrong: ["Hoa's friend", "Hoa's teacher"],
              distractorNotes: ["Thành viên gia đình được nêu", "Không được nhắc"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Who is the man?",
              skillTag: "listening",
              topicTag,
              explanation: "He is my father.",
              correct: "Hoa's father",
              wrong: ["Hoa's brother", "The teacher"],
              distractorNotes: ["Anh trai là boy", "Giáo viên hỏi câu hỏi"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-practice",
          title: "Practice: More from At School",
          instructions: "Listen again. Answer the next questions.",
          sortOrder: 1,
          script: atSchool,
          answerKey: keysSchool,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Is the boy Hoa's brother?",
              skillTag: "listening",
              topicTag,
              explanation: "Yes. He is my brother.",
              correct: "Yes",
              wrong: ["No", "Maybe"],
              distractorNotes: ["Hoa nói yes rõ ràng", "Câu trả lời rõ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Hoa says the brother is a _____.",
              skillTag: "listening",
              topicTag,
              explanation: "He is a boy.",
              correct: "boy",
              wrong: ["girl", "friend"],
              distractorNotes: ["Sai giới tính", "Gia đình, không phải bạn"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-check",
          title: "Check: School Listening Quiz",
          instructions: "Listen one more time. Choose carefully.",
          sortOrder: 2,
          script: atSchool,
          answerKey: keysSchool,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "What is the sister's name?",
              skillTag: "listening",
              topicTag,
              explanation: "Her name is Lan.",
              correct: "Lan",
              wrong: ["Hoa", "Anna"],
              distractorNotes: ["Tên người nói", "Tên từ bài đọc khác"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How many family members does Hoa talk about?",
              skillTag: "listening",
              topicTag,
              explanation: "Sister, father, brother — ba người.",
              correct: "Three",
              wrong: ["Two", "Four"],
              distractorNotes: ["Thiếu một người", "Đếm giáo viên"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-school-apply",
          title: "Apply: Match School Dialogue",
          instructions: "Listen again. Match each person to what Hoa says.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: atSchool, answerKey: keysSchool },
          questions: [
            buildMatching({
              questionText: "Match people to Hoa's words.",
              skillTag: "listening",
              topicTag,
              explanation: "Lan = sister; man = father; boy = brother.",
              pairs: [
                { left: "Lan", right: "She is my sister" },
                { left: "The man", right: "He is my father" },
                { left: "The boy", right: "He is my brother" },
                { left: "The brother", right: "He is a boy" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-school-review",
          title: "Review: School Dialogue Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: atSchool,
          answerKey: keysSchool,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Who is the girl with Hoa?",
              skillTag: "listening",
              topicTag,
              explanation: "Who is the girl with you? — She is my sister.",
              correct: "Hoa's sister",
              wrong: ["Hoa's friend", "Hoa's mother"],
              distractorNotes: ["Không phải bạn", "Không được nhắc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The teacher asks about the man. Hoa says he is her _____.",
              skillTag: "listening",
              topicTag,
              explanation: "He is my father.",
              correct: "father",
              wrong: ["brother", "friend"],
              distractorNotes: ["Anh trai là boy", "Không phải bạn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Hoa's brother is a _____.",
              skillTag: "listening",
              topicTag,
              explanation: "He is a boy.",
              correct: "boy",
              wrong: ["girl", "teacher"],
              distractorNotes: ["Sai giới tính", "Người lớn"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-home-review",
      title: "Lesson 3: Review At Home",
      learningObjective:
        "Review the at-home listening script and identify all people correctly.",
      estimatedMinutes: 18,
      exercises: [
        buildListeningExercise({
          slug: "listening-home-review-learn",
          title: "Learn: Listen at Home Again",
          instructions: "Listen to Minh at home. Answer the questions.",
          sortOrder: 0,
          script: atHome,
          answerKey: keysHome,
          questions: [
            buildMcq({
              questionText: "Who is the woman?",
              skillTag: "listening",
              topicTag,
              explanation: "This is my mother.",
              correct: "Minh's mother",
              wrong: ["Minh's sister", "Lily"],
              distractorNotes: [
                "Minh nói no với sister cho cô gái",
                "Lily là bạn",
              ],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What is the brother's name?",
              skillTag: "listening",
              topicTag,
              explanation: "His name is Duc.",
              correct: "Duc",
              wrong: ["Minh", "Lily"],
              distractorNotes: ["Tên người nói", "Tên bạn"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-home-review-practice",
          title: "Practice: Lily and Duc",
          instructions: "Listen again. Focus on the friend and brother.",
          sortOrder: 1,
          script: atHome,
          answerKey: keysHome,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Who is Lily?",
              skillTag: "listening",
              topicTag,
              explanation: "She is my friend.",
              correct: "Minh's friend",
              wrong: ["Minh's sister", "Minh's mother"],
              distractorNotes: ["Minh nói no", "Đã xác định là mẹ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh says 'No' when asked if the girl is his _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Is the girl your sister? — No.",
              correct: "sister",
              wrong: ["friend", "mother"],
              distractorNotes: [
                "Cô ấy là friend nhưng câu hỏi về sister",
                "Câu hỏi về sister",
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-home-review-check",
          title: "Check: At Home Review Quiz",
          instructions: "Listen one final time. Choose carefully.",
          sortOrder: 2,
          script: atHome,
          answerKey: keysHome,
          difficulty: 0.36,
          questions: [
            buildMcq({
              questionText: "Who is Duc?",
              skillTag: "listening",
              topicTag,
              explanation: "He is my brother. His name is Duc.",
              correct: "Minh's brother",
              wrong: ["Minh's friend", "Minh's father"],
              distractorNotes: ["Lily là friend", "Không được nhắc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Put in order: (1) mother (2) brother (3) friend",
              skillTag: "listening",
              topicTag,
              explanation: "Hội thoại: mẹ → anh Duc → bạn Lily.",
              correct: "1 → 2 → 3",
              wrong: ["2 → 1 → 3", "3 → 2 → 1"],
              distractorNotes: ["Mẹ đến trước", "Bạn ở cuối"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-home-review-apply",
          title: "Apply: Match At Home People",
          instructions: "Listen and match each name to their role.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: atHome, answerKey: keysHome },
          questions: [
            buildMatching({
              questionText: "Match names to relationships.",
              skillTag: "listening",
              topicTag,
              explanation: "Duc = brother; Lily = friend; woman = mother.",
              pairs: [
                { left: "Duc", right: "Minh's brother" },
                { left: "Lily", right: "Minh's friend" },
                { left: "The woman", right: "Minh's mother" },
                { left: "The boy", right: "He is my brother" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-home-review-final",
          title: "Review: Full At Home Recall",
          instructions: "Listen and answer — full review.",
          sortOrder: 4,
          script: atHome,
          answerKey: keysHome,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "The girl's name is _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Her name is Lily.",
              correct: "Lily",
              wrong: ["Lan", "Anna"],
              distractorNotes: ["Tên ở bài school", "Tên ở bài đọc"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh introduces his mother first. True or false?",
              skillTag: "listening",
              topicTag,
              explanation: "Câu đầu tiên về người: This is my mother — đúng.",
              correct: "True",
              wrong: ["False", "Not in the script"],
              distractorNotes: ["Thứ tự trong script là mẹ trước", "Mẹ được nhắc rõ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Brother and friend: which comes first in the dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Brother (Duc) trước, friend (Lily) sau.",
              correct: "Brother first",
              wrong: ["Friend first", "At the same time"],
              distractorNotes: ["Lily sau Duc", "Không cùng lúc"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
