/** Starters U1 — reading lessons (3 × 5 exercises). */

export function readingLessons({
  buildMcq,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMaiFamily,
  topicTag,
}) {
  const passage = passageMaiFamily;

  return [
    {
      slug: "reading-my-family-photo",
      title: "Lesson 1: My Family Photo",
      learningObjective:
        "Read a short text about Mai's family and answer questions about main idea and details.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-family-learn",
          title: "Learn: Read Mai's Family",
          instructions: "Read the text. Then answer the questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What is the main idea of the text?",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation:
                "Toàn bài Mai giới thiệu gia đình và bạn. Không nói về trường hay đồ ăn.",
              correct: "Mai introduces her family and friend.",
              wrong: ["Mai describes her school.", "Mai talks about her favourite food."],
              distractorNotes: [
                "Trường chỉ nhắc một lần",
                "Không có đồ ăn trong bài",
              ],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "How old is Mai's brother?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Bài viết: He is six.",
              correct: "Six years old",
              wrong: ["Eight years old", "Seven years old"],
              distractorNotes: ["Tuổi của Mai", "Số không có trong bài"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-family-practice",
          title: "Practice: More from the Text",
          instructions: "Read again. Answer about people in the text.",
          sortOrder: 1,
          passage,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "Why is Anna in the text?",
              skillTag: "reading",
              topicTag,
              assessmentType: "inference",
              explanation:
                "Anna được mô tả là bạn trong lớp, không phải thành viên gia đình.",
              correct: "She is Mai's friend from class.",
              wrong: ["She is Mai's sister.", "She is Mai's teacher."],
              distractorNotes: ["Là con gái nhưng không phải chị/em", "Vai trò người lớn không có"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "In 'Her eyes are brown', what does her refer to?",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "Her = mother trong câu trước.",
              correct: "Mai's mother",
              wrong: ["Mai's father", "Anna"],
              distractorNotes: ["Sẽ dùng his", "Được nhắc sau"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-family-check",
          title: "Check: Family Reading Quiz",
          instructions: "Read carefully. Choose the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText:
                "Put the ideas in order: (1) Mai tells her age (2) Mai describes parents (3) Mai mentions brother and friend",
              skillTag: "reading",
              topicTag,
              assessmentType: "sequencing",
              explanation: "Bài đi từ bản thân → bố mẹ → anh trai và bạn.",
              correct: "1 → 2 → 3",
              wrong: ["2 → 1 → 3", "3 → 2 → 1"],
              distractorNotes: ["Tuổi đến trước chi tiết bố mẹ", "Thứ tự ngược"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How many brothers does Mai have?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "I have one brother.",
              correct: "One",
              wrong: ["Two", "None"],
              distractorNotes: ["Chỉ Nam được nhắc", "Bài nói one brother"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-family-apply",
          title: "Apply: Match People to Facts",
          instructions: "Use the text. Match each person to a fact.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match people to facts from the text.",
              skillTag: "reading",
              topicTag,
              explanation:
                "Anna = girl in class; Nam = six; father = black hair; mother = brown eyes.",
              pairs: [
                { left: "Anna", right: "She is a girl in our class" },
                { left: "Nam", right: "He is six years old" },
                { left: "Mai's father", right: "His hair is black" },
                { left: "Mai's mother", right: "Her eyes are brown" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-family-review",
          title: "Review: Mai's Family Mix",
          instructions: "Read the text again. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "How old is Mai?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "I am eight years old.",
              correct: "Eight years old",
              wrong: ["Six years old", "Seven years old"],
              distractorNotes: ["Tuổi anh trai", "Không có trong bài"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "At the end, how does Mai feel?",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation: "We are happy!",
              correct: "Happy",
              wrong: ["Sad", "Angry"],
              distractorNotes: ["Trái nghĩa bài", "Không có trong bài"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who is Nam?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "His name is Nam. He is a boy. He is six — anh trai Mai.",
              correct: "Mai's brother",
              wrong: ["Mai's friend", "Mai's father"],
              distractorNotes: ["Anna là bạn", "Bố được mô tả tall"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-about-friends",
      title: "Lesson 2: Read About Friends",
      learningObjective:
        "Read about friends in Mai's family text and answer detail questions.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-friends-learn",
          title: "Learn: Read About Friends",
          instructions: "Read Mai's text. Answer about Anna and friends.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What is Anna's role in the text?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Anna là bạn của Mai: We have a friend. Her name is Anna.",
              correct: "Mai's friend",
              wrong: ["Mai's sister", "Mai's mother"],
              distractorNotes: ["Là con gái nhưng không phải chị/em", "Người lớn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Anna is a _____ in Mai's class.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "She is a girl in our class.",
              correct: "girl",
              wrong: ["boy", "teacher"],
              distractorNotes: ["Sai giới tính", "Không có trong bài"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-friends-practice",
          title: "Practice: Friends in Context",
          instructions: "Read again. Answer about people and words.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "In 'He is a boy', who is he?",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "He là Nam — anh trai của Mai.",
              correct: "Nam, Mai's brother",
              wrong: ["Mai's father", "Anna"],
              distractorNotes: ["Ngữ cảnh khác", "Sẽ dùng she"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Why is Anna not in Mai's family photo as a sister?",
              skillTag: "reading",
              topicTag,
              assessmentType: "inference",
              explanation: "Bài nói friend from class, không phải sister.",
              correct: "She is a friend, not a sister.",
              wrong: ["She is Mai's mother.", "She is not in the photo."],
              distractorNotes: ["Sai quan hệ", "Anna được nhắc trong bài"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-friends-check",
          title: "Check: Friends Reading Quiz",
          instructions: "Read carefully. Choose the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.35,
          questions: [
            buildMcq({
              questionText: "Who is the boy in the text?",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation: "Nam là boy, anh trai sáu tuổi của Mai.",
              correct: "Nam, Mai's six-year-old brother",
              wrong: ["Mai's father", "Anna's brother"],
              distractorNotes: ["Bố tall, không six", "Anna là bạn gái"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText:
                "Order: (1) parents (2) brother (3) friend — how does Mai tell the story?",
              skillTag: "reading",
              topicTag,
              assessmentType: "sequencing",
              explanation: "Mai mô tả bố mẹ trước, rồi anh trai, rồi bạn Anna.",
              correct: "1 → 2 → 3",
              wrong: ["3 → 1 → 2", "2 → 3 → 1"],
              distractorNotes: ["Bạn đến sau gia đình", "Bố mẹ đến trước"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-friends-apply",
          title: "Apply: Match Friends to Facts",
          instructions: "Use the text. Match each person to a fact.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match people to facts from the text.",
              skillTag: "reading",
              topicTag,
              explanation:
                "Anna = girl in class; Nam = six; father = black hair; mother = brown eyes.",
              pairs: [
                { left: "Anna", right: "She is a girl in our class" },
                { left: "Nam", right: "He is six years old" },
                { left: "Mai's father", right: "His hair is black" },
                { left: "Mai's mother", right: "Her eyes are brown" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-friends-review",
          title: "Review: Friends Reading Mix",
          instructions: "Read and answer — mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.33,
          questions: [
            buildMcq({
              questionText: "Anna's name is _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Her name is Anna.",
              correct: "Anna",
              wrong: ["Lily", "Linh"],
              distractorNotes: ["Tên khác unit", "Tên khác unit"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai and Anna are both _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "inference",
              explanation: "Anna is a girl in our class — cùng lớp với Mai.",
              correct: "in the same class",
              wrong: ["sisters", "brothers"],
              distractorNotes: ["Không phải chị/em", "Cả hai là con gái"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We have a friend. Her name is _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Câu trong bài: Her name is Anna.",
              correct: "Anna",
              wrong: ["Nam", "Mai"],
              distractorNotes: ["Anh trai", "Người kể chuyện"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-more-details",
      title: "Lesson 3: More Details from the Text",
      learningObjective:
        "Find specific details about hair, eyes, age and feelings in Mai's text.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-details-learn",
          title: "Learn: More Details",
          instructions: "Read the text. Answer detail questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What colour is Mai's mother's eyes?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Her eyes are brown — her = mother.",
              correct: "Brown",
              wrong: ["Black", "Blue"],
              distractorNotes: ["Màu tóc bố", "Không có trong bài"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "How old is Nam?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "He is six.",
              correct: "Six years old",
              wrong: ["Eight years old", "Seven years old"],
              distractorNotes: ["Tuổi Mai", "Không có trong bài"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-details-practice",
          title: "Practice: Hair and Eyes",
          instructions: "Read again. Answer about descriptions.",
          sortOrder: 1,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "Whose hair is black?",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "His hair is black — his = father.",
              correct: "Mai's father's",
              wrong: ["Mai's mother's", "Anna's"],
              distractorNotes: [
                "Mẹ có mắt nâu, không nói tóc đen",
                "Không mô tả",
              ],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai says her mother is _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "inference",
              explanation: "My mother is kind.",
              correct: "kind",
              wrong: ["tall", "six"],
              distractorNotes: ["Bố tall", "Nam six"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-details-check",
          title: "Check: Detail Reading Quiz",
          instructions: "Read one more time. Harder questions.",
          sortOrder: 2,
          passage,
          difficulty: 0.38,
          questions: [
            buildMcq({
              questionText: "How many brothers does Mai have?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "I have one brother.",
              correct: "One",
              wrong: ["Two", "None"],
              distractorNotes: ["Chỉ Nam", "Bài nói one"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "At the end, how does Mai feel?",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation: "We are happy!",
              correct: "Happy",
              wrong: ["Sad", "Angry"],
              distractorNotes: ["Trái nghĩa", "Không có"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-details-apply",
          title: "Apply: Match Details to People",
          instructions: "Match each description to the correct person.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match descriptions from the text.",
              skillTag: "reading",
              topicTag,
              explanation: "Mai = eight; father = tall; mother = kind; Nam = boy.",
              pairs: [
                { left: "Mai", right: "eight years old" },
                { left: "Father", right: "tall" },
                { left: "Mother", right: "kind" },
                { left: "Nam", right: "a boy" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-details-review",
          title: "Review: Details Mix",
          instructions: "Find details in the text.",
          sortOrder: 4,
          passage,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Mai's father is _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "My father is tall.",
              correct: "tall",
              wrong: ["kind", "six"],
              distractorNotes: ["Mẹ kind", "Nam six"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Nam is a _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "He is a boy.",
              correct: "boy",
              wrong: ["girl", "friend"],
              distractorNotes: ["Con gái", "Anna là friend"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The text is a _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation: "This is my family photo — giới thiệu ảnh gia đình.",
              correct: "family introduction",
              wrong: ["school story", "weather report"],
              distractorNotes: ["Không phải chủ đề", "Không có"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
