/** Starters U1 — speaking lessons (3 × 5 exercises; only Check is AI). */

const FAMILY_PICTURE =
  "A mother, father, boy, girl and friend in a garden.";

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [familyCheck, pictureCheck, situationalCheck] = speakingChecks;

  return [
    {
      slug: "speaking-talk-about-family",
      title: "Lesson 1: Talk About Your Family",
      learningObjective:
        "Answer simple questions about yourself, family and friends with short phrases.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-family-learn",
          title: "Learn: What to Say About Family",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { pictureDescription: FAMILY_PICTURE },
          questions: [
            buildMcq({
              questionText: "Someone asks: What is your name? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "My name is Mai. — giới thiệu tên đầy đủ.",
              correct: "My name is Mai.",
              wrong: ["Name Mai.", "I name is Mai."],
              distractorNotes: ["Quá ngắn", "Sai ngữ pháp"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Someone asks: How old are you? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I am eight. — I + am + tuổi.",
              correct: "I am eight.",
              wrong: ["I is eight.", "He is eight."],
              distractorNotes: ["Sai động từ", "Nói về người khác"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-family-practice",
          title: "Practice: Family Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { pictureDescription: FAMILY_PICTURE },
          questions: [
            buildMcq({
              questionText: "Who is she? (your mother) You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "She is my mother.",
              correct: "She is my mother.",
              wrong: ["He is my mother.", "She is my brother."],
              distractorNotes: ["Mẹ dùng she", "Brother là nam"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who is he? (your father) You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "He is my father.",
              correct: "He is my father.",
              wrong: ["She is my father.", "He is my sister."],
              distractorNotes: ["Bố dùng he", "Sister là nữ"],
              difficultyRating: 2,
            }),
          ],
        }),
        familyCheck,
        buildExercise({
          slug: "speaking-family-apply",
          title: "Apply: Quick Family Replies",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Friend asks: Is she your sister? (No — she is your friend) You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "No. She is my friend.",
              correct: "No. She is my friend.",
              wrong: ["Yes. She is my sister.", "No. He is my friend."],
              distractorNotes: ["Sai câu trả lời", "Friend là she"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You want to say your hair is black. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "My hair is black. — my hair + is.",
              correct: "My hair is black.",
              wrong: ["Hair my is black.", "I hair black."],
              distractorNotes: ["Sai thứ tự", "Không đủ câu"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-family-review",
          title: "Review: Family Speaking Mix",
          instructions: "Choose the best spoken reply.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Introduce your brother Nam. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "He is my brother. His name is Nam.",
              correct: "He is my brother. His name is Nam.",
              wrong: ["She is my brother.", "He is my sister."],
              distractorNotes: ["Brother dùng he", "Sister là nữ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say you are happy with your family. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "We are happy! — như cuối bài đọc Mai.",
              correct: "We are happy!",
              wrong: ["I am mother.", "They is happy."],
              distractorNotes: ["Sai ngữ pháp", "Sai động từ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Teacher asks: Who is your friend? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Anna is my friend. hoặc She is my friend.",
              correct: "She is my friend.",
              wrong: ["He is my friend.", "She is my sister."],
              distractorNotes: ["Nếu bạn nữ dùng she", "Sister khác friend"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-picture-who-is-who",
      title: "Lesson 2: Picture — Who Is Who?",
      learningObjective:
        "Identify and name family and friends in a picture using short phrases.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-picture-learn",
          title: "Learn: Who Is in the Picture?",
          instructions: "Imagine a family picture. Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { pictureDescription: FAMILY_PICTURE },
          questions: [
            buildMcq({
              questionText: "The tall man is the _____.",
              skillTag: "speaking",
              topicTag,
              explanation: "Trong ảnh gia đình, người đàn ông lớn thường là father.",
              correct: "father",
              wrong: ["brother", "friend"],
              distractorNotes: [
                "Con trai trẻ, không phải người đàn ông lớn",
                "Thường không phải người đàn ông lớn",
              ],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The young girl in the family is the _____.",
              skillTag: "speaking",
              topicTag,
              explanation: "Young girl in family → sister.",
              correct: "sister",
              wrong: ["mother", "friend"],
              distractorNotes: ["Người lớn", "Bạn từ lớp"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-picture-practice",
          title: "Practice: Point and Name",
          instructions: "Choose what you would say for each person.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { pictureDescription: FAMILY_PICTURE },
          questions: [
            buildMcq({
              questionText: "Point to your mother. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "She is my mother.",
              correct: "She is my mother.",
              wrong: ["He is my mother.", "She is my brother."],
              distractorNotes: ["Mẹ là she", "Brother là nam"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Point to a boy who is your brother. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "He is my brother.",
              correct: "He is my brother.",
              wrong: ["She is my sister.", "He is my friend."],
              distractorNotes: ["Dạng nữ", "Sai quan hệ nếu là brother"],
              difficultyRating: 2,
            }),
          ],
        }),
        pictureCheck,
        buildExercise({
          slug: "speaking-picture-apply",
          title: "Apply: Picture Who Is Who",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Teacher points to a girl from class. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "She is my friend — from class, not sister.",
              correct: "She is my friend.",
              wrong: ["She is my sister.", "He is my friend."],
              distractorNotes: [
                "Bạn cùng lớp thường là friend",
                "Con gái cần she",
              ],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You point to yourself and your age. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I am eight. — giới thiệu tuổi bản thân.",
              correct: "I am eight.",
              wrong: ["He is eight.", "I is eight."],
              distractorNotes: ["Nói về người khác", "Sai động từ với I"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-picture-review",
          title: "Review: Picture Speaking Mix",
          instructions: "Choose the best phrase.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Point to your father. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "He is my father.",
              correct: "He is my father.",
              wrong: ["She is my father.", "He is my mother."],
              distractorNotes: ["Bố dùng he", "Mother là nữ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The woman in the photo is not your friend. She is your _____.",
              skillTag: "speaking",
              topicTag,
              explanation: "Woman in family photo → mother or sister; mother phổ biến hơn.",
              correct: "mother",
              wrong: ["boy", "hair"],
              distractorNotes: ["Sai giới tính/từ loại", "Không phải người"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Ask about a person: _____ is he?",
              skillTag: "speaking",
              topicTag,
              explanation: "Who is he? — hỏi về người.",
              correct: "Who",
              wrong: ["What", "Where"],
              distractorNotes: ["Hỏi vật", "Hỏi nơi"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-situational-replies",
      title: "Lesson 3: More Situational Replies",
      learningObjective:
        "Choose and say appropriate short replies in family and friend situations.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-situational-learn",
          title: "Learn: Situational Replies",
          instructions: "Choose the best reply in each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Friend asks: Who is she? (your sister) You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "She is my sister.",
              correct: "She is my sister.",
              wrong: ["He is my sister.", "She is my friend."],
              distractorNotes: ["Sister là she", "Sai nếu là sister"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Teacher asks: How old are you? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "I am + tuổi.",
              correct: "I am eight.",
              wrong: ["I is eight.", "He is eight."],
              distractorNotes: ["Sai động từ", "Nói về người khác"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-situational-practice",
          title: "Practice: More Situations",
          instructions: "Choose what you would say.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Examiner: Is he your father? (Yes) You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes. He is my father.",
              correct: "Yes. He is my father.",
              wrong: ["No. She is my mother.", "Yes. She is my father."],
              distractorNotes: ["Sai câu trả lời", "Bố dùng he"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Friend asks about Anna. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Her name is Anna. — giới thiệu bạn gái.",
              correct: "Her name is Anna.",
              wrong: ["His name is Anna.", "My name is Anna."],
              distractorNotes: ["Anna là tên nữ", "Nói về bản thân"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "You finish talking about family happily. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "We are happy! — kết thúc tích cực.",
              correct: "We are happy!",
              wrong: ["I am mother.", "They is happy."],
              distractorNotes: ["Sai ngữ pháp", "Sai động từ"],
              difficultyRating: 2,
            }),
          ],
        }),
        situationalCheck,
        buildExercise({
          slug: "speaking-situational-apply",
          title: "Apply: Quick Situational Replies",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Someone says: Nice to meet your family! You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "We are happy! — phản hồi tích cực phù hợp unit.",
              correct: "We are happy!",
              wrong: ["I am friend.", "She are happy."],
              distractorNotes: ["Sai ngữ pháp", "Sai động từ với she"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner points to your sister. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "She is my sister.",
              correct: "She is my sister.",
              wrong: ["He is my sister.", "She is my brother."],
              distractorNotes: ["Sister là nữ", "Brother là nam"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-situational-review",
          title: "Review: Situational Speaking Mix",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "What is your best friend's name? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Her name is Anna. / His name is Tom. — tùy giới tính.",
              correct: "Her name is Anna.",
              wrong: ["His name is Anna.", "Name friend Anna."],
              distractorNotes: ["Anna thường là tên nữ", "Không đủ câu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say one sentence about your mother. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "My mother is kind. — như bài đọc Mai.",
              correct: "My mother is kind.",
              wrong: ["Mother my kind is.", "My mother kind."],
              distractorNotes: ["Sai thứ tự", "Thiếu is"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Your brother is six. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "He is six. / My brother is six.",
              correct: "He is six.",
              wrong: ["She is six.", "He six is."],
              distractorNotes: ["Brother dùng he", "Sai thứ tự"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
