/** Starters U1 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-meet-my-family",
      title: "Lesson 1: Meet My Family",
      learningObjective:
        "Recognise and use father, mother, brother and sister in short sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-family-learn",
          title: "Learn: Family Words",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Your mother's husband is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation:
                "Father (bố) là cha — chồng của mẹ. Friend cũng bắt đầu bằng f nhưng không phải thành viên gia đình.",
              correct: "father",
              wrong: ["friend", "brother"],
              distractorNotes: [
                "Cùng chữ f; hay nhầm với bạn",
                "Nam trong gia đình nhưng không phải cha",
              ],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Match: 'This is my _____. She cooks dinner.'",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mother (mẹ) — đại từ she giúp nhận ra đáp án.",
              correct: "mother",
              wrong: ["brother", "boy"],
              distractorNotes: ["Nam trong gia đình", "Không hợp với she"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "A boy in your family is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Brother (anh/em trai) — con trai trong gia đình.",
              correct: "brother",
              wrong: ["sister", "father"],
              distractorNotes: ["Con gái trong gia đình", "Cha — người lớn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "A girl in your family is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Sister (chị/em gái) — con gái trong gia đình.",
              correct: "sister",
              wrong: ["brother", "mother"],
              distractorNotes: ["Con trai", "Mẹ — người lớn"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-family-practice",
          title: "Practice: Match Family Words",
          instructions: "Match each word to the correct meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the family words to their meanings.",
              skillTag: "vocabulary",
              topicTag,
              explanation:
                "Mỗi từ khớp một nghĩa rõ ràng. Brother và sister hay bị đảo.",
              pairs: [
                { left: "father", right: "your male parent" },
                { left: "mother", right: "your female parent" },
                { left: "brother", right: "a boy in your family" },
                { left: "sister", right: "a girl in your family" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-family-check",
          title: "Check: Family Words Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "She is kind. She is my _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "She + kind → mother (mẹ). Father dùng he.",
              correct: "mother",
              wrong: ["father", "brother"],
              distractorNotes: ["Nam — dùng he", "Con trai — dùng he"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "I have one _____. His name is Nam.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "His name → brother (anh/em trai). Sister dùng her.",
              correct: "brother",
              wrong: ["sister", "mother"],
              distractorNotes: ["Con gái — dùng her", "Mẹ — không phải anh trai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "My _____ is tall. He has black hair.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "He + tall → father (bố). Mother dùng she.",
              correct: "father",
              wrong: ["mother", "sister"],
              distractorNotes: ["Nữ — dùng she", "Em gái — trẻ hơn"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-family-apply",
          title: "Apply: Family in Sentences",
          instructions: "Complete each sentence with the correct family word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: This is my [0]. | She is my [1]. | He is my [2].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "father (he); mother (she); brother (he).",
              template: "This is my [0]. She is my [1]. He is my [2].",
              correctAnswers: ["father", "mother", "brother"],
              acceptableAnswers: [
                ["father", "Father"],
                ["mother", "Mother"],
                ["brother", "Brother"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-family-review",
          title: "Review: Family Words Mix",
          instructions: "Mixed review. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Your father's wife is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mother (mẹ) — vợ của bố.",
              correct: "mother",
              wrong: ["sister", "friend"],
              distractorNotes: ["Em gái", "Không phải gia đình"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh is a girl in my family. She is my _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Girl in family → sister (chị/em gái).",
              correct: "sister",
              wrong: ["brother", "father"],
              distractorNotes: ["Con trai", "Cha — người lớn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word is NOT a family member?",
              skillTag: "vocabulary",
              topicTag,
              explanation:
                "Father, mother, brother, sister là gia đình. Friend (bạn) không phải.",
              correct: "friend",
              wrong: ["brother", "mother"],
              distractorNotes: ["Thành viên gia đình", "Thành viên gia đình"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-friends-and-people",
      title: "Lesson 2: Friends and People",
      learningObjective:
        "Recognise and use friend, boy and girl to talk about people at Starters level.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-friends-learn",
          title: "Learn: Friends and People",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Tom plays with you at school. Tom is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation:
                "Friend (bạn) là người chơi cùng ở trường. Brother là anh/em trai trong gia đình.",
              correct: "friend",
              wrong: ["brother", "father"],
              distractorNotes: [
                "Thành viên gia đình, không phải bạn ở trường",
                "Cha — người lớn",
              ],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "A young male child is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation:
                "Boy (cậu bé) chỉ con trai nhỏ. Girl là con gái; friend là quan hệ.",
              correct: "boy",
              wrong: ["girl", "friend"],
              distractorNotes: ["Con gái", "Từ chỉ quan hệ, không phải giới tính"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Anna is a young _____. She is seven.",
              skillTag: "vocabulary",
              topicTag,
              explanation:
                "Girl (cô bé) phù hợp với tên nữ và tuổi nhỏ. Boy dùng cho con trai.",
              correct: "girl",
              wrong: ["boy", "mother"],
              distractorNotes: ["Con trai", "Người lớn — tuổi không hợp"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "My best _____ is Linh. We sit together in class.",
              skillTag: "vocabulary",
              topicTag,
              explanation:
                "Friend (bạn) là người ngồi cạnh ở lớp. Sister là chị/em gái trong gia đình.",
              correct: "friend",
              wrong: ["sister", "brother"],
              distractorNotes: [
                "Vai trò gia đình; bạn cùng lớp không nhất thiết là chị/em",
                "Anh/em trai — nam",
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-friends-practice",
          title: "Practice: Match Friends and People",
          instructions: "Match each word to the correct meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the people words to their meanings.",
              skillTag: "vocabulary",
              topicTag,
              explanation:
                "Mỗi từ khớp một nghĩa rõ ràng. Boy/girl nói giới tính/tuổi; friend nói quan hệ.",
              pairs: [
                { left: "friend", right: "a person you like and know" },
                { left: "boy", right: "a young male child" },
                { left: "girl", right: "a young female child" },
                { left: "brother", right: "a boy in your family" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-friends-check",
          title: "Check: Friends Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "She is not my sister. She is my _____ from class.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "from class → friend (bạn), không phải thành viên gia đình.",
              correct: "friend",
              wrong: ["mother", "brother"],
              distractorNotes: ["Cha mẹ — người lớn", "Anh/em trai — nam"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Look at the picture: a young male child. He is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Boy (cậu bé) = young male. Girl là nữ.",
              correct: "boy",
              wrong: ["girl", "friend"],
              distractorNotes: ["Con gái", "Nói quan hệ, không phải giới tính"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Lily and Mai play together. They are _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation:
                "Hai người chơi cùng nhau thường là friends (bạn). Sister cần quan hệ gia đình.",
              correct: "friends",
              wrong: ["sisters", "brothers"],
              distractorNotes: [
                "Vai trò gia đình không được nêu",
                "Anh em trai; cả hai là con gái",
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-friends-apply",
          title: "Apply: People in Sentences",
          instructions: "Complete each sentence with the correct word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: Tom is my [0]. | He is a [1]. | Anna is a [2].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "friend (bạn); boy (cậu bé) với he; girl (cô bé) với Anna.",
              template: "Tom is my [0]. He is a [1]. Anna is a [2].",
              correctAnswers: ["friend", "boy", "girl"],
              acceptableAnswers: [
                ["friend", "Friend"],
                ["boy", "Boy"],
                ["girl", "Girl"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-friends-review",
          title: "Review: Friends and People Mix",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "A person you know from school but not family is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Friend (bạn) — người quen ở trường, không phải gia đình.",
              correct: "friend",
              wrong: ["sister", "mother"],
              distractorNotes: ["Chị/em gái", "Mẹ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Nam is six. He is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "He + young child → boy (cậu bé).",
              correct: "boy",
              wrong: ["girl", "father"],
              distractorNotes: ["Con gái", "Cha — người lớn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna is in our class. She is a _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "She + young → girl (cô bé).",
              correct: "girl",
              wrong: ["boy", "brother"],
              distractorNotes: ["Con trai", "Anh/em trai"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-face-words",
      title: "Lesson 3: Face Words",
      learningObjective:
        "Name and use head, eyes, nose, mouth and hair in short sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-face-learn",
          title: "Learn: Face Words",
          instructions: "Read each clue. Choose the face word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "You see with your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Eyes (mắt) dùng để nhìn. Nose để ngửi; mouth để ăn.",
              correct: "eyes",
              wrong: ["nose", "mouth"],
              distractorNotes: ["Dùng để ngửi", "Dùng để ăn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "You smell with your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Nose (mũi) dùng để ngửi.",
              correct: "nose",
              wrong: ["eyes", "hair"],
              distractorNotes: ["Dùng để nhìn", "Trên đầu, không dùng để ngửi"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "You eat with your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mouth (miệng) dùng để ăn và nói.",
              correct: "mouth",
              wrong: ["nose", "head"],
              distractorNotes: ["Dùng để ngửi", "Cả phần đầu, không dùng để ăn"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Long or short _____ grows on your head.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hair (tóc) mọc trên đầu. Head là cả phần đầu.",
              correct: "hair",
              wrong: ["head", "eyes"],
              distractorNotes: ["Cả đầu, không chỉ tóc", "Dùng để nhìn"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-face-practice",
          title: "Practice: Match Face Parts",
          instructions: "Match each word to what you do with it or where it is.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match face words to their descriptions.",
              skillTag: "vocabulary",
              topicTag,
              explanation:
                "Mỗi bộ phận có chức năng hoặc vị trí riêng trên khuôn mặt/đầu.",
              pairs: [
                { left: "eyes", right: "you see with them" },
                { left: "nose", right: "you smell with it" },
                { left: "mouth", right: "you eat and talk with it" },
                { left: "hair", right: "grows on your head" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-face-check",
          title: "Check: Face Words Quiz",
          instructions: "Choose the best answer. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "The part above your neck that has your face is your _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Head (đầu) là phần trên cổ có mặt. Hair chỉ là tóc.",
              correct: "head",
              wrong: ["hair", "mouth"],
              distractorNotes: ["Chỉ phần tóc", "Phần dưới khuôn mặt"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Her _____ are brown. She can see well.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Eyes (mắt) — are + eyes; dùng để nhìn.",
              correct: "eyes",
              wrong: ["nose", "hair"],
              distractorNotes: ["Dùng để ngửi", "Không dùng để nhìn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Touch your _____. It is at the top of your body.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Head (đầu) ở trên cùng cơ thể.",
              correct: "head",
              wrong: ["mouth", "eyes"],
              distractorNotes: ["Trong mặt, không phải trên cùng", "Trong mặt"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-face-apply",
          title: "Apply: Face Words in Context",
          instructions: "Complete the sentences with face words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: I see with my [0]. | I smell with my [1]. | Her [2] is long.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "eyes (mắt); nose (mũi); hair (tóc) — her hair is long.",
              template: "I see with my [0]. I smell with my [1]. Her [2] is long.",
              correctAnswers: ["eyes", "nose", "hair"],
              acceptableAnswers: [
                ["eyes", "Eyes"],
                ["nose", "Nose"],
                ["hair", "Hair"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-face-review",
          title: "Review: Face Words Mix",
          instructions: "Choose the best face word.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Open your _____ to eat.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mouth (miệng) dùng để ăn.",
              correct: "mouth",
              wrong: ["nose", "eyes"],
              distractorNotes: ["Ngửi", "Nhìn"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "His _____ is black. It is on his head.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Hair (tóc) trên đầu. Eyes ở trên mặt.",
              correct: "hair",
              wrong: ["eyes", "mouth"],
              distractorNotes: ["Mắt — không phải trên đầu", "Miệng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which part do you use to smell flowers?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Nose (mũi) dùng để ngửi hoa.",
              correct: "nose",
              wrong: ["mouth", "hair"],
              distractorNotes: ["Ăn/nói", "Tóc"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
