/** Starters U4 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-this-that",
      title: "Lesson 1: This and That",
      learningObjective:
        "Use this for animals near and that for animals far away.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-this-that-learn",
          title: "Learn: This vs That",
          instructions: "Choose the correct word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "The cat is near Mai. She says: _____ is my cat.",
              skillTag: "grammar",
              topicTag,
              explanation: "This — gần người nói dùng this.",
              correct: "This",
              wrong: ["That", "These"],
              distractorNotes: ["That = xa hơn", "These = số nhiều gần"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The tiger is far away. Anna says: _____ tiger is far away.",
              skillTag: "grammar",
              topicTag,
              explanation: "That — xa dùng that.",
              correct: "That",
              wrong: ["This", "It"],
              distractorNotes: ["This = gần", "It không chỉ xa/gần rõ"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mai points to an elephant near her: _____ is an elephant.",
              skillTag: "grammar",
              topicTag,
              explanation: "This is an elephant — voi gần Mai.",
              correct: "This is an elephant.",
              wrong: ["That is an elephant.", "This are an elephant."],
              distractorNotes: ["That = xa", "Are số nhiều sai"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Nam points to a sleeping lion far away: Look at _____ lion!",
              skillTag: "grammar",
              topicTag,
              explanation: "That — sư tử xa → that lion.",
              correct: "that",
              wrong: ["this", "these"],
              distractorNotes: ["This = gần", "These = số nhiều"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-this-that-practice",
          title: "Practice: This/That Gap Fill",
          instructions: "Complete with this or that.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] is my cat. | [1] is my dog. | [2] tiger is far away.",
              skillTag: "grammar",
              topicTag,
              explanation: "This (cat gần); That (dog xa hơn); That (tiger xa).",
              template: "[0] is my cat. [1] is my dog. [2] tiger is far away.",
              correctAnswers: ["This", "That", "That"],
              acceptableAnswers: [
                ["This", "this"],
                ["That", "that"],
                ["That", "that"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-this-that-check",
          title: "Check: This/That Quiz",
          instructions: "Choose the best answer. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "This is my cat — mèo gần Mai.",
              correct: "This is my cat.",
              wrong: ["That is my cat near me.", "This are my cat."],
              distractorNotes: ["Gần dùng this", "Are số nhiều sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The elephant is near. Best sentence:",
              skillTag: "grammar",
              topicTag,
              explanation: "This is an elephant — gần → this.",
              correct: "This is an elephant.",
              wrong: ["That is an elephant.", "These is an elephant."],
              distractorNotes: ["That = xa", "These + is sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is wrong?",
              skillTag: "grammar",
              topicTag,
              explanation: "This is tiger sai — cần a/an: This is a tiger.",
              correct: "This is tiger.",
              wrong: ["This is a cat.", "That is a dog."],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-this-that-apply",
          title: "Apply: Order This/That Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: This / is / my / cat.",
              skillTag: "grammar",
              topicTag,
              explanation: "This is my cat. — this + is + sở hữu + danh từ.",
              words: ["This", "is", "my", "cat."],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: Look / at / that / lion!",
              skillTag: "grammar",
              topicTag,
              explanation: "Look at that lion! — that + danh từ xa.",
              words: ["Look", "at", "that", "lion!"],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-this-that-review",
          title: "Review: This/That Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Mai holds her cat. She says:",
              skillTag: "grammar",
              topicTag,
              explanation: "This is my cat — đang ôm = gần.",
              correct: "This is my cat.",
              wrong: ["That is my cat.", "These is my cat."],
              distractorNotes: ["That = xa", "These + is sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The monkey is near Mai. Mai says:",
              skillTag: "grammar",
              topicTag,
              explanation: "This is a monkey — gần → this.",
              correct: "This is a monkey.",
              wrong: ["That is a monkey.", "This are a monkey."],
              distractorNotes: ["That = xa", "Are sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The bear is far. Best phrase:",
              skillTag: "grammar",
              topicTag,
              explanation: "That bear — xa → that.",
              correct: "that bear",
              wrong: ["this bear", "these bear"],
              distractorNotes: ["This = gần", "These = số nhiều"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-plural-s",
      title: "Lesson 2: Plural -s",
      learningObjective:
        "Add -s to make plural animal nouns: cats, dogs, birds.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "grammar-plural-learn",
          title: "Learn: Plural with -s",
          instructions: "Choose the correct plural form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "One cat, two _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Cats — thêm -s: cat → cats.",
              correct: "cats",
              wrong: ["cat", "caties"],
              distractorNotes: ["Số ít", "Không đúng quy tắc"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "One dog, three _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Dogs — dog + s = dogs.",
              correct: "dogs",
              wrong: ["dog", "doges"],
              distractorNotes: ["Số ít", "Sai chính tả"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Two _____ are in the tree.",
              skillTag: "grammar",
              topicTag,
              explanation: "Birds — two + birds (số nhiều).",
              correct: "birds",
              wrong: ["bird", "birdes"],
              distractorNotes: ["Số ít với two", "Sai"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Nam sees three _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Monkeys — three monkeys at the zoo.",
              correct: "monkeys",
              wrong: ["monkey", "monkies"],
              distractorNotes: ["Số ít", "Sai — monkey → monkeys"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-plural-practice",
          title: "Practice: Plural Gap Fill",
          instructions: "Complete with the correct plural form.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: two [0] | three [1] | The [2] are in the pool.",
              skillTag: "grammar",
              topicTag,
              explanation: "cats; dogs; fish — fish có thể giữ nguyên hoặc fishes; Starters dùng fish.",
              template: "two [0] | three [1] | The [2] are in the pool.",
              correctAnswers: ["cats", "dogs", "fish"],
              acceptableAnswers: [
                ["cats", "Cats"],
                ["dogs", "Dogs"],
                ["fish", "Fish"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-plural-check",
          title: "Check: Plural -s Quiz",
          instructions: "Choose the correct form. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "They see monkeys — số nhiều + -s.",
              correct: "They see monkeys.",
              wrong: ["They see monkey.", "They sees monkeys."],
              distractorNotes: ["Thiếu -s", "Sees số ít"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The _____ are big. (bear — more than one)",
              skillTag: "grammar",
              topicTag,
              explanation: "Bears — The bears are big.",
              correct: "bears",
              wrong: ["bear", "beares"],
              distractorNotes: ["Số ít với are", "Sai chính tả"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which is wrong?",
              skillTag: "grammar",
              topicTag,
              explanation: "Two cat sai — phải two cats.",
              correct: "two cat",
              wrong: ["two cats", "three dogs"],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-plural-apply",
          title: "Apply: Order Plural Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Two / birds / are / in / the / tree.",
              skillTag: "grammar",
              topicTag,
              explanation: "Two birds are in the tree. — số nhiều + are.",
              words: ["Two", "birds", "are", "in", "the", "tree."],
              correctOrder: [0, 1, 2, 3, 4, 5],
            }),
            buildSentenceOrdering({
              questionText: "Make: I / have / two / cats.",
              skillTag: "grammar",
              topicTag,
              explanation: "I have two cats. — two + plural.",
              words: ["I", "have", "two", "cats."],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-plural-review",
          title: "Review: Plural -s Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Mai has one cat and one dog. She has two _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Pets — two pets (cat + dog).",
              correct: "pets",
              wrong: ["pet", "animals cat"],
              distractorNotes: ["Số ít", "Không phải cụm đúng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The fish _____ orange. (many fish)",
              skillTag: "grammar",
              topicTag,
              explanation: "Are — fish số nhiều → are.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is số ít", "Am với I"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Three _____ play at the zoo.",
              skillTag: "grammar",
              topicTag,
              explanation: "Monkeys — I can see three monkeys.",
              correct: "monkeys",
              wrong: ["monkey", "monkys"],
              distractorNotes: ["Số ít", "Sai chính tả"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-animals-mixed",
      title: "Lesson 3: Mixed Grammar",
      learningObjective:
        "Use this/that and plural -s together in animal contexts.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "grammar-mixed-learn",
          title: "Learn: Mixed Patterns",
          instructions: "Choose the correct word or phrase.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "_____ is an elephant. (near)",
              skillTag: "grammar",
              topicTag,
              explanation: "This — voi gần → this.",
              correct: "This",
              wrong: ["That", "These"],
              distractorNotes: ["That = xa", "These số nhiều"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Two _____ are in the garden.",
              skillTag: "grammar",
              topicTag,
              explanation: "Birds — two + plural birds.",
              correct: "birds",
              wrong: ["bird", "birdes"],
              distractorNotes: ["Số ít", "Sai"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The monkeys _____ funny.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are — monkeys số nhiều → are.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is số ít", "Am với I"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best sentence: tiger far away",
              skillTag: "grammar",
              topicTag,
              explanation: "That tiger is far away.",
              correct: "That tiger is far away.",
              wrong: ["This tiger is far away.", "That tigers is far away."],
              distractorNotes: ["This = gần", "Tigers + is sai"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-practice",
          title: "Practice: Mixed Gap Fill",
          instructions: "Complete with this, that, or plural forms.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] is my dog. | [1] lion is sleeping. | Three [2] play.",
              skillTag: "grammar",
              topicTag,
              explanation: "This/That; that; monkeys — hỗn hợp this/that và plural.",
              template: "[0] is my dog. [1] lion is sleeping. Three [2] play.",
              correctAnswers: ["That", "That", "monkeys"],
              acceptableAnswers: [
                ["That", "that", "This", "this"],
                ["That", "that"],
                ["monkeys", "Monkeys"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-check",
          title: "Check: Mixed Grammar Quiz",
          instructions: "Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "This is my cat. It is small. — this + is + số ít.",
              correct: "This is my cat. It is small.",
              wrong: ["This are my cat.", "That is my cat near me."],
              distractorNotes: ["Are sai", "Gần dùng this"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They see bears. The bears _____ big.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are — bears số nhiều.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is số ít", "Am với I"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai: One cat and one dog. I have two _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Pets — two pets total.",
              correct: "pets",
              wrong: ["pet", "cats"],
              distractorNotes: ["Số ít", "Chỉ mèo — có cả chó"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-apply",
          title: "Apply: Order Mixed Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: This / is / an / elephant.",
              skillTag: "grammar",
              topicTag,
              explanation: "This is an elephant. — this + an + vowel noun.",
              words: ["This", "is", "an", "elephant."],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: The / fish / are / in / the / pool.",
              skillTag: "grammar",
              topicTag,
              explanation: "The fish are in the pool. — plural + are.",
              words: ["The", "fish", "are", "in", "the", "pool."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-review",
          title: "Review: Mixed Grammar",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Anna: Me too. The fish _____ orange.",
              skillTag: "grammar",
              topicTag,
              explanation: "Are — fish (nhiều con) + are.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is số ít", "Am với I"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which question uses this/that correctly?",
              skillTag: "grammar",
              topicTag,
              explanation: "What is that animal? — hỏi con vật xa.",
              correct: "What is that animal?",
              wrong: ["What are that animal?", "What is these animal?"],
              distractorNotes: ["That + are sai", "These + is sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Complete: Look at _____ lion! (far)",
              skillTag: "grammar",
              topicTag,
              explanation: "That — xa → that lion.",
              correct: "that",
              wrong: ["this", "these"],
              distractorNotes: ["This = gần", "These số nhiều"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
