/** Starters U4 — reading lessons (3 × 5 exercises). */

export function readingLessons({
  buildMcq,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMaiPetsAndZoo,
  topicTag,
}) {
  const passage = passageMaiPetsAndZoo;

  return [
    {
      slug: "reading-decode-words",
      title: "Lesson 1: Decode Familiar Words",
      learningObjective:
        "Read animal words in context and match them to meanings.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-decode-learn",
          title: "Learn: Read Animal Words",
          instructions: "Read the text. Then answer the questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "What is the main idea of the text?",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation:
                "Bài về thú cưng ở nhà Mai và chuyến đi sở thú.",
              correct: "Mai's pets at home and a zoo visit.",
              wrong: ["Mai goes shopping for clothes.", "Mai learns numbers."],
              distractorNotes: ["Unit 3 — quần áo", "Unit 2 — số"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which word means 'con mèo'?",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "Cat = con mèo — Mai has a cat.",
              correct: "cat",
              wrong: ["dog", "zoo"],
              distractorNotes: ["Chó", "Sở thú — nơi chốn"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-decode-practice",
          title: "Practice: More Animal Words",
          instructions: "Read again. Find more animal words.",
          sortOrder: 1,
          passage,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "Mai has a cat and a _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Dog — a cat and a dog.",
              correct: "dog",
              wrong: ["zoo", "horse"],
              distractorNotes: ["Nơi chốn", "Không trong bài"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The word 'elephant' is in the part about the _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "Zoo — elephant at the zoo.",
              correct: "zoo",
              wrong: ["school", "garden"],
              distractorNotes: ["Trường", "Vườn nhà"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-decode-check",
          title: "Check: Decode Words Quiz",
          instructions: "Read carefully. Choose the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Which animal word is NOT in the text?",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "Horse không có trong bài. Cat, dog, elephant, monkey, bear, tiger, fish, lion, bird có.",
              correct: "horse",
              wrong: ["monkey", "tiger"],
              distractorNotes: ["Có — favourite", "Có — far away"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna likes the _____ in the pool.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Fish — Anna likes the fish in the pool.",
              correct: "fish",
              wrong: ["bear", "rabbit"],
              distractorNotes: ["Gấu không ở bể", "Thỏ không trong bài"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-decode-apply",
          title: "Apply: Match Words to Animals",
          instructions: "Use the text. Match words to descriptions.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match animal words to short descriptions from the text.",
              skillTag: "reading",
              topicTag,
              explanation: "Cat=small and black; dog=big and brown; elephant=near Mai; tiger=far away.",
              pairs: [
                { left: "cat", right: "small and black" },
                { left: "dog", right: "big and brown" },
                { left: "elephant", right: "This is an…" },
                { left: "tiger", right: "far away" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-decode-review",
          title: "Review: Decode Words Mix",
          instructions: "Read the text again. Mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "They see monkeys, bears and _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Birds — They see monkeys, bears and birds.",
              correct: "birds",
              wrong: ["fish only", "horses"],
              distractorNotes: ["Fish ở bể riêng", "Không có horses"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The word 'zoo' means:",
              skillTag: "reading",
              topicTag,
              assessmentType: "vocabulary_in_context",
              explanation: "Zoo = sở thú — nơi xem động vật.",
              correct: "a place to see animals",
              wrong: ["a pet at home", "a school"],
              distractorNotes: ["Pet ở nhà", "Trường học"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which word describes Mai's dog?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Big — The dog is big and brown.",
              correct: "big",
              wrong: ["small", "orange"],
              distractorNotes: ["Small = cat", "Orange = fish"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-mais-pets",
      title: "Lesson 2: Mai's Pets",
      learningObjective:
        "Read about Mai's cat and dog at home.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-pets-learn",
          title: "Learn: Read About Mai's Pets",
          instructions: "Read the first part about pets. Answer the questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "How many pets does Mai have at home?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Two pets — a cat and a dog.",
              correct: "Two",
              wrong: ["One", "Four"],
              distractorNotes: ["Có cả cat và dog", "Quá nhiều"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The cat is small and _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Black — The cat is small and black.",
              correct: "black",
              wrong: ["brown", "white"],
              distractorNotes: ["Brown = dog", "Không nêu"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-pets-practice",
          title: "Practice: More About the Pets",
          instructions: "Read again. Answer about the dog.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "The dog is big and _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Brown — The dog is big and brown.",
              correct: "brown",
              wrong: ["black", "green"],
              distractorNotes: ["Black = cat", "Không phải màu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which pet is small?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "The cat — The cat is small.",
              correct: "the cat",
              wrong: ["the dog", "the elephant"],
              distractorNotes: ["Dog is big", "Elephant at zoo"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-pets-check",
          title: "Check: Mai's Pets Quiz",
          instructions: "Read carefully. Choose the best answer.",
          sortOrder: 2,
          passage,
          difficulty: 0.35,
          questions: [
            buildMcq({
              questionText: "Mai is _____ years old.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Eight — Mai is eight.",
              correct: "eight",
              wrong: ["six", "ten"],
              distractorNotes: ["Không nêu", "Không nêu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence from the text is about pets at HOME?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "She has two pets at home — a cat and a dog.",
              correct: "She has two pets at home.",
              wrong: ["This is an elephant.", "Look at that lion!"],
              distractorNotes: ["Zoo part", "Zoo part"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-pets-apply",
          title: "Apply: Match Pets to Descriptions",
          instructions: "Match each pet to its description.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match Mai's pets to their descriptions.",
              skillTag: "reading",
              topicTag,
              explanation: "Cat=small and black; dog=big and brown.",
              pairs: [
                { left: "cat", right: "small and black" },
                { left: "dog", right: "big and brown" },
                { left: "pets at home", right: "two (cat and dog)" },
                { left: "Mai's age", right: "eight" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-pets-review",
          title: "Review: Mai's Pets Mix",
          instructions: "Read and answer — mixed review.",
          sortOrder: 4,
          passage,
          difficulty: 0.33,
          questions: [
            buildMcq({
              questionText: "Which animal is NOT a pet at Mai's home?",
              skillTag: "reading",
              topicTag,
              assessmentType: "inference",
              explanation: "Monkey ở zoo. Cat và dog là pets.",
              correct: "monkey",
              wrong: ["cat", "dog"],
              distractorNotes: ["Pet ở nhà", "Pet ở nhà"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The cat and dog are at _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Home — pets at home.",
              correct: "home",
              wrong: ["the zoo", "school"],
              distractorNotes: ["Zoo = phần sau", "Không nêu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Complete: Mai has a _____ cat and a big dog.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Small — The cat is small.",
              correct: "small",
              wrong: ["big", "far"],
              distractorNotes: ["Big = dog", "Far = tiger"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-favourite-and-detail",
      title: "Lesson 3: Detail and Favourite Animal",
      learningObjective:
        "Find details and Mai's favourite animal in the zoo part.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-fav-learn",
          title: "Learn: Read the Zoo Part",
          instructions: "Read about the zoo visit. Answer the questions.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "Who goes to the zoo with Mai?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Nam (brother) and Anna (friend).",
              correct: "Nam and Anna",
              wrong: ["Mum only", "Teacher"],
              distractorNotes: ["Mum không đi zoo trong bài", "Không có"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Mai's favourite animal is the _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Monkey — Mai's favourite animal is the monkey.",
              correct: "monkey",
              wrong: ["elephant", "fish"],
              distractorNotes: ["Elephant gần nhưng không favourite", "Anna thích fish"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-fav-practice",
          title: "Practice: Zoo Details",
          instructions: "Read again. Find more details.",
          sortOrder: 1,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "That _____ is far away.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Tiger — That tiger is far away.",
              correct: "tiger",
              wrong: ["elephant", "monkey"],
              distractorNotes: ["Elephant gần — This is", "Monkey favourite"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Nam says: Look at that _____!",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Lion — Look at that lion!",
              correct: "lion",
              wrong: ["bear", "bird"],
              distractorNotes: ["Bear — they see bears", "Bird — they see birds"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-fav-check",
          title: "Check: Favourite and Detail Quiz",
          instructions: "Read one more time. Harder questions.",
          sortOrder: 2,
          passage,
          difficulty: 0.38,
          questions: [
            buildMcq({
              questionText: "When does Mai go to the zoo?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Saturday — On Saturday Mai goes to the zoo.",
              correct: "Saturday",
              wrong: ["Monday", "Sunday morning at home"],
              distractorNotes: ["Không nêu", "Pets part — not zoo day"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How do they feel at the end?",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Happy — They have a happy day at the zoo.",
              correct: "happy",
              wrong: ["sad", "angry"],
              distractorNotes: ["Trái nghĩa", "Không nêu"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-fav-apply",
          title: "Apply: Match Zoo Facts",
          instructions: "Match people and animals to facts from the text.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match zoo facts from the reading.",
              skillTag: "reading",
              topicTag,
              explanation: "Anna=likes fish; Nam=says lion; Mai=favourite monkey; tiger=far away.",
              pairs: [
                { left: "Anna", right: "likes the fish" },
                { left: "Nam", right: "Look at that lion!" },
                { left: "Mai", right: "favourite = monkey" },
                { left: "tiger", right: "far away" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-fav-review",
          title: "Review: Zoo Reading Mix",
          instructions: "Find details in the text.",
          sortOrder: 4,
          passage,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Mai says: This is an _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Elephant — This is an elephant.",
              correct: "elephant",
              wrong: ["tiger", "cat"],
              distractorNotes: ["Tiger = that, far", "Cat at home"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They see monkeys, bears and birds. They also see fish in the _____.",
              skillTag: "reading",
              topicTag,
              assessmentType: "detail",
              explanation: "Pool — fish in the pool.",
              correct: "pool",
              wrong: ["tree", "cupboard"],
              distractorNotes: ["Birds in tree at home", "Clothes unit"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The text is mainly about:",
              skillTag: "reading",
              topicTag,
              assessmentType: "main_idea",
              explanation: "Pets at home + happy zoo day with friends.",
              correct: "Mai's pets and a fun zoo visit",
              wrong: ["Mai's clothes colours", "Numbers and time"],
              distractorNotes: ["Unit 3", "Unit 2"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
