/** Starters U4 — speaking lessons (3 × 5 exercises; only Check is AI). */

const MAI_PETS_SCENE =
  "Mai's home after school. Mai is eight. She has a small black cat and a big brown dog. Two birds are in the tree in the garden. Her brother Nam is nearby. Her friend Anna visits sometimes.";

const MAI_ZOO_SCENE =
  "The zoo on Saturday. Mai, her brother Nam and her friend Anna walk around. They see an elephant near them. A tiger is far away. Three monkeys play. Big bears stand near a pool with orange fish. A lion sleeps. Mai's favourite animal is the monkey.";

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [petsCheck, zooCheck, pluralCheck] = speakingChecks;

  return [
    {
      slug: "speaking-pets",
      title: "Lesson 1: Talk About Pets",
      learningObjective:
        "Answer simple questions about pets with short phrases.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-pets-learn",
          title: "Learn: What to Say About Pets",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { sceneDescription: MAI_PETS_SCENE },
          questions: [
            buildMcq({
              questionText: "Someone asks: Do you have a pet? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes. / Yes, I have a cat and a dog.",
              correct: "Yes. I have a cat and a dog.",
              wrong: ["No pets ever.", "Yes. I have an elephant."],
              distractorNotes: ["Mai có pets", "Elephant ở zoo"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Someone asks: What is this? (near cat) You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "This is my cat.",
              correct: "This is my cat.",
              wrong: ["That is my cat.", "This are my cat."],
              distractorNotes: ["Gần dùng this", "Are sai"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-pets-practice",
          title: "Practice: Pet Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { sceneDescription: MAI_PETS_SCENE },
          questions: [
            buildMcq({
              questionText: "Mum asks: What colour is your cat? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Black. / It is black.",
              correct: "Black.",
              wrong: ["Brown.", "Orange."],
              distractorNotes: ["Brown = dog", "Orange = fish"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Friend asks: Is your dog big? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes. It is big and brown.",
              correct: "Yes. It is big.",
              wrong: ["Yes. They are big.", "Yes. It are big."],
              distractorNotes: ["Dog số ít — it", "It + are sai"],
              difficultyRating: 2,
            }),
          ],
        }),
        petsCheck,
        buildExercise({
          slug: "speaking-pets-apply",
          title: "Apply: Quick Pet Replies",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Point to your dog (far). You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "That is my dog.",
              correct: "That is my dog.",
              wrong: ["This is my dog far.", "That are my dog."],
              distractorNotes: ["Xa dùng that", "Are sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say how many pets you have. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Two. / I have two pets.",
              correct: "Two.",
              wrong: ["One.", "Zero."],
              distractorNotes: ["Mai có cat và dog", "Mai có pets"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-pets-review",
          title: "Review: Pet Speaking",
          instructions: "Choose the best spoken reply.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "How many birds in the tree? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Two. / Two birds.",
              correct: "Two birds.",
              wrong: ["One bird.", "Three birds."],
              distractorNotes: ["Listening script says two", "Script says two"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Describe Mai's cat. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Small and black.",
              correct: "It is small and black.",
              wrong: ["It is big and brown.", "They are small."],
              distractorNotes: ["Dog description", "Cat số ít — it"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say one sentence with this + pet. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "This is my cat.",
              correct: "This is my cat.",
              wrong: ["This is my cats.", "That is my cat near."],
              distractorNotes: ["Cat số ít", "Gần dùng this"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-zoo",
      title: "Lesson 2: Talk About the Zoo",
      learningObjective:
        "Answer questions about animals at the zoo.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-zoo-learn",
          title: "Learn: Zoo Speaking Phrases",
          instructions: "Read the scene description. Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { sceneDescription: MAI_ZOO_SCENE },
          questions: [
            buildMcq({
              questionText: "Where are Mai, Nam and Anna? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "At the zoo.",
              correct: "At the zoo.",
              wrong: ["At home.", "At school."],
              distractorNotes: ["Pets at home", "Không đi học"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What is near Mai? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "An elephant. / This is an elephant.",
              correct: "This is an elephant.",
              wrong: ["That is an elephant.", "This is a tiger."],
              distractorNotes: ["Gần → this", "Tiger far away"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-zoo-practice",
          title: "Practice: Zoo Questions",
          instructions: "Choose what you would say at the zoo.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { sceneDescription: MAI_ZOO_SCENE },
          questions: [
            buildMcq({
              questionText: "Examiner: What animal is far away? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "The tiger. / That tiger is far away.",
              correct: "That tiger is far away.",
              wrong: ["This tiger is far away.", "That elephant is far away."],
              distractorNotes: ["Xa → that", "Elephant near"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Examiner: What is Mai's favourite animal? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "The monkey.",
              correct: "The monkey.",
              wrong: ["The elephant.", "The fish."],
              distractorNotes: ["Near but not favourite", "Anna likes fish"],
              difficultyRating: 2,
            }),
          ],
        }),
        zooCheck,
        buildExercise({
          slug: "speaking-zoo-apply",
          title: "Apply: Zoo Speaking",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Nam points to the lion. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Look at that lion!",
              correct: "Look at that lion!",
              wrong: ["Look at this lion far.", "Look at that lions!"],
              distractorNotes: ["Xa → that", "Lion số ít"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Anna likes animals in the pool. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "The fish. / I like the fish too.",
              correct: "I like the fish too.",
              wrong: ["I like the bear.", "I like the horse."],
              distractorNotes: ["Bear not in pool", "Horse not in story"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-zoo-review",
          title: "Review: Zoo Speaking Mix",
          instructions: "Choose the best phrase.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Mai says the zoo is _____. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Fun! — The zoo is fun!",
              correct: "Fun!",
              wrong: ["Sad.", "Cold."],
              distractorNotes: ["Trái script", "Không nêu"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Describe the elephant near Mai. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "This is an elephant.",
              correct: "This is an elephant.",
              wrong: ["That is an elephant.", "This is a elephant."],
              distractorNotes: ["Gần → this", "Cần an"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They have a happy day. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes! A happy day at the zoo.",
              correct: "We have a happy day!",
              wrong: ["We are sad.", "We go home only."],
              distractorNotes: ["Trái bài", "Không kết bài"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-plural-animals",
      title: "Lesson 3: Plural Animals Speaking",
      learningObjective:
        "Use plural -s when talking about more than one animal.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "speaking-plural-learn",
          title: "Learn: Plural Speaking Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          content: { sceneDescription: MAI_ZOO_SCENE },
          questions: [
            buildMcq({
              questionText: "Examiner: How many monkeys? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Three. / Three monkeys.",
              correct: "Three monkeys.",
              wrong: ["Three monkey.", "One monkey."],
              distractorNotes: ["Cần -s", "Script says three"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Examiner: What are in the tree at home? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Birds. / Two birds.",
              correct: "Two birds.",
              wrong: ["Two bird.", "One birds."],
              distractorNotes: ["Cần plural", "Sai số"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-plural-practice",
          title: "Practice: More Plural Replies",
          instructions: "Choose what you would say.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          content: { sceneDescription: MAI_ZOO_SCENE },
          questions: [
            buildMcq({
              questionText: "The bears are big. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes. The bears are big.",
              correct: "The bears are big.",
              wrong: ["The bear are big.", "The bears is big."],
              distractorNotes: ["Bear số ít", "Bears + is sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The fish are orange. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes. The fish are orange.",
              correct: "The fish are orange.",
              wrong: ["The fish is orange.", "The fishs are orange."],
              distractorNotes: ["Nhiều con → are", "Fish không thêm s"],
              difficultyRating: 2,
            }),
          ],
        }),
        pluralCheck,
        buildExercise({
          slug: "speaking-plural-apply",
          title: "Apply: Quick Plural Replies",
          instructions: "Choose the best phrase for each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Say: two cats. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Two cats. — plural -s.",
              correct: "Two cats.",
              wrong: ["Two cat.", "Two caties."],
              distractorNotes: ["Thiếu -s", "Sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They see monkeys and bears. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "They see monkeys and bears. — cả hai plural.",
              correct: "They see monkeys and bears.",
              wrong: ["They see monkey and bear.", "They sees monkeys."],
              distractorNotes: ["Thiếu -s", "Sees số ít"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-plural-review",
          title: "Review: Plural Animals Speaking Mix",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "I can see three _____. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Monkeys — three + plural.",
              correct: "monkeys",
              wrong: ["monkey", "monkies"],
              distractorNotes: ["Thiếu -s", "Sai chính tả"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The birds _____ in the tree. You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Are — birds số nhiều.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is số ít", "Am với I"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Say one sentence with plural animals. Best:",
              skillTag: "speaking",
              topicTag,
              explanation: "Two birds are in the tree.",
              correct: "Two birds are in the tree.",
              wrong: ["Two bird is in the tree.", "Two birds is in the tree."],
              distractorNotes: ["Thiếu -s và are", "Birds + is sai"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
