/** Starters U4 — writing lessons (3 × 5 exercises; only Check is AI). */

export function writingLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  writingChecks,
  topicTag,
}) {
  const [petsCheck, zooCheck, pluralCheck] = writingChecks;

  return [
    {
      slug: "writing-pets",
      title: "Lesson 1: Write About Pets",
      learningObjective:
        "Write short phrases about pets using this and animal words.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-pets-learn",
          title: "Learn: Pet Writing Frames",
          instructions: "Complete the sentences about pets.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: This is my [0]. | That is my [1]. | I have two [2].",
              skillTag: "writing",
              topicTag,
              explanation: "cat; dog; pets — this/that + pet words.",
              template: "This is my [0]. That is my [1]. I have two [2].",
              correctAnswers: ["cat", "dog", "pets"],
              acceptableAnswers: [
                ["cat", "Cat"],
                ["dog", "Dog"],
                ["pets", "Pets", "animals"],
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-pets-practice",
          title: "Practice: Order Pet Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: This / is / my / cat.",
              skillTag: "writing",
              topicTag,
              explanation: "This is my cat. — viết về thú cưng gần.",
              words: ["This", "is", "my", "cat."],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: That / is / my / dog.",
              skillTag: "writing",
              topicTag,
              explanation: "That is my dog. — thú cưng xa hơn.",
              words: ["That", "is", "my", "dog."],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
          ],
        }),
        petsCheck,
        buildExercise({
          slug: "writing-pets-apply",
          title: "Apply: Choose the Best Pet Sentence",
          instructions: "Choose the best written sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best sentence about Mai's cat:",
              skillTag: "writing",
              topicTag,
              explanation: "This is my cat. It is small. — this + is + mô tả.",
              correct: "This is my cat. It is small.",
              wrong: ["That is my cat near me.", "This are my cat."],
              distractorNotes: ["Gần dùng this", "Are sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best sentence about Mai's dog:",
              skillTag: "writing",
              topicTag,
              explanation: "That is my dog. It is big.",
              correct: "That is my dog. It is big.",
              wrong: ["That are my dog.", "This is my dog far away."],
              distractorNotes: ["Are sai", "Xa thường that"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-pets-review",
          title: "Review: Pet Writing",
          instructions: "Complete the writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 4,
          questions: [
            buildGapFill({
              questionText: "Complete: Mai has a [0] cat. | The [1] is big. | One cat and one [2].",
              skillTag: "writing",
              topicTag,
              explanation: "small; dog; dog — mô tả pets Mai.",
              template: "Mai has a [0] cat. The [1] is big. One cat and one [2].",
              correctAnswers: ["small", "dog", "dog"],
              acceptableAnswers: [
                ["small", "Small"],
                ["dog", "Dog"],
                ["dog", "Dog"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "writing-zoo",
      title: "Lesson 2: Write About the Zoo",
      learningObjective:
        "Write short sentences about animals at the zoo.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-zoo-learn",
          title: "Learn: Zoo Writing Frames",
          instructions: "Complete each sentence about the zoo.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: Mai goes to the [0]. | This is an [1]. | That [2] is far away.",
              skillTag: "writing",
              topicTag,
              explanation: "zoo; elephant; tiger — this/that at zoo.",
              template: "Mai goes to the [0]. This is an [1]. That [2] is far away.",
              correctAnswers: ["zoo", "elephant", "tiger"],
              acceptableAnswers: [
                ["zoo", "Zoo"],
                ["elephant", "Elephant"],
                ["tiger", "Tiger"],
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-zoo-practice",
          title: "Practice: Order Zoo Sentences",
          instructions: "Put words in order to make sentences.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: This / is / an / elephant.",
              skillTag: "writing",
              topicTag,
              explanation: "This is an elephant. — voi gần.",
              words: ["This", "is", "an", "elephant."],
              correctOrder: [0, 1, 2, 3],
            }),
            buildSentenceOrdering({
              questionText: "Make: Look / at / that / lion!",
              skillTag: "writing",
              topicTag,
              explanation: "Look at that lion! — Nam at zoo.",
              words: ["Look", "at", "that", "lion!"],
              correctOrder: [0, 1, 2, 3],
              difficultyRating: 2,
            }),
          ],
        }),
        zooCheck,
        buildExercise({
          slug: "writing-zoo-apply",
          title: "Apply: More Zoo Frames",
          instructions: "Complete the writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: Anna likes the [0]. | Mai's favourite is the [1]. | They have a happy day at the [2].",
              skillTag: "writing",
              topicTag,
              explanation: "fish; monkey; zoo — chi tiết bài đọc.",
              template: "Anna likes the [0]. Mai's favourite is the [1]. They have a happy day at the [2].",
              correctAnswers: ["fish", "monkey", "zoo"],
              acceptableAnswers: [
                ["fish", "Fish"],
                ["monkey", "Monkey"],
                ["zoo", "Zoo"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-zoo-review",
          title: "Review: Zoo Writing Quiz",
          instructions: "Choose the best sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best sentence about the elephant:",
              skillTag: "writing",
              topicTag,
              explanation: "This is an elephant. — gần → this + an.",
              correct: "This is an elephant.",
              wrong: ["This is a elephant.", "That is an elephant near."],
              distractorNotes: ["Elephant cần an", "Gần dùng this"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best sentence about the tiger:",
              skillTag: "writing",
              topicTag,
              explanation: "That tiger is far away.",
              correct: "That tiger is far away.",
              wrong: ["This tiger is far away.", "That tigers is far away."],
              distractorNotes: ["Xa dùng that", "Tigers + is sai"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Mai, Nam and Anna go to the _____.",
              skillTag: "writing",
              topicTag,
              explanation: "Zoo — on Saturday.",
              correct: "zoo",
              wrong: ["school", "shop"],
              distractorNotes: ["Không đi học", "Không mua sắm"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "writing-plural-animals",
      title: "Lesson 3: Write Plural Animals",
      learningObjective:
        "Write short phrases using plural -s (cats, dogs, birds).",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "writing-plural-learn",
          title: "Learn: Plural Animal Writing",
          instructions: "Complete sentences with plural forms.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: two [0] | three [1] | The [2] are in the tree.",
              skillTag: "writing",
              topicTag,
              explanation: "cats; dogs; birds — thêm -s.",
              template: "two [0] | three [1] | The [2] are in the tree.",
              correctAnswers: ["cats", "dogs", "birds"],
              acceptableAnswers: [
                ["cats", "Cats"],
                ["dogs", "Dogs"],
                ["birds", "Birds"],
              ],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-plural-practice",
          title: "Practice: Order Plural Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Two / birds / are / in / the / tree.",
              skillTag: "writing",
              topicTag,
              explanation: "Two birds are in the tree.",
              words: ["Two", "birds", "are", "in", "the", "tree."],
              correctOrder: [0, 1, 2, 3, 4, 5],
            }),
            buildSentenceOrdering({
              questionText: "Make: I / can / see / three / monkeys.",
              skillTag: "writing",
              topicTag,
              explanation: "I can see three monkeys. — plural at zoo.",
              words: ["I", "can", "see", "three", "monkeys."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        pluralCheck,
        buildExercise({
          slug: "writing-plural-apply",
          title: "Apply: Write Plural Frames",
          instructions: "Complete the gap-fill writing frames.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText: "Complete: They see [0]. | The [1] are big. | The fish [2] orange.",
              skillTag: "writing",
              topicTag,
              explanation: "monkeys; bears; are — plural + are.",
              template: "They see [0]. The [1] are big. The fish [2] orange.",
              correctAnswers: ["monkeys", "bears", "are"],
              acceptableAnswers: [
                ["monkeys", "Monkeys"],
                ["bears", "Bears"],
                ["are"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "writing-plural-review",
          title: "Review: Plural Animals Writing Mix",
          instructions: "Choose or complete plural frames.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best written phrase:",
              skillTag: "writing",
              topicTag,
              explanation: "Three monkeys — số + plural.",
              correct: "three monkeys",
              wrong: ["three monkey", "three monkies"],
              distractorNotes: ["Thiếu -s", "Sai chính tả"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which is wrong to write?",
              skillTag: "writing",
              topicTag,
              explanation: "Two cat sai — phải two cats.",
              correct: "two cat",
              wrong: ["two cats", "two birds"],
              distractorNotes: ["Đúng", "Đúng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The bears _____ big.",
              skillTag: "writing",
              topicTag,
              explanation: "Are — bears số nhiều.",
              correct: "are",
              wrong: ["is", "am"],
              distractorNotes: ["Is số ít", "Am với I"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
