import type {
  YleMockBlueprint,
  YleMockPartBlueprint,
  YleMockSectionBlueprint,
} from "@/lib/mock-blueprints/yle-mock-blueprint-types";
import {
  YLE_LESSON_BLUEPRINT_REFS,
  YLE_LEVEL_METADATA,
  buildDefaultCoverageRules,
  buildDefaultDifficultyPolicy,
} from "@/lib/mock-blueprints/yle-coverage";

function startersListeningParts(): YleMockPartBlueprint[] {
  return [
    {
      partSlug: "listening-part-1-link",
      partTitle: "Part 1 — Link names to pictures",
      skillCategory: "listening",
      displayOrder: 1,
      intendedQuestionCount: 5,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 5,
      allowedQuestionTypeKeys: ["matching", "mcq_listening"],
      mediaExpectations: { audio: true, image: true, passage: false },
      answerFormatNotes: "One link or selection per item.",
      authoringNotes: "YLE Listening Part 1 — draw lines between people and objects.",
      childFriendlyConstraints: "Slow, clear audio; familiar names and objects.",
      runtimeSupport: "supported",
      curriculumTaskTypeRefs: ["Listen and draw lines between people and objects"],
    },
    {
      partSlug: "listening-part-2-write",
      partTitle: "Part 2 — Write words or numbers",
      skillCategory: "listening",
      displayOrder: 2,
      intendedQuestionCount: 5,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 5,
      allowedQuestionTypeKeys: ["gap_fill", "mcq_listening"],
      mediaExpectations: { audio: true, image: true, passage: false },
      answerFormatNotes: "Single word or number per gap.",
      authoringNotes: "Map to gap_fill with short accepted answers.",
      childFriendlyConstraints: "Spellings must match YLE Starters word list.",
      runtimeSupport: "supported",
      curriculumTaskTypeRefs: ["Listen and write words or numbers"],
    },
    {
      partSlug: "listening-part-3-tick",
      partTitle: "Part 3 — Tick the correct picture",
      skillCategory: "listening",
      displayOrder: 3,
      intendedQuestionCount: 5,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 5,
      allowedQuestionTypeKeys: ["mcq_listening", "mcq_image"],
      mediaExpectations: { audio: true, image: true, passage: false },
      answerFormatNotes: "Single correct picture per item.",
      authoringNotes: "Short conversations; 3 picture options.",
      childFriendlyConstraints: "Avoid trick distractors — one clearly wrong option.",
      runtimeSupport: "partial",
      curriculumTaskTypeRefs: ["Listen to short conversations and tick a picture"],
    },
    {
      partSlug: "listening-part-4-colour",
      partTitle: "Part 4 — Colour and draw",
      skillCategory: "listening",
      displayOrder: 4,
      intendedQuestionCount: 5,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 5,
      allowedQuestionTypeKeys: ["mcq_listening"],
      mediaExpectations: { audio: true, image: true, passage: false },
      answerFormatNotes: "Exam uses colouring — proxy with picture MCQ in CAMBA.",
      authoringNotes: "Blueprint-only fidelity; use mcq_image proxy for auto-scored mocks.",
      childFriendlyConstraints: "Instructions must be one action per sentence.",
      runtimeSupport: "blueprint_only",
      curriculumTaskTypeRefs: ["Listen to colour and draw"],
    },
  ];
}

function startersReadingWritingParts(): YleMockPartBlueprint[] {
  return [
    {
      partSlug: "rw-part-1-match-words",
      partTitle: "Part 1 — Match words to pictures",
      skillCategory: "reading_writing",
      displayOrder: 1,
      intendedQuestionCount: 5,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 6,
      allowedQuestionTypeKeys: ["mcq_image", "matching"],
      mediaExpectations: { audio: false, image: true, passage: false },
      answerFormatNotes: "Word ↔ picture association.",
      authoringNotes: "High-frequency nouns from Starters themes.",
      childFriendlyConstraints: "One clear picture per word.",
      runtimeSupport: "supported",
      curriculumTaskTypeRefs: ["Match words to pictures"],
    },
    {
      partSlug: "rw-part-2-sentences",
      partTitle: "Part 2 — Sentences and pictures",
      skillCategory: "reading_writing",
      displayOrder: 2,
      intendedQuestionCount: 5,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 6,
      allowedQuestionTypeKeys: ["mcq_single", "mcq_image"],
      mediaExpectations: { audio: false, image: true, passage: false },
      answerFormatNotes: "Choose picture matching a short sentence.",
      authoringNotes: "Sentences ≤ 10 words.",
      childFriendlyConstraints: "Present simple only.",
      runtimeSupport: "supported",
      curriculumTaskTypeRefs: ["Read short sentences and choose matching pictures"],
    },
    {
      partSlug: "rw-part-3-dialogues",
      partTitle: "Part 3 — Short dialogues",
      skillCategory: "reading_writing",
      displayOrder: 3,
      intendedQuestionCount: 5,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 7,
      allowedQuestionTypeKeys: ["reading_comprehension", "mcq_single"],
      mediaExpectations: { audio: false, image: false, passage: true },
      answerFormatNotes: "MCQ over 2–4 line dialogues.",
      authoringNotes: "Shared dialogue per item group optional in M1.2.",
      childFriendlyConstraints: "Familiar classroom/home contexts.",
      runtimeSupport: "partial",
      curriculumTaskTypeRefs: ["Read short dialogues and select answers"],
    },
    {
      partSlug: "rw-part-4-read-write",
      partTitle: "Part 4 — Read and write",
      skillCategory: "reading_writing",
      displayOrder: 4,
      intendedQuestionCount: 3,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 6,
      allowedQuestionTypeKeys: ["gap_fill", "writing_copy"],
      mediaExpectations: { audio: false, image: true, passage: false },
      answerFormatNotes: "Complete words with picture support.",
      authoringNotes: "Use gap_fill for auto-scored practice; writing_copy is blueprint-only.",
      childFriendlyConstraints: "Missing letters only — no free paragraphs.",
      runtimeSupport: "partial",
      curriculumTaskTypeRefs: ["Read and write words and short phrases with picture support"],
    },
    {
      partSlug: "rw-part-5-questions",
      partTitle: "Part 5 — Answer questions",
      skillCategory: "reading_writing",
      displayOrder: 5,
      intendedQuestionCount: 2,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 5,
      allowedQuestionTypeKeys: ["gap_fill", "writing_copy"],
      mediaExpectations: { audio: false, image: true, passage: false },
      answerFormatNotes: "Single word/phrase answers about a picture.",
      authoringNotes: "Proxy with gap_fill until writing mock flow exists.",
      childFriendlyConstraints: "Questions about visible picture content only.",
      runtimeSupport: "blueprint_only",
      curriculumTaskTypeRefs: ["Answer short questions with single words or phrases"],
    },
  ];
}

function moversListeningParts(): YleMockPartBlueprint[] {
  return [
    {
      partSlug: "listening-part-1-pictures",
      partTitle: "Part 1 — Picture descriptions",
      skillCategory: "listening",
      displayOrder: 1,
      intendedQuestionCount: 5,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 6,
      allowedQuestionTypeKeys: ["mcq_listening", "mcq_image"],
      mediaExpectations: { audio: true, image: true, passage: false },
      answerFormatNotes: "Select picture matching description.",
      authoringNotes: "Movers Listening Part 1 style.",
      childFriendlyConstraints: "Clear adjectives; no abstract vocabulary.",
      runtimeSupport: "partial",
      curriculumTaskTypeRefs: ["Listen and draw lines between people and objects"],
    },
    {
      partSlug: "listening-part-2-fill",
      partTitle: "Part 2 — Fill in blanks",
      skillCategory: "listening",
      displayOrder: 2,
      intendedQuestionCount: 5,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 6,
      allowedQuestionTypeKeys: ["gap_fill", "mcq_listening"],
      mediaExpectations: { audio: true, image: true, passage: false },
      answerFormatNotes: "Words/numbers in a scene.",
      authoringNotes: "gap_fill with audio script.",
      childFriendlyConstraints: "A1 word list spellings.",
      runtimeSupport: "supported",
      curriculumTaskTypeRefs: ["Listen and write words or numbers"],
    },
    {
      partSlug: "listening-part-3-dialogues",
      partTitle: "Part 3 — Dialogues",
      skillCategory: "listening",
      displayOrder: 3,
      intendedQuestionCount: 5,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 6,
      allowedQuestionTypeKeys: ["mcq_listening"],
      mediaExpectations: { audio: true, image: true, passage: false },
      answerFormatNotes: "Choose correct response or picture.",
      authoringNotes: "Short exchanges; 3 options.",
      childFriendlyConstraints: "Routine social language.",
      runtimeSupport: "partial",
      curriculumTaskTypeRefs: ["Listen to short conversations and tick a picture"],
    },
    {
      partSlug: "listening-part-4-colour",
      partTitle: "Part 4 — Colour and draw",
      skillCategory: "listening",
      displayOrder: 4,
      intendedQuestionCount: 5,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 6,
      allowedQuestionTypeKeys: ["mcq_listening", "mcq_image"],
      mediaExpectations: { audio: true, image: true, passage: false },
      answerFormatNotes: "Proxy colouring with picture MCQ.",
      authoringNotes: "Blueprint-only exam fidelity.",
      childFriendlyConstraints: "One instruction per utterance.",
      runtimeSupport: "blueprint_only",
      curriculumTaskTypeRefs: ["Listen to colour and draw"],
    },
  ];
}

function moversReadingWritingParts(): YleMockPartBlueprint[] {
  return [
    {
      partSlug: "rw-part-1-definitions",
      partTitle: "Part 1 — Definitions",
      skillCategory: "reading_writing",
      displayOrder: 1,
      intendedQuestionCount: 6,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 7,
      allowedQuestionTypeKeys: ["matching", "mcq_single"],
      mediaExpectations: { audio: false, image: false, passage: false },
      answerFormatNotes: "Match definition to word.",
      authoringNotes: "Movers R&W Part 1.",
      childFriendlyConstraints: "Definitions use known vocabulary only.",
      runtimeSupport: "supported",
      curriculumTaskTypeRefs: ["Match definitions to words"],
    },
    {
      partSlug: "rw-part-2-conversations",
      partTitle: "Part 2 — Conversations",
      skillCategory: "reading_writing",
      displayOrder: 2,
      intendedQuestionCount: 6,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 8,
      allowedQuestionTypeKeys: ["reading_comprehension", "mcq_single"],
      mediaExpectations: { audio: false, image: false, passage: true },
      answerFormatNotes: "Choose best reply in dialogue.",
      authoringNotes: "Shared dialogue blocks in M1.2 importer.",
      childFriendlyConstraints: "Social formulas and routines.",
      runtimeSupport: "partial",
      curriculumTaskTypeRefs: ["Read conversations and choose correct responses"],
    },
    {
      partSlug: "rw-part-3-story",
      partTitle: "Part 3 — Story completion",
      skillCategory: "reading_writing",
      displayOrder: 3,
      intendedQuestionCount: 6,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 8,
      allowedQuestionTypeKeys: ["gap_fill", "mcq_single", "sentence_ordering"],
      mediaExpectations: { audio: false, image: true, passage: true },
      answerFormatNotes: "Complete story sentences.",
      authoringNotes: "Chronological 5–10 sentence stories.",
      childFriendlyConstraints: "Past simple limited to taught verbs.",
      runtimeSupport: "supported",
      curriculumTaskTypeRefs: ["Read stories and complete sentences"],
    },
    {
      partSlug: "rw-part-4-messages",
      partTitle: "Part 4 — Messages and notes",
      skillCategory: "reading_writing",
      displayOrder: 4,
      intendedQuestionCount: 6,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 8,
      allowedQuestionTypeKeys: ["form_completion", "gap_fill", "writing_message"],
      mediaExpectations: { audio: false, image: false, passage: true },
      answerFormatNotes: "Short note completion.",
      authoringNotes: "Split forms into gap_fill items for M1.2.",
      childFriendlyConstraints: "Authentic but simple note formats.",
      runtimeSupport: "partial",
      curriculumTaskTypeRefs: ["Read and write short messages and notes"],
    },
    {
      partSlug: "rw-part-5-writing",
      partTitle: "Part 5 — Guided writing",
      skillCategory: "reading_writing",
      displayOrder: 5,
      intendedQuestionCount: 6,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 8,
      allowedQuestionTypeKeys: ["writing_message", "gap_fill"],
      mediaExpectations: { audio: false, image: true, passage: false },
      answerFormatNotes: "Picture prompt writing — blueprint-only in runtime.",
      authoringNotes: "Use gap_fill sentence frames for practice mocks.",
      childFriendlyConstraints: "3–4 sentence maximum with prompts.",
      runtimeSupport: "blueprint_only",
      curriculumTaskTypeRefs: ["Read and write short messages and notes"],
    },
  ];
}

function flyersListeningParts(): YleMockPartBlueprint[] {
  return moversListeningParts().map((p) => ({
    ...p,
    intendedQuestionCount: 6,
    authoringNotes: `${p.authoringNotes} Flyers — slightly longer recordings.`,
    childFriendlyConstraints: `${p.childFriendlyConstraints} A2 vocabulary ceiling.`,
  }));
}

function flyersReadingWritingParts(): YleMockPartBlueprint[] {
  return [
    {
      partSlug: "rw-part-1-headings",
      partTitle: "Part 1 — Match headings or sentences",
      skillCategory: "reading_writing",
      displayOrder: 1,
      intendedQuestionCount: 7,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 8,
      allowedQuestionTypeKeys: ["matching", "mcq_single"],
      mediaExpectations: { audio: false, image: false, passage: true },
      answerFormatNotes: "Match sentence to paragraph or heading.",
      authoringNotes: "Flyers R&W Part 1.",
      childFriendlyConstraints: "Paragraphs ≤ 40 words each.",
      runtimeSupport: "supported",
      curriculumTaskTypeRefs: ["Match headings or sentences to paragraphs"],
    },
    {
      partSlug: "rw-part-2-dialogues",
      partTitle: "Part 2 — Complete dialogues",
      skillCategory: "reading_writing",
      displayOrder: 2,
      intendedQuestionCount: 6,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 8,
      allowedQuestionTypeKeys: ["gap_fill", "mcq_single", "reading_comprehension"],
      mediaExpectations: { audio: false, image: false, passage: true },
      answerFormatNotes: "Insert missing sentence in conversation.",
      authoringNotes: "MCQ or gap_fill for missing line.",
      childFriendlyConstraints: "Cohesive dialogue logic.",
      runtimeSupport: "partial",
      curriculumTaskTypeRefs: ["Complete conversations with missing sentences"],
    },
    {
      partSlug: "rw-part-3-story-gaps",
      partTitle: "Part 3 — Story gaps",
      skillCategory: "reading_writing",
      displayOrder: 3,
      intendedQuestionCount: 7,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 9,
      allowedQuestionTypeKeys: ["gap_fill", "mcq_single"],
      mediaExpectations: { audio: false, image: false, passage: true },
      answerFormatNotes: "Closed-gap story completion.",
      authoringNotes: "Stories up to ~150 words.",
      childFriendlyConstraints: "Past simple + connectors (then, because).",
      runtimeSupport: "supported",
      curriculumTaskTypeRefs: ["Read stories and complete gaps"],
    },
    {
      partSlug: "rw-part-4-messages",
      partTitle: "Part 4 — Messages and emails",
      skillCategory: "reading_writing",
      displayOrder: 4,
      intendedQuestionCount: 7,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 9,
      allowedQuestionTypeKeys: ["form_completion", "gap_fill"],
      mediaExpectations: { audio: false, image: false, passage: true },
      answerFormatNotes: "Email/note field completion.",
      authoringNotes: "Multi-gap forms split per field in importer.",
      childFriendlyConstraints: "Informal email register for children.",
      runtimeSupport: "partial",
      curriculumTaskTypeRefs: ["Read and write longer messages, emails, and stories"],
    },
    {
      partSlug: "rw-part-5-writing",
      partTitle: "Part 5 — Story or message writing",
      skillCategory: "reading_writing",
      displayOrder: 5,
      intendedQuestionCount: 6,
      defaultPointsPerQuestion: 1,
      timeGuidanceMinutes: 10,
      allowedQuestionTypeKeys: ["writing_message", "gap_fill", "sentence_ordering"],
      mediaExpectations: { audio: false, image: true, passage: false },
      answerFormatNotes: "Guided story with picture series — blueprint-only free writing.",
      authoringNotes: "sentence_ordering for story panels; gap_fill for frames.",
      childFriendlyConstraints: "Prompt every sentence in practice mocks.",
      runtimeSupport: "blueprint_only",
      curriculumTaskTypeRefs: ["Read and write longer messages, emails, and stories"],
    },
  ];
}

function speakingSection(level: "starters" | "movers" | "flyers"): YleMockSectionBlueprint {
  const counts = { starters: 4, movers: 4, flyers: 4 };
  const parts: YleMockPartBlueprint[] = [
    {
      partSlug: "speaking-part-1-interview",
      partTitle: "Part 1 — Personal questions",
      skillCategory: "speaking",
      displayOrder: 1,
      intendedQuestionCount: counts[level],
      defaultPointsPerQuestion: 0,
      timeGuidanceMinutes: 4,
      allowedQuestionTypeKeys: ["speaking_interview"],
      mediaExpectations: { audio: false, image: false, passage: false },
      answerFormatNotes: "Examiner interview — not auto-scored.",
      authoringNotes: "Tracked for full-form blueprint; exclude from practice mock imports.",
      childFriendlyConstraints: "Formulaic personal questions.",
      runtimeSupport: "blueprint_only",
      curriculumTaskTypeRefs: ["Answer personal questions"],
    },
    {
      partSlug: "speaking-part-2-story",
      partTitle: "Part 2 — Picture story",
      skillCategory: "speaking",
      displayOrder: 2,
      intendedQuestionCount: counts[level],
      defaultPointsPerQuestion: 0,
      timeGuidanceMinutes: 4,
      allowedQuestionTypeKeys: ["speaking_picture_story"],
      mediaExpectations: { audio: false, image: true, passage: false },
      answerFormatNotes: "Describe picture sequence.",
      authoringNotes: "Blueprint-only.",
      childFriendlyConstraints: "4–6 panel stories.",
      runtimeSupport: "blueprint_only",
      curriculumTaskTypeRefs: ["Describe pictures in a picture story"],
    },
    {
      partSlug: "speaking-part-3-compare",
      partTitle: "Part 3 — Compare pictures",
      skillCategory: "speaking",
      displayOrder: 3,
      intendedQuestionCount: 2,
      defaultPointsPerQuestion: 0,
      timeGuidanceMinutes: 3,
      allowedQuestionTypeKeys: ["speaking_picture_story", "speaking_interview"],
      mediaExpectations: { audio: false, image: true, passage: false },
      answerFormatNotes: "Spot differences / compare.",
      authoringNotes: "Movers/Flyers speaking — blueprint-only.",
      childFriendlyConstraints: "Simple contrast vocabulary.",
      runtimeSupport: "blueprint_only",
      curriculumTaskTypeRefs: ["Compare and contrast two pictures"],
    },
    {
      partSlug: "speaking-part-4-questions",
      partTitle: "Part 4 — Personalised questions",
      skillCategory: "speaking",
      displayOrder: 4,
      intendedQuestionCount: 2,
      defaultPointsPerQuestion: 0,
      timeGuidanceMinutes: 3,
      allowedQuestionTypeKeys: ["speaking_interview"],
      mediaExpectations: { audio: false, image: true, passage: false },
      answerFormatNotes: "Follow-up questions linked to story.",
      authoringNotes: "Blueprint-only.",
      childFriendlyConstraints: "Supportive examiner prompts.",
      runtimeSupport: "blueprint_only",
      curriculumTaskTypeRefs: ["Personalised questions linked to picture story"],
    },
  ];

  return {
    sectionSlug: "speaking",
    sectionTitle: "Speaking (blueprint reference)",
    skillCategory: "speaking",
    displayOrder: 3,
    timeGuidanceMinutes: 12,
    parts,
  };
}

function buildYleBlueprint(
  level: "starters" | "movers" | "flyers",
  listeningParts: YleMockPartBlueprint[],
  rwParts: YleMockPartBlueprint[]
): YleMockBlueprint {
  const meta = YLE_LEVEL_METADATA[level];
  const lessonRef = YLE_LESSON_BLUEPRINT_REFS[level];

  const listeningSection: YleMockSectionBlueprint = {
    sectionSlug: "listening",
    sectionTitle: "Listening",
    skillCategory: "listening",
    displayOrder: 1,
    timeGuidanceMinutes: 20,
    parts: listeningParts,
  };

  const rwSection: YleMockSectionBlueprint = {
    sectionSlug: "reading-writing",
    sectionTitle: "Reading & Writing",
    skillCategory: "reading_writing",
    displayOrder: 2,
    timeGuidanceMinutes: 25,
    parts: rwParts,
  };

  return {
    blueprintId: `yle-${level}-practice-v1`,
    blueprintVersion: "1.0.0",
    level: meta,
    formKind: "practice",
    title: `${meta.displayTitle} — Practice Mock Blueprint`,
    description: `Canonical M1.1 practice mock architecture for ${meta.displayTitle}. Speaking section is blueprint reference only.`,
    sections: [listeningSection, rwSection, speakingSection(level)],
    difficultyPolicy: buildDefaultDifficultyPolicy(level),
    coverageRules: buildDefaultCoverageRules(level),
    lessonBlueprintRefs: [
      {
        levelSlug: level,
        blueprintPath: lessonRef.blueprintPath,
        generatedContentPath: lessonRef.generatedContentPath,
        reuseNotes: lessonRef.reuseNotes,
      },
    ],
  };
}

export const STARTERS_PRACTICE_MOCK_BLUEPRINT: YleMockBlueprint = buildYleBlueprint(
  "starters",
  startersListeningParts(),
  startersReadingWritingParts()
);

export const MOVERS_PRACTICE_MOCK_BLUEPRINT: YleMockBlueprint = buildYleBlueprint(
  "movers",
  moversListeningParts(),
  moversReadingWritingParts()
);

export const FLYERS_PRACTICE_MOCK_BLUEPRINT: YleMockBlueprint = buildYleBlueprint(
  "flyers",
  flyersListeningParts(),
  flyersReadingWritingParts()
);

export const YLE_MOCK_BLUEPRINT_REGISTRY: Record<
  import("@/lib/mock-blueprints/yle-mock-blueprint-types").YleLevelSlug,
  YleMockBlueprint
> = {
  starters: STARTERS_PRACTICE_MOCK_BLUEPRINT,
  movers: MOVERS_PRACTICE_MOCK_BLUEPRINT,
  flyers: FLYERS_PRACTICE_MOCK_BLUEPRINT,
};

export const ALL_YLE_MOCK_BLUEPRINTS = Object.values(YLE_MOCK_BLUEPRINT_REGISTRY);
