import type {
  YleBlueprintQuestionTypeKey,
  YleMockQuestionTypeBlueprint,
} from "@/lib/mock-blueprints/yle-mock-blueprint-types";

/**
 * Canonical question-type contracts for YLE mock blueprints.
 * Maps blueprint families → CAMBA `question_type` where runtime supports auto-scoring.
 */
export const YLE_MOCK_QUESTION_TYPE_REGISTRY: Record<
  YleBlueprintQuestionTypeKey,
  YleMockQuestionTypeBlueprint
> = {
  mcq_single: {
    key: "mcq_single",
    label: "Multiple choice (single answer)",
    description: "One correct option from 3–4 text choices.",
    cambaQuestionType: "multiple_choice",
    runtimeSupport: "supported",
    answerShape: "single_choice",
    requiredContentFields: ["question_text", "choices"],
    optionalContentFields: ["explanation", "media_url", "skillTag", "topicTag"],
    mediaRequirements: { audio: false, image: false, passage: false },
    scoringAssumption: "Single correct choice earns full part points.",
    reviewModeNotes: "Show correct choice highlight after submit.",
    authoringNotes: "Keep stems short; child-friendly vocabulary only.",
  },
  mcq_image: {
    key: "mcq_image",
    label: "Image-based multiple choice",
    description: "Choose the correct picture or image option.",
    cambaQuestionType: "image_selection",
    runtimeSupport: "supported",
    answerShape: "single_choice",
    requiredContentFields: ["question_text", "choices"],
    optionalContentFields: ["media_url", "explanation"],
    mediaRequirements: { audio: false, image: true, passage: false },
    scoringAssumption: "Same as multiple_choice.",
    reviewModeNotes: "Highlight selected and correct image options.",
    authoringNotes: "Use clear, unambiguous pictures; avoid cultural bias.",
  },
  mcq_listening: {
    key: "mcq_listening",
    label: "Listening multiple choice",
    description: "Listen to audio and select the correct answer.",
    cambaQuestionType: "listening",
    runtimeSupport: "partial",
    answerShape: "single_choice",
    requiredContentFields: ["question_text", "choices", "content.audioUrl"],
    optionalContentFields: ["content.script", "explanation"],
    mediaRequirements: { audio: true, image: false, passage: false },
    scoringAssumption: "Auto-scored when audio + choices present.",
    reviewModeNotes: "Audio replay in review not yet first-class in mock player.",
    authoringNotes: "Provide script in content; audio URL under public/audio/.",
  },
  reading_comprehension: {
    key: "reading_comprehension",
    label: "Reading comprehension",
    description: "Read passage or dialogue and answer MCQ.",
    cambaQuestionType: "reading_comprehension",
    runtimeSupport: "partial",
    answerShape: "single_choice",
    requiredContentFields: ["question_text", "choices"],
    optionalContentFields: ["content.passage"],
    mediaRequirements: { audio: false, image: false, passage: true },
    scoringAssumption: "Auto-scored MCQ over shared passage.",
    reviewModeNotes: "Passage context not yet shown in mock player — lesson pattern exists.",
    authoringNotes: "Share passage via exercise-level content when importing.",
  },
  multi_select: {
    key: "multi_select",
    label: "Multi-select",
    description: "Select all correct answers.",
    cambaQuestionType: "multi_select",
    runtimeSupport: "supported",
    answerShape: "multi_choice",
    requiredContentFields: ["question_text", "choices"],
    optionalContentFields: ["explanation"],
    mediaRequirements: { audio: false, image: false, passage: false },
    scoringAssumption: "All-or-nothing unless scoring extended later.",
    reviewModeNotes: "Show all correct options on review.",
    authoringNotes: "Rare in young YLE papers; use sparingly.",
  },
  matching: {
    key: "matching",
    label: "Matching",
    description: "Match items from two columns (names, words, pictures).",
    cambaQuestionType: "matching",
    runtimeSupport: "supported",
    answerShape: "matching_pairs",
    requiredContentFields: ["question_text", "pairs"],
    optionalContentFields: ["matchingOptions", "explanation"],
    mediaRequirements: { audio: false, image: false, passage: false },
    scoringAssumption: "Full credit when all pairs correct.",
    reviewModeNotes: "Show correct pair mapping.",
    authoringNotes: "YLE Listening Part 1 style — lines between people and objects.",
  },
  drag_drop: {
    key: "drag_drop",
    label: "Drag and drop matching",
    description: "Same scoring as matching with drag UI variant.",
    cambaQuestionType: "drag_drop",
    runtimeSupport: "supported",
    answerShape: "matching_pairs",
    requiredContentFields: ["question_text", "pairs"],
    optionalContentFields: ["matchingOptions"],
    mediaRequirements: { audio: false, image: false, passage: false },
    scoringAssumption: "Alias of matching in scoring.ts.",
    reviewModeNotes: "Rendered via Matching component.",
    authoringNotes: "Prefer matching for simpler authoring unless UI requires drag.",
  },
  gap_fill: {
    key: "gap_fill",
    label: "Gap fill",
    description: "Complete words or short phrases in a template.",
    cambaQuestionType: "gap_fill",
    runtimeSupport: "supported",
    answerShape: "gap_fill_text",
    requiredContentFields: ["question_text", "content.template", "content.correctAnswers"],
    optionalContentFields: ["content.acceptedAnswers", "explanation"],
    mediaRequirements: { audio: false, image: false, passage: false },
    scoringAssumption: "Normalized text match per gap.",
    reviewModeNotes: "Show correct answers per gap.",
    authoringNotes: "YLE Listening Part 2 / R&W completion style.",
  },
  sentence_ordering: {
    key: "sentence_ordering",
    label: "Sentence ordering",
    description: "Put words or sentences in correct order.",
    cambaQuestionType: "sentence_ordering",
    runtimeSupport: "supported",
    answerShape: "sentence_order",
    requiredContentFields: ["question_text", "content.items", "content.correctOrder"],
    optionalContentFields: ["explanation"],
    mediaRequirements: { audio: false, image: false, passage: false },
    scoringAssumption: "Exact order match.",
    reviewModeNotes: "Show correct sequence.",
    authoringNotes: "Use for short story ordering at Movers/Flyers level.",
  },
  form_completion: {
    key: "form_completion",
    label: "Form / note completion",
    description: "Complete structured form fields from reading or listening.",
    cambaQuestionType: "gap_fill",
    runtimeSupport: "partial",
    answerShape: "gap_fill_text",
    requiredContentFields: ["question_text", "content.template"],
    optionalContentFields: ["content.formFields", "content.passage"],
    mediaRequirements: { audio: false, image: false, passage: true },
    scoringAssumption: "Mapped to gap_fill when imported.",
    reviewModeNotes: "May need multiple gap_fill questions per form in M1.2.",
    authoringNotes: "Flyers/Movers message completion — split into per-field gaps for now.",
  },
  writing_copy: {
    key: "writing_copy",
    label: "Copy / complete writing",
    description: "Copy words or complete missing letters (exam R&W).",
    cambaQuestionType: "writing",
    runtimeSupport: "blueprint_only",
    answerShape: "free_text",
    requiredContentFields: ["question_text", "content.prompt"],
    optionalContentFields: ["content.rubric", "content.minWords"],
    mediaRequirements: { audio: false, image: true, passage: false },
    scoringAssumption: "Not auto-scored in mock runtime; lesson uses AI writing flow.",
    reviewModeNotes: "Deferred to M1.3+ or human review.",
    authoringNotes: "Represent in blueprint; proxy with gap_fill for auto-scored practice mocks.",
  },
  writing_message: {
    key: "writing_message",
    label: "Short message / email writing",
    description: "Write a short message or email (Flyers/Movers).",
    cambaQuestionType: "writing",
    runtimeSupport: "blueprint_only",
    answerShape: "free_text",
    requiredContentFields: ["question_text", "content.prompt"],
    optionalContentFields: ["content.taskDescription", "content.maxWords"],
    mediaRequirements: { audio: false, image: false, passage: false },
    scoringAssumption: "Human or AI scoring — not in U6 mock submit path.",
    reviewModeNotes: "Blueprint-only until writing mock flow exists.",
    authoringNotes: "Use gap_fill proxies for M1.2 practice forms if needed.",
  },
  speaking_picture_story: {
    key: "speaking_picture_story",
    label: "Speaking — picture story",
    description: "Describe a picture story (YLE Speaking).",
    cambaQuestionType: "speaking",
    runtimeSupport: "blueprint_only",
    answerShape: "audio_response",
    requiredContentFields: ["question_text", "content.prompt"],
    optionalContentFields: ["content.pictureDescription", "content.followUpQuestions"],
    mediaRequirements: { audio: false, image: true, passage: false },
    scoringAssumption: "Lesson speaking AI flow only.",
    reviewModeNotes: "Not in mock take flow.",
    authoringNotes: "Track in blueprint for full-form fidelity.",
  },
  speaking_interview: {
    key: "speaking_interview",
    label: "Speaking — interview questions",
    description: "Answer personal and picture-linked questions.",
    cambaQuestionType: "speaking",
    runtimeSupport: "blueprint_only",
    answerShape: "human_scored",
    requiredContentFields: ["question_text", "content.prompt"],
    optionalContentFields: ["content.followUpQuestions"],
    mediaRequirements: { audio: false, image: true, passage: false },
    scoringAssumption: "Examiner-led; not auto-scored.",
    reviewModeNotes: "Blueprint-only.",
    authoringNotes: "Exclude from auto-scored practice mocks until M1.3+.",
  },
};

export function getQuestionTypeBlueprint(
  key: YleBlueprintQuestionTypeKey
): YleMockQuestionTypeBlueprint {
  return YLE_MOCK_QUESTION_TYPE_REGISTRY[key];
}

export function getRuntimeSupportedQuestionTypes(): YleMockQuestionTypeBlueprint[] {
  return Object.values(YLE_MOCK_QUESTION_TYPE_REGISTRY).filter(
    (t) => t.runtimeSupport === "supported"
  );
}

export function resolveCambaQuestionType(
  key: YleBlueprintQuestionTypeKey
): string | null {
  return YLE_MOCK_QUESTION_TYPE_REGISTRY[key].cambaQuestionType;
}
