/** Movers U1 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-present-simple-habits",
      title: "Lesson 1: Present Simple Habits",
      learningObjective:
        "Use present simple to describe daily habits, including third person -s.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-habits-learn",
          title: "Learn: Daily Habits",
          instructions: "Choose the correct verb form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "I _____ up at six thirty every day.",
              skillTag: "grammar",
              topicTag,
              explanation: "I + wake up (present simple, không -s).",
              correct: "wake",
              wrong: ["wakes", "waking"],
              distractorNotes: ["He/she form", "Needs auxiliary"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh _____ breakfast with his family.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh (he) → has với third person.",
              correct: "has",
              wrong: ["have", "having"],
              distractorNotes: ["I/you form", "Not complete verb"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "They _____ to school at seven thirty.",
              skillTag: "grammar",
              topicTag,
              explanation: "They + go (plural, không -s).",
              correct: "go",
              wrong: ["goes", "going"],
              distractorNotes: ["He/she form", "Needs am/is/are"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "She _____ her homework after school.",
              skillTag: "grammar",
              topicTag,
              explanation: "She → does (do + es cho third person).",
              correct: "does",
              wrong: ["do", "doing"],
              distractorNotes: ["I/you form", "Needs auxiliary"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-habits-practice",
          title: "Practice: Complete the Habits",
          instructions: "Fill in each gap with the correct present simple form.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I [0] up at six. | He [1] breakfast at seven. | We [2] to school together.",
              skillTag: "grammar",
              topicTag,
              explanation: "wake; has; go — present simple với I/he/we.",
              template: "I [0] up at six. He [1] breakfast at seven. We [2] to school together.",
              correctAnswers: ["wake", "has", "go"],
              acceptableAnswers: [
                ["wake", "Wake"],
                ["has", "Has"],
                ["go", "Go"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-habits-check",
          title: "Check: Habits Challenge",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh _____ to bed at nine o'clock.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh (he) → goes to bed.",
              correct: "goes",
              wrong: ["go", "going"],
              distractorNotes: ["Wrong person", "Incomplete"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Present simple thói quen — không dùng am/is + V-ing.",
              correct: "I brush my teeth every morning.",
              wrong: [
                "I am brush my teeth every morning.",
                "I brushing my teeth every morning.",
              ],
              distractorNotes: ["Wrong tense", "Missing auxiliary"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "My friends _____ lunch at school.",
              skillTag: "grammar",
              topicTag,
              explanation: "Friends (plural) → have lunch.",
              correct: "have",
              wrong: ["has", "having"],
              distractorNotes: ["Singular form", "Incomplete"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-habits-apply",
          title: "Apply: Build Routine Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: I / wake up / at / six thirty / every day.",
              skillTag: "grammar",
              topicTag,
              explanation: "I wake up at six thirty every day.",
              words: ["I", "wake up", "at", "six thirty", "every day."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Minh / has / breakfast / with / his family.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh has breakfast with his family.",
              words: ["Minh", "has", "breakfast", "with", "his family."],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-habits-review",
          title: "Review: Present Simple Mix",
          instructions: "Choose the correct verb form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Every day Linh _____ to school at seven thirty.",
              skillTag: "grammar",
              topicTag,
              explanation: "Linh (she) → goes với third person -s.",
              correct: "goes",
              wrong: ["go", "going"],
              distractorNotes: ["I/you/we/they", "Cần am/is/are"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We _____ lunch at twelve.",
              skillTag: "grammar",
              topicTag,
              explanation: "We (số nhiều) → have, không has.",
              correct: "have",
              wrong: ["has", "having"],
              distractorNotes: ["He/she/it", "Không đủ"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Present simple thói quen — I do my homework.",
              correct: "I do my homework after school.",
              wrong: ["I am do my homework.", "I doing homework after school."],
              distractorNotes: ["Thừa am", "Thiếu động từ"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-frequency-position",
      title: "Lesson 2: Adverbs of Frequency",
      learningObjective:
        "Place always, sometimes and never correctly before the main verb.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-frequency-learn",
          title: "Learn: Adverb Position",
          instructions: "Choose the sentence with correct adverb position.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Always đứng trước động từ chính do.",
              correct: "I always do my homework.",
              wrong: ["I do always my homework.", "Always I do my homework."],
              distractorNotes: ["Adverb after verb", "Adverb before subject"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Sometimes trước play.",
              correct: "She sometimes plays football.",
              wrong: [
                "She plays sometimes football.",
                "Sometimes plays she football.",
              ],
              distractorNotes: ["Wrong position", "Wrong word order"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Never trước watch.",
              correct: "He never watches TV before homework.",
              wrong: [
                "He watches never TV before homework.",
                "Never he watches TV.",
              ],
              distractorNotes: ["Wrong position", "Wrong word order"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "They are _____ hungry before dinner.",
              skillTag: "grammar",
              topicTag,
              explanation: "Với be → adverb sau am/is/are: are always.",
              correct: "always",
              wrong: ["always are", "never is"],
              distractorNotes: ["Wrong order with be", "Wrong verb"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-frequency-practice",
          title: "Practice: Add the Adverb",
          instructions: "Complete each sentence with the adverb in brackets.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I [0] brush my teeth. (always) | Minh [1] plays football. (sometimes) | She [2] watches TV before homework. (never)",
              skillTag: "grammar",
              topicTag,
              explanation: "always; sometimes; never — trước động từ chính.",
              template:
                "I [0] brush my teeth. Minh [1] plays football. She [2] watches TV before homework.",
              correctAnswers: ["always", "sometimes", "never"],
              acceptableAnswers: [
                ["always", "Always"],
                ["sometimes", "Sometimes"],
                ["never", "Never"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-frequency-check",
          title: "Check: Frequency Grammar",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh _____ forgets to brush his teeth.",
              skillTag: "grammar",
              topicTag,
              explanation: "Never = không bao giờ quên → never forgets.",
              correct: "never",
              wrong: ["always", "sometimes"],
              distractorNotes: ["Would mean he forgets", "Uncertain"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "We are always — adverb sau are.",
              correct: "We are always tired after school.",
              wrong: [
                "We always are tired after school.",
                "We are tired always after school.",
              ],
              distractorNotes: ["Unnatural with be", "Wrong position"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "I _____ have rice for breakfast.",
              skillTag: "grammar",
              topicTag,
              explanation: "Every day có thể đứng cuối hoặc đầu; ở đây cuối câu.",
              correct: "always",
              wrong: ["never", "sometimes"],
              distractorNotes: ["Opposite habit", "Not every day"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-frequency-apply",
          title: "Apply: Order the Words",
          instructions: "Put the words in order to make correct sentences.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: I / never / watch / TV / before / homework.",
              skillTag: "grammar",
              topicTag,
              explanation: "I never watch TV before homework.",
              words: ["I", "never", "watch", "TV", "before", "homework."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: She / sometimes / plays / football / after / school.",
              skillTag: "grammar",
              topicTag,
              explanation: "She sometimes plays football after school.",
              words: ["She", "sometimes", "plays", "football", "after", "school."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-frequency-review",
          title: "Review: Adverb Position Mix",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Never đứng trước watch.",
              correct: "I never eat dinner before six.",
              wrong: ["I eat never dinner before six.", "Never I eat dinner."],
              distractorNotes: ["Sai vị trí trạng từ", "Sai trật tự"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh _____ plays football after homework.",
              skillTag: "grammar",
              topicTag,
              explanation: "Sometimes — đôi khi chơi, không phải luôn.",
              correct: "sometimes",
              wrong: ["never", "always"],
              distractorNotes: ["Không chơi", "Mỗi lần"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They are _____ late for school.",
              skillTag: "grammar",
              topicTag,
              explanation: "Với be → are never (trạng từ sau are).",
              correct: "never",
              wrong: ["never are", "always is"],
              distractorNotes: ["Sai thứ tự", "Sai động từ"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-routine-questions",
      title: "Lesson 3: Questions About Routines",
      learningObjective:
        "Ask and answer What time…? and Do you…? questions about daily routines.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-questions-learn",
          title: "Learn: Routine Questions",
          instructions: "Choose the correct question word or auxiliary.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "_____ time do you wake up?",
              skillTag: "grammar",
              topicTag,
              explanation: "What time — hỏi giờ.",
              correct: "What",
              wrong: ["When", "Where"],
              distractorNotes: ["Also possible but What time is standard", "Asks place"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ you always brush your teeth?",
              skillTag: "grammar",
              topicTag,
              explanation: "Do you — yes/no question present simple.",
              correct: "Do",
              wrong: ["Does", "Are"],
              distractorNotes: ["For he/she", "Needs -ing or adjective"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ does Minh go to school?",
              skillTag: "grammar",
              topicTag,
              explanation: "When — hỏi thời điểm (có thể dùng What time).",
              correct: "When",
              wrong: ["Who", "What"],
              distractorNotes: ["Asks person", "Asks thing, not time"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "_____ she do her homework after school?",
              skillTag: "grammar",
              topicTag,
              explanation: "Does + she — third person question.",
              correct: "Does",
              wrong: ["Do", "Is"],
              distractorNotes: ["For I/you/we", "Present continuous"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-questions-practice",
          title: "Practice: Complete the Questions",
          instructions: "Fill in the gaps to make questions.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: [0] time do you have lunch? | [1] you do homework every day? | [2] does Minh go to bed?",
              skillTag: "grammar",
              topicTag,
              explanation: "What; Do; When — ba dạng câu hỏi routine.",
              template:
                "[0] time do you have lunch? [1] you do homework every day? [2] does Minh go to bed?",
              correctAnswers: ["What", "Do", "When"],
              acceptableAnswers: [
                ["What", "what"],
                ["Do", "do"],
                ["When", "when", "What"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-questions-check",
          title: "Check: Question Forms",
          instructions: "Choose the correct question.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which question is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "What time do you — đúng trật tự auxiliary.",
              correct: "What time do you wake up?",
              wrong: [
                "What time you wake up?",
                "What time do you wakes up?",
              ],
              distractorNotes: ["Missing do", "Wrong verb form"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best answer: Do you always eat breakfast?",
              skillTag: "grammar",
              topicTag,
              explanation: "Yes, I always eat breakfast — short natural answer.",
              correct: "Yes, I always eat breakfast.",
              wrong: ["Yes, I eat always breakfast.", "Yes, always I eat breakfast."],
              distractorNotes: ["Wrong adverb position", "Wrong word order"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which question is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Does he — third person với go (không goes trong question).",
              correct: "Does he go to bed at nine?",
              wrong: ["Do he go to bed at nine?", "Does he goes to bed at nine?"],
              distractorNotes: ["Wrong auxiliary", "Double -s"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-questions-apply",
          title: "Apply: Build Questions",
          instructions: "Put the words in order to make a question.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: What / time / do / you / have / dinner?",
              skillTag: "grammar",
              topicTag,
              explanation: "What time do you have dinner?",
              words: ["What", "time", "do", "you", "have", "dinner?"],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Do / you / sometimes / play / football?",
              skillTag: "grammar",
              topicTag,
              explanation: "Do you sometimes play football?",
              words: ["Do", "you", "sometimes", "play", "football?"],
              correctOrder: [0, 1, 2, 3, 4],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-questions-review",
          title: "Review: Question Forms Mix",
          instructions: "Choose the correct question or answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "_____ do you go to bed?",
              skillTag: "grammar",
              topicTag,
              explanation: "What time — hỏi giờ đi ngủ.",
              correct: "What time",
              wrong: ["Who", "Where"],
              distractorNotes: ["Hỏi người", "Hỏi địa điểm"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "_____ your brother do homework every day?",
              skillTag: "grammar",
              topicTag,
              explanation: "Does + he/she/your brother — third person.",
              correct: "Does",
              wrong: ["Do", "Is"],
              distractorNotes: ["I/you/we/they", "Present continuous"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best answer: When do you have breakfast?",
              skillTag: "grammar",
              topicTag,
              explanation: "At + time — trả lời thời gian tự nhiên.",
              correct: "At seven o'clock.",
              wrong: ["Seven o'clock breakfast.", "I breakfast seven."],
              distractorNotes: ["Không thành câu", "Sai trật tự"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
