/** Movers U1 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-morning-routine",
      title: "Lesson 1: Morning Routine Words",
      learningObjective:
        "Recognise and use wake up, breakfast, get dressed and brush teeth in short sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-morning-learn",
          title: "Learn: Morning Routine Words",
          instructions: "Read each clue. Choose the best word or phrase.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "At six thirty Minh stops sleeping. He _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Wake up (thức dậy) là bắt đầu ngày mới. Go to bed là đi ngủ.",
              correct: "wakes up",
              wrong: ["goes to bed", "has dinner"],
              distractorNotes: ["Evening routine", "Evening meal"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The first meal in the morning is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Breakfast (bữa sáng) là bữa đầu tiên trong ngày.",
              correct: "breakfast",
              wrong: ["lunch", "homework"],
              distractorNotes: ["Midday meal", "School work, not a meal"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "After breakfast Minh puts on his school uniform. He _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Get dressed (mặc quần áo) sau khi ăn sáng.",
              correct: "gets dressed",
              wrong: ["wakes up", "does homework"],
              distractorNotes: ["Happens earlier", "After-school activity"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh cleans his teeth in the bathroom. He _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Brush teeth (đánh răng) trong phòng tắm buổi sáng.",
              correct: "brushes his teeth",
              wrong: ["has lunch", "never forgets"],
              distractorNotes: ["Midday meal", "Not the action described"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-morning-practice",
          title: "Practice: Match Morning Routines",
          instructions: "Match each phrase to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the morning routine phrases.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mỗi cụm mô tả một hoạt động buổi sáng rõ ràng.",
              pairs: [
                { left: "wake up", right: "stop sleeping and get out of bed" },
                { left: "breakfast", right: "the first meal of the day" },
                { left: "get dressed", right: "put on clothes" },
                { left: "brush teeth", right: "clean your teeth" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-morning-check",
          title: "Check: Morning Words Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Mum says: 'Minh, _____! It's six thirty.'",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Wake up! — gọi thức dậy. Go to bed là buổi tối.",
              correct: "wake up",
              wrong: ["go to bed", "have dinner"],
              distractorNotes: ["Evening phrase", "Evening meal"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "I always have rice and eggs for _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Rice and eggs là đồ ăn sáng → breakfast.",
              correct: "breakfast",
              wrong: ["homework", "lunch"],
              distractorNotes: ["School work", "Later meal"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Don't forget to _____ before school.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Brush teeth trước khi đi học — thói quen vệ sinh.",
              correct: "brush your teeth",
              wrong: ["wake up", "get dressed"],
              distractorNotes: ["Earlier in routine", "Different action"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-morning-apply",
          title: "Apply: Complete Morning Sentences",
          instructions: "Fill in each gap with the correct word or phrase.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I [0] at six thirty. | I have [1] with my family. | Then I [2] and brush my teeth.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "wake up; breakfast; get dressed — thứ tự buổi sáng.",
              template:
                "I [0] at six thirty. I have [1] with my family. Then I [2] and brush my teeth.",
              correctAnswers: ["wake up", "breakfast", "get dressed"],
              acceptableAnswers: [
                ["wake up", "Wake up"],
                ["breakfast", "Breakfast"],
                ["get dressed", "Get dressed"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-morning-review",
          title: "Review: Morning Routine Mix",
          instructions: "Mixed review from this lesson. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Every morning I _____ at six thirty.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Wake up (thức dậy) — hoạt động đầu tiên trong ngày.",
              correct: "wake up",
              wrong: ["go to bed", "have dinner"],
              distractorNotes: ["Buổi tối", "Bữa tối"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "After you eat in the morning, you _____ for school.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Get dressed (mặc quần áo) sau bữa sáng.",
              correct: "get dressed",
              wrong: ["wake up", "do homework"],
              distractorNotes: ["Trước bữa sáng", "Sau giờ học"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The meal you eat before lunch is _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Breakfast (bữa sáng) — bữa trước trưa.",
              correct: "breakfast",
              wrong: ["dinner", "homework"],
              distractorNotes: ["Bữa tối", "Không phải bữa ăn"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-day-and-meals",
      title: "Lesson 2: Meals and School Day",
      learningObjective:
        "Use lunch, dinner and homework to talk about meals and after-school activities.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-meals-learn",
          title: "Learn: Meals and School",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "At twelve o'clock students eat _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Lunch (bữa trưa) vào giữa trưa ở trường.",
              correct: "lunch",
              wrong: ["breakfast", "dinner"],
              distractorNotes: ["Morning meal", "Evening meal"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The family eats _____ together at six o'clock.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Dinner (bữa tối) thường buổi tối.",
              correct: "dinner",
              wrong: ["lunch", "homework"],
              distractorNotes: ["Midday", "School work, not a meal"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "After school Minh does his _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Homework (bài tập về nhà) sau giờ học.",
              correct: "homework",
              wrong: ["breakfast", "lunch"],
              distractorNotes: ["Morning", "Midday meal"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh goes to _____ at seven thirty every morning.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "School — đi học buổi sáng (ngữ cảnh Movers).",
              correct: "school",
              wrong: ["bed", "dinner"],
              distractorNotes: ["Sleep time", "Evening meal"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-meals-practice",
          title: "Practice: Match Meals and Activities",
          instructions: "Match each word to the correct time or situation.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match meals and school-day words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ghép bữa ăn và hoạt động với thời điểm phù hợp.",
              pairs: [
                { left: "lunch", right: "at twelve at school" },
                { left: "dinner", right: "in the evening with family" },
                { left: "homework", right: "after school before dinner" },
                { left: "school", right: "where you learn in the morning" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-meals-check",
          title: "Check: Meals Quiz",
          instructions: "Choose the best answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh has _____ at school at twelve o'clock.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Twelve o'clock at school → lunch.",
              correct: "lunch",
              wrong: ["breakfast", "dinner"],
              distractorNotes: ["Eaten at home in morning", "Evening meal"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "He always does his _____ before dinner.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Homework trước bữa tối — theo passage Minh.",
              correct: "homework",
              wrong: ["lunch", "breakfast"],
              distractorNotes: ["Midday meal", "Morning meal"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We eat _____ at six in the evening.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Six in the evening → dinner.",
              correct: "dinner",
              wrong: ["lunch", "homework"],
              distractorNotes: ["Midday", "Not a meal"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-meals-apply",
          title: "Apply: School Day Sentences",
          instructions: "Complete the sentences about Minh's school day.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh goes to [0] at seven thirty. | He has [1] at twelve. | After school he does his [2].",
              skillTag: "vocabulary",
              topicTag,
              explanation: "school; lunch; homework — ngày đi học của Minh.",
              template:
                "Minh goes to [0] at seven thirty. He has [1] at twelve. After school he does his [2].",
              correctAnswers: ["school", "lunch", "homework"],
              acceptableAnswers: [
                ["school", "School"],
                ["lunch", "Lunch"],
                ["homework", "Homework"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-meals-review",
          title: "Review: Meals and School Mix",
          instructions: "Mixed review. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Students eat _____ at twelve at school.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Lunch (bữa trưa) — giữa ngày ở trường.",
              correct: "lunch",
              wrong: ["breakfast", "dinner"],
              distractorNotes: ["Buổi sáng", "Buổi tối"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "I do my _____ when I get home from school.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Homework (bài tập) — sau khi tan học.",
              correct: "homework",
              wrong: ["breakfast", "lunch"],
              distractorNotes: ["Bữa sáng", "Bữa trưa"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We eat _____ together in the evening.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Dinner (bữa tối) — buổi tối.",
              correct: "dinner",
              wrong: ["lunch", "homework"],
              distractorNotes: ["Bữa trưa", "Không phải bữa ăn"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-frequency-adverbs",
      title: "Lesson 3: How Often?",
      learningObjective:
        "Use always, sometimes, never and every day to say how often you do things.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-frequency-learn",
          title: "Learn: Frequency Words",
          instructions: "Choose the word that best completes each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "I _____ brush my teeth in the morning. (100% of the time)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Always (luôn luôn) = mọi lúc.",
              correct: "always",
              wrong: ["sometimes", "never"],
              distractorNotes: ["Not every time", "Zero times"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "I _____ play football after homework. (not every day)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Sometimes (đôi khi) = thỉnh thoảng.",
              correct: "sometimes",
              wrong: ["always", "never"],
              distractorNotes: ["Every time", "Never plays"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh _____ watches TV before homework. (0% of the time)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Never (không bao giờ) = không lần nào.",
              correct: "never",
              wrong: ["always", "sometimes"],
              distractorNotes: ["Opposite meaning", "Would allow some TV"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "I walk to school _____. (each day)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Every day (mỗi ngày) = hàng ngày.",
              correct: "every day",
              wrong: ["never", "sometimes"],
              distractorNotes: ["Never walks", "Only some days"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-frequency-practice",
          title: "Practice: Match How Often",
          instructions: "Match each adverb to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the frequency words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Always/sometimes/never/ every day — bốn mức độ khác nhau.",
              pairs: [
                { left: "always", right: "100% of the time" },
                { left: "sometimes", right: "not every time" },
                { left: "never", right: "0% of the time" },
                { left: "every day", right: "once each day" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-frequency-check",
          title: "Check: Frequency Challenge",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh _____ does his homework before dinner.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Trong bài đọc Minh always làm bài trước tối.",
              correct: "always",
              wrong: ["never", "sometimes"],
              distractorNotes: ["Opposite of the text", "Text says every time"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "He _____ plays football in the park.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Passage: sometimes plays football.",
              correct: "sometimes",
              wrong: ["never", "always"],
              distractorNotes: ["He does play sometimes", "Not every day"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Never đứng trước động từ chính watch.",
              correct: "I never watch TV before homework.",
              wrong: [
                "I watch never TV before homework.",
                "Never I watch TV before homework.",
              ],
              distractorNotes: ["Wrong word order", "Wrong word order"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-frequency-apply",
          title: "Apply: How Often Do You…?",
          instructions: "Fill in with always, sometimes or never.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I [0] wake up at six thirty. | I [1] play football after school. | I [2] watch TV before homework.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "always; sometimes; never — mẫu câu thói quen hợp lý.",
              template:
                "I [0] wake up at six thirty. I [1] play football after school. I [2] watch TV before homework.",
              correctAnswers: ["always", "sometimes", "never"],
              acceptableAnswers: [
                ["always", "Always"],
                ["sometimes", "Sometimes"],
                ["never", "Never"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-frequency-review",
          title: "Review: Frequency Words Mix",
          instructions: "Choose the best frequency word.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "I _____ eat breakfast with my family. (every day)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Always (luôn luôn) — mỗi ngày đều ăn sáng cùng gia đình.",
              correct: "always",
              wrong: ["never", "sometimes"],
              distractorNotes: ["Không bao giờ", "Chỉ thỉnh thoảng"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "She _____ plays football. (about twice a week)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Sometimes (đôi khi) — không phải mỗi ngày.",
              correct: "sometimes",
              wrong: ["always", "never"],
              distractorNotes: ["Mỗi lần", "Không chơi"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "He _____ walks to school on rainy days. (0%)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Never (không bao giờ) — 0% trên ngày mưa.",
              correct: "never",
              wrong: ["always", "every day"],
              distractorNotes: ["Luôn đi bộ", "Mỗi ngày"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
