import { buildExpansionItems } from "./expansion-item-factory";

export const FLYERS_EXPANSION_ITEMS = buildExpansionItems("flyers", [
  {
    id: "001",
    part: "listening-part-1",
    skill: "listening",
    questionType: "matching",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["jobs"],
    topicTag: "jobs",
    stem: "Listen and match each speaker to the job they describe.",
  },
  {
    id: "002",
    part: "listening-part-1",
    skill: "listening",
    questionType: "matching",
    difficulty: "easy",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel"],
    topicTag: "travel",
    stem: "Listen and match each tourist to the place they visited last summer.",
  },
  {
    id: "003",
    part: "listening-part-2",
    skill: "listening",
    questionType: "gap_fill",
    difficulty: "medium",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["weather"],
    topicTag: "weather",
    stem: "Listen and write the missing word about yesterday's storm.",
    template: "The wind broke a window in the [0].",
    correctAnswers: ["greenhouse"],
  },
  {
    id: "004",
    part: "listening-part-2",
    skill: "listening",
    questionType: "gap_fill",
    difficulty: "hard",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["places"],
    topicTag: "places",
    stem: "Listen and write the missing direction word.",
    template: "Walk past the fountain and turn [0] at the bridge.",
    correctAnswers: ["left"],
  },
  {
    id: "005",
    part: "listening-part-3",
    skill: "listening",
    questionType: "listening",
    difficulty: "medium",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["technology"],
    topicTag: "technology",
    stem: "Listen. Which picture shows students using laptops in the science lab?",
  },
  {
    id: "006",
    part: "listening-part-3",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: "hard",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["environment"],
    topicTag: "environment",
    stem: "Listen. Why must visitors stay on the path in the nature reserve?",
    choices: [
      { text: "to protect rare plants", isCorrect: true },
      { text: "to find the café faster", isCorrect: false },
      { text: "to hear the guide better", isCorrect: false },
    ],
  },
  {
    id: "007",
    part: "listening-part-4",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["nature"],
    topicTag: "nature",
    stem: "Listen. Which animal should be drawn next to the oak tree?",
    choices: [
      { text: "a squirrel", isCorrect: true },
      { text: "a whale", isCorrect: false },
      { text: "a penguin", isCorrect: false },
    ],
  },
  {
    id: "008",
    part: "rw-part-1",
    skill: "reading",
    questionType: "matching",
    difficulty: "easy",
    grammarTags: ["superlatives"],
    vocabularyTopics: ["sports"],
    topicTag: "sports",
    stem: "Match each sport word to the picture of the fastest athlete.",
  },
  {
    id: "009",
    part: "rw-part-1",
    skill: "reading",
    questionType: "matching",
    difficulty: "medium",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["food"],
    topicTag: "food",
    stem: "Match each dish word to the picture of the healthier meal.",
  },
  {
    id: "010",
    part: "rw-part-2",
    skill: "reading",
    questionType: "reading_comprehension",
    difficulty: "medium",
    grammarTags: ["past_continuous"],
    vocabularyTopics: ["community"],
    topicTag: "community",
    stem: "Read: 'While the volunteers were planting trees, it started to rain.' What happened while they planted?",
  },
  {
    id: "011",
    part: "rw-part-2",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "hard",
    grammarTags: ["relative_clauses"],
    vocabularyTopics: ["culture"],
    topicTag: "culture",
    stem: "Read: 'The dancer who wore a red costume won the competition.' Who won?",
    choices: [
      { text: "the dancer in red", isCorrect: true },
      { text: "the singer in blue", isCorrect: false },
      { text: "the judge on stage", isCorrect: false },
    ],
  },
  {
    id: "012",
    part: "rw-part-2",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["future_will"],
    vocabularyTopics: ["technology"],
    topicTag: "technology",
    stem: "Read: 'Next year our school will open a new robotics club.' What will happen next year?",
    choices: [
      { text: "a new robotics club", isCorrect: true },
      { text: "a bigger canteen", isCorrect: false },
      { text: "longer holidays", isCorrect: false },
    ],
  },
  {
    id: "013",
    part: "rw-part-3",
    skill: "reading",
    questionType: "reading_comprehension",
    difficulty: "hard",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["health"],
    topicTag: "health",
    stem: "Read the article: 'Although exercise is tiring, it helps you sleep better.' What is the main benefit mentioned?",
  },
  {
    id: "014",
    part: "rw-part-3",
    skill: "reading",
    questionType: "reading_comprehension",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["shopping"],
    topicTag: "shopping",
    stem: "Read the advert: 'Our shop sells handmade gifts from local artists.' What kind of products are sold?",
  },
  {
    id: "015",
    part: "rw-part-3",
    skill: "reading",
    questionType: "gap_fill",
    difficulty: "hard",
    grammarTags: ["conjunctions"],
    vocabularyTopics: ["feelings"],
    topicTag: "feelings",
    stem: "Complete: 'She was nervous _____ she practised every day.'",
    template: "She was nervous [0] she practised every day.",
    correctAnswers: ["but"],
  },
  {
    id: "016",
    part: "listening-part-4",
    skill: "listening",
    questionType: "listening",
    difficulty: "medium",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["clothes"],
    topicTag: "clothes",
    stem: "Listen. Colour the scarf on the girl who is ice-skating.",
  },
  {
    id: "017",
    part: "rw-part-1",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "easy",
    grammarTags: ["countable_uncountable"],
    vocabularyTopics: ["drink"],
    topicTag: "drink",
    stem: "Which sentence matches a picture of several cups of hot chocolate?",
    choices: [
      { text: "There is some hot chocolate.", isCorrect: false },
      { text: "There are several cups of hot chocolate.", isCorrect: true },
      { text: "There is one glass of lemonade.", isCorrect: false },
    ],
  },
  {
    id: "018",
    part: "rw-part-3",
    skill: "reading",
    questionType: "gap_fill",
    difficulty: "medium",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["transport"],
    topicTag: "transport",
    stem: "Complete: 'You _____ borrow my bike if you wear a helmet.'",
    template: "You [0] borrow my bike if you wear a helmet.",
    correctAnswers: ["can"],
  },
  {
    id: "019",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "medium",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel"],
    topicTag: "travel",
    stem: "Look at the picture. Write one sentence about what the hikers found on the mountain.",
    writing: {
      prompt: "Look at the picture. Write one sentence about what the hikers found on the mountain.",
      writingTaskType: "write_sentence",
      minWords: 5,
      maxWords: 22,
      rubricId: "expansion-write_sentence-v1",
    },
  },
  {
    id: "020",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "hard",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["environment"],
    topicTag: "environment",
    stem: "Look at the picture. Write one sentence about how people are cleaning the beach.",
    writing: {
      prompt: "Look at the picture. Write one sentence about how people are cleaning the beach.",
      writingTaskType: "write_sentence",
      minWords: 6,
      maxWords: 25,
      rubricId: "expansion-write_sentence-v1",
    },
  },
  {
    id: "021",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    topicTag: "school",
    stem: "Write a message to your classmate explaining the science project deadline.",
    writing: {
      prompt: "Write a message to your classmate explaining the science project deadline.",
      writingTaskType: "writing_message",
      minWords: 10,
      maxWords: 40,
      rubricId: "expansion-writing_message-v1",
    },
  },
  {
    id: "022",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "easy",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["friends"],
    topicTag: "friends",
    stem: "Write a note reminding your friend to bring trainers for the football match.",
    writing: {
      prompt: "Write a note reminding your friend to bring trainers for the football match.",
      writingTaskType: "writing_message",
      minWords: 8,
      maxWords: 35,
      rubricId: "expansion-writing_message-v1",
    },
  },
  {
    id: "023",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "hard",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["places"],
    topicTag: "places",
    stem: "Look at the market picture. Write three sentences describing the stalls and the crowd.",
    writing: {
      prompt: "Look at the market picture. Write three sentences describing the stalls and the crowd.",
      writingTaskType: "picture_description",
      minWords: 15,
      maxWords: 45,
      rubricId: "expansion-picture_description-v1",
    },
  },
  {
    id: "024",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "medium",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["home"],
    topicTag: "home",
    stem: "Look at the attic picture. Write two sentences about where objects are stored.",
    writing: {
      prompt: "Look at the attic picture. Write two sentences about where objects are stored.",
      writingTaskType: "picture_description",
      minWords: 12,
      maxWords: 40,
      rubricId: "expansion-picture_description-v1",
    },
  },
  {
    id: "025",
    part: "speaking-part-1",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "hard",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["leisure"],
    topicTag: "leisure",
    stem: "Look at the two theme-park pictures. Describe six differences to your teacher.",
    speaking: {
      prompt: "Look at the two theme-park pictures. Describe six differences to your teacher.",
      speakingTaskType: "speaking_picture_description",
      maxDurationSeconds: 120,
      rubricId: "expansion-speaking_picture_description-v1",
    },
  },
  {
    id: "026",
    part: "speaking-part-1",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "medium",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["sports"],
    topicTag: "sports",
    stem: "Look at the two stadium pictures. Say how the players' positions differ.",
    speaking: {
      prompt: "Look at the two stadium pictures. Say how the players' positions differ.",
      speakingTaskType: "speaking_picture_description",
      maxDurationSeconds: 120,
      rubricId: "expansion-speaking_picture_description-v1",
    },
  },
  {
    id: "027",
    part: "speaking-part-2",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "medium",
    grammarTags: ["question_forms"],
    vocabularyTopics: ["travel"],
    topicTag: "travel",
    stem: "Answer questions about holidays you have taken.",
    speaking: {
      prompt: "Answer questions about holidays you have taken.",
      speakingTaskType: "speaking_personal_questions",
      maxDurationSeconds: 90,
      followUpQuestions: [
        "Where did you go on your last holiday?",
        "What was the best thing you ate there?",
        "Would you like to return to that place?",
      ],
      rubricId: "expansion-speaking_personal_questions-v1",
    },
  },
  {
    id: "028",
    part: "speaking-part-2",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "hard",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["technology"],
    topicTag: "technology",
    stem: "Answer questions about how you use technology for learning.",
    speaking: {
      prompt: "Answer questions about how you use technology for learning.",
      speakingTaskType: "speaking_personal_questions",
      maxDurationSeconds: 90,
      followUpQuestions: [
        "Which app helps you study languages?",
        "Can you explain a video you watched recently?",
        "How often do you search for information online?",
      ],
      rubricId: "expansion-speaking_personal_questions-v1",
    },
  },
  {
    id: "029",
    part: "speaking-part-3",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "hard",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["culture"],
    topicTag: "culture",
    stem: "Look at the picture story. Tell the story of the international food festival at school.",
    speaking: {
      prompt: "Look at the picture story. Tell the story of the international food festival at school.",
      speakingTaskType: "speaking_storytelling",
      maxDurationSeconds: 150,
      rubricId: "expansion-speaking_storytelling-v1",
    },
  },
  {
    id: "030",
    part: "speaking-part-3",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["animals"],
    topicTag: "animals",
    stem: "Look at the picture story. Tell the story of the dolphin rescue at the coast.",
    speaking: {
      prompt: "Look at the picture story. Tell the story of the dolphin rescue at the coast.",
      speakingTaskType: "speaking_storytelling",
      maxDurationSeconds: 150,
      rubricId: "expansion-speaking_storytelling-v1",
    },
  },
]);
