import { buildExpansionItems } from "./expansion-item-factory";

export const KET_EXPANSION_ITEMS = buildExpansionItems("ket", [
  {
    id: "001",
    part: "rw-part-1",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "easy",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["shopping"],
    topicTag: "shopping",
    stem: "Sign in a shop: 'Please pay here before you leave.' What must customers do?",
    choices: [
      { text: "pay before leaving", isCorrect: true },
      { text: "ask for a receipt later", isCorrect: false },
      { text: "return items for free", isCorrect: false },
    ],
  },
  {
    id: "002",
    part: "rw-part-1",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["transport"],
    topicTag: "transport",
    stem: "Notice at the station: 'Passengers must show tickets at the gate.' Who needs a ticket?",
    choices: [
      { text: "all passengers", isCorrect: true },
      { text: "only children", isCorrect: false },
      { text: "only tourists", isCorrect: false },
    ],
  },
  {
    id: "003",
    part: "rw-part-2",
    skill: "reading",
    questionType: "matching",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["leisure"],
    topicTag: "leisure",
    stem: "Match each person to the leisure activity they describe in their profile.",
  },
  {
    id: "004",
    part: "rw-part-2",
    skill: "reading",
    questionType: "matching",
    difficulty: "hard",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel"],
    topicTag: "travel",
    stem: "Match each traveller to the problem they had on their journey.",
  },
  {
    id: "005",
    part: "rw-part-3",
    skill: "reading",
    questionType: "reading_comprehension",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["environment"],
    topicTag: "environment",
    stem: "Read the blog: 'Our class planted fifty trees to reduce pollution near the river.' Why did the class plant trees?",
  },
  {
    id: "006",
    part: "rw-part-3",
    skill: "reading",
    questionType: "reading_comprehension",
    difficulty: "hard",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["health"],
    topicTag: "health",
    stem: "Read: 'Doctors recommend walking because it strengthens your heart.' What is the reason for walking?",
  },
  {
    id: "007",
    part: "rw-part-4",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["articles"],
    vocabularyTopics: ["school"],
    topicTag: "school",
    stem: "Choose the best word: 'She wants to become ___ engineer after university.'",
    choices: [
      { text: "a", isCorrect: false },
      { text: "an", isCorrect: true },
      { text: "the", isCorrect: false },
    ],
  },
  {
    id: "008",
    part: "rw-part-4",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "easy",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["home"],
    topicTag: "home",
    stem: "Choose the best word: 'We arrived ___ the hotel at midnight.'",
    choices: [
      { text: "at", isCorrect: true },
      { text: "on", isCorrect: false },
      { text: "by", isCorrect: false },
    ],
  },
  {
    id: "009",
    part: "rw-part-5",
    skill: "reading",
    questionType: "gap_fill",
    difficulty: "medium",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["friends"],
    topicTag: "friends",
    stem: "Complete the email: 'We _____ a great film last night.'",
    template: "We [0] a great film last night.",
    correctAnswers: ["watched"],
  },
  {
    id: "010",
    part: "rw-part-5",
    skill: "reading",
    questionType: "gap_fill",
    difficulty: "hard",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["technology"],
    topicTag: "technology",
    stem: "Complete: 'My brother is _____ a new language app every day.'",
    template: "My brother is [0] a new language app every day.",
    correctAnswers: ["using"],
  },
  {
    id: "011",
    part: "listening-part-1",
    skill: "listening",
    questionType: "listening",
    difficulty: "easy",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["food"],
    topicTag: "food",
    stem: "Listen. Which picture shows the woman buying vegetables?",
  },
  {
    id: "012",
    part: "listening-part-2",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["jobs"],
    topicTag: "jobs",
    stem: "Listen. What is the man going to do tomorrow?",
    choices: [
      { text: "attend a job interview", isCorrect: true },
      { text: "visit his grandparents", isCorrect: false },
      { text: "repair his bicycle", isCorrect: false },
    ],
  },
  {
    id: "013",
    part: "listening-part-3",
    skill: "listening",
    questionType: "gap_fill",
    difficulty: "medium",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["places"],
    topicTag: "places",
    stem: "Listen and write the missing word: 'The museum is opposite the _____.'",
    template: "The museum is opposite the [0].",
    correctAnswers: ["library"],
  },
  {
    id: "014",
    part: "listening-part-4",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: "hard",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["sports"],
    topicTag: "sports",
    stem: "Listen to the coach. Why can't the team train today?",
    choices: [
      { text: "the pitch is flooded", isCorrect: true },
      { text: "the bus broke down", isCorrect: false },
      { text: "the match was cancelled", isCorrect: false },
    ],
  },
  {
    id: "015",
    part: "listening-part-5",
    skill: "listening",
    questionType: "matching",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["culture"],
    topicTag: "culture",
    stem: "Listen and match each speaker to the festival they enjoyed most.",
  },
  {
    id: "016",
    part: "rw-part-3",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "easy",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["shopping"],
    topicTag: "shopping",
    stem: "Read: 'Online prices are cheaper than in the city centre.' Where are prices lower?",
    choices: [
      { text: "online", isCorrect: true },
      { text: "in the city centre", isCorrect: false },
      { text: "at the airport", isCorrect: false },
    ],
  },
  {
    id: "017",
    part: "listening-part-1",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["community"],
    topicTag: "community",
    stem: "Listen. Which picture shows volunteers painting a community hall?",
    choices: [
      { text: "people painting a hall", isCorrect: true },
      { text: "people cooking soup", isCorrect: false },
      { text: "people planting flowers", isCorrect: false },
    ],
  },
  {
    id: "018",
    part: "rw-part-5",
    skill: "reading",
    questionType: "gap_fill",
    difficulty: "easy",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["feelings"],
    topicTag: "feelings",
    stem: "Complete: 'They _____ very excited about the concert.'",
    template: "They [0] very excited about the concert.",
    correctAnswers: ["were"],
  },
  {
    id: "019",
    part: "rw-part-6",
    skill: "writing",
    questionType: "writing",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["friends"],
    topicTag: "friends",
    stem: "Write an email to your friend about a birthday party you are planning.",
    writing: {
      prompt:
        "Write an email to your friend about a birthday party you are planning. Say when it is, who is invited, and what activities you will have.",
      writingTaskType: "writing_email",
      minWords: 25,
      maxWords: 35,
      rubricId: "expansion-writing_email-v1",
    },
  },
  {
    id: "020",
    part: "rw-part-6",
    skill: "writing",
    questionType: "writing",
    difficulty: "easy",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["school"],
    topicTag: "school",
    stem: "Write a message to your teacher explaining why you missed the science lesson.",
    writing: {
      prompt:
        "Write a message to your teacher explaining why you missed the science lesson and what homework you will complete.",
      writingTaskType: "writing_message",
      minWords: 25,
      maxWords: 35,
      rubricId: "expansion-writing_message-v1",
    },
  },
  {
    id: "021",
    part: "rw-part-6",
    skill: "writing",
    questionType: "writing",
    difficulty: "hard",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel"],
    topicTag: "travel",
    stem: "Write an email to your cousin describing a train journey you took last weekend.",
    writing: {
      prompt:
        "Write an email to your cousin describing a train journey you took last weekend. Mention the scenery and one problem you had.",
      writingTaskType: "writing_email",
      minWords: 25,
      maxWords: 35,
      rubricId: "expansion-writing_email-v1",
    },
  },
  {
    id: "022",
    part: "rw-part-7",
    skill: "writing",
    questionType: "writing",
    difficulty: "medium",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["animals"],
    topicTag: "animals",
    stem: "Look at the three pictures. Write a story about a lost dog and how it was found.",
    writing: {
      prompt:
        "Look at the three pictures. Write a story about a lost dog and how it was found. Use past tenses.",
      writingTaskType: "writing_story",
      minWords: 35,
      maxWords: 45,
      rubricId: "expansion-writing_story-v1",
    },
  },
  {
    id: "023",
    part: "rw-part-7",
    skill: "writing",
    questionType: "writing",
    difficulty: "hard",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["weather"],
    topicTag: "weather",
    stem: "Look at the pictures. Write a story about a sudden storm during a picnic.",
    writing: {
      prompt:
        "Look at the pictures. Write a story about a sudden storm during a picnic. Use linking words like 'suddenly' and 'finally'.",
      writingTaskType: "writing_story",
      minWords: 35,
      maxWords: 45,
      rubricId: "expansion-writing_story-v1",
    },
  },
  {
    id: "024",
    part: "rw-part-7",
    skill: "writing",
    questionType: "writing",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["hobbies"],
    topicTag: "hobbies",
    stem: "Write a short article for the school website about your favourite hobby.",
    writing: {
      prompt:
        "Write a short article for the school website about your favourite hobby. Explain why other students should try it.",
      writingTaskType: "writing_article",
      minWords: 35,
      maxWords: 45,
      rubricId: "expansion-writing_article-v1",
    },
  },
  {
    id: "025",
    part: "speaking-part-1",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "easy",
    grammarTags: ["question_forms"],
    vocabularyTopics: ["home"],
    topicTag: "home",
    stem: "Answer interview questions about your home and neighbourhood.",
    speaking: {
      prompt: "Answer interview questions about your home and neighbourhood.",
      speakingTaskType: "speaking_personal_questions",
      maxDurationSeconds: 120,
      followUpQuestions: [
        "Where do you live?",
        "What is the best thing about your area?",
        "How do you usually travel to school?",
      ],
      rubricId: "expansion-speaking_personal_questions-v1",
    },
  },
  {
    id: "026",
    part: "speaking-part-1",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "medium",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["food"],
    topicTag: "food",
    stem: "Answer questions about food you like to cook or eat.",
    speaking: {
      prompt: "Answer questions about food you like to cook or eat.",
      speakingTaskType: "speaking_personal_questions",
      maxDurationSeconds: 120,
      followUpQuestions: [
        "What is your favourite meal?",
        "Can you cook anything yourself?",
        "Have you ever tried food from another country?",
      ],
      rubricId: "expansion-speaking_personal_questions-v1",
    },
  },
  {
    id: "027",
    part: "speaking-part-2",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "medium",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["leisure"],
    topicTag: "leisure",
    stem: "Describe the photo showing people at an outdoor concert.",
    speaking: {
      prompt: "Describe the photo showing people at an outdoor concert. Say what they are doing and how they feel.",
      speakingTaskType: "speaking_picture_description",
      maxDurationSeconds: 120,
      rubricId: "expansion-speaking_picture_description-v1",
    },
  },
  {
    id: "028",
    part: "speaking-part-2",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "hard",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["transport"],
    topicTag: "transport",
    stem: "Describe the photo of a busy train station during rush hour.",
    speaking: {
      prompt:
        "Describe the photo of a busy train station during rush hour. Mention locations of people and objects.",
      speakingTaskType: "speaking_picture_description",
      maxDurationSeconds: 120,
      rubricId: "expansion-speaking_picture_description-v1",
    },
  },
  {
    id: "029",
    part: "speaking-part-2",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "medium",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["environment"],
    topicTag: "environment",
    stem: "Discuss with your partner how your school could reduce plastic waste.",
    speaking: {
      prompt: "Discuss with your partner how your school could reduce plastic waste.",
      speakingTaskType: "speaking_discussion",
      maxDurationSeconds: 180,
      followUpQuestions: [
        "What items could we recycle more?",
        "Who should lead the project?",
        "How can students help every day?",
      ],
      rubricId: "expansion-speaking_discussion-v1",
    },
  },
  {
    id: "030",
    part: "speaking-part-1",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "hard",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["culture"],
    topicTag: "culture",
    stem: "Tell your partner about a festival or celebration you enjoyed.",
    speaking: {
      prompt: "Tell your partner about a festival or celebration you enjoyed.",
      speakingTaskType: "speaking_storytelling",
      maxDurationSeconds: 150,
      rubricId: "expansion-speaking_storytelling-v1",
    },
  },
]);
