import { buildExpansionItems } from "./expansion-item-factory";

export const PET_EXPANSION_ITEMS = buildExpansionItems("pet", [
  {
    id: "001",
    part: "reading-part-1",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "easy",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["shopping"],
    topicTag: "shopping",
    stem: "Sign: 'Customers must queue behind the red line.' What should customers do?",
    choices: [
      { text: "stand behind the red line", isCorrect: true },
      { text: "pay at any counter", isCorrect: false },
      { text: "enter through the back door", isCorrect: false },
    ],
  },
  {
    id: "002",
    part: "reading-part-1",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["modal_must"],
    vocabularyTopics: ["health"],
    topicTag: "health",
    stem: "Clinic notice: 'Patients must not eat for six hours before the test.' What is forbidden?",
    choices: [
      { text: "eating before the test", isCorrect: true },
      { text: "drinking water", isCorrect: false },
      { text: "bringing a friend", isCorrect: false },
    ],
  },
  {
    id: "003",
    part: "reading-part-2",
    skill: "reading",
    questionType: "matching",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["jobs"],
    topicTag: "jobs",
    stem: "Match each job advertisement to the person who would be most interested.",
  },
  {
    id: "004",
    part: "reading-part-2",
    skill: "reading",
    questionType: "matching",
    difficulty: "hard",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel"],
    topicTag: "travel",
    stem: "Match each travel review to the type of holiday it describes.",
  },
  {
    id: "005",
    part: "reading-part-3",
    skill: "reading",
    questionType: "reading_comprehension",
    difficulty: "medium",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["technology"],
    topicTag: "technology",
    stem: "Article: 'Although smartphones are useful, they can distract students during lessons.' What is the writer's concern?",
  },
  {
    id: "006",
    part: "reading-part-3",
    skill: "reading",
    questionType: "reading_comprehension",
    difficulty: "hard",
    grammarTags: ["relative_clauses"],
    vocabularyTopics: ["environment"],
    topicTag: "environment",
    stem: "Text: 'Scientists who study coral reefs warn that pollution is damaging them.' Who issued the warning?",
  },
  {
    id: "007",
    part: "reading-part-4",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["articles"],
    vocabularyTopics: ["culture"],
    topicTag: "culture",
    stem: "Choose the best word: 'She gave me ___ useful advice about the exhibition.'",
    choices: [
      { text: "a", isCorrect: false },
      { text: "an", isCorrect: false },
      { text: "some", isCorrect: true },
    ],
  },
  {
    id: "008",
    part: "reading-part-4",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "easy",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["places"],
    topicTag: "places",
    stem: "Choose the best word: 'We walked ___ the bridge to reach the island.'",
    choices: [
      { text: "across", isCorrect: true },
      { text: "into", isCorrect: false },
      { text: "among", isCorrect: false },
    ],
  },
  {
    id: "009",
    part: "reading-part-5",
    skill: "reading",
    questionType: "gap_fill",
    difficulty: "medium",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["friends"],
    topicTag: "friends",
    stem: "Complete: 'I hadn't seen Marco for years, but we _____ friends immediately.'",
    template: "I hadn't seen Marco for years, but we [0] friends immediately.",
    correctAnswers: ["became"],
  },
  {
    id: "010",
    part: "reading-part-5",
    skill: "reading",
    questionType: "gap_fill",
    difficulty: "hard",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["community"],
    topicTag: "community",
    stem: "Complete: 'Local residents are _____ a campaign to save the old theatre.'",
    template: "Local residents are [0] a campaign to save the old theatre.",
    correctAnswers: ["organising"],
  },
  {
    id: "011",
    part: "reading-part-6",
    skill: "reading",
    questionType: "reading_comprehension",
    difficulty: "hard",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["culture"],
    topicTag: "culture",
    stem: "Gapped text: Choose the sentence that best introduces the paragraph about street art in the city.",
  },
  {
    id: "012",
    part: "reading-part-6",
    skill: "reading",
    questionType: "matching",
    difficulty: "medium",
    grammarTags: ["conjunctions"],
    vocabularyTopics: ["health"],
    topicTag: "health",
    stem: "Match each removed sentence to the correct gap in the article about sleep habits.",
  },
  {
    id: "013",
    part: "listening-part-1",
    skill: "listening",
    questionType: "listening",
    difficulty: "easy",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["food"],
    topicTag: "food",
    stem: "Listen. Which picture shows the chef preparing seafood?",
  },
  {
    id: "014",
    part: "listening-part-2",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["jobs"],
    topicTag: "jobs",
    stem: "Listen. What is the woman going to study at college?",
    choices: [
      { text: "graphic design", isCorrect: true },
      { text: "mechanical engineering", isCorrect: false },
      { text: "marine biology", isCorrect: false },
    ],
  },
  {
    id: "015",
    part: "listening-part-3",
    skill: "listening",
    questionType: "gap_fill",
    difficulty: "hard",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["travel"],
    topicTag: "travel",
    stem: "Listen and write the missing word: 'The ferry leaves from the _____ terminal.'",
    template: "The ferry leaves from the [0] terminal.",
    correctAnswers: ["north"],
  },
  {
    id: "016",
    part: "listening-part-4",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["sports"],
    topicTag: "sports",
    stem: "Listen to the announcement. Why has the tennis match been delayed?",
    choices: [
      { text: "heavy rain on the court", isCorrect: true },
      { text: "a player injury", isCorrect: false },
      { text: "a power failure", isCorrect: false },
    ],
  },
  {
    id: "017",
    part: "listening-part-5",
    skill: "listening",
    questionType: "matching",
    difficulty: "hard",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["leisure"],
    topicTag: "leisure",
    stem: "Listen and match each speaker to the reason they prefer their hobby.",
  },
  {
    id: "018",
    part: "reading-part-3",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "easy",
    grammarTags: ["comparatives"],
    vocabularyTopics: ["shopping"],
    topicTag: "shopping",
    stem: "Review: 'This jacket is warmer than the one I bought last year.' Which jacket is warmer?",
    choices: [
      { text: "the new jacket", isCorrect: true },
      { text: "last year's jacket", isCorrect: false },
      { text: "both are equal", isCorrect: false },
    ],
  },
  {
    id: "019",
    part: "writing-part-1",
    skill: "writing",
    questionType: "writing",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    topicTag: "school",
    stem: "Write an email to your English teacher about a school trip you want to organise.",
    writing: {
      prompt:
        "Write an email to your English teacher about a school trip you want to organise. Explain the destination, dates, and why the trip would be educational.",
      writingTaskType: "writing_email",
      minWords: 100,
      maxWords: 120,
      rubricId: "expansion-writing_email-v1",
    },
  },
  {
    id: "020",
    part: "writing-part-1",
    skill: "writing",
    questionType: "writing",
    difficulty: "easy",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["friends"],
    topicTag: "friends",
    stem: "Write an email to your friend inviting them to join a weekend hiking group.",
    writing: {
      prompt:
        "Write an email to your friend inviting them to join a weekend hiking group. Give details about the route and what to bring.",
      writingTaskType: "writing_email",
      minWords: 100,
      maxWords: 120,
      rubricId: "expansion-writing_email-v1",
    },
  },
  {
    id: "021",
    part: "writing-part-1",
    skill: "writing",
    questionType: "writing",
    difficulty: "hard",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel"],
    topicTag: "travel",
    stem: "Write a message to your class group chat about plans for a language course abroad.",
    writing: {
      prompt:
        "Write a message to your class group chat about plans for a language course abroad. Mention your budget and preferred country.",
      writingTaskType: "writing_message",
      minWords: 100,
      maxWords: 120,
      rubricId: "expansion-writing_message-v1",
    },
  },
  {
    id: "022",
    part: "writing-part-2",
    skill: "writing",
    questionType: "writing",
    difficulty: "medium",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["community"],
    topicTag: "community",
    stem: "Write a story titled 'The surprise in the old town square'.",
    writing: {
      prompt:
        "Write a story titled 'The surprise in the old town square'. Include a problem and a happy ending.",
      writingTaskType: "writing_story",
      minWords: 100,
      maxWords: 120,
      rubricId: "expansion-writing_story-v1",
    },
  },
  {
    id: "023",
    part: "writing-part-2",
    skill: "writing",
    questionType: "writing",
    difficulty: "hard",
    grammarTags: ["linking_words"],
    vocabularyTopics: ["weather"],
    topicTag: "weather",
    stem: "Write a story about a camping trip that almost went wrong because of the weather.",
    writing: {
      prompt:
        "Write a story about a camping trip that almost went wrong because of the weather. Use linking words to show the sequence of events.",
      writingTaskType: "writing_story",
      minWords: 100,
      maxWords: 120,
      rubricId: "expansion-writing_story-v1",
    },
  },
  {
    id: "024",
    part: "writing-part-2",
    skill: "writing",
    questionType: "writing",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["technology"],
    topicTag: "technology",
    stem: "Write an article for a youth magazine about whether teenagers should limit screen time.",
    writing: {
      prompt:
        "Write an article for a youth magazine about whether teenagers should limit screen time. Give reasons and examples.",
      writingTaskType: "writing_article",
      minWords: 100,
      maxWords: 120,
      rubricId: "expansion-writing_article-v1",
    },
  },
  {
    id: "025",
    part: "speaking-part-3",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "easy",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["hobbies"],
    topicTag: "hobbies",
    stem: "Discuss with your partner which school club new students should join first.",
    speaking: {
      prompt: "Discuss with your partner which school club new students should join first.",
      speakingTaskType: "speaking_discussion",
      maxDurationSeconds: 180,
      followUpQuestions: [
        "Which club is easiest for beginners?",
        "What skills can students learn there?",
        "How often does the club meet?",
      ],
      rubricId: "expansion-speaking_discussion-v1",
    },
  },
  {
    id: "026",
    part: "speaking-part-1",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "easy",
    grammarTags: ["question_forms"],
    vocabularyTopics: ["home"],
    topicTag: "home",
    stem: "Answer interview questions about where you live and your daily routine.",
    speaking: {
      prompt: "Answer interview questions about where you live and your daily routine.",
      speakingTaskType: "speaking_personal_questions",
      maxDurationSeconds: 150,
      followUpQuestions: [
        "What kind of house do you live in?",
        "Who do you usually have meals with?",
        "What do you do to relax after school?",
      ],
      rubricId: "expansion-speaking_personal_questions-v1",
    },
  },
  {
    id: "027",
    part: "speaking-part-2",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "medium",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["leisure"],
    topicTag: "leisure",
    stem: "Describe the photograph of a family enjoying a city festival.",
    speaking: {
      prompt:
        "Describe the photograph of a family enjoying a city festival. Say what each person is doing and what the atmosphere is like.",
      speakingTaskType: "speaking_picture_description",
      maxDurationSeconds: 180,
      rubricId: "expansion-speaking_picture_description-v1",
    },
  },
  {
    id: "028",
    part: "speaking-part-2",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "hard",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["transport"],
    topicTag: "transport",
    stem: "Describe the photograph of passengers waiting at an international airport gate.",
    speaking: {
      prompt:
        "Describe the photograph of passengers waiting at an international airport gate. Compare what different people are doing.",
      speakingTaskType: "speaking_picture_description",
      maxDurationSeconds: 180,
      rubricId: "expansion-speaking_picture_description-v1",
    },
  },
  {
    id: "029",
    part: "speaking-part-3",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "medium",
    grammarTags: ["future_going_to"],
    vocabularyTopics: ["environment"],
    topicTag: "environment",
    stem: "Discuss with your partner how your town could encourage more people to cycle.",
    speaking: {
      prompt: "Discuss with your partner how your town could encourage more people to cycle.",
      speakingTaskType: "speaking_discussion",
      maxDurationSeconds: 240,
      followUpQuestions: [
        "What new facilities would help cyclists?",
        "Who should pay for bike lanes?",
        "How can schools promote cycling safely?",
      ],
      rubricId: "expansion-speaking_discussion-v1",
    },
  },
  {
    id: "030",
    part: "speaking-part-1",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "hard",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["culture"],
    topicTag: "culture",
    stem: "Tell your partner about a memorable performance you watched at a theatre or concert.",
    speaking: {
      prompt: "Tell your partner about a memorable performance you watched at a theatre or concert.",
      speakingTaskType: "speaking_storytelling",
      maxDurationSeconds: 180,
      rubricId: "expansion-speaking_storytelling-v1",
    },
  },
]);
