import { buildExpansionItems } from "./expansion-item-factory";

export const STARTERS_EXPANSION_ITEMS = buildExpansionItems("starters", [
  {
    id: "001",
    part: "listening-part-1",
    skill: "listening",
    questionType: "matching",
    difficulty: "easy",
    grammarTags: ["have_got"],
    vocabularyTopics: ["family"],
    topicTag: "family",
    stem: "Listen and match each name to the correct family member picture.",
  },
  {
    id: "002",
    part: "listening-part-1",
    skill: "listening",
    questionType: "matching",
    difficulty: "easy",
    grammarTags: ["possessives"],
    vocabularyTopics: ["animals"],
    topicTag: "animals",
    stem: "Listen and match each child to the pet they describe.",
  },
  {
    id: "003",
    part: "listening-part-2",
    skill: "listening",
    questionType: "gap_fill",
    difficulty: "easy",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["numbers"],
    topicTag: "numbers",
    stem: "Listen and write the missing number.",
    template: "There are [0] ducks on the pond.",
    correctAnswers: ["four"],
  },
  {
    id: "004",
    part: "listening-part-2",
    skill: "listening",
    questionType: "gap_fill",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["food"],
    topicTag: "food",
    stem: "Listen and write the missing food word.",
    template: "Sam wants a [0] for lunch.",
    correctAnswers: ["banana"],
  },
  {
    id: "005",
    part: "listening-part-3",
    skill: "listening",
    questionType: "listening",
    difficulty: "easy",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["sports"],
    topicTag: "sports",
    stem: "Listen. Which picture shows the boy playing football?",
  },
  {
    id: "006",
    part: "listening-part-3",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["leisure"],
    topicTag: "leisure",
    stem: "Listen. Where can the children swim?",
    choices: [
      { text: "at the beach", isCorrect: true },
      { text: "in the classroom", isCorrect: false },
      { text: "on the bus", isCorrect: false },
    ],
  },
  {
    id: "007",
    part: "listening-part-4",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: "easy",
    grammarTags: ["articles"],
    vocabularyTopics: ["colours"],
    topicTag: "colours",
    stem: "Listen. Which colour should the girl's hat be?",
    choices: [
      { text: "red", isCorrect: false },
      { text: "yellow", isCorrect: true },
      { text: "purple", isCorrect: false },
    ],
  },
  {
    id: "008",
    part: "rw-part-1",
    skill: "reading",
    questionType: "matching",
    difficulty: "easy",
    grammarTags: ["articles"],
    vocabularyTopics: ["animals"],
    topicTag: "animals",
    stem: "Match each word to the correct animal picture.",
  },
  {
    id: "009",
    part: "rw-part-1",
    skill: "reading",
    questionType: "matching",
    difficulty: "easy",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["clothes"],
    topicTag: "clothes",
    stem: "Match each clothing word to the correct picture.",
  },
  {
    id: "010",
    part: "rw-part-2",
    skill: "reading",
    questionType: "reading_comprehension",
    difficulty: "easy",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["home"],
    topicTag: "home",
    stem: "Read: 'The dog sleeps on the sofa.' Which picture is correct?",
  },
  {
    id: "011",
    part: "rw-part-2",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "easy",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["school"],
    topicTag: "school",
    stem: "Read: 'There are three pencils on the desk.' Choose the right picture.",
    choices: [
      { text: "one pencil", isCorrect: false },
      { text: "three pencils", isCorrect: true },
      { text: "five pencils", isCorrect: false },
    ],
  },
  {
    id: "012",
    part: "rw-part-2",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "medium",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["transport"],
    topicTag: "transport",
    stem: "Read: 'The bus is in front of the school.' Which picture shows this?",
    choices: [
      { text: "bus behind school", isCorrect: false },
      { text: "bus in front of school", isCorrect: true },
      { text: "bus inside school", isCorrect: false },
    ],
  },
  {
    id: "013",
    part: "rw-part-3",
    skill: "reading",
    questionType: "reading_comprehension",
    difficulty: "medium",
    grammarTags: ["question_forms"],
    vocabularyTopics: ["friends"],
    topicTag: "friends",
    stem: "Read the short message: 'Hi Tom! Can you come to my party on Saturday?' What day is the party?",
  },
  {
    id: "014",
    part: "rw-part-3",
    skill: "reading",
    questionType: "reading_comprehension",
    difficulty: "easy",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["weather"],
    topicTag: "weather",
    stem: "Read: 'It is sunny today. We play in the garden.' Where are the children playing?",
  },
  {
    id: "015",
    part: "rw-part-3",
    skill: "reading",
    questionType: "gap_fill",
    difficulty: "medium",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["feelings"],
    topicTag: "feelings",
    stem: "Read and complete: 'The baby is _____.'",
    template: "The baby is [0].",
    correctAnswers: ["happy"],
  },
  {
    id: "016",
    part: "listening-part-4",
    skill: "listening",
    questionType: "listening",
    difficulty: "medium",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["nature"],
    topicTag: "nature",
    stem: "Listen. Which tree should have apples drawn on it?",
  },
  {
    id: "017",
    part: "rw-part-1",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: "easy",
    grammarTags: ["pronouns"],
    vocabularyTopics: ["drink"],
    topicTag: "drink",
    stem: "Which word matches the picture of a glass of milk?",
    choices: [
      { text: "juice", isCorrect: false },
      { text: "milk", isCorrect: true },
      { text: "water", isCorrect: false },
    ],
  },
  {
    id: "018",
    part: "rw-part-3",
    skill: "reading",
    questionType: "gap_fill",
    difficulty: "easy",
    grammarTags: ["have_got"],
    vocabularyTopics: ["hobbies"],
    topicTag: "hobbies",
    stem: "Complete: 'I have got a new _____.'",
    template: "I have got a new [0].",
    correctAnswers: ["kite"],
  },
  {
    id: "019",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "easy",
    grammarTags: ["verb_be"],
    vocabularyTopics: ["family"],
    topicTag: "family",
    stem: "Look at the picture. Write one sentence about the boy and his dad.",
    writing: {
      prompt: "Look at the picture. Write one sentence about the boy and his dad.",
      writingTaskType: "write_sentence",
      minWords: 3,
      maxWords: 15,
      rubricId: "expansion-write_sentence-v1",
    },
  },
  {
    id: "020",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "easy",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["animals"],
    topicTag: "animals",
    stem: "Look at the picture. Write one sentence about what the rabbit is doing.",
    writing: {
      prompt: "Look at the picture. Write one sentence about what the rabbit is doing.",
      writingTaskType: "write_sentence",
      minWords: 4,
      maxWords: 18,
      rubricId: "expansion-write_sentence-v1",
    },
  },
  {
    id: "021",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "medium",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["school"],
    topicTag: "school",
    stem: "Write a short note to your teacher. Say you are sorry you are late.",
    writing: {
      prompt: "Write a short note to your teacher. Say you are sorry you are late.",
      writingTaskType: "writing_message",
      minWords: 5,
      maxWords: 25,
      rubricId: "expansion-writing_message-v1",
    },
  },
  {
    id: "022",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "easy",
    grammarTags: ["imperatives"],
    vocabularyTopics: ["friends"],
    topicTag: "friends",
    stem: "Write a message to your friend. Ask them to come to your house after school.",
    writing: {
      prompt: "Write a message to your friend. Ask them to come to your house after school.",
      writingTaskType: "writing_message",
      minWords: 5,
      maxWords: 25,
      rubricId: "expansion-writing_message-v1",
    },
  },
  {
    id: "023",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "medium",
    grammarTags: ["there_is_are"],
    vocabularyTopics: ["places"],
    topicTag: "places",
    stem: "Look at the park picture. Write two sentences about what you can see.",
    writing: {
      prompt: "Look at the park picture. Write two sentences about what you can see.",
      writingTaskType: "picture_description",
      minWords: 8,
      maxWords: 30,
      rubricId: "expansion-picture_description-v1",
    },
  },
  {
    id: "024",
    part: "rw-part-4",
    skill: "writing",
    questionType: "writing",
    difficulty: "easy",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["food"],
    topicTag: "food",
    stem: "Look at the kitchen picture. Write two sentences about the food on the table.",
    writing: {
      prompt: "Look at the kitchen picture. Write two sentences about the food on the table.",
      writingTaskType: "picture_description",
      minWords: 8,
      maxWords: 30,
      rubricId: "expansion-picture_description-v1",
    },
  },
  {
    id: "025",
    part: "speaking-part-1",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "easy",
    grammarTags: ["prepositions"],
    vocabularyTopics: ["home"],
    topicTag: "home",
    stem: "Look at the two bedroom pictures. Tell your teacher four differences.",
    speaking: {
      prompt: "Look at the two bedroom pictures. Tell your teacher four differences.",
      speakingTaskType: "speaking_picture_description",
      maxDurationSeconds: 90,
      rubricId: "expansion-speaking_picture_description-v1",
    },
  },
  {
    id: "026",
    part: "speaking-part-1",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "medium",
    grammarTags: ["present_continuous"],
    vocabularyTopics: ["leisure"],
    topicTag: "leisure",
    stem: "Look at the two park pictures. Say what is different in each picture.",
    speaking: {
      prompt: "Look at the two park pictures. Say what is different in each picture.",
      speakingTaskType: "speaking_picture_description",
      maxDurationSeconds: 90,
      rubricId: "expansion-speaking_picture_description-v1",
    },
  },
  {
    id: "027",
    part: "speaking-part-2",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "easy",
    grammarTags: ["question_forms"],
    vocabularyTopics: ["family"],
    topicTag: "family",
    stem: "Answer questions about your family.",
    speaking: {
      prompt: "Answer questions about your family.",
      speakingTaskType: "speaking_personal_questions",
      maxDurationSeconds: 60,
      followUpQuestions: [
        "How many people are there in your family?",
        "Who is the oldest person in your family?",
        "What does your mum or dad do every morning?",
      ],
      rubricId: "expansion-speaking_personal_questions-v1",
    },
  },
  {
    id: "028",
    part: "speaking-part-2",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "easy",
    grammarTags: ["modal_can"],
    vocabularyTopics: ["sports"],
    topicTag: "sports",
    stem: "Answer questions about sports and games you like.",
    speaking: {
      prompt: "Answer questions about sports and games you like.",
      speakingTaskType: "speaking_personal_questions",
      maxDurationSeconds: 60,
      followUpQuestions: [
        "What sport do you like best?",
        "Can you swim?",
        "Do you play sport at school?",
      ],
      rubricId: "expansion-speaking_personal_questions-v1",
    },
  },
  {
    id: "029",
    part: "speaking-part-3",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "medium",
    grammarTags: ["past_simple"],
    vocabularyTopics: ["travel"],
    topicTag: "travel",
    stem: "Look at the picture story. Tell the story of the family trip to the beach.",
    speaking: {
      prompt: "Look at the picture story. Tell the story of the family trip to the beach.",
      speakingTaskType: "speaking_storytelling",
      maxDurationSeconds: 120,
      rubricId: "expansion-speaking_storytelling-v1",
    },
  },
  {
    id: "030",
    part: "speaking-part-3",
    skill: "speaking",
    questionType: "speaking",
    difficulty: "easy",
    grammarTags: ["present_simple"],
    vocabularyTopics: ["animals"],
    topicTag: "animals",
    stem: "Look at the picture story. Tell the story of the lost puppy.",
    speaking: {
      prompt: "Look at the picture story. Tell the story of the lost puppy.",
      speakingTaskType: "speaking_storytelling",
      maxDurationSeconds: 120,
      rubricId: "expansion-speaking_storytelling-v1",
    },
  },
]);
