/** Flyers U4 — grammar lessons (3 × 5 exercises). */

export function grammarLessons({
  buildMcq,
  buildGapFill,
  buildSentenceOrdering,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "grammar-gerunds-infinitives",
      title: "Lesson 1: enjoy watching / want to see",
      learningObjective:
        "Use enjoy + -ing and want to + verb when talking about media.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-gerund-learn",
          title: "Learn: enjoy watching",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh _____ watching cartoons on television.",
              skillTag: "grammar",
              topicTag,
              explanation: "Enjoys watching — enjoy + V-ing, không dùng to watch.",
              correct: "enjoys watching",
              wrong: ["enjoys to watch", "enjoy watch"],
              distractorNotes: ["Enjoy không đi với to", "Thiếu -ing"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh _____ to see a new film at the cinema.",
              skillTag: "grammar",
              topicTag,
              explanation: "Wants to see — want + to + verb.",
              correct: "wants to see",
              wrong: ["wants seeing", "want see"],
              distractorNotes: ["Want không đi với -ing", "Thiếu to"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "I _____ watching documentaries about animals.",
              skillTag: "grammar",
              topicTag,
              explanation: "Enjoy watching — enjoy + V-ing.",
              correct: "enjoy watching",
              wrong: ["enjoy to watch", "enjoy watch"],
              distractorNotes: ["Enjoy + to (×)", "Thiếu -ing"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Do you _____ to watch the news tonight?",
              skillTag: "grammar",
              topicTag,
              explanation: "Want to watch — câu hỏi với want to + verb.",
              correct: "want to watch",
              wrong: ["want watching", "want watch"],
              distractorNotes: ["Want + -ing (×)", "Thiếu to"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-gerund-practice",
          title: "Practice: Complete enjoy / want",
          instructions: "Fill in each gap with the correct form.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh enjoys [0] comedy programmes. | Linh wants [1] see a cartoon. | We enjoy [2] films on a big screen.",
              skillTag: "grammar",
              topicTag,
              explanation: "watching; to; watching — enjoy + -ing, want to + verb.",
              template:
                "Minh enjoys [0] comedy programmes. Linh wants [1] see a cartoon. We enjoy [2] films on a big screen.",
              correctAnswers: ["watching", "to", "watching"],
              acceptableAnswers: [
                ["watching", "Watching"],
                ["to", "To"],
                ["watching", "Watching"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-gerund-check",
          title: "Check: Gerund and Infinitive Challenge",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "I enjoy watching television — enjoy + V-ing.",
              correct: "I enjoy watching television after school.",
              wrong: [
                "I enjoy to watch television after school.",
                "I enjoy watch television after school.",
              ],
              distractorNotes: ["Enjoy + to (×)", "Thiếu -ing"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "She wants to see a film — want to + verb.",
              correct: "She wants to see a film at the cinema.",
              wrong: [
                "She wants seeing a film at the cinema.",
                "She want see a film at the cinema.",
              ],
              distractorNotes: ["Want + -ing (×)", "Thiếu to và -s"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh and Linh _____ listening to music on the radio.",
              skillTag: "grammar",
              topicTag,
              explanation: "Enjoy listening — enjoy + V-ing.",
              correct: "enjoy listening",
              wrong: ["enjoy to listen", "enjoy listen"],
              distractorNotes: ["Enjoy + to (×)", "Thiếu -ing"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-gerund-apply",
          title: "Apply: Build enjoy / want Sentences",
          instructions: "Put the words in the correct order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Minh / enjoys / watching / documentaries / on / television.",
              skillTag: "grammar",
              topicTag,
              explanation: "Minh enjoys watching documentaries on television.",
              words: ["Minh", "enjoys", "watching", "documentaries", "on", "television."],
              correctOrder: [0, 1, 2, 3, 4, 5],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: Linh / wants / to / see / a / new / comedy.",
              skillTag: "grammar",
              topicTag,
              explanation: "Linh wants to see a new comedy.",
              words: ["Linh", "wants", "to", "see", "a", "new", "comedy."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-gerund-review",
          title: "Review: enjoy / want Mix",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "We _____ watching our favourite programme together.",
              skillTag: "grammar",
              topicTag,
              explanation: "Enjoy watching — enjoy + V-ing.",
              correct: "enjoy watching",
              wrong: ["enjoy to watch", "enjoys watch"],
              distractorNotes: ["Enjoy + to (×)", "Sai ngôi và thiếu -ing"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Dad _____ to watch the news on channel three.",
              skillTag: "grammar",
              topicTag,
              explanation: "Wants to watch — want to + verb, ngôi 3 thêm -s.",
              correct: "wants to watch",
              wrong: ["wants watching", "want to watch"],
              distractorNotes: ["Want + -ing (×)", "Thiếu -s cho Dad"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "They enjoy watching films — enjoy + V-ing.",
              correct: "They enjoy watching films on a big screen.",
              wrong: [
                "They enjoy to watch films on a big screen.",
                "They enjoys watching films on a big screen.",
              ],
              distractorNotes: ["Enjoy + to (×)", "Enjoys với They (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-too-enough",
      title: "Lesson 2: Too / enough",
      learningObjective:
        "Use too + adjective and adjective + enough to describe media.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-too-learn",
          title: "Learn: too + adjective",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "The news programme is _____ boring for Minh.",
              skillTag: "grammar",
              topicTag,
              explanation: "Too boring — too + adjective = quá nhàm chán.",
              correct: "too",
              wrong: ["enough", "very only"],
              distractorNotes: ["Enough = đủ, không phải quá", "Very không có nghĩa vượt mức"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The television screen is _____ small for a big audience.",
              skillTag: "grammar",
              topicTag,
              explanation: "Too small — màn hình quá nhỏ.",
              correct: "too",
              wrong: ["enough", "enjoy"],
              distractorNotes: ["Enough small (×)", "Verb không phù hợp"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The comedy was funny _____ for the whole family.",
              skillTag: "grammar",
              topicTag,
              explanation: "Funny enough — adjective + enough = đủ vui.",
              correct: "enough",
              wrong: ["too", "to"],
              distractorNotes: ["Too = quá, không phải đủ", "To là giới từ khác"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The film is exciting _____ for Linh.",
              skillTag: "grammar",
              topicTag,
              explanation: "Exciting enough — đủ hấp dẫn.",
              correct: "enough",
              wrong: ["too", "enjoy"],
              distractorNotes: ["Too exciting = quá hấp dẫn", "Verb"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-too-practice",
          title: "Practice: Complete too / enough",
          instructions: "Fill in each gap.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: The news is [0] boring. | The screen is [1] small. | The comedy is funny [2].",
              skillTag: "grammar",
              topicTag,
              explanation: "too; too; enough — too + adj; adj + enough.",
              template:
                "The news is [0] boring. The screen is [1] small. The comedy is funny [2].",
              correctAnswers: ["too", "too", "enough"],
              acceptableAnswers: [
                ["too", "Too"],
                ["too", "Too"],
                ["enough", "Enough"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-too-check",
          title: "Check: Too / enough Challenge",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "The screen is too dark — too + adjective.",
              correct: "The screen is too dark to watch the film.",
              wrong: [
                "The screen is enough dark to watch the film.",
                "The screen is too enough dark.",
              ],
              distractorNotes: ["Enough dark (×)", "Too enough (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "The documentary is interesting enough — adj + enough.",
              correct: "The documentary is interesting enough for Minh.",
              wrong: [
                "The documentary is enough interesting for Minh.",
                "The documentary is too enough interesting.",
              ],
              distractorNotes: ["Enough interesting (×)", "Too enough (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The news on this channel is _____ long.",
              skillTag: "grammar",
              topicTag,
              explanation: "Too long — quá dài.",
              correct: "too",
              wrong: ["enough", "enjoy"],
              distractorNotes: ["Enough = đủ dài", "Verb"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-too-apply",
          title: "Apply: Order too / enough Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: The / screen / is / too / small / for / the / audience.",
              skillTag: "grammar",
              topicTag,
              explanation: "The screen is too small for the audience.",
              words: ["The", "screen", "is", "too", "small", "for", "the", "audience."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: The / film / is / exciting / enough / for / everyone.",
              skillTag: "grammar",
              topicTag,
              explanation: "The film is exciting enough for everyone.",
              words: ["The", "film", "is", "exciting", "enough", "for", "everyone."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-too-review",
          title: "Review: Too / enough Mix",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Last week's comedy was _____ boring.",
              skillTag: "grammar",
              topicTag,
              explanation: "Too boring — quá nhàm chán.",
              correct: "too",
              wrong: ["enough", "to"],
              distractorNotes: ["Enough boring (×)", "To không đi với adj"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The actor is funny _____ for this comedy.",
              skillTag: "grammar",
              topicTag,
              explanation: "Funny enough — đủ hài.",
              correct: "enough",
              wrong: ["too", "enjoy"],
              distractorNotes: ["Too funny = quá hài", "Verb"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "We have enough time — enough + noun.",
              correct: "We have enough time to watch one programme.",
              wrong: [
                "We have time enough to watch one programme.",
                "We have too enough time to watch one programme.",
              ],
              distractorNotes: ["Time enough ít dùng ở A2", "Too enough (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "grammar-media-mixed",
      title: "Lesson 3: Gerunds, Infinitives and Too/Enough — Mixed",
      learningObjective:
        "Combine enjoy/want patterns with too/enough in media sentences.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "grammar-mixed-learn",
          title: "Learn: Media Grammar Together",
          instructions: "Choose the correct form.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh enjoys watching cartoons but the news is _____ boring.",
              skillTag: "grammar",
              topicTag,
              explanation: "Too boring — too + adjective sau enjoy watching.",
              correct: "too",
              wrong: ["enough", "to"],
              distractorNotes: ["Enough = đủ", "To không đi với adj"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh wants to see the film because the actor is interesting _____.",
              skillTag: "grammar",
              topicTag,
              explanation: "Interesting enough — want to see + adj + enough.",
              correct: "enough",
              wrong: ["too", "enjoy"],
              distractorNotes: ["Too = quá", "Verb"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The screen is too small, so we _____ to watch at the cinema.",
              skillTag: "grammar",
              topicTag,
              explanation: "Want to watch — want to + verb.",
              correct: "want to watch",
              wrong: ["want watching", "enjoy to watch"],
              distractorNotes: ["Want + -ing (×)", "Enjoy + to (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "I enjoy watching documentaries when they are _____ enough.",
              skillTag: "grammar",
              topicTag,
              explanation: "Interesting enough — adj + enough.",
              correct: "interesting",
              wrong: ["too", "enjoy"],
              distractorNotes: ["Too alone không đủ", "Verb lặp"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-practice",
          title: "Practice: Mixed Media Grammar",
          instructions: "Fill in each gap with the correct form.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh enjoys [0] comedy programmes. | The news is [1] boring. | Linh wants [2] see an exciting film.",
              skillTag: "grammar",
              topicTag,
              explanation: "watching; too; to — enjoy + -ing; too + adj; want to.",
              template:
                "Minh enjoys [0] comedy programmes. The news is [1] boring. Linh wants [2] see an exciting film.",
              correctAnswers: ["watching", "too", "to"],
              acceptableAnswers: [
                ["watching", "Watching"],
                ["too", "Too"],
                ["to", "To"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-check",
          title: "Check: Mixed Grammar Challenge",
          instructions: "Choose the correct sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Enjoy watching + too boring — cả hai cấu trúc đúng.",
              correct: "I enjoy watching television but the news is too boring.",
              wrong: [
                "I enjoy to watch television but the news is too boring.",
                "I enjoy watching television but the news is enough boring.",
              ],
              distractorNotes: ["Enjoy + to (×)", "Enough boring (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Want to see + exciting enough.",
              correct: "She wants to see a film that is exciting enough.",
              wrong: [
                "She wants seeing a film that is too enough exciting.",
                "She want to see a film exciting too.",
              ],
              distractorNotes: ["Want seeing + too enough (×)", "Word order wrong"],
              difficultyRating: 3,
            }),
            buildMcq({
              questionText: "The comedy is funny enough, so the audience _____ watching.",
              skillTag: "grammar",
              topicTag,
              explanation: "Enjoys watching — enjoy + V-ing.",
              correct: "enjoys watching",
              wrong: ["enjoys to watch", "enjoy watch"],
              distractorNotes: ["Enjoy + to (×)", "Thiếu -ing"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-apply",
          title: "Apply: Build Mixed Sentences",
          instructions: "Put the words in order.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          questions: [
            buildSentenceOrdering({
              questionText: "Make: Linh / enjoys / watching / cartoons / but / the / news / is / too / boring.",
              skillTag: "grammar",
              topicTag,
              explanation: "Linh enjoys watching cartoons but the news is too boring.",
              words: ["Linh", "enjoys", "watching", "cartoons", "but", "the", "news", "is", "too", "boring."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
              difficultyRating: 2,
            }),
            buildSentenceOrdering({
              questionText: "Make: We / want / to / watch / a / film / exciting / enough.",
              skillTag: "grammar",
              topicTag,
              explanation: "We want to watch a film exciting enough.",
              words: ["We", "want", "to", "watch", "a", "film", "exciting", "enough."],
              correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-mixed-review",
          title: "Review: Media Grammar Mix",
          instructions: "Choose the correct answer.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Minh _____ documentaries but the screen is too small.",
              skillTag: "grammar",
              topicTag,
              explanation: "Enjoys watching — enjoy + V-ing.",
              correct: "enjoys watching",
              wrong: ["enjoys to watch", "enjoy watch"],
              distractorNotes: ["Enjoy + to (×)", "Thiếu -ing"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They _____ to see the comedy because it looks funny enough.",
              skillTag: "grammar",
              topicTag,
              explanation: "Want to see — want to + verb.",
              correct: "want to see",
              wrong: ["want seeing", "wants to see only"],
              distractorNotes: ["Want + -ing (×)", "They → want không wants"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which sentence is correct?",
              skillTag: "grammar",
              topicTag,
              explanation: "Too many programmes + enjoy watching.",
              correct: "There are too many programmes but I enjoy watching comedy.",
              wrong: [
                "There are enough many programmes but I enjoy to watch comedy.",
                "There are too many programmes but I enjoy watch comedy.",
              ],
              distractorNotes: ["Enough many + enjoy to (×)", "Enjoy watch (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
