/** Flyers U4 — listening lessons (3 × 5 exercises). */

export function listeningLessons({
  buildMcq,
  buildMatching,
  buildListeningExercise,
  buildExercise,
  listeningScriptTVChoices,
  listeningScriptCinemaNight,
  listeningAnswerKeys,
  topicTag,
}) {
  const tvChoices = listeningScriptTVChoices;
  const cinemaNight = listeningScriptCinemaNight;
  const keysTV = listeningAnswerKeys.tvChoices;
  const keysCinema = listeningAnswerKeys.cinemaNight;

  return [
    {
      slug: "listening-tv-opinions",
      title: "Lesson 1: TV Programme Opinions",
      learningObjective:
        "Listen for opinions and attitudes when choosing TV programmes.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-tv-learn",
          title: "Learn: Choosing What to Watch",
          instructions: "Listen to Minh and Linh. Answer the questions.",
          sortOrder: 0,
          script: tvChoices,
          answerKey: keysTV,
          questions: [
            buildMcq({
              questionText: "What does Linh enjoy watching?",
              skillTag: "listening",
              topicTag,
              explanation: "Cartoons — Linh nói enjoy watching cartoons.",
              correct: "Cartoons",
              wrong: ["Only the news", "Science experiments"],
              distractorNotes: ["Minh mentions news too long", "Science U5"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "What does Minh think about cartoons?",
              skillTag: "listening",
              topicTag,
              explanation: "OK but he wants a documentary — thái độ trung lập/khác Linh.",
              correct: "They are OK but he prefers a documentary",
              wrong: ["They are his favourite", "They are too boring for everyone"],
              distractorNotes: ["Linh loves cartoons", "Linh enjoys cartoons"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-tv-practice",
          title: "Practice: Attitudes About Programmes",
          instructions: "Listen again. Focus on opinions.",
          sortOrder: 1,
          script: tvChoices,
          answerKey: keysTV,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "How does Linh feel about the news on this channel?",
              skillTag: "listening",
              topicTag,
              explanation: "Too long — quá dài, thái độ tiêu cực.",
              correct: "It is too long",
              wrong: ["It is her favourite", "It is exciting enough"],
              distractorNotes: ["Comedy is favourite", "Comedy is exciting"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What does Minh say about the actor on the screen?",
              skillTag: "listening",
              topicTag,
              explanation: "Looks funny enough — diễn viên đủ hài.",
              correct: "Looks funny enough",
              wrong: ["Is too boring", "Is from the parade"],
              distractorNotes: ["Last comedy boring not this actor", "Festival U3"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-tv-check",
          title: "Check: TV Opinion Listening",
          instructions: "Listen carefully. Choose the best answer.",
          sortOrder: 2,
          script: tvChoices,
          answerKey: keysTV,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What programme do they decide to watch?",
              skillTag: "listening",
              topicTag,
              explanation: "A comedy — Let's watch a comedy instead.",
              correct: "A comedy",
              wrong: ["The news", "Only a documentary"],
              distractorNotes: ["News too long", "Minh wanted documentary first"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What is Linh's favourite type of programme?",
              skillTag: "listening",
              topicTag,
              explanation: "Comedies are my favourite — phim hài yêu thích.",
              correct: "Comedies",
              wrong: ["Documentaries only", "The news"],
              distractorNotes: ["Minh prefers documentaries", "News too long"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What will they do if the programme is too boring?",
              skillTag: "listening",
              topicTag,
              explanation: "Change the channel — đổi kênh.",
              correct: "Change the channel",
              wrong: ["Go to the cinema immediately", "Listen to the parade"],
              distractorNotes: ["Cinema is different dialogue", "Festival U3"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-tv-apply",
          title: "Apply: Match Opinion to Speaker",
          instructions: "Listen again. Match each opinion to Minh or Linh.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: tvChoices },
          questions: [
            buildMatching({
              questionText: "Match each opinion to the correct speaker.",
              skillTag: "listening",
              topicTag,
              explanation: "Linh: cartoons/comedy favourite; Minh: documentary/actor funny enough.",
              pairs: [
                { left: "Linh", right: "enjoys watching cartoons" },
                { left: "Minh", right: "wants to see a documentary about animals" },
                { left: "Linh", right: "comedies are her favourite" },
                { left: "Minh", right: "will change channel if too boring" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-tv-review",
          title: "Review: TV Opinions Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: tvChoices,
          answerKey: keysTV,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "How does Linh describe the last video they watched?",
              skillTag: "listening",
              topicTag,
              explanation: "Exciting — video was exciting.",
              correct: "Exciting",
              wrong: ["Too boring", "Too long"],
              distractorNotes: ["If too boring change channel", "News too long"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh thinks there are too many _____ tonight.",
              skillTag: "listening",
              topicTag,
              explanation: "Programmes — too many programmes on television.",
              correct: "programmes",
              wrong: ["parades", "experiments"],
              distractorNotes: ["Festival U3", "Science U5"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-cinema-attitudes",
      title: "Lesson 2: Cinema Trip Attitudes",
      learningObjective:
        "Understand speakers' attitudes when planning a cinema visit.",
      estimatedMinutes: 20,
      exercises: [
        buildListeningExercise({
          slug: "listening-cinema-learn",
          title: "Learn: Planning the Cinema Trip",
          instructions: "Listen to Linh, Minh and Dad. Answer the questions.",
          sortOrder: 0,
          script: cinemaNight,
          answerKey: keysCinema,
          questions: [
            buildMcq({
              questionText: "Does Minh want to see the new film?",
              skillTag: "listening",
              topicTag,
              explanation: "Yes! — thái độ tích cực.",
              correct: "Yes, he does",
              wrong: ["No, television is better", "No, it is too boring"],
              distractorNotes: ["He prefers big screen cinema", "He is excited"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Why does Minh prefer the cinema?",
              skillTag: "listening",
              topicTag,
              explanation: "Television screen is too small — màn hình tivi quá nhỏ.",
              correct: "The television screen is too small",
              wrong: ["The news is too long", "He hates comedies"],
              distractorNotes: ["News in TV dialogue", "He likes the actor"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cinema-practice",
          title: "Practice: Film Preferences",
          instructions: "Listen again. Focus on attitudes.",
          sortOrder: 1,
          script: cinemaNight,
          answerKey: keysCinema,
          difficulty: 0.26,
          questions: [
            buildMcq({
              questionText: "What type of film does Linh prefer?",
              skillTag: "listening",
              topicTag,
              explanation: "Exciting comedy — prefers comedy over documentary.",
              correct: "An exciting comedy",
              wrong: ["A boring documentary", "Only the news"],
              distractorNotes: ["Documentary looks interesting but she prefers comedy", "News on radio"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How does Linh feel about the documentary?",
              skillTag: "listening",
              topicTag,
              explanation: "Looks interesting — tích cực nhưng không chọn.",
              correct: "It looks interesting",
              wrong: ["It is too boring", "It is her favourite actor"],
              distractorNotes: ["Positive attitude", "Actor is in comedy"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cinema-check",
          title: "Check: Cinema Attitude Listening",
          instructions: "Listen to the full conversation again.",
          sortOrder: 2,
          script: cinemaNight,
          answerKey: keysCinema,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText: "What time does the comedy start?",
              skillTag: "listening",
              topicTag,
              explanation: "At two — starts at two.",
              correct: "At two o'clock",
              wrong: ["At seven o'clock", "At midnight"],
              distractorNotes: ["Seven is programme time in reading", "Not mentioned"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Who is Minh's favourite actor in the film?",
              skillTag: "listening",
              topicTag,
              explanation: "The actor in that film is my favourite — diễn viên trong phim hài.",
              correct: "The actor in the comedy film",
              wrong: ["A dancer in the parade", "A scientist in a lab"],
              distractorNotes: ["Festival U3", "Science U5"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What did the audience do during the best scene?",
              skillTag: "listening",
              topicTag,
              explanation: "Clapped loudly — vỗ tay mạnh.",
              correct: "Clapped loudly",
              wrong: ["Changed the channel", "Recycled plastic"],
              distractorNotes: ["TV dialogue", "Eco U2"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-cinema-apply",
          title: "Apply: Order Cinema Opinions",
          instructions: "Put the attitudes in the order they are discussed.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          content: { script: cinemaNight },
          questions: [
            buildMcq({
              questionText:
                "Correct order: (1) comedy vs documentary (2) cinema invitation (3) radio in car",
              skillTag: "listening",
              topicTag,
              explanation: "Invitation → comedy preference → radio/news in car.",
              correct: "2 → 1 → 3",
              wrong: ["1 → 3 → 2", "3 → 2 → 1"],
              distractorNotes: ["Invitation first", "Radio is last"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-cinema-review",
          title: "Review: Cinema Attitudes Mix",
          instructions: "Listen and answer — mixed review.",
          sortOrder: 4,
          script: cinemaNight,
          answerKey: keysCinema,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Where is the best scene in the film?",
              skillTag: "listening",
              topicTag,
              explanation: "On a ship — cảnh trên tàu.",
              correct: "On a ship",
              wrong: ["At Hoan Kiem Lake", "In the school gym"],
              distractorNotes: ["Fireworks lake U3", "School festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Dad asks if two o'clock is early _____ for them.",
              skillTag: "listening",
              topicTag,
              explanation: "Early enough — đủ sớm.",
              correct: "enough",
              wrong: ["too", "boring"],
              distractorNotes: ["Too = quá", "Adjective không phù hợp"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "listening-media-review",
      title: "Lesson 3: Mixed Opinion and Attitude",
      learningObjective:
        "Identify opinions and attitudes across two media dialogues.",
      estimatedMinutes: 22,
      exercises: [
        buildListeningExercise({
          slug: "listening-review-learn",
          title: "Learn: TV Choices Reminder",
          instructions: "Listen to the TV choices dialogue again.",
          sortOrder: 0,
          script: tvChoices,
          answerKey: keysTV,
          questions: [
            buildMcq({
              questionText: "What attitude does Linh show toward comedies?",
              skillTag: "listening",
              topicTag,
              explanation: "Positive — comedies are my favourite.",
              correct: "Very positive — they are her favourite",
              wrong: ["Negative — too boring", "Neutral — no opinion"],
              distractorNotes: ["News is too long not comedy", "She states favourite clearly"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh's attitude toward documentaries is _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Positive — wants to see documentary about animals.",
              correct: "positive",
              wrong: ["negative", "angry"],
              distractorNotes: ["He wants to see one", "Friendly tone"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-practice",
          title: "Practice: Cinema Reminder",
          instructions: "Listen to the cinema dialogue again.",
          sortOrder: 1,
          script: cinemaNight,
          answerKey: keysCinema,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Minh's attitude toward watching at the cinema is _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Much better when exciting enough — rất tích cực.",
              correct: "very positive",
              wrong: ["negative", "bored"],
              distractorNotes: ["He says much better", "He wants to go"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What does the news on the radio say about the film?",
              skillTag: "listening",
              topicTag,
              explanation: "The film is popular — phim phổ biến.",
              correct: "The film is popular",
              wrong: ["The film is too boring", "The parade is starting"],
              distractorNotes: ["Positive news", "Parade U3"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-check",
          title: "Check: Mixed Attitude Listening",
          instructions: "Listen to the cinema dialogue. Harder questions.",
          sortOrder: 2,
          script: cinemaNight,
          answerKey: keysCinema,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which detail is ONLY in the TV choices dialogue?",
              skillTag: "listening",
              topicTag,
              explanation: "Change the channel if too boring — chỉ hội thoại TV.",
              correct: "Change the channel if too boring",
              wrong: ["Listen to the radio in the car", "Comedy starts at two"],
              distractorNotes: ["Cinema dialogue", "Cinema dialogue"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Both dialogues show speakers who _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Give opinions about programmes and films — đúng cả hai.",
              correct: "give opinions about programmes and films",
              wrong: ["only talk about festivals", "only use past tense went/saw"],
              distractorNotes: ["Media topic not festivals", "Present/future opinions too"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "listening-review-apply",
          title: "Apply: Match Dialogue to Attitude",
          instructions: "Match each attitude to the correct dialogue.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { script: cinemaNight },
          questions: [
            buildMatching({
              questionText: "Match attitudes to TV choices or Cinema dialogue.",
              skillTag: "listening",
              topicTag,
              explanation: "TV: too many programmes; Cinema: screen too small, popular film.",
              pairs: [
                { left: "Too many programmes tonight", right: "TV choices dialogue" },
                { left: "Television screen is too small", right: "Cinema dialogue" },
                { left: "Comedies are my favourite", right: "TV choices dialogue" },
                { left: "Film is popular on the news", right: "Cinema dialogue" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-review-final",
          title: "Review: Both Dialogues Mix",
          instructions: "Listen to the TV choices dialogue. Final review.",
          sortOrder: 4,
          script: tvChoices,
          answerKey: keysTV,
          difficulty: 0.34,
          questions: [
            buildMcq({
              questionText: "Which word describes Linh's attitude to the last video?",
              skillTag: "listening",
              topicTag,
              explanation: "Exciting — video was exciting.",
              correct: "exciting",
              wrong: ["boring", "too long"],
              distractorNotes: ["If boring they'd change channel", "News too long"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "In BOTH dialogues, speakers mention _____.",
              skillTag: "listening",
              topicTag,
              explanation: "Comedy/comedies in both — phim hài.",
              correct: "comedy or comedies",
              wrong: ["fireworks only", "recycling only"],
              distractorNotes: ["Fireworks U3 only", "Eco U2 only"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
