/** Flyers U4 — reading lessons (3 × 5 exercises). */

export function readingLessons({
  buildMcq,
  buildGapFill,
  buildMatching,
  buildReadingExercise,
  buildExercise,
  passageMinhTV,
  topicTag,
}) {
  const passage = passageMinhTV;

  return [
    {
      slug: "reading-missing-sentences",
      title: "Lesson 1: Complete Conversations with Missing Sentences",
      learningObjective:
        "Choose the best missing sentence to complete a TV conversation.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-missing-learn",
          title: "Learn: Read the TV Conversation",
          instructions: "Read the passage. Choose the best missing sentence.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText:
                'Minh: "Let\'s watch the news on channel three." Linh: "_____"',
              skillTag: "reading",
              topicTag,
              explanation: "The news is too boring! I want to see a cartoon — Linh phản đối tin tức.",
              correct: "The news is too boring! I want to see a cartoon.",
              wrong: [
                "The audience clapped when the film finished.",
                "Grandma listens to the radio in the kitchen.",
              ],
              distractorNotes: ["Không liên quan hội thoại", "Không trong bài"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText:
                'Minh: "Cartoons are for little children. I enjoy watching documentaries." Linh: "_____"',
              skillTag: "reading",
              topicTag,
              explanation: "Documentaries can be interesting, but your screen is too small — trong bài đọc.",
              correct:
                "Documentaries can be interesting, but your screen is too small. Let's watch a comedy — comedies are my favourite programmes.",
              wrong: [
                "The news is too boring! I want to see a cartoon.",
                "We went to the national parade yesterday.",
              ],
              distractorNotes: ["Câu trước đó", "Unit 3 festival"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-missing-practice",
          title: "Practice: More Missing Sentences",
          instructions: "Read again. Choose the best sentence to complete each gap.",
          sortOrder: 1,
          passage,
          difficulty: 0.25,
          questions: [
            buildMcq({
              questionText:
                'Minh: "OK, but only if the actor is funny enough. Last week\'s comedy was boring." Linh: "_____"',
              skillTag: "reading",
              topicTag,
              explanation: "This one has an exciting scene on a ship — Linh mô tả phim hài.",
              correct:
                "This one has an exciting scene on a ship. The whole audience at school said it was interesting.",
              wrong: [
                "Let's watch the news on channel three.",
                "The screen was too small for recycling bins.",
              ],
              distractorNotes: ["Minh nói trước", "Eco U2 topic"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText:
                "After they found a comedy, what did Minh do once?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh stopped the programme because the screen was too dark.",
              correct: "He stopped the programme because the screen was too dark.",
              wrong: [
                "He changed the channel to watch the news.",
                "He went to the national parade.",
              ],
              distractorNotes: ["Linh wanted news change earlier", "Unit 3"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-missing-check",
          title: "Check: Missing Sentence Challenge",
          instructions: "Read carefully. Pick the best missing sentence.",
          sortOrder: 2,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText:
                'Complete: Minh and Linh cannot agree on a _____.',
              skillTag: "reading",
              topicTag,
              explanation: "Programme — họ không đồng ý chương trình xem.",
              correct: "programme",
              wrong: ["parade", "experiment"],
              distractorNotes: ["Festival U3", "Science U5"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText:
                'Best missing line after "They changed the channel":',
              skillTag: "reading",
              topicTag,
              explanation: "Found a comedy with a famous actor — đoạn cuối bài.",
              correct: "and found a comedy with a famous actor.",
              wrong: [
                "and watched fireworks by the lake.",
                "and cleaned the house before Tet.",
              ],
              distractorNotes: ["Festival U3", "Tet custom U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText:
                'Linh thinks comedies are her _____ programmes.',
              skillTag: "reading",
              topicTag,
              explanation: "Favourite — comedies are my favourite programmes.",
              correct: "favourite",
              wrong: ["boring", "national"],
              distractorNotes: ["Opposite opinion", "Festival adjective"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-missing-apply",
          title: "Apply: Complete Conversation Gaps",
          instructions: "Fill in the best words from the conversation.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                'Complete: "The news is too [0]!" | "I enjoy watching [1]." | "Comedies are my [2] programmes."',
              skillTag: "reading",
              topicTag,
              explanation: "boring; documentaries; favourite — từ trong hội thoại.",
              template:
                '"The news is too [0]!" "I enjoy watching [1]." "Comedies are my [2] programmes."',
              correctAnswers: ["boring", "documentaries", "favourite"],
              acceptableAnswers: [
                ["boring", "Boring"],
                ["documentaries", "Documentaries", "documentary"],
                ["favourite", "Favourite", "favorite"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-missing-review",
          title: "Review: Missing Sentences Mix",
          instructions: "Read the passage. Mixed review of conversation completion.",
          sortOrder: 4,
          passage,
          difficulty: 0.3,
          questions: [
            buildMcq({
              questionText:
                'Minh: "Let\'s watch the news." Best response from Linh:',
              skillTag: "reading",
              topicTag,
              explanation: "News too boring, wants cartoon — phản ứng trong bài.",
              correct: "The news is too boring! I want to see a cartoon.",
              wrong: [
                "The audience clapped loudly at the parade.",
                "We celebrate Tet with our family.",
              ],
              distractorNotes: ["Parade context", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "At the end, both friends _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Enjoyed watching together — câu kết bài.",
              correct: "enjoyed watching together",
              wrong: ["went to the national parade", "recycled plastic waste"],
              distractorNotes: ["Festival U3", "Eco U2"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-media-conversation",
      title: "Lesson 2: Media Conversation Details",
      learningObjective:
        "Understand details in conversations about choosing TV programmes.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-convo-learn",
          title: "Learn: Who Says What?",
          instructions: "Read the passage. Who says each line?",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "Who says: \"I enjoy watching documentaries\"?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh — anh thích xem phim tài liệu.",
              correct: "Minh",
              wrong: ["Linh", "Dad"],
              distractorNotes: ["Linh prefers cartoons/comedy", "Dad not in text"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Who says: \"Comedies are my favourite programmes\"?",
              skillTag: "reading",
              topicTag,
              explanation: "Linh — phim hài là yêu thích của Linh.",
              correct: "Linh",
              wrong: ["Minh", "Grandma"],
              distractorNotes: ["Minh prefers documentaries", "Grandma not in text"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-convo-practice",
          title: "Practice: Programme Choices",
          instructions: "Read again. Choose the correct statement.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "What channel does Minh suggest for the news?",
              skillTag: "reading",
              topicTag,
              explanation: "Channel three — kênh ba.",
              correct: "Channel three",
              wrong: ["Channel seven", "The cinema channel"],
              distractorNotes: ["Programme at seven, not channel", "Not in text"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Why does Linh say the screen is too small?",
              skillTag: "reading",
              topicTag,
              explanation: "When talking about documentaries — màn hình nhỏ cho tài liệu.",
              correct: "For watching documentaries properly",
              wrong: ["For the national parade", "For recycling videos"],
              distractorNotes: ["Festival U3", "Eco U2"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-convo-check",
          title: "Check: Conversation Details",
          instructions: "Find the answers in the text.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "What type of scene does Linh mention in the comedy?",
              skillTag: "reading",
              topicTag,
              explanation: "Exciting scene on a ship — cảnh trên tàu.",
              correct: "A scene on a ship",
              wrong: ["Fireworks at the lake", "A dance on stage"],
              distractorNotes: ["Festival U3", "School festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What did the audience at school say about the comedy?",
              skillTag: "reading",
              topicTag,
              explanation: "It was interesting — thú vị.",
              correct: "It was interesting",
              wrong: ["It was too boring", "It was a Tet custom"],
              distractorNotes: ["Minh said last week boring", "Festival custom"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Why does Minh agree to watch the comedy?",
              skillTag: "reading",
              topicTag,
              explanation: "Only if the actor is funny enough — diễn viên đủ hài.",
              correct: "If the actor is funny enough",
              wrong: ["Because he loves the news", "Because of fireworks"],
              distractorNotes: ["Minh finds news OK but Linh bored", "Fireworks U3"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-convo-apply",
          title: "Apply: Match Speaker to Opinion",
          instructions: "Match each speaker to their opinion.",
          exerciseType: "matching",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildMatching({
              questionText: "Match each person to their media opinion.",
              skillTag: "reading",
              topicTag,
              explanation: "Minh: documentaries; Linh: cartoons/comedy; both: enjoy together.",
              pairs: [
                { left: "Minh", right: "enjoys watching documentaries" },
                { left: "Linh", right: "thinks the news is too boring" },
                { left: "Linh", right: "favourite programmes are comedies" },
                { left: "Both friends", right: "enjoyed watching together in the end" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-convo-review",
          title: "Review: Conversation Mix",
          instructions: "Read and answer about the conversation.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "When do Minh and Linh usually watch television?",
              skillTag: "reading",
              topicTag,
              explanation: "After homework — câu mở đầu.",
              correct: "After homework",
              wrong: ["During the national parade", "At the cinema only"],
              distractorNotes: ["Festival U3", "Cinema is different place"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Which programme do they watch in the end?",
              skillTag: "reading",
              topicTag,
              explanation: "A comedy with a famous actor — phim hài.",
              correct: "A comedy with a famous actor",
              wrong: ["The news on channel three", "Only a documentary"],
              distractorNotes: ["Minh's first suggestion", "Minh's preference not final"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "reading-opinion-inference",
      title: "Lesson 3: Opinions and Inference in Conversations",
      learningObjective:
        "Infer opinions and attitudes from the TV conversation text.",
      estimatedMinutes: 20,
      exercises: [
        buildReadingExercise({
          slug: "reading-opinion-learn",
          title: "Learn: Opinion Words in the Text",
          instructions: "Read the passage. Find opinion words.",
          sortOrder: 0,
          passage,
          questions: [
            buildMcq({
              questionText: "How does Linh describe the news?",
              skillTag: "reading",
              topicTag,
              explanation: "Too boring — quá nhàm chán.",
              correct: "Too boring",
              wrong: ["Very exciting", "Interesting enough"],
              distractorNotes: ["Opposite", "She uses interesting for documentary"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "How does Linh describe the scene on the ship?",
              skillTag: "reading",
              topicTag,
              explanation: "Exciting — hấp dẫn.",
              correct: "Exciting",
              wrong: ["Too boring", "Too small"],
              distractorNotes: ["News opinion", "Screen problem"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-opinion-practice",
          title: "Practice: Infer Attitudes",
          instructions: "Read again. Choose the best inference.",
          sortOrder: 1,
          passage,
          difficulty: 0.28,
          questions: [
            buildMcq({
              questionText: "Why does Minh think cartoons are for little children?",
              skillTag: "reading",
              topicTag,
              explanation: "He prefers documentaries — suy luận từ sở thích.",
              correct: "He prefers more serious programmes like documentaries",
              wrong: ["He never watches television", "He hates Linh"],
              distractorNotes: ["He watches TV after homework", "They are friends"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We can infer that Minh and Linh _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Compromise and enjoy together — thỏa hiệp xem comedy.",
              correct: "can compromise and enjoy watching together",
              wrong: ["never agree on anything", "only watch the news"],
              distractorNotes: ["They agree in end", "They choose comedy not news"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-opinion-check",
          title: "Check: Opinion and Inference",
          instructions: "Think carefully about attitudes in the text.",
          sortOrder: 2,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Which detail is NOT in the text?",
              skillTag: "reading",
              topicTag,
              explanation: "Text never mentions radio — không có radio.",
              correct: "Minh listens to the radio in the kitchen.",
              wrong: [
                "Linh wants to see a cartoon.",
                "The screen was too dark once.",
              ],
              distractorNotes: ["True in text", "True in text"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Minh says last week's comedy was _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Boring — nhàm chán.",
              correct: "boring",
              wrong: ["exciting", "favourite"],
              distractorNotes: ["This week's is exciting", "Comedy is Linh's favourite type"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The film was exciting enough for Linh to _____.",
              skillTag: "reading",
              topicTag,
              explanation: "Continue watching — tiếp tục xem sau khi screen too dark.",
              correct: "keep watching after Minh fixed the screen",
              wrong: ["change to the news", "go to the parade"],
              distractorNotes: ["They watch comedy not news", "Parade U3"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "reading-opinion-apply",
          title: "Apply: Complete Opinion Sentences",
          instructions: "Fill in using words from the conversation.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          content: { passage },
          questions: [
            buildGapFill({
              questionText:
                "Complete: The news is too [0]. | The screen is too [1]. | The film was [2] enough.",
              skillTag: "reading",
              topicTag,
              explanation: "boring; dark/small; exciting — ý kiến trong bài.",
              template:
                "The news is too [0]. The screen is too [1]. The film was [2] enough.",
              correctAnswers: ["boring", "dark", "exciting"],
              acceptableAnswers: [
                ["boring", "Boring"],
                ["dark", "Dark", "small", "Small"],
                ["exciting", "Exciting", "interesting", "Interesting"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-opinion-review",
          title: "Review: Opinion and Inference Mix",
          instructions: "Read and answer about opinions.",
          sortOrder: 4,
          passage,
          difficulty: 0.32,
          questions: [
            buildMcq({
              questionText: "Which sentence best summarises the conversation?",
              skillTag: "reading",
              topicTag,
              explanation: "Friends disagree then choose comedy — tóm tắt toàn bài.",
              correct:
                "Minh and Linh disagree about programmes but enjoy watching a comedy together.",
              wrong: [
                "Minh and Linh only watch the news on channel three.",
                "Minh and Linh went to a Tet parade with fireworks.",
              ],
              distractorNotes: ["News was rejected", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "How old is Minh?",
              skillTag: "reading",
              topicTag,
              explanation: "Minh is eleven — câu mở đầu.",
              correct: "Eleven",
              wrong: ["Nine", "Thirteen"],
              distractorNotes: ["Movers age", "Not in text"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
