/** Flyers U4 — speaking lessons (3 × 5 exercises; only Check is AI). */

export function speakingLessons({
  buildMcq,
  buildExercise,
  speakingChecks,
  topicTag,
}) {
  const [tvCheck, filmCheck, opinionCheck] = speakingChecks;

  return [
    {
      slug: "speaking-tv-programmes",
      title: "Lesson 1: Talk About TV Programmes",
      learningObjective:
        "Choose appropriate spoken phrases about television programmes.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-tv-learn",
          title: "Learn: What to Say About TV",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Someone asks: What do you enjoy watching? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Enjoy watching + programme type — trả lời đầy đủ.",
              correct:
                "I enjoy watching documentaries on television, but my friend Linh prefers cartoons.",
              wrong: [
                "Enjoy watch television programme documentary.",
                "I enjoy to watch news boring channel.",
              ],
              distractorNotes: ["Fragment", "Enjoy to (×)"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best answer: Why don't you watch the news?",
              skillTag: "speaking",
              topicTag,
              explanation: "Too boring — lý do rõ ràng.",
              correct: "Because the news is too boring. I want to see a comedy instead.",
              wrong: ["Because news channel programme.", "News is enjoy enough too."],
              distractorNotes: ["Fragment", "Grammar wrong"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-tv-practice",
          title: "Practice: TV Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Friend asks: Which channel is the news on? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Channel three — câu hoàn chỉnh.",
              correct: "The news is on channel three every evening.",
              wrong: ["Channel news three programme.", "On channel boring news too."],
              distractorNotes: ["Fragment", "Fragment"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What do you say when the screen is too dark?",
              skillTag: "speaking",
              topicTag,
              explanation: "Stop programme / screen too dark — từ bài đọc.",
              correct: "Can we stop? The screen is too dark to watch the film.",
              wrong: ["Screen dark film stop enough.", "The parade is too boring."],
              distractorNotes: ["Fragment", "Festival U3"],
              difficultyRating: 2,
            }),
          ],
        }),
        tvCheck,
        buildExercise({
          slug: "speaking-tv-apply",
          title: "Apply: Best TV Response",
          instructions: "Choose the best spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Teacher asks: What are comedies? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Funny programmes + favourite — định nghĩa và ý kiến.",
              correct:
                "Comedies are funny programmes that make the audience laugh. They are my favourite.",
              wrong: ["Comedy funny programme audience laugh favourite.", "Comedies is too boring."],
              distractorNotes: ["Fragment", "Opposite of favourite"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best way to suggest watching together:",
              skillTag: "speaking",
              topicTag,
              explanation: "Let's watch + enjoy — lời mời tự nhiên.",
              correct: "Let's watch a comedy on television. I think we'll enjoy it together.",
              wrong: ["Watch comedy television enjoy together let's.", "Let's parade fireworks festival."],
              distractorNotes: ["Word order wrong", "Festival U3"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-tv-review",
          title: "Review: TV Speaking Mix",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best answer: Do you listen to the radio?",
              skillTag: "speaking",
              topicTag,
              explanation: "Grandma listens to radio — câu hoàn chỉnh.",
              correct: "My grandma listens to the radio in the kitchen while we watch television.",
              wrong: ["Grandma radio kitchen television.", "Radio is too boring enough."],
              distractorNotes: ["Fragment", "Grammar wrong"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best answer: What is your favourite programme?",
              skillTag: "speaking",
              topicTag,
              explanation: "Favourite + reason — trả lời đầy đủ.",
              correct:
                "My favourite programme is a comedy with a famous actor. It is never too boring.",
              wrong: ["Favourite programme comedy actor boring.", "I enjoy to watch favourite enough."],
              distractorNotes: ["Fragment", "Enjoy to (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-films",
      title: "Lesson 2: Talk About Films",
      learningObjective:
        "Choose spoken phrases about films, actors and scenes.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-film-learn",
          title: "Learn: What to Say About Films",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Someone asks: Do you want to see the new film? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes + want to see + big screen — trả lời đầy đủ.",
              correct:
                "Yes! I want to see it at the cinema because the television screen is too small.",
              wrong: ["Yes want see film cinema screen.", "Yes I enjoy to watch film enough."],
              distractorNotes: ["Fragment", "Enjoy to (×)"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best answer: Who is your favourite actor?",
              skillTag: "speaking",
              topicTag,
              explanation: "Actor in comedy + funny enough — câu hoàn chỉnh.",
              correct: "The actor in the new comedy is my favourite. He is funny enough for the whole audience.",
              wrong: ["Actor comedy favourite funny audience.", "Actor is too boring documentary."],
              distractorNotes: ["Fragment", "Wrong programme type"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-film-practice",
          title: "Practice: Film Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Friend asks: What is the best scene? Best answer:",
              skillTag: "speaking",
              topicTag,
              explanation: "Scene on a ship + exciting — từ unit content.",
              correct: "The best scene is on a big ship. It is very exciting!",
              wrong: ["Scene ship exciting best.", "Best scene parade fireworks lake."],
              distractorNotes: ["Fragment", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "What do you say about the audience?",
              skillTag: "speaking",
              topicTag,
              explanation: "Audience clapped loudly — câu hoàn chỉnh.",
              correct: "The audience clapped loudly when the exciting scene finished.",
              wrong: ["Audience clap scene loud.", "Audience is too watch television."],
              distractorNotes: ["Fragment", "Grammar wrong"],
              difficultyRating: 2,
            }),
          ],
        }),
        filmCheck,
        buildExercise({
          slug: "speaking-film-apply",
          title: "Apply: Best Film Response",
          instructions: "Choose the best spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best way to compare documentary and comedy:",
              skillTag: "speaking",
              topicTag,
              explanation: "Documentary interesting + prefer comedy — nuanced opinion.",
              correct:
                "The documentary looks interesting, but I prefer an exciting comedy at the cinema.",
              wrong: ["Documentary interesting comedy prefer cinema.", "Documentary is enjoy to watch."],
              distractorNotes: ["Fragment", "Enjoy to (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best answer: Is the film exciting enough?",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes + reason — adj + enough.",
              correct: "Yes, it is exciting enough for everyone. The audience loved it!",
              wrong: ["Yes exciting enough audience film.", "Yes it is too enough exciting."],
              distractorNotes: ["Fragment", "Too enough (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-film-review",
          title: "Review: Film Speaking Mix",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best answer: Why go to the cinema?",
              skillTag: "speaking",
              topicTag,
              explanation: "Big screen + exciting enough — lý do rõ.",
              correct:
                "Watching at the cinema is much better when the programme is exciting enough for a big audience.",
              wrong: ["Cinema better exciting audience programme.", "Cinema is too boring television."],
              distractorNotes: ["Fragment", "Opposite meaning"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best answer: What video did you share?",
              skillTag: "speaking",
              topicTag,
              explanation: "Funny video + class — từ vocab bank.",
              correct: "I shared a funny video with my class. Everyone thought it was exciting!",
              wrong: ["Video funny class share exciting.", "Video is enough too boring."],
              distractorNotes: ["Fragment", "Grammar wrong"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "speaking-media-opinions",
      title: "Lesson 3: Talk About Media Opinions",
      learningObjective:
        "Give spoken opinions using too, enough and enjoy + -ing.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-opinion-learn",
          title: "Learn: Giving Media Opinions",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Examiner asks: What do you think of the news? You say:",
              skillTag: "speaking",
              topicTag,
              explanation: "Too boring + want comedy — opinion rõ ràng.",
              correct: "I think the news is too boring. I want to watch a comedy instead.",
              wrong: ["News boring think comedy want.", "News is enjoy to watch enough."],
              distractorNotes: ["Fragment", "Enjoy to (×)"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Best answer: Are documentaries interesting enough?",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes + enjoy watching — adj + enough + enjoy.",
              correct: "Yes, they are interesting enough. I enjoy watching them about animals.",
              wrong: ["Yes documentary enough interesting enjoy.", "Yes they is too boring."],
              distractorNotes: ["Fragment", "Grammar wrong"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-opinion-practice",
          title: "Practice: Opinion Replies",
          instructions: "Choose the best reply.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({
              questionText: "Friend says cartoons are boring. Best reply:",
              skillTag: "speaking",
              topicTag,
              explanation: "Disagree politely + favourite — thái độ lịch sự.",
              correct:
                "I don't think so. Cartoons are my favourite programmes and they are never too boring for me.",
              wrong: ["Cartoons favourite not boring think.", "Cartoons is parade fireworks."],
              distractorNotes: ["Fragment", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best answer: Too many programmes tonight?",
              skillTag: "speaking",
              topicTag,
              explanation: "Yes + let's choose comedy — từ listening script.",
              correct: "Yes, there are too many programmes! Let's watch a comedy instead.",
              wrong: ["Too many programme comedy watch.", "Too many parade costume festival."],
              distractorNotes: ["Fragment", "Festival U3"],
              difficultyRating: 2,
            }),
          ],
        }),
        opinionCheck,
        buildExercise({
          slug: "speaking-opinion-apply",
          title: "Apply: Best Opinion Response",
          instructions: "Choose the best spoken response.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          questions: [
            buildMcq({
              questionText: "Best way to describe all three media:",
              skillTag: "speaking",
              topicTag,
              explanation: "TV + radio + cinema — review toàn unit.",
              correct:
                "I enjoy watching television after school. Grandma listens to the radio, and I want to see exciting films at the cinema.",
              wrong: ["Television radio cinema enjoy film exciting.", "I enjoy to watch radio cinema enough."],
              distractorNotes: ["Fragment", "Enjoy to (×)"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best answer: What makes a programme interesting?",
              skillTag: "speaking",
              topicTag,
              explanation: "Good actor + exciting scene — chi tiết cụ thể.",
              correct:
                "A programme is interesting when the actor is good and there is an exciting scene.",
              wrong: ["Programme interesting actor scene exciting.", "Programme is too enough boring."],
              distractorNotes: ["Fragment", "Too enough (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "speaking-opinion-review",
          title: "Review: Media Opinion Speaking Mix",
          instructions: "Choose the best thing to say.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Best summary of Minh and Linh's TV habits:",
              skillTag: "speaking",
              topicTag,
              explanation: "Different tastes + enjoy together — tóm tắt unit.",
              correct:
                "Minh enjoys watching documentaries and Linh loves comedies, but they enjoy watching together in the end.",
              wrong: ["Minh Linh documentary comedy enjoy together.", "Minh Linh parade festival Tet."],
              distractorNotes: ["Fragment", "Festival U3"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Best closing answer in a speaking test:",
              skillTag: "speaking",
              topicTag,
              explanation: "Favourite + exciting enough — kết thúc tự nhiên.",
              correct:
                "My favourite programme is a comedy because it is exciting enough and never too boring.",
              wrong: ["Favourite comedy exciting enough boring.", "Favourite is enjoy to watch programme."],
              distractorNotes: ["Fragment", "Enjoy to (×)"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
