/** Flyers U4 — vocabulary lessons (3 × 5 exercises). */

export function vocabularyLessons({
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  topicTag,
}) {
  return [
    {
      slug: "vocab-tv-programmes",
      title: "Lesson 1: TV and Programmes",
      learningObjective:
        "Recognise and use television, programme, channel, news, radio, watch and screen.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-tv-learn",
          title: "Learn: TV and Programme Words",
          instructions: "Read each clue. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh watches _____ after he finishes homework.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Television (tivi) — xem tivi sau bài tập.",
              correct: "television",
              wrong: ["audience", "actor"],
              distractorNotes: ["People who watch", "Person in a film"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Their favourite _____ starts at seven o'clock.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Programme (chương trình) — chương trình yêu thích.",
              correct: "programme",
              wrong: ["scene", "comedy only"],
              distractorNotes: ["Part of a film", "One type only"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh changed the _____ to watch the news.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Channel (kênh) — đổi kênh truyền hình.",
              correct: "channel",
              wrong: ["screen", "video"],
              distractorNotes: ["The display", "Online clip"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Dad watches the _____ on television every evening.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "News (tin tức) — xem tin tức buổi tối.",
              correct: "news",
              wrong: ["cartoon", "comedy"],
              distractorNotes: ["Animated show", "Funny show"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-tv-practice",
          title: "Practice: Match TV Words",
          instructions: "Match each word to what it means.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match TV and programme words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Mỗi từ chỉ một khái niệm truyền hình cụ thể.",
              pairs: [
                { left: "television", right: "a device or service for watching programmes at home" },
                { left: "programme", right: "a show that is broadcast on TV or radio" },
                { left: "channel", right: "a station you select to watch different programmes" },
                { left: "watch", right: "look at a programme or film for a period of time" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-tv-check",
          title: "Check: TV Vocabulary Quiz",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Grandma listens to the _____ in the kitchen.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Radio (đài phát thanh) — nghe radio trong bếp.",
              correct: "radio",
              wrong: ["screen", "scene"],
              distractorNotes: ["Visual display", "Film part"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Do you want to _____ a film tonight?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Watch (xem) — muốn xem phim tối nay.",
              correct: "watch",
              wrong: ["audience", "boring"],
              distractorNotes: ["Noun for viewers", "Adjective"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The _____ was too small for the whole audience.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Screen (màn hình) — màn hình quá nhỏ.",
              correct: "screen",
              wrong: ["channel", "programme"],
              distractorNotes: ["TV station", "A show"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-tv-apply",
          title: "Apply: Complete TV Sentences",
          instructions: "Fill in each gap with the correct word.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh watches [0] after homework. | Their favourite [1] starts at seven. | Linh changed the [2] to watch the news.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "television; programme; channel — từ TV cơ bản.",
              template:
                "Minh watches [0] after homework. Their favourite [1] starts at seven. Linh changed the [2] to watch the news.",
              correctAnswers: ["television", "programme", "channel"],
              acceptableAnswers: [
                ["television", "Television", "TV"],
                ["programme", "Programme", "program"],
                ["channel", "Channel"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-tv-review",
          title: "Review: TV and Programmes Mix",
          instructions: "Mixed review from this lesson. Choose carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which word means 'a show that is broadcast on TV'?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Programme (chương trình) — chương trình phát sóng.",
              correct: "programme",
              wrong: ["screen", "audience"],
              distractorNotes: ["The display", "The viewers"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Dad watches the news on _____ every evening.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Television (tivi) — xem tin trên tivi.",
              correct: "television",
              wrong: ["actor", "scene"],
              distractorNotes: ["Person in show", "Part of film"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "We can _____ the news or listen to it on the radio.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Watch (xem) — xem tin trên tivi.",
              correct: "watch",
              wrong: ["boring", "favourite"],
              distractorNotes: ["Adjective", "Adjective"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-show-types",
      title: "Lesson 2: Types of Shows",
      learningObjective:
        "Use cartoon, comedy, documentary, film, video, scene and actor.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-shows-learn",
          title: "Learn: Types of Shows",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "Minh enjoys watching _____ on Saturday morning.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Cartoons (phim hoạt hình) — xem hoạt hình sáng thứ Bảy.",
              correct: "cartoons",
              wrong: ["news", "radio"],
              distractorNotes: ["Information show", "Audio only"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The _____ made the whole audience laugh loudly.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Comedy (phim hài) — chương trình hài làm khán giả cười.",
              correct: "comedy",
              wrong: ["documentary", "channel"],
              distractorNotes: ["Factual film", "TV station"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Linh watched an interesting _____ about animals.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Documentary (phim tài liệu) — phim tài liệu về động vật.",
              correct: "documentary",
              wrong: ["cartoon", "screen"],
              distractorNotes: ["Animated show", "Display"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "They want to see a new _____ at the cinema.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Film (phim) — xem phim mới ở rạp.",
              correct: "film",
              wrong: ["programme only", "news only"],
              distractorNotes: ["Broader term", "News is one type"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-shows-practice",
          title: "Practice: Match Show Types",
          instructions: "Match each word to the correct meaning or situation.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match types of shows and media.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Ghép loại chương trình với nghĩa phù hợp.",
              pairs: [
                { left: "cartoon", right: "an animated programme, often for children" },
                { left: "comedy", right: "a funny programme that makes people laugh" },
                { left: "documentary", right: "a factual programme about real events or topics" },
                { left: "film", right: "a story shown at the cinema or on television" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-shows-check",
          title: "Check: Show Types Quiz",
          instructions: "Choose the best answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Minh shared a funny _____ with his class.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Video (video) — chia sẻ video hài với lớp.",
              correct: "video",
              wrong: ["channel", "radio"],
              distractorNotes: ["TV station", "Audio medium"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The best _____ in the film is on a big ship.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Scene (cảnh) — cảnh hay nhất trong phim.",
              correct: "scene",
              wrong: ["programme", "audience"],
              distractorNotes: ["Whole show", "Viewers"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The _____ in the comedy is very famous.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Actor (diễn viên) — diễn viên trong phim hài.",
              correct: "actor",
              wrong: ["screen", "channel"],
              distractorNotes: ["Display", "Station"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-shows-apply",
          title: "Apply: Show Type Sentences",
          instructions: "Complete the sentences about types of shows.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: Minh enjoys [0]. | They want to see a new [1] at the cinema. | The best [2] is on a ship.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "cartoons; film; scene — loại chương trình và phim.",
              template:
                "Minh enjoys [0]. They want to see a new [1] at the cinema. The best [2] is on a ship.",
              correctAnswers: ["cartoons", "film", "scene"],
              acceptableAnswers: [
                ["cartoons", "Cartoons", "cartoon"],
                ["film", "Film"],
                ["scene", "Scene"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-shows-review",
          title: "Review: Show Types Mix",
          instructions: "Mixed review. No hints.",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Which programme type teaches facts about real life?",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Documentary (phim tài liệu) — dạy sự thật về đời thực.",
              correct: "documentary",
              wrong: ["comedy", "cartoon"],
              distractorNotes: ["Funny show", "Animated show"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The whole _____ laughed during the comedy.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Audience (khán giả) — khán giả cười khi xem hài.",
              wrong: ["actor", "channel"],
              correct: "audience",
              distractorNotes: ["Performer", "Station"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Let's watch the news on channel three. (Which word is a TV station?)",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Channel (kênh) — kênh ba là đài truyền hình.",
              correct: "channel",
              wrong: ["scene", "video"],
              distractorNotes: ["Film part", "Online clip"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    {
      slug: "vocab-opinions",
      title: "Lesson 3: Opinions About Media",
      learningObjective:
        "Use audience, enjoy, boring, exciting, favourite and interesting to give opinions.",
      estimatedMinutes: 18,
      exercises: [
        buildExercise({
          slug: "vocab-opinions-learn",
          title: "Learn: Opinion Words",
          instructions: "Choose the word that best completes each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({
              questionText: "The _____ clapped when the film finished.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Audience (khán giả) — khán giả vỗ tay khi phim kết thúc.",
              correct: "audience",
              wrong: ["actor", "channel"],
              distractorNotes: ["Performer on screen", "TV station"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "I _____ watching documentaries about nature.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Enjoy (thích) — enjoy + V-ing: thích xem phim tài liệu.",
              correct: "enjoy",
              wrong: ["boring", "screen"],
              distractorNotes: ["Adjective", "Noun"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "Minh thought the news programme was _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Boring (nhàm chán) — chương trình tin nhàm chán.",
              correct: "boring",
              wrong: ["exciting", "interesting"],
              distractorNotes: ["Opposite positive", "Opposite positive"],
              difficultyRating: 1,
            }),
            buildMcq({
              questionText: "The film had an _____ scene at the end.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Exciting (hấp dẫn) — cảnh hấp dẫn ở cuối phim.",
              correct: "exciting",
              wrong: ["boring", "radio"],
              distractorNotes: ["Opposite", "Audio medium"],
              difficultyRating: 1,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-opinions-practice",
          title: "Practice: Match Opinion Words",
          instructions: "Match each word or phrase to its meaning.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match opinion and media words.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Opinion adjectives và audience/enjoy — từ đánh giá media.",
              pairs: [
                { left: "favourite", right: "the one you like more than any other" },
                { left: "interesting", right: "holding your attention because it is good to learn or watch" },
                { left: "boring", right: "not interesting; making you want to stop watching" },
                { left: "enjoy", right: "get pleasure from doing something" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-opinions-check",
          title: "Check: Opinion Vocabulary Challenge",
          instructions: "No hints — choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          questions: [
            buildMcq({
              questionText: "Cartoons are Linh's _____ programmes.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Favourite (yêu thích nhất) — chương trình yêu thích của Linh.",
              correct: "favourite",
              wrong: ["boring", "audience"],
              distractorNotes: ["Negative opinion", "Viewers"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The documentary about Hanoi was very _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Interesting (thú vị) — phim tài liệu rất thú vị.",
              correct: "interesting",
              wrong: ["boring", "screen"],
              distractorNotes: ["Opposite", "Display noun"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Comedies are my _____ because they are never boring.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Favourite (yêu thích) — phim hài là loại yêu thích.",
              correct: "favourite",
              wrong: ["actor", "video"],
              distractorNotes: ["Person", "Clip type"],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-opinions-apply",
          title: "Apply: Opinion Sentences",
          instructions: "Fill in with opinion words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          questions: [
            buildGapFill({
              questionText:
                "Complete: I [0] watching cartoons. | The news is too [1]. | The film was [2] enough for everyone.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "enjoy; boring; exciting — từ đánh giá chương trình.",
              template:
                "I [0] watching cartoons. The news is too [1]. The film was [2] enough for everyone.",
              correctAnswers: ["enjoy", "boring", "exciting"],
              acceptableAnswers: [
                ["enjoy", "Enjoy"],
                ["boring", "Boring"],
                ["exciting", "Exciting", "interesting", "Interesting"],
              ],
              difficultyRating: 2,
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-opinions-review",
          title: "Review: Unit Vocabulary Mix",
          instructions: "Choose the best word from the whole unit (all 20 words).",
          exerciseType: "multiple_choice",
          sortOrder: 4,
          questions: [
            buildMcq({
              questionText: "Minh watches _____ on television after homework.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Television (tivi) — xem tivi sau bài tập.",
              correct: "television",
              wrong: ["documentary only", "audience only"],
              distractorNotes: ["One show type", "Viewers not device"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Linh changed the _____ to watch the news.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Channel (kênh) — đổi kênh xem tin.",
              correct: "channel",
              wrong: ["scene", "actor"],
              distractorNotes: ["Film part", "Performer"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "They want to _____ a new film at the cinema.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Watch (xem) — muốn xem phim mới.",
              correct: "watch",
              wrong: ["boring", "favourite"],
              distractorNotes: ["Adjective", "Adjective"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The _____ in the comedy is very famous.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Actor (diễn viên) — diễn viên nổi tiếng.",
              correct: "actor",
              wrong: ["programme", "radio"],
              distractorNotes: ["The show itself", "Audio medium"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "Grandma listens to the _____ in the kitchen.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Radio (đài phát thanh) — nghe radio trong bếp.",
              correct: "radio",
              wrong: ["screen", "video"],
              distractorNotes: ["Visual display", "Online clip"],
              difficultyRating: 2,
            }),
            buildMcq({
              questionText: "The documentary about animals was very _____.",
              skillTag: "vocabulary",
              topicTag,
              explanation: "Interesting (thú vị) — phim tài liệu thú vị.",
              correct: "interesting",
              wrong: ["channel", "television"],
              distractorNotes: ["Station", "Device"],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
  ];
}
