import {
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  buildVocabWord,
  buildGrammarRef,
  buildPassage,
  buildListeningScript,
  buildReadingExercise,
  buildListeningExercise,
  buildWritingCheck,
  buildSpeakingCheck,
} from "../ket-unit-builder.mjs";

const TOPIC = "public-places-and-directions";

function sentenceOrder(questionText, explanation, parts, skillTag = "grammar", difficultyRating = 2) {
  const items = parts.map((text, i) => ({ id: `w${i + 1}`, text }));
  return {
    questionText,
    questionType: "sentence_ordering",
    skillTag,
    difficultyRating,
    points: 2,
    explanation,
    qualityScores: {
      quality: 0.89,
      difficulty: difficultyRating === 3 ? 0.38 : 0.35,
      curriculumAlignment: 0.95,
      needsReview: false,
    },
    content: { items, correctOrder: items.map((x) => x.id) },
  };
}

const vocabularyBank = [
  buildVocabWord({ word: "pedestrian", ipa: "/pəˈdestriən/", partOfSpeech: "noun", vietnameseMeaning: "người đi bộ", exampleSentence: "Pedestrians must use the pavement near the crossing.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "crossing", ipa: "/ˈkrɒsɪŋ/", partOfSpeech: "noun", vietnameseMeaning: "lối qua đường / vạch sang đường", exampleSentence: "Wait at the crossing until the light turns green.", difficulty: 1, topic: TOPIC }),
  buildVocabWord({ word: "monument", ipa: "/ˈmɒnjumənt/", partOfSpeech: "noun", vietnameseMeaning: "đài tưởng niệm", exampleSentence: "The war monument stands in the main square.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "entrance", ipa: "/ˈentrəns/", partOfSpeech: "noun", vietnameseMeaning: "lối vào", exampleSentence: "The museum entrance is on River Street.", difficulty: 1, topic: TOPIC }),
  buildVocabWord({ word: "exit", ipa: "/ˈeksɪt/", partOfSpeech: "noun", vietnameseMeaning: "lối ra", exampleSentence: "Follow the signs to the nearest exit.", difficulty: 1, topic: TOPIC }),
  buildVocabWord({ word: "square", ipa: "/skweə(r)/", partOfSpeech: "noun", vietnameseMeaning: "quảng trường", exampleSentence: "We meet friends in the town square every Saturday.", difficulty: 1, topic: TOPIC }),
  buildVocabWord({ word: "statue", ipa: "/ˈstætʃuː/", partOfSpeech: "noun", vietnameseMeaning: "tượng", exampleSentence: "There is a famous statue in front of the library.", difficulty: 1, topic: TOPIC }),
  buildVocabWord({ word: "landmark", ipa: "/ˈlændmɑːk/", partOfSpeech: "noun", vietnameseMeaning: "địa danh / cột mốc", exampleSentence: "The clock tower is a well-known landmark in our city.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "pavement", ipa: "/ˈpeɪvmənt/", partOfSpeech: "noun", vietnameseMeaning: "vỉa hè", exampleSentence: "Walk on the pavement, not on the road.", difficulty: 1, topic: TOPIC }),
  buildVocabWord({ word: "footbridge", ipa: "/ˈfʊtbrɪdʒ/", partOfSpeech: "noun", vietnameseMeaning: "cầu bộ hành", exampleSentence: "Cross the river on the footbridge near the park.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "roundabout", ipa: "/ˈraʊndəbaʊt/", partOfSpeech: "noun", vietnameseMeaning: "bùng binh", exampleSentence: "Turn left at the roundabout after the monument.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "junction", ipa: "/ˈdʒʌŋkʃn/", partOfSpeech: "noun", vietnameseMeaning: "ngã tư / nút giao", exampleSentence: "The bus stop is at the junction of Oak Road and Hill Street.", difficulty: 2, topic: TOPIC }),
];

const grammarReference = [
  buildGrammarRef({
    structure: "Imperatives and directions",
    explanation: "Use the base verb (without subject) to give clear instructions and directions. Add please to be polite. Use turn, go, walk, cross and follow for routes.",
    examples: [
      "Turn left at the roundabout.",
      "Walk along the pavement to the crossing.",
      "Go through the park and cross the footbridge.",
    ],
    commonMistakes: [
      "You turn left at the crossing (×) → Turn left at the crossing (✓)",
      "Walk to along the square (×) → Walk along the square (✓)",
      "Please crosses at the lights (×) → Please cross at the lights (✓)",
    ],
    topic: TOPIC,
  }),
  buildGrammarRef({
    structure: "Prepositions of movement: through, across, along",
    explanation: "Use through for movement inside a space, across for from one side to another, and along for following a line or path.",
    examples: [
      "Walk through the park to reach the square.",
      "Go across the footbridge over the river.",
      "Follow the path along the river to the monument.",
    ],
    commonMistakes: [
      "Walk across the park tunnel (×) → Walk through the park tunnel (✓)",
      "Go along the road to the other side (×) → Go across the road to the other side (✓)",
      "Walk through the pavement line (×) → Walk along the pavement (✓)",
    ],
    topic: TOPIC,
  }),
];

const museumSignPassage = buildPassage({
  title: "City Museum — Visitor Information",
  text: "WELCOME TO RIVERSIDE CITY MUSEUM\n\nENTRANCE: Main door on River Street (near the statue).\nEXIT: Side door to the square — for pedestrians only.\n\nVISITOR ROUTE\n1. Enter through the main entrance.\n2. Walk along the gallery to the monument room.\n3. Cross the footbridge display area to the exit.\n\nSAFETY\n• Do not run on the pavement outside.\n• Use the marked crossing on River Street.\n• The nearest landmark for taxis is the clock tower at the junction.\n\nOPEN: Tuesday–Sunday, 9 a.m. – 5 p.m.\nClosed Mondays.\n\nQuestions? Ask at the information desk by the entrance.",
  imagePrompt: "A printed museum information sign with entrance and exit arrows, a small map and safety icons near a city statue.",
});

const tourScript = buildListeningScript({
  title: "Walking Tour Directions",
  setting: "City square with a tour guide and tourists",
  speakers: [
    { name: "Elena", role: "tour guide" },
    { name: "Tourist", role: "visitor" },
  ],
  lines: [
    { speaker: "Elena", text: "Welcome everyone! We're standing in the main square next to the famous statue." },
    { speaker: "Elena", text: "Please walk along the pavement on your left. Go through the small park." },
    { speaker: "Elena", text: "At the junction, turn right. Cross the footbridge over the river." },
    { speaker: "Tourist", text: "Is the monument on this side of the river?" },
    { speaker: "Elena", text: "Yes. After the bridge, the war monument is straight ahead — it's an important landmark." },
    { speaker: "Elena", text: "We'll use the pedestrian crossing to return. The museum entrance is near the clock tower." },
  ],
  audioNotes: "Clear guide voice outdoors, light background ambience. Approx. 45 seconds.",
});

const stationScript = buildListeningScript({
  title: "Finding the Train Station Exit",
  setting: "Busy train station",
  speakers: [
    { name: "Minh", role: "traveller" },
    { name: "Staff", role: "station worker" },
  ],
  lines: [
    { speaker: "Minh", text: "Excuse me, how do I get to the town square from here?" },
    { speaker: "Staff", text: "Leave through the main exit and turn left." },
    { speaker: "Staff", text: "Walk along Station Road until you see the roundabout." },
    { speaker: "Minh", text: "Do I cross the road at the junction?" },
    { speaker: "Staff", text: "No. Use the pedestrian crossing after the roundabout. Go across the road safely." },
    { speaker: "Staff", text: "Walk through the park gate. The square with the statue is on your right." },
    { speaker: "Minh", text: "Thank you! Is the clock tower a good landmark?" },
    { speaker: "Staff", text: "Yes, you can see it from the square." },
  ],
  audioNotes: "Station announcements softly in background. Approx. 50 seconds.",
});

export default {
  unit: {
    learningObjectives: [
      "Use core public places and directions vocabulary at A2 level.",
      "Use imperatives to give and follow clear directions.",
      "Use through, across and along to describe movement routes.",
      "Read short signs and messages about public places.",
      "Listen to longer extracts and identify route details.",
      "Write short directions to meet at a landmark.",
      "Answer interview questions about places in town.",
    ],
  },
  vocabularyBank,
  grammarReference,
  lessons: {
    vocabulary: {
      slug: "vocab-places-words",
      title: "Lesson 1: Public Places and Directions Words",
      learningObjective: "Recognise and understand twelve public places and directions words at KET A2 level.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "vocab-places-learn",
          title: "Learn: Places Word Match",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({ questionText: "A person walking in the street is a _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Pedestrian (người đi bộ) đi bộ trên vỉa hè hoặc qua đường.", correct: "pedestrian", wrong: ["landmark", "monument"], distractorNotes: ["A famous place", "A memorial structure"] }),
            buildMcq({ questionText: "The safe place where people walk over a road is a _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Crossing (vạch sang đường) là nơi người đi bộ qua đường.", correct: "crossing", wrong: ["roundabout", "junction"], distractorNotes: ["Traffic circle", "Road meeting point"] }),
            buildMcq({ questionText: "A stone figure of a person or animal in a public place is a _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Statue (tượng) là tác phẩm điêu khắc công cộng.", correct: "statue", wrong: ["exit", "pavement"], distractorNotes: ["Way out", "Sidewalk"] }),
            buildMcq({ questionText: "A large open area in the centre of a town is a _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Square (quảng trường) là không gian mở giữa thành phố.", correct: "square", wrong: ["entrance", "footbridge"], distractorNotes: ["Way in", "Bridge for walkers"] }),
            buildMcq({ questionText: "The door you use to go into a building is the _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Entrance (lối vào) là cửa vào.", correct: "entrance", wrong: ["exit", "crossing"], distractorNotes: ["Way out", "Road crossing"] }),
            buildMcq({ questionText: "A well-known building or place that helps you find your way is a _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Landmark (địa danh) giúp định hướng trong thành phố.", correct: "landmark", wrong: ["pedestrian", "pavement"], distractorNotes: ["A person", "Path beside road"] }),
          ],
        }),
        buildExercise({
          slug: "vocab-places-matching",
          title: "Practice: Match the Pairs",
          instructions: "Match each word on the left with the correct meaning on the right.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the places words to their meanings.",
              skillTag: "vocabulary",
              topicTag: TOPIC,
              explanation: "Mỗi từ khớp với một nghĩa rõ ràng. Monument và landmark đều liên quan địa điểm nổi bật.",
              pairs: [
                { left: "monument", right: "a structure built to remember an important person or event" },
                { left: "exit", right: "the way out of a building or area" },
                { left: "pavement", right: "the path at the side of a road for walkers" },
                { left: "footbridge", right: "a bridge for people to walk across" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-places-check",
          title: "Check: Vocab Quiz",
          instructions: "No hints — choose the best answer for each question.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          qualityScores: { quality: 0.91, difficulty: 0.32, curriculumAlignment: 0.96, needsReview: false },
          questions: [
            buildMcq({ questionText: "Drivers go around a circular island in the road at a _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Roundabout (bùng binh) là nút giao hình tròn.", correct: "roundabout", wrong: ["crossing", "statue"], distractorNotes: ["Pedestrian path", "Art object"], difficultyRating: 2 }),
            buildMcq({ questionText: "Two roads meet at a _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Junction (ngã tư) là nơi các đường giao nhau.", correct: "junction", wrong: ["entrance", "square"], distractorNotes: ["Building door", "Open plaza"], difficultyRating: 2 }),
            buildMcq({ questionText: "Please walk on the _____ — do not walk on the road.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Pavement (vỉa hè) dành cho người đi bộ.", correct: "pavement", wrong: ["exit", "monument"], distractorNotes: ["Way out", "Memorial"], difficultyRating: 2 }),
            buildMcq({ questionText: "Tourists took photos of the war _____ in the square.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Monument (đài tưởng niệm) tưởng nhớ sự kiện lịch sử.", correct: "monument", wrong: ["crossing", "pedestrian"], distractorNotes: ["Road feature", "A person"], difficultyRating: 3 }),
            buildMcq({ questionText: "We crossed the river on a narrow _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Footbridge (cầu bộ hành) chỉ dành cho người đi bộ.", correct: "footbridge", wrong: ["landmark", "junction"], distractorNotes: ["Famous place", "Road meeting"], difficultyRating: 3 }),
          ],
        }),
        buildExercise({
          slug: "vocab-places-apply",
          title: "Apply: Words in Sentences",
          instructions: "Complete each sentence with the correct word from the unit.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.36, curriculumAlignment: 0.96, needsReview: false },
          questions: [
            buildGapFill({
              questionText: "Complete: Use the [0] on River Street. | Wait at the [1] for the green light. | Meet me in the town [2].",
              skillTag: "vocabulary",
              topicTag: TOPIC,
              explanation: "entrance (lối vào); crossing (vạch sang đường); square (quảng trường).",
              template: "Use the [0] on River Street. Wait at the [1] for the green light. Meet me in the town [2].",
              correctAnswers: ["entrance", "crossing", "square"],
              acceptableAnswers: [["entrance", "Entrance"], ["crossing", "Crossing"], ["square", "Square"]],
              difficultyRating: 2,
            }),
            buildGapFill({
              questionText: "Complete: The clock tower is a famous [0]. | Walk on the [1], not the road. | Leave by the side [2] to the square.",
              skillTag: "vocabulary",
              topicTag: TOPIC,
              explanation: "landmark (địa danh); pavement (vỉa hè); exit (lối ra).",
              template: "The clock tower is a famous [0]. Walk on the [1], not the road. Leave by the side [2] to the square.",
              correctAnswers: ["landmark", "pavement", "exit"],
              acceptableAnswers: [["landmark", "Landmark"], ["pavement", "Pavement"], ["exit", "Exit"]],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    grammar: {
      slug: "grammar-directions-movement",
      title: "Lesson 2: Directions and Movement",
      learningObjective: "Use imperatives and prepositions through, across and along to give and understand directions.",
      estimatedMinutes: 24,
      exercises: [
        buildExercise({
          slug: "grammar-directions-learn",
          title: "Learn: Imperatives and Prepositions",
          instructions: "Choose the correct word or phrase to complete each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({ questionText: "_____ left at the roundabout.", skillTag: "grammar", topicTag: TOPIC, explanation: "Imperative: Turn left — không cần chủ ngữ.", correct: "Turn", wrong: ["Turning", "Turns"], distractorNotes: ["Gerund form", "Third person"] }),
            buildMcq({ questionText: "Walk _____ the pavement to the crossing.", skillTag: "grammar", topicTag: TOPIC, explanation: "Along + đường đi dài: along the pavement.", correct: "along", wrong: ["through", "across"], distractorNotes: ["Inside a space", "One side to other"] }),
            buildMcq({ questionText: "Go _____ the park to reach the square quickly.", skillTag: "grammar", topicTag: TOPIC, explanation: "Through + không gian bên trong: through the park.", correct: "through", wrong: ["along", "across"], distractorNotes: ["Follow a line", "Over to other side only"] }),
            buildMcq({ questionText: "_____ the footbridge to the other side of the river.", skillTag: "grammar", topicTag: TOPIC, explanation: "Cross / Go across — qua từ bên này sang bên kia.", correct: "Cross", wrong: ["Crosses", "Crossing"], distractorNotes: ["Third person", "Gerund/noun form"] }),
            buildMcq({ questionText: "Pedestrians should use the crossing to go _____ the road.", skillTag: "grammar", topicTag: TOPIC, explanation: "Across the road — sang phía bên kia đường.", correct: "across", wrong: ["through", "along"], distractorNotes: ["Inside tunnel", "Follow road line"] }),
            buildMcq({ questionText: "_____ straight ahead until you see the statue.", skillTag: "grammar", topicTag: TOPIC, explanation: "Imperative: Walk straight ahead.", correct: "Walk", wrong: ["Walked", "Walking"], distractorNotes: ["Past tense", "Gerund"] }),
          ],
        }),
        buildExercise({
          slug: "grammar-directions-practice",
          title: "Practice: Complete the Grammar",
          instructions: "Fill in each gap with the correct word.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] along the river path. | Go [1] the museum entrance. | [2] at the junction.",
              skillTag: "grammar",
              topicTag: TOPIC,
              explanation: "Walk (imperative); through (inside); Turn (imperative).",
              template: "[0] along the river path. Go [1] the museum entrance. [2] at the junction.",
              correctAnswers: ["Walk", "through", "Turn"],
              acceptableAnswers: [["Walk", "walk"], ["through", "Through"], ["Turn", "turn"]],
            }),
            buildGapFill({
              questionText: "Complete: [0] the footbridge carefully. | Follow the signs to the [1]. | Go [2] the road at the crossing.",
              skillTag: "grammar",
              topicTag: TOPIC,
              explanation: "Cross (imperative); exit (noun); across (movement).",
              template: "[0] the footbridge carefully. Follow the signs to the [1]. Go [2] the road at the crossing.",
              correctAnswers: ["Cross", "exit", "across"],
              acceptableAnswers: [["Cross", "cross"], ["exit", "Exit"], ["across", "Across"]],
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-directions-check",
          title: "Check: Grammar Challenge",
          instructions: "Choose the correct answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          qualityScores: { quality: 0.92, difficulty: 0.38, curriculumAlignment: 0.97, needsReview: false },
          questions: [
            buildMcq({ questionText: "Which instruction is correct for pedestrians at a busy junction?", skillTag: "grammar", topicTag: TOPIC, explanation: "Please cross at the pedestrian crossing — mệnh lệnh lịch sự.", correct: "Please cross at the pedestrian crossing.", wrong: ["Please crossing at the pedestrian crossing.", "Please crosses at the pedestrian crossing."], distractorNotes: ["Gerund wrong", "Third person wrong"], difficultyRating: 2 }),
            buildMcq({ questionText: "The guide said: 'Walk _____ the gallery to the monument room.'", skillTag: "grammar", topicTag: TOPIC, explanation: "Along the gallery — đi theo hành lang.", correct: "along", wrong: ["through", "across"], distractorNotes: ["Inside whole building", "Side to side only"], difficultyRating: 2 }),
            buildMcq({ questionText: "To leave the station, you must go _____ the ticket hall to the main exit.", skillTag: "grammar", topicTag: TOPIC, explanation: "Through the ticket hall — đi xuyên qua không gian bên trong.", correct: "through", wrong: ["along", "across"], distractorNotes: ["Follow edge only", "One step over"], difficultyRating: 3 }),
            buildMcq({ questionText: "Which sentence gives a clear direction?", skillTag: "grammar", topicTag: TOPIC, explanation: "Turn right at the landmark — cấu trúc mệnh lệnh rõ ràng.", correct: "Turn right at the landmark near the square.", wrong: ["Turning right at the landmark near the square.", "You turning right at the landmark near the square."], distractorNotes: ["Not imperative", "Ungrammatical"], difficultyRating: 3 }),
          ],
        }),
        buildExercise({
          slug: "grammar-directions-order",
          title: "Apply: Build the Sentence",
          instructions: "Put the words in the correct order to make a sentence.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.4, curriculumAlignment: 0.96, needsReview: false },
          questions: [
            sentenceOrder("Make a sentence: Walk / along / the pavement / to / the crossing.", "Walk along the pavement to the crossing. — imperative + along.", ["Walk", "along", "the pavement", "to", "the crossing."]),
            sentenceOrder("Make a sentence: Go / through / the park / and / cross / the footbridge.", "Go through the park and cross the footbridge. — through + across route.", ["Go", "through", "the park", "and", "cross", "the footbridge."], "grammar", 2),
            sentenceOrder("Make a sentence: Turn / left / at / the roundabout / after / the monument.", "Turn left at the roundabout after the monument. — direction sequence.", ["Turn", "left", "at", "the roundabout", "after", "the monument."], "grammar", 3),
          ],
        }),
      ],
    },
    reading: {
      slug: "reading-museum-sign",
      title: "Lesson 3: Museum Visitor Sign",
      learningObjective: "Read a short public sign and understand directions, details and vocabulary in context.",
      estimatedMinutes: 23,
      exercises: [
        buildReadingExercise({
          slug: "reading-sign-learn",
          title: "Learn: Read the Museum Sign",
          instructions: "Read the sign carefully. Answer the detail questions.",
          sortOrder: 0,
          passage: museumSignPassage,
          questions: [
            buildMcq({ questionText: "Where is the main entrance?", skillTag: "reading", topicTag: TOPIC, explanation: "Main door on River Street near the statue.", correct: "On River Street near the statue", wrong: ["In the square by the exit", "At the junction by the clock tower"], distractorNotes: ["Exit is side door", "Landmark for taxis, not entrance"], assessmentType: "detail" }),
            buildMcq({ questionText: "Who may use the side exit to the square?", skillTag: "reading", topicTag: TOPIC, explanation: "Side door to the square — for pedestrians only.", correct: "Pedestrians only", wrong: ["Buses and taxis", "Museum staff only"], distractorNotes: ["Not stated", "Not restricted to staff"], assessmentType: "detail" }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-sign-practice",
          title: "Practice: Words in the Sign",
          instructions: "Read the sign again. Answer about vocabulary and meaning.",
          sortOrder: 1,
          passage: museumSignPassage,
          difficulty: 0.3,
          questions: [
            buildMcq({ questionText: "In step 3 of the visitor route, visitors _____ the footbridge display area.", skillTag: "reading", topicTag: TOPIC, explanation: "Cross the footbridge display area — đi qua khu trưng bày cầu.", correct: "cross", wrong: ["argue", "congratulate"], distractorNotes: ["Not in text", "Not in text"], difficultyRating: 2, assessmentType: "vocabulary_in_context" }),
            buildMcq({ questionText: "Why does the sign mention the clock tower?", skillTag: "reading", topicTag: TOPIC, explanation: "Nearest landmark for taxis at the junction.", correct: "It is a landmark for finding taxis", wrong: ["It is the museum exit", "It is closed on Mondays"], distractorNotes: ["Exit is side door", "Monday closure is museum rule"], difficultyRating: 2, assessmentType: "inference" }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-sign-check",
          title: "Check: Main Idea and Order",
          instructions: "Read the sign one more time. These questions need careful thinking.",
          sortOrder: 2,
          passage: museumSignPassage,
          difficulty: 0.35,
          questions: [
            buildMcq({ questionText: "What is the main purpose of this sign?", skillTag: "reading", topicTag: TOPIC, explanation: "Welcome + entrance/exit + route + safety for visitors.", correct: "To guide visitors around the museum safely", wrong: ["To sell tickets for the town square", "To advertise a new statue"], distractorNotes: ["Not selling", "Statue is location marker"], assessmentType: "main_idea" }),
            buildMcq({ questionText: "Put the visitor route steps in order: (1) Monument room (2) Main entrance (3) Exit area", skillTag: "reading", topicTag: TOPIC, explanation: "Enter → gallery/monument → cross to exit.", correct: "2 → 1 → 3", wrong: ["1 → 2 → 3", "3 → 2 → 1"], distractorNotes: ["Enter first", "Exit before enter"], difficultyRating: 2, assessmentType: "sequencing" }),
          ],
        }),
        buildExercise({
          slug: "reading-sign-apply",
          title: "Apply: Match Facts from the Sign",
          instructions: "Use what you read. Match each item to the correct fact.",
          exerciseType: "matching",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.32, curriculumAlignment: 0.95, needsReview: false },
          content: { passage: museumSignPassage },
          questions: [
            buildMatching({
              questionText: "Match each topic to a fact from the sign.",
              skillTag: "reading",
              topicTag: TOPIC,
              explanation: "Mỗi mục khớp với thông tin cụ thể trên bảng hướng dẫn bảo tàng.",
              pairs: [
                { left: "Entrance location", right: "River Street near the statue" },
                { left: "Safety outside", right: "Use the marked crossing" },
                { left: "Opening days", right: "Tuesday to Sunday" },
                { left: "Help desk", right: "By the entrance" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    listening: {
      slug: "listening-directions-tour",
      title: "Lesson 4: Tours and Station Directions",
      learningObjective: "Listen to longer extracts about routes and identify landmarks, directions and movement details.",
      estimatedMinutes: 22,
      exercises: [
        buildListeningExercise({
          slug: "listening-tour-learn",
          title: "Learn: Walking Tour",
          instructions: "Listen to the tour guide. Answer the first two questions.",
          sortOrder: 0,
          script: tourScript,
          answerKey: { q1: "main square by statue", q2: "walk along pavement through park" },
          questions: [
            buildMcq({ questionText: "Where does the tour start?", skillTag: "listening", topicTag: TOPIC, explanation: "Standing in the main square next to the famous statue.", correct: "In the main square by the statue", wrong: ["At the train station exit", "Inside the museum entrance"], distractorNotes: ["Different script", "Not the tour start"] }),
            buildMcq({ questionText: "What is the first direction Elena gives?", skillTag: "listening", topicTag: TOPIC, explanation: "Walk along the pavement on your left.", correct: "Walk along the pavement on the left", wrong: ["Cross the footbridge immediately", "Turn right at the roundabout"], distractorNotes: ["Comes later", "Not first instruction"], }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-tour-practice",
          title: "Practice: More from the Walking Tour",
          instructions: "Listen again to the same tour. Answer the next questions.",
          sortOrder: 1,
          script: tourScript,
          answerKey: { q1: "turn right at junction", q2: "monument after bridge" },
          questions: [
            buildMcq({ questionText: "What do tourists do at the junction?", skillTag: "listening", topicTag: TOPIC, explanation: "At the junction, turn right.", correct: "Turn right", wrong: ["Turn left", "Wait at a crossing"], distractorNotes: ["Opposite direction", "Not at junction"], difficultyRating: 2 }),
            buildMcq({ questionText: "What landmark is straight ahead after the footbridge?", skillTag: "listening", topicTag: TOPIC, explanation: "The war monument is straight ahead.", correct: "The war monument", wrong: ["The clock tower", "The museum entrance"], distractorNotes: ["Mentioned later for museum", "Mentioned at end, not after bridge"], difficultyRating: 2 }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-station-check",
          title: "Check: Station to Square Directions",
          instructions: "Listen to a new conversation. Choose the correct answer.",
          sortOrder: 2,
          script: stationScript,
          answerKey: { q1: "town square", q2: "use crossing after roundabout", q3: "clock tower from square" },
          difficulty: 0.32,
          questions: [
            buildMcq({ questionText: "Where does Minh want to go?", skillTag: "listening", topicTag: TOPIC, explanation: "How do I get to the town square?", correct: "The town square", wrong: ["The museum monument room", "The nearest exit only"], distractorNotes: ["Not mentioned", "Exit is step, not destination"] }),
            buildMcq({ questionText: "How should Minh cross the road at the junction?", skillTag: "listening", topicTag: TOPIC, explanation: "Use the pedestrian crossing after the roundabout.", correct: "Use the pedestrian crossing after the roundabout", wrong: ["Cross directly at the junction", "Go through the station again"], distractorNotes: ["Staff says no", "Wrong direction"], difficultyRating: 2 }),
            buildMcq({ questionText: "Which landmark can Minh see from the square?", skillTag: "listening", topicTag: TOPIC, explanation: "Yes, you can see the clock tower from the square.", correct: "The clock tower", wrong: ["The footbridge", "The war monument"], distractorNotes: ["On the route, not visible from square", "From tour script"], difficultyRating: 2 }),
          ],
        }),
        buildExercise({
          slug: "listening-tour-apply",
          title: "Apply: Match What You Heard",
          instructions: "Listen again to the walking tour. Match each item to the correct detail.",
          exerciseType: "matching",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.3, curriculumAlignment: 0.95, needsReview: false },
          content: { script: tourScript },
          questions: [
            buildMatching({
              questionText: "Match each item from the walking tour.",
              skillTag: "listening",
              topicTag: TOPIC,
              explanation: "Mỗi mục khớp với hướng dẫn Elena đưa ra trong tour.",
              pairs: [
                { left: "First movement", right: "Walk along the pavement" },
                { left: "Through the park", right: "Go through the small park" },
                { left: "After the bridge", right: "War monument straight ahead" },
              ],
              difficultyRating: 2,
              points: 3,
            }),
          ],
        }),
      ],
    },
    writing: {
      slug: "writing-directions-message",
      title: "Lesson 5: Write Directions",
      learningObjective: "Write short directions to meet at a landmark using imperatives and movement prepositions.",
      estimatedMinutes: 25,
      exercises: [
        buildExercise({
          slug: "writing-directions-learn",
          title: "Learn: Direction Phrases",
          instructions: "Complete each gap with a word from the unit.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: [0] left at the roundabout. | Walk [1] the pavement to the [2]. | [3] the footbridge to the square.",
              skillTag: "writing",
              topicTag: TOPIC,
              explanation: "Turn (imperative); along (preposition); crossing (noun); Cross (imperative).",
              template: "[0] left at the roundabout. Walk [1] the pavement to the [2]. [3] the footbridge to the square.",
              correctAnswers: ["Turn", "along", "crossing", "Cross"],
              acceptableAnswers: [["Turn", "turn"], ["along", "Along"], ["crossing", "Crossing"], ["Cross", "cross"]],
            }),
          ],
        }),
        buildExercise({
          slug: "writing-directions-order-practice",
          title: "Practice: Build Direction Sentences",
          instructions: "Put the words in the correct order to make correct direction sentences.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            sentenceOrder("Make a sentence: Go / through / the park / to / the monument.", "Go through the park to the monument. — through + destination.", ["Go", "through", "the park", "to", "the monument."], "writing", 2),
            sentenceOrder("Make a sentence: Walk / along / River Street / to / the museum / entrance.", "Walk along River Street to the museum entrance. — along + route.", ["Walk", "along", "River Street", "to", "the museum", "entrance."], "writing", 2),
          ],
        }),
        buildWritingCheck({
          slug: "writing-directions-check",
          topicTag: TOPIC,
          title: "Check: Directions to a Landmark",
          instructions: "Write short directions. Write at least 25 words.",
          sortOrder: 2,
          taskDescription: "Your friend wants to meet you at the clock tower landmark in the town square on Saturday. Write a short message with directions from the train station exit.",
          prompts: [
            "Say where to start (train station exit).",
            "Use at least two imperatives (e.g. turn, walk, cross).",
            "Use through, across or along at least once.",
            "Mention a landmark or public place from the unit.",
          ],
          minWords: 25,
          modelAnswerText: "Hi Sam,\n\nLeave the station exit and turn left. Walk along Station Road to the roundabout. Go across the road at the pedestrian crossing. Walk through the park gate. The square with the statue is on your right. The clock tower landmark is straight ahead.\n\nSee you,\nMinh",
          rubric: {
            grammar: { weight: 0.25, criteria: "Uses imperatives and through/across/along correctly." },
            vocabulary: { weight: 0.25, criteria: "Uses places words (square, crossing, landmark, entrance) appropriately." },
            organization: { weight: 0.25, criteria: "Directions are in a clear step-by-step order with greeting and closing." },
            taskAchievement: { weight: 0.25, criteria: "Route from station to landmark is clear; at least 25 words." },
          },
          successCriteria: [
            "At least 25 words",
            "Clear route from station to meeting place",
            "At least two imperatives",
            "Uses through, across or along",
            "Mentions a unit vocabulary place word",
          ],
          autoCheckKeywords: ["turn", "walk", "cross", "along", "through", "across", "square", "station", "crossing", "landmark", "entrance", "exit"],
        }),
        buildExercise({
          slug: "writing-directions-apply",
          title: "Apply: Complete the Direction Frames",
          instructions: "Complete the direction frames with the correct unit words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.34, curriculumAlignment: 0.95, needsReview: false },
          questions: [
            buildGapFill({
              questionText: "Complete: [0] the main entrance on River Street. | Walk [1] the gallery to the monument. | Use the side [2] to reach the square.",
              skillTag: "writing",
              topicTag: TOPIC,
              explanation: "Enter/Use (imperative context); along (path); exit (way out).",
              template: "[0] the main entrance on River Street. Walk [1] the gallery to the monument. Use the side [2] to reach the square.",
              correctAnswers: ["Use", "along", "exit"],
              acceptableAnswers: [["Use", "Enter", "use", "enter"], ["along", "Along"], ["exit", "Exit"]],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    speaking: {
      slug: "speaking-places-interview",
      title: "Lesson 6: Talk About Places in Town",
      learningObjective: "Answer interview questions about public places and giving directions using unit vocabulary and grammar.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-places-learn",
          title: "Learn: Choose the Best Reply",
          instructions: "Imagine an examiner asks you a question. Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({ questionText: "Examiner: Is there a famous landmark in your town? You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Landmark + vị trí — câu trả lời mô tả địa danh.", correct: "Yes, the clock tower in the square is a famous landmark.", wrong: ["Yes, the pedestrian in the square is a famous landmark.", "Yes, I argue at the landmark every day."], distractorNotes: ["Pedestrian is a person", "Wrong verb"] }),
            buildMcq({ questionText: "Examiner: How do pedestrians cross busy roads safely? You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Use the crossing — an toàn cho người đi bộ.", correct: "They use the pedestrian crossing and wait for the green light.", wrong: ["They use the monument and wait for the statue.", "They use the exit and wait for the entrance."], distractorNotes: ["Nonsense", "Wrong places"] }),
            buildMcq({ questionText: "Examiner: Tell me how to get to the museum entrance. You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Imperative + along — chỉ đường đơn giản.", correct: "Walk along the pavement and turn left at the junction.", wrong: ["Walking along the pavement and turns left at the junction.", "Walk along the pavement and turning left at the junction."], distractorNotes: ["Mixed forms", "Gerund wrong"] }),
          ],
        }),
        buildExercise({
          slug: "speaking-places-practice",
          title: "Practice: Best Response",
          instructions: "Choose the best phrase you would say in each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({ questionText: "Examiner: What can you see in the main square? You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Statue + monument — mô tả quảng trường.", correct: "There is a statue and an old monument near the fountain.", wrong: ["There is a crossing and an exit near the pavement only.", "There is a pedestrian and a roundabout inside the museum."], distractorNotes: ["Road features not typical square focus", "Illogical location"], difficultyRating: 2 }),
            buildMcq({ questionText: "Examiner: How do you get to the other side of the river? You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Cross the footbridge — across the river.", correct: "I cross the footbridge near the park.", wrong: ["I through the footbridge along the river.", "I along the footbridge across the monument."], distractorNotes: ["Wrong verb", "Wrong prepositions"], difficultyRating: 2 }),
            buildMcq({ questionText: "Examiner: Give directions to the nearest exit. You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Go through + follow signs — chỉ lối ra.", correct: "Go through the hall and follow the exit signs on your right.", wrong: ["Go across the hall and follow the entrance signs on your left.", "Go along the exit and follow the roundabout on your right."], distractorNotes: ["Exit not entrance", "Nonsense collocation"], difficultyRating: 2 }),
          ],
        }),
        buildSpeakingCheck({
          slug: "speaking-places-interview",
          topicTag: TOPIC,
          title: "Check: Places and Directions Interview",
          instructions: "Answer the examiner's questions about public places and directions. Speak for up to two minutes.",
          sortOrder: 2,
          prompt: "The examiner will ask you about landmarks, public places and how to give directions in your town.",
          pictureDescription: "A city map showing a square with a statue, a footbridge over a river, a pedestrian crossing and a museum entrance.",
          followUpQuestions: [
            "What is a famous landmark in your area?",
            "Where do pedestrians walk in busy streets?",
            "How do you cross the road safely?",
            "Is there a monument or statue near your home?",
            "How do you get from the station to the town square?",
            "Tell me how to find the museum entrance.",
          ],
          suggestedAnswers: [
            "The clock tower near the junction is a well-known landmark.",
            "They walk on the pavement, not on the road.",
            "I use the pedestrian crossing and wait for the green light.",
            "Yes, there is a war monument in the main square.",
            "Leave the exit, walk along Station Road and go through the park.",
            "Walk along River Street and the entrance is near the statue.",
          ],
          assessmentCriteria: {
            pronunciation: "Key words (pedestrian, crossing, landmark, entrance, footbridge) are understandable.",
            fluency: "Responds with phrases or short sentences without long silences.",
            grammar: "Uses imperatives or through/across/along in at least two answers.",
            vocabulary: "Uses at least four different unit words correctly.",
          },
          maxDurationSeconds: 120,
        }),
        buildExercise({
          slug: "speaking-places-apply",
          title: "Apply: Situational Responses",
          instructions: "Choose the best thing to say in each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.3, curriculumAlignment: 0.95, needsReview: false },
          questions: [
            buildMcq({ questionText: "A tourist asks how to reach the square from the footbridge. You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Walk along + turn — chỉ đường sau cầu.", correct: "Walk along the river path and turn right at the junction.", wrong: ["Walk through the junction and turn along the monument.", "Walk across the statue and turn through the exit."], distractorNotes: ["Wrong prepositions", "Nonsense"], difficultyRating: 2 }),
            buildMcq({ questionText: "Your friend is lost near the roundabout. You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Landmark + imperative — định hướng bằng địa danh.", correct: "Look for the clock tower landmark. Cross at the pedestrian crossing.", wrong: ["Look for the pavement landmark. Cross at the entrance statue.", "Look for the exit landmark. Cross at the monument square."], distractorNotes: ["Pavement not landmark", "Mixed wrong words"], difficultyRating: 2 }),
            buildMcq({ questionText: "The examiner asks: How do tourists leave the museum to the square? You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Side exit for pedestrians — khớp bài đọc.", correct: "They use the side exit for pedestrians to the square.", wrong: ["They use the main entrance for pedestrians to the junction.", "They use the roundabout for pedestrians to the statue."], distractorNotes: ["Entrance is way in", "Roundabout not exit"], difficultyRating: 3 }),
          ],
        }),
      ],
    },
  },
};
