import {
  buildMcq,
  buildMatching,
  buildGapFill,
  buildExercise,
  buildVocabWord,
  buildGrammarRef,
  buildPassage,
  buildListeningScript,
  buildReadingExercise,
  buildListeningExercise,
  buildWritingCheck,
  buildSpeakingCheck,
} from "../ket-unit-builder.mjs";

const TOPIC = "personal-relationships";

function sentenceOrder(questionText, explanation, parts, skillTag = "grammar", difficultyRating = 2) {
  const items = parts.map((text, i) => ({ id: `w${i + 1}`, text }));
  return {
    questionText,
    questionType: "sentence_ordering",
    skillTag,
    difficultyRating,
    points: 2,
    explanation,
    qualityScores: {
      quality: 0.89,
      difficulty: difficultyRating === 3 ? 0.38 : 0.35,
      curriculumAlignment: 0.95,
      needsReview: false,
    },
    content: { items, correctOrder: items.map((x) => x.id) },
  };
}

const vocabularyBank = [
  buildVocabWord({ word: "neighbour", ipa: "/ˈneɪbə(r)/", partOfSpeech: "noun", vietnameseMeaning: "hàng xóm", exampleSentence: "Our neighbour often brings us fruit from her garden.", difficulty: 1, topic: TOPIC }),
  buildVocabWord({ word: "invitation", ipa: "/ˌɪnvɪˈteɪʃn/", partOfSpeech: "noun", vietnameseMeaning: "lời mời", exampleSentence: "I got an invitation to Mai's birthday party.", difficulty: 1, topic: TOPIC }),
  buildVocabWord({ word: "apologise", ipa: "/əˈpɒlədʒaɪz/", partOfSpeech: "verb", vietnameseMeaning: "xin lỗi", exampleSentence: "He called to apologise for being late.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "congratulate", ipa: "/kənˈɡrætʃuleɪt/", partOfSpeech: "verb", vietnameseMeaning: "chúc mừng", exampleSentence: "We congratulated her on her new job.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "relationship", ipa: "/rɪˈleɪʃnʃɪp/", partOfSpeech: "noun", vietnameseMeaning: "mối quan hệ", exampleSentence: "They have a good relationship with their neighbours.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "trust", ipa: "/trʌst/", partOfSpeech: "verb", vietnameseMeaning: "tin tưởng", exampleSentence: "I trust my best friend with my secrets.", difficulty: 1, topic: TOPIC }),
  buildVocabWord({ word: "argue", ipa: "/ˈɑːɡjuː/", partOfSpeech: "verb", vietnameseMeaning: "cãi nhau", exampleSentence: "Brothers sometimes argue about small things.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "forgive", ipa: "/fəˈɡɪv/", partOfSpeech: "verb", vietnameseMeaning: "tha thứ", exampleSentence: "She forgave him after he apologised.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "friendship", ipa: "/ˈfrendʃɪp/", partOfSpeech: "noun", vietnameseMeaning: "tình bạn", exampleSentence: "Their friendship started in primary school.", difficulty: 1, topic: TOPIC }),
  buildVocabWord({ word: "support", ipa: "/səˈpɔːt/", partOfSpeech: "verb", vietnameseMeaning: "hỗ trợ / ủng hộ", exampleSentence: "Good friends support each other in difficult times.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "jealous", ipa: "/ˈdʒeləs/", partOfSpeech: "adjective", vietnameseMeaning: "ghen tị", exampleSentence: "He felt jealous when his friend got a new phone.", difficulty: 2, topic: TOPIC }),
  buildVocabWord({ word: "colleague", ipa: "/ˈkɒliːɡ/", partOfSpeech: "noun", vietnameseMeaning: "đồng nghiệp", exampleSentence: "My mum invited a colleague to dinner.", difficulty: 2, topic: TOPIC }),
];

const grammarReference = [
  buildGrammarRef({
    structure: "Present perfect with experience (ever / never)",
    explanation: "Use present perfect (have/has + past participle) with ever or never to talk about life experiences up to now. Ever goes in questions; never replaces not.",
    examples: [
      "I have never argued with my neighbour.",
      "Have you ever congratulated a friend online?",
      "She has always trusted her best friend.",
    ],
    commonMistakes: [
      "I never have met her (×) → I have never met her (✓)",
      "Did you ever visit them? (×) → Have you ever visited them? (✓)",
      "She has never forgive him (×) → She has never forgiven him (✓)",
    ],
    topic: TOPIC,
  }),
  buildGrammarRef({
    structure: "Conjunctions: because, when, although",
    explanation: "Use because to give a reason, when to show time, and although to show contrast. At A2, keep clauses short and clear.",
    examples: [
      "I apologised because I was late.",
      "When we argue, we usually forgive each other quickly.",
      "Although we are neighbours, we are also close friends.",
    ],
    commonMistakes: [
      "I was late because of I missed the bus (×) → I was late because I missed the bus (✓)",
      "Although it was raining, but we went out (×) → Although it was raining, we went out (✓)",
      "When I will arrive, call me (×) → When I arrive, call me (✓)",
    ],
    topic: TOPIC,
  }),
];

const opinionPassage = buildPassage({
  title: "Online Advice: Neighbours and Noise",
  text: "Posted by Linh, age 13\n\nLast week my neighbour played loud music every evening. I felt angry because I couldn't do my homework. My mum said I should talk to him politely first.\n\nI knocked on his door when he came home from work. I explained the problem and he apologised immediately. He didn't know the music was so loud in my room.\n\nIn my opinion, good neighbours communicate before they argue. Although we are different ages, we now have a better relationship. I have never had a serious argument with a neighbour before, but this experience taught me to speak up calmly.\n\nWhat do you think? Should young people always tell an adult first?",
});

const partyScript = buildListeningScript({
  title: "Birthday Party Invitation",
  setting: "Phone call between two friends",
  speakers: [
    { name: "Hana", role: "friend" },
    { name: "Tom", role: "friend" },
  ],
  lines: [
    { speaker: "Hana", text: "Hi Tom! I'm calling about my birthday party on Saturday." },
    { speaker: "Tom", text: "Oh great! Is it at your house?" },
    { speaker: "Hana", text: "No, we're having it in the park near the statue. The invitation says four o'clock." },
    { speaker: "Tom", text: "Can I bring my neighbour, Minh? He's new in our street." },
    { speaker: "Hana", text: "Of course! Tell him to bring a football. We'll play before the cake." },
    { speaker: "Tom", text: "Perfect. I'll congratulate you again on Saturday!" },
  ],
  audioNotes: "Friendly teenage voices, clear pace. Approx. 35 seconds.",
});

const apologyScript = buildListeningScript({
  title: "Apologising to a Colleague",
  setting: "Office break room",
  speakers: [
    { name: "Mrs Pham", role: "manager" },
    { name: "David", role: "colleague" },
  ],
  lines: [
    { speaker: "David", text: "Mrs Pham, can I speak to you for a minute?" },
    { speaker: "Mrs Pham", text: "Yes, David. What's wrong?" },
    { speaker: "David", text: "I want to apologise because I was late to the meeting this morning." },
    { speaker: "Mrs Pham", text: "Thank you for telling me. Why were you late?" },
    { speaker: "David", text: "My bus broke down. I have never been late before." },
    { speaker: "Mrs Pham", text: "I understand. Please call when that happens. I trust you will try harder." },
    { speaker: "David", text: "I will. Thank you for your support." },
  ],
  audioNotes: "Calm adult voices, polite tone. Approx. 40 seconds.",
});

export default {
  unit: {
    learningObjectives: [
      "Use core personal relationship vocabulary at A2 level.",
      "Use present perfect with ever/never to talk about experiences with friends and neighbours.",
      "Use because, when and although in sentences about relationships.",
      "Understand opinions in short online texts.",
      "Listen to short extracts and identify main ideas about invitations and apologies.",
      "Write a short message to apologise or accept an invitation.",
      "Answer interview questions about friendships and neighbours.",
    ],
  },
  vocabularyBank,
  grammarReference,
  lessons: {
    vocabulary: {
      slug: "vocab-relationship-words",
      title: "Lesson 1: Personal Relationship Words",
      learningObjective: "Recognise and understand twelve personal relationship words at KET A2 level.",
      estimatedMinutes: 22,
      exercises: [
        buildExercise({
          slug: "vocab-relationship-learn",
          title: "Learn: Relationship Word Match",
          instructions: "Read each sentence. Choose the best word.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({ questionText: "A person who lives next to your house is your _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Neighbour (hàng xóm) là người sống cạnh nhà bạn.", correct: "neighbour", wrong: ["colleague", "invitation"], distractorNotes: ["Works with you, not next door", "A message to come to an event"] }),
            buildMcq({ questionText: "A card or message asking you to come to a party is an _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Invitation (lời mời) mời bạn đến sự kiện.", correct: "invitation", wrong: ["relationship", "trust"], distractorNotes: ["Connection between people", "To believe someone"] }),
            buildMcq({ questionText: "When you say sorry for a mistake, you _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Apologise (xin lỗi) khi bạn nhận lỗi.", correct: "apologise", wrong: ["congratulate", "argue"], distractorNotes: ["Say well done", "Have an angry discussion"] }),
            buildMcq({ questionText: "When your friend passes an exam, you _____ them.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Congratulate (chúc mừng) khi ai đó thành công.", correct: "congratulate", wrong: ["forgive", "trust"], distractorNotes: ["Stop being angry", "Believe someone is honest"] }),
            buildMcq({ questionText: "The connection between two people is their _____.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Relationship (mối quan hệ) mô tả cách hai người liên kết.", correct: "relationship", wrong: ["friendship", "neighbour"], distractorNotes: ["Specifically between friends", "A person, not a connection"] }),
            buildMcq({ questionText: "If you believe someone will not hurt you, you _____ them.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Trust (tin tưởng) nghĩa là tin người đó trung thực.", correct: "trust", wrong: ["argue", "support"], distractorNotes: ["Disagree angrily", "Help someone"] }),
          ],
        }),
        buildExercise({
          slug: "vocab-relationship-matching",
          title: "Practice: Match the Pairs",
          instructions: "Match each word on the left with the correct meaning on the right.",
          exerciseType: "matching",
          sortOrder: 1,
          questions: [
            buildMatching({
              questionText: "Match the relationship words to their meanings.",
              skillTag: "vocabulary",
              topicTag: TOPIC,
              explanation: "Mỗi từ khớp với một nghĩa rõ ràng. Argue và forgive thường đi cùng nhau trong mâu thuẫn.",
              pairs: [
                { left: "argue", right: "to disagree angrily with someone" },
                { left: "forgive", right: "to stop being angry with someone" },
                { left: "friendship", right: "a close bond between friends" },
                { left: "colleague", right: "someone you work with" },
              ],
            }),
          ],
        }),
        buildExercise({
          slug: "vocab-relationship-check",
          title: "Check: Vocab Quiz",
          instructions: "No hints — choose the best answer for each question.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          qualityScores: { quality: 0.91, difficulty: 0.32, curriculumAlignment: 0.96, needsReview: false },
          questions: [
            buildMcq({ questionText: "She felt _____ when her best friend spent time with someone else.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Jealous (ghen tị) khi lo bạn bè quan tâm người khác hơn.", correct: "jealous", wrong: ["trust", "support"], distractorNotes: ["Positive feeling", "To help"], difficultyRating: 2 }),
            buildMcq({ questionText: "Good friends always _____ each other in difficult times.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Support (hỗ trợ) nghĩa là giúp đỡ lẫn nhau.", correct: "support", wrong: ["argue", "apologise"], distractorNotes: ["Negative action", "Say sorry"], difficultyRating: 2 }),
            buildMcq({ questionText: "After they argued, he asked her to _____ him.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Forgive (tha thứ) sau khi cãi nhau và xin lỗi.", correct: "forgive", wrong: ["congratulate", "trust"], distractorNotes: ["Celebrate success", "Believe — wrong context after argument"], difficultyRating: 2 }),
            buildMcq({ questionText: "Their _____ grew stronger after they helped each other every day.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Friendship (tình bạn) phát triển khi bạn hỗ trợ nhau.", correct: "friendship", wrong: ["invitation", "neighbour"], distractorNotes: ["A party message", "A person next door"], difficultyRating: 3 }),
            buildMcq({ questionText: "My dad's _____ from work came to our barbecue last Sunday.", skillTag: "vocabulary", topicTag: TOPIC, explanation: "Colleague (đồng nghiệp) là người làm cùng nơi.", correct: "colleague", wrong: ["neighbour", "relationship"], distractorNotes: ["Lives nearby", "Abstract connection word"], difficultyRating: 3 }),
          ],
        }),
        buildExercise({
          slug: "vocab-relationship-apply",
          title: "Apply: Words in Sentences",
          instructions: "Complete each sentence with the correct word from the unit.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.36, curriculumAlignment: 0.96, needsReview: false },
          questions: [
            buildGapFill({
              questionText: "Complete: I got an [0] to Hana's party. | Our [1] waters our plants when we travel. | Please [2] — I broke your cup.",
              skillTag: "vocabulary",
              topicTag: TOPIC,
              explanation: "invitation (lời mời); neighbour (hàng xóm); apologise (xin lỗi).",
              template: "I got an [0] to Hana's party. Our [1] waters our plants when we travel. Please [2] — I broke your cup.",
              correctAnswers: ["invitation", "neighbour", "apologise"],
              acceptableAnswers: [["invitation", "Invitation"], ["neighbour", "neighbor", "Neighbour", "Neighbor"], ["apologise", "apologize", "Apologise", "Apologize"]],
              difficultyRating: 2,
            }),
            buildGapFill({
              questionText: "Complete: I [0] my sister on her new job. | We should [1] each other and not [2] about small things.",
              skillTag: "vocabulary",
              topicTag: TOPIC,
              explanation: "congratulated (chúc mừng); trust (tin tưởng); argue (cãi nhau).",
              template: "I [0] my sister on her new job. We should [1] each other and not [2] about small things.",
              correctAnswers: ["congratulated", "trust", "argue"],
              acceptableAnswers: [["congratulated", "Congratulated"], ["trust", "Trust"], ["argue", "Argue"]],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    grammar: {
      slug: "grammar-relationship-experience",
      title: "Lesson 2: Experience and Connecting Ideas",
      learningObjective: "Use present perfect with ever/never and conjunctions because, when and although to talk about relationships.",
      estimatedMinutes: 24,
      exercises: [
        buildExercise({
          slug: "grammar-experience-learn",
          title: "Learn: Ever, Never and Conjunctions",
          instructions: "Choose the correct word or phrase to complete each sentence.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({ questionText: "I have _____ argued with my best friend.", skillTag: "grammar", topicTag: TOPIC, explanation: "Never + present perfect: have never argued.", correct: "never", wrong: ["ever", "since"], distractorNotes: ["Used in questions", "Needs a time point"] }),
            buildMcq({ questionText: "_____ you ever congratulated a friend online?", skillTag: "grammar", topicTag: TOPIC, explanation: "Have you ever...? — câu hỏi kinh nghiệm.", correct: "Have", wrong: ["Did", "Are"], distractorNotes: ["Past simple question", "Present continuous"] }),
            buildMcq({ questionText: "I apologised _____ I was late to the party.", skillTag: "grammar", topicTag: TOPIC, explanation: "Because + lý do: I was late.", correct: "because", wrong: ["although", "when"], distractorNotes: ["Shows contrast", "Shows time, not reason"] }),
            buildMcq({ questionText: "_____ we are neighbours, we are also close friends.", skillTag: "grammar", topicTag: TOPIC, explanation: "Although + contrast: neighbours but also friends.", correct: "Although", wrong: ["Because", "When"], distractorNotes: ["Gives reason, not contrast", "Shows time"] }),
            buildMcq({ questionText: "_____ I saw the invitation, I called my friend immediately.", skillTag: "grammar", topicTag: TOPIC, explanation: "When + thời điểm: at the moment I saw it.", correct: "When", wrong: ["Although", "Because"], distractorNotes: ["Contrast", "Reason"] }),
            buildMcq({ questionText: "She has _____ forgiven him after the argument.", skillTag: "grammar", topicTag: TOPIC, explanation: "Present perfect: has forgiven (past participle).", correct: "forgiven", wrong: ["forgive", "forgave"], distractorNotes: ["Base form after has", "Past simple"] }),
          ],
        }),
        buildExercise({
          slug: "grammar-experience-practice",
          title: "Practice: Complete the Grammar",
          instructions: "Fill in each gap with the correct form.",
          exerciseType: "gap_fill",
          sortOrder: 1,
          questions: [
            buildGapFill({
              questionText: "Complete: I [0] never had a serious argument with my neighbour. | [1] you ever trusted a new friend quickly? | She apologised [2] she forgot the invitation.",
              skillTag: "grammar",
              topicTag: TOPIC,
              explanation: "have (present perfect); Have (question); because (reason).",
              template: "I [0] never had a serious argument with my neighbour. [1] you ever trusted a new friend quickly? She apologised [2] she forgot the invitation.",
              correctAnswers: ["have", "Have", "because"],
              acceptableAnswers: [["have", "Have"], ["Have", "have"], ["because", "Because"]],
            }),
            buildGapFill({
              questionText: "Complete: [0] they argue, they usually forgive each other. | [1] we live on the same street, we don't know each other well. | He has [2] congratulated a colleague online.",
              skillTag: "grammar",
              topicTag: TOPIC,
              explanation: "When (time); Although (contrast); never (experience).",
              template: "[0] they argue, they usually forgive each other. [1] we live on the same street, we don't know each other well. He has [2] congratulated a colleague online.",
              correctAnswers: ["When", "Although", "never"],
              acceptableAnswers: [["When", "when"], ["Although", "although"], ["never", "Never"]],
            }),
          ],
        }),
        buildExercise({
          slug: "grammar-experience-check",
          title: "Check: Grammar Challenge",
          instructions: "Choose the correct answer. Think carefully.",
          exerciseType: "multiple_choice",
          sortOrder: 2,
          qualityScores: { quality: 0.92, difficulty: 0.38, curriculumAlignment: 0.97, needsReview: false },
          questions: [
            buildMcq({ questionText: "My neighbour and I have known each other _____ five years.", skillTag: "grammar", topicTag: TOPIC, explanation: "For + khoảng thời gian với present perfect.", correct: "for", wrong: ["since", "when"], distractorNotes: ["Since + point in time", "Conjunction for time clause"], difficultyRating: 2 }),
            buildMcq({ questionText: "_____ I was jealous, I didn't argue with my friend.", skillTag: "grammar", topicTag: TOPIC, explanation: "Although + contrast: felt jealous but stayed calm.", correct: "Although", wrong: ["Because", "When"], distractorNotes: ["Would mean jealousy caused no argument", "Time, not contrast"], difficultyRating: 2 }),
            buildMcq({ questionText: "Have you ever _____ to a neighbour for playing loud music?", skillTag: "grammar", topicTag: TOPIC, explanation: "Have you ever apologised — past participle after ever.", correct: "apologised", wrong: ["apologise", "apologising"], distractorNotes: ["Base form after have", "Gerund form"], difficultyRating: 3 }),
            buildMcq({ questionText: "I called her _____ I wanted to congratulate her.", skillTag: "grammar", topicTag: TOPIC, explanation: "Because gives the reason for calling.", correct: "because", wrong: ["although", "when"], distractorNotes: ["Contrast not needed", "When focuses on time of calling"], difficultyRating: 3 }),
          ],
        }),
        buildExercise({
          slug: "grammar-relationship-order",
          title: "Apply: Build the Sentence",
          instructions: "Put the words in the correct order to make a sentence.",
          exerciseType: "sentence_ordering",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.4, curriculumAlignment: 0.96, needsReview: false },
          questions: [
            sentenceOrder("Make a sentence: I / have never / argued / with / my neighbour.", "I have never argued with my neighbour. — present perfect + never.", ["I", "have never", "argued", "with", "my neighbour."]),
            sentenceOrder("Make a sentence: Although / we argue / sometimes, / we / always / forgive / each other.", "Although we argue sometimes, we always forgive each other. — although + contrast.", ["Although", "we argue", "sometimes,", "we", "always", "forgive", "each other."], "grammar", 2),
            sentenceOrder("Make a sentence: I / apologised / because / I / was / late.", "I apologised because I was late. — because + reason.", ["I", "apologised", "because", "I", "was", "late."], "grammar", 3),
          ],
        }),
      ],
    },
    reading: {
      slug: "reading-neighbour-opinion",
      title: "Lesson 3: Neighbour Opinion Text",
      learningObjective: "Read a short online post and understand opinions, details and vocabulary in context.",
      estimatedMinutes: 23,
      exercises: [
        buildReadingExercise({
          slug: "reading-opinion-learn",
          title: "Learn: Read the Online Post",
          instructions: "Read the post carefully. Answer the detail questions.",
          sortOrder: 0,
          passage: opinionPassage,
          questions: [
            buildMcq({ questionText: "Why did Linh feel angry at first?", skillTag: "reading", topicTag: TOPIC, explanation: "Loud music stopped her doing homework.", correct: "Her neighbour played loud music", wrong: ["She lost an invitation", "Her colleague was late"], distractorNotes: ["Not mentioned", "Not the problem"], assessmentType: "detail" }),
            buildMcq({ questionText: "What did Linh's mum suggest?", skillTag: "reading", topicTag: TOPIC, explanation: "Talk to him politely first.", correct: "Talk to the neighbour politely", wrong: ["Call the police", "Argue loudly"], distractorNotes: ["Not suggested", "Opposite of politely"], assessmentType: "detail" }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-opinion-practice",
          title: "Practice: Words in the Post",
          instructions: "Read the post again. Answer about vocabulary and meaning.",
          sortOrder: 1,
          passage: opinionPassage,
          difficulty: 0.3,
          questions: [
            buildMcq({ questionText: "In the post, 'speak up calmly' means to _____.", skillTag: "reading", topicTag: TOPIC, explanation: "Nói rõ vấn đề một cách bình tĩnh, không la lớn.", correct: "say what you think in a calm way", wrong: ["shout as loudly as possible", "write an invitation"], distractorNotes: ["Opposite of calmly", "Wrong context"], difficultyRating: 2, assessmentType: "vocabulary_in_context" }),
            buildMcq({ questionText: "Why does Linh think the neighbour apologised quickly?", skillTag: "reading", topicTag: TOPIC, explanation: "He didn't know the music was so loud in her room.", correct: "He didn't realise the music was loud for her", wrong: ["He was jealous of her", "He wanted an invitation"], distractorNotes: ["Not mentioned", "Not in the text"], difficultyRating: 2, assessmentType: "inference" }),
          ],
        }),
        buildReadingExercise({
          slug: "reading-opinion-check",
          title: "Check: Main Idea and Order",
          instructions: "Read the post one more time. These questions need careful thinking.",
          sortOrder: 2,
          passage: opinionPassage,
          difficulty: 0.35,
          questions: [
            buildMcq({ questionText: "What is Linh's main opinion about neighbours?", skillTag: "reading", topicTag: TOPIC, explanation: "Good neighbours communicate before they argue.", correct: "They should talk politely before arguing", wrong: ["Young people should never speak to neighbours", "Neighbours should always play music"], distractorNotes: ["Opposite of her advice", "Not her view"], assessmentType: "main_idea" }),
            buildMcq({ questionText: "Put the events in order: (1) Neighbour apologises (2) Linh talks to neighbour (3) Loud music problem", skillTag: "reading", topicTag: TOPIC, explanation: "Problem → talk → apology.", correct: "3 → 2 → 1", wrong: ["1 → 2 → 3", "2 → 3 → 1"], distractorNotes: ["Apology before talk", "Talk before problem"], difficultyRating: 2, assessmentType: "sequencing" }),
          ],
        }),
        buildExercise({
          slug: "reading-opinion-apply",
          title: "Apply: Match Facts from the Post",
          instructions: "Use what you read. Match each item to the correct fact.",
          exerciseType: "matching",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.32, curriculumAlignment: 0.95, needsReview: false },
          content: { passage: opinionPassage },
          questions: [
            buildMatching({
              questionText: "Match each topic to a fact from the post.",
              skillTag: "reading",
              topicTag: TOPIC,
              explanation: "Mỗi mục khớp với thông tin cụ thể trong bài đăng của Linh.",
              pairs: [
                { left: "The problem", right: "Loud music every evening" },
                { left: "Linh's action", right: "Knocked on the neighbour's door" },
                { left: "Neighbour's reaction", right: "Apologised immediately" },
                { left: "Linh's experience", right: "Never had a serious argument before" },
              ],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    listening: {
      slug: "listening-relationship-extracts",
      title: "Lesson 4: Invitations and Apologies",
      learningObjective: "Listen to short extracts about invitations and apologies and identify main ideas and details.",
      estimatedMinutes: 22,
      exercises: [
        buildListeningExercise({
          slug: "listening-party-learn",
          title: "Learn: Birthday Party Invitation",
          instructions: "Listen to the phone call. Answer the first two questions.",
          sortOrder: 0,
          script: partyScript,
          answerKey: { q1: "birthday party Saturday", q2: "park near statue 4pm" },
          questions: [
            buildMcq({ questionText: "What is the call mainly about?", skillTag: "listening", topicTag: TOPIC, explanation: "Hana calls about her birthday party on Saturday.", correct: "A birthday party invitation", wrong: ["An apology for being late", "A problem with a colleague"], distractorNotes: ["Different script", "Office topic"] }),
            buildMcq({ questionText: "Where is the party?", skillTag: "listening", topicTag: TOPIC, explanation: "In the park near the statue.", correct: "In the park near the statue", wrong: ["At Hana's house", "At Tom's neighbour's house"], distractorNotes: ["Tom asked but Hana said no", "Minh is invited, not host"] }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-party-practice",
          title: "Practice: More from the Invitation Call",
          instructions: "Listen again to the same call. Answer the next questions.",
          sortOrder: 1,
          script: partyScript,
          answerKey: { q1: "bring neighbour Minh", q2: "bring a football" },
          questions: [
            buildMcq({ questionText: "Who does Tom want to bring?", skillTag: "listening", topicTag: TOPIC, explanation: "His neighbour Minh, who is new in the street.", correct: "His neighbour Minh", wrong: ["His colleague David", "Mrs Pham"], distractorNotes: ["From apology script", "Not mentioned"], difficultyRating: 2 }),
            buildMcq({ questionText: "What should Minh bring?", skillTag: "listening", topicTag: TOPIC, explanation: "Tell him to bring a football.", correct: "A football", wrong: ["An invitation card", "A cake"], distractorNotes: ["Topic of call, not to bring", "They will have cake at party"], difficultyRating: 2 }),
          ],
        }),
        buildListeningExercise({
          slug: "listening-apology-check",
          title: "Check: Apologising at Work",
          instructions: "Listen to a new conversation. Choose the correct answer.",
          sortOrder: 2,
          script: apologyScript,
          answerKey: { q1: "apologise for being late", q2: "bus broke down", q3: "call when it happens" },
          difficulty: 0.32,
          questions: [
            buildMcq({ questionText: "Why does David want to speak to Mrs Pham?", skillTag: "listening", topicTag: TOPIC, explanation: "He wants to apologise for being late.", correct: "To apologise for being late", wrong: ["To invite her to a party", "To congratulate her"], distractorNotes: ["Party script topic", "No celebration mentioned"] }),
            buildMcq({ questionText: "Why was David late?", skillTag: "listening", topicTag: TOPIC, explanation: "His bus broke down.", correct: "His bus broke down", wrong: ["He argued with a neighbour", "He lost an invitation"], distractorNotes: ["Not mentioned", "Not the reason"], difficultyRating: 2 }),
            buildMcq({ questionText: "What does Mrs Pham ask David to do next time?", skillTag: "listening", topicTag: TOPIC, explanation: "Please call when that happens.", correct: "Call her when he will be late", wrong: ["Forgive his colleague", "Never trust the bus"], distractorNotes: ["Not requested", "Not said"], difficultyRating: 2 }),
          ],
        }),
        buildExercise({
          slug: "listening-party-apply",
          title: "Apply: Match What You Heard",
          instructions: "Listen again to the party invitation call. Match each item to the correct detail.",
          exerciseType: "matching",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.3, curriculumAlignment: 0.95, needsReview: false },
          content: { script: partyScript },
          questions: [
            buildMatching({
              questionText: "Match each item from the invitation call.",
              skillTag: "listening",
              topicTag: TOPIC,
              explanation: "Mỗi mục khớp với chi tiết Hana và Tom nói trong cuộc gọi.",
              pairs: [
                { left: "Party day", right: "Saturday" },
                { left: "Party time", right: "Four o'clock" },
                { left: "Tom's extra guest", right: "Neighbour Minh" },
              ],
              difficultyRating: 2,
              points: 3,
            }),
          ],
        }),
      ],
    },
    writing: {
      slug: "writing-relationship-message",
      title: "Lesson 5: Apologise or Accept",
      learningObjective: "Write a short message apologising or accepting an invitation using relationship vocabulary and conjunctions.",
      estimatedMinutes: 25,
      exercises: [
        buildExercise({
          slug: "writing-message-learn",
          title: "Learn: Message Phrases",
          instructions: "Complete each gap with a word from the unit.",
          exerciseType: "gap_fill",
          sortOrder: 0,
          questions: [
            buildGapFill({
              questionText: "Complete: Hi Mai, | I'm sorry — I need to [0]. | I was late [1] my bus broke down. | Thank you for the [2].",
              skillTag: "writing",
              topicTag: TOPIC,
              explanation: "apologise (xin lỗi); because (lý do); invitation (lời mời).",
              template: "Hi Mai,\n\nI'm sorry — I need to [0]. I was late [1] my bus broke down.\n\nThank you for the [2].",
              correctAnswers: ["apologise", "because", "invitation"],
              acceptableAnswers: [["apologise", "apologize", "Apologise", "Apologize"], ["because", "Because"], ["invitation", "Invitation"]],
            }),
          ],
        }),
        buildExercise({
          slug: "writing-message-order-practice",
          title: "Practice: Build Message Sentences",
          instructions: "Put the words in the correct order to make correct sentences for a message.",
          exerciseType: "sentence_ordering",
          sortOrder: 1,
          questions: [
            sentenceOrder("Make a sentence: I / have never / missed / your / party / before.", "I have never missed your party before. — present perfect experience.", ["I", "have never", "missed", "your", "party", "before."], "writing", 2),
            sentenceOrder("Make a sentence: Although / I / was / busy, / I / will / come.", "Although I was busy, I will come. — although + contrast in a reply.", ["Although", "I", "was", "busy,", "I", "will", "come."], "writing", 2),
          ],
        }),
        buildWritingCheck({
          slug: "writing-message-check",
          topicTag: TOPIC,
          title: "Check: Apology or Invitation Reply",
          instructions: "Write a short message. Write at least 25 words.",
          sortOrder: 2,
          taskDescription: "Your friend Hana sent you an invitation to her birthday party in the park on Saturday. You were late to school today and want to apologise to your teacher in a message. Write ONE short message — choose either replying to Hana OR apologising to your teacher.",
          prompts: [
            "Say who you are writing to and why.",
            "Use because, when or although in at least one sentence.",
            "Use at least two unit words (e.g. invitation, apologise, neighbour, congratulate).",
            "End the message politely.",
          ],
          minWords: 25,
          modelAnswerText: "Hi Hana,\n\nThank you for the invitation to your party on Saturday. Although I have a football match in the morning, I will come to the park at four o'clock. I have never been to a party near the statue before!\n\nSee you,\nLinh",
          rubric: {
            grammar: { weight: 0.25, criteria: "Uses present perfect with ever/never or conjunctions because/when/although correctly." },
            vocabulary: { weight: 0.25, criteria: "Uses relationship words (invitation, apologise, neighbour, trust) appropriately." },
            organization: { weight: 0.25, criteria: "Message has greeting, clear purpose and polite closing." },
            taskAchievement: { weight: 0.25, criteria: "Replies to invitation OR apologises clearly; at least 25 words." },
          },
          successCriteria: [
            "At least 25 words",
            "Clear purpose (apology or invitation reply)",
            "Uses because, when or although",
            "Polite opening and closing",
            "Uses at least two unit vocabulary words",
          ],
          autoCheckKeywords: ["dear", "hi", "invitation", "apologise", "apologize", "because", "although", "when", "thank", "party", "friend"],
        }),
        buildExercise({
          slug: "writing-message-apply",
          title: "Apply: Complete the Message Frames",
          instructions: "Complete the message frames with the correct unit words.",
          exerciseType: "gap_fill",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.34, curriculumAlignment: 0.95, needsReview: false },
          questions: [
            buildGapFill({
              questionText: "Complete: Dear Mrs Pham, | I [0] because I was late today. | [1] the bus broke down, I couldn't call. | I hope you can [2] me.",
              skillTag: "writing",
              topicTag: TOPIC,
              explanation: "apologise; Because/When (Because fits reason); forgive.",
              template: "Dear Mrs Pham,\n\nI [0] because I was late today. [1] the bus broke down, I couldn't call.\n\nI hope you can [2] me.",
              correctAnswers: ["apologise", "Because", "forgive"],
              acceptableAnswers: [["apologise", "apologize", "Apologise", "Apologize"], ["Because", "because", "When", "when"], ["forgive", "Forgive", "trust", "Trust"]],
              difficultyRating: 2,
            }),
          ],
        }),
      ],
    },
    speaking: {
      slug: "speaking-relationship-interview",
      title: "Lesson 6: Talk About Relationships",
      learningObjective: "Answer interview questions about friends, neighbours and relationships using unit vocabulary and grammar.",
      estimatedMinutes: 20,
      exercises: [
        buildExercise({
          slug: "speaking-relationship-learn",
          title: "Learn: Choose the Best Reply",
          instructions: "Imagine an examiner asks you a question. Choose the best answer.",
          exerciseType: "multiple_choice",
          sortOrder: 0,
          questions: [
            buildMcq({ questionText: "Examiner: Do you know your neighbours well? You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Mô tả mối quan hệ với hàng xóm — câu trả lời tự nhiên A2.", correct: "Yes, we often chat when we see each other.", wrong: ["Yes, I invitation them every day.", "Yes, I argue my neighbour is a door."], distractorNotes: ["Wrong word class", "Nonsense sentence"] }),
            buildMcq({ questionText: "Examiner: Have you ever congratulated a friend online? You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Present perfect + ever: Yes, I have...", correct: "Yes, I have congratulated friends on social media.", wrong: ["Yes, I never congratulate friends online.", "Yes, I congratulate since yesterday."], distractorNotes: ["Never contradicts yes", "Since needs present perfect duration"] }),
            buildMcq({ questionText: "Examiner: What do you do when you argue with a friend? You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Forgive + apologise — giải quyết mâu thuẫn.", correct: "We usually apologise and forgive each other.", wrong: ["We usually invitation and trust each other.", "We usually jealous and colleague each other."], distractorNotes: ["Wrong verbs", "Wrong word classes"] }),
          ],
        }),
        buildExercise({
          slug: "speaking-relationship-practice",
          title: "Practice: Best Response",
          instructions: "Choose the best phrase you would say in each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 1,
          questions: [
            buildMcq({ questionText: "Examiner: Why is trust important in a friendship? You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Because + lý do — trust helps you share secrets.", correct: "Because you can tell your friend private things.", wrong: ["Because you can argue every day.", "Because you need an invitation to school."], distractorNotes: ["Negative, not a reason for trust", "Wrong context"], difficultyRating: 2 }),
            buildMcq({ questionText: "Examiner: When do you usually see your colleagues? You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "When + thời gian: at work on weekdays.", correct: "When I help my mum at her shop on Saturdays.", wrong: ["Although I see colleagues at the park statue.", "Because I congratulate colleagues at midnight."], distractorNotes: ["Although wrong connector", "Unnatural time"], difficultyRating: 2 }),
            buildMcq({ questionText: "Examiner: Tell me about a good friendship. You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Support + friendship — mô tả tình bạn tích cực.", correct: "We support each other although we sometimes argue.", wrong: ["We jealous each other although we trust.", "We neighbour each other when we forgive."], distractorNotes: ["Wrong adjective as verb", "Nonsense"], difficultyRating: 2 }),
          ],
        }),
        buildSpeakingCheck({
          slug: "speaking-relationship-interview",
          topicTag: TOPIC,
          title: "Check: Relationships Interview",
          instructions: "Answer the examiner's questions about friends and neighbours. Speak for up to two minutes.",
          sortOrder: 2,
          prompt: "The examiner will ask you about your friends, neighbours and how you solve problems in relationships.",
          sceneDescription: "Two teenagers talking in a park; one holds a party invitation, the other waves to a neighbour across the street.",
          followUpQuestions: [
            "Do you know your neighbours well?",
            "Have you ever argued with a friend?",
            "How do you usually congratulate your friends?",
            "Who do you trust with your secrets?",
            "When do you apologise to someone?",
            "Although friends sometimes disagree, how do you stay friends?",
          ],
          suggestedAnswers: [
            "Yes, our neighbour often helps us and we trust her.",
            "Yes, I have argued with my cousin about games, but we forgive each other.",
            "I congratulate them in person or send a message online.",
            "I trust my best friend because she never tells my secrets.",
            "I apologise when I am late or say something unkind.",
            "We support each other and talk calmly because friendship is important.",
          ],
          assessmentCriteria: {
            pronunciation: "Key words (neighbour, invitation, apologise, relationship, trust) are understandable.",
            fluency: "Responds with phrases or short sentences without long silences.",
            grammar: "Uses present perfect with ever/never or conjunctions because/when/although in at least two answers.",
            vocabulary: "Uses at least four different unit words correctly.",
          },
          maxDurationSeconds: 120,
        }),
        buildExercise({
          slug: "speaking-relationship-apply",
          title: "Apply: Situational Responses",
          instructions: "Choose the best thing to say in each situation.",
          exerciseType: "multiple_choice",
          sortOrder: 3,
          qualityScores: { quality: 0.9, difficulty: 0.3, curriculumAlignment: 0.95, needsReview: false },
          questions: [
            buildMcq({ questionText: "Your friend is jealous because you went to a party without them. You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Apologise + invitation for next time — xử lý tình huống nhạy cảm.", correct: "I'm sorry. I will invite you next time because our friendship is important.", wrong: ["I'm sorry. I will argue you next time because I am jealous.", "I'm sorry. I will colleague you next time at the statue."], distractorNotes: ["Illogical", "Wrong vocabulary"], difficultyRating: 2 }),
            buildMcq({ questionText: "A new neighbour moves in. You want to be friendly. You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Chào hàng xóm mới — câu đơn giản lịch sự.", correct: "Hello! Welcome to the street. I'm your neighbour next door.", wrong: ["Hello! Welcome to the forgive. I'm your invitation next door.", "Hello! Welcome to the argue. I'm your trust next door."], distractorNotes: ["Nonsense", "Nonsense"], difficultyRating: 2 }),
            buildMcq({ questionText: "The examiner asks: Have you ever had to forgive a friend? You say:", skillTag: "speaking", topicTag: TOPIC, explanation: "Present perfect experience + forgive.", correct: "Yes, I have forgiven a friend after we argued about a game.", wrong: ["Yes, I have forgive a friend although we invitation.", "Yes, I never have forgiven although I always argue happily."], distractorNotes: ["Wrong form", "Contradictory"], difficultyRating: 3 }),
          ],
        }),
      ],
    },
  },
};
